### ISSUE TITLE
S3 Static Website Hosting

### ISSUE THREAD

**Issue by Jumblemuddle** [aws/aws-cdk#632]
Currently an S3 bucket can't be configured with a [`WebsiteConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-websiteconfiguration).
Is there any sort of escape hatch to do this or would I need to create some sort of custom resource?

I know I could create CloudFront distribution, but I'm not looking to do that at the moment.

**Comment by eladb** [comment]
Yes, it's a known missing feature. Currently, the only way to work around these types of gaps is to override the `toCloudFormation` method in your `Stack` and "patch" the synthesized template.

See #606 for an example on how to implement something like this and a discussion on possible approaches we are considering.

**Comment by rix0rrr** [comment]
@eladb we now have https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-s3-deployment.html , so that's great start.

Is there already a way to configure S3 Bucket/CloudFront distribution to host those files, or is that still going down to L1 level?

**Comment by eladb** [comment]
There is a cloud front L2 which I believe needs quite a lot of work. Also, we need to add support for blue/green deployments of static content as part of s3-deployment

**Comment by john-shaskin** [comment]
Hey, @Jumblemuddle, are you just looking to set up an s3 bucket as a static website, or something more involved? I've currently been able to set up a publicly readable s3 site with the following snippet.
```
const websiteBucket = new s3.Bucket(this, 'MyStaticWebsite', {
  websiteIndexDocument: 'index.html',
  websiteErrorDocument: 'error.html'
});
websiteBucket.grantPublicAccess('*', 's3:GetObject');
```

**Comment by eladb** [comment]
Still relevant

**Comment by hoegertn** [comment]
I have an S3 Website Hosting construct in my library. Maybe this could be integrated: https://github.com/taimos/cdk-constructs/blob/master/lib/web/single-page-app.ts

What do you think?

**Comment by spaceemotion** [comment]
@hoegertn Fancy seeing you here. You've linked me on the AWS Community Day to your stack.

The only "problem" I have with it is that it tends to redirect me to /index.html in almost all error cases.

Since I am using a Vue SPA, the router picks it up and simply shows a blank page. Redirecting to "/" so the browser can fetch the index.html on its own would be better (haven't figured out how to configure the CDK code for that yet though).

Otherwise it works as expected, having a [blue green deployment](https://github.com/aws/aws-cdk/issues/954) would be amazing 👍

**Comment by hoegertn** [comment]
It is not redirecting but returning the content of `index.html` which is what e.g. Angular recommends for their routing. But this would be configurable in a generic CDK construct.

**Comment by spaceemotion** [comment]
Hmm, when I enter `http://my-site.com` it redirects me to `https://my-site.com/index.html`

**Comment by hoegertn** [comment]
Yes, Cloudfront is configured with DefaultPage of `index.html` but if you call `foobar.html` you get the same content without redirect. This could all be configurable if needed.

**Comment by btakita** [comment]
How would one use the CDK to configure GET /subdirectory to serve /subdirectory/index.html from the S3 bucket when going through Cloudfront?

**Comment by iliapolo** [comment]
Closing as we now have all the [`WebsiteConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-websiteconfiguration.html) properties: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html

- `websiteErrorDocument`
- `websiteIndexDocument`
- `websiteRedirect`
- `websiteRoutingRules`
