### ISSUE TITLE
'identitySource' needs to accept array of headers in TokenAuthorizer

### ISSUE THREAD

**Issue by rampatina** [aws/aws-cdk#6330]
### Use Case
 Getting below error if I pass array of headers as we need to provide for 'identitySource' in 'TokenAuthorizer'.
`Invalid token source expression: method.request.header.authorization, method.request.header.appkey. The source must be a method request header, matching 'method.request.header.[a-zA-Z0-9._-]+' `

Example token authorizer which we tried:
```
const customAuth1 = new apigw.TokenAuthorizer(this, 'customAuthorizer1', {
      handler: customAuthorizer.jwtValidatorConstruct.handler,
      identitySource: 'method.request.header.authorization,method.request.header.appkey',
      resultsCacheTtl: resultTtlInSeconds,
      authorizerName: 'customAuthorizer1'
    });
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
From what I can tell from [the documentation](https://docs.aws.amazon.com/apigateway/api-reference/resource/authorizer/#identitySource), token based authorizers don't support only a single header. This is consistent with the [documented input protocol for the lambda function](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-input.html) that backs the token authorizer - the value of the specified header is part of `authorizationToken` key in the function's input.

If you're instead looking for the request authorizer, that's currently being implemented in https://github.com/aws/aws-cdk/pull/5642.
