### ISSUE TITLE
Find a way to signal to users that they should never call "resolve" on tokens

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#634]
Currently, Tokens implement a method `resolve` which is called to resolve the token during synthesis, but users are tempted to invoke this method in various situations (i.e. to "resolve" the value in runtime, to "resolve" the value so they can reason about it, etc).

We should hide this method and/or signal that it shouldn't be called by users.

I propose that:

1. We rename this method `_resolve`.
2. We make it `private` and use duck-typing to identify the token (`public`/`private` is just a typescript annotation, doesn't apply at runtime).

**Comment by rix0rrr** [comment]
Both methods hide it from jsii, so jsii users will never be able to implement a new subclass of `Token`. That seems not ideal.
