### ISSUE TITLE
lambda-nodejs: parcel is too big to bundle

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#6340]
We are looking into releasing the entire AWS CDK as a single library (see https://github.com/aws/aws-cdk-rfcs/issues/6). This basically means that all modules (and their transitive dependencies) will be bundled into a single package.

Recently, we have introduced @aws-cdk/aws-lambda-nodejs as a high level API for writing node.js lambda functions. This construct uses [parcel] in order to bundle all function's dependencies into a single artifact.

The problem is that [parcel] is too big:
- It has [652](http://npm.broofa.com/?q=parcel) transitive dependencies
- 15,558 files
- 100MiB (uncompressed)

This is unrealistic and also introduces an intrinsic security risk posed by including so many dependencies in our project.

### Proposal

Let's use parcel as an [undeclared] peer-dependency. Simply require that users declare parcel in their own `package.json` file. It will also give them more control over which version to use.

**Comment by eladb** [comment]
@jogold what do you think?

**Comment by jogold** [comment]
Yes, peer dependency is fine. What do you mean with [undeclared]?

**Comment by eladb** [comment]
I mean that we won't be able to officially declare it as a "peerDependency" in our package.json because jsii doesn't really know what to do with it, so basically I think at runtime we can do something like `require.resolve('parcel/package.json').version` and check that we are compatible with the version the user installed.

**Comment by jogold** [comment]
OK, let me open a PR for this.

**Comment by eladb** [comment]
Awesome, thanks!
