### ISSUE TITLE
Cannot avoid new policy creation when creating CodeBuild and CodeDeploy

### ISSUE THREAD

**Issue by MinoZhangTR** [aws/aws-cdk#6342]
### The Question

Our team is trying to use CDK to generate a reusable CICD pipeline. and the problem we are facing now is that when we create CodeBuild and CodeDeploy resources through CDK, we are able to reuse an existing role but a new policy is created and attached to the role, which is causing it to reach the limit for the size of policies allowed to be attached to the role.

Error Message when running `cdk deploy *`: Maximum policy size of 10240 bytes exceeded for role *********** .....

Is there a way to avoid creating a new policy to the role when creating CodeBuild and CodeDeploy resources?

### Environment

  - **CDK CLI Version:** 1.23.0
  - **Module Version:**     
    "@aws-cdk/aws-codebuild": "^1.18.0",
    "@aws-cdk/aws-codepipeline": "^1.18.0",
    "@aws-cdk/aws-codepipeline-actions": "^1.18.0"
  - **OS:** Windows 10 
  - **Language:**  TypeScript

**Comment by skinny85** [comment]
Hey @MinoZhangTR ,

what you probably want is to pass the `mutable: false` option when importing the Role - this way, no new Policies will be added to it by the CDK. See: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Role.html#static-from-wbr-role-wbr-arnscope-id-rolearn-options

Hope this helps!

Thanks,
Adam

**Comment by MinoZhangTR** [comment]
@skinny85 I tried this `mutable: false` option when I imported the role, but I am getting error: `policy must be attached to at least one principal: user, group or role`.

My code:
In the definition, we added our roles as List:
```
const roleMap = [
    {
        roleName: 'codePipelineRole',
        roleArn: 'arn:aws:iam::1234567890::role/codepipeline-role',
        mutable: false
    },
    {
        roleName: 'codeDeployRole',
        roleArn: 'arn:aws:iam::1234567890::role/codedeploy-role',
        mutable: false
    },
    {
        roleName: 'codeBuildRole',
        roleArn: 'arn:aws:iam::1234567890:role/codebuild-role',
        mutable: false
    }]
```

In the Import Function, it will import those roles according to each setting in List:
``` 
for ( let role of roles) {
            _roleMap[role.roleName] = Role.fromRoleArn(scope, role.roleName, role.roleArn, {
                mutable: role.mutable
            })
 }
```
It will throw the error when it tries to create codebuild/codedeploy by using those roles.

**Comment by skinny85** [comment]
What version of the CDK you're on?

**Comment by MinoZhangTR** [comment]
@skinny85 Thanks a lot! It works for the latest version.
