### ISSUE TITLE
New PublicHostedZone created on every deployment

### ISSUE THREAD

**Issue by saltman424** [aws/aws-cdk#6349]
When I include a PublicHostedZone in my cdk app, a new hosted zone is created every time I deploy.

The expected behavior would be the same as any other resource: a new hosted zone is created the first time I deploy, the existing hosted zone is then updated each time any of its attributes are changed, and it is deleted when I destroy the stack.

### Reproduction Steps

1. Include a PublicHostedZone in your CDK app
1. Deploy
1. Deploy again
1. Check the Route53 console to see duplicate hosted zones

### Error Log
None

### Environment

  - **CLI Version      :**  1.24.0
  - **Framework Version:** 1.24.0
  - **OS               :** Windows 10
  - **Language         :** TypeScript

### Other
As an additional note, I use a DnsValidatedCertificate with the HostedZone (which creates a RecordSet), so it is possible that this bug only occurs when a RecordSet is present in the HostedZone.

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@saltman424 - thanks for reporting the issue, few questions to help me get to the bottom of it:

* can you share a [gist](https://gist.github.com/) with some sample code?
* Are you changing any attributes in between your deploys or is a new PublicHostedZone created every time regardless?
* What does your CloudFormation stack point to from the console?
* what's the status of the duplicate hosted zones (i.e. `INSYNC`, `PENDING`, etc)

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Comment by saltman424** [comment]
Apologies for the delay. After further debugging, I believe the issue was with CloudFormation deleting resources, not CDK.
