### ISSUE TITLE
Feature Request for Ability to Modify Graph Widget Period

### ISSUE THREAD

**Issue by wsoula** [aws/aws-cdk#6367]
There is not a way to modify the period of a graph widget.

### Use Case

Now that Math Expressions exist I need a way to essentially set the period of a math expression which is not possible in cloudwatch to set directly on the expression so you have to set it at the graph widget level, otherwise it defaults to 300 and you do not get what you want.  The below source is what I get when I set a period of 1 minute on the math expression.  This gives me 1 minute granularity but only gives me results every 5 minutes.  I need to be able to set period to 60 and then I would get the graph widget I want.  Furthermore, with this setup setting the time to 1D for the dashboard results in the graph widget switching to 5 minute granularity.

Source:
```
{
    "view": "timeSeries",
    "title": "Table-ConsumedWriteCapacityUnits/second",
    "region": "us-east-1",
    "metrics": [
        [ { "label": "WCU/s", "expression": "m1/60", "region": "us-east-1" } ],
        [ "AWS/DynamoDB", "ConsumedWriteCapacityUnits", "TableName", "Table", { "period": 60, "stat": "Sum", "visible": false, "id": "m1" } ]
    ],
    "period": 300
}
```

### Proposed Solution

Like the stacked parameter or title, I would like to be able to set the period on the graph widget itself.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I'm afraid I'm not getting the issue from your description. I might be clearer to me if you were to phrase this in the wording of a bug report:

* I'm doing X
* I'm expecting Y to happen
* Z happens instead

As far as I know, while a Math Expression doesn't have a period itself, it has the period of all of its constituent metrics. In your example, 1 minute for the Dynamo metric.

I am unclear how the period on the widget relates to this. If the `period: 300` on the graph wasn't there, you would probably get the granularity you desire, no?

**Comment by rix0rrr** [comment]
BTW you can use `m1/PERIOD(m1)` as an expression to get `capacity/s`.

**Comment by wsoula** [comment]
Sorry for the lack of clarity.

I am trying to display ConsumedWriteCapacityUnits per second on a dashboard with a 23 hour and 59 minute timeframe
I am expecting for the graph to display results every minute at 1 minute granularity
The graph displays results every 5 minutes at a 1 minute granularity

When I say every 5 minutes at a 1 minute granularity I mean the graph only has points every 5 minutes but they are the sum of that minute not the sum of the previous 5 minutes.

I didn't think a math expression took a period either until I was playing with it today and changed the period in the UI from multiple to 1 minute and it produced this source:
```
{
    "metrics": [
        [ { "label": "WCU/s", "expression": "m1/PERIOD(m1)", "region": "us-east-1", "period": 60 } ],
        [ "AWS/DynamoDB", "ConsumedWriteCapacityUnits", "TableName", "Table", { "stat": "Sum", "visible": false, "id": "m1" } ]
    ],
    "view": "timeSeries",
    "title": "Table-ConsumedWriteCapacityUnits/second",
    "region": "us-east-1",
    "period": 60,
    "stat": "Average"
}
```
Changing the period in the math expression to 300 made the graph show results every 5 minutes at 1 minute granularity from every minute at 1 minute granularity.

The second issue I mentioned does not have anything to do with the cdk but cloudwatch itself, which I think makes this issue less severe.  The second issue was:

I am trying to display 1 minute granularity of ConsumedWriteCapacityUnits per second on a graph with a 1 day timeframe
I am expecting the graph to display a result every minute for that minute
The graph displays a result every 5 minutes for that 5 minute period, but editing it shows a graph with a result every 1 minute for that minute.
This is due to the Auto Period override setting that cannot be changed.  Setting it to Do not override provides the expected results
