### ISSUE TITLE
applicationautoscaling: missing PredefinedMetric for Lambda provisioned concurrency

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#6369]
`LambdaProvisionedConcurrencyUtilization` is required but missing.

https://github.com/aws/aws-cdk/blob/b47eccc5ff6b6e72fc53ebd68b52650f2f9f499b/packages/%40aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts#L165-L177

Without this enum, we can't configure props for `scaleToTrackMetric` like this.

```ts
    target.scaleToTrackMetric('PceTracking', {
      targetValue: 1,
      predefinedMetric: applicationautoscaling.PredefinedMetric.LAMBDA_PROVISIONED_CONCURRENCY_UTILIZATION,
    })
```

### Reproduction Steps

missing `LAMBDA_PROVISIONED_CONCURRENCY_UTILIZATION` in the following sample

```ts
    const target = new applicationautoscaling.ScalableTarget(this, 'ScalableTarget', {
      serviceNamespace: applicationautoscaling.ServiceNamespace.LAMBDA,
      maxCapacity: 100,
      minCapacity: 10,
      resourceId: `function:${handler.functionName}:${fnVer.version}`,
      scalableDimension: 'lambda:function:ProvisionedConcurrency',
    })

    target.scaleToTrackMetric('PceTracking', {
      targetValue: 1,
      predefinedMetric: applicationautoscaling.PredefinedMetric.LAMBDA_PROVISIONED_CONCURRENCY_UTILIZATION,
    })
  }
```

### Environment

  - **CLI Version      : v1.25.0**
  - **Framework Version:**
  - **OS               : Mac OS X**
  - **Language         : TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Thanks for putting in a PR @pahud, much appreciated! 👍
