### ISSUE TITLE
Support for weighted round robin, header based routing and rounting based on source ip

### ISSUE THREAD

**Issue by anjalisayshi** [aws/aws-cdk#6372]
We are using CDK and ALB to build CI/CD pipeline and was wondering if like ALB, CDK can also support weighted round robin, header based routing and rounting based on source ip, instead of us having a work-around.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
What would you write in CloudFormation to get the results you want?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
