### ISSUE TITLE
Java cdk cast exception IBucket to Bucket

### ISSUE THREAD

**Issue by jimbitol** [aws/aws-cdk#6376]
Hello!
When doing
`Bucket bucket = (Bucket) Bucket.fromBucketName(this, "myId", "existingBucketName");`

when executing cdk commands I have
java.lang.ClassCastException: software.amazon.awscdk.services.s3.IBucket$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.s3.Bucket

It happen with other interfaces as well
Any ideas?

cdk --version
1.24.0 (build 6619e36)

**Comment by skinny85** [comment]
Hey @jimbitol ,

yes, this is expected. The instance returned from `fromBucketName` is not an instance of the `Bucket` class.

Thanks,
Adam

**Comment by jimbitol** [comment]
Hi @skinny85 , thanks for your answer!

I need to get the instance of that existing Bucket.

I was expecting to use `Bucket.fromBucketName()` to do it, but apparently that it is not the way.

How can I get an instance of that Bucket?

Later I will need to add an event notification to it -> `importedBucket.addEventNotification()`
and that exists only in the `Bucket` class.

Any thoughts?

Thanks!

**Comment by skinny85** [comment]
Yes - bucket notifications are not allowed on existing buckets: https://github.com/aws/aws-cdk/issues/2004 . Sorry about that.

**Comment by jimbitol** [comment]
Again, thanks for the answer @skinny85 

Do not worry, It is clear enough.

Thanks
