### ISSUE TITLE
EKS stack is failing to be created

### ISSUE THREAD

**Issue by nikhilbhoj** [aws/aws-cdk#6377]
HI,
I was able to create EKS with Cloud Development Kit version 1.17 but after CDK version upgrade my Stack creation of EKS is failing. In our AWS environment we had to add boundary policy and can only create Managed policy which I have customized programmatically but even after that my stack creation is failing.

Basically the nested stack is failing to be created.

I am using below sample from AWS.
https://github.com/aws-samples/amazon-eks-cicd-codebuild 

which I have customized for our AWS environment.

I had raised a support ticket with AWS  for this issue and came to know that in new eks package it has two nested stack having different resource but has same logical id. As logical id has to be unique my stack creation is failing. 

Nested Stack 1: CdkStackawscdkawseksClusterResourceProvider56AF5AFA.nested.template.json
Nested Satck 2: CdkStackawscdkawseksKubectlProvider6C5CC6BA.nested.template.json 

both have same logical id for couple of resources.

For example ProviderframeworkonEventServiceRoleDefaultPolicy48CD2133 policy is present in both the stack.

Also this Lambda function is ProviderframeworkonEvent83C1D0A7 is present in both the stack.

### Reproduction Steps

If required let me know I can even share my main template or source code if required.

### Error Log

```
  9/28 | 12:38:18 AM | CREATE_FAILED        | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStackResource (awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454) Embedded stack arn:aws:cloudformation:ap-southeast-2:786326914961:stack/CdkStack-awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProv-1NY3SCHT34UCN/057f52c0-5379-11ea-ba9e-0229e4e38598 was not successfully created: The following resource(s) failed to create: [ProviderframeworkonEventServiceRoleDefaultPolicy48CD2133].
```

### Environment

  - **CLI Version      :** 1.25
  - **Framework Version:**
  - **OS               :** Ubuntu 16.0
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@nikhilbhoj why is it a problem to have the same logical ID in two nested stacks?

**Comment by nikhilbhoj** [comment]
@eladb My stack is failing to be created due to this. This was also mentioned by the AWS Support person too. I can mention the case Id is required for reference.

**Comment by eladb** [comment]
It appears that the issue is that it is impossible to create the IAM role. Could that be because of the IAM security boundary you have?

**Comment by nikhilbhoj** [comment]
Hi eladb
Probably the issue is due to mandatory boundary policy  that has to be  attached for every role that is being created either manually or through automation. 
I have to apply a global boundary policy on all my roles that are to be created and this was working in cdk version 1.17  but this stopped working since the introduction of nested stack in eks from 1.21 onward although I have applied the same global boundary policy on the nested stack too, I had verified this by checking them in the cdk.out directory all the stack where roles are created have this boundary policy but the issue I came to find out that some roles are duplicate in this new eks cdk version while in 1.17 this was not the case. 

Also, I was able to to make this stack work in my public AWS account which does not have this boundary policy restrictions.

**Comment by eladb** [comment]
Can you share some details (and preferably code) on how you apply the boundary policy and what it is exactly?

**Comment by nikhilbhoj** [comment]
Thanks @eladb  for looking into this. I am share this gist containing code for my stack.

https://gist.github.com/nikhilbhoj/0b3d9c9fca767330fdd02cd83846dcf6

**Comment by eladb** [comment]
I need to see the permission boundary policy itself.

**Comment by nikhilbhoj** [comment]
Hi @eladb ,

I checked internally for sharing boundary policy but was advise not to share that as it has some proprietary code.

Thanks for the input and the issue seems to be pointing towards our boundary policy which I have to resolve with our platform team.

**Comment by eladb** [comment]
Thanks for letting us know. Would be great if you could share the root cause here for future generations.

**Comment by nikhilbhoj** [comment]
Hi @eladb 

I had made some customized changes on the Managed policy that was been generated via my code wrapper by adding some randomness on the resources and I was able to create the EKS cluster via CDK.
This means that managed policy seems to have global scope and inline is local scoped.
