### ISSUE TITLE
About Typescript docs: add inheritance and property's requirements

### ISSUE THREAD

**Issue by tbrand** [aws/aws-cdk#6380]
I would like to suggest to add "class/interface inheritance" and "property's requirements" into Typescript docs.

After I started to write CDK, even it's great tool, I faced below problems sometimes.
- CDK said that I missed a required property. But there is no property like that in the docs. When I checked source code, I found that the property of interface is defined in the interface which inherited from.
- CDK said that I missed a required property. I thought that property is filled by default.

If these contents are written in the docs, I guess developer can write CDK code more smoothly.

Regards.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
If you are writing TypeScript, the universal docs are probably better than the TypeScript docs. 

Thanks for bringing this to our attention.
