### ISSUE TITLE
StepFunctions -> TaskInput cannot select the entire Input 

### ISSUE THREAD

**Issue by mrgrain** [aws/aws-cdk#6388]
Using `TaskInput` in step functions, it is impossible to select the entire step input.

I would expect to be able to select the entire input using `$`, however the JSON path validator expects a path to start with `$.`

### Reproduction Steps
In a newly created project, put this as stack:
```
export class StepfunctionbugStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const topic = new Topic(this, "topic");

    const definition = new Task(this, "task", {
      task: new PublishToTopic(topic, {
        message: TaskInput.fromDataAt("$")
      })
    });

    new StateMachine(this, "state-machine", {
      stateMachineType: StateMachineType.STANDARD,
      definition
    });
  }
}
```

### Error Log

```>$ cdk synth

Data JSON path values must start with '$.'
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.25.0 (build 5ced526)
  - **Framework Version:** 1.25.0
  - **OS               :**  macOS Mojave 10.14.5
  - **Language         :** Typescript 3.7.5

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This seems to be a fundamental limitation of StepFunctions itself, and not necessarily the CDK. 

Based on their [documentation](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-paths.html), they're using [JsonPath](https://github.com/json-path/JsonPath). I can't seem to find a way in JsonPath to specify a 'select all' operator. The closest that comes is the `$..*` operator.

Can you try the `$..*` and see if this satisfies your use case?

**Comment by rix0rrr** [comment]
Also, in case of the `PublishToTopic` action, I believe not specifying a TaskInput at all will make it default to the entire message.

**Comment by mrgrain** [comment]
@nija-at StepFunctions is perfecty happy with a `$` to include the entire input. It's also how I would read the JsonPath documentation.

@rix0rrr That's good to know, thanks 👍  I still believe the JsonPath parser isnt't correct though, as `$` is a valid JsonPath and meets the extra requirements for StepFunctions. See http://jsonpath.herokuapp.com/?path=$

-----

There is another work around as well, but it's not obvious to find:
```
new PublishToTopic(snsTopic, {
  message: TaskInput.fromText(Data.entirePayload)
})
```

**Comment by nija-at** [comment]
@rix0rrr - `Message` attribute is a mandatory property for the Notification type in the Amazon states language, so what you're suggesting won't work here.

However, I seem to have missed in the documentation that `$` is a valid path that refers to selecting everything. (thanks @rix0rrr for pointing this out).

The validations in field.ts will need to updated to support `$` and `$$`.

https://github.com/aws/aws-cdk/blob/983dd403d1293f7b1a01dd18f65d65cfee964eba/packages/%40aws-cdk/aws-stepfunctions/lib/fields.ts#L131-L140
