### ISSUE TITLE
Missing Deployment Stage on addBasePathMapping

### ISSUE THREAD

**Issue by renanmav** [aws/aws-cdk#6395]
### Context

This issue is related to `@aws-cdk/aws-apigateway` and its custom domain names. 

When setting up a `DomainName`, we need to create base path mappings to indicate which ApiGateway will be trigged by this domain. When creating a mapping, we can specify the base path, and the destination, using the **ApiGateway ARN** and its **Deployment Stage**. On AWS Console, this is the card that allow us to create these mappings:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/43140758/75035425-2caf5a00-548e-11ea-92fc-f745ce65353b.png">

When trying to reproduce this with `aws-cdk`, we create a DomainName instance like:
```ts
const graphqlDomainName = new ApiGateway.DomainName(this, 'GraphQLDomainName', { ... });
```
And we can add a base path mapping with the `addBasePathMapping` of the recent instantiated object, like:
```ts
graphqlDomainName.addBasePathMapping({
  stack: this,
  node: this.node,
  restApiId,
});
```
NOTE: the `restApiId` can be pulled from anywhere, I’m using `@aws-cdk/aws-ssm` to share info across stacks.

### The problem

I can’t pass a deployment stage to this recent created mapping.  

On AWS Console, this is the card that is created:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/43140758/75036673-2c648e00-5491-11ea-8c42-c4292fb4bfb8.png"> 

We can see that the typings of the `addBasePathMapping` function are:
```ts
/**
 * Maps this domain to an API endpoint.
 * @param targetApi That target API endpoint, requests will be mapped to the deployment stage.
 * @param options Options for mapping to base path with or without a stage
 */
addBasePathMapping(targetApi: IRestApi, options?: BasePathMappingOptions): BasePathMapping;
```
JSDoc says that we can pass a second argument with or without a stage, while the `BasePathMappingOptions` interface doesn’t accept a `stage` prop, see:
```ts
export interface BasePathMappingOptions {
    /**
     * The base path name that callers of the API must provide in the URL after
     * the domain name (e.g. `example.com/base-path`). If you specify this
     * property, it can't be an empty string.
     *
     * @default - map requests from the domain root (e.g. `example.com`). If this
     * is undefined, no additional mappings will be allowed on this domain name.
     */
    readonly basePath?: string;
}
```

### Reproduction Steps

I’ve been working on this [open source repo](https://github.com/renanmav/animavita). The file that contains this bug/missing feature is https://github.com/renanmav/animavita/blob/0cb517d3aa062c792da02e15ddacb9c8246ed059/packages/aws/stacks/DomainStack.ts

### Environment

  - **CLI Version      :** 1.25.0
  - **Framework Version:** 1.25.0
  - **OS               :** MacOS Catalina
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Thanks for filing this request. This does look like a gap in our construct library. 

Currently, the stage field is derived from the [`deploymentStage` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html#deploymentstage) of the RestApi that is passed in. It seems reasonable to want to specify different stages associated with the same RestApi.

I'm switching this issue into a feature request.

As a work around you can use escape hatches to access the `CfnBasePathMapping` instance and set this to the desired stage.

Thanks!
