### ISSUE TITLE
@aws-cdk/aws-autoscaling.LifecycleHookProps - make notificationTarget optional.

### ISSUE THREAD

**Issue by bf-sodle** [aws/aws-cdk#6399]
When creating a lifecycle hook for an auto-scaling group, specifying a notification target should be optional.

### Use Case

When no notification target is specified for a Lifecycle Hook, AWS simply broadcasts a CloudWatch event describing the instance launch or termination. The recipient of this event is not necessarily a Lambda function, and the CDK should not require knowledge of it anyway.

### Proposed Solution

Make the `notificationTarget` property of `@aws-cdk/aws-autoscaling.LifecycleHookProps` optional, and handle cases where it is not provided.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by indrora** [comment]
This is currently the case already: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.LifecycleHookProps.html#notificationtarget
