### ISSUE TITLE
aws-lambda: Simplify Lambda provisioned concurrency autoscaling

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#6400]
[Provisioned concurrency for Lambda function](https://aws.amazon.com/tw/blogs/aws/new-provisioned-concurrency-for-lambda-functions/) is a huge announcement last year in re:Invent and the Lambda developer guide has a [chapter](https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html) talking about how to configure provisioned concurrency auto scaling with target tracking with AWS CLI like this:

```bash
$ aws lambda put-provisioned-concurrency-config --function-name my-function \
--qualifier BLUE --provisioned-concurrent-executions 100
{
    "Requested ProvisionedConcurrentExecutions": 100,
    "Allocated ProvisionedConcurrentExecutions": 0,
    "Status": "IN_PROGRESS",
    "LastModified": "2019-11-21T19:32:12+0000"
}
```

```bash
$ aws application-autoscaling register-scalable-target --service-namespace lambda \
      --resource-id function:my-function:BLUE --min-capacity 1 --max-capacity 100 \
      --scalable-dimension lambda:function:ProvisionedConcurrency
```

```bash
$ aws application-autoscaling put-scaling-policy --service-namespace lambda \
--scalable-dimension lambda:function:ProvisionedConcurrency --resource-id function:my-function:BLUE \
--policy-name my-policy --policy-type TargetTrackingScaling \
--target-tracking-scaling-policy-configuration '{ "TargetValue": 0.7, "PredefinedMetricSpecification": { "PredefinedMetricType": "LambdaProvisionedConcurrencyUtilization" }}'
{
    "PolicyARN": "arn:aws:autoscaling:us-east-2:123456789012:scalingPolicy:12266dbb-1524-xmpl-a64e-9a0a34b996fa:resource/lambda/function:my-function:BLUE:policyName/my-policy",
    "Alarms": [
        {
            "AlarmName": "TargetTracking-function:my-function:BLUE-AlarmHigh-aed0e274-xmpl-40fe-8cba-2e78f000c0a7",
            "AlarmARN": "arn:aws:cloudwatch:us-east-2:123456789012:alarm:TargetTracking-function:my-function:BLUE-AlarmHigh-aed0e274-xmpl-40fe-8cba-2e78f000c0a7"
        },
        {
            "AlarmName": "TargetTracking-function:my-function:BLUE-AlarmLow-7e1a928e-xmpl-4d2b-8c01-782321bc6f66",
            "AlarmARN": "arn:aws:cloudwatch:us-east-2:123456789012:alarm:TargetTracking-function:my-function:BLUE-AlarmLow-7e1a928e-xmpl-4d2b-8c01-782321bc6f66"
        }
    ]
}
```

In the latest aws-cdk v1.25.0 we start supporting aws-applicationautoscaling with Lambda([PR](url)) and I have yet another PR(#6394 ) to make it complete. We should be able to build the provisioned concurrency autoscaling like this 

![圖片](https://user-images.githubusercontent.com/278432/75083206-76fa0f00-5552-11ea-9a54-addf22159421.png)

To make it even simplied, as the provisioned concurrency can be configured over any lambda function version or alias, we probably can extend the [lambda.Version](https://github.com/aws/aws-cdk/blob/8e2e4920cc0e3ff4c2e06139f040548da48fa953/packages/%40aws-cdk/aws-lambda/lib/lambda-version.ts#L82) class by adding a `scaleOnProvisionedConcurrency` function like this

```ts
  public scaleOnProvisionedConcurrency(props: ScaleProvisionedConcurrencyProps): applicationautoscaling.TargetTrackingScalingPolicy {
      return new applicationautoscaling.ScalableTarget(this, 'ScalableLambdaTarget', {
      serviceNamespace: applicationautoscaling.ServiceNamespace.LAMBDA,
      maxCapacity: props.max,
      minCapacity: props.min,
      resourceId: `function:${this.functionName}:${this.version}`,
      scalableDimension: 'lambda:function:ProvisionConcurrency',
    })
      .scaleToTrackMetric('PceTracking', {
        targetValue: props.target,
        predefinedMetric: applicationautoscaling.PredefinedMetric.LAMBDA_PROVISIONED_CONCURRENCY_UTILIZATION,
      });
  }
```

And in this case, all lambda function alias can have autoscaling capabilities. Sample code here

![圖片](https://user-images.githubusercontent.com/278432/75083371-5b433880-5553-11ea-887b-d28aefa86105.png)

Any thoughts?

### Use Case

To make any AWS Lambda function version or alias very easy to enable its provisioned concurrency auto scaling capabilities.

### Proposed Solution

described above

### Other

* [v] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Thanks for filing this issue. In general, we should have this feature included into the CDK.

There's a few things we should consider during the start of implementation -
* be careful about how we connect this to versions. We have a reported bug that causes versions to not update as expected - https://github.com/aws/aws-cdk/issues/5334. It might turn out that we have to fix up [this behaviour](https://github.com/aws/aws-cdk/issues/5334#issuecomment-581650265) before implementing this feature.
* work out what the right location for this package would be. There are two options, either in the `@aws-cdk/aws-lambda` package or a new `@aws-cdk/aws-autoscaling-targets` package.

Finally, the API signatures you've suggested need to be tuned for a more ergonomic customer experience.

**Comment by eladb** [comment]
Related: https://github.com/aws/aws-cdk/pull/6771
