### ISSUE TITLE
CDK won't exit if the deployment of nested stack failed and rollback completed

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#6403]
CDK cli stuck on running if the deployment of nested stack failed and rollback completed. Have to kill the process to exit the CDK app.

### Reproduction Steps

1. create an app with nested stack
1. successfully deploy the stack and nested stack 
1. modify the nested stack to cause deployment failure, such as running ec2 instances exceeding the limit
1. deploy the updated stack again, the nested stack will fail, but the cdk command is still running the nested stack and parent stack have been rollbacked completely.

### Error Log

![image](https://user-images.githubusercontent.com/843303/75095330-92a2fb00-55ce-11ea-864c-1855c7165920.png)

### Environment

  - **CLI Version      :*1.25.0*
  - **Framework Version:**
  - **OS               :*macosx*
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by gadams999** [comment]
this is also happening with un-nested stacks too. Worked in 1.24.0 and now ROLLBACK_COMPLETE doesn't exit.

**Comment by michaelday008** [comment]
I experienced this issue by following a code sample in the documentation, which then failed, rolled back, and then got stuck at 9/16 and I had to ctrl-C to get back to the command line after waiting an hour with nothing happening.

**Comment by anmolsi** [comment]
Facing same issue.

**Comment by shivlaks** [comment]
confirming that we have a regression in `1.25.0` - I believe we introduced this regression in [this change](https://github.com/aws/aws-cdk/commit/aba1485765a4ac31e5acabaa945b1b4adde94c6a). Attempted to roll it back locally and the stack kills once it hits the `ROLLBACK_COMPLETE` state

minimal repro:

```ts
import * as cdk from '@aws-cdk/core';
import * as cfn from '@aws-cdk/aws-cloudformation';
import * as s3 from '@aws-cdk/aws-s3';

export class NestedbugStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new NestedStack(this, 'Nest1');
    new NestedStack(this, 'Nest2');
  }
}

class NestedStack extends cfn.NestedStack {
  constructor(scope: cdk.Construct, id: string, props?: cfn.NestedStackProps) {
    super(scope, id, props);

    new s3.Bucket(this, 'MyBucketNest', {
      bucketName: 'one-will-fail'
    }) ;
  }
}

```

looking into a fix

**Comment by shivlaks** [comment]
update: The regression in behavior was not introduced by the change above, but rather uncovered because of it. We were not handling errors in stack deployments gracefully so there were open handles that prevented Node from exiting gracefully and caused the CLI to hang.

Fix incoming
