### ISSUE TITLE
Use IService instead of BaseService in EcsDeployActionProps?

### ISSUE THREAD

**Issue by atsushi-ishibashi** [aws/aws-cdk#6408]
## :question: General Issue

To construct EcsDeployAction, we need BaseService for EcsDeployActionProps.
```
Type 'IEc2Service' is missing the following properties from type 'BaseService': connections, serviceName, taskDefinition, cluster, and 31 more.
```

### The Question

Following the flow in management console, IService is better than BaseService?
I hope you can set it like below.
```
const service = ecs.Ec2Service.fromEc2ServiceArn(stack, `service`, serviceArn)
const action = new codepipeline_actions.EcsDeployAction({
  actionName: 'ECS',
  service,
});
```

### Environment

  - **CDK CLI Version:** 1.25.0
  - **Module Version:** 
  - **OS:** 
  - **Language:** TypeScript

**Comment by atsushi-ishibashi** [comment]
The service cannot be defined uniquely by ARN 🤔

**Comment by skinny85** [comment]
Done in #6412 🙂
