### ISSUE TITLE
Make `/tools/` packages public

### ISSUE THREAD

**Issue by campionfellin** [aws/aws-cdk#6429]
### The Question

Is there any plan forward for making at least some of the packages in `/tools/` public?

Would there be any blockers to a PR from the community to publish something like `cdk-integ-tools` to `@aws-cdk/cdk-integ-tools` so it can be consumed directly?

The problem currently is, that if these tools get changed, and they are being copy+pasted then we may not pick up the changes.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by eladb** [comment]
Duplicate https://github.com/aws/aws-cdk-rfcs/issues/4
