### ISSUE TITLE
S3 error: Access Denied on cdk deploy

### ISSUE THREAD

**Issue by AlexCheema** [aws/aws-cdk#6430]
Around 10% of `cdk deploy` commands fail with `S3 error: Access Denied`.

### Reproduction Steps

`cdk "deploy" "-e" "true" "--require-approval" "never" "--no-ci" "--output" "1432235223.cdk.out" "--no-staging" "MyStack"`

### Error Log

```
978 MyStack: creating CloudFormation changeset...
979  ❌  MyStack failed: ValidationError: S3 error: Access Denied
980 For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
981 S3 error: Access Denied
982 For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```

### Environment

  - **CLI Version      :1.25.0**
  - **Framework Version:1.25.0**
  - **OS               :Linux Ubuntu 18.04**
  - **Language         :Typescript**

### Other

The stack itself is irrelevant. This can even happen with an almost empty stack.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@AlexCheema 

You said the stack itself is irrelevant, nonetheless, can you please provide some minimal repro stack this happens to you?

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.

**Comment by UnbiasedGoat** [comment]
We've had this twice now. Seems like just a random blip. Must be a race condition of some kind.....

**Comment by serverlessunicorn** [comment]
I get this about 1 time in 20. It's really embarrassing when running a demo in front of customers. Please take it seriously.

**Comment by RomainMuller** [comment]
We nevertheless are going to require a minimal reproduction before we can work on it. What is the smallest possible CDK app you can come up with that triggers the issue? Does your environment have anything particular about it? In particular - how are credentials provided?

**Comment by serverlessunicorn** [comment]
What I can tell you:
- I only use the python flavor of the CDK.
- This has been happening for the past year (as long as I've been using the CDK), across many versions/updates and across different deployments. As I write this I'm on 1.34.1 (build 7b21aa0) but there's been no improvement over the past year in any release. I'm using Python 3.7.4.
- I've seen it in tiny projects and large ones; doesn't seem to matter.
- It's not related to the AWS account. I've seen it on accounts that are years old and ones created in the last few days. I've seen the same deployment to two accounts fail for one and succeed for the other.
- It's very random...almost certainly an infrequent race condition. Appears unrelated to the size/complexity of the actual deployment.
- I only write serverless apps, so my cdk stacks typically contain some combo of {API Gateway, Lambda, AppSync, DynamoDB, Step Functions, SQS}.

I can send you a simple registration service app if that helps, though it's nothing more than AppSync with a Lambda resolver that calls DDB. You would have to create a synthetic harness that makes innocuous changes to the Lambda and attempts to deploy them and then run that in a loop until the bug hits - just doing an "empty" deploy won't tickle the bug.

**Comment by serverlessunicorn** [comment]
Credentials: In my case, creds come from ~/.aws/credentials. I've seen the bug on both the default credentials and with explicit --profile args provided; doesn't seem to matter. I've seen it happen on both the root account creds and IAM role creds. Different profiles in my credentials file relate to different accounts at the moment, but I've seen this bug in simple, single account cases, in multi-role-within-one-account cases, and in cross-account cases.

HTH.

**Comment by RomainMuller** [comment]
@serverlessunicorn thanks for these details...

To confirm: no fancy things with respects to credentials, like MFA or anything of the sort?

Additionally - is there any particular region you're experiencing this with?

**Comment by serverlessunicorn** [comment]
No fancy MFA :). us-east-1 most of the time.

**Comment by RomainMuller** [comment]
@NetaNir and @rix0rrr might actually have identified an S3 negative cache entry situation which could cause the symptoms you're facing.

We're checking if an asset exists in S3 before uploading (to avoid re-uploading possibly large assets). This causes HEAD/GET-after-PUT to become eventually consistent because it creates a negative cache entry...

We're looking to switch to using a LIST-based check, which would not create the negative cache entry, and hopefully stop this issue altogether.

**Comment by RomainMuller** [comment]
I intend on releasing a version of CDK with the fix in it today, so y'all can collecting evidence on whether that was it or not... 🤞🏻

**Comment by msimperi** [comment]
I saw this error today with CDK version 1.105.0 similar error. One stack failed to this validation error always after it has been uploaded. It just started to happen when deploying locally. With other stacks all good and those are 100% from configuration point of view.

```
origo-myapp-app-pipeline-release-stack
origo-myapp-app-pipeline-release-stack: deploying...
[0%] start: Publishing d29ee123a2bdb2df2e9084ea497482ff7111093a56b25dbc4ebfbe70cb64c54c:current
[100%] success: Published d29ee123a2bdb2df2e9084ea497482ff7111093a56b25dbc4ebfbe70cb64c54c:current
origo-myapp-app-pipeline-release-stack: creating CloudFormation changeset...

 ❌  origo-myapp-app-pipeline-release-stack failed: Error [ValidationError]: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
    at Request.extractError (/Users/simpemat/src/origo-myapp/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/simpemat/src/origo-myapp/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/simpemat/src/origo-myapp/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/simpemat/src/origo-myapp/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
```

**Comment by msimperi** [comment]
It seems to me that after naming something in the stack to get different stack generated (different hash), it started to work. Again when returning to the same stack (identical hash), I'm getting this error 100% of the rounds. It has to be that something with S3 file publishing has failed.

**Comment by g-wozniak** [comment]
@msimperi make sure you used CdkPipeline (from [@aws-cdk/pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CdkPipeline.html) ) not Pipeline from `@aws-cdk/aws-codepipeline`. The latter won't let you run `cdk deploy` on this kind of asset, no matter if you try in Build step or Pipeline_Update.

**Comment by robertd** [comment]
Got the same error... I've never seen this before. I'm trying to deploy a resource in a VPC I haven't visited in a while.
![image](https://user-images.githubusercontent.com/31543/132578823-5f9b25a8-9e5a-4166-87f4-bbdd47ddf333.png)

**Comment by cagdas-carbon** [comment]
I started seeing the same issue right after switching to `newStyleStackSynthesis`. Deploy & file publishing IAM roles both do have the permission to write to S3.

**Comment by ShantanuKumar** [comment]
This is bit frustrating. I got recently this error on a pipeline which working fine until this showed up. These things are just so random

```
Action execution failed
Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: ZFGNHFPM4RZDZ20N; S3 Extended Request ID: yIsZfjsZo4D+jk1boQlva1qYDmkNHAaISWGzWJfP3bH0n4VKVAgccS9BDVRp6vp2upr1BbBqj/o=; Proxy: null)
```

**Comment by jdebo-slalom** [comment]
> It seems to me that after naming something in the stack to get different stack generated (different hash), it started to work. Again when returning to the same stack (identical hash), I'm getting this error 100% of the rounds. It has to be that something with S3 file publishing has failed.

This worked for me when running into the exact same issue - CDK V2.3.0, Typescript, Deploying lambdas and dynamodb

**Comment by mbdilaver** [comment]
I had the same issue. My user has MFA by default. I disabled and enabled the MFA and switched to another 2FA app. 
I don't know if this was the exact solution but I no longer have this issue and CDK deploy command works fine.

**Comment by rudpot** [comment]
I keep seeing this on EKS stacks but only occasionally - maybe 1 in 10. Details:

* new AWS accounts
* CDK v2
* CDK is already initialized in the account before this deploy runs
* other AWS accounts running the same deployment sequence succeed

**Comment by michielvermeir** [comment]
Can this issue be reopened? We are also seeing this sporadically with recent versions of CDK. Although for us it seems to happen when deploying `StackSet`s across a large number of AWS accounts with `MaxConcurrentCount` set higher than 1.

**Comment by u2mejc** [comment]
> failed: ValidationError: S3 error: Access Denied

I also ran into this issue and initially it seemed related to this post: https://repost.aws/knowledge-center/cfn-s3-access-denied-error

The fix in the end for me was I wasn't passing the region in my stack's class correctly. Once I figured that out (and the stack was in the correct region), it started working again.

**Comment by GarryOne** [comment]
I have the same error, but when running `cdk import` for a DynamoDB table
```
 ❌  My-Stack failed: CloudFormationServiceException [ValidationError]: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
    at throwDefaultError (/Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:71296:24)
    at /Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:71305:9
    at de_CommandError (/Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:126353:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:63004:24
    at async /Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:63144:22
    at async /Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:76814:42
    at async /Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:62711:26
    at async FullCloudFormationDeployment.createChangeSet (/Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:150217:27)
    at async FullCloudFormationDeployment.changeSetDeployment (/Users/igor.mardari/.nvm/versions/node/v20.18.2/lib/node_modules/aws-cdk/lib/index.js:150158:38) {
  '$fault': 'client',
  '$metadata': [Object],
  Type: 'Sender',
  Code: 'ValidationError'
}
S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```
