### ISSUE TITLE
Lambda UI showing Cloudwatch Event "Enabled" even if CW rule is disabled

### ISSUE THREAD

**Issue by sacag** [aws/aws-cdk#6437]
Lambda UI is showing the Slider button "Enabled" for the Cloudwatch event, even if the cloudwatch rule for the lambda is disabled.
Using .NET CDK (1.24)

![image](https://user-images.githubusercontent.com/9053257/75251088-e583da80-57a7-11ea-8fc1-da9c8dfa2be9.png)

### Reproduction Steps

```
var rule = new Rule(scope, $"{props.UniqueFunctionSuffix}-EventTrigger-Id", new RuleProps
            {
                Description = $"This cron job invokes the {props.UniqueFunctionSuffix}-Subscriber lambda function every 1 minute",
                Enabled = false,
                RuleName = $"{props.UniqueFunctionSuffix}-CronEvent-Trigger",
                Schedule = Schedule.Rate(Duration.Minutes(1))
            });
            rule.AddTarget(new LambdaFunction(func));
```

**Comment by nija-at** [comment]
Can you let me what the value of [the `State` property of `AWS::Events::Rule` resource type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-state) in the CDK synthesized CloudFormation template, or in the CDK deployed stack?
