### ISSUE TITLE
Autogenerating a new Hosted Zone is really fragile, when parent HZ is in a different account

### ISSUE THREAD

**Issue by lemiesz** [aws/aws-cdk#6449]
```
    this.service = new ecsPatterns.ApplicationLoadBalancedFargateService(
      this,
      "Service",
      {
        publicLoadBalancer: true,

        domainName: `app.${props.stage}.parent.a2z.com`,
        domainZone: new HostedZone(this, "HostedZone", {
          zoneName: `${props.stage}.parent.a2z.com`
        }),
```

We run multiple subdomains on the same parent HZ. This poses some problems when trying to autogenerate a HZ using ecspatterns. The parent HZ exists within a different AWS account. So during a deployment, there needs to be a manual step where we add the newly create HZ as a NameServer record on the parent HZ. 

If I am not quick enough about doing this the ACM certificate validation will fail, and the whole deployment will no go through. 

This would be fine if I could just do the manual step and rerun my deployment. The problem is during the CFN rollback, the newly created HZ fails to delete and gets left in a limbo state. Subsequent deployments will try to create a new HZ instead of reusing the existing one. 

### Reproduction Steps

see above

### Environment

  - **CLI Version      :*1.17.1*
  - **Framework Version:*1.17.1*
  - **OS               :*OSX*
  - **Language         :**

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
This may be related to other work involving multiple accounts being deployed to from the CDK CLI.
