### ISSUE TITLE
Output YAML format template to cdk.out

### ISSUE THREAD

**Issue by hiraken-w** [aws/aws-cdk#6461]
Currently, JSON format XXX.template.json is output to cdk.out directory.
I want to be able to change the format of this file to YAML format.

### Use Case

To change to a format that is easy for humans to understand.

I know the command "cdk synth" can output template as YAML format.
But I want to be able to select YAML and JSON for the file format of the template in cdk.out.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@hiraken-w - I believe this request is something that was raised in #2965 

as mentioned in [this comment](https://github.com/aws/aws-cdk/issues/2965#issuecomment-589151156)

> This is not something we will likely support. cdk.out is designed to be machine-readable and there is value in keeping it "agnostic" of visual representation. YAML is not an ideal format for that.
> It should trivial to convert the templates from cdk.out to YAML using any standard tool if you desire to review them as YAML.

I'm closing this so we can keep the related conversation in #2965
Please continue the conversation there.

Cheers!

**Comment by navjyotnishant** [comment]
you can always out yaml 

cdk synth > /<path>/template.yaml

**Comment by karanthakkaredwards** [comment]
Came here to point out that depending on the use case, the above solution may not work. Found that out the annoying way, had a pre-commit hook that did cdk synth > cft.yaml then ran checkov scan on the yaml. Worked fine initially then realized that it only works with a single stack and for multiple stacks you'd have to specify stack name in the command if you want to get output in cft.yaml
