### ISSUE TITLE
[ElasticSearch] UltraWarm Elasticsearch

### ISSUE THREAD

**Issue by 9tontruck** [aws/aws-cdk#6462]
I would like to make a feature request for UltraWarm Elasticsearch features.
AWS UltraWarm Elasticsearch:
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ultrawarm.html

The biggest benefit of UltraWarm is about 90% reduced storage cost by storing data in S3 instead of SSD. 

### Use Case
We are building a project that involves indexing visual features of more than 100 million images and we planned to use an Elasticsearch. Because the size of data we need to index is extremely huge, the expected resource cost is also really high. By using UltraWarm, we are expecting about 90% of storage cost drop.

### Proposed Solution

When Elasticsearch is being created,
ElasticsearchClusterConfigProperty would need to accept following parameters
1. warmEnabled: true/false. Enabling UltraWarm elasticsearch
2. warmCount: int. Number of instances
3. warmType: String. Type of instance. eg. ultrawarm1.medium.elasticsearch

**Comment by iliapolo** [comment]
Hi @9tontruck - Thanks for reporting this!

Unfortunately, this feature is not yet supported by CloudFormation. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html

I'm marking this request as `needs-cfn` and once they add support we can start pushing this forward.

**Comment by 9tontruck** [comment]
> Hi @9tontruck - Thanks for reporting this!
> 
> Unfortunately, this feature is not yet supported by CloudFormation.
> 
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html
> 
> I'm marking this request as `needs-cfn` and once they add support we can start pushing this forward.

Thank you!

**Comment by 9tontruck** [comment]
Any updates on this?

**Comment by iliapolo** [comment]
@9tontruck It still is not available in CloudFormation unfortunately. 

I encourage you to [open](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/new) a feature request for CloudFormation as well.

**Comment by erik-telesoftas** [comment]
Reference to CloudFormation feature request: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/283

**Comment by heikkis** [comment]
Support for CF has been published: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html

**Comment by jumi-dev** [comment]
I will implement the support for UltraWarm instances and create a pull request.
