### ISSUE TITLE
stepfunctions task - support dynamodb

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#6468]
https://docs.aws.amazon.com/step-functions/latest/dg/connect-ddb.html

---

This is a :rocket: Feature Request

**Comment by ayush987goyal** [comment]
Hi @nija-at ,

To implement this, I was thinking of having individual classes for all 4 APIs (GetItem, PutItem, DeleteItem and UpdateItem) that implement `IStepFunctionsTask` and one public class called `CallDynamoDB` which has static methods for each of these APIs that instantiates and returns a task object for these. How does that sound?

**Comment by nija-at** [comment]
This sounds like a good start. I would prefix the classes with the service name and drop the `Task` suffix, so `DynamoGetItem`, `DynamoPutItem`, etc.

**Comment by ayush987goyal** [comment]
@nija-at Hi, I am having trouble installing `@aws-cdk/aws-dynamodb` as a dependency of `@aws-cdk/aws-stepfunctions-tasks`. This is what I am doing in `aws-cdk/packages/@aws-cdk/aws-stepfunctions-tasks` sub-directory:

1. `yarn add @aws-cdk/aws-dynamodb@0.0.0`
2. `../../../scripts/buildup`

I am getting following error
> cdk-build Error: 
  Error: Unable to locate module: @aws-cdk/aws-dynamodb

I am not sure what I am doing wrong and what I should do instead.

**Comment by ayush987goyal** [comment]
I ran a `yarn build` in the root and I am getting the following error

> lerna ERR! ECYCLE Dependency cycles detected, you should fix these!
lerna ERR! ECYCLE @aws-cdk/aws-dynamodb -> @aws-cdk/custom-resources -> @aws-cdk/aws-stepfunctions-tasks -> @aws-cdk/aws-dynamodb

I think there is a cycle in the dependencies. The `custom-resources` package requires `aws-stepfunctions-tasks`. How do we handle this scenario?
