### ISSUE TITLE
Token resolver - unable to obtain Simple AD DNS Ip's

### ISSUE THREAD

**Issue by Mejato** [aws/aws-cdk#6475]
Simple AD DNS ip's - token not resolving

### Reproduction Steps

        directory = simple_ad.CfnSimpleAD(self,
                                          'simple-ad',
                                          name='something.cloud',
                                          password='somepassword',
                                          size='Small',
                                          vpc_settings={"vpcId": fargate_vpc.vpc_id,
                                                        "subnetIds": private_subnets})

        jumphost = ec2.Instance(self, 'jumphost',
                                instance_type=ec2.InstanceType('t3a.small'),
                                machine_image=jumphost_image,
                                vpc=fargate_vpc,
                                key_name='somekey',
                                vpc_subnets=jumphost_subnet_selection)

        core.CfnOutput(self, 'jumphost-ip', value=jumphost.instance_private_ip)
        core.CfnOutput(self, 'simple-ad-dns-ips', value=directory.attr_dns_ip_addresses[0])

### Error Log

simple-ad-deployment.jumphostip = 192.168.0.7
simple-ad-deployment.simpleaddnsips = #{**Token[TOKEN.84]**}

### Environment

  - **CLI Version      :1.17.9
  - **Framework Version:1.23.0
  - **OS               :Windows 10
  - **Language         :Python 3.6.0

This is :bug: Bug Report

**Comment by richardhboyd** [comment]
Is the #{Token[TOKEN.84]} what shows up in the CloudFormation Console?

**Comment by Mejato** [comment]
It shown up in the CloudFormation outputs - i.e after stack deployment.
![image](https://user-images.githubusercontent.com/41669982/75401406-f29af800-5966-11ea-8445-f88f511a5a15.png)

**Comment by rix0rrr** [comment]
```
    core.CfnOutput(self, 'simple-ad-dns-ips', value=directory.attr_dns_ip_addresses[0])
```

You are not allowed to take an element from a tokenized list in Python.

Use `Fn.select()` instead.

**Comment by Mejato** [comment]
Awesome thanks for the assistance @rix0rrr! That solved my problem.
