### ISSUE TITLE
[aws-sns] support overrideLogicalId() for sns.Topic class

### ISSUE THREAD

**Issue by brijeshdankhara** [aws/aws-cdk#6479]
`sns.Topic` has `grantPublish()` to setup TopicPolicy easily and `sns.CfnTopic` has `overrideLogicalId()` to provide a specific topicName. I wanted to request to have overrideLogicalId() to be implemented for sns.Topic class.

### Use Case
I have been working on a use case where an AWS _account_A_ will publish to an SNS topic in _account_B_. _account_A_ has been configured with the topicName created by `sns.CfnTopic`, but to grant them `sns.Publish` permission, I cannot use `grantPublish()`. Instead, I would have to create a new `iam.PolicyDocument` and attach it to the SNS topic.

#### Workaround I am using
When creating SNS topic in _account_B_. Instead of using `sns.CfnTopic`, use `sns.Topic` and use both `grantPublish` and `overrideLogicalId()` as shown below:
* `(topic.node.defaultChild as sns.CfnTopic).overrideLogicalId(<topic-name>);`
* `topic.grantPublish(new iam.AccountPrincipal(<account_A>));`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
hey @brijeshdankhara, you can specify a specific topic name using the `topicName` argument
```typescript
const topic = new sns.Topic(this, "Topic", { topicName: "my-topic-name" });
```

CDK generally discourages explicitly naming resources. Generally we encourage letting a name be auto-generated and then exposing that name by passing the construct object around and referencing its property, ie `topic.topicName`. Cross account scenarios don't currently support this as well as we want.

If setting the name still does't provide enough information to find the topic across accounts and you do in fact need to override the resource's logical ID, the way you're doing it is probably the best way.

ping @rix0rrr @skinny85 @eladb. What does everyone thing here?

**Comment by brijeshdankhara** [comment]
Hey @MrArnoldPalmer, I agree with your point on explicitly naming resource. In my use case, two packages agree on a `topicName` as a contract. 

I am not sure if auto-generated `topicName` would change for newer versions of the package. If it does, then the contract is void and _account_A_ would not be able to publish as the topicName is changed.

**Comment by MrArnoldPalmer** [comment]
auto-generated names don't change unless you change a parameter on a resource that requires it to be replaced completely.

Does setting the name manually with `topicName` work for you instead of overrideLogicalId?

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
