### ISSUE TITLE
Support EKS in China regions

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#6481]
According to the latest Amaozn EKS document [history](https://docs.aws.amazon.com/eks/latest/userguide/doc-history.html), it has been available in `cn-north-1` and `cn-northwest-1`. However, as `kubectl` layer is missing in SAR of `cn-north-1` we need some tweaks before we can successfully deploy it in China.

I will create a PR shortly to fix this issue.

### Error Log

```
 User: arn:aws-cn:iam::xxxxxxxxxxxx:user/pahud is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl
```

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/278432/75411302-ba40ed00-5959-11ea-968a-389dc0a8d96c.png">

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

related PR from **eksctl**: https://github.com/weaveworks/eksctl/pull/1720

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Thanks
