### ISSUE TITLE
Api Gateway model validations not working as documented

### ISSUE THREAD

**Issue by maxsap** [aws/aws-cdk#6485]
Reference doc page: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html

I am trying to add model schema to an API Gateway, when using the code from the documentation I am getting the following error:

> TypeError: __init__() got an unexpected keyword argument '$schema'

When I remove the dollar sign from the schema I get :

> jsii.errors.JSIIError: Value did not match any type in union: Expected enum value, got "string",Expected array type, got "string"

I have tried multiple different variations on the schema but none worked.
I am sure that the schema is valid because when I manually create an API GW and manually define the same schema from the AWS console everything works as expected.

I am using Python (not sure if this is relevant)

I think the documentation should be updated in order to provide a working example.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Thanks for bringing this to our attention. The docs were indeed erroneous in this section. I have a fix out for this - https://github.com/aws/aws-cdk/pull/6725
