### ISSUE TITLE
📊Tracking: AWS CloudFront

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#6490]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

A CloudFront construct - for setting up the AWS CDN with ease!

[AWS Docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

[CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html) 

- [x] CloudFront Web Distribution
- [x] default certificate
- [x] ACM certificate
- [x] IAM certificate
- [x] Origin Access Identity
- [ ] Streaming Distribution

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by heiba** [comment]
Hello, can you please prioritize https://github.com/aws/aws-cdk/issues/5607 ?

Without it, we are unable to utilize existing CloudFront Web Distributions in CDK. Usually creating / destroying CloudFront Distributions takes 15 minutes to create. So many customers prefer to lookup existing distributions instead.
