### ISSUE TITLE
Batch ComputeEvironment does not type or build instanceRole correctly

### ISSUE THREAD

**Issue by damonmaria** [aws/aws-cdk#6495]
In `@aws-cdk/aws-batch` `compute-environment` constructs the default for instanceRole as an `iam.Role`:
```javascript
new iam.Role(this, 'Resource-Instance-Role', {
                        assumedBy: new iam.ServicePrincipal('batch.amazonaws.com'),
                    }).roleArn
```

In `CfnComputeEnvironment` this should actually be a instance profile arn, not a role arn. 

### Reproduction Steps

Create a `ComputeEnvironment` using the default for `computeResources.instanceRole`. When you attempt to use the environment it goes INVALID with: "Invalid instance profile". 

```javascript
            new ComputeEnvironment(this, `${prefix}ModelEtlComputeEnv${i}`, {
              computeResources: {
                desiredvCpus: 0,
                instanceTypes: [new InstanceType('m5.4xlarge')],
                vpc,
              },
              managed: false,
            }),
```

### Error Log

Console message when viewing compute environment (once you try and start a batch): "Invalid instance profile"

### Environment

  - **CLI Version      :** 1.26.0
  - **Framework Version:** 1.26.0
  - **OS               :** MacOS
  - **Language         :** Typescript

### Other

Currently the workaround is painful because the type on `instanceRole` is incorrect. Here's the code I'm using to get around create what is needed manually:
```typescript
    const amazonEC2ContainerServiceForEC2Role = ManagedPolicy.fromManagedPolicyArn(
      this,
      'amazonEC2ContainerServiceForEC2Role',
      'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role',
    )
    const modelEtlInstanceRole = new Role(this, 'modelEtlInstanceRole', {
      assumedBy: new ServicePrincipal('ec2.amazonaws.com'),
      managedPolicies: [amazonEC2ContainerServiceForEC2Role],
    })
    const modelEtlInstanceProfile = new CfnInstanceProfile(
      this,
      'modelEtlInstanceProfile',
      {
        roles: [modelEtlInstanceRole.roleName],
      },
    )
    const mockInstanceRole = {
      roleArn: modelEtlInstanceProfile.ref,
    } as IRole
```

And then assign `mockInstanceRole` as the `instanceRole`.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @damonmaria, thanks for reporting this.

This should be fixed along with this PR: https://github.com/aws/aws-cdk/pull/6549. 

Stay tuned :)

**Comment by Dzhuneyt** [comment]
This is a blocking point for our company that we just encountered. Thank you for working on this @iliapolo!

Let me know if I can help in some way (code review, tests, etc).
