### ISSUE TITLE
Dynamodb: Type error ITable is missing properties in Table

### ISSUE THREAD

**Issue by harmohan-a** [aws/aws-cdk#6496]
I am writing code for an application (in typescript) to connect to a dynamodb table either by creating a table or connect to an existing table. I am getting error :
```
Type 'ITable' is missing the following properties from type 'Table': tableStreamArn, table, keySchema, attributeDefinitions, and 38 more.
```

Going through the doc, the code should work. 
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-dynamodb-readme.html
```
const table = Table.fromTableArn(this, 'ImportedTable', 'arn:aws:dynamodb:us-east-1:111111111:table/my-table');
// now you can just call methods on the table
table.grantReadWriteData(user);
```

### Reproduction Steps

```
public dynamoDBTable: Table;

....

try {
this.dynamoDBTable = new Table(this, 'table', {});
} catch(e) {
this.dynamoDBTable = Table.fromTableArn(this, 'Table', 'ARN'); //  Type 'ITable' is missing the following properties from type 'Table': tableStreamArn, table, keySchema, attributeDefinitions, and 38 more.
}
```

### Environment

  - **CLI Version      : 1.24.0, 1.26.0
  - **Framework Version: 
  - **OS               :Mac
  - **Language         : Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
The result of `Table.fromTableArn` is an `ITable`, not a `Table`. You should be able to fix yourself up by changing the type of `public dynamiDBTable` to be `ITable`.

The documentation is incorrect (wasn't updated after the introduction of `ITable`, I suppose) and needs fixing.
