### ISSUE TITLE
The pathPattern property, in AddApplicationTargetsProps and AddApplicationTargetGroupsProps, should accept a list, not just a simple string.

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#6497]
There is currently no way to add a target group to `ApplicationListener` using multiple path patterns.

According to the doc, https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#path-conditions, one should be able to use one or more path patterns as a set. I think this can be very useful in general, but it is also required to be able to support certain simple (but important) use cases. CDK currently does not support this in `ApplicationListener.addTargets()` and `ApplicationListener.addTargetGroups()`.

As an example, currently it is not possible to add a target group with path patterns, "/extra" and "/extra/\*". (There does not seem to be a way to express these two as a single path pattern.) If you specify "/extra", then it'll match "/extra" but not "/extra/abc", ... If you specify "/extra/\*", then it'll match patterns like "/extra/xyz", ... but not "/extra".

I would consider it a fundamental limitation of the API ("bug") rather than a missing feature. (I haven't found a workaround for this use case.)

### Reproduction Steps

1. Create an `ApplicationLoadBalancer`.
1. Add an `ApplicationListener` to the ALB.
1. Create a new target group.
1. Try to add the new TG to path ["/extra", "/extra/\*"] using `ApplicationListener.addTargetGroups()`.

### Environment

  - **CLI Version     : 1.25.0 (build 5ced526)
  - **Language         : Typescript

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You are not wrong that we should have this. 

Given that there is a workaround though (adding two rules) I'm going to mark this a feature request instead of a bug. Thanks for reporting.

**Comment by realharry** [comment]
Yes, I did realize, after opening the issue, that I could just call `ApplicationListener.addTargetGroups()` multiple times with the same TG (with different paths). Although non-intuitive, that achieved what I wanted. Thanks.

**Comment by DerkSchooltink** [comment]
I've taken the liberty to open a PR for this issue, as it was bothering me as well. @realharry can you verify if this solution aligns with your created issue (and perhaps leave a review)?

**Comment by realharry** [comment]
Hey @DerkSchooltink Thanks for taking the time to work on this. Yes, (although I am not an official reviewer :)), your PR looks good to me. (btw, I was just thinking about this. Algebraic types, sort of. it's the power of typescript, I am not sure how you can achieve that (`string | string[]`) in other statically typed languages like Java or C#. ;)

**Comment by vukers** [comment]
@DerkSchooltink Do you know of a reason why the same prop should not be handled on `ImportedApplicationListener` as well? ([line](https://github.com/DerkSchooltink/aws-cdk/blob/fdfd48ef691a994d616d282740fce6d487597ff2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L492))

**Comment by DerkSchooltink** [comment]
> @DerkSchooltink Do you know of a reason why the same prop should not be handled on `ImportedApplicationListener` as well? ([line](https://github.com/DerkSchooltink/aws-cdk/blob/fdfd48ef691a994d616d282740fce6d487597ff2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L492))

Ah! Oversight on my end, apologies. Can you create an issue, I will submit a PR. :)
