### ISSUE TITLE
Case insensitivity in cognito user pools

### ISSUE THREAD

**Issue by Lasitha92** [aws/aws-cdk#6499]
Trying to use CfnUserPool from @aws-cdk/aws-cognito.
I cannot find a way to enable case insensivity 

![image](https://user-images.githubusercontent.com/16875652/75535566-38c18b80-5a3b-11ea-810e-e97b5559de5f.png)

---

This is a :rocket: Feature Request

**Comment by Lasitha92** [comment]
For anyone searching for this, you can use following in the CfnUserPool construct props ,
`usernameConfiguration: {
   caseSensitive: false
}`

**Comment by IanIsFluent** [comment]
For me this was `new UserPool(this, 'UserPool', {signInCaseSensitive: false})` Unfortunately this is one of those things you can never change after creation :'(
