### ISSUE TITLE
Lambda: support inline code for Runtime.PYTHON_3_8

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#6503]
The CloudFormation documentation seems to imply that *all* node.js and Python runtimes support inline code. We should verify this and correctly enable the flags in those cases.

In particular, it appears PYTHON_3_8 should support inline code but this is prohibited by the current code.

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Unfortunately, inline code support for python3.8 is still not supported by cloudformation - https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/80#issuecomment-587209603 :(

**Comment by meleksomai** [comment]
@nija-at , it seems that it is available now to include InlineCode for Python3_8.

**Comment by mdipirro** [comment]
CDK 1.83.0 (build 827c5f4) still fails if `Code.fromInline(...)` is used with a Python 3.8 runtime.

**Comment by christophgysin** [comment]
@SomayaB @nija-at @NGL321: Could you please review and approve my PR #12788? Thanks!
