### ISSUE TITLE
AWS CodeBuild LinuxBuildImages seem to be out of date

### ISSUE THREAD

**Issue by aripalo** [aws/aws-cdk#6517]
I am quite new to AWS CodeBuild and to `@aws-cdk/aws-codebuild` so I might be missing something here, but it seems to me that the CDK CodeBuild module is out-of-date with its `LinuxBuildImage` class: The static values of `LinuxBuildImage` provides values for build images such as `UBUNTU_14_04_GOLANG_1_11` and `UBUNTU_14_04_NODEJS_8_11_0`, but the platform Ubuntu version is quite old and the runtimes too.

The [Docker images provided by CodeBuild page](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) lists build images such as Ubuntu `18.04` with runtimes such as Go `1.13` and NodeJS `12.14`.

For example, if using CodeBuild to build Lambda functions this is problematic as NodeJS `8.11` is now in end-of-life phase and one can't create Lambda functions with it anymore and if working with Go modules, having access to 1.13 would be nice. 

### Use Case

Support the latest build images from https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

### Other

Current workaround probably is to not use `codebuild.BuildSpec.fromObject` and instead define the buildspec file yaml, but it would be nice to be able to define these in "cdk way".

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by aripalo** [comment]
Oh actually, now did a little digging through… it seems that to use the newer Linux build images in CodeBuild one has to use `codebuild.LinuxBuildImage.STANDARD_3_0` which seems to provide the [newest environments](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/3.0/Dockerfile) (such as Go v1.13 and NodeJS 12).

But I feel this now is actually a documentation issue since the [CDK docs use the old Linux Build images in the examples](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codebuild-readme.html#images ) such as `LinuxBuildImage.UBUNTU_14_04_RUBY_2_5_1`.

So it might be a good idea to update the docs to guide users to use the `STANDARD_3_0` build image instead.

**Comment by skinny85** [comment]
Thanks for opening the issue @aripalo . Notice that the "old" Ubuntu 14.04 images are all deprecated, so that's a hint that they shouldn't really be used.

I'll submit a PR removing mentioning `UBUNTU_14_04_RUBY_2_5_1` from our docs.

Thanks,
Adam
