### ISSUE TITLE
"Invalid subnet group name" for CfnDBCluster

### ISSUE THREAD

**Issue by matwerber1** [aws/aws-cdk#6519]
Hi, 

I successfully create a database subnet group but then, when trying to use it to create an Aurora Serverless PG cluster, receive an error that the subnet group does not exist.

### Reproduction Steps

I created a CfnDBSubnetGroup like below.

```
    const dbSubnetGroup = new rds.CfnDBSubnetGroup(this, 'DatabaseSubnetGroup', {
      dbSubnetGroupDescription: 'Subnet group for Airflow database',
      dbSubnetGroupName: 'AirflowDbSubnetGroup',
      subnetIds: CFG.db.subnetIds
    });
```

`cdk deploy` was successful for the above, and I can see the subnet group in the RDS console. 

I then try to create an Aurora Serverless Postgres cluster per below:

```
    const aurora = new rds.CfnDBCluster(this, 'AuroraAirflow', {
      databaseName: CFG.db.databaseName,
      dbClusterIdentifier: CFG.db.dbClusterIdentifier,
      engine: CFG.db.engine,
      engineMode: CFG.db.engineMode,
      masterUsername: CFG.db.masterUsername,
      masterUserPassword: databasePasswordSecret.secretValue.toString(),
      port: CFG.db.port,
      dbSubnetGroupName: dbSubnetGroup.dbSubnetGroupName,
      vpcSecurityGroupIds: CFG.db.vpcSecurityGroupIds,
      scalingConfiguration: {
        autoPause: CFG.db.autoPause,
        maxCapacity: CFG.db.maxCapacity,
        minCapacity: CFG.db.minCapacity,
      }
    });
```

Then, `cdk deploy` gives the error below: 

### Error Log

```
AuroraAirflow DB subnet group 'AirflowDbSubnetGroup' does not exist. (Service: AmazonRDS; Status Code: 404; Error Code: DBSubnetGroupNotFoundFault; Request ID: cfd07435-a361-45cd-ac1a-bf2c54819e47)
```

### Environment

  - **CLI Version      :** aws-cli/1.16.307 Python/3.7.0 Darwin/18.7.0 botocore/1.13.43
  - **Framework Version:**  CDK version 1.26
  - **OS               :** Mac Mojave 10.14.6
  - **Language         :** Typescript

### Other

I tried first deploying my template with only the db subnet group, in case the subnet group was perhaps created but not yet "ready" for use with Aurora... but I received the same error after then adding in the CfnDBCluster resource. 

Also tried an explicit dependency, below: 

```
aurora.node.addDependency(dbSubnetGroup);
```

--- 

This is :bug: Bug Report

**Comment by matwerber1** [comment]
The issue was that I was using CamelCase in the CDK template, but capital letters were converted to lowercase in the actual name of the subnet group that was created. 

So, the CfnDBCluster was looking for `AirflowDbSubnetGroup` when the real resource was named `airflowdbsubnetgroup`.

**Comment by Nicko-13** [comment]
I have experienced the same issue. I have also noticed that this is inconsistent depending on type of resources I have created. 

Here is the definition of subnet group.

```
        db_subnet_group_name = 'DbSubnetGroup'
        self.__database_subnet_group = CfnDBSubnetGroup(
            self,
            id=db_subnet_group_name,
            db_subnet_group_name=db_subnet_group_name,
            db_subnet_group_description='List of isolated subnet ids',
            subnet_ids=[subnet.subnet_id for subnet in vpc.isolated_subnets]
        )
```

Then I define `CfnDBInstance` and this works fine:

```
        db_name = 'Db'
        self.__database = CfnDBInstance(
            self,
            id=db_name,
            db_name=db_name,
            db_instance_class='db.t2.micro',
            db_subnet_group_name=self.__database_subnet_group.db_subnet_group_name,
            ... # other code omitted for brevity
        )
```

After that I define `CfnDBCluster`:

```
        cluster_name = 'ClusterlDb'
        self.__audit_trail_db = CfnDBCluster(
            scope=self,
            id= cluster_name,
            backup_retention_period=7,
            db_cluster_identifier= cluster_name,
            db_subnet_group_name=self.__database_subnet_group.db_subnet_group_name,
           ... # other code omitted for brevity
        )
```

Which throws the following exception: `DB subnet group 'DbSubnetGroup' does not exist.`
The fix is to add .lower method to the subnet group name:

```
        audit_trail_database_name = 'AuditTrailDb'
        self.__audit_trail_db = CfnDBCluster(
            scope=self,
            id=audit_trail_database_name,
            backup_retention_period=7,
            db_cluster_identifier=audit_trail_database_name,
            db_subnet_group_name=self.__database_subnet_group.db_subnet_group_name.lower(),
           ... # other code omitted for brevity
        )
```
In this case stack creates correctly. And it seems like that different constructs should demonstrate similar behaviour.
