### ISSUE TITLE
Is it not possible to create an A Record for a user-pool created CloudFront target alias?

### ISSUE THREAD

**Issue by royby-cyberark** [aws/aws-cdk#6525]
### The Question
my ultimate goal is to use CDK to create a user pool with my own domain name. for that I need to create an Alias record for the CloudFront that the user pool provides to me, and I cannot find a way to do that.
I am aware of this:
https://github.com/aws/aws-cdk/issues/5357
which may suggest that this is not possible in Python
and also this:
https://github.com/aws/aws-cdk/issues/3776
but this seem to create the CloudFront distribution whereas, I want to point to the target alias that the user pool provides after you set your domain to it. 

I came across this:
https://stackoverflow.com/questions/59063088/creating-cognito-user-pool-with-custom-domain-name-from-aws-cdk
which I used to get the value of the target alias (something like abcdefghijkl.cloudfront.net) which I want to point to.
But I cannot find any way to use it when create an ARecord in CDK as the 'target' parameter.
The SO post says that they used aws-sdk. is this the only way if i'm using Python, or am I missing something?
Thank you for your help.

### Environment

  - **CDK CLI Version:** 1.24.0
  - **Module Version:**  aws_route53* 1.26.0
  - **OS:** macOS Catalina
  - **Language:** Python

**Comment by royby-cyberark** [comment]
Also, if using aws-sdk is my only option, the [SO post](https://stackoverflow.com/questions/59063088/creating-cognito-user-pool-with-custom-domain-name-from-aws-cdk) suggest using a custom resource and then getting the target alias (see link). 
how am I supposed to use the result? since the result is s token, aws-sdk cannot use it directly. 
can I resolve it somehow, or do I need to create another stack that will run after the user-pool stack and pass the output to it?

Thanks

**Comment by 0xdevalias** [comment]
@royby-cyberark check out my response over at https://github.com/aws/aws-cdk/issues/6787#issuecomment-601432895 for some code snippets to get the CloudFront distribution for a custom `UserPoolDomain` using a custom resource, and then use that to create a Route53 A record.

**Comment by royby-cyberark** [comment]
Brilliant, thanks!
