### ISSUE TITLE
Better type database engine versions

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#6532]
Currently, the `engineVersion` of `DatabaseInstance` is a free-form string. Type it into something stronger, like a string enum, so that it's harder to make a mistake on. 

See [here](https://aws.amazon.com/rds/faqs/#Database_Engine_Versions) for the list of supported database engine versions.

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Or an enum-like class, perhaps something similar to [Lambda's `Runtime`](https://github.com/aws/aws-cdk/blob/30d751dc9e5a8359df15373fb2b10f5a2a4bded6/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L25-L25), so that our customers are not blocked from using a new `version` by a CDK upgrade.
