### ISSUE TITLE
Support for CodeBuild builds on AWS EFS mounts

### ISSUE THREAD

**Issue by nataibi** [aws/aws-cdk#6533]
Add support for CodeBuild to build on AWS EFS file system mounts using the new *ProjectFileSystemLocation* .
more info here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html

### Use Case

Create AWS CodeBuild builds on Amazon EFS.

### Proposed Solution

as per the documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Thanks for opening this issue and putting in a PR @nataibi, much appreciated! 👍
