### ISSUE TITLE
RequestAuthorizer.IdentitySources not settable in .NET

### ISSUE THREAD

**Issue by monnecc** [aws/aws-cdk#6538]
If I try to set the property RequestAuthorizer.IdentitySources in my API Gateway setup, I can't create an instance of type IdentitySource (saying it needs to use the Authorization HTTP header). There is an empty constructor of the IdentitySource class and an IdentitySource.Header method which returns a string, but not an IdentitySource instance.

### Reproduction Steps

```
Authorizer = new RequestAuthorizer(this, "Authorizer", new RequestAuthorizerProps
                    {
                        IdentitySources = new[] {  ??????  }
                    })
```

### Environment
NuGet: Amazon.CDK.AWS.APIGateway 1.26.0

--- 

This is :bug: Bug Report

**Comment by monnecc** [comment]
Is there any news on this issue?

**Comment by nija-at** [comment]
Ack. 

There's a type issue here. The type for [`identitySources` here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/authorizers/lambda.ts#L193) should be `string[]`.

I have a fix for this here - https://github.com/aws/aws-cdk/pull/6649

Once this is fixed, your code would look like -

```csharp
new RequestAuthorizer(this, "myrequestauthorizer", new RequestAuthorizerProps {
    IdentitySources = new string[] {
        IdentitySource.Header("myheader")
    }
});
```
