### ISSUE TITLE
Cloudfront Web Distribution Security Policy default does not match console recommendation

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#6547]
Currently, when using SNI, CDK defaults to TLSv1:

https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L64-L71

However, the console recommends using TLSv1.1_2016:

![Screen Shot 2020-03-02 at 1 36 20 PM](https://user-images.githubusercontent.com/630449/75716370-49b50b80-5c8c-11ea-9e91-f838e3fd8fa2.png)

> Choose the security policy that you want CloudFront to use for HTTPS connections. A security policy determines two settings: the SSL/TLS protocol that CloudFront uses to communicate with viewers, and the cipher that CloudFront uses to encrypt the content that it returns to viewers. When you use a custom SSL certificate and SNI, you must use TLSv1 or later. We recommend that you specify TLSv1.1_2016 unless your users are using browsers or devices that do not support TLSv1.1 or later. When you use a custom SSL certificate and dedicated IP addresses, we recommend that you use TLSv1. In this configuration, the TLSv1_2016, TLSv1.1_2016 and TLSv1.2_2018 security policies are not available.

### Reproduction Steps

```ts
import { CloudFrontWebDistribution } from '@aws-cdk/aws-cloudfront'

const sourceBucket = new Bucket(this, 'Bucket');

const distribution = new CloudFrontWebDistribution(this, 'MyDistribution', {
  originConfigs: [
    {
      s3OriginSource: {
      s3BucketSource: sourceBucket
      },
      behaviors : [ {isDefaultBehavior: true}]
    }
  ],
  viewerCertificate: ViewerCertificate.fromAcmCertificate(myExampleCert, {
    aliases: ['mysubdomain.example.com']
  }
});
```

### Error Log

N/A, no error is given, but the distribution is created without using the recommended TLS protocol stated in the console.

### Environment

  - **CLI Version      :**  1.26.0 (build e251651)
  - **Framework Version:** 1.26.0
  - **OS               :** MacOS
  - **Language         :** English

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @blimmer thanks for pointing this out!

I think its actually more of a feature request than a bug. btw if you feel like taking a stab at this we would be happy to provide assistance :)

**Comment by blimmer** [comment]
@iliapolo thanks for recategorizing this. I went back and forth between bug and feature-requests a bunch before just choosing one 😄 

I opened https://github.com/aws/aws-cdk/pull/6601 to correct this issue (and another bug I found in the process)

**Comment by iliapolo** [comment]
Closing this issue for now as we have decided to stick to the current defaults.
