### ISSUE TITLE
[Api Gateway]: Fix typo in Usage Plan Construct Props description

### ISSUE THREAD

**Issue by vaibhav-walia** [aws/aws-cdk#6550]
[Link to the doc page ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.UsagePlan.html#construct-props)

### Description of the apiStages property is:

API Stages to be associated which the usage plan.

### It should be:

API Stages to be associated *with* the usage plan.

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @vaibhav-walia, thanks for noticing this and putting in a PR, much appreciated! 👍
