### ISSUE TITLE
Expose attributes to allow for sensible pre-deploy testing

### ISSUE THREAD

**Issue by kasper-rutten** [aws/aws-cdk#6560]
By allowing users read-back access to a number of critical attributes, tools could be written to run a number of  checks that typically would only be possible after deploying. Tools like this critically leverage the added value of real IaC. By having object oriented cohesions and hierarchies that mimic at least to some extent the deployed architecture, the CDK should allow for these kinds of tests.

### Use Case
Any enterprise trying to leverage the power of AWS CDK that can't justify authoring and maintaining a comprehensive library of constructs. Constructs that comply with their security guidelines and best practices, could implement tools to test an architecture composed of any CDK constructs for that compliance.

Tools to generate graphs of established and allowed communications could provide real added value. At low level that added value could be visualizing architectures for overview, at high level it could be linked to runtime data(flow logs) to optimize running architectures.

### Proposed Solution
In trying to write a tool as described above, I got roadblocked by the construct tree of my proposed architecture not allowing non-tokenized read-back of which ENI-having resource is associated with which security group + rules, or vice versa. I would have expected the L2 constructs to expose this data. Most intuitively would be from a Connections method call like xxx.connections.list_rules().
### Other
I'm a novice CDK practitioner, and I suspect I'm trying to do something that is fundamentally not desirable or possible for some reason. Couldn't really get any closure via gitter, stackoverflow or enterprise AWS support however. 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Hi @kasper-rutten, I am not sure I fully understand your use case. Can you please provide an example of what you are trying to achieve?

**Comment by kasper-rutten** [comment]
@eladb Instead of trying to enforce the cloud sales team’s compliance by writing and maintaining a library of curated constructs for them to architect with, we would like to write a tool that reads back from the construct tree what they are synthing, and checking if that is compliant.

This seemed like a reasonable use case, considering cfn tools exist that do the same in a much more roundabout way(cfn_nag and the like), and it seems like an obvious way to leverage the fact that in CDK, your infra exists as real, OO code. We expected to be able to read from the python objects how they were configured.

Some checks were trivial to implement. However, some information seems impossible to retrieve from the construct tree. Notably, trying to read back which security group belongs to which instance proved impossible. Between the 4 constructs theoretically involved that could contain this info, L2 Instance, L2 SecurityGroup, L1 CfnInstance and L1 CfnSecurityGroup, only the CfnInstance exposes the .security_group_ids attribute. However that attr is tokenized, and therefore not useful.

**Comment by eladb** [comment]
Do you think https://github.com/aws/aws-cdk-rfcs/issues/19 addresses your use case?

**Comment by kasper-rutten** [comment]
Yes. Very much so.

The implementation of that rfc would drastically improve the added value of CDK in my use case. Besides adding post-hoc compliance checks. With very limited overhead I could integrate my CDK architecture with powerful python packages, notably networkx and pygraphviz, allowing me to simulate, visualize and test my architecture without the need to deploy. 

Feel free to close if you deem appropriate.

**Comment by eladb** [comment]
Okay, I am closing here and will follow up on the RFC repo.
