### ISSUE TITLE
Support adding metadata to DnsValidatedCertificate 

### ISSUE THREAD

**Issue by ggoodman** [aws/aws-cdk#6561]
I would like for it to be possible to set metadata on the created ACM certificate.

`DnsValidatedCertificate` relies on a custom resource backed by a lambda function to create and effect the validation for underlying certificate. The tags set on resources of the `Stack` are not propagated from the custom resource through to the lambda function.

### Use Case

We manage a set of 'logical deployment' stacks via the CDK. These are long-lived stacks that are mutated over time and represent the conceptual deployment of one of our services. Instances of the service do not use the CDK but leverage CloudFormation outputs to `Fn::Import` the required resources from the relevant logical deployment stack.

This works fairly well in isolation but falls apart in two ways:

1. We cannot properly attribute the ACM Certificates to the right team for budgeting.
2. Tooling that doesn't use CloudFormation is unable to identify which certificate belongs to which logical deployment because the standard tags we use to classify AWS resources are absent.

### Proposed Solution

The solution would be that tags set on the `DnsValidatedCertificate` are properly propagated to the underlying ACM Certificate.

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Hi @ggoodman - 

Thanks for the feature request, apologies for the delay in response. 

Recently, we -- and the CloudFormation team -- introduced native support for DNS-validated certificates, that doesn't rely on a custom resource and can be directly tagged. See the README for more usage details, but the basics are:

```ts
new Certificate(this, 'Certificate', {
  domainName: 'hello.example.com',
  validation: CertificateValidation.fromDns(myHostedZone), // Route 53 hosted zone
});
```

Would using the `Certificate` construct directly solve this issue for you? The one limitation of the `Certificate` (vs `DnsValidatedCertificate` is that the latter supports requesting certificates cross-region, whereas the former does not.

**Comment by ggoodman** [comment]
We used the CDK for a time to move quickly and prove things out before internal tooling could catch up. Our tooling has now caught up so I can't comment on whether this would do the trick.

That being said, it seems like it would! Thanks for circling back.
