### ISSUE TITLE
missing CloudWatch ComparisonOperator

### ISSUE THREAD

**Issue by surfaslt** [aws/aws-cdk#6563]
## :question: General Issue
When trying to access
aws_cloudwatch.ComparisonOperator.LESS_THAN_LOWER_OR_GREATER_THAN_UPPER_THRESHOLD
I get `AttributeError: LESS_THAN_LOWER_OR_GREATER_THAN_UPPER_THRESHOLD` because it does not exist yet but is needed for `Alarm comparison_operator` that run on Anomaly Detection Metrics as the attribute only accepts enums.

If I try this putting in: `comparison_operator="LESS_THAN_LOWER_OR_GREATER_THAN_UPPER_THRESHOLD",`
I am getting this error which makes sense but there seems to be no cdk-native work around it `jsii.errors.JSIIError: Expected enum value, got "LESS_THAN_LOWER_OR_GREATER_THAN_UPPER_THRESHOLD"`

Can this enum be added please?

### Environment

  - **CDK CLI Version:**  1.23.0 (build 01f326e)
  - **Module Version:**  1.23.0
  - **OS:** OSX Catalina
  - **Language:** Python

### Other information
pip freeze
attrs==19.3.0
aws-cdk.assets==1.23.0
aws-cdk.aws-applicationautoscaling==1.23.0
aws-cdk.aws-autoscaling==1.23.0
aws-cdk.aws-autoscaling-common==1.23.0
aws-cdk.aws-certificatemanager==1.23.0
aws-cdk.aws-cloudformation==1.23.0
aws-cdk.aws-cloudwatch==1.23.0
aws-cdk.aws-cloudwatch-actions==1.23.0
aws-cdk.aws-ec2==1.23.0
aws-cdk.aws-elasticloadbalancing==1.23.0
aws-cdk.aws-elasticloadbalancingv2==1.23.0
aws-cdk.aws-events==1.23.0
aws-cdk.aws-iam==1.23.0
aws-cdk.aws-kms==1.23.0
aws-cdk.aws-lambda==1.23.0
aws-cdk.aws-logs==1.23.0
aws-cdk.aws-route53==1.23.0
aws-cdk.aws-s3==1.23.0
aws-cdk.aws-s3-assets==1.23.0
aws-cdk.aws-sns==1.23.0
aws-cdk.aws-sns-subscriptions==1.23.0
aws-cdk.aws-sqs==1.23.0
aws-cdk.aws-ssm==1.23.0
aws-cdk.core==1.23.0
aws-cdk.cx-api==1.23.0
aws-cdk.region-info==1.23.0
cattrs==1.0.0
importlib-resources==1.0.2
jsii==0.21.2
publication==0.0.3
python-dateutil==2.8.1
six==1.14.0
typing-extensions==3.7.4.1

**Comment by rix0rrr** [comment]
Yes it can. In fact, you could do it yourself if you wanted to:

https://github.com/aws/aws-cdk/blob/212687c1427b4e0e6dde11c69139e5036a1ce087/packages/%40aws-cdk/aws-cloudwatch/lib/alarm.ts#L40

**Comment by surfaslt** [comment]
PR Created https://github.com/aws/aws-cdk/pull/6597
