### ISSUE TITLE
Interface VPC Endpoint cannot get the DNS Entries with cdk.Token

### ISSUE THREAD

**Issue by edermanoel94** [aws/aws-cdk#6566]
Description of the bug: cannot get the dns entries **(vpcEndpointDnsEntries)** to put in lambda environment for use in **ENDPOINT** configuration on **AWS SDK**. i try with cdk.Token.asList, because this property is a array and dont work properly, keeping tokenized.

### Reproduction Steps

This is my cdk, which i ignored some codes,

```
const interfaceVpcEndpoint = new ec2.InterfaceVpcEndpoint(this, 'InterfaceVpcEndpoint', {
            service: ec2.InterfaceVpcEndpointAwsService.SQS,
            vpc: vpc,
            securityGroups: [securityGroup],
        });

// I try to tokezine and make a join for break my array and get a string.
console.log(cdk.Token.asList(interfaceVpcEndpoint.vpcEndpointDnsEntries).join(","));

new DispatcherService(this, 'DispatcherService', vpc, role, capabilityService.queue);
```

Deploy with this command:

`cdk deploy`

### Error Log

this is the console.log for cdk.Token.asList

```#{Token[TOKEN.93]}```

### Environment

  - **CLI Version      :*1.22.0 (build 309ac1b)*
  - **Framework Version:*Node v10.16.3, NPM 6.12.0*
  - **OS               :*Mac OS Catalina*
  - **Language         :*Typescript v3.7.2*

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
