### ISSUE TITLE
Copying assets to a S3 website bucket

### ISSUE THREAD

**Issue by kennu** [aws/aws-cdk#657]
I would like to use AWS CDK to create an S3 bucket with a website configuration, and then sync some HTML asset files to it. This would let me create a reusable Construct that sets up both a REST API and its HTML UI.

Is this possible, or are there plans to make it possible?

When it tried to implement this using TypeScript, I couldn't find a way to setup a "hook" that would run after the CloudFormation deployment to sync the files to S3.

**Comment by eladb** [comment]
Yes, definitely on our radar. The way we would like to support this is via [assets](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_assets.html). Today we only have support for `ZipDirectory` and `File` asset packaging, but it should be trivial to add a `Directory` option which will upload an entire directory and wire up the S3 prefix.

**Comment by kennu** [comment]
That’s good to know. In fact I briefly tried to use ZipDirectory and File but it seemed you cannot control the destination bucket.

**Comment by eladb** [comment]
Yes, assets will use the "CDK Toolkit Bucket" as the destination. I guess for your use case you would want to define the bucket in your stack and specify the destination bucket when you define the asset. That makes sense

**Comment by kennu** [comment]
Yeah basically I'd like to do the same that `aws s3 sync` does: Define the destination bucket and optional object key prefix, and have all files in a folder recursively synced there, with their Content-Types set appropriately.
