### ISSUE TITLE
Stepfunctions: support for SageMaker createModel, createEndpointConfig, createEndpoint and updateEndpoint

### ISSUE THREAD

**Issue by Hari-Nagarajan** [aws/aws-cdk#6572]
I would like to create sagemaker sfn tasks for: createModel, createEndpointConfig, createEndpoint and updateEndpoint 

### Use Case

So I can use these tasks to have a stepfunction that can train data, create a model and then deploy/update an endpoint

### Proposed Solution

I've lightly implemented these already based on the patterns in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-train-task.ts and can contribute these. 

* [x] :wave: I may be able to implement this feature request

**Comment by nija-at** [comment]
Please post a PR when you're ready.

**Comment by Stacy-D** [comment]
Hey all, I'm interested in picking up this issue as my team is relying on custom implementation for these tasks and it would be good to contribute them to where they belong.
Let me know if contributions are welcomed on this one.

**Comment by Stacy-D** [comment]
Hey all, as no one opposed, I went ahead and published a new PR for this feature: https://github.com/aws/aws-cdk/pull/10187 with the hope that we can get the required features merged as soon as possible.

@Hari-Nagarajan  I took some inspiration from your old PR on this issue, so I'll appreciate any comments that you may have.
@shivlaks as you are the one assigned to this issue, I'll appreciate your review for the new PR.

**Comment by Hari-Nagarajan** [comment]
@Stacy-D Thanks for taking this up. I've had to abandon this due to changes in work priority.
