### ISSUE TITLE
`--profile` option is not respected if both AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID defined

### ISSUE THREAD

**Issue by ahmetsevki** [aws/aws-cdk#6574]
If you have `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` exported, then the cdk doesn't respect the `--profile` option and try to make calls to AWS using the set `AWS_ACCESS_KEY_ID` in shell. (If either of them is set this does not happen, both needs to be set)
 

### Reproduction Steps

AWS_SECRET_ACCESS_KEY=local AWS_ACCESS_KEY_ID=local cdk  --profile=someprofile bootstrap

### Error Log

Environment aws://xxxx/us-east-1 failed bootstrapping: Error: Need to perform AWS calls for account xxxx, but no credentials found. Tried: default credentials.

### Environment

  - **CLI Version      :** 1.24.0 (build 6619e36)
  - **Framework Version:** 1.24.0 (build 6619e36)
  - **OS               :** MacOS 
  - **Language         :** cli

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@ahmetsevki - is this still an issue? the `profile` should be respected.

I'd also recommend giving the [cdk credential provider](https://aws.amazon.com/blogs/devops/cdk-credential-plugin/) blog post a read as it simplifies cross-account usage of the CLI.
