### ISSUE TITLE
Auto-tagging existing subnets in aws_eks.Cluster

### ISSUE THREAD

**Issue by shrivastavshubham34** [aws/aws-cdk#6576]
## When can we expect to see automatic tagging of the existing subnets in the aws_eks.Cluster library?

Trying to build an AWS EKS Cluster with AWS CDK in Python.

We have an existing VPC and subnets which need to get some Kubernetes tags like kubernetes.io/role/internal-elb=1 etc.

After running **cdk deploy**, I get the below warning:
```error
[Warning at /stack/some-project-EKS-cluster] Could not auto-tag private subnets with "kubernetes.io/role/internal-elb=1", please remember to do this manually
```

### Environment

  - **CDK CLI Version:** 1.25.0
  - **OS:** all
  - **Language:** Python

**Comment by eladb** [comment]
I don't think that we will be able to provide this capability for existing subnets since we don't have control over their tags. 

Closing for now.

**Comment by shrivastavshubham34** [comment]
Guys, I see some updates on this issue. This still not possible? @eladb @iliapolo

**Comment by iliapolo** [comment]
@shrivastavshubham34 no this is still not possible since CDK cannot tag existing subnets. The updates you are seeing is just some repository cleanup.
