### ISSUE TITLE
Trying to implement VPC with single isolated subnet : facing error

### ISSUE THREAD

**Issue by anandakrishnan-a** [aws/aws-cdk#6578]
I tried to create a VPC with single isolated subnet in typescript.
But ending up with the below issue:
"There are no 'Public' subnet groups in this VPC. Available types: Isolated"
my code :
const vpc = new Vpc(this, awsPrefixName + this.node.tryGetContext("vpcName"), {
      cidr: '10.0.0.0/16',
      enableDnsHostnames: true,
      enableDnsSupport: true,
      maxAzs: 3,
      subnetConfiguration:[
      {
        cidrMask: 24,
        name: "isolated_subnet",
        subnetType: SubnetType.ISOLATED
      }]
    });

I tried to dig the code, it shows subnettype is assigned to public only when placement.subnetType === undefined && placement.subnetGroupName === undefined && placement.subnets === undefined.
Kindly let me know the workaround for creating isolated subnet in vpc.

**Comment by rix0rrr** [comment]
I copy/pasted this code, and it does not throw the error you quoted. That probably means there was code you left out which triggered that particular error. Without that additional code, I cannot diagnose what was going on. Probably, you tried to create something which defaults to a PUBLIC subnet (maybe an internet-facing load balancer?), which this VPC indeed does not have.

-----

We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
