### ISSUE TITLE
TransitGateway failed due to AmazonSideAsn doesn't match type {Integer}

### ISSUE THREAD

**Issue by hertzknight** [aws/aws-cdk#6580]
It looks like the number variable is not being transitioned to an Integer when I run cdk deploy for the TransitGateway.

### Reproduction Steps

```
new CfnTransitGateway(this, 'Transit-Gateway',{
      amazonSideAsn: 4200066801,
    })
```

### Error Log

Property validation failure: [Value of property {/AmazonSideAsn} does not match type {Integer}]

### Environment

  - **CLI Version      : 1.26.0
  - **Framework Version: Node v13.2.0 / NPM 6.14.1
  - **OS               : Mac Catalina 10.15.3
  - **Language         : Typescript 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It synthesizes to the following: 

```
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 4200066801
```

Which is the only correct way to represent a number in YAML.

Something is probably going wrong with the automatic data type detection when CloudFormation parses the YAML, which probably means that it is impossible for everyone (not just CDK-generated templates) to instantiate `AWS::EC2::TransitGateway` using YAML-based templates.

Please report this as a bug on [CloudFormation's bug tracker](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap)
