### ISSUE TITLE
CLI might skip deployments incorrectly

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#6582]
Found at least one situation (during bootstrapping) where the stack creation failed, stack ended up in `ROLLBACK_COMPLETE` (which is an unrecoverable situation) but since CloudFormation still responded with the template that we attempted to deploy the CLI thinks the deployment succeeded (Reported here: https://github.com/aws/aws-cdk/issues/6581)

Fix for this particular instance: check stack state before checking the template.

But more generally, I think we should not do this optimization.

* Assumptions break in the face of CFN parameters
* Assumptions break in the face of side effectful updates (template uses SSM Parameters, SecretsManager secrets).

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
good catch on this issue, i'm taking a look at the optimization we perform since it's essentially a bug now and will remove it
