### ISSUE TITLE
Cannot retrieve elasticache reader endpoint from ReplicationGroup

### ISSUE THREAD

**Issue by maxsap** [aws/aws-cdk#6585]
Elasticache introduced [reader endpoints](https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-elasticache-launches-reader-endpoint-for-redis/)  for making connection management easier.

At the moment this information seems to be missing whenever you create a replication group

**Comment by iliapolo** [comment]
@maxsap I believe this information is available on the `CfnReplicationGroup` object.
- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticache.CfnReplicationGroup.html#attrprimaryendpointaddress
- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticache.CfnReplicationGroup.html#attrprimaryendpointport

You will also find the rest of the attributes on the same. Is that what you meant?

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
