### ISSUE TITLE
@aws-cdk/aws-lambda-nodejs anyone using this with layers?

### ISSUE THREAD

**Issue by nateiler** [aws/aws-cdk#6586]
Is anyone using this Parcel based function class with Lambda Layers.  I'm experiencing an issue where Parcel tires to resolve the `/opt/*` modules.  

`... Cannot resolve dependency '/opt/api-proxy' at '/opt/api-proxy'`

and in my lambda i've got something like:

```
import {
  ApiEvent,
  ApiHandler,
  ErrorCode,
  ApiResponse,
  ResponseFactory,
  Transaction
} from "/opt/api-proxy";
...
```

I've tried using the [parcel-plugin-externals ](https://github.com/FlorianRappl/parcel-plugin-externals) plugin.

### Environment
  - **CDK CLI Version:** 1.27.0
  - **Language:** TypeScript

**Comment by eladb** [comment]
@jogold can you take a look?

**Comment by jogold** [comment]
> I've tried using the [parcel-plugin-externals ](https://github.com/FlorianRappl/parcel-plugin-externals) plugin.

Can you detail how you tried with `parcel-plugin-externals`?

**Comment by nateiler** [comment]
In my experience, `parcel-plugin-externals` doesn't support absolute path references. As a result the code from a layer is included in the package.

package.json
```
{
     "alias": {
          "./src/opt/api-proxy": "../api-proxy/"
     },
     "externals": {
         "/opt/api-proxy": "*"
       }
}
```

**Comment by jogold** [comment]
> In my experience, `parcel-plugin-externals` doesn't support absolute path references

Have you tried with https://github.com/FlorianRappl/parcel-plugin-externals#dynamic-dependency-resolution?

**Comment by nateiler** [comment]
I have not.  I believe it only gets to the plugin if a module is found.  And Parcel interprets an absolute path as not a node module.

https://github.com/parcel-bundler/parcel/blob/d2dc7c96331f015bdf67ff8286dbb95de2dd6c9b/src/Resolver.js#L91

https://github.com/FlorianRappl/parcel-plugin-externals/issues/9

**Comment by jogold** [comment]
OK, I understand. Can you detail your use case and why your are working with a layer instead of "local" files that parcel could bundle?

**Comment by jogold** [comment]
@nateiler is this still relevant with the latest `NodejsFunction` and `esbuild`? `bundling.externalModules` supports paths and wildcards (https://esbuild.github.io/api/#external).

**Comment by nateiler** [comment]
After working with layers for a while we ended up switching to webpack.  Thanks for the follow up.
