### ISSUE TITLE
[GLUE ETL JOB] When trying to create "S3" connection for a GlueJob, it throws a "No enum constant" error

### ISSUE THREAD

**Issue by Akshay-Mukkavilli** [aws/aws-cdk#6587]
Creation of AWS::Glue::Connection fails with No enum constant error

This could probably be a feature request. I'm creating a bug since I'm not entirely sure that there's no solution.

### Reproduction Steps

```
def create_glue_etl_job(self, catalog_id):
        iam_policy = aws_iam.PolicyStatement(
            resources=["*"],
            actions=[
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "glue:*",

                "iam:ListRolePolicies",
                "iam:GetRole",
                "iam:GetRolePolicy"
            ]
        )
        logs_policy = aws_iam.PolicyStatement(
            resources=["arn:aws:logs:*:*:/aws-glue/*"],
            actions=[
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ]
        )
        iam_role = aws_iam.Role(
            scope=self,
            role_name=CONFIG.performance_glue_etl_job_role(),
            path="/pgi/",
            id=CONFIG.performance_glue_etl_job_role(),
            assumed_by=aws_iam.ServicePrincipal("glue.amazonaws.com")
        )

        iam_role.add_to_policy(iam_policy)
        iam_role.add_to_policy(logs_policy)

        s3_connection = aws_glue.CfnConnection(
            scope=self,
            id="some_connection_id ",
            catalog_id=catalog_id,
            connection_input=aws_glue.CfnConnection.ConnectionInputProperty(
                connection_properties={
                    "paths": "s3://pgi-performance-esdl-ingestion-bucket",
                },
                connection_type="s3",
            )
        )

        glue_job = aws_glue.CfnJob(
            scope=self,
            id=CONFIG.performance_glue_etl_job_name(),
            name=CONFIG.performance_glue_etl_job_name(),
            glue_version="1.0",
            command=aws_glue.CfnJob.JobCommandProperty(
                name="glueetl",
                python_version="3",
                script_location="s3://aws-glue-scripts-XXXXXXXXXX-us-east-1/admin",
            ),
            role=iam_role.role_arn,
            connections=aws_glue.CfnJob.ConnectionsListProperty(connections=[
                    "some_connection_id "
                ]),
            allocated_capacity=10

        )
        return glue_job
```

### Error Log

 6/9 | 10:43:51 PM | CREATE_FAILED        | AWS::Glue::Connection           | something No enum constant com.amazonaws.daylight.core.connection.datamodel.entities.ConnectionType.s3 (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: 47648b1e-5abc-4431-b7f5-e89756297b25)
	/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:49
	\_ Kernel._wrapSandboxCode (/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8298:20)
	\_ Kernel._create (/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:26)
	\_ Kernel.create (/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7585:21)
	\_ KernelHost.processRequest (/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7372:28)
	\_ KernelHost.run (/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7312:14)
	\_ Immediate._onImmediate (/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7315:37)
	\_ processImmediate (internal/timers.js:456:21)

### Environment

  - **CLI Version      :**  CDK 1.27.0
  - **OS               :**  ubuntu-16.04
  - **Language         :** Python 3.7

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @Akshay-Mukkavilli 

It looks like the `s3` connection type is simply not yet supported by CloudFormation.

See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html

We encourage you to reach out to CloudFormation [support](https://forums.aws.amazon.com/forum.jspa?forumID=92) forums and/or [create](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/new) a feature request to CloudFormation. Once support is added, your CDK app should work fine.

Closing this issue for now, please feel free to re-open if needed.

Thanks
