### ISSUE TITLE
Lazily add principals to iam.PolicyStatement

### ISSUE THREAD

**Issue by bweigel** [aws/aws-cdk#6588]
## :question: General Issue

I would like to do create a high level construct for a KMS-Key where I need to modify the key policy:

```typescript
export class S3KmsSseKey extends kms.Key {
    private allowedAccounts: string[]

    constructor(scope: cdk.Construct, id: string, props?: kms.KeyProps) {
        super(scope, id, props);
        const statement = this.makePolicyStatementForExternalAccountAccess();
        this.addToResourcePolicy(statement);
    }

    public addAllowedAccount(account: string) {
        if (this.allowedAccounts === undefined) {
            this.allowedAccounts = [];
        }
        this.allowedAccounts.push(account)
    }

    private makePolicyStatementForExternalAccountAccess() {

        const statement = new iam.PolicyStatement({
            resources: ["*"],
            principals: cdk.Lazy.listValue({ produce: () => this.allowedAccounts }).map(accountId => new iam.AccountPrincipal(accountId)),
            actions: [
                "kms:CreateGrant",
                "kms:ListGrants",
                "kms:RevokeGrant",
            ],
            conditions: {
                bool: {
                    "kms:GrantIsForAWSResource": true
                }
            }
        });
        return statement
}
```
...to satisfy the interface for `PolicyStatementProps`:
https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L294

However, using `cdk.Lazy.xyz` like this (i.e. functional chaining of a `.map(...)`) results in an error:

``` 
/home/bweigel/Projects/.../node_modules/@aws-cdk/core/lib/resolvable.ts:161
      throw new Error(`Cannot add elements to list token, got: ${xs}`);
            ^
Error: Cannot add elements to list token, got: arn:,[object Object],:iam::#{Token[TOKEN.20]}:root
```

### The Question

Is there any possibility of getting around this?
Meaning can I either:
- a) create a PolicyStatement with a different interface (i.e. `principals: string[]`)
- b) use functional chaining with `cdk.Lazy.listValue`
- c) ???

### Environment

  - **CDK CLI Version:** 1.27.0 (build a98c0b3)
  - **Module Version:** 1.22.0
  - **OS:** Ubuntu 18.04.4 LTS
  - **Language:** TypeScript

**Comment by rix0rrr** [comment]
Do the `.map()` inside the `Lazy` instead of outside it.

----

We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
