### ISSUE TITLE
Assets: allow specifying destination bucket

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#659]
Brought up in #657: for use cases like uploading an asset directory to a website bucket, we should allow specifying the bucket when defining an asset.

**Comment by kennu** [comment]
I'd like to add the note that the current code in https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/assets.ts doesn't seem to perform any auto-detection of Content-Type based on filename extensions. I think it will be required to successfully deploy HTML/CSS/JS and other web assets.

**Comment by eladb** [comment]
Users can use s3-deployment to upload files to S3 buckets.

**Comment by asyschikov** [comment]
What about specifying a bucket for Lambda Function code?

**Comment by IngussNeilands** [comment]
Asset target is CDK deployment bucket, we should not be using that to store our lambda zip assets - I would like to suggest reopening this ticket and allowing to specify target bucket for s3 assets.

**Comment by avikaza** [comment]
Giving the ability to specify Asset destination bucket will enable many models. 
(For example) If we have a parent stack which uses SAM deploy wants to do all of the deployment steps for a nested stack which is using `cdk deploy`. we can just do `cdk synth` on nested stack and specify parent stacks deployment bucket as nested stack asset destination.

If there is an easier way of achieving what I described above, please educate me.
