### ISSUE TITLE
aws-batch creates an "UNMANAGED" compute environment even when 'managed' property is set to true

### ISSUE THREAD

**Issue by ayush987goyal** [aws/aws-cdk#6590]
aws-batch creates an "UNMANAGED" compute environment even when 'managed' property is set to true. Ref doc: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.ComputeEnvironment.html

This might be related to typo in [this](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-batch/lib/compute-environment.ts#L341) line

### Reproduction Steps

1. Create a new `ComputeEnvironment`
2. Check the AWS Batch console and inspect the generated compute environment

### Environment

  - **CLI Version      :** 1.27
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by zechariahks** [comment]
I have seen this issue as well. Found that the issue will be fixed in this pull request.. https://github.com/aws/aws-cdk/pull/6549
