### ISSUE TITLE
Bucket serverAccessLogsPrefix can't be defined independently from serverAccessLogsBucket

### ISSUE THREAD

**Issue by lanwen** [aws/aws-cdk#6599]
Here defined validation that `prefix` couldn't be specified without the `bucket`

https://github.com/aws/aws-cdk/blob/c9b074b28b26a537fb81b9a4a431df6412964c59/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1296

But in fact, [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-loggingconfig.html) don't say anything about this dependency and actually it works perfectly fine independently with the raw CF

### Reproduction Steps

```javascript
new s3.Bucket(scope, "Bucket", {serverAccessLogsPrefix: "pref"});
```

### Error Log

`Error: "serverAccessLogsBucket" is required if "serverAccessLogsPrefix" is set`

### Environment

  - **CLI Version      : *1.27.0 (build a98c0b3)*
  - **Framework Version: *1.27.0*
  - **OS               : *mac*
  - **Language         : *js*

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @lanwen, thanks for reporting this! 

Indeed seems like an oversight - would you be interested in contributing a fix for this? :)

**Comment by lanwen** [comment]
@iliapolo Yes, I'd like to provide a fix
