### ISSUE TITLE
Does AWS CDK provide constructs to deploy ECS applications using rolling deployments?

### ISSUE THREAD

**Issue by shamhub** [aws/aws-cdk#6605]
We generally use BlueGreen & Rolling deployment strategy to deploy/update docker containers in ECS container instances.

--------------

Ansible ECS modules allow implement such deployment strategies(rolling deployment) with below modules:

https://docs.ansible.com/ansible/latest/modules/ecs_taskdefinition_module.html

https://docs.ansible.com/ansible/latest/modules/ecs_task_module.html

https://docs.ansible.com/ansible/latest/modules/ecs_service_module.html

------------

Does AWS CDK provide such constructs to deploy ECS applications?

**Comment by hencrice** [comment]
Hey @shamhub This requires support from the Cloudformation service side and we are actively working on it. You can find the tracking issue [here](https://github.com/aws/containers-roadmap/issues/130).

**Comment by shamhub** [comment]
> Hey @shamhub This requires support from the Cloudformation service side and we are actively working on it. You can find the tracking issue [here](https://github.com/aws/containers-roadmap/issues/130).

Am not sure why the question title has changed? I have re-corrected the question title and my actual question

**Comment by hencrice** [comment]
Hey @shamhub so I suppose you would like to see both blue/green & rolling deployments? I will contact our product team regarding the second deployment strategy and get back to you.

**Comment by shamhub** [comment]
> Hey @shamhub so I suppose you would like to see both blue/green & rolling deployments? I will contact our product team regarding the second deployment strategy and get back to you.

Priority wise... I would like to see "Roling deployment" first and then "B/G deployment" next

**Comment by hencrice** [comment]
For rolling update, I think this is what you want: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.DeploymentControllerType.html.

You can specify the deployment controller type when creating a service construct: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Ec2Service.html

**Comment by jcragg** [comment]
@hencrice now that support for ECS blue/green this has been added to CFN, can we expect to see this functionality available in CDK soon?

**Comment by shamhub** [comment]
> @hencrice now that support for ECS blue/green this has been added to CFN, can we expect to see this functionality available in CDK soon?

What ecs modules in ansible?  for Blue green

**Comment by MrArnoldPalmer** [comment]
Hey there, we are working to implement this. Gonna close this in favor of https://github.com/aws/aws-cdk/issues/6605.

**Comment by shamhub** [comment]
Check this NPM plugin which helps with blue-green deployment using CDK.

https://www.npmjs.com/package/@cloudcomponents/cdk-blue-green-container-deployment
