### ISSUE TITLE
availabilityZone is mandatory inside SubnetAttributes while using Subnet.fromSubnetAttributes

### ISSUE THREAD

**Issue by nirvana124** [aws/aws-cdk#6607]
### The Question
To get subnet details if we are using Subnet.fromSubnetAttributes  we are required to pass SubnetAttributes. Inside SubnetAttributes we have availabilityZone which is defined as mandatory.
Even if we do not pass empty string there it works fine.
Can we make availabilityZone optional or i am missing something here ?

Subnet.fromSubnetAttributes(this, 'MySubnet', {
        subnetId: 'sb-123456789',
        availabilityZone: ''
      })
Also inside cfn template only subnet ids are present.

### Environment

  - **CDK CLI Version:** 1.27.0
  - **Module Version:** 1.27.0
  - **OS:**  Windows 10
  - **Language:** TypeScript

**Comment by rix0rrr** [comment]
AZs will be used sometimes in subnet selection (such as, for example, to evaluate subnet queries using `onePerAz: true`).

If you don't care about those, it's fine to pass an empty string.

We can consider making the AZ property optional and throw a runtime error if you use a mechanism that uses AZ information saying something like "you must specify AZs if you want to do this."

We'll consider it as a feature request.
