### ISSUE TITLE
[RDS] Associated roles on database cluster

### ISSUE THREAD

**Issue by PikeDev** [aws/aws-cdk#6610]
It is not yet possible to specify associated roles to a database cluster through the CDK.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-associatedroles

### Use Case

Deploying a database cluster that is configured for S3 integration.

### Proposed Solution

Adding a DatabaseClusterRole high level construct to allow adding associated roles to the DatabaseCluster construct.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @PikeDev, thanks for opening this issue and putting in a PR, much appreciated! 👍
