### ISSUE TITLE
AWS FireLens integration in ECS task definition needs container dependency ordering

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#6613]
When the ECS task definition [adds the FireLens sidecar container](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L464-L477) it does not define any container dependency ordering for the containers that depend on the sidecar.

This can in some cases result in the application container starting up and emitting logs that are lost because FireLens is not yet running to receive them.

To fix this we just need to add a healthcheck to the FireLens sidecar container and use ContainerDefinition.addContainerDependency() with the HEALTHY condition, so that the dependent container does not start until FireLens is up, healthy, and able to receive logs

I will work on a fix for this next week

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
This will be encompassed in @nathanpeck 's work on the ECS add-on feature.
