### ISSUE TITLE
AWS Batch JobQueue does not provide computeResources required for managed ComputeEnvironment 

### ISSUE THREAD

**Issue by ayush987goyal** [aws/aws-cdk#6615]
AWS Batch `JobQueue` does not provide `computeResources` required for managed ComputeEnvironment. Since `JobQueue` does not require the user to provide a `computeEnvironmentOrder`, the default `ComputeEnvironment` created by it should provide some `computeResources` as required by `ComputeEnvironment`.

Need to be fixed after the change in #6549 

### Reproduction Steps

1. Create a `JobQueue`
2. Try to deploy. 

### Error Log

You will get the following error

> computeResources is missing but required on a managed compute environment

### Environment

  - **CLI Version      :** 1.27.0
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by andrestone** [comment]
Hmm.. I see no solution other than creating an "unmanaged" `computeEnvironment` on the `JobQueue` constructor or make it a required property. Actually I see the latter case as more appropriate.

Defining default `computeResources` makes no sense to me.

Thoughts?

**Comment by ayush987goyal** [comment]
Yes I agree. Default `computeResource` is very rare and would only we used when the compute defaults actually match you would need. I think we can make `computeEnvironments` a required prop.

**Comment by iliapolo** [comment]
I think that making the `computeEnvironments` property required at this stage is better. It makes more sense to me for any use case that isn't just sanity testing. Maybe we can think of a default compute environment later on. And even then I would probably prefer having something like `ComputeEnvironment.lotsOfMemory()` to help users, rather than implicitly creating the defaults. 

@andrestone Feel like whipping up a PR?

**Comment by ayush987goyal** [comment]
While we are at it, can we also add a small overview [page](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-batch-readme.html) with content similar to what I am including in example usage of batch with sfn [here](https://github.com/ayush987goyal/aws-cdk/blob/pr/invoke-batch/packages/%40aws-cdk/aws-stepfunctions/README.md#batch-example).

**Comment by iliapolo** [comment]
@ayush987goyal You're right. It was an oversight in the initial [PR](https://github.com/aws/aws-cdk/commit/c8a22b176cdee7da2cde15c38a6fc107686cf2d0#diff-332fea72f9417955a167b0c2561bf600) that introduced these L2's. 

@andrestone Has already added some content to the page with the launch template support [PR](https://github.com/aws/aws-cdk/pull/6602). 

I wouldn't want to overwhelm this PR with adding all this content right now. I will create a separate issue for completing the README with all the necessary examples and explanations. 

Sound good?
