### ISSUE TITLE
Read CloudFormation stack API Gateway output

### ISSUE THREAD

**Issue by lukehedger** [aws/aws-cdk#6618]
### The Question

It is possible to read CloudFormation stack outputs via the AWS CLI like so:

```sh
aws cloudformation describe-stacks --stack-name TestStack --query "Stacks[0].Outputs[?OutputKey=='TestAPIGatewayEndpoint'].OutputValue" --output text
```

How can I do this in a CDK app using the Constructs Library? Specifically, I am trying to get the API Gateway endpoint from a deployed stack and pass that to an S3 bucket website in another stack.

### Environment

  - **CDK CLI Version:** 1.27.0
  - **Module Version:** 1.27.0
  - **OS:** OSX
  - **Language:** TypeScript

**Comment by shivlaks** [comment]
@lukehedger A simpler way to read stack outputs was missing until aws-cdk `1.32.0` which added the ability to specify `--outputs-file` with your deploy command to write the stack outputs to a file you can read. Stack outputs will be keyed under the stack name. Learn more by taking a look at the [documentation](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/README.md#outputs)

Let me know if that helps!
