### ISSUE TITLE
lambda-layer-kubectl does not have a version 1.13.7

### ISSUE THREAD

**Issue by orangewise** [aws/aws-cdk#6634]
I'm getting this error when while updating my eks cluster: 

Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA] is invalid. Application arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl does not have a version 1.13.7 

The updates ran fine until last week.

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by john-bakker** [comment]
same here as well, tried to install an eks-cluster and got this error message : 

```
ClusterStack failed: Error: Failed to create ChangeSet CDK-233dd538-73cf-4ce3-824a-b8267f39a910 on ClusterStack: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA] is invalid. Application arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl does not have a version 1.13.7
Failed to create ChangeSet CDK-233dd538-73cf-4ce3-824a-b8267f39a910 on ClusterStack: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA] is invalid. Application arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl does not have a version 1.13.7
```

checked the code in the aws-cdk master repo and found the following :
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-eks/lib/kubectl-layer.ts

```
import * as lambda from '@aws-cdk/aws-lambda';
import { CfnResource, Construct, Stack, Token } from '@aws-cdk/core';
import * as crypto from 'crypto';

const KUBECTL_APP_ARN = 'arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl';
const KUBECTL_APP_VERSION = '1.13.7';

export interface KubectlLayerProps {
```

it seems the version of kubectl is hardcoded, but not longer available in this repo

**Comment by orangewise** [comment]
Seems to be working with version `1.27.0`...

**Comment by JamesLuoau** [comment]
Hi, we have same issue. What happened to people like us can't (have time) upgrade to newest 1.27, we can't run any CDK command now.

**Comment by eladb** [comment]
Apologies for the breakage. I am looking into it.

**Comment by pahud** [comment]
Looking into it now.

**Comment by pahud** [comment]
Hi @eladb 

I have verified and I can deploy `1.13.7` from my two different AWS accounts either in `us-west-2` or `ap-northeast-1` and the version does exist.

<img width="998" alt="圖片" src="https://user-images.githubusercontent.com/278432/76291788-c7aa8f80-62e8-11ea-86df-bd1d6f2529a7.png">

**Comment by john-bakker** [comment]
Hi @pahud, I upgraded my cdk to 1.27, then it worked, but it wasn't on 1.19.0. Luckily I could upgrade without too much issues but can imagine this isn't the case for everyone.

**Comment by eladb** [comment]
@pahud identified that this issue only happens in us-east-2. For some reason the app is not replicated in there. We are investigating internally.

**Comment by JamesLuoau** [comment]
Hi @eladb our stack is in ap-southeast-2 and have same issue

**Comment by john-bakker** [comment]
> @pahud identified that this issue only happens in us-east-2. For some reason the app is not replicated in there. We are investigating internally.

This is not the case, if you read my error message it said us-east-1

**Comment by pahud** [comment]
> Hi @eladb our stack is in ap-southeast-2 and have same issue

@JamesLuoau 

yes this layer version is also missing in `ap-southeast-2`.  Thank for the heads-up.

<img width="1546" alt="圖片" src="https://user-images.githubusercontent.com/278432/76311159-4a444680-630b-11ea-8f84-32e276944a1b.png">

@john-bakker  Actually when we deploy the SAR application to any AWS regions in `aws` partition, we always specify the ApplicationId with `us-east-1` but it should pull the SAR application locally from the region you are deploying to. We are investigating this issue.

**Comment by pahud** [comment]
This issue should be fixed internally. Apologies for the breakage.
