### ISSUE TITLE
S3 bucket cannot be created if region is set

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#6646]
I'm trying to get Lambda@Edge working with Cloudfront in CDK. To make things easy, I was hoping that I could override my default region (`us-west-2`) for my whole stack so that the Lambda would be deployed in `us-east-1`, as required by Lambda@Edge functions.

However, when I set the region as a `prop`, the S3 bucket creation fails with status code 400.

If I remove the `region` property, the bucket is created without a problem.

### Reproduction Steps

```
export abstract class ExampleStack extends Stack {
  constructor(scope: Construct, id: string, props) {
    super(scope, id, {
      env: {
        region: "us-east-1",
      },
    });
	
	new Bucket(this, "MyBucket", {
	  bucketName: 'somesuch-bucket-foobar',
    }
  }
}
```

### Error Log

```
 1/3 | 3:21:58 PM | CREATE_FAILED        | AWS::S3::Bucket    | Bucket (Bucket83908E77) Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 0FB9C10A83924370; S3 Extended Request ID: Vr8/8sYPDksJgYQ1IaFbpAA32xHSCohJnyXGoVjAOo1Z6gsQ5eHGNmQ06sEfsi6WaC3Y/1IcNfo=)
```

### Environment

  - **CLI Version      :**  1.27.0 (build a98c0b3)
  - **Framework Version:**  1.27.0
  - **OS               :**  macOS
  - **Language         :**  en-us

### Other

--- 

This is :bug: Bug Report

**Comment by blimmer** [comment]
Interestingly, if I add account to the env, e.g.,

```
{
  env: {
     region: 'us-east-1',
     account: 'my-account-number-here'
  }
}
```

It seems to work.

**Comment by blimmer** [comment]
Actually, I think my previous message was a red herring. I think the problem was actually because I had previously created a bucket with the same name in a different region. If I change the bucket name to something else, it works.

The error message coming back from S3 could definitely be improved to make that clearer. Today, for whatever reason, I got this error:
```
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: D298BD580B3CFA0E; S3 Extended Request ID: P+meTRAxKVXhETeXU9nHxnZl5UQ2ypS+1IeI9tdFSqU+f6a2ysQ9pcBWG+VajJW362GVV5dkwvY=)
```

Which led me to this comment: https://github.com/hashicorp/terraform/issues/2774#issuecomment-280156579

**Comment by iliapolo** [comment]
@blimmer It seems like you managed to resolve the problem. Can we close this issue?

**Comment by blimmer** [comment]
Hey @iliapolo - thanks for checking back in. Yep, I think we're good to close this.

For future travelers, if you run into this, a few things to try:

1. Are you trying to recreate an s3 bucket in a new region, after you deleted a bucket with the same name from another region? If so, that can cause the 400 status code. I couldn't find official documentation on this, but it seems like the name is "released" for the bucket to be recreated in a new region 24 hours after it's deleted in the old region.

2. From the [docs](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_credentials_prop), it looks like you should pass the account number *and* and the region if you try to specify a region in the `env` param.

**Comment by J-Swift** [comment]
Man, the 'same name in different region' issue just sucked a large chunk of time from me. I was able to recreate the bucket with the name in the same region, and I could create the bucket with a new name in a different region, but I couldn't reuse the (already deleted) bucket name in a new region.

I doubt its something for CDK to fix, but it should really have a better error output. Instead I'm just left with `Bad Request Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request` and no idea why it is failing.

**Comment by ansman** [comment]
Same here, I had the exact same experience as @J-Swift. I spent 2 hours try to debug this. Perhaps if the error message could be included instead of just the code this would be easier to debug.

**Comment by jonmadison** [comment]
Luckily, you all had already had the problem so i didn't have to spend as much time on the issue, but i learned something today. :)

**Comment by Yarles404** [comment]
Makes me wonder what it would take to have the bucket name free up immediately in other regions.
Anyways, ditto on the terrible error message.
