### ISSUE TITLE
AwsCustomResource support for log retention

### ISSUE THREAD

**Issue by mcalello** [aws/aws-cdk#6652]
Currently, whenever an AwsCustomResource is deployed it creates its own Lambda function - with the LogRetention set to INFINITE.  This feature requests is asking for that to be overridable by an additional Contruct prop within the AwsCustomResource or the AwsSdkCall.

### Use Case

Without this feature, teams must manually find and delete logs created by these lambdas.

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Copy: @jogold

**Comment by mcalello** [comment]
@eladb Thank you! 👍  Question - is there any task on the RoadMap for Function/SingletonFunction to use the LogRetention construct - that is comprised of both logRetentionDays and the related Role?

**Comment by jogold** [comment]
@mcalello do you mean using the custom resource with log retention and also a custom IAM role for this log retention (`logRetentionRole` prop)? Can you open a new feature request for that?

**Comment by mcalello** [comment]
Thanks @jogold - I was about to do that, when I realized that there's a construct that would capture both of those mentioned above.  But if Lambda isn't going to support that soon - yes, we would need to add the logRetentionRole prop to AwsCustomResource.
