### ISSUE TITLE
How to resolve id (for example vpc id)

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#6656]
I have an app with two stacks. The first stack creates a VPC. The second stack needs to grab the id of the vpc created by the first, write it to a file so that it can be uploaded using `BucketDeployment`. 
The first stack writes the vpc id to its output.
I'm running cdk deploy on the first stack only, so that it's guaranteed to exist.
Now, in the second stack: How can I reference the vpc id output created by the first? I'm assuming this is the only way to reference ids between stacks in the same app (just for clarity, these are actual ids that only exist after the vpc has been created. It won't help to just pass in a cloudformation reference/token. The actual id is needed).

From the documentation I don't understand how to reference the output of another stack - in the same app or external.
I'm using python.

---

This is a 📕 documentation issue

**Comment by thibaut-singlefile** [comment]
This approach worked for me: https://stackoverflow.com/a/57586393/705661 but only works when the stacks are in the same region.

**Comment by rix0rrr** [comment]
Inside the same app you don't have to do gymnastics.

Sharing to outside the app, I can think of a couple solutions:

* Write to SSM Parameter Store (can be done in-template)
* Custom resource to write the data anywhere (requires some custom scripting)

----

We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.

**Comment by trondhindenes** [comment]
> Inside the same app you don't have to do gymnastics
An example would be awesome. I cannot find any documentation on it.
