### ISSUE TITLE
Update the ReadMe with a link to our Slack room (in addition to the Gitter room)

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#6669]
## :question: General Issue

I'm convinced that we can provide a better experience for CDK questions. The Gitter channel seems cluttered and we're not able to discuss things in separate threads in the channel. It's also easy to overlook a question, which leaves questions unanswered.

### The Question
Can we move the community to a place that supports threads and has a more user friendly UI?

I'm a really big fan of the https://devopschat.co/ slack community because it also has channels for general AWS support, terraform, networking, etc. 

Please let me know what your thoughts are and if this is the right place for this question.

**Comment by robertd** [comment]
@abelmokadem I think they've already tried moving away from Gitter to [Spectrum.chat](https://spectrum.chat/aws-cdk?tab=posts) but I don't think that came to fruition.

**Comment by abelmokadem** [comment]
Maybe it's good for now to at least list the "unofficial" slack channels in the README.md.

**Comment by skinny85** [comment]
I can see changing the ReadMe.
