### ISSUE TITLE
Multiple ways to invoke Lambda function as a Step Functions task

### ISSUE THREAD

**Issue by shivlaks** [aws/aws-cdk#6676]
There are currently multiple ways to invoke a Lambda function through Step Functions [tasks](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html#activity)

`InvokeFunction` - initial offering by Step Functions to invoke a Lambda function. 
`RunLambdaTask` - latest mechanism to invoke a Lambda function. includes all the functionality as `InvokeFunction` but also enables the capability to pause a workflow until a task token is returned or fire and forget.

Both of these mechanisms are valid in the Amazon States Language

### Proposed Solution

* Mark the `InvokeFunction` task as as deprecated and guide users towards using the newer `RunLambdaTask`. This solution is less abrasive than simply removing the legacy mechanism as there are likely customers who will not want to be forced to migrate. 

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
duplicate of #4801

**Comment by eikeon** [comment]
@shivlaks, The RunLambdaTask does not appear to offer the sync running of a lambda that the InvokeFunction did. Has the initial offering by Step Function to (synchronously) invoke a Lambda function been deprecated? I've not seen any documentation suggesting that.

The use case I'm currently working on has a Lambda function that's meant to be run synchronously and modifying it to fit the service integration pattern (that doesn't support sync in the case of lambda) only complicates it. Is the intent to have RunLambdaTask also support sync?

**Comment by shivlaks** [comment]
@eikeon You can invoke Lambda functions asynchronously through `RunLambdaTask`. The [invocation type](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.RunLambdaTaskProps.html) property on the Lambda is how you would specify that the Lambda should run synchronously

The default is [`REQUEST_RESPONSE`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.InvocationType.html) which will invoke the function synchronously.

Here is the relevant Step Functions [documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_RequestSyntax)
> Invoke the function synchronously. Keep the connection open until the function returns a response or times out. The API response includes the function response and additional data.

I'm wondering if it's the `FIRE_AND_FORGET` setting at the service integration level itself that's confusing here because it potentially leads users to think that the function will be invoked asynchronously. Can you expand on what threw you off? We should consider simplifying if possible.

**Comment by eikeon** [comment]
You're correct in your wondering, I didn't work out that FIRE_AND_FORGET would correspond to synchronous. I'll test that out now.

Also thrown off by the service integration not listing sync support for the lambda case here: https://docs.aws.amazon.com/step-functions/latest/dg/concepts-service-integrations.html

**Comment by eikeon** [comment]
When switching from InvokeFunction to RunLambdaTask w/ FIRE_AND_FORGET I see a TaskStarted with ```{
  "resourceType": "lambda",
  "resource": "invoke"
}``` but it looks like the lambda is getting no input.

```TypeScript
        const getObj = new sfn.Task(this, "Get Obj", {
            task: new tasks.InvokeFunction(getObjectLambda, {}),
        });

        const getObject = new sfn.Task(this, "Get Object", {
            task: new tasks.RunLambdaTask(getObjectLambda, {
                integrationPattern:
                    sfn.ServiceIntegrationPattern.FIRE_AND_FORGET,
            }),
            resultPath: '$.GetObjectResult',
        });
```

I also tried adding `payload: sfn.TaskInput.fromDataAt('$')` -- which looks like the default but still no input.

Did I mess up what the RunLambdaTask should look like to get it to ask like InvokeFunction (which is passed the tasks entire input)?

**Comment by shivlaks** [comment]
@eikeon you did not, that's a bug - fixed by #7428 will be released in the next version

**Comment by eikeon** [comment]
@shivlaks Thank you. I'm all sorted with the possible exception of where to add documentation so other don't take the FIRE_AND_FORGET detour. Looks like the defaults of FIRE_AND_FORGET and RequestResponse etc leave RunLambdaTask acting like InvokeFunction did. Thanks again

**Comment by eikeon** [comment]
Upgraded to version 1.36.1 to switch to and test RunLambdaTask. I'm now able to get the right input to the lambda, but I'm not able to return the lambda's output as the task output via adding `outputPath: "$.Payload",` to the sfn.Task. Which the current overview has as an example. When doing so I get 
```json
{
  "error": "States.Runtime",
  "cause": "An error occurred while executing the state 'Get Object' (entered at the event id #2). Invalid path '$.Payload' : No results for path: $['Payload']"
}
```

**Comment by shivlaks** [comment]
@eikeon - what does your Lambda function produce as output? are you able to take a look at the Step Functions console to see what the output of the step was?

**Comment by eikeon** [comment]
The output of the Lambda is what's in the Payload I'm seeing in the Step Functions console under the `TaskSucceeded` event. Before the following event `ExecutionFailed` shows the above invalid path. I have both a outputPath: '$.Payload', and a resultPath: '$.GetObjectResult' if that matters? I can open a new issue in the morning if this is a bug, can't see what I'm doing wrong at this point. But it's the end of a long day.

```
{
  "resourceType": "lambda",
  "resource": "invoke",
  "output": {
    "ExecutedVersion": "$LATEST",
    "Payload": {
      "Done": true,
      "Next": null,
      "BitsFetched": 0
    },
    "SdkHttpMetadata": {
      "HttpHeaders": {
        "Connection": "keep-alive",
        "Content-Length": "41",
        "Content-Type": "application/json",
        "Date": "Thu, 30 Apr 2020 00:39:33 GMT",
        "X-Amz-Executed-Version": "$LATEST",
        "x-amzn-Remapped-Content-Length": "0",
        "x-amzn-RequestId": "dc8e5c92-28b4-41fd-a7bf-90970b93f51a",
        "X-Amzn-Trace-Id": "root=1-5eaa1e45-f6d040f0e5b2480a56f2dba4;sampled=0"
      },
      "HttpStatusCode": 200
    },
    "SdkResponseMetadata": {
      "RequestId": "dc8e5c92-28b4-41fd-a7bf-90970b93f51a"
    },
    "StatusCode": 200
  }
}
```

**Comment by shivlaks** [comment]
@eikeon the example just uses the task result as output (default of '$')

seems like you have your output inside output so you'd want `$.output.Payload`
the `resultPath` does affect what goes to state output and from what you have it'd append whatever you reference to the state input.
