### ISSUE TITLE
Batch ComputeEnvironment LaunchTemplate not updated

### ISSUE THREAD

**Issue by reisingerf** [aws/aws-cdk#6686]
### The Question
How can I best get around the limitation that the Batch ComputeEnvironment does not support updating of its LaunchTemplate?

As far as I can tell, I am faced with destroying and re-creating my entire Batch stack whenever I make the slightest change to my LaunchTemplate.

### Environment

  - **CDK CLI Version:** all? (1.26.0 (build e251651) in my case)
  - **Module Version:** aws-cdk.aws-batch==1.25.0
  - **OS:** all
  - **Language:** all

### Other information
This issue was briefly discussed in [this][1] issue and goes back to the limitation mentioned in the AWS Batch [docs][2]:
> AWS Batch does not support updating a compute environment with a new launch template version.

My current CDK code can be seen [here][3]

[1]: https://github.com/aws/aws-cdk/issues/6427#issuecomment-597122999
[2]: https://docs.aws.amazon.com/batch/latest/userguide/launch-templates.html
[3]: https://github.com/umccr/infrastructure/blob/4d8bedf946c97fb62df7b9f369919dab732b1ddd/cdk/apps/umccrise/stacks/batch.py#L154-L189

**Comment by iliapolo** [comment]
Closing this as there doesn't seem to be a reasonable solution for this except for CFN support.

**Comment by iliapolo** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=318580

**Comment by brainstorm** [comment]
@iliapolo Are you aware of any issue filed upstream in CFN for this?

**Comment by iliapolo** [comment]
@brainstorm I guess the root cause of this issue is the fact that batch itself doesn't support updating the launch template. 

To that end, CFN can only "workaround" the issue by identifying changes to the launch template and recreating the environment. And actually in that sense, CDK can do the same, without explicit CFN support. 

The question is, what kind of solution is really desired here? If we don't want to recreate the env, than we are stuck until batch supports it, if we are ok to re-create it, then we can talk about way the CDK can help.

**Comment by iliapolo** [comment]
> Closing this as there doesn't seem to be a reasonable solution for this except for CFN support.

This isn't entirely accurate. See https://github.com/aws/aws-cdk/issues/6686#issuecomment-644032869

**Comment by reisingerf** [comment]
@iliapolo Thanks for your update! We appreciate the help!

I agree, ideally that is fixed upstream in Batch (and I hope it found it's way in their roadmap), but without that I believe we are stuck having to destroy and re-deploy our entire stack whenever the LaunchTemplate is changed. And since we are running custom user data via the LaunchTemplate that happens quite frequently. 

We also have to remember to destroy/deploy when we change the LaunchTemplate, which is error prone.
It would be a big help if the compute environment alone could be recreated, instead of all the other bits and bobs we have in our stack. Either by way of manually "tainting" the resource like in TerraForm or even better if the environment could autodetect the change and flag itself for recreation. If such a thing is even possible...

**Comment by iliapolo** [comment]
@reisingerf yeah i see what you mean. I think we can possibly do some nice tricks here to make this a bit less painful. 

Stay tuned! :)

I'm re-opening this so we have it on our radar.

**Comment by iliapolo** [comment]
Note to self: We could possibly hash the dynamic parts of the launch template and use the hash as a tag of the compute environment. It seems like changes to tags cause a recreation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html#cfn-batch-computeenvironment-computeresources-tags

So this might actually work.

**Comment by reisingerf** [comment]
Thanks a lot for looking into this, @iliapolo !!

**Comment by bounlu** [comment]
This still remains as an issue today. $Latest tag in the compute environment is not effective to use the latest version of the launch template.

**Comment by blisst** [comment]
Still an issue

**Comment by damienleger-cure51** [comment]
My workaround to this inspired by @iliapolo comment https://github.com/aws/aws-cdk/issues/6686#issuecomment-644094715

I make sure default version of launch template is updated on every update + add this version number as a tag on autoscaling group to enforce compute environment recreation on launch template update

Terraform code below (aws provider 5.100) with the non-interesting parts removed for brevity.


```
resource "aws_launch_template" "lt" {
  name_prefix = "example-lt"

  # last update is set to the new launch template default version
  update_default_version = true

  ...
}

resource "aws_batch_compute_environment" "ce" {
  # need to use a name_prefix to be able to create_before_destroy on modification
  # update fail with default destroy before create because aws_batch_job_queue cannot be empty
  compute_environment_name_prefix = "example-ce-"

  compute_resources {
    ...
	
    launch_template {
      launch_template_id = aws_launch_template.lt.id
    }

    # launch template on underlying autoscaling group is not updated: https://github.com/aws/aws-cdk/issues/6686
    # this tag set on autoscaling group, enforce autoscaling group recreation on launch template change
    # inspired by https://github.com/aws/aws-cdk/issues/6686#issuecomment-644094715
    tags = {
      lt-version = aws_launch_template.lt.default_version
    }
  }

  lifecycle {
    create_before_destroy = true
  }
  ...
}

resource "aws_batch_job_queue" "jq" {
  name     = "example-jq"
  priority = 1
  state    = "ENABLED"
  compute_environment_order {
    order               = 1
    compute_environment = aws_batch_compute_environment.ce.arn
  }
  ...
}
```
