### ISSUE TITLE
Vpc.fromLookup fails in Java

### ISSUE THREAD

**Issue by magnusalstad** [aws/aws-cdk#6688]
I've created a VPC in one App and tried to import this VPC using fromLookup in another app. The output generated at app-synth in Java is invalid as it always contains "VpcId": "vpc-12345". This happens regardless of options I use in the VpcLookupOptions, even when i set vpcId in lookup options explicitly to another value. 

_Just to be sure I didn't do anything wrong I wrote the same pice in TypeScript on the same computer and it worked just fine._

### Reproduction Steps
**Create VPC in one app:**
```java
public class VpcCreateApp extends App {
    public VpcCreateApp() {
        Stack myStack = Stack.Builder.create(this, "createStack").stackName("createStack").build();
        Vpc vpc = Vpc.Builder.create(myStack, "vpc").subnetConfiguration(List.of(SubnetConfiguration.builder()
                .subnetType(SubnetType.PUBLIC).name("Public").build())).build();
        SecurityGroup.Builder.create(myStack, "sg").vpc(vpc).securityGroupName("sg").build();
    }
}
```
**Import the VPC in another app**
```java
public class VpcImportApp extends App {
    public VpcImportApp() {
        Stack myStack = Stack.Builder.create(this,"myStack").stackName("myStack")
                .env(Environment.builder().account(<my real account id>").region("eu-west-1").build()).build();
        IVpc importVpc = Vpc.fromLookup(myStack, "importVpc", VpcLookupOptions.builder().vpcName("vpc").build());
        SecurityGroup.Builder.create(myStack,"mysg").vpc(importVpc).securityGroupName("sgName").build();
    }
}
```
### Error Log

The synth output of this import Vpc App is:
```console
{
  "Resources": {
    "mysg339A1FFD": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "myStack/mysg",
        "GroupName": "sgName",
        "SecurityGroupEgress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow all outbound traffic by default",
            "IpProtocol": "-1"
          }
        ],
        **"VpcId": "vpc-12345"**
      }
    }
  }
}
```

### Environment

  - **CLI Version      :** 1.27
  - **Framework Version:** 1.27
  - **OS               :** Mac OS Catalina (10.15.3)
  - **Language         :** Java

### Other

As it works in typescript with same npm/node version etc I would not expect it's related to environment but the Java cdk sdk.
--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Please paste the output of `cdk synth -v`.

**Comment by magnusalstad** [comment]
Hi, sorry for the late answer! After you request for synth -.v output I did further investigations and was able to make it work using the cdk init --langeuage=java layout.

The problem was related to that we did a synth in java first then deploying the output afterwards with the CDK command line tool. This seemed to cause problems looking up an existing VPC, but works just fine for everything else. I suppose that the cdk command provides some environment or service for the java App to talk to during synth phase.

I guess what we really miss to support our own workflow, is the ability to be independent of cdk.json  and the strict module layout (with one app per java module) enforced by the cdk init --language=java. 
So we would really like the https://github.com/aws/aws-cdk/issues/601 to be implemented.

Br. Magnus

**Comment by rix0rrr** [comment]
We suggest a default way of working in our init template to not overwhelm new starters with choices. As you become more experienced using CDK, you may feel that some of our default patterns don't suit you.

There is not necessarily a limit of one CDK executable per set of classes. CDK needs "an" entry point, an will read one from `cdk.json` if you don't supply one, but you can use a different entry point for each `cdk synth` invocation if you care to (which you can obviously wrap in any set of scripts to make it more convenient to use):

```
cdk --app 'mvn exec:java -Dexec.mainClass="my.Class1"' deploy
cdk --app 'mvn exec:java -Dexec.mainClass="my.Class2"' deploy
```

Will close this issue now.
