### ISSUE TITLE
retentionInDays for logs.LogGroup using a CfnParameter throws an error

### ISSUE THREAD

**Issue by nmoutschen** [aws/aws-cdk#6690]
When using the retention property in logs.LogGroup and provide the value of a parameter, it throws an error that the number is negative: `retentionInDays must be positive, got -1.888154589708755e+289`. This exception seems to be [thrown by the LogGroup](https://github.com/aws/aws-cdk/blob/874516ba25705c6e9ee6f56c0420929e9f51e2b5/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L339).

Here is the CfnParameter:

```typescript
const retentionInDays = new cdk.CfnParameter(this, "RetentionInDays", { default: 30, type: "Number" });
```

The log group:

```typescript
new logs.LogGroup(this, "PreAuthLogGroup", {
  logGroupName: "/aws/lambda/"+preAuthFunction.functionName,
  retention: retentionInDays.valueAsNumber
});
```

### Reproduction Steps

1. Create a stack with the two resources mentioned above.
2. Run `cdk synth`.

### Error Log

```
retentionInDays must be positive, got -1.888154589708755e+289
```

### Environment

  - **CLI Version      :** 1.27.0
  - **Framework Version:** 1.27.0
  - **OS               :** MacOS
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Validation shouldn't happen if the input is a `Token.isUnresolved()`.
