### ISSUE TITLE
ECR repository/S3 Bucket of assets needs clean up

### ISSUE THREAD

**Issue by DerkSchooltink** [aws/aws-cdk#6692]
# Please +1 [Garbage Collection RFC](https://github.com/aws/aws-cdk-rfcs/issues/64)

Original title:  (was Lifecycle support for DockerImageAssets)

It would be helpful to apply lifecycle rules for the ECR to which `DockerImageAsset`'s are pushed to.

### Use Case

Right now CDK automatically defines the repository and keeps all previous images stored in there. Because of rapid prototyping this causes a lot of images to build up. In order to save cost on storing these images and to declutter the interface from old unused images it would be neat to be able to define a lifecycle for these images. 

### Proposed Solution

Ideally it would be possible to define lifecycle rules for the `DockerImageAsset` itself, but exposing the `Repository` construct through `DockerImageAsset#repository` instead of the generic `IRepository` interface would also work:

```
import {DockerImageAsset} from "@aws-cdk/aws-ecr-assets";

const image = new DockerImageAsset(this, "Image", {
  directory: "path/to/dockerfile"
});

image.repository.addLifecycleRule({maxImageCount: 30})
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
@rix0rrr @eladb, how does this fit into the "single repository : n images" strategy? Can we add a method that lets you add lifecycle rules at the image level (by targetting specific tags based on the assets unique ID perhaps?) in addition to exposing at the repository level?

**Comment by DerkSchooltink** [comment]
> @rix0rrr @eladb, how does this fit into the "single repository : n images" strategy? Can we add a method that lets you add lifecycle rules at the image level (by targetting specific tags based on the assets unique ID perhaps?) in addition to exposing at the repository level?

What about exposing a field on `DockerImageAsset` that allows for defining a repository yourself? That allows us to create an ECR separately (with the lifecycle rules) and would not mess with the single repository setup.

Example:

```
const repository = new Repository(this, 'Repository');
repository.addLifecycleRule({maxImageCount: 5});

const image = new DockerImageAsset(this, "Image", {
    directory: "path/to/dockerfile",
    repository: repository
});
```

**Comment by luxaritas** [comment]
Concurred - would also like to enable scanOnPush in addition to the lifecycle policy

**Comment by peterjuras** [comment]
Any update on this?

**Comment by eladb** [comment]
The current way image assets work in the CDK implies that a single ECR repository is used for all asset images. You can use [cdk-ecr-deployment] in order to deploy image assets to a specific ECR repository in your control.

As for garbage collecting images from the assets ECR repository, this is something we plan to add at some point as part of a broader garbage collection capability (applies to buckets as well).

Please +1 this RFC if you want to see this prioritized: https://github.com/aws/aws-cdk-rfcs/issues/64

[cdk-ecr-deployment]: https://constructs.dev/packages/cdk-ecr-deployment/v/0.0.59?lang=typescript

**Comment by zacyang** [comment]
At least could we have the `ScanOnPush`  configuration exposed?

**Comment by blimmer** [comment]
With the new `dockerTagPrefix` behavior (see https://github.com/aws/aws-cdk/pull/17028/files), you can kind of manually start to do this. For instance, you can tag your image with some recognizable prefix and then manually create a lifecycle rule. I agree that this should be built-in and "just work" per the RFC.

**Comment by jonathan-kosgei** [comment]
@rix0rrr is there any workaround for this? Our AWS bill is up tens of thousands of dollars a year due to ECR storage.

**Comment by blimmer** [comment]
You might give https://github.com/jogold/cloudstructs/blob/master/src/toolkit-cleaner/README.md a try (see the linked RFC above for where I found this: https://github.com/aws/aws-cdk-rfcs/issues/64#issuecomment-1027026969). That construct has worked well for me.

**Comment by lge-micropole** [comment]
I see everywhere that ECR image **assets** are managed by the CDK deployment and should be like a black box for users (which brings pain, when looking at security findings e.g.). 

Wouldn't it be possible to create an ECR Image **Resource**? (even if the ECR resource is a copy of the Asset), so that we could then reference it from other resources?

**Comment by joao-moonward** [comment]
Hello everyone! This issue seems quiet. Any feedback?

**Comment by MrArnoldPalmer** [comment]
No updates currently but there is a third party construct to help enable this for those that need something in the interim https://constructs.dev/packages/cloudstructs/v/0.6.18/api/ToolkitCleaner?lang=typescript

For tracking a built in solution https://github.com/aws/aws-cdk-rfcs/issues/64 is the place to watch.

**Comment by arminnajafi** [comment]
I've been needing this feature too.

**Comment by evgenyka** [comment]
Closing in favor of https://github.com/aws/aws-cdk-rfcs/issues/64

**Comment by peterjuras** [comment]
@evgenyka is the implementation planned on the roadmap and is there an ETA? Closing in favor of an RFC does not inspire a lot of confidence that this feature will be prioritised.
