### ISSUE TITLE
Incorrect documentation on elbv2 package (open on listener default true)

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#6694]
https://github.com/aws/aws-cdk/blame/c3ee41366b3f0a59864decd47d2feea9849fd095/packages/%40aws-cdk/aws-elasticloadbalancingv2/README.md#L42

I think this should get some priority. The default for the `open` property is set to true.

https://github.com/aws/aws-cdk/blob/7f8c90decd58d2016611e6f94fc506156e047b59/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L73

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Sorry, what do you wish to report exactly?

> 'open' is the default

I guess this might be confusingly phrased. Would you prefer 

> 'open: true' is the default

?

**Comment by abelmokadem** [comment]
I see what got me confused. I'm on the road now but why is the example using open: true and not open: false. The latter would make more sense

**Comment by rix0rrr** [comment]
The example is highlighting this option as one you are likely to want to change, but I agree it might be confusing.
