### ISSUE TITLE
What is an interview? Typo in README?

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#6695]
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/README.md#parameters

> Parameter values can be overwritten by supplying the --force flag. Example of overwriting the topic name from a previous interview

What is an "interview"? Is this a typo?

---

This is a 📕 documentation issue

**Comment by DerkSchooltink** [comment]
Seems to be a typo. Opened a PR to fix some of the documentation regarding CDK CLI, there were some other formatting issues as well. I hope this helps! @rittneje
