### ISSUE TITLE
Why is `aws-sam` module in developer preview?

### ISSUE THREAD

**Issue by abiro** [aws/aws-cdk#6696]
Doc page: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-sam-readme.html

I'm wondering why the `aws-sam` module is in developer preview. The documentation says:

> This is a developer preview (public beta) module.
>
> All classes with the Cfn prefix in this module (CFN Resources) are auto-generated from CloudFormation. They are stable and safe to use.
>
> However, all other classes, i.e., higher level constructs, are under active development and subject to non-backward compatible changes or removal in any future version. These are not subject to the Semantic Versioning model. This means that while you may use them, you may need to update your source code when upgrading to a newer version of this package.

But it seems to me that there are only CFN resources in the module? Am I missing something?

Thanks!

---

This is a 📕 documentation issue

**Comment by ccfife** [comment]
Hi abrio, 

I understand the confusion. We are in the process of updating our stability tags, and wanted to make sure people know that the cfn* constructs are always stable and safe to use. At the moment we have 2 labels: 1) **experimental** that is automatically applied to new construct libraries, and 2) **stable** that is applied to construct libraries with mature high-level constructs.

We are moving toward using labels that match the stages outlined in the [construct library lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md). So expect to see labels like CFN-only, experimental, developer preview, and stable.

**Comment by ccfife** [comment]
The aws-sam module is now correctly labeled as "CFN-RESOURCES: STABLE"  https://docs.aws.amazon.com/cdk/api/latest/docs/aws-sam-readme.html
