### ISSUE TITLE
Add support for custom S3 bucket ACLs

### ISSUE THREAD

**Issue by michaelday008** [aws/aws-cdk#6703]
I can't seem to find a way through CDK or cloudformation to add custom ACLs to an S3 bucket.

### Use Case

We are using CDK to create a cross account pipeline similar to the reference pipeline provided by AWS here: https://aws.amazon.com/blogs/devops/aws-building-a-secure-cross-account-continuous-delivery-pipeline/

We have a tools account, a dev account, and a prod account.  The beginning stage of the pipeline monitors an ECR repository in the tools account, plus s3 buckets in the dev and prod accounts that contain elastic beanstalk configuration deploy.zip files.

The dev and prod s3 source actions assume a role in the dev and prod accounts that gives them permission to read the deploy.zip files from the dev and prod s3 buckets.

The problem is that even though I have added roles and policies to allow the dev/prod accounts s3:* permissions to the pipeline artifact bucket, the source stage still fails with a rather generic (and likely incorrect) message that 'the provided role does have permissions'.  As soon as I go into the AWS console and add an ACL to the pipeline artifact bucket to allow those accounts, it starts working, hence my assumption that the error message is incorrect because it has nothing to do with the role, but with the bucket ACLs instead.

So it appears that the legacy ACL system is preventing the full access policies from being applied cross account as by default, all S3 buckets with public access blocked only have a single ACL granting the owning account permissions.

Obviously in a fully-automated world, deploying this great pipeline with CDK should not have to be followed up with manual s3 ACL tweaking using the UI.

### Proposed Solution

I'm not sure how this would be implemented.  I could not find any concrete examples of doing this even in cloudformation after spending several hours reading documentation.  There are canned ACLs, but they are not suitable for adding cross account ACLs as they do not allow you to specify a source account.

### Other

---

This is a :rocket: Feature Request

**Comment by michaelday008** [comment]
After further investigation, I'm not sure if this is needed anymore.

I think this was a case of trying to read between the lines for multiple different documents and examples that had a slightly different use case than ours.

I have filed a bug report (https://github.com/aws/aws-cdk/issues/6708) regarding the related issue.

If you feel that the ACLs are not necessary because the use case covered in https://github.com/aws/aws-cdk/issues/6708 will work fine once that bug is fixed, or the documentation updated to be more clear about the need for the `/*` after the bucket ARN, then you can close this ticket.

**Comment by skinny85** [comment]
@michaelday008 do the CodePipeline sources work correctly cross-account now that you fixed the bucket's Resource Policy, like you mentioned in #6708?

BTW, the CodePipeline construct should handle these permissions automatically (even if the source buckets are in a different account) - if it doesn't, then it is a bug.

**Comment by michaelday008** [comment]
@skinny85 The codepipeline sources do work correctly now that I fixed the bucket's Resource Policy.

I did note that the permissions were able to be added to a bucket created with CKD but did not get updated on a bucket that was imported.  On the imported bucket, I had to set them manually.

**Comment by iliapolo** [comment]
@michaelday008 You mentioned:

> I did note that the permissions were able to be added to a bucket created with CDK but did not get updated on a bucket that was imported. On the imported bucket, I had to set them manually.

This is the expected behavior. 

See https://github.com/aws/aws-cdk/issues/6548 to keep track on updating policies for imported buckets. 

Closing this issue, please re-open if there is still a need.
