### ISSUE TITLE
aws-batch compute-environment builds spot fleet role arn incorrectly

### ISSUE THREAD

**Issue by damonmaria** [aws/aws-cdk#6706]
`getSpotFleetRole` in `compute-environment.js` in `aws-batch` builds the arn like so:
```javascript
                return iam.Role.fromRoleArn(this, 'Resource-SpotFleet-Role', `arn${core_1.Aws.PARTITION}iam::${this.stack.account}:role/aws-service-role/spotfleet.amazonaws.com/AWSServiceRoleForEC2SpotFleet`);
```

It's missing `:` around the partition so he resulting arn looks like:
```
arnawsiam::XXXXXXXX:role/aws-service-role/spotfleet.amazonaws.com/AWSServiceRoleForEC2SpotFleet
```

### Reproduction Steps

```javascript
new batch.ComputeEnvironment(this, 'test', {
  computeResources: {
    desiredvCpus: 0,
    instanceTypes: [instanceType],
    type: ComputeResourceType.SPOT,
    vpc,
  },
  managed: false,
})
```

### Error Log

```
CLIENT_ERROR - Parameter: SpotFleetRequestConfig.IamFleetRole is invalid.
```

### Environment

  - **CLI Version      :** 1.26.0
  - **Framework Version:** 1.26.0
  - **OS               :** MacOS 10.15.3
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by damonmaria** [comment]
Even after fixing the role that role does not exist. So I'm not sure if fixing this just uncovers another bug.

**Comment by iliapolo** [comment]
Hi @damonmaria - Thanks for reporting this!

It indeed looks like a bug with missing `:` around the partition. 

Can you tell me please where exactly are you seeing this error though?

```console
CLIENT_ERROR - Parameter: SpotFleetRequestConfig.IamFleetRole is invalid.
```

Is it on stack creation time? job submission? 

Also, you mentioned:

> Even after fixing the role that role does not exist. So I'm not sure if fixing this just uncovers another bug.

The `AWSServiceRoleForEC2SpotFleet` role is not created as part of the `ComputeEnvironment` - it is assumed to exist. Its best to create it once using these [instructions](https://docs.aws.amazon.com/batch/latest/userguide/spot_fleet_IAM_role.html ).

I'm acknowledging the `:` bug and prioritizing it. 

Note that we have just release version [`1.28.0`](https://github.com/aws/aws-cdk/releases/tag/v1.28.0) which contains many fixes and changes (though unrelated to this issue) to the `batch` library. I suggest you upgrade :)

Thanks!

**Comment by damonmaria** [comment]
@iliapolo 

> Can you tell me please where exactly are you seeing this error though?

Sometime after the batch job is submitted the compute environment will go INVALID with this error. You can also see it in CloudTrail. 

> Note that we have just release version 1.28.0 which contains many fixes and changes

Thanks!
