### ISSUE TITLE
@aws-cdk/aws-datapipeline.CfnPipeline don't need to require `parameterObjects`

### ISSUE THREAD

**Issue by ufoo68** [aws/aws-cdk#6711]
## @aws-cdk/aws-datapipeline.CfnPipeline don't need `parameterObjects`

I think [@aws-cdk/aws-datapipeline.CfnPipeline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-datapipeline.CfnPipeline.html) on CfnPipelineProps, `parameterObjects` is not required and `pipelineObjects` is required (if pipelineObjects is empty, cdk-deploy cause an error).

Because, aws-cdk able to define parameters using programing language(TypeScript etc..)

**Comment by iliapolo** [comment]
Hi @ufoo68.

The code you are referring to is auto generated from the CloudFormation specifications. You can see in the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-datapipeline-pipeline.html#cfn-datapipeline-pipeline-parameterobjects) that:

- `parameterObjects` is required.
- `pipelineObjects` is **not** required.

You say there is an error when `pipelineObjects` is not specified, can you share the error and the code you used to deploy?

Thanks

**Comment by ufoo68** [comment]
Sorry, it is a not bug.  This issue is just my option. CloudFormation on the doc specify `parameterObjects` is required, so `parameterObjects` is not nullable on aws-cdk.
I basically do not use `parameterObjects`  for develop the datapipeline using aws-cdk.

However, I understand that this library is based on cloudformation docs. I close this issue
