### ISSUE TITLE
rds: Reboot the construct library

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#6713]
The RDS construct library today closely mimics how resources type are organized in CloudFormation - 

<img src="https://user-images.githubusercontent.com/16217941/76615594-420e2600-651a-11ea-934f-cd390caae842.jpg" height="350">

The additional constructs such as `DatabaseSecret` does add value over simply using the L1 constructs. However, there are a number of modeling restrictions that come with this. A few instances of this are -
1. The list of database engine versions are different depending on the database engine picked that is picked - https://aws.amazon.com/rds/faqs/#Database_Engine_Versions
2. Some properties apply to only some database engines but not others, such as [`timezone`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-timezone) that applies only to SQL Server. This leads to guard rails based development where there are validations all over the place, and the user has to keep adjusting to avoid these validations and take the working path.
3. An extension of #2 but applies more broadly to [Parameter Groups](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_WorkingWithParamGroups.html). Parameters like the `inno_db_file_per_table` will apply to Mysql and Aurora but not to other database types. Similarly, the [`aurora_load_from_s3_role`](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.LoadFromS3.html) applies to Aurora databases but not others.

Codifying all of this in the current RDS model will lead to fragmented code, validations lying around and overall, a poor customer experience where a feature is advertised as available (i.e., it's in the `Props` interface) but is actually not because there is validation that prevents it based on the database type (or some other condition).

The alternative is to reboot the construct library along the lines of creating constructs such as `AuroraDatabase`, `MysqlDatabase`, `AuroraDBCluster`, etc. which would make this experience significantly better.

**Comment by nija-at** [comment]
One more customer complaint and case for why we need this - https://github.com/aws/aws-cdk/issues/7072

**Comment by eladb** [comment]
Is it possible to offer subclasses for specific database types with all the specific APIs in there and leave the current api in tact. We can also do this incrementally (that is implement one subclass, Then another...)

**Comment by nija-at** [comment]
Definitely possible.

However, my feeling is that module is going to cause long term maintenance and customer usage pain. For instance, this PR - https://github.com/aws/aws-cdk/pull/6611 - the work was to simply add a property to the CDK interface that needs to get passed down to two different CloudFormation resources (the DB cluster and parameter group). 
The amount of code that needed to be written behind defensive code block was quite high and the number of iterations of the PR could have been significantly reduced if we had the correct model in place.

**Comment by skinny85** [comment]
We decide to forgo this large "reboot" in favor of incremental improvements, and minimizing breaking changes.
