### ISSUE TITLE
[Bug] RDS tries to replace a database when setting the StorageEncrypted setting to the default value

### ISSUE THREAD

**Issue by thibaut-singlefile** [aws/aws-cdk#6718]
RDS tries to replace a database when setting the StorageEncrypted setting to the default value which should not be required.

### Reproduction Steps

1. Create an RDS database with default settings: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html
    ```Typescript
    const instance = new DatabaseInstance(stack, 'Instance', {
        engine: rds.DatabaseInstanceEngine.POSTGRES,
        instanceClass: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.SMALL),
        masterUsername: 'syscdk',
        vpc
    });
    ```
1. Run `cdk deploy` (this will create a database where `StorageEncrypted` is set to `false`)
1. Explicitely set RDS database `StorageEncrypted` setting to `false`
    ```Typescript
    const instance = new DatabaseInstance(stack, 'Instance', {
        engine: rds.DatabaseInstanceEngine.POSTGRES,
        instanceClass: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.SMALL),
        masterUsername: 'syscdk',
        vpc,
        storageEncrypted: false
    });
    ```
1. Run `cdk deploy` 

Expected: succeeds with No Changed Detected
Actual: Tries to replace the database and fails

### Error Log

![image](https://user-images.githubusercontent.com/59576766/76651068-17739b80-6521-11ea-8f87-0db4c1ad0219.png)

### Environment

  - **CLI Version      :** aws-cli/1.16.310 Python/3.8.1 Darwin/19.2.0 botocore/1.13.46
  - **Framework Version:** cdk/1.27.0
  - **OS               :** macOS Catalina version 10.15.2
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Unfortunately, this is behaviour is from CloudFormation. There is nothing we can do for this in the CDK.

Internal refernce: i/CFN-31220

**Comment by alex9311** [comment]
If I'm seeing the same behavior for setting a port on an existing RDS instance is that the same cloudformation behavior? I have an existing RDS instance running postgress on port `5432` but the port wasnt explicitly set on the `new DatabaseInstance` call. If I add `port: 5432` it tries to replace my existing RDS instance
