### ISSUE TITLE
Add a KMS alias to the new bootstrapping stack

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#6719]
Now that we have a KMS key in the new bootstrapping stack, it would be great to also have a KMS alias there (so i't obvious in the console when looking at the key what is it for).

**Comment by NetaNir** [comment]
I think it's also required for convention mode?

**Comment by skinny85** [comment]
> I think it's also required for convention mode?

Interestingly, no. That's because the Key is set on the Bucket level - which means any operations on it will implicitly use that Key (unless overridden when calling S3 APIs, but we know this won't happen in our assets upload). For that reason, you don't need to know the identifier of the Key (you do need permissions for it though).
