### ISSUE TITLE
Add support for Launch Templates

### ISSUE THREAD

**Issue by NetaNir** [aws/aws-cdk#6734]
Currently the CDK configures EC2 autoscaling using  LaunchConfigurations, we should add support for  [Launch Templates](https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates.html)  which enables more advanced features such as: 

* [Mixed auto scaling groups](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html)
* Versioning

**Comment by NetaNir** [comment]
Related issues:
* https://github.com/aws/aws-cdk/issues/3077
* https://github.com/aws/aws-cdk/issues/6714
* https://github.com/aws/aws-cdk/pull/6290

**Comment by MajaScherman** [comment]
Hello. I was wondering if there is an ETA of this ticket. It would be very helpful if it were implemented for my team.

**Comment by pahud** [comment]
Are we going to support [AWS::EC2::LaunchTemplate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html) first? Is there any PR working on this?

**Comment by ddneilson** [comment]
Also relevant (some LT & ASG design discussion going on) : https://github.com/aws/aws-cdk/issues/1403

**Comment by rix0rrr** [comment]
https://github.com/aws/aws-cdk/issues/1403#issuecomment-603931579

**Comment by dvonessen** [comment]
I would also appreciate the availability of a plain LaunchTemplate Construct instead of the low level CFNLaunchTemplate Construct.

**Comment by chrispernicano** [comment]
As others have commented, support for launch templates is something my team would like to see implemented soon. Is there any ETA on when this might be fixed?

**Comment by moby04** [comment]
It seems that a bunch of other tickets mentioning this issue got closed with this issue as favored one but there are no updates here. Any ETA on the topic?

**Comment by NetaNir** [comment]
The issue is still open, we don't have an ETA to when it will be added.

**Comment by mingteoh** [comment]
anyone has a workaround to overcome this issue before it gets implemented (without using lc)? I got stuck with alb-listener-tg-asg-lt relationship. 

first line in https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchConfiguration.html says "We strongly recommend that you do not use launch configurations." but if this ticket does not get priorities then I have to give up on cdk, not to mention this is first project i am using cdk.

and this ticket is going to have its first birthday cake very soon...

**Comment by zstarkebaumcalico** [comment]
I was able to create a workaround for this. My specific need was to be able to set gp3 as the volume type and also set the burstable CPU credits to standard. I am using the L2 ECS constructs to create a cluster, then at the very end I create a launch template and replace the existing launch config. Credit to this site for setting me in the right direction:
https://ecsworkshop.com/capacity_providers/ec2_spot/ 

This is in C# but the concept should translate easily

``` C#

// Not shown: creation of the Cluster and the Auto Scaling Group with minimal instance launch config settings.

// Create launch template with the props we really want
var ec2LaunchTemplate = new LaunchTemplate(this, "ClusterLaunchTemplate", new LaunchTemplateProps
{
    InstanceType = InstanceType.Of(InstanceClass.BURSTABLE3, InstanceSize.MEDIUM),
    CpuCredits = CpuCredits.STANDARD,
    MachineImage = MachineImage.FromSSMParameter(
        "/aws/service/ami-windows-latest/Windows_Server-2004-English-Core-ECS_Optimized/image_id",
        OperatingSystemType.WINDOWS),
    SecurityGroup = ec2SecurityGroup,
    Role = InstanceIamRole, 
    DetailedMonitoring = false,
    BlockDevices = new[]
    {
        new Amazon.CDK.AWS.EC2.BlockDevice()
        {
            DeviceName = "/dev/sda1",
            Volume = Amazon.CDK.AWS.EC2.BlockDeviceVolume.Ebs(
                50,
                new Amazon.CDK.AWS.EC2.EbsDeviceOptions
                {
                    DeleteOnTermination = true,
                    VolumeType = Amazon.CDK.AWS.EC2.EbsDeviceVolumeType.GP3,
                })
        }
    }
});

// Get the underlying CfnAutoScalingGroup from the L2 construct
// CDK escape hatch docs: https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html
var cfnEc2Group = ((CfnAutoScalingGroup)ec2group.Node.DefaultChild);

// Remove the launch config from our stack
DefaultCluster.AutoscalingGroup.Node.TryRemoveChild("LaunchConfig");
cfnEc2Group.LaunchConfigurationName = null;

// Attach the launch template to the auto scaling group
CfnLaunchTemplate cfnLaunchTemplate = (CfnLaunchTemplate)ec2LaunchTemplate.Node.DefaultChild;
cfnEc2Group.LaunchTemplate = new CfnAutoScalingGroup.LaunchTemplateSpecificationProperty
{
    LaunchTemplateId = cfnLaunchTemplate.Ref,
    Version = cfnLaunchTemplate.AttrDefaultVersionNumber
};

```

**Comment by cprice404-aws** [comment]
thanks @zstarkebaumcalico !  That was super helpful.

Here's a TypeScript example that also uses Spot instances, based on the code above.  Hacky but better than nothing until CDK supports launch templates and instanceDistribution.

```

    // hack until they support LaunchTemplates properly: https://github.com/aws/aws-cdk/issues/6734
    const cfnAsg = asg.node.defaultChild as autoscaling.CfnAutoScalingGroup;
    asg.node.tryRemoveChild('LaunchConfig');
    cfnAsg.launchConfigurationName = undefined;

    const cfnLaunchTemplate = ec2LaunchTemplate.node.defaultChild as ec2.CfnLaunchTemplate;
    cfnAsg.mixedInstancesPolicy = {
        instancesDistribution: {
            onDemandBaseCapacity: 0,
            onDemandPercentageAboveBaseCapacity: 0,
            spotAllocationStrategy: 'capacity-optimized',
        },
        launchTemplate: {
            launchTemplateSpecification: {
                launchTemplateId: cfnLaunchTemplate.ref,
                version: cfnLaunchTemplate.attrLatestVersionNumber,
            },
            // TODO: we could add additional instance types here to possibly save costs further.  If you go into
            // the console and use the wizard to start creating a spot ASG it will recommend similar instance types.
            overrides: [
                {
                    instanceType: instanceType,
                },
            ],
        },
    };
```

**Comment by icelava** [comment]
Looking at the workaround hack, I'm trying to instantiate an AutoScalingGroup with only parameters a LaunchTemplate does not contain, and before I can even cast that to a CfnAutoScalingGroup to take on the rest of config from the LaunchTemplate, its constructor complains

_Unhandled exception. Amazon.JSII.Runtime.JsiiException: Missing required properties for @aws-cdk/aws-autoscaling.AutoScalingGroupProps: instanceType, machineImage_

Guess have to include those redundant parameters.

**Comment by Martin1994** [comment]
Here is a WIP commit: https://github.com/Martin1994/aws-cdk/commit/07af2e88f6b885a11df93a7716c970ab4c8cd6f1

I will send a PR shortly once I finish its unit tests, but any early feedback is welcomed, especially its design including breaking API changes, as the current ASG construct is deeply coupled with the usage of LC.

I really wonder whether we take the next major version bump (saying CDK 2.0) as a chance to completely rework the ASG construct.

**Comment by neilferreira** [comment]
I'm very eager to use Launch Templates on a new project.   @Martin1994's changes look good, but I'm not sure if this would go into version 1 or 2.

Is there any escape hatch that can be used in the meanwhile to achieve this using ASGs ?

**Comment by erikdebruin** [comment]
Another few months have gone by... Any updates on this?

**Comment by pv93** [comment]
It's been almost [3 years](https://github.com/aws/aws-cdk/issues/3077) since the initial request for Mixed Instance Auto Scaling groups, and [6 months](https://github.com/Martin1994/aws-cdk/commit/07af2e88f6b885a11df93a7716c970ab4c8cd6f1) since a PR has been opened implementing this feature.

It's evident that many people are requesting this feature, so I have to ask: what is the hold up? And is there anything we as the community could do to speed up the process?

**Comment by Martin1994** [comment]
https://github.com/Martin1994/aws-cdk/commit/07af2e88f6b885a11df93a7716c970ab4c8cd6f1 hasn't been turned into a PR yet since its testing was missing. I will try to finish its testing this week and open a PR.

**Comment by martinKindall** [comment]
Hi everyone, any news on this? As I noticed, Launch Templates are recommended over Launch Configs. Today I created an ASG using the CDK, but I could not find a way to create the asg from a Launch Template.

**Comment by badfun** [comment]
I believe you are still going to have to use [CfnAutoScalingGroup](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.CfnAutoScalingGroup.html) for now.

**Comment by lmayorga1980** [comment]
Is there any documentation regarding the AutoScaling and LaunchTemplates in CDKTF?
