### ISSUE TITLE
No such file or directory error when running CDK synth & tests with GitHub Actions

### ISSUE THREAD

**Issue by nmoutschen** [aws/aws-cdk#6736]
### The Question

I am trying to run `cdk synth` and/or tests within GitHub actions. It keeps failing with the following error message and no other explanations:

```
ENOENT: no such file or directory, open '/home/runner/.aws/credentials'
```

The tests themselves don't need to deploy anything on AWS or have access to AWS resources.

How can I run these tests in GitHub Actions without providing AWS credentials?

### Environment

  - **CDK CLI Version:** 1.27.0
  - **Module Version:** 1.27.0
  - **OS:** ubuntu-latest
  - **Language:** TypScript

**Comment by shivlaks** [comment]
@nmoutschen can you run the command with `-v` enabled? That error usually indicates that default credentials were not established. However, that should not result in a failure (it should just be a debug statement

**Comment by rusyasoft** [comment]
Still having an issue

**Comment by mstoyanov-coke** [comment]
Try adding dummy values as env variables like: 
        env: 
          AWS_ACCESS_KEY_ID: 'xxx'
          AWS_SECRET_ACCESS_KEY: 'xxx'
          AWS_DEFAULT_REGION: 'eu-west-2'
