### ISSUE TITLE
CDK - wafv2 - Cfn*Props - embedded sub-type interface declared in Parent CfnObjects  -Typescript

### ISSUE THREAD

**Issue by javabrad** [aws/aws-cdk#6745]
### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by javabrad** [comment]
RuleTypeProperty is a good example.   It is declared in 2 different props but is never declared as a independent type.   This makes it impossible to use CDK with external json configs that represent these types.   We do this is a number of other products in CDK ( Cognito and Cloudfront ).

**Comment by SomayaB** [comment]
Hi @javabrad, thanks for opening an issue. Please fill out the provided template in order for us to have as much information as possible to help you. You just have to edit your original issue. Thanks
