### ISSUE TITLE
EFS Removal Policy

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#6757]
I'd like to be able to set a removal policy for an EfsFileSystem and for the default removal policy to be "RETAIN" instead of "DESTROY".

### Use Case

In my pipeline for a named environment ("test", "staging", "production") I want EFS FileSystems to survive accidental stack deletion and changes to my construct that might result in the FileSystem being gone forever. However, when my pipeline is working in a branch environment, I'd like a stack deletion to remove the EFS FileSystem as the branches are much shorter-lived.

### Proposed Solution
I think an EfsFileSystem prop that provides a `removalPolicy` like RDS would work for me.

I also think that this feature should default to a removal policy of "RETAIN" to be consistent with DynamoDB Tables and RDS Instances. This is probably a breaking change, but it's pretty early days in this experimental module. My reasoning is that the EFS file system may contain data that the user doesn't want to lose if they accidentally cause the resource to vanish during a deploy.

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Yep, sounds like a good idea.

As a workaround until this feature lands, you can access the `filesystem.node.defaultChild`, cast it to a `CfnResource`, and set the removal policy there.
