### ISSUE TITLE
📊Tracking: Cognito

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#6765]
Add your +1 👍  to help us prioritize high-level constructs for this service

--- 

### Overview:
Amazon Cognito provides authentication, authorization, and user management for your web and mobile apps. Your users can sign in directly with a user name and password, or through a third party such as Facebook, Amazon, Google or Apple.

The two main components of Amazon Cognito are user pools and identity pools. User pools are user directories that provide sign-up and sign-in options for your app users. Identity pools enable you to grant your users access to other AWS services.

[AWS Docs for User Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html)

[AWS Docs for Identity Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html)

[CDK API reference page](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html)

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

#### User Pool

| Done | Item | Needed for Graduation | Link to issue or docs |
| ---- | ---- | ---- | ---- |
| ✔️ | initialization & import | ✔️ | [construction](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cognito#user-pools) & [import](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cognito#importing-user-pools) | 
| ✔️ | sign in & sign up configuration, auto verification | ✔️ | [sign up](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cognito#sign-up) & [sign in](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cognito#sign-in) |
| ✔️ | basic security (mfa, password policy, etc.) | ✔️ | [security](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cognito#security) |
| ✔️ | standard and custom attributes | ✔️ | [attributes](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cognito#attributes) |
| ✔️ | triggers | ✔️ | [lambda triggers](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cognito/README.md#lambda-triggers) |
| ✔️ | app clients | ✔️ | [app clients](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cognito/README.md#app-clients) |
| ✔️ | domains | ✔️ | [domains](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cognito/README.md#domains) |
| | users & groups | ✔️ | |
| | message template builder |  | [#6811](https://github.com/aws/aws-cdk/issues/6811) |
| | advanced security | | [#7405](https://github.com/aws/aws-cdk/issues/7405) |
| ✔️ | route53 integration with user pool domain | ✔️ | search for 'user pool domain' [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-route53-targets/README.md) |
| | Simple Email Service integration | ❓ | [#6768](https://github.com/aws/aws-cdk/issues/6768) |
| | identity providers | ✔️ | [#6853](https://github.com/aws/aws-cdk/issues/6853) |
| | hosted UI customization | | [#6953](https://github.com/aws/aws-cdk/issues/6953) |
| | risk configuration | | |
| | resource server | | |

#### Identity Pool

| Done | Item | Needed for Graduation | Link to issue or docs |
| ---- | ---- | ---- | ---- |
| | initialization & import | ✔️ | |
| | [public identity providers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html) & access control | ✔️ | |
| | role mapping & mapping rules | ✔️ | |
| | [OpenIdConnect & SAML and developer-authenticated identity providers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html) | ❓ | |

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html) for more implementation details.

### Issues

All open Cognito issues can be found [here](https://github.com/aws/aws-cdk/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%2Fcognito)

--- 
This is a  📊Tracking Issue

**Comment by 0xdevalias** [comment]
Linking to the RFC for better discoverability:

- https://github.com/aws/aws-cdk-rfcs/issues/95

**Comment by 0xdevalias** [comment]
Added a new issue for Hosted UI customisations: https://github.com/aws/aws-cdk/issues/6953

**Comment by markcarroll** [comment]
Added new issue #7011 for custom attributes which are currently set to immutable

**Comment by 0xdevalias** [comment]
This may need to be captured in a new issue, but should the `UserPool` have `grant*` methods on it to give other resources (eg. lambda functions) access to various API/SDK methods?

- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPool.html
- https://docs.aws.amazon.com/cdk/api/latest/docs/aws-iam-readme.html
- https://docs.aws.amazon.com/cdk/latest/guide/permissions.html

- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/Welcome.html
  - eg. https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminGetUser.html
- https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html
  - eg. https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminGetUser-property

**Comment by nija-at** [comment]
@0xdevalias - please open a new issue for this request. Thanks!

**Comment by brainstorm** [comment]
Added new issue for some UserPool attributes that are present on the Web Console (post deploy) but that I'm not able to reach via CDK (Java): https://github.com/aws/aws-cdk/issues/7245

**Comment by brainstorm** [comment]
"Advanced security" is in issue https://github.com/aws/aws-cdk/issues/7405 (to be added on the summary above).

**Comment by nija-at** [comment]
This has been forked into two separate tracking issues - one [tracking user pools](https://github.com/aws/aws-cdk/issues/8629) and the other [tracking identity pools](https://github.com/aws/aws-cdk/issues/8630).

Please transfer your upvotes (👍) to the respective issues, so we know which one of the two you're interested in.
