### ISSUE TITLE
Missing "ReceiveMessage on SQS" permission for Lambda function

### ISSUE THREAD

**Issue by dstroppa** [aws/aws-cdk#6770]
I’m trying to create a simple Lambda function that reads messages from a SQS queue - here’s my code https://github.com/dstroppa/queue-processing-cdk
 
When deploying, CFN fails to create the EventSource for the function with this error: "The provided execution role does not have permissions to call ReceiveMessage on SQS (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 19af6e68-d98a-421a-ad4b-af20c8a757e9)”. 
 
The CFN template seems to have the right resources (role and permissions). Am I missing something?

### Reproduction Steps

Deploy the stack to an AWS account

My code: https://github.com/dstroppa/queue-processing-cdk
The pipeline used to deploy the stack: https://github.com/aws-samples/aws-lambda-sample-applications/blob/master/CICD-toolchain-for-serverless-applications/toolchain.yml

### Error Log

When deploying, CFN fails to create the EventSource for the function with this error: "The provided execution role does not have permissions to call ReceiveMessage on SQS (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 19af6e68-d98a-421a-ad4b-af20c8a757e9)”. 

### Environment

  - **CLI Version      :** aws-cli/1.18.17
  - **Framework Version:** 1.28.0 (build 5f2bbc6)
  - **OS               :** macOS 10.14.6
  - **Language         :** Typescript

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
Hey there. I'll use your example repo to try and reproduce. Just wondering though if there is a reason you're on v1.19.0 of cdk?

**Comment by dstroppa** [comment]
Thanks @MrArnoldPalmer. No particular reason, I started working on this when 1.19 was the latest version :) 
This is the log - https://gist.github.com/dstroppa/56f1cbe09bd932cca2605c920ea567ab - from a build I ran a couple of days ago, the CDK version used there is 1.28.0

**Comment by dstroppa** [comment]
It seems this issue was related to how the Permission boundary was created upstream, not with CDK. Closing for now.
