### ISSUE TITLE
[EKS Bug] CFN Stack stuck at `UPDATE_ROLLBACK_FAILED` upon changing HelmChart release name

### ISSUE THREAD

**Issue by yjw113080** [aws/aws-cdk#6782]
I've tried to add a helm chart with CDK code and then changed the release name.

my code:
```
    cluster.addChart('metrics-server', {
      chart: 'metrics-server',
      repository: stable,
      namespace: 'management',
      release: 'metrics-server'
    })
```

### Reproduction Steps

Generate a chart with CDK and then update it with another release name.

### Error Log

error message:
```
Failed to update resource. Error: b'Release "ckapnortheast2demogoclusterchartmetricsserver68c20644" does not exist. Installing it now.\nError: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request\n'
    at invokeUserFunction (/var/task/framework.js:85:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Environment

  - **CLI Version      :*1.27.0 (build a98c0b3)*
  - **Framework Version: 1.27
  - **OS               : MacOS Mojave
  - **Language         : Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Unable to reproduce this exactly. Indeed it is [impossible] to change a release name in Helm, but the CDK deployment fails "gracefully" and rolls back with the following message:

```
Failed to update resource. Error: b'Release "metrics-server-two" does not exist. Installing it now.\nError: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "system:metrics-server-aggregated-reader" in namespace "
" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "metrics-server-two": current value is "metrics-server"\n'
```

To update the release name, you will need to remove the Helm resource from your CDK app, deploy and then deploy with a new release name.

[impossible]: https://github.com/helm/helm/issues/1809
