### ISSUE TITLE
Can not avoid codepipeline creating a Role for s3bucket as source Stage 

### ISSUE THREAD

**Issue by MinoZhangTR** [aws/aws-cdk#6791]
### The Question

I was trying to create a aws pipeline by using codepipeline and codepipeline-action lib in cdk, But whenever I put S3 bucket as source stage, it will try to create a role for the pipeline, which is what I want to avoid.

**Code:**
```ts
            source = new S3BucketSourceAction({
                actionName: pipelineSource.stageName,
                scope: this,
                bucket: bucket,
                bucketKey: pipelineSource.bucketKey!
            });
```
**Result**
![image](https://user-images.githubusercontent.com/52667189/76970923-ee794f00-6902-11ea-917c-13e63e825f09.png)

### Environment

  - **CDK CLI Version:** 1.27.0
  - **Module Version:**     `@aws-cdk/aws-codebuild": "^1.27.0`,
                                         `@aws-cdk/aws-codepipeline": "^1.27.0`,
                                         `@aws-cdk/aws-codepipeline-actions": "^1.27.0`,
                                          `@aws-cdk/core": "^1.27.0`,
  - **OS:**  Windows 10 
  - **Language:** TypeScript 

### Other information

The ouput below is I use console.log to debug S3BucketAction class
![image](https://user-images.githubusercontent.com/52667189/76972213-ab1fe000-6904-11ea-83ab-162ddcffc6e0.png)

**Comment by skinny85** [comment]
Hey @MinoZhangTR ,

you can create or import an existing Role, and pass it to `S3BucketSourceAction`:

```ts
            source = new S3BucketSourceAction({
                actionName: pipelineSource.stageName,
                scope: this,
                bucket: bucket,
                bucketKey: pipelineSource.bucketKey!,
                role: yourRoleHere,
            });
```

Thanks,
Adam

**Comment by MinoZhangTR** [comment]
@skinny85 Thanks a lot! the solution you posted works well.
