### ISSUE TITLE
Stand-alone API Gateway request authorizer fails

### ISSUE THREAD

**Issue by davazp** [aws/aws-cdk#6798]
When a API Gateway Request authorizer is created but not assigned to any of the methods, `cdk` will fails with a not very descriptive error.

This error goes away when assigned to a API method but I did not know why it was. 

I am not sure if it is possible to have an authorizer without explicitly setting it in any method. If it is, then this should work.  But at last it `cdk` should fail with a bit more understandable error.

Some examples in the `RequestAuthorizer` construct would also help! 

### Reproduction Steps

```typescript
    const basicAuth = new lambda.Function(this, "BasicAuth", {
      runtime: lambda.Runtime.NODEJS_12_X,
      code: lambda.Code.fromAsset('...'),
      handler: "basicAuth.handler",
    });

    let api = new apigw.LambdaRestApi(this, "Endpoint", {
      handler: dataMockEndpoint,
      options: {
        deployOptions: {},
      },
      proxy: false,
    });

    let authorizer = new apigw.RequestAuthorizer(this, "RequestAuthorizer", {
      handler: basicAuth,
      identitySources: [apigw.IdentitySource.header("Authorization")],
    });
```

### Error Log

```
Error: Resolution error: Supplied properties not correct for "CfnAuthorizerProps"
  restApiId: required but missing.
```

### Environment

  - **CLI Version      :**. 1.28.0 (build 5f2bbc6)
  - **Framework Version:**
  - **OS               :**. Mac OS X
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Unfortunately, it is not possible to have an authorizer that is not attached to a RestApi. It's a [restriction](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html#cfn-apigateway-authorizer-restapiid) of how API Gateway has modeled them.

Improved messaging and documentation coming up - https://github.com/aws/aws-cdk/pull/6886
