### ISSUE TITLE
Adding a Class containing the IAM Policy Actions

### ISSUE THREAD

**Issue by froilan** [aws/aws-cdk#6801]
### Use Case
When building IAM Policy Statements in CDK, our workflow usually is to refer to the documentation then copy paste the policy actions string from there. For example: "ecr:GetDownloadUrlForLayer", "s3:GetObject"

This can be prone to typos/mistakes.

### Proposed Solution

Since we now have the CDK, we can create a class that can contains all these Actions. Potentially grouped by AWS Service, like s3, ecr, etc. This way, we can easily refer to them within the code when building Policy Statements.

I noticed LinuxBuildImage from the codebuild module does this similar pattern.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by rix0rrr** [comment]
We tend to use [grants](https://docs.aws.amazon.com/cdk/latest/guide/permissions.html#permissions_grants) for this.

Can you describe why you can't achieve what you need to achieve using the mechanism we have?

**Comment by froilan** [comment]
@rix0rrr 

You are right, grant works.

Tho, IMO there are still use cases when defining custom roles are preferable:
- resources that you need to access are not defined on the current codebase. (Exported Resources)
- you want to fine tune or only have specific actions allowed, which usually are bundled with other actions when using grant methods.
- re usability of certain custom policies.

**Comment by rix0rrr** [comment]
I get that, and thanks for the feedback.

We're going all-in on what we have today. We may consider changing it if we get enough feedback that the current mechanism isn't good enough, but for now I don't think this is actionable for us. We may revisit after a year or so.

Closing.
