### ISSUE TITLE
[EKS] If add two helm chart only one chart can get be installed 

### ISSUE THREAD

**Issue by JamesLuoau** [aws/aws-cdk#6806]
If add two helm chart only one chart can get be installed 

### Error Log

No error log, after deploy cdk, only one chart in kubectrl deployment list

### Environment

  - **CLI Version      :1.17
  - **Framework Version:1.28
  - **OS               :MacOS
  - **Language         :Java

### Other

--- 

This is :bug: Bug Report

**Comment by eduardomourar** [comment]
This is probably related #7592. And you should be able to resolve by using method [`addDepencies`](https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#construct-dependencies).

**Comment by eladb** [comment]
Closing as dup

**Comment by eladb** [comment]
Does this happen for any two Helm charts? If that's the case we can serialize Helm chart updates.

**Comment by eduardomourar** [comment]
I cannot say for previous CDK versions, but with current v1.46.0 I am able to deploy two helm charts in the same stack. Whenever I ran into these issues, I solve it by setting the wait flag to true and adding dependency.

**Comment by JamesLuoau** [comment]
I was trying to install "external-dns" and "aws-alb-ingress-controller" together and no luck. I will give the new version an other try. Thanks for looking into this.

**Comment by eladb** [comment]
> I was trying to install "external-dns" and "aws-alb-ingress-controller" together and no luck. I will give the new version an other try. Thanks for looking into this.

Since both charts install the same nginx CRD you won't be able to install them concurrently so make sure to add a dependency between the two charts.
