### ISSUE TITLE
Diff is not shown for resources which are processed by CloudFormation

### ISSUE THREAD

**Issue by mariusgrigaitis** [aws/aws-cdk#6812]
Diffing against existing deployed CF stack does not show changes on resources which were added by CF processing (macros)

### Reproduction Steps (generic)
1. Manually create a CF stack which contains Fn::Transform statements e.g. Include
2. Execute stack
3. Create CDK stack which the same name and try to `cdk diff` against it
4. Diff is shown against non-processed resources. If resources were created by Processing of the template, those are not visible in diff

### Detailed steps
More exact reproduction steps:

1. Deploy following CF template with stack-name=`CdkFooStack`
```
Transform: AWS::Serverless-2016-10-31
Resources:
  MyServerlessFunctionLogicalID:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: 's3://testBucket/mySourceCode.zip'
```

Code taken from: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html

> Rollback is ok since there's no code in that s3 path but feel free to add yours if needed or use different macro. Rollback also allows for diffing and that's the fastest way to demonstrate it I have found

2. Create empty cdk project with same stack name
`mkdir CdkFoo && cd CdkFoo`
`cdk init app --language typescript`

#### Output
```
cdk diff
```

```
Stack CdkFooStack
Template
[-] Transform Transform: AWS::Serverless-2016-10-31

Conditions
[+] Condition CDKMetadataAvailable: {"Fn::Or":[{"Fn::Or":[{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-northeast-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-northeast-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-south-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-southeast-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-southeast-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ca-central-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"cn-north-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"cn-northwest-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-central-1"]}]},{"Fn::Or":[{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-north-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-3"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"me-south-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"sa-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-east-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-west-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-west-2"]}]}]}

Resources
[-] AWS::Serverless::Function MyServerlessFunctionLogicalID destroy
```

#### Expected Output

```
cdk diff
```

```
Stack CdkFooStack
Conditions
[+] Condition CDKMetadataAvailable: {"Fn::Or":[{"Fn::Or":[{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-northeast-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-northeast-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-south-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-southeast-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-southeast-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ca-central-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"cn-north-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"cn-northwest-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-central-1"]}]},{"Fn::Or":[{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-north-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-3"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"me-south-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"sa-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-east-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-west-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-west-2"]}]}]}

Resources
[-] AWS::IAM::Role MyServerlessFunctionLogicalIDRole destroy
[-] AWS::Lambda::Function MyServerlessFunctionLogicalID destroy
```

### Error Log

No errors are produced

### Environment

  - **CLI Version      : 1.30.0**
  - **Framework Version: 1.30.0**
  - **OS               :Mac**
  - **Language         :TS**

### Other

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_GetTemplate.html#API_GetTemplate_RequestParameters

--- 

This is :bug: Bug Report

**Comment by mariusgrigaitis** [comment]
Will try to create a more concrete example to demonstrate the issue

**Comment by shivlaks** [comment]
Does this issue only present itself when diffing against a stack authored outside of the CDK or are there other scenarios where it's ideal to diff against the processed (expanded) template?

**Comment by shivlaks** [comment]
Resolving this issue as it's not one we're currently planning to take on.
If there's a concrete use case that requires follow-up feel free to reopen the issue.

My current read is that this is not a common use case.
