### ISSUE TITLE
📊Tracking: AWS APIGateway V2 - HTTP APIs

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#6830]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

Amazon API Gateway is a fully managed service that makes it easy for developers to publish, maintain, monitor, and secure APIs at any scale. Create an API to access data, business logic, or functionality from your back-end services, such as applications running on Amazon Elastic Compute Cloud (Amazon EC2), code running on AWS Lambda, or any web application.

This is the library for V2 of the the service.

[AWS Docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html#http-api) for more implementation details.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by nija-at** [comment]
I've reclassified this tracking issue to track HTTP APIs.

I've opened a separate tracking issue for Websocket APIs - https://github.com/aws/aws-cdk/issues/14935. Add your +1 if you're interested in these.

**Comment by evgenyka** [comment]
Closing Tracking issue.
