### ISSUE TITLE
[AWS CDK.Lambda.EventSource C#] add cloudwatch events in the lambda function

### ISSUE THREAD

**Issue by UlissesMaiaSage** [aws/aws-cdk#6844]
I need this, because I have some lambda functions that are triggered by these cloudwatch events and the options that exist do not really provide the need

**Comment by nija-at** [comment]
Does this not satisfy your use case? https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events-targets.LambdaFunction.html

**Comment by UlissesMaiaSage** [comment]
@nija-at Thanks, that solved my problem
