### ISSUE TITLE
aws_appsync.AuthorizationConfig does not support AWS_IAM

### ISSUE THREAD

**Issue by mostafafarzane** [aws/aws-cdk#6849]
I do not see a way to set default_authorization of AuthorizationConfig to AWS_IAM.
I am using aws_cdk:1.30 in python.

**Comment by 0xdevalias** [comment]
dupe of https://github.com/aws/aws-cdk/issues/6772

**Comment by MrArnoldPalmer** [comment]
Closing in favor of #6772
