### ISSUE TITLE
User Identity Provider - SAML

### ISSUE THREAD

**Issue by moofish32** [aws/aws-cdk#6853]
[Cognito Identity Providers](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolidentityprovider.html)  are not supported as an AWS construct or natively by the User Pool construct. Integrating this new construct with the user pool will resolve challenges correctly setting attribute mutability as warned in the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-schemaattribute.html#cfn-cognito-userpool-schemaattribute-mutable)

### Use Case

I want to be able to easily integrate a user pool with my company provided SAML IdP. The same will be true for other IdPs supported by Cognito.

### Proposed Solution
Correctly model the providers available in the [current list](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolidentityprovider.html#cfn-cognito-userpoolidentityprovider-providerdetails). I don't think this is really a stand alone construct, but an integrated function on the user pool. Depending on the variation on the interface this may be require individual methods to avoid JSII limits regarding interface unions.

CDK might look like:

```ts
         const userPool: cognito.UserPool = new cognito.UserPool(this, `${id}-pool`, {
            userPoolName: props.name,
            autoVerify: { email: true },
            selfSignUpEnabled: props.allowUserSignUp,
            mfa: cognito.Mfa.OFF,
            requiredAttributes: {
              email: true,
              nickname: true,
              fullname: true,
            },
            lambdaTriggers: { preTokenGeneration: preTokenTrigger },
        });
        userPool.addSamlIdp(mySamlIdpProps); // userPool.addGoogleIdp(myGoogleProps) ...
```
In that function we will ensure mutable properties from the mapping json are correctly set in the user pool properties. By providing individual functions we'll have type validation.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by TheRealAmazonKendra** [comment]
Looks like this has actually been implemented. Closing this issue.
