### ISSUE TITLE
📊Tracking: AWS Pinpoint Email

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#6861]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

The Amazon Pinpoint Email API provides programmatic access to options that are unique to the email channel and supplement the options provided by the Amazon Pinpoint API. 

[AWS Docs](https://docs.aws.amazon.com/pinpoint-email/latest/APIReference/Welcome.html)  

### Maturity: CloudFormation Resources Only

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-pinpointemail-readme.html) for more implementation details.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by iliapolo** [comment]
Dont close
