### ISSUE TITLE
support for cfn resource depends on non-cfn resource

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#6883]
I'm finding I have to resort to `cfn` classes quite often in CDK to be able to express what I need, which is fine.
However, we try and use higher-level constructs where possible. This leads to situations like this:

```typescript
        const logsLogGroup = new logs.LogGroup(this, 'logGroup', {
            logGroupName: `/ecs/${appBaseName}`,
            retention: 7,
            removalPolicy: cdk.RemovalPolicy.DESTROY
        });

        const cfnTaskDefinition = new ecs.CfnTaskDefinition(this, 'taskDefinition', {
            family: appBaseName,
            containerDefinitions: []
        });
        cfnTaskDefinition.addDependsOn()
```

This is currently not supported as far as I can see, `addDependsOn` only supports other cfntype class instances.
I'd really like to see a way to reference non-cfn resources from cfn resrouces.

### Use Case
See description

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
You can use [`node.addDependency`](https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#construct-dependencies)
