### ISSUE TITLE
Allow secret lookup by name

### ISSUE THREAD

**Issue by machielg** [aws/aws-cdk#6889]
Make it possible to get an existing secret by name

### Use Case

When deploying my stack on multiple accounts, I don't know the ARN of existing secrets but they do have the same name in each account (since we make them manually)

### Proposed Solution

Add name (or perhaps tag?) as one of the attributes in secretsmanager.Secret.fromSecretAttributes

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @machielg ,

thanks for the feature request, but this can't really happen :(. Because the ARN of the secret cannot be inferred from the name (it gets suffixed with 6 pseudo-random characters), there's no way to reliably formulate an ARN from a name.

We could add a `fromSecretLookup` method that would do a call to the AWS API to find out the ARN of the secret based on its name, similarly like we have `Vpc.fromLookup`, and cache the results in the `cdk.context.json` file... would that be acceptable?

Thanks,
Adam

**Comment by machielg** [comment]
@skinny85 hi Adam, 
I found the lookup by name isn't needed actually since apparently one can reference a secret without knowing the random chars at the end.

I now do this:
```typescript
const secretArn = cdk.Stack.of(this).formatArn({
                service: 'secretsmanager',
                resource: 'secret',
                sep: ':',
                resourceName: `bitbucket-credentials`
            });
```

I can use this arn in the sagemaker gitrepo properties even though it's not the exact ARN.

**Comment by skinny85** [comment]
@machielg really?? I'm kind of shocked that would work... are you 100% certain the secret gets resolved correctly?

**Comment by machielg** [comment]
@skinny85 yes it works, I've tried it now several times. It confused me too, since in the UI it obvious the ARN doens't resolve to anything (when you click it, it just lists all the secrets). I'm guessing this is a common way to reference secrets. Although not the best documented feature.

In my project I actually switched to getting the secrets outside of CDK with a aws cli call, since it turned out I need to fetch all secrets and that's not feasible with CDK.

Sorry that this feature request is a bit muddy, you can close it from my part.

**Comment by skinny85** [comment]
@machielg can you let me know which service allowed you to use this non-full ARN, and it worked? Because I just tried it with CodeBuild with the secret ARN equal to `arn:aws:secretsmanager:us-west-2:123456789012:secret:dockerhub-token-personal`, and I got the following error:

```
2:26:28 PM | UPDATE_FAILED        | AWS::CodeBuild::Project | ProjectC78D97AD
Failed to call UpdateProject, reason: Registry credential is invalid, it must be either the full ARN or name of the secre
t (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; Request ID: 71dc60db-dc93-4614-aca3-56a6d1
81926f; Proxy: null)
```

Very curious which service allows these partial ARNs.

**Comment by sreekanth-bg** [comment]
this seems to be working while I was trying create env vars out of secrets for the ECS fargate tasks...

```

        const mysecretArn = cdk.Stack.of(this).formatArn({
          service: 'secretsmanager',
          resource: 'secret',
          sep: ':',
          resourceName: `test/secret01`
	});
		
        const mysecret = secretsmanager.Secret.fromSecretAttributes(this, 'mysecret', {
          secretArn: mysecretArn,
        });
		
	// and consume in the ECS container prop
		
	secrets: {
            TEST_SECRET: ecs.Secret.fromSecretsManager(mysecret),
	}
		
```
		
however, im also looking forward to [import]([https://github.com/aws/aws-cdk/issues/7444]) the secrets through the API as the above seems to be a hack...

**Comment by machielg** [comment]
@skinny85  I couldn't reproduce the lookup like you're showing. I solved my problem by switching to the Systems Manager parameter store which also supports secrets and those parameters can be referenced by name.

**Comment by skinny85** [comment]
@sreekanth-bg Sure, passing an environment variable that way works. But did you actually try to use the `TEST_SECRET` environment variable from your ECS service to call SecretsManager, and did it work?

**Comment by eikeon** [comment]
> it must be either the full ARN or name of the secret

@skinny85 Is there a way to use just the name of the secret as suggested by the UPDATE_FAILED's reason?

**Comment by skinny85** [comment]
@eikeon yes. For example, in the example that I did above (this comment: https://github.com/aws/aws-cdk/issues/6889#issuecomment-652676913 ), if I change the `credential` field to just the name of the SecretManager Secret (so just `dockerhub-token-personal`), it actually does work.

Unfortunately, SecretsManager doesn't have this functionality yet, but perhaps, given this, we should add it.
