### ISSUE TITLE
CONTRIBUTING.md has old info about adding a language

### ISSUE THREAD

**Issue by Doug-AWS** [aws/aws-cdk#689]
From a user:

I was looking further into this [support for Swift] and found instructions for adding language support in the CONTRIBUTING.md[1] however it looks like the links are out of date – there are no longer any directories under packages/aws-cdk-xxx (where "xxx" is the language). Do you have any guidance here?

**Comment by Doug-AWS** [comment]
The "Adding Language Support" section of CONTRIBUTING.md is still WRONG! There is no https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk-java/package.json.

**Comment by SomayaB** [comment]
Closing since that section no longer exists in CONTRIBUTING.md.
