### ISSUE TITLE
How create alarm in cdk when apigateway generate error4xx and error5xx

### ISSUE THREAD

**Issue by jlmenezes** [aws/aws-cdk#6916]
### The Question
I am trying to generate an alarm when the apigateway returns error 4xx and 5xx but I am not getting it, there is some documentation to generate this alarms via cdk

### Environment

  - **CDK CLI Version:** 1.28.0
  - **Module Version:** 
  - **OS:** Windows 10
  - **Language:** C#

**Comment by nija-at** [comment]
The ApiGateway service produces [CloudWatch metrics for `4XXError` and `5XXError`](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html#api-gateway-metrics) for all Rest APIs that are set up.

You can then use the [Alarm construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Alarm.html) in the CDK CloudWatch library to create alarms against these metrics.

Re-open this issue if you have more questions. 
Thanks!
