### ISSUE TITLE
Pipeline config not showing up on synth output

### ISSUE THREAD

**Issue by Thomazella** [aws/aws-cdk#6923]
![Screen Shot 2020-03-21 at 3 54 21 PM](https://user-images.githubusercontent.com/15015324/77234345-5bebe080-6b8c-11ea-87b2-85bfc4798644.png)

### Reproduction Steps

```js
const lambdaWithStash = `
#set($ctx.stash.newId = $util.autoId())
{"version": "2017-02-28", "operation": "Invoke", "payload": $util.toJson($ctx)}
`
const passThrough = `$util.toJson($ctx.result)`

export const resolverDefaults = {
  requestMappingTemplate: Appsync.MappingTemplate.fromString(lambdaWithStash),
  responseMappingTemplate: Appsync.MappingTemplate.fromString(passThrough),
}

// this == CDK.Stack
new Appsync.Resolver(this, 'pipeline', {
      ...resolverDefaults,
      api: Graphql, // Appsync.GraphQLApi
      typeName: 'Conversation',
      fieldName: 'messages',
      pipelineConfig: {
        functions: ['lambda1', 'lambda2'] // valid lambdas on my Lambda console
      }
    })
```

### Error Log

see screnshot

### Environment

  - **CLI Version      :** 1.27.0 (build a98c0b3)
  - **Framework Version:** not sure what this means.
  - **OS               :** macos 10.14.6
  - **Language         :** typescript

### Other

I'm passing a valid, as per cdk types, `pipelineConfig` but it shows as undefined in my `cdk synth` output, causing deploy to fail even though my cdk code looks correct

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
Yeah looks like we are not forwarding pipelineConfig from the L2 to CfnResolver.
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L1061

imo, we should remove some of the unnecessary information from the `pipelineConfig` arg as well and make it type `Array<string>` wrapping it in `{ functions: }` when forwarding to the CfnResolver.

**Comment by iamtheworstdev** [comment]
@MrArnoldPalmer what do you think is a reasonable eta on this? no pipeline resolvers means using CDK for Appsync is pointless.

**Comment by MrArnoldPalmer** [comment]
@iamtheworstdev a PR has been submitted but stalled out for now. @Thomazella do you plan on continuing or should we take this over to close it out?

https://github.com/aws/aws-cdk/pull/6924

**Comment by Thomazella** [comment]
Please take it over. Seems pretty simple but I'm terribly busy lately 🙏

**Comment by MrArnoldPalmer** [comment]
@iamtheworstdev feel free to jump in if you want to add some tests and try to get this resolved. Otherwise I'll add it to my list but its a long one at the moment 😉

**Comment by iamtheworstdev** [comment]
@MrArnoldPalmer assume I'm not, because it's not just a clever moniker but you probably don't want me writing the code. but I think my work around for avoid pipelines just reached the end of its useful life so I may. I'll comment back in here if I start any work.

**Comment by vengadanathan** [comment]
Any update on the same ? seems like a bad bug, would be great if you guys can fix it. I am currently blocked on the same

**Comment by BryanPan342** [comment]
Hi @alextriaca  @vengadanathan I'll start working on this today, my goal is to complete it and merge by Thursday.

For future reference, please add a 👍 to the issues that you are stuck on that way they can get sorted to the top :)

**Comment by BryanPan342** [comment]
I believe the work around to this pipeline would be to create multiple resolvers as follows. 

```
const api = new GraphQLApi(...);

const function1 = new Lambda(...);
const function2 = new Lambda(...);

const lambda1DS = api.addLambdaDataSource('DS1', 'function1', function1);
const lambda2DS = api.addLambdaDataSource('DS2', 'function2', function2);

lambda1DS.createResolver({
  typeName: [TYPE],
  fieldName: [FIELD],
  requestMappingTemplate: [REQUEST],
  responseMappingTemplate: [RESPONSE],
});

lambda2DS.createResolver({
  typeName: [TYPE],
  fieldName: [FIELD],
  requestMappingTemplate: [REQUEST],
  responseMappingTemplate: [RESPONSE],
});
```

**Comment by BryanPan342** [comment]
Okay I think I found the root of the confusion.

The `Function` that can be added to the `pipelineConfig` is not a `Lambda Function`. Instead, it is `AppSync::Function`. 

See documentation on `pipelineConfig` [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-resolver-pipelineconfig.html).

See documentation on `functionConfiguration` [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html).

See documentation on `appsync:CreateFunction` [here](https://docs.aws.amazon.com/appsync/latest/APIReference/API_CreateFunction.html).

If you want to use `Lambda Functions`, I suggest using the `addLambdaDataSource` and `createResolver` method outlined above.

That being said, CDK doesn't have implementation for AppSync Function so I will close this issue and opening # for a feature request for AppSync function creation.
