### ISSUE TITLE
Support for the new HTTP APIs for API Gateway 

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#6927]
AWS recently announced GA for "HTTP API" for API Gateway, https://aws.amazon.com/about-aws/whats-new/2020/03/api-gateway-private-integrations-aws-elb-cloudmap-http-apis-release/

It'll be nice if we can use CDK to deploy the new type of apis to API Gateway (with Lambda integration).
 
### Use Case

As far as I can tell, HTTP API is really a next generation/replacement for REST API if you can use the new HTTP API integration for your particular use cases. For us, the (promised) cost saving and reduction in latency justifies the migration. 

### Proposed Solution

I'm not entirely sure what really needs to be done. The current CDK API includes `IRestApi`, `LambdaRestApi`, etc. Will we need new constructs like `IHttpApi` and `LambdaHttpApi`? Or, can we overload the existing constructs/interfaces, say, with some kind of "api type" flag? As far as I can see, the `Cfn-` resources do not include a separate resource for "HTTP API" type.

### Other

> HTTP API doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
We already have a request for this here - https://github.com/aws/aws-cdk/issues/5301

Closing this as duplicate.
