### ISSUE TITLE
DynamoDB metrics to my custom dashboard

### ISSUE THREAD

**Issue by pradeephr** [aws/aws-cdk#6928]
I am trying to add collect metrics related to all my resources into one dashboard
I see that dynamoDB metrics are available in the global metrics but I am not able to find a way to get these metrics into my custom dashboard.

I couldn't find any documentation related to this 

### Use Case

Multiple people use my aws account to build their services, I have some of my own and I want to be able to see all metrics related only to my service in this dashboard

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by RomainMuller** [comment]
Hey @pradeephr,

Can you please provide specifics about the metrics you would like to access (what are their dimensions & names, ...)?

**Comment by pradeephr** [comment]
I wanted to get metrics related to WCUs, RCUs consumed, I found that this feature is supported in higher version of DynamoDB construct. 
You can close this issue now
