### ISSUE TITLE
Custom::LogRetention hangs when referencing Function logGroup property

### ISSUE THREAD

**Issue by binaryblake** [aws/aws-cdk#6932]
When referencing the `logGroup` property of Function, a lambda-backed Custom Resource is created (called `Custom::LogRetention`), but it hangs and times out. It appears that the function backing the resource is never actually invoked.

### Reproduction Steps

```
const myfn = new Function(...)
myfn.logGroup.addSubscriptionFilter(...);
```

### Error Log

`Custom::LogRetention` resource hangs in a state of `CREATE_IN_PROGRESS`, then eventually times out after about an hour.

### Environment

  - **CLI Version      : 1.30.0**
  - **Framework Version: 1.30.0**
  - **OS               : macOS Catalina 10.15.3**
  - **Language         : TypeScript**

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Can you share the logs of the log retention Lambda function (the one implementing `Custom::LogRetention`)?

**Comment by binaryblake** [comment]
Since the backing lambda is never invoked, there are no logs in CloudWatch for it. 

It seems to work fine if I invoke the lambda directly with a valid payload, but for some reason the `Custom::LogRetention` isn't calling it.

**Comment by jogold** [comment]
@binaryblake is this reproductible? Could it be linked to the account where you stack is deployed or the permissions for the role/user deploying the stack?

**Comment by binaryblake** [comment]
I thought the same thing at first - but I saw the same behavior deploying to a personal account with the root user. Both of these accounts have other custom resources that are working fine.

**Comment by nija-at** [comment]
I built a small CDK app to reproduce this and am unable to. I'm using CDK version `1.30.0`. See below -

```ts
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { Function, Code, Runtime } from '@aws-cdk/aws-lambda';
import { LambdaDestination } from '@aws-cdk/aws-logs-destinations';

const app = new App();
const stack = new Stack(app, 'mystack');

const fn = new Function(stack, 'myfn', {
  code: Code.fromInline('foo'),
  runtime: Runtime.NODEJS_12_X,
  handler: 'index.handler'
});

const destinationFn = new Function(stack, 'destinationfn', {
  code: Code.fromInline('foo'),
  runtime: Runtime.NODEJS_12_X,
  handler: 'index.handler'
});

fn.logGroup.addSubscriptionFilter('filter', {
  destination: new LambdaDestination(destinationFn),
  filterPattern: {
    logPatternString: 'this pattern'
  }
});
```

There's something unique about your set up that's causing this.

**Comment by binaryblake** [comment]
Thanks @nija-at - not sure what changed but I just tried this again and it's now working in my personal account. In my corporate account it's failing because of a permissions issue. Regardless, I have the feedback I need so I think we can close this.

**Comment by evanerwee** [comment]
I have just run into this issue.
