### ISSUE TITLE
API Gateway Construct Library docs do not mention the v2 interface requirements on some scenarios

### ISSUE THREAD

**Issue by royby-cyberark** [aws/aws-cdk#6937]
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/README.md#custom-domains

I was trying to follow the instructions for adding a base path mapping, but got an error about having to use the V2 interface. the docs doesn't state anything regarding this and it is unclear why this is required in my scenario, rather, the docs instruct you to use the normal API.
Using the V2 interface worked and added the mapping, so I think that docs should say something about this and explain when is the v2 interface required and why.

This code that I ran:

```
api_gateway: RestApi = RestApi.from_rest_api_id(scope=self, id='ApiGatewayFromId', rest_api_id=<api gw id>)
cert = Certificate.from_certificate_arn(scope=self, id='SomeDomainCert', certificate_arn=cert_arn)
domain = DomainName(scope=self,
                                id='APIGatewayDomainName',
                                certificate=cert,
                                domain_name=<domain>,
                                endpoint_type=EndpointType.REGIONAL,
                                security_policy=SecurityPolicy.TLS_1_2)

base_path_mapping = BasePathMapping(scope=self,
                                                id="TestBasePathMapping",
                                                domain_name=domain,
                                                rest_api=api_gateway)
```

Calling this also gave the same error:
`domain.add_base_path_mapping(target_api=api_gateway, base_path='v1')`

And this is the error that you get:

> Mixing of REST APIs and HTTP APIs on the same domain name can only be accomplished through API Gateway's V2 DomainName interface. Currently, WebSocket APIs can only be attached to a domain name with other WebSocket APIs. This must also occur through API Gateway's V2 DomainName interface. (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException

And I mentioned above, working with the v2 interface did the trick.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
This package only supports APIGateway v1 and doesn't yet have any support for APIGateway v2 (which will be available [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html) when it's ready).

It seems to me that something you something you are importing (probably the `RestApi`) is actually a v2 resource, which is why you're having this error.

> Using the V2 interface worked and added the mapping

How did you do this?

**Comment by royby-cyberark** [comment]
you're saying that the v1 interface is only for APIGateway V1, right? that makes sense, which is why I was very surprised to get the "mixing of REST and HTTP APIs" error.
and what you said about importing issues makes a lot of sense, i'm not sure what it was but I was able to get it to work with the expected, v1 API.

To answer your question, my code that added the domain name and mapping was:

```
from aws_cdk.aws_apigatewayv2 import CfnDomainName, CfnApiMapping
...
            domain_name_properties = CfnDomainName. \
                DomainNameConfigurationProperty(certificate_arn=cert_arn,
                                                certificate_name=<cert name>,
                                                endpoint_type=str(EndpointType.REGIONAL))

            domain_name = CfnDomainName(scope=self, id='APIGatewayDomainNameV2',
                                          domain_name=<domain>,
                                          domain_name_configurations=[domain_name_properties])

            api_mapping = CfnApiMapping(scope=self, id="APIGatewayApiMapping1",
                                        api_id=<rest_api_id>,
                                        domain_name=<domain>,
                                        stage='v1',
                                        api_mapping_key='v1')

            api_mapping.add_depends_on(domain_name)
```

So, just to understand, the V2 is/will be able to do both v1 and v2 API gateway?

**Comment by nija-at** [comment]
I'm closing this since we don't have any implementation for APIGWv2 at this point. This will get addressed when we implement it.
