### ISSUE TITLE
RDS: Allow enabling deletion protection for an RDS cluster

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#6944]
As of now, it doesn't appear that I can enable ["Deletion Protection"](https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-rds-now-provides-database-deletion-protection/) for my RDS cluster via CDK.

There is an option provided in the [`DatabaseInstanceNewProps`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstanceNewProps.html) interface, but that's not exposed at the cluster level.

I am able to turn this on via the console:

![Screen_Shot_2020-03-23_at_10_42_34_AM](https://user-images.githubusercontent.com/630449/77340607-27466900-6cf3-11ea-8d52-db0d0659b9d1.png)

and it also is a supported value in the `AWS::RDS::DBCluster` CloudFormation template according to [the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-deletionprotection).

### Use Case

I would like to prevent my production database cluster from being accidentally deleted due to a mistake in our CDK definitions. If a developer's intention is truly to delete the cluster, I'd like to require them to deploy a change disabling deletion protection, and then proceed with their delete.

### Proposed Solution

I propose that we add an optional `deletionProtection?` boolean attribute to [`DatabaseClusterProps`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseClusterProps.html). To match the default behavior of the CloudFormation template (and to provide better backwards compatibility), this property would be `false` by default (not specified in the CloudFormation template output at all). If the user specifies `true`, we would emit `DeletionProtection: true` in the produced CloudFormation template.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by blimmer** [comment]
For those looking for a workaround in the meantime, you can set this parameter in CDK by accessing the CFN doc:

```ts
const cluster = new DatabaseCluster(/* params */);
const cfn = cluster.node.defaultChild as CfnDBCluster;
cfn.deletionProtection = true;
```

**Comment by wswoodruff** [comment]
Does `deletionProtection` default to `true` for you now? It does when I create a `DatabaseInstance` — discussion on secure defaults on this thread https://github.com/aws/aws-cdk/issues/5282

**Comment by skinny85** [comment]
> Does `deletionProtection` default to `true` for you now? It does when I create a `DatabaseInstance` — discussion on secure defaults on this thread #5282

It does default to `true` for Instance. It's not currently surfaced for Cluster, and thus defaults to `false` for it.
