### ISSUE TITLE
Documentation for aws-dynamodb refers to aws-dynamodb-global

### ISSUE THREAD

**Issue by aaronbrashears** [aws/aws-cdk#6955]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-dynamodb-readme.html

The documentation at the bottom of the `aws-dynamodb` overview references the `aws-dynamodb-global` package which is deprecated. The `aws-dynamodb` package now includes support for `replicationRegions` in `TableProps` to provide global tables. The reference to the deprecated package should be removed.

---

This is a 📕 documentation issue

**Comment by RomainMuller** [comment]
Thanks for pointing this out!
