### ISSUE TITLE
DockerImageAsset dockerignore handling anchors globs incorrectly

### ISSUE THREAD

**Issue by anguslees** [aws/aws-cdk#6964]
I think the `.dockerignore` handling introduced in #4104 is incorrect.  Afaics that PR appends `.dockerignore` entries to the asset `exclude` list.  I think docker interprets these entries slightly differently however:

From: https://docs.docker.com/engine/reference/builder/#dockerignore-file (emphasis added)

> `temp?`	Exclude files and directories in the **root** directory whose names are a one-character extension of temp.

@aws-cdk/assets `exclude` ends up using `minimatch` to do the globbing.  From https://github.com/isaacs/minimatch#matchbase however, `minimatch` `matchBase=true` does this (emphasis added):

> If set, then patterns without slashes will be matched against the basename of the path **if it contains slashes**. For example, a?b would match the path /xyz/123/acb, but not /xyz/acb/123.

ie: `temp?` in .dockerfile only matches `/tempa` and not `/foo/tempb`.  When interpreted by DockerImageAsset (via `exclude`) however, `temp?` will match _both_ `/tempa` and `/foo/tempb`.

If we want to continue using minimatch, then I think we need to massage the patterns to always include a slash (`temp?` => `./temp?`)

*Not properly tested!*
```patch
--- @aws-cdk/aws-ecr-assets/lib/image-asset.js.orig        2020-03-24 06:42:11.489493755 +0000
+++ @aws-cdk/aws-ecr-assets/lib/image-asset.js     2020-03-24 06:41:46.589507462 +0000
@@ -29,7 +29,7 @@
         let exclude = props.exclude || [];
         const ignore = path.join(dir, '.dockerignore');
         if (fs.existsSync(ignore)) {
-            exclude = [...exclude, ...fs.readFileSync(ignore).toString().split('\n').filter(e => !!e)];
+            exclude = [...exclude, ...fs.readFileSync(ignore).toString().split('\n').filter(e => !!e).map(e => e.includes('/') ? e : './' + e)];
         }
         // make sure the docker file and the dockerignore file end up in the staging area
         // see https://github.com/aws/aws-cdk/issues/6004

```
--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
This makes sense to me. Maybe we don't need to manage this ourselves and we can just use https://github.com/zeit/dockerignore.

@rix0rrr @eladb @RomainMuller what you guys think? (it has no runtime dependencies)

**Comment by eladb** [comment]
> This makes sense to me. Maybe we don't need to manage this ourselves and we can just use https://github.com/zeit/dockerignore.
> 
> 
> 
> @rix0rrr @eladb @RomainMuller what you guys think? (it has no runtime dependencies)

If the only issue is minimatch’s `matchBase` then can’t we just turn it off?

**Comment by MrArnoldPalmer** [comment]
@eladb I just wonder if there are other parts of the ignore spec that we conflict with that we may uncover later. Might be worth trying to figure that out as part of this work.
