### ISSUE TITLE
Python Subnet docs page has possibly depreciated method & outdated info

### ISSUE THREAD

**Issue by JamieMcKernanKaizen** [aws/aws-cdk#6969]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Subnet.html

The page for Subnet in the Python documentation has a couple of issues with it.

Firstly, when I use the static classmethod `from_subnet_id` I get the following error:

> AttributeError: type object 'Subnet' has no attribute 'from_subnet_id'

perhaps this method has been depreciated and replaced by `from_subnet_attributes` it seems. If so this should be reflected in the docs.

Once I switched to using `from_subnet_attributes` instead I implemented it like so:
```
aws_ec2.Subnet.from_subnet_attributes(
    self,
    "privateSubnet1",
    subnet_id="subnet-123456789"
)
```
But then I received the following error:

> TypeError: from_subnet_attributes() missing 1 required keyword-only argument: 'availability_zone'

Even though **the docs list this attribute as optional**. So this attribute should be changed to required.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Well interestingly both of those pieces of docs are generated.

**Comment by rix0rrr** [comment]
Not exactly sure what's going on, but your issue doesn't reproduce for me:

```
from aws_cdk import core
from aws_cdk import aws_ec2


class TestpythonStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        aws_ec2.Subnet.from_subnet_id(
            self,
            "privateSubnet1",
            "subnet-123456789"
        )

        aws_ec2.Subnet.from_subnet_attributes(
            self,
            "privateSubnet2",
            subnet_id="subnet-123456789"
        )
```

Synthesizes fine.

setup.py:

```
    install_requires=[
        "aws-cdk.core==1.32.2",
        "aws-cdk.aws-ec2==1.32.2",
    ],
```

Closing, please reopen if you have a repro.
