### ISSUE TITLE
IMDSv2: AutoscalingGroups should support LaunchTemplate instead of/as well as LaunchConfiguration

### ISSUE THREAD

**Issue by winjer** [aws/aws-cdk#6977]
Support LaunchTemplates as part of AutoScalingGroups as well as or instead of LaunchConfigurations.

### Use Case

I am required to use IMDSv2 by our security policy.

From the docs:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html:
> To require the use of IMDSv2 on all new instances launched by Auto Scaling groups, your Auto Scaling groups must use launch templates. When you create a launch template, configure the MetadataOptions parameters to require the use IMDSv2. For Auto Scaling groups that use launch configurations, replace the launch configurations with launch templates.

### Proposed Solution

@aws-cdk/aws-autoscaling needs changing.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
Hi @winjer!

You are right we should, tracking it here https://github.com/aws/aws-cdk/issues/6734
closing it as duplicate.
