### ISSUE TITLE
Support Code Guru Profiler Group creation and permissions

### ISSUE THREAD

**Issue by jmnarloch** [aws/aws-cdk#6984]
### Use Case

I wish to enable Code Guru Profiling for my Lambda function using CDK. It appears that CDK doesn't support yet Code Guru Profiler Group creation.

Reference: 

* https://docs.aws.amazon.com/codeguru/latest/profiler-ug/setting-up.html#setting-up-step-5

### Proposed Solution

As for the moment I am forced to create the resources manually.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
@SomayaB - This is not a feature request for lambda, but rather a feature request for Amazon CodeGuru. We don't have a label for this as yet.

**Comment by ccfife** [comment]
CloudFormation recently added support for Code Guru, and so CDK now supports the CFN Resources for this service. Here's a link to the CDK package https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-codeguruprofiler and CDK API reference entry: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codeguruprofiler.CfnProfilingGroup.html

**Comment by ccfife** [comment]
@SomayaB now that there is a CDK construct library module for Code Guru, please create a label and tracking issue for this feature. THX!
