### ISSUE TITLE
Providing the physicalResourceId on AwsCustomResource onUpdate / onDelete

### ISSUE THREAD

**Issue by hlascelles** [aws/aws-cdk#6985]
### How should a physicalResourceId be provided to AwsCustomResource onUpdate / onDelete

`AwsCustomResource` works well for resource creation.

But how should `onUpdate` and `onDelete` supply the `physicalResourceId` that was returned during the onCreate phase?

Take this example. How should the `DirectoryId` to be deleted be provided in the `onDelete` phase?
I am not sure if this just isn't documented yet, or isn't possible. If it isn't possible, I feel it should be, and if it isn't possible, what should we do instead? It would definitely be a shame if there was no intent to add this as functionality, as `AwsCustomResource` is extremely useful.

```
    var adConnector = new AwsCustomResource(this, "ADConnector", {
        onCreate: {
          service: 'DirectoryService',
          action: 'connectDirectory',
          parameters: { ... },
          physicalResourceId: PhysicalResourceId.fromResponse('DirectoryId')
        },
        onDelete: {
          service: 'DirectoryService',
          action: 'deleteDirectory',
          parameters: {
            DirectoryId: ???,
          }
        }
      }
    );
```

### Environment

**CDK CLI** 1.30.0
**Module Version:** 1.30.0
**OS:** all
**Language:** all

**Comment by jogold** [comment]
It's currently not possible but you should be able to do something along those lines:

```ts
const connectDirectory = new AwsCustomResource(this, 'ConnectDirectory', {
  onCreate: {
    service: 'DirectoryService',
    action: 'connectDirectory',
    parameters: { ... },
    physicalResourceId: PhysicalResourceId.fromResponse('DirectoryId')
  },
});
const deleteDirectory = new AwsCustomResource(this, 'DeleteDirectory', {
  onDelete: {
    service: 'DirectoryService',
    action: 'deleteDirectory',
    parameters: {
      DirectoryId: connectDirectory.getResponseField('DirectoryId'),
    },
  },
});
```

**Comment by hlascelles** [comment]
Excellent, that works great.

Can I ask that we add a feature to "do that in one"? Maybe a new method `PhysicalResourceId.fromCreateResponse('DirectoryId')` (and Update equivalent) to replace the `???` in my original code example? 

I understand it may be a great deal more complicated than that of course. Let me know if I should close this and open new more specific issue.

**Comment by jogold** [comment]
We can leave this open as a feature request.

**Comment by aserour** [comment]
+1

**Comment by 0xjjoyy** [comment]
@jogold How to handle update which requires an identifier from the create response?

**Comment by jogold** [comment]
@0xjjoyy the only workaround I see because `onCreate` defaults to the `onUpdate` call is this:

```ts
const onCreate = new AwsCustomResource(this, 'OnCreate', {
  onCreate: {
    service: 'create-service',
    action: 'create-action',
    physicalResourceId: PhysicalResourceId.of('id'),
  },
  policy: AwsCustomResourcePolicy.fromSdkCalls({ resources: AwsCustomResourcePolicy.ANY_RESOURCE }),
});

const onUpdate = new AwsCustomResource(this, 'OnUpdate', {
  onCreate: { // Make a dummy call here
    service: 'dummy-service',
    action: 'dummy-action',
  },
  onUpdate: {
    service: 'update-service',
    action: 'update-action',
    parameters: {
      FOO: onCreate.getResponseField('bar'), // Use data from onCreate
    },
  },
  policy: AwsCustomResourcePolicy.fromSdkCalls({ resources: AwsCustomResourcePolicy.ANY_RESOURCE }),
});
```

**Comment by 0xjjoyy** [comment]
PhysicalResourceIdReference should be used and can be made into a single AwsCustomResource
https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#physical-resource-id-parameter

Example here
https://github.com/aws-samples/aws-iam-permissions-guardrails/blob/master/iam_permissions_guardrails/constructs/service_control_policies/scp_policy_resource.py#L49

**Comment by jogold** [comment]
You are correct, forgot about this feature. 😉
