### ISSUE TITLE
node-termination-handler installed into 'default' namespace, not kube-system

### ISSUE THREAD

**Issue by anguslees** [aws/aws-cdk#6990]
https://github.com/aws/aws-cdk/blob/f4a41d1c68a42e796294692ef00c1fbc83d5dcff/packages/%40aws-cdk/aws-eks/lib/spot-interrupt-handler.ts#L15
(and similar lines in that file)

Despite the name, a less surprising default namespace would be `kube-system`.  The actual `default` namespace is a legacy and almost never used in Kubernetes.

**Comment by eladb** [comment]
@pahud can you take a look at this?

**Comment by pahud** [comment]
looking into this

**Comment by pahud** [comment]
@anguslees 

Yes, you are right. I'll create a PR to fix this shortly.
