### ISSUE TITLE
Error resolving DynamoDB table name from ARN read from list parameter when used to set Lambda environment variable

### ISSUE THREAD

**Issue by tbartley** [aws/aws-cdk#6991]
I am having trouble using values stroed in a StringList SSM parameter to read DynamoDB table attributes and construct a table using Table.fromTableAttributes.

### Reproduction Steps

1. Read `<table-arn>,<table-stream-arn>` from a StringList SSM parameter
2. Call Table.fromTableAttributes with the tableArn and tableStreamArn.
3. Reference properties of the ITable in other constructs

```typescript
const stringListParameter = StringListParameter.fromStringListParameterName(
  scope,
  `${id}Parameter`,
  parameterName,
)

const tableArn = Fn.select(0, stringListParameter.stringListValue)
const tableStreamArn = Fn.select(1, stringListParameter.stringListValue)

const table = Table.fromTableAttributes(scope, 'Table', {
  tableArn,
  tableStreamArn,
})

new Function(this, 'Lambda', {
  code: Code.fromInline('blah'),
  runtime: Runtime.NODEJS_10_X,
  handler: 'handler',
  environment: {
    TABLE_NAME: table.tableName,
  },
})
```
### Error Log

 ❌ TestStack failed: ValidationError: Template error: Fn::Select  cannot select nonexistent value at index 5

### Environment

  - **CLI Version      : 1.30.0**
  - **Framework Version: 1.30.0**
  - **OS               : MacOS**
  - **Language         : typescript**

### Other

I store a DynamoDB table ARN and stream ARN in a StringList SSM parameter.

In a stack, I read them in and construct an `ITable` as follows:

```typescript
const stringListParameter = StringListParameter.fromStringListParameterName(
  scope,
  `${id}Parameter`,
  parameterName,
)

const tableArn = Fn.select(0, stringListParameter.stringListValue)
const tableStreamArn = Fn.select(1, stringListParameter.stringListValue)

const table = Table.fromTableAttributes(scope, 'Table', {
  tableArn,
  tableStreamArn,
})
```

I then construct lambda passing the table name in to the lambda as an environment variable:
```typescript
new Function(this, 'Lambda', {
  code: Code.fromInline('blah'),
  runtime: Runtime.NODEJS_10_X,
  handler: 'handler',
  environment: {
    TABLE_NAME: table.tableName,
  },
})
```

But I get an error on deploy:
```
 ❌ TestStack failed: ValidationError: Template error: Fn::Select  cannot select nonexistent value at index 5
Template error: Fn::Select  cannot select nonexistent value at index 5
```

From the generated template this corresponds to the following code:
```
            "TABLE_NAME": {
              "Fn::Select": [
                1,
                {
                  "Fn::Split": [
                    "/",
                    {
                      "Fn::Select": [
                        5,
                        {
                          "Fn::Split": [
                            ":",
                            {
                              "Fn::Select": [
                                0,
                                {
                                  "Fn::Split": [
                                    ",",
                                    "{{resolve:ssm:/path/to/ssm/parameter}}"
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            },
```
which on the surface seems fine to me:
1. Split StringList parameter value by `,`
2. Select element 0 to get the table ARN
3. Split the ARN on `:`
4. Select element 5 to get the table name prefixed with `table/`
5. Split on `/`
6. Select element 1 to remove the `table/` prefix and get the table name

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
I find it odd that the `{{resolve:ssm:...}}` token does not include a `version` component, which the documentation states is mandatory.

**Comment by MrArnoldPalmer** [comment]
Yeah this is a known issue with StringListParameter. It apparently has never appended the version for resolution.

This is most likely a duplicate of https://github.com/aws/aws-cdk/issues/3586

**Comment by tbartley** [comment]
Thanks for looking in to this @RomainMuller and  @MrArnoldPalmer - does that mean the outlook for resolving this issue  isn't great? I'd also note that I don't see the same validation error reported in #3586 which is obviously quite old. Would a work around for me be simply to, say, call this a string parameter (rather than stringlist parameter) and just do my own splitting on the `,`, ?

**Comment by MrArnoldPalmer** [comment]
@tbartley thats the workaround I have used in the past before working on CDK.

Open to PRs here if you're interested, but its not super simple because we can't just use `LATEST` as the version, we have to resolve the current version number at deploy time and use that. Getting something like that will probably involve a custom resource.

The lack of a validation error is interesting though. We can dig a little deeper and verify that this in fact the same issue. Will update when I find that out.
