### ISSUE TITLE
NetworkLoadBalancedFargateService.domainName not generating AWS::Route53::RecordSet

### ISSUE THREAD

**Issue by erik-telesoftas** [aws/aws-cdk#6992]
After upgrading Java libraries to version 1.31.0 `AWS::Route53::RecordSet` are not generated for NetworkLoadBalancedFargateService, for version 1.30.0 it works just fine.

### Reproduction Steps
We set domain name and zone when generating template
```
            NetworkLoadBalancedFargateService.Builder
                .create(scope, "LBService")
                    .domainZone(internalZoneStack)
                    .domainName("foo.bar");
```

### Error Log

`AWS::Route53::RecordSet` is not being generated in output template.

### Environment

  - **CLI Version      : 1.31.0**
  - **Framework Version: 1.31.0**
  - **OS               : Ubuntu Linux**
  - **Language         : Java**

### Other

Also tried adding `route53` libraries explicitly to my Maven build - did not help.

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@erik-telesoftas - I'm investigating. Do you have the output prior to `1.31.0` that's missing now? 

I'm reproducing in TypeScript but would like to see what's gone missing

**Comment by hoegertn** [comment]
maybe this is related to #6702

**Comment by erik-telesoftas** [comment]
Missing output is
```
    "LBServiceDNS622147F9": {
      "Type": "AWS::Route53::RecordSet",
      "Properties": {
        "Name": "internala-alias-name.internal.domain.",
        "Type": "A",
        "AliasTarget": {
          "DNSName": {
            "Fn::GetAtt": [
              "LBServiceLB17EC2DD2",
              "DNSName"
            ]
          },
          "HostedZoneId": {
            "Fn::GetAtt": [
              "LBServiceLB17EC2DD2",
              "CanonicalHostedZoneID"
            ]
          }
        },
        "HostedZoneId": {
          "Fn::ImportValue": "StageDev-Apis-Dev-IntZone:ExportsOutputRefStageDevApisDevIntZoneAC2B44EF092EB7AB"
        }
      },
      "Metadata": {
        "aws:cdk:path": "StageDev-StageData-Dev-Api/LBService/DNS/Resource"
      }
    },
```
And, yes, indeed, we are using it to generate internal aliases (not for public use) to make communication among our micro-services independent on LB generated URLs.

**Comment by hencrice** [comment]
We've reverted the commit #6987. Pending release

**Comment by erik-telesoftas** [comment]
All good with version 1.32.0 thanks!
