### ISSUE TITLE
Docker Login Failure when using Custom Image for Codebuild with local Assets

### ISSUE THREAD

**Issue by yjw113080** [aws/aws-cdk#6993]
There has been no issue when I use image from other registry,
but when I try to have my custom image from local assets I get the following error.
I tried different regions, but this problem remains still...
any idea on this?

### Reproduction Steps

```
function deployToEKSspec (scope: cdk.Construct, cluster: eks.Cluster, apprepo: string) :PipelineProject {
    const deployBuildSpec = new codebuild.PipelineProject(scope, `deploy-to-eks`, {
        projectName: `deploy-to-eks`,
        environment: {
            buildImage: codebuild.LinuxBuildImage.fromAsset(scope, 'custom-image-for-eks', {
                directory: './utils/buildimage'
            })
        },
...
```

### Error Log

```
[100%] fail: docker login --username AWS --password-stdin https://865200059792.dkr.ecr.ap-northeast-1.amazonaws.com exited with error code 1
```
![image](https://user-images.githubusercontent.com/35519343/77511184-df227480-6eb3-11ea-8786-94234ee291fa.png)

### Environment

  - **CLI Version      :**1.31.0 (build 8f3ac79)
  - **Framework Version:**1.30.0
  - **OS               :**MacOS Mojave
  - **Language         :**Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by yjw113080** [comment]
Well, self-solved!
I was using awscli v1 instead of v2, upgrading awscli worked it.

**Comment by martysweet** [comment]
Just spent a while on this as well!

For anyone else having this problem on Ubuntu - I was using the `snap` package version which resulted in this error, despite docker login working fine using the CLI manually. https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html

Uninstalling the snap package `snap remove docker` and installing docker via these instructions did the trick: https://docs.docker.com/engine/install/ubuntu/

Not sure of the underlying cause, perhaps the snap version is returning 1 erroneously.

**Comment by schopra8** [comment]
I'm currently having the same issue with aws-cli/2.5.5 - any suggestions from the team on how to address this? 

Environment
**CLI Version :** aws-cli/2.5.5 Python/3.9.11 Darwin/20.6.0 exe/x86_64 prompt/off
**Framework Version:**2.19.0 (build e0d3e62)
**OS :**MacOS BigSur
**Language :**Typescript

**Comment by schopra8** [comment]
Looks to be a docker issue. [This](https://github.com/docker/for-mac/issues/2295#issuecomment-356832693 )fixed this for me.

**Comment by nielsrolf** [comment]
I had this issue because I forgot to start docker after restarting my laptop.
