### ISSUE TITLE
CLI: cdk destroy behavior

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#7018]
### The Question
Suppose I am using Cloud9 in us-west-2 and I deploy to us-east-1 by setting the environment variable in the Stack Constructor. Later I remove the explicit environment identifier and then run `cdk destroy`, CDK  will look in us-west-2 for the stack and claim the deletion was successful even though it didn't delete anything. Should CDK throw an error or prompt the user if `cdk destroy [STACK_NAME]` doesn't find a stack with the right name.

### Environment

  - **CDK CLI Version:** 1.29.0
  - **Module Version:** N/A
  - **OS:** Amazon Linux
  - **Language:** Python

**Comment by eladb** [comment]
It's a philosophical question: whether destroy needs to be idempotent or not. At the moment it is (i.e. if the resource is not there anymore, it is already destroyed...).

We can introduce a flag that will change this behavior if you think it's useful. WDYT?

**Comment by shivlaks** [comment]
I'm inclined to agree with the idea that it should be idempotent. Many services in AWS also deal with resource deletion in that manner but I guess the real driver should be whether there's value in the error and what users would want to do with it.

I believe there are some delete APIs that return what they deleted as output. A flag would be a reasonable mechanism to achieve it.

The current behavior is that you'd see stack events as the deletion completes when the resource exists. If the resource does not exist, there are `destroying`... and `destroyed` messages. Depending on whether there's value, we could also relay more information such as the stackArn or region to help with clarity. It might be useful for auditing purposes.

**Comment by richardhboyd** [comment]
I want to add to this. 

* I deploy a stack and it works
* I make a change to my CDK stack and it no longer deploys correctly
* I decide to delete the stacks via `cdk destroy '*'`
* `cdk destroy` fails because cdk synth fails which isn't very intuitive,

**Comment by KTamas** [comment]
still an issue
