### ISSUE TITLE
Custom Resource Properties Keys Are Being Uppercased

### ISSUE THREAD

**Issue by chriscoombs** [aws/aws-cdk#7035]
The CustomResource type is currently uppercasing the first letter in each prop.properties key. There is no requirement in CloudFormation for the first letter to be uppercased. The CloudFormation documentation for Custom Resources shows properties with lowercase keys.

Uppercasing the properties prevents the porting of existing custom resources to CDK. Even when code changes to the backing Lambda function are possible, simple object destructuring is not.

### Reproduction Steps

```
new cloudformation.CustomResource(this, 'Custom Resource', {
      provider: cloudformation.CustomResourceProvider.fromLambda(customResource),
      properties: {
        detail: {
          event: 'referenceCreated',
          repositoryName,
        }
      }
    })
```

### Error Log

```
detail: {
          ...
        }
```

becomes

```
Detail: {
          ...
        }
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

Fixed in [pull request 7034](https://github.com/aws/aws-cdk/pull/7034).

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Superseded by #7736
