### ISSUE TITLE
Latest version of  "@aws-cdk/aws-cloudtrail" does not work

### ISSUE THREAD

**Issue by jatin7gupta** [aws/aws-cdk#7039]
If you install the latest version of  "@aws-cdk/aws-cloudtrail" using npm install, you will get the version  "^1.31.0" and if you try to initialise the object you will get an error. And if you downgrade to version "1.30.0", it will work.

### Reproduction Steps
npm install @aws-cdk/aws-cloudtrail
in package json
```
 "dependencies": {
    "@aws-cdk/aws-cloudtrail": "^1.31.0",
    "@aws-cdk/aws-cognito": "^1.30.0",
    "@aws-cdk/aws-dynamodb": "^1.30.0",
    "@aws-cdk/aws-lambda": "^1.30.0",
    "@aws-cdk/core": "1.30.0",
    "cdk-watchful": "^0.4.6",
    "source-map-support": "^0.5.16"
  }
```

Code
import * as cloudtrail from '@aws-cdk/aws-cloudtrail';

in the constructor of the construct
```
const trail = new cloudtrail.Trail(this, 'cloudwatch', {
      sendToCloudWatchLogs: true
    });
```

### Error Log

![image](https://user-images.githubusercontent.com/9363287/77743970-ff496380-706c-11ea-9ff6-899df463862b.png)

### Environment

  - **CLI Version      :1.27.0 (build a98c0b3)
  - **Framework Version:1.30 (not sure)
  - **OS               :Windows 10
  - **Language         :Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @jatin7gupta ,

that's because in your `package.json` you have `@aws-cdk/core` pinned to version `1.30.0`. In the CDK, you can't mix multiple versions of packages in the same module. So, if you change your modules to all have the version `1.31.0`, this will work.

Thanks,
Adam

**Comment by jatin7gupta** [comment]
Thanks @skinny85 for the very quick response. Closing the issue.
