### ISSUE TITLE
SQS subscription to cross-region SNS topic not working via addSubscription

### ISSUE THREAD

**Issue by watkinsmatthewp** [aws/aws-cdk#7044]
When I try to subscribe an SQS queue in one account to an SNS topic in another account _and another region_ using `topic.addSubscription()`, I get error "Invalid parameter: TopicArn." This works when adding a subscription to a the same account/region or a different account but same region. But it fails when subscribing to a different account and region:

```ts
topicInRegionA.addSubscription(new SqsSubscription(queueInRegionB));
```

I thought this was supposed to be fixed by #3842?

### Reproduction Steps

1. Try to subscribe an SQS queue to a topic in another region using `addSubscription()`

### Error Log

```txt
1/13 | 5:11:07 PM | CREATE_FAILED        | AWS::SNS::Subscription          | MyQueue/MyServicealphauswest2MyTopic915AE08F (MyQueueMyServicealphauswest2MyTopic915AE08F58613436) Invalid parameter: TopicArn (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: ...)
        new Subscription (...CDK/node_modules/@aws-cdk/aws-sns/lib/subscription.js:29:9)
        \_ Topic.addSubscription (...CDK/node_modules/@aws-cdk/aws-sns/lib/topic-base.js:23:9)
        \_ AppStack.bindCustomComponents (...CDK/dist/lib/custom/app-stack.js:48:43)
        \_ Object.<anonymous> (...CDK/dist/lib/app.js:66:18)
        ...
```

### Environment

  - **CLI Version      : 1.30.0 (build 4f54ff7)**
  - **OS               : Red Hat variant**
  - **Language         : TypeScript**

This is :bug: Bug Report

**Comment by watkinsmatthewp** [comment]
Whoops, missed something. I may open another ticket later.

**Comment by watkinsmatthewp** [comment]
Re-opened with accurate description

**Comment by MrArnoldPalmer** [comment]
@watkinsmatthewp is it possible to share your code or create a minimum reproduction repo?

How are you importing the queue from other account/region? Running a basic test I don't run into this error.

**Comment by watkinsmatthewp** [comment]
@MrArnoldPalmer I'll provide more details offline.

**Comment by raphaelsalomao3** [comment]
@watkinsmatthewp did you manage to solve this issue? I'm running into the same problem.

This is my setting:
Account A, us-east-1: SNS topic
Account B, eu-west-2: SQS queue

From Account A, when I try to subscribe to Account B topic, it throws InvalidParameter:

```
sns_client.subscribe(
                TopicArn=topic_arn,
                Protocol="sqs",
                Endpoint=queue_arn,
                Attributes={"RawMessageDelivery": "true"},
            )
```

Throws:
`An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: TopicArn`

**Comment by jacoblangston** [comment]
This is still an issue.

Steps to reproduce:

- Create an SNS topic in an account in us-east-1
- In a CDK project, configured for a different account and region (us-west-2), create a queue, and subscribe to the SNS Topic.

This is the CDK code I'm using:

```
  const queue = new sqs.CfnQueue(this, 'MyQueue', {
      queueName: 'MyQueue',
      kmsMasterKeyId: cmk.keyId,
      visibilityTimeout: 900,
    });
    
  const topicSubscription = new sns.CfnSubscription(this, 'MySubscription', {
    topicArn: 'arn-for-sns-topic',
    region: scopedAws.region,
    endpoint: queue.attrArn,
    protocol: 'sqs',
  });
```
