### ISSUE TITLE
CDK need have a way to put tags on the staging bucket created by bootstrap

### ISSUE THREAD

**Issue by chenzhendong** [aws/aws-cdk#7046]
CDK need allow user create tags set for the resources that boostrap creates.

### Use Case

Big company has the tagging policy for bucket.   Any resource without proper tagged will be quarantined.

### Proposed Solution

Reuse the stack tag paramter and allow it post on all resources it create.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@chenzhendong this functionality is supported today

```shell
cdk bootstrap --tags key=value
```

This will tag the CloudFormation stack as well as the S3 bucket that it creates

you can read more about it in our [documentation](https://docs.aws.amazon.com/cdk/latest/guide/tools.html).

Feel free to re-open the issue if you still have any unanswered questions.

**Comment by chenzhendong** [comment]
It would be nice to add document for the sample format, I don't know the format would like which one of below
cdk bootstrap --tags key1=value1,key2=value2
cdk bootstrap --tags [key1=value1,key2=value2]
cdk bootstrap --tags ["key1=value1","key2=value2"]
cdk bootstrap --tags key1=value1 --tags key2=value2

**Comment by shivlaks** [comment]
that's good feedback, we should be able to improve on the sample snippets.

I think this is what you want.
```
cdk bootstrap --tags key1=value1 --tags key2=value2
```

Let me know how it goes!

**Comment by satishj3-tr** [comment]
When using the above command I am getting error 

[Container] 2020/11/05 10:01:41 Running command npm run cdk-bootstrap --tags assetId=206136 ${ENVIRONMENT} ${REGION}
--
52 |  
53 | > temp@0.1.0 cdk-bootstrap /codebuild/output/src698655178/src/iac/cdk/cdk_ecs
54 | > func() { cdk bootstrap -c environment=$1 -c region=$2; }; func "assetId=206136" "DEV" "us-east-1"
55 |  
56 | npx: installed 8 in 1.216s
57 | Cannot read property 'environmentType' of undefined
58 | Subprocess exited with error 1
59 | npm ERR! code ELIFECYCLE
