### ISSUE TITLE
Allow us to specify tsconfig.json

### ISSUE THREAD

**Issue by SachinShekhar** [aws/aws-cdk#7054]
When I run any `cdk` command, it picks `tsconfig.json` from the working directory. AFAIK, there's no way to specify a different `tsconfig.json` file either using command or `cdk.json` file.

## Why?

When working in a monorepo, this becomes necessary because root `tsconfig.json` file can be used by other apps or other child `tsconfig.json` files.

## What I encountered?

I moved my already working cloud infrastructure code into a monorepo and updated `cdk.json` file accordingly in the hope that it would work smoothly without any issue. Instead, I was greeted with this error on running any `cdk` command:

```
Unexpected token *
Subprocess exited with error 1
```
Tracing the issue using `--verbose` didn't help. After wasting several hours, I discovered that tsc's `compilerOptions.module` was causing the problem. CDK doesn't support `ESNEXT` and `ES2015`. I had to switch to `CommonJS` and I am still testing my existing apps for their integrity.

**Comment by SachinShekhar** [comment]
As `aws-cdk` uses `ts-node` in the background, it just occurred to me that it's possible to pick different `tsconfig.json` file using ts-node's `--project` flag. If you run into the same issue, update your `cdk.json` file to

```json
{
  "app": "npx ts-node --project=path/to/tsconfig.json path/to/cdk/entry/point"
}
```
It works!

**Comment by PeteLindsell** [comment]
I also have the need for multiple tsconfig.json files I tried @SachinShekhar suggestion of adding the project to the `cdk.json` file. Initially it appeared to work but when it was run on a clean project without a `cdk.out` directory it fails with the following error.
`ENOENT: no such file or directory, open 'cdk.out/manifest.json'`

**Comment by SachinShekhar** [comment]
@PeteLindsell I don't think this depends on `cdk.out` directory in any way. Another thing in your project is causing the issue. See this: https://github.com/aws/aws-cdk/issues/5815
