### ISSUE TITLE
real examples of architecture

### ISSUE THREAD

**Issue by andrefedev** [aws/aws-cdk#7055]
It is difficult to find an architecture where you can have tens of stacks with thousands of functions that represent microservices for an e-commerce store. How can you live the cdk code with the application source code, if each one has different environments, package.json, layers, eslint and other configurations. Thank You.

**Comment by SomayaB** [comment]
Hi @andrefedev, thanks for bringing this up. I can definitely see value in having more complex examples. I think a better place for this request would be the [cdk examples repo](https://github.com/aws-samples/aws-cdk-examples/issues), so I'm going to recreate your issue there. Have a good day!
