### ISSUE TITLE
Deploy fails when adding Cognito requiredAttributes as per documentation

### ISSUE THREAD

**Issue by fi5u** [aws/aws-cdk#7058]
The [CDK documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html#attributes) shows how to add required attributes to the Cognito user pool. However, when implemented as per the documentation, the deploy fails. Removing the the `requiredAttributes` property results in a successful build.

### Reproduction Steps

```
new cognito.UserPool(this, `${id}Pool`, {
  requiredAttributes: {
    email: true,
    fullname: true,
  },
  selfSignUpEnabled: true,
  signInAliases: {
    email: true,
    username: false,
  },
  userPoolName: `${id}UserPool`,
})
```

### Error Log

```
LappuApeStack: creating CloudFormation changeset...
 0/8 | 10:16:47 AM | UPDATE_IN_PROGRESS   | AWS::Cognito::UserPool                 | LappuApeStackPool (LappuApeStackPool52D61340)
 1/8 | 10:16:49 AM | UPDATE_FAILED        | AWS::Cognito::UserPool                 | LappuApeStackPool (LappuApeStackPool52D61340) Invalid AttributeDataType input, consider using the provided AttributeDataType enum. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 51786c92-4147-43e5-8bff-e1ed2717a3f9)
	new UserPool (/Users/fisu/Projects/lappu-ape/node_modules/@aws-cdk/aws-cognito/lib/user-pool.ts:518:22)
	\_ new LappuApeStack (/Users/fisu/Projects/lappu-ape/lib/lappu-ape-stack.ts:15:40)
	\_ Object.<anonymous> (/Users/fisu/Projects/lappu-ape/bin/lappu-ape.ts:6:1)
	\_ Module._compile (internal/modules/cjs/loader.js:955:30)
	\_ Module.m._compile (/Users/fisu/Projects/lappu-ape/node_modules/ts-node/src/index.ts:837:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	\_ Object.require.extensions.<computed> [as .ts] (/Users/fisu/Projects/lappu-ape/node_modules/ts-node/src/index.ts:840:12)
	\_ Module.load (internal/modules/cjs/loader.js:811:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:723:14)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
	\_ main (/Users/fisu/Projects/lappu-ape/node_modules/ts-node/src/bin.ts:226:14)
	\_ Object.<anonymous> (/Users/fisu/Projects/lappu-ape/node_modules/ts-node/src/bin.ts:485:3)
	\_ Module._compile (internal/modules/cjs/loader.js:955:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	\_ Module.load (internal/modules/cjs/loader.js:811:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:723:14)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
	\_ /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
 1/8 | 10:16:49 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack             | LappuApeStack The following resource(s) failed to update: [LappuApeStackPool52D61340].
```

### Environment

  - **CLI Version: 1.31.0 (build 8f3ac79)**
  - **Framework Version: 1.31.0**
  - **OS: MacOS 10.15.4**
  - **Language: Typescript**

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
The Cognito service limits that required attributes for a UserPool cannot be modified after it has been created. It turns out this is the error message they throw when this is performed.

I was able to create a new stack with a user pool with the configurations you have provided.

**Comment by fi5u** [comment]
@nija-at I've run `cdk destroy` then `cdk deploy` with nothing more than the above code, but still I get the same error message. Is there more required than `cdk destroy` to be able to implement required attributes after the user pool having already been created?

**Comment by nija-at** [comment]
`cdk destroy` should be sufficient.

Weird. I was able to run the exact code, that you pasted in the original description, and successfully created a user pool.

**Comment by fi5u** [comment]
Ok, I guess I'll try with a completely fresh project. Thanks.

**Comment by ShivamJoker** [comment]
> The Cognito service limits that required attributes for a UserPool cannot be modified after it has been created. It turns out this is the error message they throw when this is performed.
> 
> I was able to create a new stack with a user pool with the configurations you have provided.

Why is that? My stack depends on lot of other stack as well, so if I destroy cognito stack I need to destroy all the stack which it depends on.

**Comment by clayrosenthal** [comment]
I feel like this should force recreation instead of just erroring when you try to deploy... Destroying the whole stack (and its dependencies) is very disruptive.
