### ISSUE TITLE
RDS DatabaseClusterEngine.AURORA_MYSQL missing Defaults

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#7072]
## :question: General Issue

It's hard to get a working Aurora/Mysql stack out of the box currently. It's a bit confusing that there is DatabaseClusterEngine.AURORA_MYSQL and DatabaseClusterEngine.AURORA while the latter one seems to be old version 5.6 and the other one is 5.7?

It seems it's still required to set `engineVersion` and `parameterGroup` and still I don't get a working stack with this code:

```typescript
        const database = new DatabaseCluster(this, 'DatabaseCluster', {
            removalPolicy: RemovalPolicy.DESTROY,
            defaultDatabaseName: 'test',
            masterUser: {
                username: 'root',
                password: SecretValue.secretsManager(databaseSecret.secretArn),
            },
            instances: 1,
            engine: DatabaseClusterEngine.AURORA_MYSQL,
            parameterGroup: ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-mysql5.7'),
            engineVersion: '5.7',
            port: 3306,
            instanceProps: {
                instanceType: InstanceType.of(InstanceClass.R5, InstanceSize.XLARGE8),
                vpc: vpc,
                vpcSubnets: {
                    subnetType: SubnetType.PRIVATE,
                },
                securityGroup: securityGroupDB,
            },
            backup: {
                preferredWindow: '00:00-01:00',
                retention: Duration.days(14),
            },
        })
```

Cloudformation error is:
```
RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.r5.8xlarge, Engine=aurora-mysql, EngineVersion=5.7.12, LicenseModel=general-public-license
```

This might be due to Cloudformation being imprecise but I was expecting CDK to compensate this and set sensible defaults automatically.

### Environment

  - **CDK CLI Version:** 1.31.0
  - **Module Version:** 1.31.0
  - **OS:** OSX
  - **Language:** Typescript

**Comment by nija-at** [comment]
@konstantinj - we apologize for this poor experience with RDS. 

We have recognized the need that the RDS module needs a complete overhaul to fix this experience - https://github.com/aws/aws-cdk/issues/6713. 

Upvotes on this issue will help us prioritize this.
