### ISSUE TITLE
cdk deploy with context parameters not working on linux agents

### ISSUE THREAD

**Issue by sacag** [aws/aws-cdk#7076]
sh("cdk deploy -c awsAcctId=XXXXXXX StackName --require-approval never") in JenkinsFile from a Jenkins agent(Linux) does not recognize the context variables passed in.
Running the same command from my local(windows-10) using command prompt works fine.

Also, when i run the above command without specifying the context parameter, then that works fine from the jenkins agent(linux)

### Reproduction Steps

```
JenkinsFIle code: from jenkins agent
sh("cdk deploy -c awsAcctId=XXXXXXX StackName --require-approval never")
```
```
C# code: Program.cs
var app = new App();
var ctxParam = ""; 
ctxParam = app.Node.TryGetContext("awsAcctId").ToString();
```
app.Node.TryGetContext("awsAcctId") is NULL

As, I said, the above sh command works fine when called from Windows(command prompt) but not when called from Linux agent(in this case jenkins)

### Environment

  - **CLI Version      :**1.31
  - **Framework Version:**
  - **OS               :**
  - **Language         :** C#

### Other

--- 

This is :bug: Bug Report

**Comment by sacag** [comment]
Hello @skinny85, it will be great if you could give me some pointers as I am nearing a production deployment and would be good to get this going. Sorry for the rush as I am sure you must be swamped as well.

**Comment by skinny85** [comment]
Hey @sacag ,

what's the `sh` function quoted in your Jenkins config? Is that a Groovy script...? What language is that?

Thanks,
Adam

**Comment by sacag** [comment]
Yep, that's groovy

**Comment by skinny85** [comment]
Can you add `--verbose` to the argument, and paste the output? (if it gets too big, maybe use GitHub's gists).

**Comment by sacag** [comment]
So, I tried that, but doesn't even get to that point as it fails with null ref exception before. because in the C# code it doesn't find the value in the context.

**Comment by skinny85** [comment]
I don't understand...? `--verbose` is an argument to the `cdk` command, and it's the `cdk` command that executes the C#...?

If it didn't work, your C# would never be executed.

**Comment by sacag** [comment]
Let me try it again. What I meant was when the cdk deploy executes, it calls the C# code for deploying the stack with context parameters and that's when the C# code can't find the variable in the context. So, it wasn't printing any verbose log. But i can try again. Maybe I misplaced the -v option

**Comment by sacag** [comment]
sh("cdk deploy --context testVar=1234 pra-messaging-ssmparams-app --verbose=true")
I see this:
```
21:46:37  + cdk bootstrap aws://397090398856/us-east-1
21:46:40  (node:1139) ExperimentalWarning: The fs.promises API is experimental
21:46:42  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
21:46:42     at FMI.BioPharma.Messaging.Program.Main(String[] args) in /home/jenkins/workspace/ma.Messaging_release-1.1-testcdk/src/FMI.BioPharma.Messaging/Program.cs:line 23
21:46:42  Subprocess exited with error 134
```

**Comment by skinny85** [comment]
What's this?

```
21:46:37  + cdk bootstrap aws://XXXXXXXX/us-east-1
```

?

**Comment by sacag** [comment]
bootstrapping the account...just masked the account number here

**Comment by skinny85** [comment]
I understand. Where does that command comes from? You said the command was `sh("cdk deploy --context testVar=1234 pra-messaging-ssmparams-app --verbose=true")`.

**Comment by sacag** [comment]
just above that line i have another sh command:
sh("cdk bootstrap aws://"+GetRoleAccountNumber(params.DeployTo)+"/us-east-1")

**Comment by skinny85** [comment]
Can you add `--verbose` to that `bootstrap` command, and show the output?

**Comment by sacag** [comment]
that build is still running, but i tried this -  removed the cdk bootstrap command and used this:
cdk deploy --context testVar=1234 pra-messaging-ssmparams-app -v

that worked fine

**Comment by skinny85** [comment]
I don't understand - was it the bootstrap command failed previously...?

**Comment by sacag** [comment]
no bootstrap didn't fail. here is the log
```
22:00:36  CDK toolkit version: 1.31.0 (build 8f3ac79)
22:00:36  Command line arguments: { _: [ 'bootstrap' ],
22:00:36    verbose: true,
22:00:36    v: true,
22:00:36    'ignore-errors': false,
22:00:36    ignoreErrors: false,
22:00:36    json: false,
22:00:36    j: false,
22:00:36    ec2creds: undefined,
22:00:36    i: undefined,
22:00:36    'version-reporting': undefined,
22:00:36    versionReporting: undefined,
22:00:36    'path-metadata': true,
22:00:36    pathMetadata: true,
22:00:36    'asset-metadata': true,
22:00:36    assetMetadata: true,
22:00:36    'role-arn': undefined,
22:00:36    r: undefined,
22:00:36    roleArn: undefined,
22:00:36    staging: true,
22:00:36    'no-color': false,
22:00:36    noColor: false,
22:00:36    fail: false,
22:00:36    'bootstrap-bucket-name': undefined,
22:00:36    b: undefined,
22:00:36    'toolkit-bucket-name': undefined,
22:00:36    toolkitBucketName: undefined,
22:00:36    bootstrapBucketName: undefined,
22:00:36    'bootstrap-kms-key-id': undefined,
22:00:36    bootstrapKmsKeyId: undefined,
22:00:36    tags: [],
22:00:36    t: [],
22:00:36    execute: true,
22:00:36    trust: [],
22:00:36    'cloudformation-execution-policies': [],
22:00:36    cloudformationExecutionPolicies: [],
22:00:36    '$0': '/usr/bin/cdk',
22:00:36    ENVIRONMENTS: [ 'aws://397090398856/us-east-1' ],
22:00:36    environments: [ 'aws://397090398856/us-east-1' ] }
22:00:36  Determining whether we're on an EC2 instance.
22:00:36  Looks like EC2 instance.
22:00:36  cdk.json: {
22:00:36    "app": "dotnet run -p src/FMI.BioPharma.Messaging/FMI.BioPharma.Messaging.csproj",
22:00:36    "context": {
22:00:36      "vpc-id-dev": "vpc-6b37dc0d",
22:00:36      "subnet-ids-dev": "subnet-583a9103,subnet-22cf790f,subnet-eedfb9a7",
22:00:36      "routeTable-ids-dev": "rtb-94134af2,rtb-d8134abe,rtb-b5134ad3",
22:00:36      "securityGroup-id-dev": "sg-fb0b5e84",
22:00:36      "vpc-id-qa": "vpc-9c26cdfa",
22:00:36      "subnet-ids-qa": "subnet-a1c2a4e8,subnet-3dd36510,subnet-4f56fd14",
22:00:36      "routeTable-ids-qa": "rtb-60f5ab06,rtb-96f4aaf0,rtb-bcf4aada",
22:00:36      "securityGroup-id-qa": "sg-d7567ea8",
22:00:36      "vpc-id-stg": "vpc-b2fe15d4",
22:00:36      "subnet-ids-stg": "subnet-4fe78106,subnet-6170db3a,subnet-caf640e7",
22:00:36      "routeTable-ids-stg": "rtb-15df8173,rtb-45dc8223,rtb-d5df81b3",
22:00:36      "securityGroup-id-stg": "sg-d2523dad",
22:00:36      "vpc-id-prod": "vpc-69f2190f",
22:00:36      "subnet-ids-prod": "subnet-4de48204,subnet-86f741ab,subnet-8777dcdc",
22:00:36      "routeTable-ids-prod": "rtb-4adc822c,rtb-35dc8253,rtb-18dc827e",
22:00:36      "securityGroup-id-prod": "sg-b92b30c6",
22:00:36      "notificationEmail": "pharma.dev@foundationmedicine.com",
22:00:36      "notificationEmailQA": "pharma.qa@foundationmedicine.com",
22:00:36      "enableLogZioLogShipping": "false",
22:00:36      "aws_account_id": "397090398856|DEV"
22:00:36    }
22:00:36  }
22:00:36  cdk.context.json: {
22:00:36    "@aws-cdk/core:enableStackNameDuplicates": "true"
22:00:36  }
22:00:36  merged settings: { versionReporting: true,
22:00:36    pathMetadata: true,
22:00:36    output: 'cdk.out',
22:00:36    app:
22:00:36     'dotnet run -p src/FMI.BioPharma.Messaging/FMI.BioPharma.Messaging.csproj',
22:00:36    context:
22:00:36     { 'vpc-id-dev': 'cxccxcxcxcxc',
22:00:36       'subnet-ids-dev': 'xxccxcxcx',
22:00:36       'routeTable-ids-dev': 'sdsdsdssd',
22:00:36       'securityGroup-id-dev': 'dssddsd',
22:00:36      
22:00:36    tags: [],
22:00:36    assetMetadata: true,
22:00:36    toolkitBucket: {},
22:00:36    staging: true }
22:00:36  Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
22:00:36  Resolving default credentials
22:00:36  Looking up default account ID from STS
22:00:36  Default account ID: 397090398856
22:00:36  Setting "CDK_DEFAULT_ACCOUNT" environment variable to 397090398856
22:00:36  context: { '@aws-cdk/core:enableStackNameDuplicates': 'true',
22:00:36    'vpc-id-dev': 'vpc-6b37dc0d',
22:00:36    'subnet-ids-dev': 'subnet-583a9103,subnet-22cf790f,subnet-eedfb9a7',
22:00:36    'routeTable-ids-dev': 'rtb-94134af2,rtb-d8134abe,rtb-b5134ad3',
22:00:36    'securityGroup-id-dev': 'sg-fb0b5e84',


22:00:36    'aws:cdk:enable-path-metadata': true,
22:00:36    'aws:cdk:enable-asset-metadata': true }
22:00:36  outdir: cdk.out
22:00:36  env: { CDK_DEFAULT_REGION: 'us-east-1',
22:00:36    CDK_DEFAULT_ACCOUNT: '397090398856',
22:00:36    CDK_CONTEXT_JSON:
22:00:36     '{"@aws-cdk/core:enableStackNameDuplicates":"true","vpc-id-dev":"dsdsds","subnet-ids-dev":"dsdsdsds","routeTable-ids-dev":"ssddsds","securityGroup-id-dev":"ccsdss",
"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
22:00:36    CDK_OUTDIR: 'cdk.out',
22:00:36    CDK_CLI_ASM_VERSION: '1.21.0',
22:00:36    CDK_CLI_VERSION: '1.31.0' }
22:00:39  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
22:00:39     at FMI.BioPharma.Messaging.Program.Main(String[] args) in /home/jenkins/workspace/ma.Messaging_release-1.1-testcdk/src/FMI.BioPharma.Messaging/Program.cs:line 23
22:00:39  Subprocess exited with error 134
22:00:39  Error: Subprocess exited with error 134
22:00:39      at ChildProcess.proc.on.code (/usr/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:115:23)
22:00:39      at ChildProcess.emit (events.js:182:13)
22:00:39      at ChildProcess.EventEmitter.emit (domain.js:441:20)
22:00:39      at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

**Comment by skinny85** [comment]
What command failed? If it was `cdk deploy`, where is this part of the output:

```
22:00:36  CDK toolkit version: 1.31.0 (build 8f3ac79)
22:00:36  Command line arguments: { _: [ 'bootstrap' ],
```

that you can see for `cdk bootstrap --verbose`?

**Comment by sacag** [comment]
```
+ cdk deploy -c aws_account_id=397090398856
22:21:27  + DEV pra-messaging-ssmparams-app --require-approval never -v
22:21:27  /home/jenkins/workspace/ma.Messaging_release-1.1-testcdk@tmp/durable-31dcff0d/script.sh: 1: /home/jenkins/workspace/ma.Messaging_release-1.1-testcdk@tmp/durable-31dcff0d/script.sh: DEV: not found
22:21:28  (node:1129) ExperimentalWarning: The fs.promises API is experimental
22:21:36  Since this app includes more than a single stack, specify which stacks to use (wildcards are supported)
22:21:36  Stacks: pra-messaging-check-health-app pra-messaging-client-app pra-messaging-msgDetails-app pra-messaging-msgDetails-filtered-app pra-messaging-notification-app pra-messaging-ssmparams-app pra-messaging-stepfunction-apigateway-app pra-messaging-study-app pra-messaging-variant-app


```

**Comment by sacag** [comment]
not sure why that message as i am specifying the correct stackname

**Comment by skinny85** [comment]
I think the message is pretty clear: you need to specify which stack to deploy (for example, `cdk deploy pra-messaging-check-health-app`). For all stacks, use `cdk deploy \*`.

**Comment by sacag** [comment]
but i do have this: + DEV pra-messaging-ssmparams-app --require-approval never -v
but is truncated for some reason in the log

**Comment by skinny85** [comment]
I think something is wrong with your argument passing. I would look into the `sh` function.

**Comment by skinny85** [comment]
The fact that you don't get any output when passing `--verbose` to `cdk deploy` also confirms that.

**Comment by sacag** [comment]
okay i will look into it and get back..thanks @skinny85

**Comment by sacag** [comment]
@skinny85 - I can confirm that whenever I do cdk bootstrap and then next line cdk deploy, that is causing the issue to not send the context parameters over. When I comment the cdk bootstarp, things work fine. Ideas? I believe I need to do cdk bootstrap as I have assets in the stack(s). Right?

**Comment by skinny85** [comment]
Can you paste the output of the script, that includes both `cdk bootstrap --verbose` and `cdk deploy --verbose`?

**Comment by sacag** [comment]
So, both doesn't work simultaneously..I will paste the verbose output by executing them one by one

**Comment by sacag** [comment]
below is when cdk bootstrap is commented out and is verbose output for cdk deploy
11:49:41  + cdk deploy -c awsAcctId=XXXXXXXXXX__DEV pra-messaging-ssmparams-app --require-approval never --verbose=true
11:49:42  (node:1155) ExperimentalWarning: The fs.promises API is experimental
11:49:42  CDK toolkit version: 1.31.0 (build 8f3ac79)
11:49:42  Command line arguments: { _: [ 'deploy' ],
11:49:42    c: [ 'awsAcctId=XXXXXXXXXX__DEV' ],
11:49:42    context: [ 'awsAcctId=XXXXXXXXX__DEV' ],
11:49:42    'require-approval': 'never',
11:49:42    requireApproval: 'never',
11:49:42    verbose: true,
11:49:42    v: true,
11:49:42    'ignore-errors': false,
11:49:42    ignoreErrors: false,
11:49:42    json: false,
11:49:42    j: false,
11:49:42    ec2creds: undefined,
11:49:42    i: undefined,
11:49:42    'version-reporting': undefined,
11:49:42    versionReporting: undefined,
11:49:42    'path-metadata': true,
11:49:42    pathMetadata: true,
11:49:42    'asset-metadata': true,
11:49:42    assetMetadata: true,
11:49:42    'role-arn': undefined,
11:49:42    r: undefined,
11:49:42    roleArn: undefined,
11:49:42    staging: true,
11:49:42    'no-color': false,
11:49:42    noColor: false,
11:49:42    fail: false,
11:49:42    'build-exclude': [],
11:49:42    E: [],
11:49:42    buildExclude: [],
11:49:42    ci: false,
11:49:42    execute: true,
11:49:42    force: false,
11:49:42    f: false,
11:49:42    parameters: [ {} ],
11:49:42    '$0': '/usr/bin/cdk',
11:49:42    STACKS: [ 'pra-messaging-ssmparams-app' ],
11:49:42    stacks: [ 'pra-messaging-ssmparams-app' ] }
11:49:42  Determining whether we're on an EC2 instance.
11:49:42  Looks like EC2 instance.
11:49:42  CLI argument context: awsAcctId=397090398856__DEV
11:49:42  cdk.json: {
11:49:42    "app": "dotnet run -p src/FMI.BioPharma.Messaging/FMI.BioPharma.Messaging.csproj",
11:49:42    "context": {
11:49:42     //removed the context vars for clarity
11:49:42    }
11:49:42  }
11:49:42  cdk.context.json: {
11:49:42    "@aws-cdk/core:enableStackNameDuplicates": "true"
11:49:42  }
11:49:42  merged settings: { versionReporting: true,
11:49:42    pathMetadata: true,
11:49:42    output: 'cdk.out',
11:49:42    app:
11:49:42     'dotnet run -p src/FMI.BioPharma.Messaging/FMI.BioPharma.Messaging.csproj',
11:49:42    context:
11:49:42     { //removed context vars },
11:49:42    tags: [],
11:49:42    assetMetadata: true,
11:49:42    requireApproval: 'never',
11:49:42    toolkitBucket: {},
11:49:42    staging: true }
11:49:42  Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
11:49:42  Resolving default credentials
11:49:42  Looking up default account ID from STS
11:49:42  Default account ID: XXXXXXX
11:49:42  Setting "CDK_DEFAULT_ACCOUNT" environment variable to XXXXXXXX
11:49:42  context: { '@aws-cdk/core:enableStackNameDuplicates': 'true',

11:49:42    awsAcctId: 'XXXXXXXXX__DEV',
11:49:42    'aws:cdk:enable-path-metadata': true,
11:49:42    'aws:cdk:enable-asset-metadata': true }
11:49:42  outdir: cdk.out
11:49:42  env: { CDK_DEFAULT_REGION: 'us-east-1',
11:49:42    CDK_DEFAULT_ACCOUNT: 'XXXXXXXX',
11:49:42    CDK_CONTEXT_JSON:
11:49:42     '{"@aws-cdk/core:enableStackNameDuplicates":"true","awsAcctId":"XXXXXXXXX__DEV","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
11:49:42    CDK_OUTDIR: 'cdk.out',
11:49:42    CDK_CLI_ASM_VERSION: '1.21.0',
11:49:42    CDK_CLI_VERSION: '1.31.0' }
11:49:45  hello there.. the value is XXXXXXXXX__DEV
11:49:49  pra-messaging-ssmparams-app: deploying...

**Comment by sacag** [comment]
below output for bootstrap verbose and **did not** comment out the cdk deploy...so the error at the bottom as well

12:16:09  + cdk bootstrap --verbose=true
12:16:11  (node:1136) ExperimentalWarning: The fs.promises API is experimental
12:16:11  CDK toolkit version: 1.31.0 (build 8f3ac79)
12:16:11  Command line arguments: { _: [ 'bootstrap' ],
12:16:11    verbose: true,
12:16:11    v: true,
12:16:11    'ignore-errors': false,
12:16:11    ignoreErrors: false,
12:16:11    json: false,
12:16:11    j: false,
12:16:11    ec2creds: undefined,
12:16:11    i: undefined,
12:16:11    'version-reporting': undefined,
12:16:11    versionReporting: undefined,
12:16:11    'path-metadata': true,
12:16:11    pathMetadata: true,
12:16:11    'asset-metadata': true,
12:16:11    assetMetadata: true,
12:16:11    'role-arn': undefined,
12:16:11    r: undefined,
12:16:11    roleArn: undefined,
12:16:11    staging: true,
12:16:11    'no-color': false,
12:16:11    noColor: false,
12:16:11    fail: false,
12:16:11    'bootstrap-bucket-name': undefined,
12:16:11    b: undefined,
12:16:11    'toolkit-bucket-name': undefined,
12:16:11    toolkitBucketName: undefined,
12:16:11    bootstrapBucketName: undefined,
12:16:11    'bootstrap-kms-key-id': undefined,
12:16:11    bootstrapKmsKeyId: undefined,
12:16:11    tags: [],
12:16:11    t: [],
12:16:11    execute: true,
12:16:11    trust: [],
12:16:11    'cloudformation-execution-policies': [],
12:16:11    cloudformationExecutionPolicies: [],
12:16:11    '$0': '/usr/bin/cdk' }
12:16:11  Determining whether we're on an EC2 instance.
12:16:11  Looks like EC2 instance.
12:16:11  cdk.json: {
12:16:11    "app": "dotnet run -p src/FMI.BioPharma.Messaging/FMI.BioPharma.Messaging.csproj",
12:16:11    "context": {
12:16:11      //removed context vars
12:16:11    }
12:16:11  }
12:16:11  cdk.context.json: {
12:16:11    "@aws-cdk/core:enableStackNameDuplicates": "true"
12:16:11  }
12:16:11  merged settings: { versionReporting: true,
12:16:11    pathMetadata: true,
12:16:11    output: 'cdk.out',
12:16:11    app:
12:16:11     'dotnet run -p src/FMI.BioPharma.Messaging/FMI.BioPharma.Messaging.csproj',
12:16:11    context:
12:16:11     { //removed context vars },
12:16:11    tags: [],
12:16:11    assetMetadata: true,
12:16:11    toolkitBucket: {},
12:16:11    staging: true }
12:16:11  Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
12:16:11  Resolving default credentials
12:16:11  Looking up default account ID from STS
12:16:11  Default account ID: XXXXXXXXXX
12:16:11  Setting "CDK_DEFAULT_ACCOUNT" environment variable to XXXXXXXXXXXXXXXX
12:16:11  context: { '@aws-cdk/core:enableStackNameDuplicates': 'true',
12:16:11    //removed context vars
12:16:11    'aws:cdk:enable-path-metadata': true,
12:16:11    'aws:cdk:enable-asset-metadata': true }
12:16:11  outdir: cdk.out
12:16:11  env: { CDK_DEFAULT_REGION: 'us-east-1',
12:16:11    CDK_DEFAULT_ACCOUNT: 'XXXXXXXXXX',
12:16:11    CDK_CONTEXT_JSON:
12:16:11     '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
12:16:11    CDK_OUTDIR: 'cdk.out',
12:16:11    CDK_CLI_ASM_VERSION: '1.21.0',
12:16:11    CDK_CLI_VERSION: '1.31.0' }
12:16:14  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
12:16:14     at FMI.BioPharma.Messaging.Program.Main(String[] args) in /home/jenkins/workspace/ma.Messaging_release-1.1-testcdk/src/FMI.BioPharma.Messaging/Program.cs:line 26
12:16:14  Subprocess exited with error 134
12:16:14  Error: Subprocess exited with error 134
12:16:14      at ChildProcess.proc.on.code (/usr/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:115:23)
12:16:14      at ChildProcess.emit (events.js:182:13)
12:16:14      at ChildProcess.EventEmitter.emit (domain.js:441:20)
12:16:14      at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

**Comment by sacag** [comment]
@skinny85 - maybe I need to pass the context variables in the cdk bootstrap command as well? Because I see that cdk bootstrap calls the code in Program.cs as shown in the original bug report. And cdk bootstrap doesn't have the context variable and hence null reference exception. I will try that

**Comment by sacag** [comment]
@skinny85 - yep that was it. I got it to work after i passed in the context variables to cdk bootstrap as well.

**Comment by skinny85** [comment]
👍

Feel free to reopen if you need anything else from our side for this issue.
