### ISSUE TITLE
EKS Update API server endpoint access functionality

### ISSUE THREAD

**Issue by nikhilbhoj** [aws/aws-cdk#7084]
Hi,

I was searching for EKS package if I can update EKS  API server endpoint access private or public ( in public also white list IP ranges).

But, I was unable to find that functilanity ot options in EKS package.

CDK version 1.28.
Language : Typescript

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Can you please provide a reference to AWS docs with the feature you need?

**Comment by nikhilbhoj** [comment]
Hi @eladb 

This is reference for the AWS docs that mentions this functionality.

https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html

Thanks,
Nikhil

**Comment by arjanschaaf** [comment]
@eladb isn't this an duplicate of this issue? https://github.com/aws/aws-cdk/issues/5220

**Comment by eladb** [comment]
Dup https://github.com/aws/aws-cdk/issues/5220
