### ISSUE TITLE
Support include body for LambdaFunctionAssociation

### ISSUE THREAD

**Issue by prax0724** [aws/aws-cdk#7085]
When creating lambda-edge behaviours from AWS console , we can select Include Body for lambda edge association.
But the same configuration can't be done by AWS CDK because Include Body property is not available in LambdaFunctionAssociation class.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.LambdaFunctionAssociation.html

**Comment by nitishdhar** [comment]
Is there an intermediate way to achieve this for now?

**Comment by marcgreenstock** [comment]
@nirvana124 it's convoluted but the CDK provides a [raw override](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw).

Here's how I got it working:

```ts
const distribution = new cloudfront.CloudFrontWebDistribution(this, 'WebDistribution', {
  originConfigs: [{
    s3OriginSource: {
      s3BucketSource: bucket
    },
    behaviors: [{
      isDefaultBehavior: true,
      compress: true
    }, {
      pathPattern: 'api/*',
      compress: true,
      allowedMethods: cloudfront.CloudFrontAllowedMethods.ALL,
      minTtl: cdk.Duration.days(0),
      maxTtl: cdk.Duration.days(0),
      defaultTtl: cdk.Duration.days(0),
      forwardedValues: {
        queryString: true,
        cookies: {
          forward: 'all'
        }
      },
      lambdaFunctionAssociations: [{
        eventType: cloudfront.LambdaEdgeEventType.ORIGIN_REQUEST,
        lambdaFunction: apiLambdaVersion
      }]
    }]
  }]
})
// get the CloudFormation template
const distributionCfn = distribution.node.defaultChild as cloudfront.CfnDistribution
// Add IncludeBody on the first cache behavior - indexed at 0 because the default behaviour is not on the CacheBehaviors array 
distributionCfn.addOverride('Properties.DistributionConfig.CacheBehaviors.0.LambdaFunctionAssociations.0.IncludeBody', true)
```

`distributionCfn` above is the CloudFormation template which would look something like this:

```yaml
Type: AWS::CloudFront::Distribution
Properties: 
  DistributionConfig:
    DefaultCacheBehavior:
      ...
    CacheBehaviors:
      - PathPatern: api/*
        LambdaFunctionAssociations:
          - EventType: origin-request
            LambdaFunctionARN: arn:...
```

The first argument in `addOverride` is a path to the [AWS::CloudFront::Distribution LambdaFunctionAssociation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-lambdafunctionassociation.html).

So `Properties.DistributionConfig.CacheBehaviors.0.LambdaFunctionAssociations.0.IncludeBody` adds `IncludeBody` to `LambdaFunctionAssociations[0]` on `CacheBehaviors[0]`.

Hopefully this will get sorted out soon, and we won't need to do this. Looks like the property in the CDK was just overlooked.

**Comment by iliapolo** [comment]
Hi @marcgreenstock and @nitishdhar 

Yeap, this is just an oversight. Adding to our docket. 

Thanks for reporting this and thanks @marcgreenstock for the correct workaround 👍

**Comment by prax0724** [comment]
@marcgreenstock Thanks!! your solution worked for me as well.
