### ISSUE TITLE
CloudWatch Events or EventBridge?

### ISSUE THREAD

**Issue by 0xdevalias** [aws/aws-cdk#7088]
As per the comment I raised in https://github.com/aws/aws-cdk/issues/4455#issuecomment-606473416 it's kind of confusing that all of the doco talks about `CloudWatch Events`, yet the service is called `EventBridge`. Did this get rebranded or something? Should the doco be updated to better match the current reality?

- https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-readme.html
  - > Amazon **CloudWatch Events** Construct Library
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Events.html
  - > Amazon **EventBridge** Resource Type Reference

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Yep, it did get rebranded. Thanks for bringing this to our attention.
