### ISSUE TITLE
Expand Availability Zones for a VPC subnet configuration.

### ISSUE THREAD

**Issue by phillipCouto** [aws/aws-cdk#7095]
It would be great if we can easily expand the VPC subnets to utilize additional availability zones without having to recreate the VPC.

### Use Case

The Canadian region just expanded its Availability zones and we would like to take advantage of the increased availability. Currently we only have two options, create a new availability zone or hack a way in the CDK to add the additional resources that is not intuitive with how the VPC was originally created.

### Proposed Solution

When we are providing the subnet configuration when it renders out the list of subnets we can utilize the list of subnets already defined to add the additional ones to the end of the array so existing subnets are not impacted.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
The problem here is more around IP space allocation. The available IP space has been completely divvied up already, so adding more subnets is not possible.

**Comment by rix0rrr** [comment]
Duplicate: https://github.com/aws/aws-cdk/issues/7073
Related: https://github.com/aws/aws-cdk/issues/5927
