### ISSUE TITLE
EventBus construct: Add more restricted grantPutEvents method

### ISSUE THREAD

**Issue by 0xdevalias** [aws/aws-cdk#7103]
Currently the `EventBus` construct has a static method `grantPutEvents(grantee)`:

- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.EventBus.html#static-grant-wbr-put-wbr-eventsgrantee

This gives `grantee` the ability to `events:PutEvents` on `*`:

```
IAM Statement Changes
┌───┬──────────┬────────┬──────────────────┬──────────────────────────────────────────────────────────┬───────────┐
│   │ Resource │ Effect │ Action           │ Principal                                                │ Condition │
├───┼──────────┼────────┼──────────────────┼──────────────────────────────────────────────────────────┼───────────┤
│ + │ *        │ Allow  │ events:PutEvents │ AWS:${FnFoo/Handler/ServiceRole}                         │           │
└───┴──────────┴────────┴──────────────────┴──────────────────────────────────────────────────────────┴───────────┘
```

It would be nice if we could restrict this `*` to a single `EventBus` (or specified `EventBus`'s)

### Use Case

Principal of least privilege, restrict the access/abilities to the minimal required to do the job.

### Proposed Solution

Add a non-static `grantPutEvents(grantee)` method on the `EventBus` construct that restricts the resource in the policy to this `EventBus`. It should be possible for a `grantee` to have access to multiple specific `EventBus`'s in this way.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by zsolt-halo** [comment]
I have stumbled upon this issue when I've spent considerable time trying to figure if it is possible to add an event-bus policy to custom event-bus.

For me, it is not apparent what does this static method operates on and how it should be used.

Considering these 2 issues it won't work out of the box either: 

- https://github.com/aws/aws-cdk/issues/1785
- https://github.com/aws/aws-cdk/issues/7103

I +1 this feature request as having the ability to add a policy (with a condition) to an event-bus defined in CDK is essential to make it useful.

Thanks :)

**Comment by DaWyz** [comment]
This is a duplicate of #11228. It was resolved in [this commit](https://github.com/aws/aws-cdk/commit/122a232343699304d8f206d3024fcddfb2a94bc8).

Use the `grantPutEventsTo()` method.

```ts
const eventBus = EventBus.fromEventBusArn(this, 'ImportedEventBus', 'arn:aws:events:us-east-1:111111111:event-bus/my-event-bus');
// now you can just call methods on the eventbus
eventBus.grantPutEventsTo(lambdaFunction);
```
