### ISSUE TITLE
LinuxBuildImage constant set is missing latest CodeBuild Linux images: "al2/standard/3.0" and "ubuntu/standard/4.0"

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#7110]
Using CDK CLI and libraries v. 1.31.0.

CodeBuild supports new [build images](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html), latest two of which are not surfaced through the `LinuxBuildImage` constants. `LinuxBuildImage.AMAZON_LINUX_2_2` and `LinuxBuildImage.STANDARD_3_0` - latest in CDK, while CodeBuild has newer ones.

Not having these images made available through CDK prevents .NET 3.1 SDK builds in CodeBuild.

### Use Case

To avoid having manually change CodeBuild image settings in AWS Console after `cdk deploy`.

### Proposed Solution

Add `AMAZON_LINUX_3` and `STANDARD_4_0` constants to the `LinuxBuildImage` class, mapping to "al2/standard/3.0" and "ubuntu/standard/4.0" build images respectively.

### Other

.NET 3.1 application build fails at an attempt to set "dotnet: 3.1" runtime on the build image.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by chefren** [comment]
Looks like it was done in #6967

**Comment by vgribok** [comment]
Yes, this is a dup.
