### ISSUE TITLE
SecurityGroup: add support for adding Ingress Rules that reference Security Groups from a Peered VPC

### ISSUE THREAD

**Issue by RolandOtta** [aws/aws-cdk#7111]
### Use Case

we have multiple sub accounts that are connected with vpc peering.
we need to manage security-groups that reference security-groups from a peered account like it is possible in cloudformation with 
SourceSecurityGroupOwnerId and
SourceSecurityGroupId in the AWS::EC2::SecurityGroup

from what i have seen so far this is not possible with the addIngressRule method of the ec2 securitygroup

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
This needs an additional implementation of `IPeer`.

**Comment by singlewind** [comment]
Can write like this
`
    const incomingSecurityGroup = new SecurityGroup(
      this,
      "IncomingSecurityGroup",
      {
        vpc: imports.vpc,
        allowAllOutbound: true,
      }
    );

    incomingSecurityGroup.addIngressRule(incomingSecurityGroup, Port.tcp(props.lokiHttpPort), 'Internal HTTP');
    incomingSecurityGroup.addIngressRule(incomingSecurityGroup, Port.tcp(props.lokiGrpcPort), 'Internal GRPC');
    incomingSecurityGroup.addIngressRule(incomingSecurityGroup, Port.tcp(props.lokiMemberlistPort), 'Internal Memberlist');
`

**Comment by dev-d** [comment]
Not sure how @singlewind 's solution solves the problem. 

Tried using `ec2.CfnSecurityGroupIngress` - in theory it should work, but It did not.

**Comment by mikeatlas** [comment]
@dev-d Any luck since posting? 
@rix0rrr I might be up for making said `IPeer` implementation...

**Comment by singlewind** [comment]
> Not sure how @singlewind 's solution solves the problem.
> 
> Tried using `ec2.CfnSecurityGroupIngress` - in theory it should work, but It did not.

Sorry, I misunderstood the problem.

**Comment by therealvio** [comment]
Any updates on this?

Connecting vpc-peered security groups is something we are looking to do too :)

**Comment by BDeus** [comment]
maybe it can be closed, because there are an implementation of Peer SG with another account ?
`Peer.securityGroupId(sgId, accoungId)`

**Comment by MrArnoldPalmer** [comment]
This was solved by https://github.com/aws/aws-cdk/pull/18248, reopen if you're still having an issue. Thanks
