### ISSUE TITLE
You must supply at least 2 intervals for autoscaling

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#7118]
It's currently not possible to use only 1 interval for autoscaling while this is possible with bare Cloudformation. What I want to achieve is that it scales up on memory reservation but scales down at the end of the day. It's running a game which has over day more or less users but at night almost no users so it's safe to scale down.

### Reproduction Steps
```typescript
        const autoScalingGroup = new AutoScalingGroup(this, 'AutoScalingGroup', {
            vpc: vpc,
            instanceType: InstanceType.of(InstanceClass.R5, InstanceSize.XLARGE2),
            machineImage: EcsOptimizedImage.amazonLinux2(),
            updateType: UpdateType.ROLLING_UPDATE,
            allowAllOutbound: true,
            desiredCapacity: 2,
            minCapacity: 1,
            maxCapacity: 4,
            keyName: 'delta',
            cooldown: Duration.seconds(30),
            spotPrice: '0.3',
        })
        autoScalingGroup.scaleOnMetric('ScaleOnLowMemoryReservation', {
            adjustmentType: AdjustmentType.CHANGE_IN_CAPACITY,
            metric: this.cluster.metricMemoryReservation(),
            scalingSteps: [
                {lower: 80, change: +1},
            ],
        })
```

### Error Log

`You must supply at least 2 intervals for autoscaling`

### Environment

  - **CLI Version      :** 1.31.0
  - **Framework Version:** 1.31.0
  - **OS               :** OSX
  - **Language         :** typescript

--- 

This is :bug: Bug Report

**Comment by konstantinj** [comment]
And another one. I'm getting this error when using `cooldown`: `Property Cooldown cannot be specified.`

```typescript
        autoScalingGroup.scaleOnMetric('ScaleOnLowMemoryReservation', {
            adjustmentType: AdjustmentType.CHANGE_IN_CAPACITY,
            metric: this.cluster.metricMemoryReservation(),
            scalingSteps: [
                {lower: 80, change: +1},
                {lower: 1, change: -1},
            ],
            cooldown: Duration.minutes(10),
        })
```

**Comment by NetaNir** [comment]
HI @konstantinj!

Maybe [scheduled-scaling](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-applicationautoscaling-readme.html#scheduled-scaling) will be a better fit for your use-case?

Regarding the `cooldown: Property Cooldown cannot be specified.`, I couldn't recreate it locally, could you paste the entire code? including imports.

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.

**Comment by altso** [comment]
You can specify 0 as a change to workaround 2 intervals limitation

```ts
scalingSteps: [
  { upper: 0, change: -1 },
  { lower: 888, upper: 999, change: 0 }, // dummy step, will be ignored
],
```
