### ISSUE TITLE
NetworkLoadBalancedFargateService with isolated subnets in VPC

### ISSUE THREAD

**Issue by fredgrossmann** [aws/aws-cdk#7131]
The NetworkLoadBalancedFargateService construct does not allow for configuring which subnets are passed into the FargateService construct.

I would like to create a NetworkLoadBalancedFargateService within an isolated subnet.

### Reproduction Steps

```
    const vpc = new Vpc(this, "SomeVpc", {
      subnetConfiguration: [
        {
          subnetType: SubnetType.ISOLATED,
          cidrMask: 20,
          name: "Isolated"
        }
      ]
    });

    new NetworkLoadBalancedFargateService(this, "SomeService", {
      taskImageOptions: {
        containerPort: 8080,
        image: ContainerImage.fromAsset("/path/to/image"),
      },
      publicLoadBalancer: false,
      vpc
    });
```

### Error Log

```
Error: There are no 'Private' subnet groups in this VPC. Available types: Isolated
```

### Environment

  - **CLI Version      :** 1.27.0
  - **Framework Version:** 1.23.0
  - **OS               :** OSX
  - **Language         :** TypeScript

### Other

This check assumes subnets are either public or private:
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/base/base-service.ts#L588

Should we include isolated subnets there as well?

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/aws-cdk/pull/3786

**Comment by iamhopaul123** [comment]
Hello @fredgrossmann I tried to reproduce the issue but it seems like this issue is now resolved. However, we are also planning to add a new field `vpcSubnets` to the load balanced fargate pattern allowing you to select the subnets that you want your tasks to run in.

Close this issue for now. Feel free to reopen if you think it still exists.

**Comment by jgarside-hrp** [comment]
@iamhopaul123 it seems like `vpcSubnets` was only added to `ApplicationLoadBalancedFargateService` and not `NetworkLoadBalancedFargateService`?

I also tried using `taskSubnets` but it doesn't have any affect on the NLB subnets.

**Comment by hardcode83** [comment]
> @iamhopaul123 it seems like `vpcSubnets` was only added to `ApplicationLoadBalancedFargateService` and not `NetworkLoadBalancedFargateService`?
> 
> I also tried using `taskSubnets` but it doesn't have any affect on the NLB subnets.
> 
> The NLB always uses all available subnets meaning I can't use it because I have multiple subnets in the same availability zone.
> 
> Although I _was_ able to get it working by passing in a `loadBalancer`.

I have the same problem in NetworkLoadBalancedFargateService yet, anybody knows if any from cdk team is working in this issue?

Thx Jose
