### ISSUE TITLE
EKS node-termination-handler on multiple ASG/Capacity

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#7136]
At this moment, the `spot-termination-handler` goes with the `AutoScalingGroup` resource

https://github.com/aws/aws-cdk/blob/d6ecf44e84cb326bcbfe48583fdae66829a86adb/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L590-L594

However, it's possible to get duplicate 'manifest-spot-interrupt-handler' error when we create more than 1 ASG or Capacity with spotPrice

```
There is already a Construct with name 'manifest-spot-interrupt-handler' in Cluster [my cluster name]
```

A quick fix is on its naming format to allow each ASG with spotPrice deploy its own `node-termination-handler` but it doesn't make sense as we just need one handler for all spot instances in the cluster. Another fix is to make the `node-termination-handler` per cluster and enabled by default, for example. `nodeTerminationHandler: true` for `Cluster` resource and user can opt-out with it.

### Error Log

```
There is already a Construct with name 'manifest-spot-interrupt-handler' in Cluster [my cluster name]
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by pahud** [comment]
copy @eladb

**Comment by eladb** [comment]
Definitely makes sense to go with a cluster level handler. But we can enable it automatically only if there are spot instances, not always. No?
