### ISSUE TITLE
aws-appsync: Support DataSource type NONE

### ISSUE THREAD

**Issue by christophgysin** [aws/aws-cdk#7144]
Currently aws-appsync only supports data source types `AMAZON_DYNAMODB` and `AWS_LAMBDA`. This is a request to add support for type `NONE`.

### Use Case

To trigger GraphQL subscriptions from the backend, it's common to create a mutation that is triggerd by the backend. These don't necessarily need an actual datasource, and the AppSync data source type `NONE` can be used instead.

### Proposed Solution

Add a new type `NoneDataSource` and a method `GraphQLApi.addNoneDataSource()`.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change
---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
This makes sense. Do you have any examples we could see of this in use? Just want to understand the use-case a little better.

**Comment by christophgysin** [comment]
fixed in #7145
