### ISSUE TITLE
Controlled deployment to API Gateways stages

### ISSUE THREAD

**Issue by alex-a-ncino** [aws/aws-cdk#7146]
### The Question

I am using CDK to create an api gateway with 2 stages, 2 deployments, autoDeploy disabled/false, in order to control deploying the changes (adding resource and/or method) to a specific stage at a time(one of the two stages). I am running into some issues and changes get deployed to both stages when I switch the "target" stage. 
**Scenario 1**: Deploy the api with the target deployment blue (By setting the deploymentStage). Deploy the same code without any change to the second stage/green and it gets deployed to blue as well.

**Scenario 2**: Do the initial deployment for blue first, and then green. Add a new method to the api, deploy to blue. The new method gets deployed to both blue and green.

**Expected behavior**: The deploy should only impact the target stage.

### Environment

  - **CDK CLI Version:** 1.22.0 
  - **Module Version:** 1.26.0 
  - **OS:**  [OSX Catalina]
  - **Language:** TypeScript] 

### Other information
The expected behavior is based on my understanding of the documentation.

I can provide sample code if needed

**Comment by nija-at** [comment]
@alex-a-ncino - 

Could you provide a code sample on your set up?

Further, in this code sample, can you describe how you change your 'target stage' from blue to green and vice versa?

Is there any documentation you are referring to for blue/green deployments of APIGW using stages? Could you provide links to them as well?

Thanks.

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
