### ISSUE TITLE
[Lambda] always create an implicit Version object

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#715]
An [AWS::Lambda::Version](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html) queries Lambda for a function's version number just after creation, and will return its own ARN as fully qualified (version and everything).

When you update a Step Functions state machine, executions in progress will keep on executing the old state machine. However, if the Lambda references in there are pointing to unqualified versions, the old definitions will start executing the new Lambdas! (This is probably not what you want)

The `Version` object is only there to import the result of an API call into CloudFormation for the duration of a single deployment, so it can have an ephemeral ID. That is, it may be changed on every deployment--this is fine. If we want to do more sophisticated things, we might tie it to the checksum of an asset bundle or something.

**Comment by eladb** [comment]
Definitely sounds like a good idea (with the ability to disable), and I think we will need to implement the hash approach (similar to APIGW deployments perhaps, which we might be able to generalize). we cant afford a version name that changes in every synthesis.

**Comment by nija-at** [comment]
still relevant

**Comment by nija-at** [comment]
The new [`currentVersion()`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/function.ts#L334) API can be used to satisfy this.
