### ISSUE TITLE
MathExpression in Cloudwatch graphs are fixed to a 5min period

### ISSUE THREAD

**Issue by alexmv** [aws/aws-cdk#7153]
When serializing the JSON of MathExpression objects, [only the expression is output](https://github.com/aws/aws-cdk/blob/174387db8eb885f634662cbe01e271bafd7db75e/packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts#L57).  If the MathExpression has a period other than 5min (due to being derived, say, from 1m metrics), it gets (incorrectly) rendered with 5min intervals -- because the default period at the graph level is 5min, and the serialized MathExpression doesn't specify one.

### Reproduction Steps

```python
from aws_cdk import aws_cloudwatch, aws_elasticloadbalancingv2, core


class Example(core.Construct):
    def __init__(
        self,
        scope: core.Construct,
        id: str,
        target_group: aws_elasticloadbalancingv2.ApplicationTargetGroup,
    ) -> None:
        super().__init__(scope, id)

        metric = aws_cloudwatch.MathExpression(
            expression=f"FILL(something,0)",
            using_metrics={
                "something": target_group.metric_healthy_host_count(
                    statistic="average", period=core.Duration.minutes(1),
                )
            },
            period=core.Duration.minutes(1),
        )

        dashboard = aws_cloudwatch.Dashboard(self, "dashboard")
        dashboard.add_widgets(aws_cloudwatch.GraphWidget(left=[metric], width=24))
```

![Screen Shot 2020-04-02 at 6 17 59 PM](https://user-images.githubusercontent.com/28347/78314302-70c25f80-750e-11ea-8a43-9ed5643763c7.png)
(Note 5-min intervals on the datapoints)

### Error Log

N/A

### Environment

  - **CLI Version:** 1.17.13
  - **Framework Version:** 1.31.0
  - **OS:** OS X 10.14.6
  - **Language:** Python 3.8.0

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Works as intended. Specify the intended duration on the `MathExpression`, not on its compound metrics.

**Comment by alexmv** [comment]
The fifth line from the end specifies the desired period, as part of the `MathExpression`.  Can you be more specific where else the period should be supplied?

**Comment by alexmv** [comment]
> Works as intended. Specify the intended duration on the MathExpression, not on its compound metrics.

I believe that's what the code I showed does:
```
        metric = aws_cloudwatch.MathExpression(
            # ...
            period=core.Duration.minutes(1),
        )
```

If you meant something else, please clarify.

**Comment by alexmv** [comment]
@rix0rrr: Am I misunderstanding your comment, or was this issue closed in error?

**Comment by zhy2002** [comment]
This problem still exists as of CDK 1.85.0

**Comment by bentonkribbs** [comment]
Looks like this issue has been fixed: https://github.com/aws/aws-cdk/pull/13078
