### ISSUE TITLE
StepFunctions service has potential superuser permissions

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#7158]
StepFunctions state machine requires broad permissions to Cloudwatch logs in order to enable logging - https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html#cloudwatch-iam-policy.

This has been encoded into the CDK as well - https://github.com/aws/aws-cdk/blob/435b66f2c4421193590e3fdf2e13d87445e25044/packages/%40aws-cdk/aws-stepfunctions/lib/state-machine.ts#L201-L215

Two potential problems here -

1. It's not clear what the 'LogDelivery' actions are. This has not been documented anywhere, so it's unclear what kind of access and operations the StepFunctions service has on the user account.

2. Allowing `PutResourcePolicy` actions is a potential super user action. With permission to this action, the StepFunctions backend service could not only gain access but also provide access to other actors on sensitive log groups.

**Comment by nija-at** [comment]
Internal ref: t.corp/D15642652

**Comment by shivlaks** [comment]
resolving this issue as we have gotten a response from the Step Functions team indicating that further action is not required on the CDK side of things at this time.

They have confirmed that the currently policy levels are as minimally scoped as possible.
Further tightening of resource policies is also being investigated (internal ref: D15642652)

Currently, the permissions that are provided on enabling log delivery are the same set of permissions that are displayed in the Step Functions console when they create IAM roles on behalf of customers.

A table will also be shown with links to the docs and descriptions of what kinds of policies are being added to the new role.
