### ISSUE TITLE
missing IAM permissions when creating EKS cluster resource

### ISSUE THREAD

**Issue by jameszh** [aws/aws-cdk#7163]
If you have created tags using core.Tag.add, and then do eks_cluster.add_fargate_profile(...), the creation of fargate profile will fail, as it will complain it doesn't have eks:TagResource (eks:UntagResource).

But if you remove the core.Tag.add statements, eks_cluster.add_fargate_profile will succeed.

### Reproduction Steps

Add some tags using core.Tag.add, and try to add_fargate_profile.

I think eks:TagResource and eks:UntagResource need to be added in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster-resource.ts

### Environment

  - **CLI Version      : 1.31.0
  - **Framework Version: 1.31.0
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Thanks for the bug report. Should be fairly easy to fix if you are interested in contributing.
