### ISSUE TITLE
Specify Subnet IDs when creating VPC Endpoints 

### ISSUE THREAD

**Issue by ywauto83** [aws/aws-cdk#7174]
when using vpc.addInterfaceEndpoint to create VPC endpoints for a service, only subnet type or subnetgroupname is supported. There is no prop or method to specify subnetIDs at L2 construct level.

### Use Case

Have to enable VPC endpoint ENIs in allowed subnets according to our Cyber security policies. 

### Proposed Solution

We should be able to mention the subnet ids explicitly when using  vpc.addInterfaceEndpoint

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I believe specifying individual subnets was added here: https://github.com/aws/aws-cdk/pull/4622

Does this not suffice?

Closing under the assumption that this was already added, please reopen if closed in error.
