### ISSUE TITLE
Step Functions - Support JSONPath in Pass State Parameters

### ISSUE THREAD

**Issue by c-py** [aws/aws-cdk#7181]
The Pass state parameters (and maybe result?) support JSONPath:

https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-pass-state.html

At the moment CDK does not.

### Reproduction Steps

`./lib/repo-stack.ts`
```typescript
import * as cdk from '@aws-cdk/core';
import { StateMachine, Pass, Data } from '@aws-cdk/aws-stepfunctions';


export class ReproStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const firstPass = new Pass(this, "FirstPass", {
      parameters: {
        example: "Example"
      }
    })

    const secondPass = new Pass(this, "Pass", {
      parameters: {
        "notworking": Data.stringAt("$.example"),
        "working.$": Data.stringAt("$.example"),
      }
    })

    new StateMachine(this, "StateMachine", {
      definition: firstPass.next(secondPass)
    })
  }
}
```

`./bin/repro.ts`
```typescipt
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { ReproStack } from '../lib/repro-stack';

const app = new cdk.App();
new ReproStack(app, 'ReproStack');
```

### Error Log

`secondPass` from the reproduction steps has input: 

```json
{
  "example": "Example"
}
```

and output:

```json
{
  "notworking": "$.example",
  "working": "Example"
}
```

### Environment

  - **CLI Version      :**
  - **Framework Version:** 1.31.0
  - **OS               :** MacOSX
  - **Language         :** Typescipt

### Other

I believe this is because Task calls `FieldUtils.renderObject`

https://github.com/aws/aws-cdk/blob/4e91cb47b9fd9d6dc74872531256bc40966ed1c6/packages/%40aws-cdk/aws-stepfunctions/lib/states/task.ts#L161

And Pass does not:

https://github.com/aws/aws-cdk/blob/4e91cb47b9fd9d6dc74872531256bc40966ed1c6/packages/%40aws-cdk/aws-stepfunctions/lib/states/pass.ts#L143

I would like to develop a fix for this. This issue is Step 1 of the contributing guidelines.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Indeed, this seems like a miss in the `Pass` state.

Thanks for filing this issue.
