### ISSUE TITLE
STDERR used as main output but why?

### ISSUE THREAD

**Issue by A-KL** [aws/aws-cdk#7193]
Hi, 
I'm working on a migration from SAM to CDK and it ran into an issue where CDK. Its output sometimes looks like a list of errors in AzureDevOps or locally (using .NET Core based process-runner), even if the process was successfully executed.

After investigation, I found these lines:
https://github.com/aws/aws-cdk/blob/d7c40c5e6209de320d2b89f27e8684bebce35cf0/packages/aws-cdk/lib/logging.ts#L24

```
export const error = logger(stderr, [colors.red]);
export const warning = logger(stderr, [colors.yellow]);
export const success = logger(stderr, [colors.green]);
export const highlight = logger(stderr, [colors.bold]);
export const print = logger(stderr);
```

It looks like writing to `stderr` was intentional, but why?? Without any prefixes, like in case with npm: `[npmWARN]..`. 

`cdk --version` writes to `stdout`
`cdk diff --profile xxx` writes to `stderr` and causes CI system to fail with a long list of errors and without any possibility to filter messages that are just info or warn level.

**Comment by shivlaks** [comment]
duplicated by #7717 - let's track this one there.
