### ISSUE TITLE
Support Fine-grained Access Elasticsearch Feature in CDK

### ISSUE THREAD

**Issue by awssenera** [aws/aws-cdk#7197]
Fine grained access is not supported neither in Cloudformation nor in CDK: 
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/384
It is an important feature which will increase the use cases of Amazon Elasticsearch Service.

This is a :rocket: Feature Request

**Comment by awssenera** [comment]
@iliapolo  Is it possible to add this attribute soon?

**Comment by iliapolo** [comment]
Hi @awssenera 

Until CloudFormation adds support for the requested attributes, there's nothing the CDK can really do. 

I encourage you to reach out to CloudFormation on the roadmap issue you referenced.

**Comment by iliapolo** [comment]
This has been shipped in the [PR](https://github.com/aws/aws-cdk/issues/8369) that introduced the L2 constructs.

Closing, let us know if you feel something is missing.
