### ISSUE TITLE
Option to disable A record creation in ECS patterns for private LBs

### ISSUE THREAD

**Issue by hencrice** [aws/aws-cdk#7206]
Give customers an option to disable A record creation in ECS pattern when the load balancers are private.

### Use Case

Some customers may not want an A record to be created when their ECS/Fargate services are behind private load balancer.

### Proposed Solution

Our initial attempt was: #6895, which straight out disabled A record creation whenever the load balancer is private. However, turned out that multiple customers actually rely on such a behavior:
* https://github.com/aws/aws-cdk/issues/6992
* https://github.com/aws/aws-cdk/issues/7148

To satisfy both groups of customers, we can potentially add a new boolean flag to all the following interfaces:
* https://github.com/aws/aws-cdk/blob/d7c40c5e6209de320d2b89f27e8684bebce35cf0/packages/%40aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts#L41
* https://github.com/aws/aws-cdk/blob/d7c40c5e6209de320d2b89f27e8684bebce35cf0/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L43
* https://github.com/aws/aws-cdk/blob/d7c40c5e6209de320d2b89f27e8684bebce35cf0/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts#L266
* https://github.com/aws/aws-cdk/blob/d7c40c5e6209de320d2b89f27e8684bebce35cf0/packages/%40aws-cdk/aws-ecs-patterns/lib/base/network-multiple-target-groups-service-base.ts#L203

The flag can be named as `createARecord` with default value `true` to be backward-compatible.

### Other
Customer ask: #6702
Initial incorrect attempt: #6895

Please +1 if you would like to see this feature implemented!

This is a :rocket: Feature Request

**Comment by konstantinj** [comment]
I think this is not a good idea. If you don't want the behaviour ECS patterns is producing simply you the bare ECS classes instead. There are more behaviours that could be controlled in ECS patterns - it's nonsense to make all of them configurable. For most customers the ECS patterns are just fine as they are.
