### ISSUE TITLE
Why is Cfn class for AWS::ApiGatewayV2::ApiGatewayManagedOverrides not auto generated?

### ISSUE THREAD

**Issue by SachinShekhar** [aws/aws-cdk#7208]
Currently, [aws-apigatewayv2](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html) module has no custom constructs. So, we're dependent on auto-generated `Cfn` classes. But, all CloudFormation resources are not available.

Why is [AWS::ApiGatewayV2::ApiGatewayManagedOverrides](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-apigatewaymanagedoverrides.html) not auto generated?

Please, fix it or add it. I don't know whether it is a :bug:bug or a :rocket:feature request.

**Comment by nija-at** [comment]
We have a maximum of 2 week delay between when CloudFormation modifies its spec to when it is available in CDK. This is likely the case for this resource type as well.

Let me know if you think this has been around for a lot longer, otherwise this will be available to you in the next couple of weeks.

Thanks.

**Comment by SachinShekhar** [comment]
@nija-at `AWS::ApiGatewayV2::ApiGatewayManagedOverrides` was added on March 12th which is more than 2 weeks ago. Search `ApiGatewayManagedOverrides` here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-cloudformation-release-notes.rss

**Comment by rix0rrr** [comment]
It's not in the CloudFormation specification yet, so the CDK doesn't know about it:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html
https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

it will appear in the CDK after appearing in the CloudFormation Resource Specification.

**Comment by rix0rrr** [comment]
Cut a ticket to CloudFormation: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/438

**Comment by jonasgroendahl** [comment]
Also looking for the Cfn for apigatewayv2/VpcLink  👍

**Comment by nija-at** [comment]
Closing this issue. We autogenerate the Cfn classes out of the latest CloudFormation spec. 
Once they are available, the next release of the CDK will contain them. 

Closing this issue. Please continue to track this with the linked CloudFormation issue.
