### ISSUE TITLE
Cannot create namespaces when trying to add helm chart to an EKS cluster

### ISSUE THREAD

**Issue by FarshadNiayesh** [aws/aws-cdk#7209]
When I try to add a helm chart to a cluster, there seems to be a problem with creating a new namespace. I get this error when trying to add helm to a kubernetes cluster in python with both the construct eks.HelmChart() and cluster method like cluster.add_chart()

### Reproduction Steps
`eks_cluster.add_chart(id="nginx-ingress-0406", chart="nginx-ingress", namespace="nginx", repository="https://kubernetes-charts.storage.googleapis.com", wait=True)`

`eks_cluster.add_chart(id="airflow-0406", chart="airflow", namespace="default", repository="https://kubernetes-charts.storage.googleapis.com", wait=True)`

or 

`chart = eks.HelmChart(self,
                              f"{chart_name}-{self.ENVIRONMENT}",
                              cluster=cluster,
                              chart=chart_name,
                              namespace=ns,
                              release=f'helm-chart-{release}-{self.ENVIRONMENT}',
                              repository=repo,
                              values=vals)`

### Error Log

`Failed to create resource. Error: b'Release "nonprodrptclusternonprodchartnginxingress0406e3cf6676" does not exist. Installing it now.\nError: create: failed to create: namespaces "nginx" not found\n' at invokeUserFunction (/var/task/framework.js:85:19) at process._tickCallback (internal/process/next_tick.js:68:7)`

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

![image](https://user-images.githubusercontent.com/39071023/78608947-5f879480-7827-11ea-92cd-da1e7df174d1.png)

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Duplicate #7216
