### ISSUE TITLE
[EKS] Upgrade to kubectl 1.15 & AWS CLI 1.18.70

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#7216]
bump `helm3` and  `kubectl` versions from the latest release of **aws-samples/aws-lambda-layer-kubectl** [2.0.0-beta3](https://github.com/aws-samples/aws-lambda-layer-kubectl/releases/tag/2.0.0-beta3)

### Use Case

1. we need the support to create new namespace with `addChart()` in aws-eks.
https://github.com/aws/aws-cdk/issues/3748#issuecomment-610053250

2. Amazon EKS 1.15 has been released for a while. Let's bump the kubectl version to 1.15.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by FarshadNiayesh** [comment]
Any update on this?

**Comment by pahud** [comment]
@FarshadNiayesh 

`--create-namespace` will be shipped in Helm v3.2.0 https://github.com/helm/helm/pull/7648#issuecomment-610393425

Will continue this when v3.2.0 is released.

**Comment by FarshadNiayesh** [comment]
@pahud seems like Helm v3.2.0 is released. Should we expect this feature any time soon in CDK?

**Comment by pahud** [comment]
@FarshadNiayesh Absolutely. I'll try it in my environment tomorrow and see how it works. Thanks.

**Comment by jonathanmccracken** [comment]
This would help me also

**Comment by arjanschaaf** [comment]
Any update on this @pahud ? This would make the combination CDK + EKS + Helm so much easier to work with :-)

**Comment by pahud** [comment]
I'll look into this again and get back to this thread tomorrow. Thanks for the headsup.

**Comment by eladb** [comment]
Would be nice to include this as part of #6279

**Comment by eladb** [comment]
@pahud can we also include the latest CLI in this upgrade so it will address https://github.com/aws/aws-cdk/issues/6279#issuecomment-648619829

**Comment by pahud** [comment]
Yap. Just bumpped **aws-lambda-layer-kubectl** to [release 2.0.0](https://github.com/aws-samples/aws-lambda-layer-kubectl/releases/tag/2.0.0) with the latest kubectl, awscli and helm3.

Layer is also available in SAR and might take 24-48hours to replicate to all global regions.

I will test the latest layer in the next 1-2 days and create a PR for aws-eks cdk construct.

kubectl | v1.16.8-eks-e16311
-- | --
awscli | 1.18.86
helm | 3.2.4
jq | 1.6
GNU Make | 3.82

**Comment by eladb** [comment]
🤝

**Comment by eladb** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/8739
