### ISSUE TITLE
Typescript: Unexpected Cloudformation output when using Vpc.fromAttributes with Fn.importValue in a lambda Function construct

### ISSUE THREAD

**Issue by soporific419** [aws/aws-cdk#7217]
I am using an imported Vpc from another CDK application for a lambda Function construct.

When I import a Vpc using the Vpc.fromAttributes static function and a list of subnet IDs, I get two different CloudFormation outputs, depending on how I generate the string[] subnet IDs.

Case 1: Fn.importValue.split(",") creates a CloudFormation output: 
[ "Fn::importValue": "..." ]

Case 2: Fn.split(",", Fn.importValue) creates a CloudFormation output:
"Fn::Split": [",", { "Fn::ImportValue": "..." } ]

In Case 1, the lambda Function causes an error when deploying the stack:

Error occurred while DescribeSubnets. EC2 Error Code: InvalidSubnetID.NotFound. EC2 Error Message: The subnet ID 'subnet-...,...' does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ...).

In case 2, the lambda Function constructor succeeds when deploying the stack.

### Reproduction Steps

other CDK app:
```
import { Vpc } from "@aws-cdk/aws-ec2";
import { CfnOutput } from '@aws-cdk/core';
const vpc = new Vpc(...);
new CfnOutput(..., {
  value: vpc.publicSubnets.map(subnet => subnet.subnetId).join(","),
  exportName: "public-subnet-ids"
});
new CfnOutput(..., {
  value: vpc.privateSubnets.map(subnet => subnet.subnetId).join(","),
  exportName: "private-subnet-ids"
});
new CfnOutput(..., {
  value: vpc.availabilityZones.join(","),
  exportName: "availability-zones"
});
new CfnOutput(..., {
  value: vpc.vpcId,
  exportName: "vpc-id"
});
```
Another CDK app (Case 1):
```
const vpc = Vpc.fromVpcAttributes(..., {
            vpcId: Fn.importValue("vpc-id"),
            availabilityZones: Fn.importValue("availability-zones").split(","),
            publicSubnetIds: Fn.importValue("public-subnet-ids").split(","),
            privateSubnetIds: Fn.importValue("private-subnet-ids").split(","),
        });
new Function(..., {
  ...,
  vpc: vpc
});
```
generates the following cdk.out entry in the Function handler:
```
...
       "VpcConfig": {
          "SecurityGroupIds": [
            {
              "Fn::GetAtt": [
                "...",
                "GroupId"
              ]
            }
          ],
          "SubnetIds": {
            [
              {
                "Fn::ImportValue": "private-subnet-ids"
              }
            ]
          }
        }
...
```
Another CDK app (Case 2):
```
const vpc = Vpc.fromVpcAttributes(..., {
            vpcId: Fn.importValue("vpc-id"),
            availabilityZones: Fn.split(',', Fn.importValue("availability-zones")),
            publicSubnetIds: Fn.split(',', Fn.importValue("public-subnet-ids")),
            privateSubnetIds: Fn.split(',', Fn.importValue("private-subnet-ids")),
        });
new Function(..., {
  ...,
  vpc: vpc
});
```
generates the following cdk.out entry in the Function handler:
```
...
       "VpcConfig": {
          "SecurityGroupIds": [
            {
              "Fn::GetAtt": [
                "...",
                "GroupId"
              ]
            }
          ],
          "SubnetIds": {
            "Fn::Split": [
              ",",
              {
                "Fn::ImportValue": "private-subnet-ids"
              }
            ]
          }
        }
...
```

### Error Log

Error occurred while DescribeSubnets. EC2 Error Code: InvalidSubnetID.NotFound. EC2 Error Message: The subnet ID 'subnet-...,...' does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ...)

### Environment

  - **CLI Version      : 1.30.0 (build 4f54ff7)**
  - **Framework Version: 1.23.0**
  - **OS               : Mac OSX, AL2012, AL2**
  - **Language         : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I'm not quite sure I follow. Can I summarize your bug report as the following?

* When I do `Fn.importValue(...).split(',')` it doesn't work.
* When I do `Fn.split(',', Fn.importValue(...))` it does.

If so, I feel that restriction has been described here: https://docs.aws.amazon.com/cdk/latest/guide/tokens.html#tokens_string

Do you not agree?
