### ISSUE TITLE
s3 asset object s3 url

### ISSUE THREAD

**Issue by machielg** [aws/aws-cdk#7221]
add a method or property to get the 's3://bucket/key' style url from the Asset in aws-s3-assets

### Use Case

In many places s3 assets are used in other constructs. In many projects I see:
people doing something like: `s3://${myAsset.s3BucketName}/${myAsset.s3ObjectKey}`

you could easily make small mistakes doing this, while it's such a common need.

### Proposed Solution

add a property to Asset s3ObjectUrl which holds `s3://${myAsset.s3BucketName}/${myAsset.s3ObjectKey}`

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Sounds like a nice addition. We already have [`s3Url`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.Asset.html#s3url-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span) which is the `https://` url of the file, so `s3ObjectUrl` might be a confusing name. I am okay with deprecating `s3Url` in favor of `httpUrl` and then using `s3ObjectUrl` for this if anyone is interested in contributing.

**Comment by ryaeng** [comment]
@eladb I'm interested in contributing. Would this only involve updating the code within the aws-s3 and aws-s3-asset modules? 

Perusing the code last night and found a few references to s3Url outside of these modules. Should we change these as well?

**Comment by eladb** [comment]
> Perusing the code last night and found a few references to s3Url outside of these modules. Should we change these as well?

Yes, the best way to do this is to comment out the deprecated property and run `./scripts/foreach.sh yarn run build` from the root of the repo to build the entire project (see contribution guide for details on how to use "foreach").

**Comment by ryaeng** [comment]
> Yes, the best way to do this is to comment out the deprecated property

What's the purpose of commenting out the deprecated property as opposed to just removing it?

**Comment by eladb** [comment]
> What's the purpose of commenting out the deprecated property as opposed to just removing it?

I meant comment it temporarily and use the compiler to identify all the usages. Then uncomment.

**Comment by ryaeng** [comment]
Got it

**Comment by ryaeng** [comment]
@eladb I have updated the code and the integration test for the asset. I was first met with the response that I had to bootstrap the environment which I looked over because the hostname included unknown. After I ran the command and bootstrapped the environment the integration test succeeded.

Is this sufficient test coverage or will more testing be required?

**Comment by eladb** [comment]
Submit a PR and I’ll be able to review

**Comment by ryaeng** [comment]
Yes sir

**Comment by ryaeng** [comment]
@eladb Submitted the pull request. It would appear that the build didn't like my changes to core. Any advice on how I should proceed?

**Comment by ryaeng** [comment]
@eladb I changed the checkouted the core files from a previous commit to see if that would take care of it. Then realized that the change broke the commit that I had originally made. Please advise.

**Comment by machielg** [comment]
Looks like #7507 duplicated and fixed this issue.

**Comment by christophgysin** [comment]
@machielg #7507 was about S3 buckets, this is about S3 assets. This issue should be reopened, and closed with #7509
