### ISSUE TITLE
LoadBalancer is in Pending state when deploying nginx ingress to EKS cluster 

### ISSUE THREAD

**Issue by FarshadNiayesh** [aws/aws-cdk#7228]
When deploying nginx-ingress (or any type of LoadBalancer) to the EKS cluster using CDK, the LoadBalancer cannot create the external DNS (URL) and the pod gets stuck in "Pending" state.

Also, when I try to edit the service type from `ClusterIP` to `LoadBalancer` for any services, I get the same "Pending" status for the pod. 

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by FarshadNiayesh** [comment]
@eladb @pahud Can you help me with this?

**Comment by pahud** [comment]
Hi @FarshadNiayesh 

Can you provide detailed steps how you deploy your Amazon EKS cluster with relevant CDK code? We need reproduce it first.

**Comment by FarshadNiayesh** [comment]
Hi @pahud I fixed the issue by deploying the nodegroup in public subnets and assigning ip addresses. That was the problem. Thank you.
