### ISSUE TITLE
Aliases are not automatically set from certificate

### ISSUE THREAD

**Issue by bdadam** [aws/aws-cdk#7240]
When creating a new CloudFront distribution the aliases need to be manually added for every domain listed in `subjectAlternativeNames` (but not for the main domain).

### Reproduction Steps

```ts
const certificate = new certificatemanager.Certificate(this, 'Certificate', {
    domainName: 'example.com',
    subjectAlternativeNames: [
        'www.example.com',
        'example.net',
        'www.example.net',
    ],
    validationMethod: certificatemanager.ValidationMethod.DNS,
});

new cloudfront.CloudFrontWebDistribution(this, 'CFDistribution', {
    viewerCertificate: cloudfront.ViewerCertificate.fromAcmCertificate(certificate),
    // ...
}
```
In the code above I would expect that the viewerCertificate.aliases is automatically populated with all the domains from the certificate.

The code below fixes the issue but it was unexpected to me that I have to list the aliases again although they are already in the certificate.

```ts
new cloudfront.CloudFrontWebDistribution(this, 'CFDistribution', {
    viewerCertificate: cloudfront.ViewerCertificate.fromAcmCertificate(certificate, {
        aliases: [
            'example.com',
            'www.example.com',
            'example.net',
            'www.example.net',
        ]
    }),
    // ...
}
```

This is maybe :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @bdadam

I agree there is some redundancy here. Repurposing this as a feature request.

Thanks! 👍
