### ISSUE TITLE
The volume property of BlockDevice should be optional

### ISSUE THREAD

**Issue by rbobrowicz** [aws/aws-cdk#7242]
The `volume` property on the `BlockDevice` interface ( https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.BlockDevice.html ) should be optional.

### Use Case

I'm trying to prevent a block device specified in an AMI from being attached by the ASG. Using the AWS CLI this would be accomplished with following mapping:

```
{
    "DeviceName": "/dev/sdf",
    "NoDevice": ""
}
```

As specified on https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html#Using_OverridingAMIBDM .

It would appear that is what the `mappingEnabled` property is for, but using it is impossible in CDK because the `volume` property of the mapping is not optional. Project won't compile without it, but specifying anything as the volume will lead to a deploy time error. For example code like this:

```
{
    deviceName: "/dev/sdf",
    volume: auto.BlockDeviceVolume.ephemeral(0),
    mappingEnabled: false,
}
```

Produces this mapping:

```
{
    "DeviceName": "/dev/sdf",
    "NoDevice": true,
    "VirtualName": "ephemeral0"
}
```

But when you deploy you get the following error: `Cannot specify both ephemeral volume and no-device for block devices. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError;`

You get similar errors if you try to specify an `ebs` volume or `ebsFromSnapshot`.

### Proposed Solution

Make `volume` optional, assert it is `undefined` if `mappingEnabled` is `false` and not `undefined` if `true`.

### Other

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
A possible better API for expressing `NoDevice` is to have a `BlockDeviceVolume` of type `None`, something like:

```javascript
autoscaling.BlockDeviceVolume.None()
```

However since the current API includes `mappingEnabled` property, adding the `None` type will result in a confusing API.

To fix the `mappingEnabled` behavior we can change the underlying implementation to ignore the `volume` property when `mappingEnabled` is set to `false`. I'm not in favor of making the `volume` property optional as in most use cases it is required and I don't want to sacrifice the common use case, especially when the API already expose the `mappingEnabled`. 

@rix0rrr what do you think?

**Comment by rbobrowicz** [comment]
Keeping `volume` as required would be a little bit weird since it would essentially force you to make up a new fake ephemeral or EBS volume just so you can disable an existing one, but I'm okay with that if the `mappingEnabled` property actually works. I can adjust my patch as needed, just let me know what you want the final API to be.

**Comment by NetaNir** [comment]
We usually try to avoid "conditional required" and prefer using explicit APIs. 
I agree with your point that creating a fake volume is not so great. What we can do is deprecate `mappingEnabled ` and introduce a new volume type:

```typescript 
autoscaling.BlockDeviceVolume.NoDevice()
```
That will emit no device configuration. Either way we will need to fix `mappingEnabled` as removing it will be a breaking change. 

@rbobrowicz how does that sound?

**Comment by rbobrowicz** [comment]
Just to make sure I'm understanding it correctly:

If a user specifies an EBS/Ephemeral volume, then we should look at `mappingEnabled` and act accordingly.

If the user specifies the new `NoDevice` volume type, then ignore `mappingEnabled` and generate the suppressed volume info.

If that's correct, then that sounds good to me, I can probably update my patch in the next next few days.

**Comment by NetaNir** [comment]
> If a user specifies an EBS/Ephemeral volume, then we should look at mappingEnabled and act accordingly.

Yes, as this is a part of the API we should make sure this work as expected, and add `@deprecated` to the property.

> If the user specifies the new NoDevice volume type, then ignore mappingEnabled and generate the suppressed volume info.

Yes (assuming you mean emitting `NoDevice`)

**Comment by rbobrowicz** [comment]
Okay, my PR is updated.
