### ISSUE TITLE
Replacing a ApplicationLoadBalancedFargateService with a DnsValidatedCertificate causes an error: record set already exists

### ISSUE THREAD

**Issue by mjsilva** [aws/aws-cdk#7244]
When replacing a running ApplicationLoadBalancedFargateService that has a DnsValidatedCertificate certificate and cloudformation update fails with the error:
> [Tried to create resource record set [name='api.example.com.', type='A'] but it already exists]

### Reproduction Steps

```
    const publicHostedZone = HostedZone.fromLookup(this.scope, `${configuration().appName}-hosted-zone-public`, {
      domainName: this.environmentHostedZoneName,
      privateZone: false,
    })

    const certificate = new DnsValidatedCertificate(this.scope, `${configuration().appName}-ssl-certificate`, {
      domainName: this.environmentHostedZoneName,
      hostedZone: publicHostedZone,
    })

    this.apiWebServiceAndLoadBalancer = new ApplicationLoadBalancedFargateService(this.scope, `${configuration().appName}-api-service`, {
      cluster: this.cluster,
      certificate: certificate,
      cpu: 256,
      memoryLimitMiB: 512,
      taskImageOptions: {
        image: ContainerImage.fromEcrRepository(this.repository, configuration().infrastructure.dockerImageTag),
        containerPort: 3000,
        environment: this.getEnvironmentVariablesMagically(),
      },
      publicLoadBalancer: true,
      assignPublicIp: true,
      protocol: ApplicationProtocol.HTTPS,
      domainName: `api.${this.environmentHostedZoneName}`,
      domainZone: publicHostedZone,
    })
```

### Error Log

> [Tried to create resource record set [name='api.example.com.', type='A'] but it already exists]

### Environment

  - **CLI Version      :** 1.32.0
  - **Framework Version:** ?
  - **OS               :** Mac/Linux
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @mjsilva, I'm so sorry for the late reply, are you still experiencing this issue?

**Comment by jakep36** [comment]
I'm seeing this same error. The dns record set does exist. I would expect the construct to update it if it does exist. Do I need to delete the DNS record prior to deploying this construct? (cdk version: 1.129)
