### ISSUE TITLE
IAM Actions should be sorted 

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#7251]
AWS IAM Actions should be sorted, preferably default is to always sort.

### Use Case

Security reviews of the IAM Actions would be easier and more efficient if the IAM Actions were sorted, rather searching and finding IAM Actions jumbled.

When specifying the IAM Actions in 'iam.PolicyStatement', the cdk synth outputs the IAM Actions in the order defined, rather than alphabetical order.

### Proposed Solution

Use the native data structure sort, as the CDK languages support sort methods.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
This is a good idea. Needs to go behind a feature/future flag though to not mess too many people up.
