### ISSUE TITLE
How to deploy multiple subdomains under one API domain?

### ISSUE THREAD

**Issue by Syy0n** [aws/aws-cdk#7257]
Hey guys,

I have a question regarding the deployment of multiple services (defined in isolated CDK-Stacks) under one API-Gateway REST-API (also defined in an isolated CDK-Stack).
For that I created a general issue because I didn't know if it's a lack of documentation or support.

Instead of giving a bad example, I linked a resource that is exactly describing what I want to achieve with the AWS-CDK (but there they used the Serverless-Framework).

https://serverless.com/blog/api-gateway-multiple-services/

Any help is appreciated, thanks!

**Comment by nija-at** [comment]
Hello @Syy0n - 

Sorry this has not had a response in a while. Are you still looking for guidance on this issue, or were you able to find your way out?
