### ISSUE TITLE
${Token[TOKEN.18]} ... where to find the values of those tokens with Python during execution?

### ISSUE THREAD

**Issue by joyofdata** [aws/aws-cdk#7258]
Hello!

When I print the name of a newly created bucket in a stack:

`print(bucket.bucket_name)`

I see something like this:

`${Token[TOKEN.18]}`

Is it possible to access the values for those Tokens with Python during synthesizing/deploying?

And more specifically - if I create a Bucket `bucket = s3.Bucket(...)` without specifying its name - what would be the easiest way to find out about the generic name or the ARN?

Thanks

Raffael

**Comment by andrestone** [comment]
As per what I could grasp, you want to see some outputs from your created stacks.

You can accomplish that by creating CloudFormation outputs.

Details [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnOutput.html).

**Comment by blimmer** [comment]
I asked a [similiar question](https://github.com/aws/aws-cdk/issues/7079). @NetaNir's [response](https://github.com/aws/aws-cdk/issues/7079#issuecomment-606394303) might be of help.

**Comment by iliapolo** [comment]
Closing this as it seems sufficient answers were provided. Please feel free to re-open if needed.

**Comment by dileepreddy450** [comment]
how to use the outputs as variables in the code ?
