### ISSUE TITLE
Failure to determine Default AWS Account

### ISSUE THREAD

**Issue by paulbrice** [aws/aws-cdk#7265]
Post upgrade from 1.28, any cdk synth or deploy commands fail with "Unable to determine the default AWS account", this then fails to create the CDK_DEFAULT_ACCOUNT env variable. We are on a corporate network behind a HTTP proxy with no other egress options. This was functional up to version 1.28, any version since has caused the same issue.

### Reproduction Steps

```
cdk init app --language python
pip install -r requirements.txt
AWS_PROFILE=default cdk synth --trace --verbose
```

### Error Log

```
CDK toolkit version: 1.32.0 (build 9766ad6)
Command line arguments: {
  _: [ 'synth' ],
  verbose: true,
  v: true,
  trace: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  '$0': '../node_modules/.bin/cdk'
}
Determining whether we're on an EC2 instance.
Does not look like EC2 instance.
Using proxy server: http://corpproxy.domain:1234
cdk.json: {
  "app": "python3 app.py"
}
cdk.context.json: {
  "@aws-cdk/core:enableStackNameDuplicates": "true",
  "aws-cdk:enableDiffNoFail": "true"
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true
}
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
Resolving default credentials
Unable to determine the default AWS account: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:299:28)
    at TLSSocket.emit (events.js:215:7)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'Client network socket disconnected before secure TLS connection was established',
  code: 'NetworkingError',
  path: null,
  host: 'sts.amazonaws.com',
  port: 443,
  localAddress: undefined,
  region: 'us-east-1',
  hostname: 'sts.amazonaws.com',
  retryable: true,
  time: 2020-04-08T22:34:21.259Z
}
context: {
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws-cdk:enableDiffNoFail': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'us-east-1',
  CDK_CONTEXT_JSON: '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.21.0',
  CDK_CLI_VERSION: '1.32.0'
}
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    account=os.environ["CDK_DEFAULT_ACCOUNT"],
  File "/Users/myuser/.asdf/installs/python/3.7.5/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CDK_DEFAULT_ACCOUNT'
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/Users/myuser/code/gitlab/cdk/node_modules/cdk/node_modules/aws-cdk/lib/api/cxapp/exec.ts:115:23)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

### Environment

  - **CLI Version      :** 1.32
  - **Framework Version:** 1.32
  - **OS               :** macOS 10.14.6
  - **Language         :** Python

### Other

We leverage the CDK_DEFAULT_REGION and CDK_DEFAULT_ACCOUNT env variables in the env parameter on each stack call.
```
env = core.Environment(
    account=os.environ["CDK_DEFAULT_ACCOUNT"],
    region=os.environ["CDK_DEFAULT_REGION"]
    )

app = core.App()
TestAppStack(app, "test-app", env=env)

app.synth()
```

Our corporate HTTP proxy spoofs certificates.

Only relative change based on this issue was here:
https://github.com/aws/aws-cdk/commit/a75f711aea3dac83c6feec885b7df9b14a39486e#diff-c59a64c4aaf11c23a64d46cfdd682054L138

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
@paulbrice we have seen issues with default account credentials resolution when behind proxies before.

It appears your aren't passing the proxy address to the cli with the `--proxy` arg so I assume its configured at the system level? Are the `http_proxy` and/or `https_proxy` env variable configured?

We recently refactored quite a bit of the CLI (the commit you linked) so that may have had some hand in this. We have some coverage for proxies but there may be an edge case we are missing that we affected without intending.

**Comment by rix0rrr** [comment]
Trying to reproduce with `mitmproxy` but works for me:

Setup

```
pip3 install mitmproxy
mitmdump -vvv

export https_proxy=http://localhost:8080/
cdk diff -v
```

Does a successful STS lookup using the proxy.

Can you help us reproduce @paulbrice ?

**Comment by rix0rrr** [comment]
This indicates some network-level error:

```
 Client network socket disconnected before secure TLS connection was established
```

**Comment by rix0rrr** [comment]
What kind of proxy is your corp running?

**Comment by rix0rrr** [comment]
Tested https://www.charlesproxy.com/, also seems to work

**Comment by paulbrice** [comment]
> @paulbrice we have seen issues with default account credentials resolution when behind proxies before.
> 
> It appears your aren't passing the proxy address to the cli with the `--proxy` arg so I assume its configured at the system level? Are the `http_proxy` and/or `https_proxy` env variable configured?
> 
> We recently refactored quite a bit of the CLI (the commit you linked) so that may have had some hand in this. We have some coverage for proxies but there may be an edge case we are missing that we affected without intending.

Yes we have proxy set in both `http_proxy` and `https_proxy` as well as upper case in our environment variables.

**Comment by rix0rrr** [comment]
Well that's unfortunately not enough for us to go on. Do you have more?

```
export http_proxy=http://localhost:8080/
export https_proxy=http://localhost:8080/
export HTTP_PROXY=http://localhost:8080/
export HTTPS_PROXY=http://localhost:8080/
export NODE_TLS_REJECT_UNAUTHORIZED=0

rm -rf ~/.cdk/cache && npx cdk diff -v

Looking up default account ID from STS
(node:50182) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Default account ID: ************
Setting "CDK_DEFAULT_ACCOUNT" environment variable to ************
```

**Comment by rix0rrr** [comment]
Oh, I bet you are using `assume_role` credentials that are driven from the AWS config file, aren't you?

**Comment by paulbrice** [comment]
> Oh, I bet you are using `assume_role` credentials that are driven from the AWS config file, aren't you?

Yes - confirmed!

If i reference an AWS config profile that has secrets in it, using the AWS_PROFILE env var, v1.32 works fine. But if i reference a profile that uses the source_profile parameter for switching roles it fails.

**Comment by rix0rrr** [comment]
Yep that was the missing piece of info. 

Confirmed.
