### ISSUE TITLE
Autoscaling for NetworkLoadBalancedFargateService with CDK?

### ISSUE THREAD

**Issue by joyofdata** [aws/aws-cdk#7271]
Hello!

I have Fargate on a cluster running behind a NLB. I'd like to add autoscaling for it. But I can't find an example for that.

[This][1] is the example I found for an `ApplicationLoadBalancedFargateService`:

```py
fg = aws_ecs_patterns.ApplicationLoadBalancedFargateService(...)

scaling = fg.service.auto_scale_task_count(max_capacity=10)
scaling.scale_on_request_count(
    id="RequestScaling",
    requests_per_target=10000,
    target_group=fg.target_group
)
```

But this won't work because the `target_group` parameter expects an instance of `ApplicationTargetGroup` but for `NetworkLoadBalancedFargateService` the `target_group` field is of type `NetworkTargetGroup`.

Thanks

  [1]: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs.README.html#task-auto-scaling

**Comment by bvtujo** [comment]
Hi there, thanks for reaching out. Do you think you could post a code snippet from your use case so we can better guide you toward the right solution?

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/aws-cdk/issues/6887

**Comment by SoManyHs** [comment]
Closing in favor of previous issue (duplicate)
