### ISSUE TITLE
The new `ecs.Secret.fromSecretsManager(secret, field?)` is not working 

### ISSUE THREAD

**Issue by dirknilius** [aws/aws-cdk#7272]
There was an enhancement recently in CDK 1.32.0 for the `ecs.Secret.fromSecretsManager(secret, field?)` function. See: https://github.com/aws/aws-cdk/pull/6435/files

I actually want to use this but the container could not be started anymore. 

### Reproduction Steps

Make something like this:

```typescript
const cluster = new DatabaseCluster(this, 'Database', {
    engine: DatabaseClusterEngine.AURORA,
    masterUser: {
        username: 'admin'
    },
    instanceProps: {
        instanceType: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.SMALL),
        vpc
    }
});

const loadBalancedFargateService = new ApplicationLoadBalancedFargateService(stack, 'Service', {
  cluster,
  memoryLimitMiB: 1024,
  cpu: 512,
  taskImageOptions: {
    image: ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
    secrets: {
      // Assign a JSON value from the secret to a environment variable
      MYSQL_HOST: Secret.fromSecretsManager(cluster.secret!, 'host'),
      MYSQL_PORT: Secret.fromSecretsManager(cluster.secret!, 'port'),
      MYSQL_USER: Secret.fromSecretsManager(cluster.secret!, 'username'),
      MYSQL_PASSWORD: Secret.fromSecretsManager(cluster.secret!, 'password'),
      MYSQL_DATABASE: Secret.fromSecretsManager(cluster.secret!, 'dbname'),
    }
  },
});
```

### Error Log

The container cannot be startet. The following was logged:

```
Fetching secret data from AWS Secrets Manager in region eu-central-1: secret arn:aws:secretsmanager:eu-central-1:123456789012:secret:DatabaseSecret3B817195-FpDznCMLC1bE-q13DbL:dbname::: ValidationException: Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@! status code: 400, request id: 9be60361-22a6-46be-a084-2370d3b63718;
```
The CloudFormation Template was generated like this:

```json
{
  "Name": "MYSQL_PASSWORD",
  "ValueFrom": {
    "Fn::Join": [
      "",
      [
        {
          "Ref": "DatabaseSecretAttachmentE5D1B020"
        },
        ":password::"
      ]
    ]
  }
}
```

I'm pretty sure that there is a `:SecretString` missing in between. Because it was referenced in another location like this:

```json
"MasterUserPassword": {
  "Fn::Join": [
    "",
    [
      "{{resolve:secretsmanager:",
      {
        "Ref": "DatabaseSecret3B817195"
      },
      ":SecretString:password::}}"
    ]
  ]
}
```

### Environment

  - **CLI Version      :** aws-cli/2.0.7 Python/3.8.2 Darwin/19.4.0 botocore/2.0.0dev11
  - **Framework Version:** 1.32.0
  - **OS               :** OSX 10.15.4
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Unfortunately for tasks that use the Fargate launch type it is only supported to inject the full contents of a secret as an environment variable. Specifying a specific JSON key or version is not supported at this time.

See https://docs.aws.amazon.com/AmazonECS/latest/userguide/specifying-sensitive-data-secrets.html

Validation should be done in the CDK.

**Comment by jogold** [comment]
> @jogold is there any issue tracking this limitation? And is there a possibility to get support for fargate?

It's here https://github.com/aws/containers-roadmap/issues/385
