### ISSUE TITLE
📊Tracking: AWS CloudTrail

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#7278]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

AWS CloudTrail is an AWS service that helps you enable governance, compliance, and operational and risk auditing of your AWS account. Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail. Events include actions taken in the AWS Management Console, AWS Command Line Interface, and AWS SDKs and APIs.

[AWS Docs](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

- [x] CDK construct to create a CloudTrail with an associated S3 bucket for log storage

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudtrail-readme.html) for more implementation details.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by nija-at** [comment]
Graduation list here - https://github.com/aws/aws-cdk/issues/8268
