### ISSUE TITLE
Testing Constructs Which Depend On Other AWS Entites

### ISSUE THREAD

**Issue by dominic-martino** [aws/aws-cdk#7285]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

  
Hi.

I need some guidance on testing a construct I have created. The Construct has a dependency on another AWS resource, a VPC - but in reality it could be anything.  

See below for an example of the test setup
``` typescript

  test("My Test", () => {
    const app = new cdk.App();
    const stack = new cdk.Stack(app, "TestStack");
  
    const vpc = new Vpc(stack, "test-vpc");
  
    const testProps: TargetGroupProps = {
        ...
        vpc: vpc,
        ...
    };
  
    new MyConstruct(stack, "test-stack", testProps);  
  
    expectCDK(stack).to(
      haveResource("AWS::SomeResource::SomeValue", {   
        VpcId: {
          Ref: vpc.id
        }
      })
    );
  });
```

The assertion against the VPC id will fail, the value for the _vpc.id_ will be placeholder in the form of a token. The Cloudformation template which has been synthesized will have a value like 'testvpc8985080E' for the VPC id. How can I resolve the token values during a test in the same way the testing framework does?

**Comment by NGL321** [comment]
Hi @dominic-martino,

Sorry for the delay in response for this question. When designing tests, we typically get the value for a resource from the Cloudformation template generated on success (see our [Workshop on testing](https://cdkworkshop.com/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.html)). However, if you want to resolve this value with tokens you can take a look at the [tokens](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html#tokens_string) section of our developer guide.
Essentially if you explicitly declare the name as a token, you will have the full value available for tests.

Let me know if this helps!

😸 😷
