### ISSUE TITLE
Support new Fargate platform version 1.4.0

### ISSUE THREAD

**Issue by michaeldimoudis** [aws/aws-cdk#7286]
AWS Fargate platform version 1.4.0 is now available https://aws.amazon.com/blogs/containers/aws-fargate-launches-platform-version-1-4/

### Proposed Solution

Add the Fargate platform version 1.4.0 in between Latest and 1.3.0

https://github.com/aws/aws-cdk/blob/8c6fc43fab73d72e2ad03013635ed21e830686fb/packages/%40aws-cdk/aws-ecs/lib/fargate/fargate-service.ts#L160-L170

### Other

[AWS Fargate launches platform version 1.4.0](https://aws.amazon.com/blogs/containers/aws-fargate-launches-platform-version-1-4/)
[AWS Fargate platform versions primer](https://aws.amazon.com/blogs/containers/aws-fargate-platform-versions-primer/)

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by idm-ryou** [comment]
https://github.com/aws/aws-cdk/pull/7267

**Comment by robertd** [comment]
Closed by #7267
