### ISSUE TITLE
IotEvents action is missing from Iot CfnTopicRule ActionProperty

### ISSUE THREAD

**Issue by nassahmed** [aws/aws-cdk#7288]
When creating an Iot CfnTopicRule, IotEvents is missing as an action property.
This action is declared in cloudformation documentation  ( [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-action.html](link) ) and in cdk documentation [https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iot.CfnTopicRule.html](link) .

### Reproduction Steps
Create an iot CfnTopicRule with an IotEvent as an action.

### Error Log

Type '{ iotEvents: {}; }' is not assignable to type 'IResolvable | ActionProperty'.
  Object literal may only specify known properties, and 'iotEvents' does not exist in type 'IResolvable | ActionProperty'.

### Environment

  - **CLI Version      :**
  - **Framework Version: 1.32.0**
  - **OS               : WSL (Ubuntu)**
  - **Language         : Typescript**

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@nassahmed can you share some code? - the `iotEvents`  action is modeled as an [action property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iot.CfnTopicRule.ActionProperty.html)

**Comment by nassahmed** [comment]
`    const nctLiveRule = new iot.CfnTopicRule(this, "nctLiveRule", {
      topicRulePayload: {
        actions: [
          {
            kinesis: {
              streamName:
                props.nctLivePositionStream.name || "nctLivePositionStream",
              roleArn: nctLiveRuleRole.roleArn,
              partitionKey: "${newuuid()}",
            },
          },
{
  iotEvents:{
    // Here is the bug
  }
}
        ],
        sql: "SELECT * FROM '$aws/rules/nct'",
        ruleDisabled: false,
      },
      ruleName: "nct",
    });`

**Comment by shivlaks** [comment]
@nassahmed  are you certain you're got `1.32.0` in your `package.json`?
It was added recently in [#7113](https://github.com/aws/aws-cdk/pull/7113)

**Comment by nassahmed** [comment]
After deleting the node_modules and runing an npm update it seems the issue was solved. I looked at the changelog but didnt notice Cloudformation line.
Sorry for this.

**Comment by shivlaks** [comment]
no worries! glad it works 👍
