### ISSUE TITLE
Authorizer(API GW) created from CDK does not work intermittently

### ISSUE THREAD

**Issue by bpcrao** [aws/aws-cdk#7289]
- we have a REST API created from APIGateway
- the Gateway invoking a Lambda
- the API is guarded by Authorizer (Lambda which generates policy) 
- having the right invocation role 

### Reproduction Steps

let gatewayAPI = new apigw.RestApi(this, "gatewayName", {
      restApiName: "APIName",
      deployOptions: {
        stageName: props.modulesStage
      }
    });

    const authorizer= new apigw.RequestAuthorizer(this, 'Authorizer', {
      handler: customAuthorizer.jwtValidatorConstruct.handler,
      identitySources: [IdentitySource.header('authorization')]
    });

      const pathResource = resource.addResource(pathPart);
        pathResource.addMethod(httpMethod, lambdaIntegration, {
            authorizer: authorizer
        });

### Error Log

- No errors in CDK deployment
- the deployed API randomly fails and does not. send the request to Authorizer 
- when we edit the authorizer manually without any changes and save it 
- it works consistently 

### Environment
 CDK Version: 1.31.0 (build 8f3ac79)
ℹ️ AWS environment variables:
  - AWS_SDK_LOAD_CONFIG = 1
ℹ️ CDK environment variables:
  - CDK_DEFAULT_ACCOUNT =XXXXXXXXX
  - CDK_DEFAULT_REGION = us-east-1
  - **Framework Version:**
  - **OS               :MAC and Ubuntu
  - **Language         :Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Based on your description of the error so far, it doesn't seem like these are related to the CDK or CloudFormation. Perhaps it has got something to do with the lambda function itself? To diagnose this better -

can you provide details on the errors, such as when does this error occur and what is the error message?

what are the manual steps that you perform that seems to make these errors go away?

**Comment by bpcrao** [comment]
@nija-at 

1. we created a new Authorizer exactly same settings associate with resource and redeploy and thing work perfectly
2. the other option is to edit Authorizer without any changes just do a save and redeploy the resource that's it things work smoothly

in the Resource deployments, I see 2 deployments one with CDK and the next one which is done manually 

and only the second deployment works 


I see 2 things either the Authorizer save or the redeployment which fixed the issue( the Lambda is fine perfectly since we are using it for over a yr without code change)

**Comment by nija-at** [comment]
Hi @bpcrao -

Unfortunately, this information is not sufficient to isolate if this is an issue with the CDK or not.

We need more information around what property of the Authorizer was different between when you had the issue vs. when it got resolved.

> regarding the errors : there are no errors

You may have to contact the APIGateway team (via AWS support). If there are no deployment errors or errors logged during the execution of your API Gateway, this is unlikely to be an issue with the CDK.

The CDK, in conjunction with CloudFormation, is responsible for correctly deploying AWS resources. If the resources and all of its properties are set according to what is expected, and yet the set up does not work for you, this is unlikely an issue with the CDK.

**Comment by SomayaB** [comment]
Closing this issue for now since there hasn't been a response in a while. Feel free to reopen.
