### ISSUE TITLE
RDS - Import existing DatabaseInstance from ARN

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#7295]
Currently the AWS CDK only allows creating a DB instance. It would be great to be able to import and reuse existing RDS instances.

### Use Case
Creating a CI pipeline that automatically provisions QA "sandboxes" of the app, that are all connected and reuse the same DB instance.

Because of this use case.

### Proposed Solution

`DatabaseInstance.fromArn();`

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
You should be able to use `fromDatabaseInstanceAttributes` for this:
https://github.com/aws/aws-cdk/blob/b14172d2ac86da55a0ebf7efdbe25b6ef35f832c/packages/%40aws-cdk/aws-rds/lib/instance.ts#L88

**Comment by nija-at** [comment]
Hi @Dzhuneyt -

Let us know if the API that @jogold has referred to above does not satisfy your use case.

Marking this issue as closing soon.

**Comment by mariusingjer** [comment]
It would be great with an example of how this is supposed to work. The suggestion from the author is to import based on arn, the method referred to is requiring instance identifier, port, security group ++. Whats the suggested solution here? To export everything required by the fromInstanceAttributes?

**Comment by romor** [comment]
> It would be great with an example of how this is supposed to work.

Not sure whether this is correct, but I would try it like this:
<pre>
const db = rds.DatabaseInstance.fromDatabaseInstanceAttributes(this, "myDb", {
      instanceIdentifier: "db-name",
      instanceEndpointAddress: "db-arn",
      port: 5432,
      securityGroups: [],
});
</pre>

**Comment by zilahir** [comment]
@romor not really :) the question was whether it's possible to get an RDS instance by it's arn. The example you provided, even you are not doing that, the `instanceEndpointAddress` is not takes an `arn`, it takes an url. So this is still a desired feature request.

**Comment by rverton** [comment]
Also looking for a solution to this, as @zilahir already mentioned, `fromDatabaseInstanceAttributes` solves a different purpose in my understanding, because you need to pass all attributes manually. @nija-at can you reopen this?

**Comment by gshpychka** [comment]
The L2 construct needs more information than the ARN to function, so you cannot only reference it by ARN.

To be clear - this function does not do a lookup or any API call, it is just a read-only reference to some resources, so you need to provide all the information it needs to it.

**Comment by JoshMcCullough** [comment]
I think what we're looking for here is "simply" a way to _not_ have to provide all of these seemingly extraneous details (`instanceEndpointAddress`, `port`, `securityGroups`). I'm sure it's more complicated than I/we realize, but it seems that we need a lookup function where we can pass the ARN or `instanceIdentifier`.

**Comment by gshpychka** [comment]
> I think what we're looking for here is "simply" a way to _not_ have to provide all of these seemingly extraneous details (`instanceEndpointAddress`, `port`, `securityGroups`).

Since this is not a lookup (as mentioned above, it does not perform any API calls), it needs all information required by the methods/props that `IDatabaseInstance` provides.

What you're asking for is a "lookup", which is reasonable, but doesn't exist at all for RDS yet - I would open a new feature request for a lookup function for RDS instances.

**Comment by JoshMcCullough** [comment]
Yes, asking for a lookup -- exactly. 

Submitted a [new feature request](https://github.com/aws/aws-cdk/issues/31720), thanks!
