### ISSUE TITLE
Confusing Error: InvalidCidrRangeError: x.x.x.x/11 is not a valid VPC CIDR 

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#7296]
This was totally my fault - I found out afterwords that a VPC has to be atleast a /16..

However if you try to use a /8:

```
    const vpc = new ec2.Vpc(this, 'privateVpc', {
       cidr: '10.0.0.0/8'
    });

    const cacheSubnet  = new ec2.Subnet(this, 'cacheSubnet', {
      vpcId: vpc.vpcId,
      cidrBlock: '10.0.0.0/24',
    });
```

Your told `InvalidCidrRangeError: x.x.x.x/11 is not a valid VPC CIDR range (must be between /16 and /28)` when you later try to create a subnet.

Clearly, its trying to calculate a subnet based on the assumption that the user followed the rules, but then spits out nonsense...

**Comment by gunggmee** [comment]
I've just experienced the same problem. CDK doesn't allow me to specify CIDR as `10.0.0.0/26~28`, otherwise the CDK throws `InvalidCidrRangeError`. I have to pass `10.0.0.0/25` to make it work.

- `x.x.x.x.28` => "`x.x.x.31` is not a valid VPC CIDR range ..."
- `x.x.x.x.27` => "`x.x.x.30` is not a valid VPC CIDR range ..."
- `x.x.x.x.26` => "`x.x.x.29` is not a valid VPC CIDR range ..."
- `x.x.x.x.25` => pass

The version of CDK is `1.49.1 (build 7d6321f)`.

**Comment by smit8995** [comment]
I am also facing the same issue. Any updates on this? Did anyone able to resolve this issue?

**Comment by sblackstone** [comment]
@smit8995 This is more of a documentation/better error message bug rather than an issue with the CDK's implemntation.. Make sure you are using a /16 or smaller for your VPC..

**Comment by smit8995** [comment]
@sblackstone I am facing the same issue as @gunggmee is facing. I am trying to create a VPC with CIDR range as "x.x.x.x/26" but it is throwing error as "x.x.x.x/29 is not a valid VPC CIDR range (must be between /16 and /28)”

**Comment by NukaCody** [comment]
I believe this is a bug.

Here is a valid VPC configuration with a CIDR split up unevenly 

![Screen Shot 2021-05-13 at 5 25 14 PM](https://user-images.githubusercontent.com/30978270/118189753-3107c000-b410-11eb-9a83-e8f37ba6175f.png)

And this is the code

```typescript
import { SubnetType, Vpc } from '@aws-cdk/aws-ec2';
import { App, Construct, Stack, StackProps } from '@aws-cdk/core';

export class SingleVPCStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    new Vpc(this, 'SingleVPC', {
      cidr: '10.128.1.0/26', // 64 host
      maxAzs: 2,
      subnetConfiguration: [
        {
          name: 'ingress',
          subnetType: SubnetType.PUBLIC,
          cidrMask: 29,
        },
        {
          name: 'application',
          subnetType: SubnetType.PRIVATE,
          cidrMask: 28,
        },
        {
          name: 'database',
          subnetType: SubnetType.PRIVATE,
          cidrMask: 29,
        },
      ],
    });
  }
}

// for development, use account/region from cdk cli
const devEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: process.env.CDK_DEFAULT_REGION,
};

const app = new App();

new SingleVPCStack(app, 'SingleVPCStackDev', { env: devEnv });
// new SingleVPCStack(app, 'my-stack-prod', { env: prodEnv });

app.synth();
```

and ideally, I should get something like this

![Screen Shot 2021-05-13 at 5 28 30 PM](https://user-images.githubusercontent.com/30978270/118190154-b2f7e900-b410-11eb-9540-c4109b64a6b4.png)

But I get the same error:

```bash
x.x.x.x/29 is not a valid VPC CIDR range (must be between /16 and /28)
```

**Comment by sblackstone** [comment]
@NukaCody A subnet has to be at-least a /28 and at most a /16...  The /29 is why you're having trouble.

**Comment by NukaCody** [comment]
Oof, yep. Thanks....
