### ISSUE TITLE
The `pathPatterns` prop should be handled when calling `addTargetGroups` on `ImportedApplicationListener`

### ISSUE THREAD

**Issue by vukers** [aws/aws-cdk#7303]
There was a recent feature added to allow for an array of pathPatterns to be used when calling `addTargetGroups`on `ApplicationListener`. This should also be applied to `ImportedApplicationListener`.

### Use Case

So I can add multiple pathPatterns to an imported application listener.

### Proposed Solution

Pass `pathPatterns` property to `ApplicationListenerRule` contructor.

https://github.com/DerkSchooltink/aws-cdk/blob/fdfd48ef691a994d616d282740fce6d487597ff2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L492

### Other

Original issue: https://github.com/aws/aws-cdk/issues/6497
Original pull request: https://github.com/aws/aws-cdk/pull/6558
Suggested link to line: https://github.com/DerkSchooltink/aws-cdk/blob/fdfd48ef691a994d616d282740fce6d487597ff2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L492

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by DerkSchooltink** [comment]
> There was a recent feature added to allow for an array of pathPatterns to be used when calling `addTargetGroups`on `ApplicationListener`. This should also be applied to `ImportedApplicationListener`.
> 
> ### Use Case
> So I can add multiple pathPatterns to an imported application listener.
> 
> ### Proposed Solution
> Pass `pathPatterns` property to `ApplicationListenerRule` contructor.
> 
> https://github.com/DerkSchooltink/aws-cdk/blob/fdfd48ef691a994d616d282740fce6d487597ff2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L492
> 
> ### Other
> Original issue: #6497
> Original pull request: #6558
> Suggested link to line: https://github.com/DerkSchooltink/aws-cdk/blob/fdfd48ef691a994d616d282740fce6d487597ff2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L492
> 
> * [ ]  👋 I may be able to implement this feature request
> * [ ]  ⚠️ This feature might incur a breaking change
> 
> This is a 🚀 Feature Request

Give me a few minutes and I will submit the PR! :)
