### ISSUE TITLE
Cyclic dependency issue when installing helm chart from a different stack

### ISSUE THREAD

**Issue by satyamkondle** [aws/aws-cdk#7307]
When creating EKS cluster in one stack and then referencing that cluster in a different stack to create helm charts, I run into cyclic dependency error.

### Reproduction Steps
1. Create eks cluster in StackA and add the cluster reference to outputs
2. Create another StackB and get the output from StackA
3. Create HelmChart from StackB and refer to the cluster from StackA

### Python CDK code to reproduce (Set AWS_REGION and AWS_ACCOUNT and run)
```
import os
import logging

from aws_cdk import (
    core,
    aws_eks as eks
)

AWS_REGION="us-east-1"
AWS_ACCOUNT="<account>"

class EKSStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # Create the EKS Cluster
        eks_cluster = eks.Cluster(
            self, "mycluster",
            default_capacity=0,
            cluster_name="mycluster",
            kubectl_enabled=True
        )

        self.output_props=dict(
            eks_cluster=eks_cluster)

    # pass objects to another stack
    @property
    def outputs(self):
        return self.output_props


class HelmStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, props, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        eks_cluster = props['eks_cluster']
        
        nginx_controller_chart = eks.HelmChart(
            self, "nginx-controller",
            cluster=eks_cluster,
            chart='nginx-ingress',
            repository='https://kubernetes-charts.storage.googleapis.com/'
        )


app = core.App()

eksStack = EKSStack(
    app,
    "eks-base",
    description="Creates the EKS Cluster",
    env=core.Environment(region=AWS_REGION, account=AWS_ACCOUNT)
)

nodeStack = HelmStack(
    app,
    "eks-helm",
    eksStack.outputs,
    description="Creates Helm charts for EKS",
    env=core.Environment(region=AWS_REGION, account=AWS_ACCOUNT)
)

app.synth()

```

### Error Log
 Error: 'eks-helm' depends on 'eks-base' (eks-helm -> eks-base/mycluster/Resource/Resource/Default.Ref, eks-helm -> eks-base/mycluster/Resource/CreationRole/Resource.Arn). Adding this dependency (eks-base -> eks-helm/@aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource.Outputs.${Token[eks-helm..aws-cdk--aws-eks.KubectlProvider.eksh...eksKubectlProviderHandlerServiceRoleC7DADAABArn.LogicalID.425]}) would create a cyclic reference.

### Environment

  - **CLI Version      :1.31.0**
  - **Framework Version:<What is this? not sure>**
  - **OS               : Mac OS Catalina**
  - **Language         : Python3**

This is :bug: Bug Report

**Comment by eladb** [comment]
Duplicate #7231 - fix is under way
