### ISSUE TITLE
Need help setting context as a Map<string, string[]> in unit tests

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#7311]
## :question: General Issue

The background for this is that I want to write a construct that can read cdk.context.json and retrieve values. I want to store a < string: string[] > in cdk.context.json like so:
```
{
  "availability-zones:account=123456789012:region=us-west-2:serviceName=com.amazonaws.vpce.us-west-2.vpce-svc.abcdefghijkl": [
    "us-west-2a",
    "us-west-2b",
    "us-west-2c"
  ]
}
```
Then retrieve it in code to create the construct.

### The Question
I am having difficulty figuring out how to unit test my construct. I think I need to set the context by doing:
```ts
const app = new App({ context });

// Other unit test code
```
for the unit test, however the AppProps context parameter requires a Map<string, string>. For my use case I think I need to pass a Map<string, string[]>, but it seems I am unable to do so.

Is it possible to do what I am trying to do in CDK?

### Environment

  - **CDK CLI Version:** 1.32.1
  - **OS:** OSX Mojave
  - **Language:** Typescript

### Other information
I was thinking - if AppProps' _context_ parameter is the issues, it could be changed to be a Map<string, any> and enforce the type within the constructor of App.

**Comment by nirvana124** [comment]
@flemjame-at-amazon looks like it was missed to make context inside AppProps to    
readonly context?: {
        [key: string]: any;
 };

For your unit test you can try out below code 
for (const [ k, v ] of Object.entries(context)) {
      app.node.setContext(k, v);
}

**Comment by NetaNir** [comment]
@flemjame-at-amazon this is a JSII limitation, you can use `{[key: string]: string}`.
Closing this, please feel free to reopen.

**Comment by flemjame-at-amazon** [comment]
@NetaNir for the case I'm trying to achieve, what would that look like?

**Comment by NetaNir** [comment]
Hi @flemjame-at-amazon,

In completely missed the cdk.context.json file in your question!
It sound like you are trying to implement a contextProvider? something similar to [availability zones](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/context-providers/availability-zones.ts)? 

What are you trying to test? setting the context? 
```typescript
    stack.node.setContext(key, ['us-east-1a', 'us-east-1b']);
```

**Comment by flemjame-at-amazon** [comment]
@NetaNir yes! I haven't gotten around to writing the context provider, but it will be modeled on the [availability zones](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/context-providers/availability-zones.ts) one, whose values are accessed by [Stack](https://github.com/aws/aws-cdk/blob/v1.32.0/packages/@aws-cdk/core/lib/stack.ts#L519-L522)

I wanted to start with reading the values from cdk.context.json before writing the provider to call AWS services, but I couldn't figure out how to unit test accessing cdk.context.json. You're saying this should work for a unit test?

```ts
stack.node.setContext(key, ['us-east-1a', 'us-east-1b']);
```

**Comment by NetaNir** [comment]
Yes, it will, checkout this [test](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/test/test.context.ts#L14)

>but it will be modeled on the availability zones one, whose values are accessed by Stack

Not completely synced with your plans but in case you find it useful, you can override [getAvailabilityZones](https://github.com/aws/aws-cdk/blob/b7bb325d62c0bddb7d70324fd35a98192f577356/packages/%40aws-cdk/core/lib/stack.ts#L497) if you need custom behavior.
