### ISSUE TITLE
Issue when creating `AwsCustomResource`

### ISSUE THREAD

**Issue by sean-smith** [aws/aws-cdk#7312]
Hi, I'm getting an error when creating the `AwsCustomResource`.

### Reproduction Steps

```python
cr.AwsCustomResource(self, 'Cloud9IAMMembership',
            resource_type='Custom::Cloud9IAMMembership', policy=cr.AwsCustomResourcePolicy.from_sdk_calls(resources=cr.AwsCustomResourcePolicy.ANY_RESOURCE)
            on_create=cr.AwsSdkCall(
                action='CreateEnvironmentMembership', 
                service='cloud9', 
                parameters={   
                    "environmentId": cloud9_instance.environment_id,
                    "permissions": "read-write",
                    "userArn": user.user_arn
                },
                physical_resource_id=cr.PhysicalResourceId.from_response("environmentId")
            ),
 )
```

### Error Log

The error is `Failed to create resource. AWS[call.service] is not a constructor`:
![image](https://user-images.githubusercontent.com/5545980/79031541-3717d700-7b54-11ea-9514-679bb75884b0.png)

### Environment

  - **CLI Version      :** `1.3.1`
  - **Framework Version:** ``
  - **OS               :** `MacOS`
  - **Language         :** `Python`

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
It should be `Cloud9` and `createEnvironmentMembership` see https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Cloud9.html

The underlying custom resource is using the AWS SDK for JavaScript.

**Comment by eladb** [comment]
Closing. Reopen if this is still an issue.

**Comment by sean-smith** [comment]
Thanks @jogold !

**Comment by eladb** [comment]
I wonder if we can do case insensitive match when we look up the api?

**Comment by jogold** [comment]
> I wonder if we can do case insensitive match when we look up the api?

Easily achievable for the `service`, somewhat more complex for the `action` (uses getters and will rely on the internals of the SDK). Should we do it for the `service`?

**Comment by touzoku** [comment]
Maybe at least some more meaningful error?
