### ISSUE TITLE
appsync example in Overview missing keyword, won't synthesize auth type Cognito User Pool

### ISSUE THREAD

**Issue by pszabop** [aws/aws-cdk#7313]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-appsync-readme.html

The following line in the overview is incorrect.  It results in the default type of `API_KEY`.  
```

        defaultAuthorization: {
          userPool,
          defaultAction: UserPoolDefaultAction.ALLOW,
        },
  
```
The following is an example that synthesizes to type `AMAZON_COGNITO_USER_POOLS`
```
        defaultAuthorization: {
          userPool: userPool,   // must name the attribute `userPool: <value>`
          defaultAction: UserPoolDefaultAction.ALLOW,
        },

```

---

This is a 📕 documentation issue

**Comment by BryanPan342** [comment]
See #8993 for changes.
