### ISSUE TITLE
Using /tmp directory as working directory easily surpass Lambda's limit

### ISSUE THREAD

**Issue by zzfukai** [aws/aws-cdk#7316]
"Failed to create resource. [Errno 28] No space left on device", it is especially common for Java applications.

https://github.com/aws/aws-cdk/blob/3bbd99d33ed246f9d7c8768b66dc44cd09f1e903/packages/%40aws-cdk/aws-s3-deployment/lambda/src/index.py#L117

**Comment by NetaNir** [comment]
Hi @zzfukai, 

You didn't specify  if this is a bug/issue, if you could edit the issue to use the issues template it will be helpful. In the meantime, https://github.com/aws/aws-cdk/issues/6893 has some discussion that might be relevant.
