### ISSUE TITLE
Bucket construct parameter type has wrong link in Python API reference

### ISSUE THREAD

**Issue by chefren** [aws/aws-cdk#7336]
link to reference doc page: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/Bucket.html

describe your issue:

- **lifecycle_rules**' type is (Optional[List[LifecycleRule]])
- When going to the definition link of LifecycleRule, it navigates to the [ECR type](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecr/LifecycleRule.html#aws_cdk.aws_ecr.LifecycleRule), instead of the [S3 type](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/LifecycleRule.html)

Probably some bug in the doc generator, as the class names are the same?
---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Feels like I've seen this issue reported before.

**Comment by rix0rrr** [comment]
Duplicate: https://github.com/aws/aws-cdk/issues/5863
