### ISSUE TITLE
Change the usage of tokens for lazy evaluation

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#736]
Instead of `new Token(() => value)`, since the use case for using lazy evaluation is only for synthesis, maybe what we can do is actually provide a method in `Construct`, which will also give us the ability to associate the token with the construct:

```ts
new QueueResource(this, 'Resource', {
  visibilityTimeout: this.lazyEval(() => 122)
});
```

See https://github.com/awslabs/aws-cdk/pull/712#discussion_r218329669

**Comment by rix0rrr** [comment]
Something like

```
Value.lazy(() => xxx)
```

might even be better. But I'm having trouble thinking of a good class name to substitute for `Value` there.

**Comment by eladb** [comment]
The reason I was thinking to tie this into the `Construct` is that the mental model is the this is a value that's going to be evaluated during synthesis (under the hood it might use something like `Value.lazy` but when I read CDK code, it actually makes sense to be more explicit about when is this value going to be resolved. 

How about `this.synthesisEval(() => 122)` or `this.synthEval(() => 'hello')`.

Thoughts?

**Comment by rix0rrr** [comment]
I'm not sure the more complex name is worth it in this case.

**Comment by eladb** [comment]
Resolved
