### ISSUE TITLE
Deploy stacks in reverse order of dependencies

### ISSUE THREAD

**Issue by timpur** [aws/aws-cdk#7379]
Some times it is required to "undo" changes in the reverse order of how you made those changes. Thus to be able to "undo", we require to deploy stacks in reverse to how they were deployed normally.

### Use Case

The main issue i face this that construct uses outputs from stack1 and stack1 can not update those outputs because stack2 is using them, hence this feature.

The main use case would be you've added a construct to stack2 that depends on stack1, but you need to change something in stack1 but because stack 2 depends on stack1 you can not. At the moment the only options are, to delete the stack or manually deploy stack2 with the removed construct thus unlinking stack2 on stack1.

### Proposed Solution

The solution would be the delete the construct in code that makes stack2 depend on stack1, but this time deploy stack2 first, then deploy stack1. Then you could re-add the construct in stack2, then make the stack1 changes that you couldn't do before and deploy normally. Thus stack 1 wont fail making the change because at this point stack2 isn't dependant on stack1.

This would make changes to underlining resources in dependant stack mush easier (assuming you have a method to "Disconnect"). Ie a 2 step process, disconnect stack and deploy in reverse, make changes to dependencies, reconnect stacks and deploy normally.

I would assumes this to be added as flag in the deploy cli to say deploy in reverse order `-r`?

### Other

```ts
const stack1 = new Stack(...)
const stack2 = new Stack(...)

stack2.connectTo(stack1) // stack2 is now dependant on stack1
```

Steps:
1. Comment out line 3 and deploy in reverse order
2. Make changes to stack1, uncomment like 3 and deploy normally

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by timpur** [comment]
@eladb @SomayaB @shivlaks any update or plans for this ? should i go forward and create a PR ?

**Comment by SomayaB** [comment]
Hi @timpur, it's low on our task list right now, so if you want to go ahead and submit a PR we would appreciate it! 👍

**Comment by rainydio** [comment]
> Thus to be able to "undo", we require to deploy stacks in reverse to how they were deployed normally.

How about adding `cdk deploy --reverse` flag? Similarly to `cdk destroy` it would select downstream stacks and then deploy them in reverse order thus undoing the changes.

**Comment by timpur** [comment]
Still would be nice to have this but not a P1
