### ISSUE TITLE
Using AdvancedSecurityOptions when creating an Elasticsearch Cluster with CDK

### ISSUE THREAD

**Issue by ravanapel** [aws/aws-cdk#7381]
When creating a new Elasticsearch cluster from the console or using the [SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ES.html#createElasticsearchDomain-property), you are able to specify the master user by filling in AdvancedSecurityOptions. Currently, the [documentation](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-elasticsearch/cfndomainprops.html#aws_elasticsearch_CfnDomainProps) does not seem to reference AdvancedSecurityOptions, and does not allow setting a master user.

### Use Case

I would use this feature because I am planning to create an ES cluster using CDK.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Hi @ravanapel - Thanks for reporting this.

It looks like this configuration is not yet supported by CloudFormation. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html

We encourage you to [open](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/new) an issue with CloudFormation to add support for this. Once it's added, it will be automatically available in the CDK.

In the meantime, you can try creating a custom resource to enable this functionality using the [`AWS Custom Resource` ](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#custom-resources-for-aws-apis).

**Comment by iliapolo** [comment]
Duplicate of https://github.com/aws/aws-cdk/issues/7197 which is now resolved. Closing.
