### ISSUE TITLE
How to pass a custom role to QueueProcessingFargate?

### ISSUE THREAD

**Issue by netmailgopi** [aws/aws-cdk#7387]
https://github.com/aws/aws-cdk/blob/f35a4db7fd6a5794f5c5449f226610915c03c053/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L88

I'm trying to use QProcessingFargate construct. I see it creating its own role and assigning permissions to access the queue. I'm looking to use the role I'm creating in another stack. What's the way to pass a role to this construct? I don't think the role is exposed, is this how it is? I'm interested in contributing if so.

**Comment by MrArnoldPalmer** [comment]
There is no way to pass a role on construction currently, but you can access the role after initialization using `service.taskDefinition.taskRole`. With that you can add policies or perform other needed actions on it.

However, there may still be a use case for passing a custom role to the construct so keeping this open.

**Comment by SoManyHs** [comment]
@pkandasamy91 is there a PR for this already?

**Comment by SoManyHs** [comment]
@netmailgopi Can you give more detail on your use case for this request? Is the role you're trying to reuse for another QueueProcessingFargate construct?

Thanks!

**Comment by netmailgopi** [comment]
Sorry for the delay - We run multi-teneted accounts with several services in them separated by SGs, IAM. We do not employ service roles, but have a role created for each of our services that have the entire set of permissions to do their job.

One of our new services/applications has some lambdas in addition to Fargate. With the lack of passing role to Q processing fargate, we're forced to build managed policies and attach them to the automatically created role.

**Comment by cdimascio** [comment]
For those looking for a workaround, you can set a custom role on the QueueProcessingFargateService by accessing the underlying taskDefinition cfn resource

for example:

```typescript
const myTaskRole = new iam.Role(/* .. */);
const qps = new ecs_patterns.QueueProcessingFargateService(this, 'QueueProcessingFargateService', { /* ... */ });

const taskDef = qps.taskDefinition.node.defaultChild as ecs.CfnTaskDefinition;
// Set the task role
taskDef.taskRoleArn = myTaskRole.roleArn;
```

**Comment by f-skold** [comment]
I had similar issued, and I failed to add an existing managed ploicy to the task definitions.
