### ISSUE TITLE
Add support for custom java script in request template of gateway lambda Integration

### ISSUE THREAD

**Issue by ssrikanta** [aws/aws-cdk#7395]
From the AWS console we can set java script in integration request template mapping. the same can not be set through AWS CDK.

### Use Case
Template mapping from api gateway integration request allows to set application/json, with we can also embed java script code as shown below, similar support should be provided through AWS CDK as well.
```
{"action": "hello",
#set($inputRoot = $input.path('$'))
"endPoints": [
#foreach($elem in $inputRoot.endPoints)
	{
	#set($headers = $elem.headers)
    #if($headers != "")
		"headers": "$elem.headers",
    #end
    "uri": "$elem.uri",
    "info": "$elem.info"
    }
 #if($foreach.hasNext),#end
 #end
 ]}

```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ssrikanta** [comment]
This is a programming error, i am withdrawing this

**Comment by iacomus** [comment]
what was the solution?
