### ISSUE TITLE
Connections.allow_from() not working when target is ScheduledFargateTask.cluster.connections

### ISSUE THREAD

**Issue by tonyhammainen** [aws/aws-cdk#7400]
I am trying to allow ScheduledFargateTask to connect to Elasticache Redis cluster.

When allowing inbound connections to the redis_connections, line
`redis_connections.allow_from(fargate_task.cluster.connections, port_range=ec2.Port.tcp(6379))` 
does not produce any CDK changes. Commenting or not commenting the line results in "No changes". Also no inbound rules appear in AWS console, so it's not just a matter of not showing them on command line.

On the contrary, line
`redis_connections.allow_from_any_ipv4(port_range=ec2.Port.tcp(6379))`
produces an expected output, i.e.
` + │ ${redis-security-group.GroupId}   │ In  │ TCP 6379   │ Everyone (IPv4) │`

### Reproduction Steps

```
redis_subnet_group = elasticache.CfnSubnetGroup(
            self,
            "RedisClusterPrivateSubnetGroup",
            cache_subnet_group_name="recommendations-redis-subnet-group",
            description="Redis subnet for recommendations",
            subnet_ids=[subnet.subnet_id for subnet in vpc.private_subnets],
        )

        redis_security_group = ec2.SecurityGroup(self, "redis-security-group", vpc=vpc)

        redis_connections = ec2.Connections(
            security_groups=[redis_security_group], default_port=ec2.Port.tcp(6379)
        )

        redis = elasticache.CfnCacheCluster(
            self,
            "RecommendationsRedisCacheCluster",
            engine="redis",
            cache_node_type="cache.t2.small",
            num_cache_nodes=1,
            cluster_name="recommendations-redis",
            vpc_security_group_ids=[redis_security_group.security_group_id],
            cache_subnet_group_name=redis_subnet_group.cache_subnet_group_name,
        )
        redis.add_depends_on(redis_subnet_group)

        image_options = ecs_patterns.ScheduledFargateTaskImageOptions(
            image=ecs.ContainerImage.from_ecr_repository(self.ecr_repo, "latest"),
            cpu=256,
            memory_limit_mib=2048,
            environment={
                "REDIS_ENDPOINT_URL": redis.attr_redis_endpoint_address,
                "REDIS_ENDPOINT_PORT": redis.attr_redis_endpoint_port,
            },
        )

        fargate_task = ecs_patterns.ScheduledFargateTask(
            self,
            "RecommendationsScheduledFargateTask",
            scheduled_fargate_task_image_options=image_options,
            schedule=applicationautoscaling.Schedule.rate(core.Duration.minutes(1)),
            desired_task_count=1,
            vpc=vpc,
        )


        redis_connections.allow_from(fargate_task.cluster.connections, port_range=ec2.Port.tcp(6379))
        redis_connections.allow_from_any_ipv4(port_range=ec2.Port.tcp(6379))
```

### Error Log
```

pipenv run -- cdk diff --profile myprofile mystack
Stack mystack
There were no differences

```
### Other

Same behavior if turned around, i.e.
`fargate_task.cluster.connections.allow_to(redis_security_group, port_range=ec2.Port.tcp(6379))`

### Environment

  - **CLI Version      : 1.32.2 (build e19e206)**
  - **Framework Version:**
  - **OS               : macos**
  - **Language         : Python**

This is :bug: Bug Report

**Comment by mskrip** [comment]
I'm experiencing a similar issue when trying to allow connection from `ecs.Cluster` to `rds.DatabaseProxy`. Following produces no cloud formation changes:

```python
db_proxy.connections.allow_from(
    cluster.connections,
    db_instance.connections.default_port,
)
```

For now I have to allow the port from all IPs within the VPC

**Comment by MisterGlass** [comment]
I was having this same issue with an ecs cluster and an RDS database, it turned out we needed to pass the service instead of the cluster.

**Comment by webm0nk3y** [comment]
> I was having this same issue with an ecs cluster and an RDS database, it turned out we needed to pass the service instead of the cluster.

How do we get to the "service" from the ScheduledFargateTask?

**Comment by MrArnoldPalmer** [comment]
@johndobrien there is no `Service` construct for ScheduledFargateTask as it just runs the tasks directly and doesn't use the service construct which is meant for continuously running tasks. I believe this could basically be a feature request to implement `IConnectable` on [EcsTask](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events_targets.EcsTask.html) so you could do `MyThing.allowFrom(ScheduledFargateTask.task)`

For now you can access the security groups directly and I believe that should solve it, IE:
```
MyScheduledFargateTask.task?.securityGroups.forEach(sg => MyThing.allowFrom(sg))
```

**Comment by madeline-k** [comment]
Looks like there is currently a way to accomplish what the original requester was looking for here, so I am closing this issue. If anyone is interested in the feature request that @MrArnoldPalmer described above, please open a new issue.
