### ISSUE TITLE
Cognito: Prevent User Existence Errors

### ISSUE THREAD

**Issue by brainstorm** [aws/aws-cdk#7406]
This is a followup issue from https://github.com/aws/aws-cdk/issues/7245#issuecomment-614658074

After creating a UserPool, the web console section that reads like the following:

> Prevent User Existence Errors

<img width="334" alt="Skärmavbild 2020-04-17 kl  21 51 45" src="https://user-images.githubusercontent.com/175587/79566336-baf23600-80f5-11ea-8fe5-676f8facbd3b.png">

Does not seem to be found on CDK.

### Use Case

I need this feature for security auditing purposes on a clinical genomics context.

### Proposed Solution

[Find out the equivalent Cloudformation section for this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-preventuserexistenceerrors), implement it in CDK.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
I can't seem to find this property on the [`AWS::Cognito::UserPool`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-writeattributes) construct in CloudFormation. We may have to wait for them to add this property in before the CDK can support it.

**Comment by brainstorm** [comment]
@nija-at I'm confused, you pointed out in https://github.com/aws/aws-cdk/issues/7245#issuecomment-614658074 that it was in CloudFormation already and the docs say so:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-preventuserexistenceerrors

**Comment by nija-at** [comment]
Oops, you are correct! I had it confused with a different property.

**Comment by duarten** [comment]
I opened https://github.com/aws/aws-cdk/pull/7836 for this.
