### ISSUE TITLE
Allow to set read and write attributes in Cognito UserPoolClient

### ISSUE THREAD

**Issue by tom139** [aws/aws-cdk#7407]
When a client of a Cognito User Pool is created, the developer can (and should) specify which user attributes the client will be able to read and/or write.

This is not currently implemented in Cognito.

### Use Case

Often you want different clients to be able to make different operations on user attributes.
For example, there might be a `customerPlan` attribute for every user but only some clients (i.e. those used by the back office) are allowed to change its value.

Or you may want to allow a specific client (e.g. the one used by the web app) to be able to read the `email` attribute but not the `

### Proposed Solution

The proposed solution is to allow to set the list of read attributes and write attributes to the props for _userPoolClient_.

As example
```typescript
const pool = new UserPool(stack, 'Pool');
pool.addClient('MyClient', {
  readAttributes: ['email', 'phoneNumber', 'custom:customerPlan', 'custom:isActive']
  writeAttributes: ['phoneNumber', 'custom:isActive']
});
```

I think there are two flaws with this approach:
 1. having to type the attribute names is error prone
 2. having to prepend `custom:` to all custom attributes can be easily forgot

The solution for both problems could be the following:

```typescript
const pool = new UserPool(stack, 'Pool');
pool.addClient('MyClient', {
  readAttributes: {
    // all cognito attributes are automatically available as boolean values
    email: true,
    phoneNumber: true,
    // all custom attributes can be set with an array without the need to prepend them with `custom:`
    custom: ['customerPlan', 'isActive'],
  },
  writeAttributes: {
    // all cognito attributes are available as boolean values
    email: false,
    phoneNumber: true,
    // all custom attributes can be set with an array without the need to prepend them with `custom:`
    custom: ['isActive'],
  },
});
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by cmckni3** [comment]
I agree with the custom attributes part.

FYI, interestingly standard attributes are defined in CDK as an [enum](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cognito/lib/user-pool.ts#L884) but the enum isn't exported.

**Comment by tom139** [comment]
Wow this is great news! I knew about the [RequiredAttributes](https://github.com/aws/aws-cdk/blob/df2fc4bf32a32e7f6e04453fd009abab80a2483c/packages/%40aws-cdk/aws-cognito/lib/user-pool-attr.ts#L6) interface but this is way better.

How do you think this should be implemented?

#### 1 - With explicit `true` or `false` behavior

Where the user set which attributes are readable/writable and which are not (this might cause confusion about default values)

```typescript
const pool = new UserPool(stack, 'Pool');
pool.addClient('MyClient', {
  readAttributes: {
    // all cognito attributes are automatically available as boolean values
    email: true,
    phoneNumber: true,
    // all custom attributes can be set with an array without the need to prepend them with `custom:`
    custom: ['customerPlan', 'isActive'],
  },
  writeAttributes: {
    // all cognito attributes are available as boolean values
    email: false,
    phoneNumber: true,
    // all custom attributes can be set with an array without the need to prepend them with `custom:`
    custom: ['isActive'],
  },
});
```

#### 2 - With 2 lists (one for standard attributes, one for custom)

Where the user sets 2 independent attribute lists.

```typescript
const pool = new UserPool(stack, 'Pool');
pool.addClient('MyClient', {
  readAttributes: {
    // all cognito attributes are available through the `StandardAttribute` enum
    standard: [StandardAttribute.EMAIL, StandardAttribute.PHONE_NUMBER]
    // all custom attributes can be set with an array without the need to prepend them with `custom:`
    custom: ['customerPlan', 'isActive'],
  },
  writeAttributes: {
    // all cognito attributes are available through the `StandardAttribute` enum
    standard: [StandardAttribute.PHONE_NUMBER],
    // all custom attributes can be set with an array without the need to prepend them with `custom:`
    custom: ['isActive'],
  },
});
```

#### 3 - With one list

The `readAttributes` and `writeAttributes` property could be of type `Array<string | StandardAttribute>` but this might be more confusing than helpful and may even cause problems to Jsii

```typescript
const pool = new UserPool(stack, 'Pool');
pool.addClient('MyClient', {
  // all cognito attributes are available through the `StandardAttribute` enum,
  // all custom attributes must be specified omitting the `custom:` prefix
  readAttributes: [StandardAttribute.EMAIL, StandardAttribute.PHONE_NUMBER, 'customerPlan', 'isActive'],
  writeAttributes: [StandardAttribute.PHONE_NUMBER, 'isActive'],
});
```

---

I think the best approach is 2, let me know if you think it is not.

**Comment by cmckni3** [comment]
I like approach 2

**Comment by arnulfojr** [comment]
I'm a little confused but I may not have the whole picture.
With now support for mutable customAttributes, (afaik) the requiredAttributes are not set as mutable atm.
Is it possible for the client to write into the (required) attributes?
Is there any reason why to not have a requiredAttribute set as mutable?
I assume the custom Attributes are allowed to be written because now the attribute can be set as mutable...

**Comment by tom139** [comment]
You are right, the ability of setting standard attributes as mutable should be implemented (basically the same of #7011 for standard attribute) and a new issue should be filed for it.

But the ability to selectively read/write custom and standard attribute is useful even if StandardAttribute are currently not mutable. Until mutability will be implemented, this means that only app clients able to write all immutable attributes will be able to signup new user.

**Comment by stevensnoeijen** [comment]
I'm using this workaround for now:
```
        const client = userPool.addClient('client', {
            userPoolClientName: 'client',
            generateSecret: false,
            disableOAuth: true,
        });
        const cfnClient = client.node.defaultChild as CfnUserPoolClient;
        cfnClient.readAttributes = [
            // customs
            'custom:validated_email',
        ];
        cfnClient.writeAttributes = [
            // defaults
            'email',
            'family_name',
            'gender',
            'given_name',
            // customs
            'custom:validated_email',
        ];
```

**Comment by jonathanbiard** [comment]
We started a project using Amplify and we are now replacing it with the CDK. As it stands right now, I cannot set the read/write attributes in the same way as Amplify was doing it because there is no option in `pool.addClient()` / `UserPoolClientOptions` for this.

I will try @stevensnoeijen 's workaround for now but it would be nice not to have to use a workaround.
