### ISSUE TITLE
s3: Better way to set BucketPolicy deletion policy

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#7415]
I want to retain S3 bucket and the S3 bucket policy that goes with the bucket. This is common for logging buckets and data buckets with a bucket policy.

Currently, I have to use an escape hatch.

```
(bucketPolicy.node.defaultChild as CfnResource).applyRemovalPolicy(
  RemovalPolicy.RETAIN
);

// OR

(bucket.policy.node.defaultChild as CfnResource).applyRemovalPolicy(
  RemovalPolicy.RETAIN
);
```

### Use Case

I want to retain logging buckets (example: CloudTrail S3 bucket). The bucket policy (if there is one) must be retained as well otherwise stack deletion will fail.

### Proposed Solution

Add an optional property on `BucketPolicyProps` and/or have a method on `BucketPolicy` to set it.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Hi @cmckni3 - sounds like a good addition.

Should be pretty similar in implementation to how we apply the removal policy for `Bucket`:
