### ISSUE TITLE
Updating parameter in cdk deploy creates new resource and deletes old resources

### ISSUE THREAD

**Issue by jacobneroth** [aws/aws-cdk#7416]
---

This is a 📕 documentation issue

**Comment by jacobneroth** [comment]
When u create a new stack and use either the context or parameter name to pass sqs queue name and lambda name and deploy it , it works 
But with the same code if you use different parameters , and send cdk deploy nothing works . Is this expected behaviour ?

**Comment by eladb** [comment]
@jacobneroth can you please follow the guidelines when reporting this bug? We need clear reproduction steps and the exact error messages.

Closing for now.
