### ISSUE TITLE
Linting doesn't work if developing from the main project with JetBrains IDEs

### ISSUE THREAD

**Issue by andrestone** [aws/aws-cdk#7423]
## Issue

This PR breaks linting for JetBrains IDEs, when working in the global project: #7232.

I can confirm that it can be fixed by adding `eslint` as a dependency to each package's `package.json`.

Ref: https://youtrack.jetbrains.com/issue/WEB-25561#focus=streamItem-27-4074912.0-0

## Details

This is the error message: 
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts.
The file must be included in at least one of the projects provided.
Process finished with exit code -1
```

**Comment by jogold** [comment]
Can you confirm that you have a `tsconfig.json` in that folder (`packages/@aws-cdk/aws-autoscaling`)? It should be there if the package was already built.

**Comment by andrestone** [comment]
Yes, I do.

Theres a detailed explanation of this issue here: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007713479-How-to-make-ESLint-run-in-package-dir-in-monorepo-?page=1#community_comment_360001548980

**Comment by nija-at** [comment]
This, unfortunately, seems like a limitation of the IDE or the IDE plugin.

Sorry there's not much we can help out here. If there's a settings file or specific instructions for the IDE, we're happy to accept a PR that adds this into the project.
