### ISSUE TITLE
Invalid Error Message in ICluster

### ISSUE THREAD

**Issue by kalzoo** [aws/aws-cdk#7431]
The error message [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ICluster.html) does not match the actual API of `ICluster`: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ICluster.html

There is no `addXXXCapacity()` method. `addCapacity` only exists on `Cluster` itself, which is not accessible via an `ApplicationLoadBalancedEc2Service` and likely other classes which include a cluster.

Possible fixes:

* Add the methods from [cluster](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html) to `ICluster` interface.
* Type `ApplicationLoadBalancedEc2Service#cluster` as `Cluster` rather than `ICluster`

### Reproduction Steps

In my case, this presented itself in using the `ApplicationLoadBalancedEc2Service`, which _should_ work out of the box, but as with earlier attempts, it does not.

```
    const service = new ecsPatterns.ApplicationLoadBalancedEc2Service(
      this,
      "ApplicationService",
      {
        cpu: 512,
        memoryLimitMiB: 1024,
        desiredCount: 1,
        healthCheckGracePeriod: cdk.Duration.seconds(30),
        publicLoadBalancer: true,
        taskImageOptions: {
          enableLogging: true,
          image: ecs.AssetImage.fromAsset("../api"),
          containerPort: 4000,
        },
        vpc,
      }
    );
```

Seems reasonable that capacity must be created and assigned, but there are no callouts for that in the [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedEc2Service.html), where the word `capacity` is nowhere on the page.

### Error Log

As shown in linked code

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

Workaround: cast

```
    (service.cluster as ecs.Cluster).addCapacity("HostFleet", {
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.SMALL
      ),
      machineImage: new ec2.AmazonLinuxImage(),
    });
```

--- 

This is :bug: Bug Report

**Comment by efekarakus** [comment]
Hi @kalzoo,

The error message link in the description doesn't seem to lead to the correct location. Would you mind sharing the error again?

However, I think the general flow for an `ApplicationLoadBalancedEc2Service` would be like this:
```typescript
const vpc = new ec2.Vpc(this, 'MyVpc', { maxAzs: 2 });
const cluster = new ecs.Cluster(this, 'Cluster', { vpc });
cluster.addCapacity("HostFleet", {
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.SMALL
      ),
      machineImage: new ec2.AmazonLinuxImage(),
    });
const service = new ecsPatterns.ApplicationLoadBalancedEc2Service(
      this,
      "ApplicationService",
      {
        cpu: 512,
        memoryLimitMiB: 1024,
        desiredCount: 1,
        healthCheckGracePeriod: cdk.Duration.seconds(30),
        publicLoadBalancer: true,
        vpc,
        taskImageOptions: {
          enableLogging: true,
          image: ecs.AssetImage.fromAsset("./api"),
          containerPort: 4000,
        },
        cluster,
      }
);
```

So the cluster needs to be declared first. I can look into updating the docs saying that a cluster with enough capacity must be associated with the service first.
