### ISSUE TITLE
ApiCustomResource - HTTP(S) API based custom resources

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#7447]
Not exactly sure what this interface would look like, but it would be nice if we could build custom resources that are based on an API call. I think this would enable a lot of custom resources to be created with ease. For example, creating resources for GitLab using the GitLab API. etc you name it.

### Use Case

I need this to manage a multitude of external applications that might be deployed as part of my infrastructure. 

### Proposed Solution

This is just a quick brain dump.

```typescript
new ApiCustomResource(this, 'GitLabProject', {
  authSecret: someSecretManagerSecret,
  onCreate: {
    endpoint: "https://.../api/v4/projects",
    method: 'POST',
    ....
    physicalResourceId: PhysicalResourceId.fromResponse('id')
  }
});
```

Perhaps we can get the inspiration for interface options from an existing system such as the terraform rest API provider: 
- https://github.com/Mastercard/terraform-provider-restapi

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
I love this idea, but I doubt that this is something we will be have time to work on. @abelmokadem, how about releasing an open source construct library with this capability? Do you need any pointers on how to do that?

**Comment by McDoit** [comment]
@eladb Dunno if you will notice this, but i stumbled across this issue and would love to ge some pointers on how to do that!
