### ISSUE TITLE
CDK Grants into AWS Managed Policy

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#7448]
CDK Grants option to specify either an existing AWS Managed Policy to to create the Grant as a new AWS Managed Policy

### Use Case

AWS IAM Best Practice
[Use Customer Managed Policies Instead of Inline Policies ](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#best-practice-managed-vs-inline)

It's easier to manage, version, control, and review AWS Customer Managed Policies compared to Inline policies.

Users should have the option to utilize AWS Customer Managed Policies, rather than only inline policies.

### Proposed Solution

Allow the ability to create a new AWS Customer Managed Policy or specify an existing AWS Customer Managed Policy. Rather than the default which is always an Inline Policy.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by athewsey** [comment]
+1: I was surprised recently to learn that `ManagedPolicy` doesn't implement `IGrantable`. Any updates on this?

I'd like to build a stack/app that outputs a ManagedPolicy with required permissions for stack resources (specifically things like S3 buckets, SSM param read/write, SFn state machine execution...) - so that this policy can be attached to/removed from roles/users/groups as required.

Today, it seems like I'd need to manually build up lists of `PolicyStatements` to achieve this, since the high-level resource methods like `Bucket.grant_read(...)` all require `IGrantable`s so can't work with a ManagedPolicy?

**Comment by elacy** [comment]
Here is a quick work around for anyone else that runs into this problem
```
import cdk = require('monocdk');
import iam = require("monocdk/aws-iam");
import {ManagedPolicy} from "monocdk/aws-iam";
import {PolicyStatement} from "monocdk/lib/aws-iam/lib/policy-statement";

export class PrincipalPolicy extends ManagedPolicy implements iam.IPrincipal {
    private principal: iam.IPrincipal;

    constructor(scope: cdk.Construct, id: string, props: iam.ManagedPolicyProps) {
        super(scope, id, props);

        if ((props.users?.length || 0) + (props.roles?.length || 0) + (props.groups?.length || 0) !== 1) {
            throw Error("PrincipalPolicy must have one and only one principal");
        }

        if (props.users?.length === 1) {
            this.principal = props.users[0];
        }

        if (props.roles?.length === 1) {
            this.principal = props.roles[0];
        }

        if (props.groups?.length === 1) {
            this.principal = props.groups[0];
        }
    }

    /**
     * (experimental) When this Principal is used in an AssumeRole policy, the action to use.
     *
     * @experimental
     */
    get assumeRoleAction(): string {
        return this.principal.assumeRoleAction;
    }

    /**
     * (experimental) Return the policy fragment that identifies this principal in a Policy.
     *
     * @experimental
     */
    get policyFragment(): iam.PrincipalPolicyFragment {
        return this.principal.policyFragment;
    }

    /**
     * (experimental) The AWS account ID of this principal.
     *
     * Can be undefined when the account is not known
     * (for example, for service principals).
     * Can be a Token - in that case,
     * it's assumed to be AWS::AccountId.
     *
     * @experimental
     */
    get principalAccount(): string | undefined {
        return this.principal.principalAccount;
    }

    /**
     * (deprecated) Add to the policy of this principal.
     *
     * @returns true if the statement was added, false if the principal in
     * question does not have a policy document to add the statement to.
     * @deprecated Use `addToPrincipalPolicy` instead.
     */
    public addToPolicy(statement: PolicyStatement): boolean {
        super.addStatements(statement);
        return true;
    }

    /**
     * (experimental) Add to the policy of this principal.
     *
     * @experimental
     */
    public addToPrincipalPolicy(statement: PolicyStatement): iam.AddToPrincipalPolicyResult {
        super.addStatements(statement);
        return {
            statementAdded: true,
            policyDependable: this
        };
    }

    /**
     * (experimental) The principal to grant permissions to.
     *
     * @experimental
     */

    get grantPrincipal(): iam.IPrincipal {
        return this;
    }
}
```

**Comment by automartin5000** [comment]
Just ran into the inline policy limit where this could've solved for that. Reported bug here: https://github.com/aws/aws-cdk/issues/18457

**Comment by kornicameister** [comment]
cdk team, why is that exactly an issue here to be able to grant into managed policies?

**Comment by bilalq** [comment]
The inability to attach a managed policy makes it way harder to grant CodeArtifact access to CDK pipeline synth steps than it should be.

**Comment by kornicameister** [comment]
I mean, the whole concept of granting is based on `iam.IGrantable` that has the principal. ManagedPolicies may have multiple policies but perhaps it would be simply sufficient to have `iam.IGrantablePolicy` and or `iam.IGrantablePrincipal` interfaces inheriting from `iam.IGrantable`. That way most of the code could stay put and long story short if we had with `iam.IGrantablePrincipal` we would simply call `add_statements`. Needless to say all those statements are anywhere in the code because you actually put them into default policy.

**Comment by dan-lind** [comment]
Related PR, not sure why it's still a draft though. https://github.com/aws/aws-cdk/pull/22712

**Comment by Tietew** [comment]
#22712 has been merged. `Policy` and `ManagedPolicy` now implement `IGrantable`.
It just throw an error when a Policy/ManagedPolicy is added to a resource-based policy.

**Comment by khushail** [comment]
Hi @Tietew , looks like the issue has been resolved and changes implemented. So I would be marking this issue as closed. 

For this new error,- `It just throw an error when a Policy/ManagedPolicy is added to a resource-based policy.`
 you might want to open a new issue to get more traction and help.
