### ISSUE TITLE
Please can I have dead letter config when subscribing a lambda to an sns topic...

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-cdk#7449]
Support for dead letter queues on lambda subscriptions to sns was added [November](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-sns-adds-support-for-dead-letter-queues-dlq/) last year.

Please can cdk allow me to register a dead letter queue against a lambda sns subscription...

So I do:

```
        event_topic.add_subscription(LambdaSubscription(my_lambda,
            filter_policy={'message_name': SubscriptionFilter.string_filter(whitelist=[...])}))
```

I've tried to use the "escape hatch" approach but I'm unable to get the CfnSubscription out of the LambdaSubscription and it seems that SnsEventSource supports a redrive policy but then I can't see a way to add filtering when using SnsEventSource.

The Redrive policy is available in Cloudformation as the CfnSubscription has it.

### Use Case

I want to leverage the new feature of having dead letter queues on lambda subscription in sqs so I can deal with errors in my messages (and still be able to use sns as a lambda event source.

### Proposed Solution

It would be great if the redrive policy could be included in the lambda subscription constructor:
```
        event_topic.add_subscription(LambdaSubscription(my_lambda,
            filter_policy={'message_name': SubscriptionFilter.string_filter(whitelist=[...])}
            redrive_policy = {'deadLetterTarget' : dead_letter_queue, "maxReceiveCount" : 5}
))
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by michaelwiles** [comment]
hmm... let me see if I can do it

**Comment by michaelwiles** [comment]
So I have made good progress on adding this to cdk.

I have a comment/question however... When I first started, I assumed that the redrive policy for sns subscriptions is the same as the redrive policy for queues. So I figured I would reuse the same construct - [DeadLetterQueue](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.DeadLetterQueue.html).

However, I then discovered that I was getting invalid attribute maxReceiveCount - this is because for sns topics redrive policy there is no max receive count - it is not supported. Only a dead letter queue can be set and the [existing maxReceiveCounts are used](https://docs.aws.amazon.com/sns/latest/dg/sns-message-delivery-retries.html). 

As a side comment it has made dead letter queues on sns much less useful for us such that I don't need this feature added - but since I've done a lot of the work I should add this in any case...

So now what I did is add a redrivePolicy of type [DeadLetterQueue](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.DeadLetterQueue.html) to [SubscriptionProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sns-subscriptions.SubscriptionProps.html).

```
export interface SubscriptionProps {
  /**
   * The filter policy.
   *
   * @default - all messages are delivered
   */
  readonly filterPolicy?: { [attribute: string]: sns.SubscriptionFilter };

  readonly redrivePolicy?: sqs.DeadLetterQueue;
}
```

But the reality is because the maxReceiveCount is not supported on sns subscriptions the DeadLetterQueue construct should possibly not be used as it houses a maxReceiveCount... So maybe the redrivePolicy should just be a queue.

I guess it depends on if maxReceiveCount will ever be added to the topic subscriptions or if extra parameters will be required in the future for redrive policy as if they are and we've gone with the plain queue approach it will require a breaking change.

**Comment by MrArnoldPalmer** [comment]
@michaelwiles This is great info. Appreciate the writeup. So since `maxReceiveCount` isn't configurable, the only time messages will populate in your DLQ is when the default of `100,015 times, over 23 days` is exceeded? that does seem to reduce the usefulness of the feature overall.

Since `DeliveryPolicy` is what dictates how retries work in SNS with custom endpoints, my guess is this is how custom retry/backoff logic would be supported in the future. Its not guaranteed that `maxReceiveCount` would be used. Its not clear if it even makes sense really nomenclature wise with the differences between how messages flow through SNS/SQS so I wouldn't want to bank on that.

Though its not ideal API wise, the prudent thing here may be to wrap this with a new type for this specific purposed, IE `SnsRedrivePolicy` that currently just accepts a `queueArn` in the constructor. In the future if the redrive policy receives more options we can expand properties there, or if DeliveryPolicy can be customized with sqs subscriptions we can handle that parameter as well.

**Comment by MrArnoldPalmer** [comment]
@michaelwiles looks like another issue was created for this and has a [PR against it](https://github.com/aws/aws-cdk/pull/7635). The subscription accepts an `IQueue` which is probably ideal with the circumstances you explained. Adding you as a reviewer on that so provide any feedback you have. Appreciate your help on this.

Closing in favor of #7623

**Comment by michaelwiles** [comment]
The "delivery policy" as you've mentioned is set at a topic level and at a subscription level all that is required is to set the dead letter queue - so I do think the PR is right in that all it sets is the deadLetterQueue.

I think the delivery policy at the topic level _may_ be extendable to handle lambda type subscrioptions as well.

**Comment by shellscape** [comment]
@MrArnoldPalmer @michaelwiles I'm not seeing anything in CDK which allows for setting the `DeliveryPolicy` on either a per-subscription or per-topic basis. We've got `CfnSubscription.deliveryPolicy` but beyond the base construct it doesn't appear to be available. Am I overlooking something, or is that still as yet to be added to the consumable constructs like `Topic` and `Subscription` (I forget what "level" they're called)
