### ISSUE TITLE
CLI: every change to assets requires permissions confirmation

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#7452]
Because we give permissions on individual asset keys, and because the keys are liable to change, we're left uselessly confirming asset changes every time, even though it doesn't REALLY change our security posture.

This may lead people to disable the confirmation (or confirm it without checking), which will be bad for security in the grand scheme of things.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@rix0rrr that seems like a valid concern where the excessive nagging would result in users bypassing it and that it's not a change in posture.

I think that the current default behavior shouldn't change as it's still a change that we have been reporting. My concern with changing the default is that it might be surprising for users who do expect the permissions confirmation and might lead them to assume that assets didn't change.

How about a context key or flag that supports bypassing asset changes? Did you have something different in mind?

**Comment by rix0rrr** [comment]
What I said might not even be true anymore. Looks like we grant permissions on the entire bucket.
