### ISSUE TITLE
Keep security groups in Connection objects as source of truth

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#7472]
Constructs that deal with SGs currently have two lists of SGs:

* One list as instance member
* One list in the Connections object

When mutation comes into the picture these lists can get out of sync, which is confusing.

The list-on-self is actually superfluous. All constructs should just be using the list in the connections object as the single source of truth, and it should be convenient to do that.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Triggered by https://github.com/aws/aws-cdk/issues/7373

**Comment by flemjame-at-amazon** [comment]
Is it possible to have a linter rule to catch this stuff? Something like "no class variables which are a security group, or list of security groups, or set of security groups?
