### ISSUE TITLE
ITable does not implement grant() api

### ISSUE THREAD

**Issue by amwill04** [aws/aws-cdk#7473]
Unsure if this is a bug or a limitaion/missing feature

Importing a `dynamodb` table using `fromTableArn` or `fromTableName` implements an `ITable` but this does not include the `grant()` method. 

```typescript
const table = new Table(...);
table.grant(....) // works

const table = Table.fromTableName(...)
table.grant(....) // grant does not exist on type ITable
```

### Environment

  - **CLI Version      :1.33.1
  - **Framework Version:1.33.1
  - **OS               :macos
  - **Language         :typescript

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
It's present on `TableBase` but unfortunately missing on `ITable`.

@RomainMuller could be easily added to #7453?

**Comment by amwill04** [comment]
@jogold the simple work around is to cast as a `Table` which works for me.

```typescript
const table = Table.fromTableName(...)
(table as Table).grant(....) // grant now available
```
