### ISSUE TITLE
New project template should use "npx ts-node --prefer-ts-exts bin/cdk.ts" instead of "npx ts-node bin/cdk/ts"

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#7475]
In the cdk.json file, the default typescript project provides the following command:
```
{
   "cdk": "npx ts-node bin/cdk.ts"
}
```

This works okay in most cases, in case you decided to run "tsc" to compile .ts to .js files. The "ts-node" library by default prioritizes and uses the .js extension files, which can quickly become out-of-sync with the .ts version, if you forget to run "tsc" afterwards.

Given that ts-node doesn't need the .js files at all, it makes sense to cause it to read .ts files with priority, avoiding headaches for developers who ran "tsc" once and forgot about the existence and need for it later.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by philBrown** [comment]
Similarly, it would be great to have the Jest config template include
``` js
moduleFileExtensions: ["ts", "tsx", "js", "json", "jsx", "node"]
```

**Comment by Jerry-AWS** [comment]
See PR: https://github.com/aws/aws-cdk/issues/7475

**Comment by Jerry-AWS** [comment]
The above PR has been merged and this change will appear in the next release of the CDK. @Dzhuneyt Thanks for raising this issue!

**Comment by rcollette** [comment]
@Jerry-AWS 
This comment
https://github.com/aws/aws-cdk/issues/7475#issuecomment-727628410

Is referencing this same issue (circular).  What is the actual PR?

**Comment by Jerry-AWS** [comment]
That was PR https://github.com/aws/aws-cdk/pull/11470, sorry
