### ISSUE TITLE
iam: policy names attached to imported resources conflict with each other

### ISSUE THREAD

**Issue by amwill04** [aws/aws-cdk#7483]
Unable to change to a dynamic policy name when using `grantXXX()` api.

Given the following within a `stack`:

```typescript
const queue = new Queue(this, 'ICEQuoteQueue', {
    queueName: `a-queue-${this.props.environment}`,
    deliveryDelay: Duration.seconds(0),
    visibilityTimeout: Duration.seconds(30),
    retentionPeriod: Duration.days(4),
    receiveMessageWaitTime: Duration.seconds(0),
});
const group = Group.fromGroupArn(
    this,
    'Group',
    this.formatArn({ resource: 'group', service: 'iam', resourceName: 'Name' })
);

queue.grantSendMessages(group)
```

if I am to create multiple `templates` the above will create the same `policy name` meaning that anthing on the same account will override the policy statement.

Therefore if i deploy `dev` followed by `test` I will lose the send permissions in `dev`

### Environment

  - **CLI Version      :1.33.1
  - **Framework Version:1.33.1
  - **OS               :macos
  - **Language         :typescript

**Comment by rix0rrr** [comment]
This is probably not solveable in general, but maybe we can make it slightly nicer.

**Comment by acere** [comment]
Encountered the same issue when granting privileges to the same IAM roles from two different stacks.
Is there any update on workarounds to rename the IAM policies created by `grant*` methods?

**Comment by thomaswr** [comment]
Having the same issue with granting permissions to imported IAM users in two different stacks.
My current workaround is to include the stack name in the id of the imported user.
But very easy to miss that.
