### ISSUE TITLE
cdk.secret "Types have separate declarations of a private property 'value'"

### ISSUE THREAD

**Issue by aflinton** [aws/aws-cdk#7485]
Using the std example to hook into Github from codepipeline.

`import * as cdk from '@aws-cdk/core';
import * as codebuild from '@aws-cdk/aws-codebuild';
import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as codepipeline_actions from '@aws-cdk/aws-codepipeline-actions';

oauthToken: cdk.SecretValue.secretsManager('my-gh-token'),`

Fails with 

`Type 'import("/home/adamf/git-emis/event-engine-examples/CDK/codepipeline/ee-pipeline/node_modules/@aws-cdk/core/lib/secret-value").SecretValue' is not assignable to type 'import("/home/adamf/git-emis/event-engine-examples/CDK/codepipeline/ee-pipeline/node_modules/@aws-cdk/aws-codebuild/node_modules/@aws-cdk/core/lib/secret-value").SecretValue'.

  Types have separate declarations of a private property 'value'.ts(2322)
source-action.d.ts(61, 14): The expected type comes from property 'oauthToken' which is declared here on type 'GitHubSourceActionProps'`

Updated to the latest cdk ( cdk --version = 1.33.1 (build 8ad4d34) ) to see if it was a bug in the version I am using. 

### Reproduction Steps

See above

### Error Log

See above 

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by aflinton** [comment]
There was a version difference between the cdk core and the cdk codepipeline packages in the packages.json. Fixed it manually in the packages.json, updated and problem solved. Thanks

**Comment by SatyaHarish9** [comment]
> There was a version difference between the cdk core and the cdk codepipeline packages in the packages.json. Fixed it manually in the packages.json, updated and problem solved. Thanks

Can you please provide the steps to update ?

**Comment by richgiuli** [comment]
I had this happen. I opened up package.json and noticed everything was version 1.69.0 except core. Running `npm install @aws-cdk` did not update to latest. I had to force it: `npm install @aws-cdk/core@1.69.0`

**Comment by abivolmv** [comment]
I had one cdk package with "~" and one with "^". After aligning all packages in package.json this was fixed.

**Comment by vincentgna** [comment]
using projen, you can use `cdkVersionPinning` when you need to ensure your app aws-cdk-lib matches a package version.
