### ISSUE TITLE
CDK diff against multiple stacks does not fail

### ISSUE THREAD

**Issue by polothy** [aws/aws-cdk#7492]
In our pipeline, trying to use this command to speed up deployments:
```shell
cdk diff --fail -e 'our-prefix-*'
```
If the command fails, then we loop through our stacks, run diff and deploy on each (we have many stacks in this project).

**The problem:** the diff command returns an exit code of `0` when the first stack **does have a diff**, but the second stack does **not have a diff**.  I assume the exit code is just being overwritten by the last diff executed.

### Reproduction Steps

* Create two stacks and prefix their names with `your-prefix-`
* Run `cdk ls` and deploy the stack listed at the end of the list
* Run `cdk diff --fail -e 'your-prefix-*'

You should get an exit code of `0` when it should be a `1` or non-zero.

### Error Log

N/A

### Environment

  - **CLI Version      :** 1.33.1
  - **Framework Version:** 1.33.1
  - **OS               :** macOS and Ubuntu (AWS CodeBuild Standard 4.0)
  - **Language         :** Python 3.7

### Other

My `cdk.context.json` has this:
```json
{
  "@aws-cdk/core:enableStackNameDuplicates": "true",
  "aws-cdk:enableDiffNoFail": "true"
}
```
I get same behavior with or without the `enableDiffNoFail` line.

--- 

This is :bug: Bug Report

**Comment by polothy** [comment]
My guess is that this line needs to change from `=` to `+=`:

https://github.com/aws/aws-cdk/blob/857e78832fbfe0a540dddff440adfd5caeca0011/packages/aws-cdk/lib/cdk-toolkit.ts#L103

**Comment by polothy** [comment]
Attempted to fix in https://github.com/aws/aws-cdk/pull/7690

**Comment by Martell96** [comment]
Confirming that this is still happening. Even if all stacks, but the last one, have a diff, the exit code of `cdk diff` will be 0.
