### ISSUE TITLE
aws-sam cloud formation resources out of date

### ISSUE THREAD

**Issue by stormsilver** [aws/aws-cdk#7493]
When attempting to utilize resources from the `aws-sam` package, the available resources and properties do not match what is in the SAM documentation.

For example:
`ApiEventProperty` currently in CDK gives three properties (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sam.CfnFunction.ApiEventProperty.html):
* method
* path
* restApiId

However, it should provide many additional properties: (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html)
* auth
* requestModel
* requestParameters

There are other examples, like `AWS::Serverless::Api`  missing the `DomainConfiguration` property.

Additionally, the `AWS::Serverless::HttpApi` resource is missing entirely.

### Use Case

I would like to take advantage of SAM cfn resources without having to resort to building them myself with `CfnResource`, which is the current workaround.

### Proposed Solution

I'm not sure precisely how these Cfn resources get generated. I have to assume they are pulled from somewhere and automatically generated but I'm not familiar with the process. Either it's run manually and simply needs to be run again, or it's run automatically and it's not pulling the updated sources.

### Other

* https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html
* https://docs.aws.amazon.com/cdk/api/latest/docs/aws-sam-readme.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Thanks for filing this issue!

We currently download the spec from a repo called awslabs/goformation - https://github.com/aws/aws-cdk/blob/9f8de62b865a5c226892630211d098bd523524cb/packages/%40aws-cdk/cfnspec/build-tools/update.sh#L58

The CDK has clearly outgrown this and we need a better way to keep the SAM spec up to date with the latest.

In the meantime, you will be able to use these missing properties using our [raw property overrides](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw).
As for the missing resource type itself, you could use [`CfnResource`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnResource.html) to specify this.
Neither of these are ideal, and we apologize for the current poor experience here.

**Comment by nija-at** [comment]
Unfortunately, there is no machine readable SAM spec available officially - https://github.com/awslabs/serverless-application-model/issues/1133

**Comment by AKK9** [comment]
This looks like it hasn't been assigned/worked on yet, but in version 1.111.0 it seems to have been fixed.

**Comment by skinny85** [comment]
Looks like this was fixed in https://github.com/aws/aws-cdk/pull/15362 🙂.
