### ISSUE TITLE
Calculate CodeSha256 from Lambda code assets for Lambda Versions

### ISSUE THREAD

**Issue by kennu** [aws/aws-cdk#7494]
The Lambda Version construct has a CodeSha256 property, but there doesn't seem any way in AWS CDK to calculate the value for it.  I think AWS CDK could handle this automatically.

### Use Case

Create new Lambda Versions when deploying new code.

### Proposed Solution

I believe AWS CDK is already calculating a [CodeSha256 parameter for artifacts](https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/core/lib/private/asset-parameters.ts#L26) and passing it to CloudFormation when deploying. We would just need a way to refer to that parameter when specifying the CodeSha256 property for the Version construct.

If this is already possible, then I think the documentation for the CodeSha256 property in VersionOptions and VersionProps should describe how to do it.

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
This can be achieved using `function.currentVersion` which will create a new version for every change to the lambda code or parameters. This was introduced in https://github.com/aws/aws-cdk/pull/6771 and released in V1.32.0

**Comment by kennu** [comment]
Thanks, it's working. I noticed `currentVersion` in the documentation. But because it's a property, I didn't understand that just reading it (without calling any methods or setting any value) will actually create a new function version.

I think the documentation could be clarified a little bit. It should explain how exactly you are supposed to create a new Lambda version (by assigning function.currentVersion to a dummy variable?).

Perhaps the documentation of the Lambda Version CodeSha256 property could also describe how you are supposed to create a new version, since that's where I was looking for it first.

FWIW, I was just about to create a little CodeSha256 hack because I found the ArtifactHash parameter in stack.node.metadata. But I didn't yet figure out how to use it as a property. I guess `currentVersion` will be enough anyway so this issue can probably be closed.

**Comment by kennu** [comment]
To increase the difficulty level, if you want to retain old versions, you need to specify `current_version_options` in the Function constructor, and then also assign `current_version` to something. 

If you only specify `current_version_options`, a version is not created. I tried that before creating this issue.

For reference, here is my test code, written in Python for random reasons.
```
from aws_cdk import core, aws_lambda

class KennuTestChangeTemplateStack(core.Stack):
    def __init__(self, scope: core.Construct, stack_name: str, **kwargs) -> None:
        super().__init__(scope, stack_name, **kwargs)
        code = aws_lambda.Code.asset('lambda_function')
        function = aws_lambda.Function(self, 'GreengrassMainFunction',
            function_name='%s-gg-main' % (stack_name),
            runtime=aws_lambda.Runtime.PYTHON_3_7,
            code=code,
            handler='handler.handle_greengrass_event',
            environment=dict(
                TARGET_DEVICE='greengrass-core',
            ),
            current_version_options=aws_lambda.VersionOptions(removal_policy=core.RemovalPolicy.RETAIN)
        )
        ver = function.current_version

```

**Comment by nija-at** [comment]
I've opened a new issue for this - https://github.com/aws/aws-cdk/issues/8149 - and resolving this one.
