### ISSUE TITLE
Using ZoneDelegationRecord adds wrong expected value to Route53

### ISSUE THREAD

**Issue by bundgaard** [aws/aws-cdk#7503]
Route53 expect ResourceRecords for Nameservers to "\n" separated, according to documentation on its webpage.

ZoneDelegationRecord used in Java, adds a list of nameservers as a comma separated of strings, which is not the expected value, and for my part is not working when querying my sub-domain.

### Reproduction Steps

```
 ZoneDelegationRecord(this, "$namePrefix-hosted-zone-sub-zone", ZoneDelegationRecordProps.builder()
                .nameServers(nsForHostedZone.getAttString("Value").split(",")) // you would expect AWS CDK to work with all the fancy constructs, but no, they add this as comma-separated files, and Route53 expect them to be newline separated... (stupid)
                .comment("Zone delegation to make sub zone available")
                .zone(HostedZone)
                .recordName("${config.environment}.${config.product}")
                .ttl(Duration.minutes(5)) // TODO: change to something longer for more durability...
                .build())
```

### Error Log

No error message, but quering the sub zone 

`dig -t NS sub-zone.domain.tld` expected value would be the name servers added.

After manually changing the comma separated value in Route53 to the expected new-line separated value makes it works...

### Environment

  - **CLI Version      : 1.32.2
  - **Framework Version: aws-cdk for java/kotlin
  - **OS               : Linux
  - **Language         :Kotlin

### Other

It should be possible to do this without having to resort to custom functionality, what is the take away from using CDK compared to CloudFormation, where you have the expected behaviour?

--- 

This is :bug: Bug Report

**Comment by bundgaard** [comment]
ResourceRecords also have this bug...

```
val nameservers = nsForHostedZone.getAttString("Value").split(",")
val nameserverRecordSet = RecordSet(this, "$namePrefix-hosted-sub-zone", RecordSetProps.builder()
                .comment("Zone delegation to make sub zone available")
                .recordType(RecordType.NS)
                .recordName("${config.environment}.${config.product}")
                .ttl(Duration.minutes(5))
                .zone(magnetarHostedZone) 
                .target(RecordTarget.fromValues(*nameservers.toTypedArray()))
                .build())```

**Comment by shivlaks** [comment]
@bundgaard - that doesn't seem ideal at all if you need to make manual changes. Are these changes to your generated template or from elsewhere? Is the generated templated incorrect?

I'll need to run through the repro steps and trace this one down.

**Comment by bundgaard** [comment]
From the generated template I get #TOKEN ... 

I will have to generate the the template again as I solved it by using a lambda function and read in the output of the stack.
