### ISSUE TITLE
Move LambdaRestApi to a pattern?

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#7505]
Does the `LambdaRestApi` construct fit in the pattern description for constructs? If so, can we move it to a new package `aws-apigateway-patterns`?

**Comment by nija-at** [comment]
The answer is maybe 😊
Unfortunately, we don't have an official definition of patterns. 

The two pattern packages we have have been used for use cases which need two or more AWS services to be set up and configured between them but themselves don't declare the other to be a dependency.

In the case of APIGateway, the service has defined [lambda integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html) as a way to set up a Rest API. 
Hence, it lives in the APIGateway package, just like how lambda can integrate with SQS, SNS or something else.

I'm curious to hear more about what prompted this question. Can you describe how this will benefit you or someone else using the CDK?

**Comment by abelmokadem** [comment]
@nija-at I think what you are saying now already gives a better explanation of when something is really a pattern. I ask this question because I'm giving training on CDK and it's good to have clarity on the things I'm explaining. Perhaps we can close this issue then?

**Comment by nija-at** [comment]
Best of luck on the training!
