### ISSUE TITLE
ScheduleExpression is not valid - Scheduled event for every minute fails to create

### ISSUE THREAD

**Issue by owenashurst** [aws/aws-cdk#7514]
### The Question

Why can't I set a scheduled event to run every minute? Creating this fails:

```
new Rule(this, 'every-minute-schedule-rule', {
            schedule: Schedule.expression('cron(* * * * *)'),
            targets: [new LambdaFunction(someLambda)],
        });
```

### Environment

  - **CDK CLI Version:** 1.34.1 (build 7b21aa0)
  - **Module Version:** @aws-cdk/aws-events - 1.34.1 AND @aws-cdk/aws-events-targets - 1.34.1
  - **OS:** Windows
  - **Language:** Typescript

### Other information
`Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: 93735cb3-21b4-44d1-a2c9-9f3b30b75610)`

**Comment by jonny-rimek** [comment]
Try 
` schedule: Schedule.cron({}),`

I did it a week ago, if I remember the syntax correctly of the top of my head

**Comment by shivlaks** [comment]
@owenashurst try

```ts
schedule: Schedule.expression('rate(1 minute)'),
```

**Comment by owenashurst** [comment]
Thanks @jonny-rimek and @shivlaks. Specifying an empty object for Schedule.cron worked great. I ended up using your second example in the @shivlaks with Schedule.rate using Duration exported from awsd-cdk/core.

**Comment by jonny-rimek** [comment]
didn't know about rate either. TIL.
