### ISSUE TITLE
Create ecs.Cluster resource without ec2.Vpc

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#7515]
I want to create an ecs.Cluster resource without needing an ec2.Vpc resource.

### Use Case

I'm creating a Fargate task and I don't have nor want to create a VPC in my AWS account.

### Proposed Solution

Add another flag to create the ecs.Cluster resource without creating the ec2.VPC for me.

```
new ecs.Cluster(this, "Cluster", {
  createVpc: false
})
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
If you do not want to create a new VPC you can supply one using the `vpc:`property. The Fargate task needs a VPC to launch containers in. So you either need to supply one or let the `ecs.Cluster` create one for you.

**Comment by abelmokadem** [comment]
@hoegertn I was under the impression that you don't need a VPC to run a Fargate task.

**Comment by abelmokadem** [comment]
@hoegertn yup, it wasn't quite clear but it is indeed needed. Thanks for responding so quickly.

**Comment by juanledesma84** [comment]
Hello fellows.
I'm working to migrate several CloudFormation scripts to CDK, and I have the same question taht @abelmokadem did, because when I have created a cluster in fargate using cloudformation I don't specify the VPC.

`
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Application}-${Environment}-fargate"
`

And that is all. Could you @hoegertn help me with that, please? 
Thanks guys.

**Comment by hoegertn** [comment]
Yes, the Cfn Resource Cluster does not need a VPC. But in CDK the `Cluster` is not only representing this but also the source of information for Services and Tasks. These need a VPC to run inside.
