### ISSUE TITLE
Updates to DB password via SecretManager does not work

### ISSUE THREAD

**Issue by mjslane** [aws/aws-cdk#7518]
When RDS is first set up using secret manager a secret is created with the following format

    {
      "password": "******",
      "dbname": "*****",
      "engine": "postgres",
      "port": 5432,
      "host": "******.rds.amazonaws.com",
      "username": "******"
    }

If a change is made to the CDK that causes the password to be regenerated the password is updated but dbname, host, port and engine is removed from the secret. If services rely on this information being there it breaks the service.

### Reproduction Steps

1. Deploy a stack using RDS for example

```   
      const instance = new DatabaseInstance(this, `my-rds-instance`,{
            engine: DatabaseInstanceEngine.POSTGRES,
            instanceClass: props.rdsInstanceClass,
            masterUsername: props.rdsMasterUserName,
            vpc: props.vpc,
            enablePerformanceInsights: props.rdsInsights,
            vpcPlacement: {subnetType: SubnetType.PRIVATE},
            databaseName: "my-dbname",
            instanceIdentifier: `my-db-identifier`,
            removalPolicy: props.rdsRemovalPolicy,
            deletionProtection: deletionProtection
        });
        //fix secret issues
        const dbSecret = instance.node.tryFindChild('Secret') as DatabaseSecret;
        const cfnSecret = dbSecret.node.defaultChild as CfnSecret;
        cfnSecret.addPropertyOverride('GenerateSecretString.ExcludeCharacters', '\'\\;@$"`!/');
```

Check the secret generated.

Update the excluded characters by adding or removing some.

Redeploy

Check the secret again.

### Environment

  - **CLI Version      :*1.33.1 (build 8ad4d34)*
  - **OS               :*OSX Catalina*
  - **Language         :*typescript*

This is :bug: Bug Report

**Comment by nija-at** [comment]
Thanks for filing this issue. I was able to reproduce this.

This is a weird one - 

I can confirm that the only thing that changes in the CloudFormation template between the two changes is the value of [`ExcludeCharacters`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-secret-generatesecretstring.html#cfn-secretsmanager-secret-generatesecretstring-excludecharacters). Everything else in the template is exactly the same, so I suspect something is different about how the Secrets Manager backend handles a create vs an update request.

The dbname, host and dbengine should not even be present in the secret generated in the first place. The [`SecretStringTemplate`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-secret-generatesecretstring.html#cfn-secretsmanager-secret-generatesecretstring-secretstringtemplate) is [configured to only contain the username and ARN of the mastersecret](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-rds/lib/database-secret.ts#L41-L44) besides the generated password. It's not clear why it got into the secret manager value in the first place. 
I can confirm this the case from the generated CloudFormation template -

```
"GenerateSecretString": {
  "ExcludeCharacters": "\"@/\\`",
  "GenerateStringKey": "password",
  "PasswordLength": 30,
  "SecretStringTemplate": "{\"username\":\"myadmin\"}"
}
```

@jogold / @skinny85 - anything either of you know of that I missed?

**Comment by jogold** [comment]
The dbname, host and dbengine come from the [`AWS::SecretsManager::SecretTargetAttachment`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html) resource. This resource exist only to avoid a circular dependency when creating a DB together with a secret. The DB needs the secret and the secret to be "usable" needs the DB connection info.

> The `AWS::SecretsManager::SecretTargetAttachment` resource completes the final link between a Secrets Manager secret and the associated database. This is required because each has a dependency on the other.

Conceptually a `AWS::SecretsManager::SecretTargetAttachment` is just a secret and it's implemented like that in the CDK:

https://github.com/aws/aws-cdk/blob/9f35104d2e6612032f2c6d8d7193baddceb30d15/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L388-L391

This allows to `ref` the secret (in fact the secret attachment) knowing that it will contain the connection information. This is needed for secret rotation for example.

I think the following happens here: when you udpate the `AWS::SecretsManager::Secret` resource by changing the `ExcludeCharacters` the secret gets updated and here it means regenerated (and this type of update [does not require a CF resource replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html#cfn-secretsmanager-secret-generatesecretstring)). But the `AWS::SecretsManager::SecretTargetAttachment` does not change so from a CF perspective it doesn't run again.

I haven't tried to reproduce it yet but does the `AWS::RDS::DBInstance` gets updated with the new master credentials when you update `ExcludeCharacters`? I'm not sure. The only solution would be to perform a secret rotation then?

**Comment by nija-at** [comment]
Thanks for the explanation @jogold.

@mjslane - can you add the following piece of code to the code snippet in your reproduction steps. This should replace the [`AWS::Secrets::SecretTargetAttachment`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html) resource type underneath and thereby get the output as you would expect - 

```ts
const secretAttachment = dbSecret.node.tryFindChild('Attachment') as SecretTargetAttachment;
const cfnAttachment = secretAttachment.node.defaultChild as CfnSecretTargetAttachment;
cfnAttachment.overrideLogicalId('AttachmentLogicalId');
```

However, I suspect @jogold is right and this may not actually change the Database password. Could you try this out and confirm if it works, and actually changes the Database password as you would expect?

**Comment by mjslane** [comment]
We tried this, but in our stack the the secret ref is exported so other stacks can use it so we're getting an error on deleting the export.

`stack-name Export secret-ref cannot be deleted as it is in use by other-stack`

We also managed to trigger a similar change when adding a new security group to connect to the RDS instance using the instance.connections.allowFrom(securityGroup, port) method. It didn't change the password but did delete everything other than the password and username.

**Comment by mjslane** [comment]
As an update, when we added the security group rule the password for the database wasn't changed but the password value in the secret was changed. This meant that new instances of our services couldn't connect to the database as the credentials in secret manager were wrong.

**Comment by nija-at** [comment]
@skinny85 and I had a discussion around this yesterday.

I believe the correct solution here is that whenever a change occurs to the `AWS::SecretsManager::Secret` resource that can modify the password, both the associated `AWS::SecretsManager::SecretAttachment` and `AWS::SecretsManager::SecretRotation` should be mutated. 

Mutating the `SecretAttachment` resource would ensure that the connection string generated by this that includes the dbname, engine, port, password, etc. is re-generated with the new password.

Mutating the `SecretRotation` resource would trigger a new asynchronous password rotation (needs to be confirmed) and keep the password in the Database and the Secret in sync.
However, there is likely going to be a period of time where the passwords are out of sync.

All of this still is likely to work but still needs verification.

**Comment by jogold** [comment]
@nija-at @skinny85  how about overriding the logical id of the `CfnSecret` with a hash of its props? This way it always gets replaced and the rest follows?

```ts
const resource = new secretsmanager.CfnSecret(this, 'Resource', {
  description: props.description,
  kmsKeyId: props.encryptionKey && props.encryptionKey.keyArn,
  generateSecretString: props.generateSecretString || {},
  name: this.physicalName,
});
const logicalId = crypto.createHash('sha256')
  .update(JSON.stringify(props.generateSecretString))
  .digest('hex');
resource.overrideLogicalId(logicalId);
```

**Comment by jogold** [comment]
Also if you're using secret rotation it doesn't make sense to override excluded characters because the secret rotation application has its own hard coded set of excluded characters:

https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/6ec39bbdd5867ba7d0c1d5ac2170278fe55fbddd/SecretsManagerRDSOracleRotationSingleUser/lambda_function.py#L116

https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/6ec39bbdd5867ba7d0c1d5ac2170278fe55fbddd/SecretsManagerRDSMySQLRotationSingleUser/lambda_function.py#L116

**Comment by skinny85** [comment]
> @nija-at @skinny85 how about overriding the logical id of the `CfnSecret` with a hash of its props? This way it always gets replaced and the rest follows?
> 
> ```ts
> const resource = new secretsmanager.CfnSecret(this, 'Resource', {
>   description: props.description,
>   kmsKeyId: props.encryptionKey && props.encryptionKey.keyArn,
>   generateSecretString: props.generateSecretString || {},
>   name: this.physicalName,
> });
> const logicalId = crypto.createHash('sha256')
>   .update(JSON.stringify(props.generateSecretString))
>   .digest('hex');
> resource.overrideLogicalId(logicalId);
> ```

Yes, this is exactly how we thought to approach it :)

**Comment by skinny85** [comment]
> Also if you're using secret rotation (the one from the CDK) it doesn't make sense to override excluded characters because the secret rotation application has its own hard coded set of excluded characters:
> 
> https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/6ec39bbdd5867ba7d0c1d5ac2170278fe55fbddd/SecretsManagerRDSOracleRotationSingleUser/lambda_function.py#L116
> 
> https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/6ec39bbdd5867ba7d0c1d5ac2170278fe55fbddd/SecretsManagerRDSMySQLRotationSingleUser/lambda_function.py#L116

Hmmm... in that case, I wonder whether we should have some validation for that case? Because the fact that this property will be ignored might catch people off guard...

**Comment by jogold** [comment]
> Hmmm... in that case, I wonder whether we should have some validation for that case? Because the fact that this property will be ignored might catch people off guard...

It's currently [not possible](https://github.com/aws/aws-cdk/blob/cb71f340343011a2a2de9758879a56e898b8e12c/packages/%40aws-cdk/aws-rds/lib/instance.ts#L776-L778) from the code to use the "managed" rotation if the secret was not created inside the L2 and in this case it's a [`DatabaseSecret`](https://github.com/aws/aws-cdk/blob/cb71f340343011a2a2de9758879a56e898b8e12c/packages/%40aws-cdk/aws-rds/lib/instance.ts#L862-L868) with the same set of excluded characters. The issue here is when someone tries to override CFN properties...

> Yes, this is exactly how we thought to approach it :)

>> Mutating the SecretRotation resource would trigger a new asynchronous password rotation (needs to be confirmed) and keep the password in the Database and the Secret in sync.

Since secret rotation is optional, I was suggesting to mutate the secret itself. This will for sure update the password in the DB (via CF).

But with the fact that the secret is created inside the L2, I'm actually not sure anymore: either the user chooses for a "managed" experience (secret and secret rotation) or he must pass a `cdk.SecretValue` for the `masterUserPassword` and implement his own rotation with `addRotationSchedule()` from `aws-secretsmanager`?
