### ISSUE TITLE
[@aws-cdk/aws-autoscaling] Introduce an AutoScalingGroupRef class/interface

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#752]
To make it aligned with other L2 (CodeDeploy [Application](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codedeploy/lib/application.ts#L28) and [DeploymentGroup](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codedeploy/lib/deployment-group.ts#L44) can be used for reference).

**Comment by rix0rrr** [comment]
As a note, we're switching to interfaces: https://github.com/awslabs/aws-cdk/issues/742
