### ISSUE TITLE
ECS on Fargate upgrade service platform_version to 1.4.0 - Task failed to start

### ISSUE THREAD

**Issue by nodesocket** [aws/aws-cdk#7529]
Running our application on ECS Fargate using service `platform_version: 1.3.0` successfully. I tried to upgrade to the newest `platform_version: 1.4.0`. When I did this, the new tasks are failing to start only with the error message `Task failed to start`.

Any ideas what would could cause this? Any way to get further details?

**Comment by pkandasamy91** [comment]
@nodesocket are you able to see the service in the AWS console?

**Comment by nodesocket** [comment]
@pkandasamy91 yes, the services are showing. The tasks fail to start only with the message `Task failed to start`.

**Comment by pkandasamy91** [comment]
@nodesocket just to confirm, nothing else has changed other than the fargate version? Also, what constructs are you using?

**Comment by nodesocket** [comment]
@pkandasamy91 nothing else changed. What do you mean constructs?

**Comment by pkandasamy91** [comment]
> @pkandasamy91 nothing else changed. What do you mean constructs?

Are you using the CDK to implement this?
