### ISSUE TITLE
If no home directory exist on host, the CDK will fail 

### ISSUE THREAD

**Issue by NetaNir** [aws/aws-cdk#7530]
The CDK creates an account cache in: 

```
~/.cdk/cache
```
When running in an environment that does no have a home directory, such as aws-lambda, attempting to create the cache will fail `synth`/`deploy`/`diff`.

### Reproduction Steps
Execute the CDK inside a lambda which defines AWS credentials using AWS environment variables.

### Error Log

```
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-west-2
Resolving default credentials
Looking up default account ID from STS
Default account ID: xxxxx
EACCES: permission denied, mkdir '/home/xxxx'
Error: EACCES: permission denied, mkdir '/home/xxx'
2020-04-23T03:11:28.801Z        fc4cb3ae-5a84-1734-2972-7f101accf659    INFO    Error: child exited with code 1
    at ChildProcess.<anonymous> (/var/task/node_modules/await-spawn/index.js:28:21)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 1,
  stderr: ''
}
```

### Environment

  - **CLI Version      :** 1.34
  - **Framework Version:** 1.34
  - **OS               :** 
  - **Language         :** typescript

### Other

A way around this is setting the `HOME` environment variable to a directory which exist, and the user has permission on (the user running `cdk`), courtesy of @rhboyd:
```
const main = async () => {
  process.env.HOME = '/tmp';
  const bl = await spawn('node', ['node_modules/aws-cdk/bin/cdk.js', '--app', '"node dist/sample-app.js"', 'synth', '--verbose', '--output', '/tmp', '--no-staging'], { stdio: ['pipe', 'pipe', process.stderr] });
  console.log(bl.toString())
}
```

**Comment by richardhboyd** [comment]
### possible fix:

A flag for where to put the things we usually put in ~/.cdk

**Comment by DerkSchooltink** [comment]
Possibly related: #4201

The `CDK_HOME` is supposed to be the flag @richardhboyd is suggesting I think. But there's a bug that prevents it from being honoured. 

Ideally you could just set that environment variable in your Lambda configuration :)

**Comment by shivlaks** [comment]
@NetaNir @richardhboyd  are you okay with me closing this one as it's duplicated by #4201 ?

I'll see if I can resurrect #4217 which had an implementation that was getting there.

**Comment by rix0rrr** [comment]
`CDK_HOME`, sounds good, and otherwise since this is an opportunistic cache, we also simply shouldn't fail if we can't create the dir.

**Comment by rhboyd** [comment]
I tried setting the Lambda Environment variables via the Lambda Configuration for both CDK_HOME and HOME. Neither worked. I had to explicitly set it in my code.
