### ISSUE TITLE
📊Tracking: Amazon RDS

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#7543]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

Amazon Relational Database Service (Amazon RDS) is a web service that makes it easier to set up, operate, and scale a relational database in the cloud. It provides cost-efficient, resizable capacity for an industry-standard relational database and manages common database administration tasks. 

[AWS Docs](https://docs.aws.amazon.com/rds/index.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html) for more implementation details.

### Project board

https://github.com/aws/aws-cdk/projects/5

--- 
This is a  📊Tracking Issue

**Comment by aripalo** [comment]
Hoping that this RDS high-level construct would support [RDS Proxy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbproxy.html) once it comes into GA.

**Comment by aripalo** [comment]
I think the RDS high-level construct should also support Aurora IAM based authentication: https://github.com/aws/aws-cdk/issues/1558

**Comment by skinny85** [comment]
We now also have a project board specifically for RDS: https://github.com/aws/aws-cdk/projects/5

Feel free to check that out for the most up-to-date status!

**Comment by shivlaks** [comment]
his tracking issue is being resolved as the RDS module is now `GA` (stable)
