### ISSUE TITLE
Autoscaling Groups Support more than a single Target

### ISSUE THREAD

**Issue by sd3z** [aws/aws-cdk#7544]
https://github.com/aws/aws-cdk/blob/cbe735e4c5a740c7e6f304bcd9aa867e4b44a9d8/packages/%40aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts#L561

I'm not sure if I've implemented this correctly, but I have five Code Deploy applications using 5 different Target Groups that I would like to attach to a single AutoScaling Group

When I attempt to attach a second ApplicationTargetGroup to the same asg it fails with the error _Cannot add AutoScalingGroup to 2nd Target Group_, but if I jump into the console I can attach multiple Targets. 

```
appWebTargetGroup = new ApplicationTargetGroup(this, 'WebTargetGroup', {}); 
appAPITargetGroup = new ApplicationTargetGroup(this, 'ApiTargetGroup', {}); 

this.asg.attachToApplicationTargetGroup(appWebTargetGroup );
this.asg.attachToApplicationTargetGroup(appAPITargetGroup );
```

If I was to comment out the line attaching the appAPITargetGroup, everything works as expected.

**Comment by sd3z** [comment]
Actually it looks like this is a bug and the work around was mentioned [here](https://github.com/aws/aws-cdk/issues/5667)

**Comment by NetaNir** [comment]
duplicate https://github.com/aws/aws-cdk/issues/5667
