### ISSUE TITLE
Doc topic about logging in cdk apps

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#755]
you can use console.error, And you can also use this.addWarning and this.addError to attach errors/warnings to the stack so they will be printed during “cdk synth”
Probably worth a documentation topic

Console.log won’t work due to stdout being used for synthesis

**Comment by jungseoklee** [comment]
+1, this is definitely helpful for users.

**Comment by Rukenshia** [comment]
Working on this 👍

**Comment by Doug-AWS** [comment]
Thanks!

**Comment by Doug-AWS** [comment]
Please mention me (Doug-AWS) if you think I should add some info into the guide.

**Comment by Jerry-AWS** [comment]
Added this to the CDK Guide project. https://github.com/awsdocs/aws-cdk-guide/issues/99

This can be closed.
