### ISSUE TITLE
📊Tracking: AWS StepFunctions Tasks

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#7550]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

[AWS Docs](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html) for more implementation details.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by shivlaks** [comment]
Both Step Functions & Step Functions Tasks modules are being tracked together in #6489
