### ISSUE TITLE
📊Tracking: AWS S3 Deployment

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#7552]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

[AWS Docs](https://docs.aws.amazon.com/s3/index.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html) for more implementation details.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by jonny-rimek** [comment]
If your target folder is empty (dist/) the deployment fails, but doesn't get rolled back, this is something that should probably be adressed.
