### ISSUE TITLE
Auto scaling support for SageMaker endpoints

### ISSUE THREAD

**Issue by elvinx** [aws/aws-cdk#7559]
I am trying to add an auotscaling policy for SageMaker endpoints.

I found out about [application auto scaling module](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-applicationautoscaling-readme.html) which says:

`As a CDK user, you will probably not have to interact with this library directly; instead, it will be used by other construct libraries to offer AutoScaling features for their own constructs.`

However, when I check `aws_cdk.aws_sagemaker` module I couldn't find anything that would allow me to define autoscaling policy for my endpoints.

My question:
Is this a missing feature and/or currently being worked on ? If not, should I use the `aws-applicationautoscaling` as a workaround until this feature is developed?

Thanks in advance.

**Comment by NetaNir** [comment]
I agree that this note is confusing, so I'm marking this as a documentation issue.

As seen in the lambda [provision concurrency example](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-applicationautoscaling#lambda-provisioned-concurrency-auto-scaling), you create a `ScalableTarget` and set the tracking metric to be the metric you would like to track, the metric must be one of the `PredefinedMetric`. 
For sage maker, the current available metric is [`SageMakerVariantInvocationsPerInstance`](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html). 

@elvinx does this make sense? I will also add some more Example to the README.
