### ISSUE TITLE
Artifacts via extraInputs on CodeBuildAction dont show up

### ISSUE THREAD

**Issue by swyp-de** [aws/aws-cdk#7561]
I have two sources in my codepipeline project, S3 and Github. Those two sources are wired up in CodeBuildAction via **input**  and **extraInputs** properties. That is, Github as **input** and S3 as **extraInputs**.

During build, only the content of the **input** property shows up. If i flip the input, the content of the other artifact show up, so its not an artifact issue per se.

Perhaps i am missing the intent of the property extraInputs but i ve seen tests in CDK repo which worked nearly the same. Unfortunately not much documentation on that prop out there.

### Reproduction Steps

Create a GitHub Source:
```
githubSourceAction = new codepipeline_actions.GitHubSourceAction({
  ...
  output: sourceOutput,
)}
```

Create a S3 Source:
```
s3SourceAction = new codepipeline_actions.S3SourceAction({
  ...
  output: source2_Output
)}
```

Wiring together:

```
buildAction = new codepipeline_actions.CodeBuildAction({
   ...
  input: sourceOutput,
  extraInputs: [source2_Output],
});
```

### Error Log

No error but just missing the artifact content in **extraInputs** during build.

### Environment

  - **CDK Version      : 1.34.1 (build 7b21aa0)**
  - **OS               : Mac OS X latest**
  - **Language         : typescript**

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @swyp-de ,

the way extra inputs work in CodeBuild is:

* The build starts in the checked out directory of the primary source (`input` in the `CodeBuildAction`).
* The path to the directory where the additional inputs are available are stored in the `CODEBUILD_SRC_DIR_<name_of_input_artifact>` environment variables.

See [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codebuild-readme.html#secondary-sources-and-artifacts) for more info.

Thanks,
Adam

**Comment by swyp-de** [comment]
Yep sorry for noise. I was irritated because i wasnt aware that shell starts at "00" subfolder and i just can go back in hierarchy use "01".

**Comment by swyp-de** [comment]
Typescript inline documentation for the property would be nice btw.

**Comment by EhsanHerai** [comment]
@skinny85 
can I access `CODEBUILD_SRC_DIR_<name_of_input_artifact>` env inside my CDK source code
