### ISSUE TITLE
Allow creating NodejsFunction singleton lambdas

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#7564]
I'd like to be able to create a singleton `NodejsFunction` but, because `lambda.SingletonFunction` is a separate constructor, not exposed via `lambda.Function` properties, it looks like I am not able to do this.

### Use Case

I'm creating a CustomResource to work around #5343 and I'd like to use Typescript to create this function. The [example I'm working off of](https://github.com/aws/aws-cdk/blob/d1b3b750cec3c514df6690e8baeffa7e9b260500/packages/%40aws-cdk/aws-lambda/lib/log-retention.ts#L47) uses `lambda.SingletonFunction`, which I'd like to use, but alongside the build process provided by `NodejsFunction`.

### Proposed Solution

I can think of two ways to do this, one that would introduce a breaking change and one that would not.

**Breaking Change**: We could deprecate `lambda.SingletonFunction` and, instead, make singleton configuration part of `lambda.FunctionProps`. If we could figure out how to do this since `NodejsFunction` extends `lambda.Function`, `NodejsFunction` would "just work" for creating singleton functions.

**Non-Breaking Change**: We could introduce a `NodejsSingletonFunction`, which extends `lambda.SingletonFunction`.

### Other

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
It's trivial to implement a singleton:

```ts
export class MyConstruct extends Construct {
  public static getOrCreate(scope: Construct): MyConstruct {
    const uniqueid = 'foobarbaz';
    const stack = Stack.of(this);
    return stack.node.tryFindChild(uniqueid) as MyConstruct ?? new MyConstruct(stack, uniqueid);
  }

  // ...
}
```

Also, did you take a look at the [custom resource provider framework](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#provider-framework)?

Closing for now.

**Comment by ilia-luk** [comment]
@eladb isn't the whole point of CDK is that I wouldn't need to do those "trivial" undocumented implementations my self?, I mean, to be honest, for someone new to CDK it makes no sense, at least not for me and frankly I was expecting exactly what @blimmer suggested to exist :)
