### ISSUE TITLE
Conflicting versions of @aws-cdk/core in type system: previously loaded 0.0.0, trying to load 1.34.1

### ISSUE THREAD

**Issue by hossain-rayhan** [aws/aws-cdk#7567]
I was trying the full clean build following the guidelines from [Contribution Guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#full-clean-build). After running for one hour it ended up with the following error message- 
`decdk: Error: Conflicting versions of @aws-cdk/core in type system: previously loaded 0.0.0, trying to load 1.34.1`

### Reproduction Steps
$ git clone https://github.com/aws/aws-cdk.git
$ cd aws-cdk
$ ./install.sh
$ yarn build

### Error Log
monocdk-experiment: found 0 vulnerabilities
monocdk-experiment: compiling...
decdk: Error: Conflicting versions of @aws-cdk/core in type system: previously loaded 0.0.0, trying to load 1.34.1
decdk:     at TypeSystem._loadModule (/Users/hrayhan/Work/cdk-fresh/aws-cdk/node_modules/jsii-reflect/lib/type-system.js:83:27)
decdk:     at async TypeSystem._loadModule (/Users/hrayhan/Work/cdk-fresh/aws-cdk/node_modules/jsii-reflect/lib/type-system.js:106:17)
decdk:     at async TypeSystem.loadModule (/Users/hrayhan/Work/cdk-fresh/aws-cdk/node_modules/jsii-reflect/lib/type-system.js:65:21)
decdk:     at async Object.loadTypeSystem (/Users/hrayhan/Work/cdk-fresh/aws-cdk/packages/decdk/lib/util.js:24:9)
decdk:     at async main (/Users/hrayhan/Work/cdk-fresh/aws-cdk/packages/decdk/bin/decdk-schema.js:7:24)
decdk: npm ERR! code ELIFECYCLE
decdk: npm ERR! errno 1

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :** macOS 10.14.6
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@hossain-rayhan - I just created a fresh clone and don't seem to be running into this issue. were you able to get past it or is it still an issue?

**Comment by MrArnoldPalmer** [comment]
This was solved. It appears there was a conflict with the some globally installed aws-cdk modules.

**Comment by hossain-rayhan** [comment]
Running `git clean -fdx`  solved my issue. Thanks.
