### ISSUE TITLE
`this` keyword in cloud dev kit is incorrect type

### ISSUE THREAD

**Issue by SeanDez** [aws/aws-cdk#7578]
### The Question

I have read that `this` may point to the wrong type definition if the cdk package dependencies are different versions. In the ghostbin below I changed them all to 1.33.1 to match the core cdk package and then ran `npm i` to reinstall the full manifest list.

After doing this, `this`, passed into the `s3.Bucket` constructor, is still linted. See here and please tell me what the issue is: https://ghostbin.co/paste/ja3ue  Thank you

### Environment

  - **CDK CLI Version:** 1.33.1 build 8ad4d34)
  - **Module Version:** 1.33.1
  - **OS:** Lubuntu 18.04
  - **Language:** Typescript

**Comment by shivlaks** [comment]
@SeanDez you have some caret dependencies `^` and others are fixed. Drop the caret for `aws-cloudfront` and `aws-s3-deployment` and let me know how it goes!

**Comment by SeanDez** [comment]
@shivlaks yes, that has cleared the issue, thank you!
