### ISSUE TITLE
support custom values in API key

### ISSUE THREAD

**Issue by gandlusn** [aws/aws-cdk#7584]
I want to create API key with custom value for API gateway usage plan, but as of now I don't see a attribute to set value of the API[1], I am aware that CDK converts code into CF template, and Cloud Formation has Value attribute defined in it[2], then my question is is there a way to create custom-api key in API Gateway using CDK

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/api-key.ts

[1]. https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/api-key.ts
[2]. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html#cfn-apigateway-apikey-generatedistinctid

**Comment by gandlusn** [comment]
1. what you’re trying to do?
Ans: I want to create a API Key using AWS CDK, in which I wants to provide a custom value, similar to cloud formation template provided below, that creates a API Key, with the Custom value provided by user in Properties.

ApiKey:
  Type: 'AWS::ApiGateway::ApiKey'
  DependsOn:
    - TestAPIDeployment
    - Test
  Properties:
    Name: TestApiKey
    Description: CloudFormation API Key V1
    Enabled: 'true'
    StageKeys:
      - RestApiId: !Ref RestApi
        StageName: Test
     Value: ‘somenew20characterkey’

How can I replicate same thing in AWS CDK.

2. what you expect?
If possible can you share a sample code to implement this, or share some articles that I can follow to accomplish this task.

Thank you

**Comment by nija-at** [comment]
Looks like we don't support this value in the CDK just yet. Marking this as a feature request.

Until then, you can use [overrides](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw) to add this to the underlying cfn layer. This should work as a workaround here.

**Comment by nija-at** [comment]
Turns out we already have an issue open for this - https://github.com/aws/aws-cdk/issues/3233. 
Resolving as duplicate.
