### ISSUE TITLE
Amplify Domain always gets a subdomain

### ISSUE THREAD

**Issue by sferencik** [aws/aws-cdk#7590]
The following code creates/associates an Amplify Domain with an Amplify Branch:
```
import * as amplify from '@aws-cdk/aws-amplify';

new amplify.Domain(this, 'my-app-domain-dev', {
    app,
    'foo.com',
    subDomains: [
        {
            branch: 'dev',
            prefix: 'dev',
        }
    ]
});
```

With `foo.com` hosted in Route53, I end up with https://dev.foo.com pointing to the Amplify "dev" branch. So far so good.

However, it's not possible to associate the _root_ domain to a branch. When I remove the subdomain prefix:
```
new amplify.Domain(this, 'my-app-domain-dev', {
    app,
    'foo.com',
    subDomains: [
        {
            branch: 'dev',
        }
    ]
});
```

I still end up with https://dev.foo.com, as opposed to the expected https://foo.com. (The subdomain is automatically derived from the branch name.)

Using `prefix: ""` results in the same:
```
new amplify.Domain(this, 'my-app-domain-dev', {
    app,
    'foo.com',
    subDomains: [
        {
            branch: 'dev',
            prefix: '',
        }
    ]
});
```

In contrast, associating the root domain is possible both in
* the Amplify Console: 
![image](https://user-images.githubusercontent.com/808557/80189070-63325e00-8612-11ea-8937-ba0d43c5cd22.png)

* the AWS CLI (`aws amplify create-domain-association --app-id ... --domain-name foo.com --sub-domain-settings "branchName=dev,prefix="`; see [here](https://docs.aws.amazon.com/cli/latest/reference/amplify/create-domain-association.html))

### Environment

  - **CLI Version      :** `cdk --version`: 1.28.0 (build 5f2bbc6)
  - **Framework Version:** 1.28.0
  - **OS               :** Windows 10
  - **Language         :** Node JS

--- 

This is :bug: Bug Report

**Comment by sferencik** [comment]
I believe this is caused by [`renderSubDomainSettings()`](https://github.com/aws/aws-cdk/blob/461f6df237a165a76880449c87e66beaa51b822f/packages/%40aws-cdk/aws-amplify/lib/domain.ts#L115) defaulting any falsy value of subdomain prefix to the branch's name.

As a result, both an omitted prefix and an empty prefix (`""`) result in prefix = "dev" (or whatever the branch name is).

To minimise breaking changes, I propose that
* an omitted prefix would still default to the branch name
* a prefix of `""` would stay as empty string (if users are relying on this fallback, they're more likely to be omitting the prefix than explicitly specifying it as empty)

Plus add documentation.

**Comment by jogold** [comment]
@sferencik can you confirm that it deploys successfully in CloudFormation when the prefix is an empty string (`''`). You can use the following override to confirm this:

```ts
const domain = new amplify.Domain(...);
const cfnDomain = domain.node.defaultChild as amplify.CfnDomain;
cfnDomain.addPropertyOverride('SubDomainSettings.0.Prefix', '');
```
(drop the `as amplify.CfnDomain` if using JavaScript)

**Comment by sferencik** [comment]
Yes it deploys. I've now also verified that aws-sdk can achieve the same:
```
amplify.createDomainAssociation({
  appId,
  domainName,
  subDomainSettings: [{
    prefix: '',
    branchName,
  }],
})
```

Thanks for the tip with `CfnDomain`; I'll try it out.

**Comment by sferencik** [comment]
Thanks, @jogold. That work-around works like charm, and it's quite instructive as well. Thanks also for the fix.
