### ISSUE TITLE
Deprecate S3 Reduced Redundancy functionality

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#7609]
Per AWS, they are phasing out S3 reduced redundancy storage and already increased its price to deter usage - https://mysteriouscode.io/blog/aws-s3-storage-classes-pricing-is-not-what-you-think/

I think that CDK should discourage its usage.

### The Question

Can we mark the related S3 functionality as "deprecated" with a description as to why? Customer will actually pay more for the product, while getting lower durability and a migration requirement at some point in the future.

### Environment
N/A

**Comment by iliapolo** [comment]
Hi @flemjame-at-amazon - Thanks for bringing this to our attention.

We will consult internally and decide on the correct course of action. Stay tuned.
