### ISSUE TITLE
dynamodb: Nested stack replicationRegions Tags must have length less than or equal to 50

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#7612]
Now, I receive a validation error from CloudFormation during deploy when trying to enable DynamoDB Global Tables replication.

### Reproduction Steps

```
import { Construct, Stack, StackProps } from '@aws-cdk/core';
import { NestedStack } from '@aws-cdk/aws-cloudformation';
import { Table, AttributeType } from '@aws-cdk/aws-dynamodb';

export class DynamoNestedStack extends NestedStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new Table(this, 'MyTable', {
      partitionKey: { name: 'pk', type: AttributeType.STRING },
      replicationRegions: ['us-east-2', 'us-west-1'],
    });
  }
}

export class CdkNested6726Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new DynamoNestedStack(this, 'DynamoStack');
  }
}
```

### Error Log

During `cdk deploy` CDK cli reports:

```
MyStack: creating CloudFormation changeset...

MyStack failed: Error [ValidationError]: Tags must have length less than or equal to 50
    at Request.extractError (<REDACTED>/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (<REDACTED>/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (<REDACTED>/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (<REDACTED>/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (<REDACTED>/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (<REDACTED>/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at <REDACTED>/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (<REDACTED>/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (<REDACTED>/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (<REDACTED>/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Tags must have length less than or equal to 50',
  code: 'ValidationError',
  time: 2020-04-26T21:50:33.518Z,
  requestId: 'd9d5932a-9997-449b-b360-c387e2e30f89',
  statusCode: 400,
  retryable: false,
  retryDelay: 81.98982718192272
}
Tags must have length less than or equal to 50
```

### Environment

  - **CLI Version      : 1.35.0**
  - **Framework Version: 1.35.0**
  - **OS               : macOS**
  - **Language         : TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by cmckni3** [comment]
New issue based on #6726.

Let me know if you have trouble replicated. I copied the sample I used in #6726 but it may need to be updated.

**Comment by jogold** [comment]
In which stack is this error first reported exactly (parent, dynamodb stack or replication provider stack)? Are you running `cdk deploy` with `--tags`?

**Comment by cmckni3** [comment]
I am not deploying with `cdk deploy --tags`. I am using `cdk deploy --profile <profile name>`.

I am using aspects to apply tags to resources including the Nested Stacks from the root stack.

**Comment by cmckni3** [comment]
Can't really tell which stack it comes from due to #6402

**Comment by jogold** [comment]
> Can't really tell which stack it comes from due to #6402

When you look in the console?

**Comment by cmckni3** [comment]
Is there a way to see change set validation errors in CloudFormation console/cli? I think I would have to try creating the changeset and attempting to run it in the console to see the error message.

**Comment by cmckni3** [comment]
> Is there a way to see change set validation errors in CloudFormation console/cli? I think I would have to try creating the changeset and attempting to run it in the console to see the error message.

There are no stack events because changeset validation failed.

**Comment by jogold** [comment]
Can you share your CF template?

**Comment by cmckni3** [comment]
Not publicly.

I was able to use the example above to deploy to Commercial (us-east-1).

Errors might be GovCloud related (us-gov-west-1).

I am trying to deploy the example above with some tags attached to GovCloud.

**Comment by cmckni3** [comment]
Hmm, my example above succeeds with in Commercial and GovCloud.

Some notes:

- Root stack contains 6 nested stacks which each receive 6 Tags.
- DynamoDB Nested Stack gets the 6 Tags from parent stack.
- Replication provider is a nested stack of the DynamoDB nested stack

I am using the CloudFormation console to generate a change set to see the error.

**Comment by cmckni3** [comment]
Creating a change set manually in the console from the CDK generated templates works.

**Comment by cmckni3** [comment]
Stack trace added to description

**Comment by jogold** [comment]
I would say this is not linked to DynamoDB or `replicationRegions`.

The error message seems to indicate that a resource has more than 50 tags applied to it. Since a `AWS::Cloudformation::Stack` (`NestedStack`) propagates the tags to the resources created in the stack and that there are 6 level of nesting, somehow somewhere it adds up to more than 50.

**Comment by cmckni3** [comment]
> I would say this is not linked to DynamoDB or `replicationRegions`.

I agree

The 

> error message seems to indicate that a resource has more than 50 tags applied to it. Since a AWS::Cloudformation::Stack (NestedStack) propagates the tags to the resources created in the stack and that there are 6 level of nesting, somehow somewhere it adds up to more than 50 (either in the template or as CF understands it).
> 
> Are you using a custom aspect?

Yes, I have a custom aspect that applies a description to Stacks/Nested Stacks. Tags use the CDK builtin Tag aspect (I apply them on the root stack).

Not sure why the stack deploys manually via CloudFormation with the same templates though. My instincts say it's something with assets maybe (since I populated the parameters to manually deploy via console). No idea though.

--------

Here's a layout of the nested stacks:

* Root Stack
  * Stack A
  * Stack B
  * Stack C
  * Stack D
  * Stack E
  * DynamoDB Stack
    * DynamoDB replication stack

**Comment by cmckni3** [comment]
Closing since this functionality should land in CloudFormation soon.

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/57

**Comment by cmckni3** [comment]
Let me know if you don't agree with closing.
