### ISSUE TITLE
Cannot call request validator options multiple times. 

### ISSUE THREAD

**Issue by durja** [aws/aws-cdk#7613]
Calling the constructor for RequestValidatorOptions multiple times gives an error 

There is already a Construct with name 'validator' in RestApi

### Reproduction Steps

`

        resource1.add_method(
            http_method='POST',
            integration=xxxIntegration,
            request_parameters={
                'method.request.header.passcode': True,
                'method.request.header.message': True
            },
            request_validator_options=_apigw.RequestValidatorOptions(validate_request_parameters=True, request_validator_name='POST-r1-validator')
        )

        resource2.add_method(
            http_method='POST',
            integration=yyyIntegration,
            request_parameters={
                'method.request.header.passcode': True,
                'method.request.querystring.id': True
            },
            request_validator_options=_apigw.RequestValidatorOptions(validate_request_parameters=True,request_validator_name='POST-r2-validator') 
        )

`

### Environment

  - **CLI Version      :1.35.1
  - **Framework Version:1.35.1
  - **OS               : Mac Mojave 
  - **Language         : Python

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Thanks for filing this @durja. This is, in fact, a bug on the CDK.

You can workaround this by using the `requestValidator` property.

**Comment by logemann** [comment]
Also ran into this bug. Dont get how to workaround it with a completely different property. How can i mark my params to validate with  requestValidator ?

**Comment by monkeytronics** [comment]
I'm on cdk version 1.91.0. 

I'm sorry. I'm not understanding the solution. I've modified my code to :

 requestValidatorOptions: {
        requestValidator: uniqueId,
        requestValidatorName: uniqueId,
        validateRequestBody: false,
        validateRequestParameters: true
      },

And it still throws the same error: `There is already a Construct with name 'validator' in RestApi [sn-dev]`  I'm aware that requestValidator doesn't actually exist on the requestValidatorOptions property. Would you be able to offer an example solution please?

**Comment by fuzzy28** [comment]
@monkeytronics changing the implementation throws another error

**Caused by: java.lang.NullPointerException: restApi is required**

**Comment by EHadoux** [comment]
Hi folks, will this be fixed eventually?

**Comment by oanguin** [comment]
Was able to get around this by creating a validator object.

```javascript
      const queryStringValidator = new apigateway.RequestValidator(
      scope,
      "validator",
      {
        restApi: api,
        requestValidatorName: "validator",
        validateRequestBody: false,
        validateRequestParameters: true,
      }
    );

    resource.addMethod(
      "GET",
      new apigateway.LambdaIntegration(this.lambdaFunc),
      {
        requestParameters: {
          "method.request.querystring.attribute": true,
        },
        requestValidator: queryStringValidator,
      }
    );
```

**Comment by bestickley** [comment]
Not the most elegant solution, but here is what I'm using:

```ts
const getMethodOptions = (model?: Model): MethodOptions => {
      const methodOptions: MethodOptions = {
        authorizer: tokenAuthorizer,
        requestParameters: {
          "method.request.header.authorization": true,
        },
        requestModels: {},
        // https://github.com/aws/aws-cdk/issues/7613
        requestValidator: new RequestValidator(
          this,
          "AppApiRequestValidator" + this.requestValidatorSuffix,
          {
            restApi: appApi,
            validateRequestParameters: true,
            validateRequestBody: Boolean(model),
          }
        ),
      };
      this.requestValidatorSuffix++;
      if (model) {
        return {
          ...methodOptions,
          requestModels: { "application/json": model },
        };
      }
      return methodOptions;
    };
```

**Comment by therealvio** [comment]
Hi there 👋 

It has been about over a year and a half since this has been reported, what is the status on this?

Thanks!

**Comment by codermarcos** [comment]
I'm facing a related problem:

![image](https://github.com/user-attachments/assets/03dc0ab1-9646-48d4-9c66-4a1a17ec8234)
