### ISSUE TITLE
Fail to create FargateProfile - Missing permissions for `ec2:DescribeSubnets`

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#7614]
We just [annouced](https://aws.amazon.com/tw/about-aws/whats-new/2020/04/eks-adds-fargate-support-in-frankfurt-oregon-singapore-and-sydney-aws-regions/) the Fargate support for Amazon EKS in 4 additional regions and I was trying to deploy a simple EKS+Fargate cluster to them ended up missiong permissions failure in `eu-central-1`, `ap-southeast-1` and `ap-southeast-2`.

### Reproduction Steps

```ts

import * as cdk from '@aws-cdk/core';
import * as eks from '@aws-cdk/aws-eks';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as iam from '@aws-cdk/aws-iam';

export class EksfgStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'Vpc', {
        maxAzs: 3,
        natGateways: 1
      });

    const mastersRole = new iam.Role(this, 'AdminRole', {
      assumedBy: new iam.AccountRootPrincipal()
    });

    const cluster = new eks.Cluster(this, 'Cluster', {
      vpc,
      mastersRole
    });

    cluster.addFargateProfile('FargateProfile', {
      selectors: [
        { namespace: 'default' },
        { namespace: 'kube-system' },
      ]
    })

    new cdk.CfnOutput(this, 'Region', { value: this.region })

  }
}
```

### Error Log
```
Cluster/fargate-profile-FargateProfile/Resource/Default (ClusterfargateprofileFargateProfileA6BADBA5) Failed to create resource. Error: Missing permissions for `ec2:DescribeSubnets` action
```

<img width="969" alt="圖片" src="https://user-images.githubusercontent.com/278432/80325398-8efa5180-8867-11ea-999c-bd1d7cc80d4f.png">

### Environment

  - **CLI Version      :** 1.35.0
  - **Framework Version:** 1.35.0
  - **OS               :** Mac OS X
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by river0825** [comment]
+1
I have the same issue too

**Comment by pahud** [comment]
this is weird I can successfully deploy it in `us-west-2` but all failed in the other 3 regions.

**Comment by eduardomourar** [comment]
I can confirm the same behavior while creating the fargate profile in region `eu-central-1`. A workaround for that is to add `ec2:*` policy to the cluster creation role:
```typescript
    const cluster = new eks.Cluster(this, 'Cluster', {
      vpc,
      mastersRole
    })

    const clusterResource = cluster.node.defaultChild as cdk.CfnResource
    const clusterCreationRole = clusterResource.node.tryFindChild('CreationRole') as iam.Role
    clusterCreationRole.addToPolicy(new iam.PolicyStatement({
      actions: [ 'ec2:*' ],
      resources: [ '*' ],
    }))
```

**Comment by pahud** [comment]
@eduardomourar thanks for the feedback. As Fargate profile would only associate with private subnets, if no `subnetSelection` property provided for the FargateProfile resource, the creation role will try to figure out the private subnet IDs hense require extra permissions such as `ec2:DescribeSubnets` and it looks like it would require more than that. In this case, if we create the EKS cluster with a provided VPC which has no private subnets and we don't specify subnets for the `Cluster` resource, the cluster will still be created with no error with all public subnets associated with it, but the Fargate Profile, on the other hand, will not be able to be created as all subnets associated with this cluster are pubilc only.

PR underway.

**Comment by pahud** [comment]
After checking the cloudtrail logs, the creation role will also need `ec2:DescribeRouteTables` to determine if there's any private subnets.

**Comment by pahud** [comment]
Now the question is, how can we determine if there are private subnets associated with this cluster? If we can check this, we can throw errors and avoid this error:

<img width="1428" alt="圖片" src="https://user-images.githubusercontent.com/278432/80685073-393cd800-8af9-11ea-8c16-8c875387bebb.png">

Wondering if we can do this way

```ts
const selection: ec2.SubnetSelection = props.subnetSelection ?? { subnetType: ec2.SubnetType.PRIVATE };
subnets = props.cluster.vpc.selectSubnets(selection).subnetIds;
if (!subnets || subnets.length === 0) {
      throw new Error('Fargate profile requires at least one private subnet but no private subnets found from the subnetSelection')
}
```

@eladb any comments?

**Comment by eladb** [comment]
Can we just add those permissions always?

**Comment by pahud** [comment]
> Can we just add those permissions always?

Yes, looks like adding the additional `ec2:DescribeRouteTables` will fix this issue. I am testing manually in different regions. Will create a PR for it today.
