### ISSUE TITLE
Vertical annotations for CloudWatch GraphWidgets

### ISSUE THREAD

**Issue by bappa601** [aws/aws-cdk#7622]
Horizontal Annotations are available for GraphWidgets in CDK. But we don't have Vertical  Annotations available in CDK 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.HorizontalAnnotation.html

 
### Use Case

We normally plot Vertical lines i.e particular timestamps of deployments/Events in the Graphs during troubleshooting any particular issue.

Let say we want to check if Latency/Error counts increased after particular deployment or timestamp.

We have that same feature in Cloudwatch Console. We can create it manually.
But CDK doesn't have that same feature. 

### Proposed Solution
Add one more property for Graph Widget like Horizontal Annotation 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.HorizontalAnnotation.html

**Comment by alluriv** [comment]
+1 need same feature

**Comment by rix0rrr** [comment]
Happy to have this feature in CDK, but I have a hard time seeing the described use case in practice.

* Would you go into your CDK code after every deployment to add a vertical annotation and redeploy the dashboards?
* Would you just automatically add a vertical annotation with the current date and time in your CDK app, and assume the interval between synthesis and deployment is "not too long"?

Could you go into some detail how you would use this feature if available?

**Comment by bappa601** [comment]
Would you just automatically add a vertical annotation with the current date and time in your CDK app, and assume the interval between synthesis and deployment is "not too long"? ---- 

this one making more sense...

**Comment by alluriv** [comment]
I actually used lambda to add timelines as we cannot add timelines in CDK it will be huge. So it should not done as part of CDK as we cannot get live timelines

Create lambda which takes CW dashboards as input
1) Create lambda which when triggered fetches events from given cloud formation stacks of service and store them in s3. Also creates vertical lines with deployment timelines in dashboards(different color for different stacks)
Some points in above steps:
a) We initially pick only stack level deployment start and end events for vertical lines in dashboards. 
b) We will fetch only new events information only as old events info is already stored
c) For first run we pick last 90 days of the events. 
d) Even if old stack with same name is deleted we can pick events/deployments in that stack.

2) when this lambda should be triggered: Ideally when ever events occur in Cloudformation template it should be triggered. It can be achieved by add notificationSNSarn which can trigger lambda.
Issue is aws-cdk/packages/core is not supporting adding notificationSNSarn.
https://github.com/aws/aws-cdk/issues/2528

Currently scheduled lambda every 15mins. 
Below is the image of snapshot
<img width="1181" alt="Screenshot 2020-05-04 at 9 49 23 AM" src="https://user-images.githubusercontent.com/25910297/82998792-c5bdb600-a025-11ea-94d6-214312c833eb.png">

**Comment by brendo-m** [comment]
This would be useful still. Right now my workaround is this: https://gist.github.com/brendo-m/a10f37a7248029a0e6a09b14b5e1600c

Seems like a small amount of work to add this upstream to CDK

**Comment by brendo-m** [comment]
https://github.com/aws/aws-cdk/pull/15809

**Comment by gshpychka** [comment]
@bappa601 why'd you close this? It's still not available in CDK.

@rix0rrr shouldn't the fact that this feature is available in CloudWatch and Cfn be enough reason to implement in CDK? I would also love to be able to mark arbitrary events on my widgets.

**Comment by blim747** [comment]
I also agree this would be a super useful feature to automatically indicate deployments or infra changes in CI/CD pipelines

**Comment by brendo-m** [comment]
Revived my PR in https://github.com/aws/aws-cdk/pull/22568

**Comment by peterwoodworth** [comment]
Reopened since this is not supported

**Comment by saurav-y** [comment]
Curious if/how people are using this to add deployment timestamp vertical annotations..?

The workflow we use for deployments builds the cfn template first and deploys to multiple stages (test, prod_1, prod_2 ...) sequentially. I'm looking for a way where I could use the deploymentTimestamp instead of the cfn sythesisTimestamp.

---

[Psuedo Parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) might provide a way. At least to plot the latest timestamp.

Created a [github issue](https://github.com/aws-cloudformation/cfn-language-discussion/issues/167) to request a deploymentTimestamp pseudo parameter.
