### ISSUE TITLE
cw.Dashboard method addWidgets(...widgets: IWidget[])) doesn't take an already formed array of GraphWidgets/TextWidgets/AlarmWidgets

### ISSUE THREAD

**Issue by bappa601** [aws/aws-cdk#7627]
``` ts
this.Dashboard.addWidgets(
      new cw.TextWidget({
        markdown:
          "# Hello World!!!",
        width: 24
      }),
    new cw.GraphWidget({
    <SOMETHING>
   }),
   new cw.AlarmWidget({
    <SOMETHING>
   }),
)
```
In the above addWidgets() method I want to add an array i.e  GraphWidget[] or AlarmWidget[]

Currently I can't really add the previously formed GraphWidget[] or AlarmWidget[] directly into the method. as It can only take IWidget[]. Whereas it should consider AlarmWidget[] or GraphWidget[] as IWidget[] but it is not doing that.

So need a way so that I can pass the array of AlarmWidgets or GraphWidgets directly into addWidgets() method.

### Use Case
Lets take an example. You have your service deployed into 3 different Availability Zones. Now you created 3 different CloudWatch Alarms for each of the Availability Zones. Now you named those 3 alarms programmatically 
``` ts
cw.Alarm[] myAlarmsArray = vpc.availabilityZones.map(
      (azs, index) =>
        new cw.Alarm(this, "MyAlarm" + index, {
          alarmName: "Too Many Unhealthy Hosts_" + azs,
          alarmDescription: "MyAlarms per AZ",
});
```
Now that you have an array of alarms i.e myAlarmsArray, you can easily create an AlarmsWidgets[] using below sort of code
i.e
myAlarmsWidgets = myAlarmsArray.map( new AlarmsWidget())

so you now have the array of AlarmWidgets[] created through code. and you want to show their status on CloudWatch dashboard. 
All you have to do is add the AlarmWidgets[] directly into your dashboard's addWidgets() method. Which is not possible currently.

It will be hard to create those AlarmWidgets one by one and add one by one into addWidgets() method.

### Proposed Solution

Technically AlarmWidget[] or GraphWidget[] arrays should be considered as  IWidget[] array but it is not doing that.

**Comment by rix0rrr** [comment]
What's the language you're having issues in?

**Comment by bappa601** [comment]
I am using 'Type Script'

**Comment by bappa601** [comment]
@rix0rrr  Can you please reopen this one

**Comment by rix0rrr** [comment]
I still don't understand this ticket, because it should work and when I try it on my machine it works. Are you looking for the `...` operator?

For reference, this works for me:

```ts
    const dash = new cloudwatch.Dashboard(this, 'DB');
    const widgets = [1, 2, 3].map(i => new cloudwatch.AlarmWidget({ alarm: cloudwatch.Alarm.fromAlarmArn(this, `Alarm${i}`, 'aws:arn:...') }));
    dash.addWidgets(...widgets);
```

**Comment by kushg18** [comment]
I'm having the same issue. 
`dashboard.addWidgets(...IWidget[])` does not expect any `ConcreteWidget`, for example `GraphWidget`.

The only way to byepass this is to actually make use of IWidget instead of using GraphWidget or possible any other concrete widget.

Error: 
[
  {
    "dataPath": "/widgets/1/properties",
    "message": "Should have required property 'metrics'"
  },
  {
    "dataPath": "/widgets/1/properties",
    "message": "The metric widget should have specified a region and a data source or an alarm annotation"
  },
  {
    "dataPath": "/widgets/1/properties",
    "message": "Should have required property 'annotations'"
  }
]
