### ISSUE TITLE
Use only Service Linked Role for EKS clusters

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#7634]
## :question: General Issue

Amazon EKS now supports service link roles
https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-eks-supports-service-linked-roles/?nc1=h_ls

According to the [eks user guide](https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html)

> Prior to April 16, 2020, AmazonEKSServicePolicy was also required and the suggested name was eksServiceRole. With the AWSServiceRoleForAmazonEKS service-linked role, that policy is no longer required. 

`eksctl` just released `0.18.0` and removed the `AmazonEKSServicePolicy` from the cluster role.

https://github.com/weaveworks/eksctl/pull/2079

I was wondering if it's safe just remove this policy from the cluster role?

https://github.com/aws/aws-cdk/blob/1ee629e418fccec30b8a94e43682ed2c47ddd8da/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L371

### Environment

  - **CDK CLI Version:**  1.35.0
  - **Module Version:**  aws-eks
  - **OS:**  mac os x
  - **Language:**  all

**Comment by pahud** [comment]
copy @eladb

**Comment by eladb** [comment]
@pahud can you run a couple of tests to ensure this works?
