### ISSUE TITLE
X-Ray support for AppSync CDK construct

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#7640]
Now that X-Ray exists as a feature that can be enabled on AppSync since February 2020 (https://aws.amazon.com/about-aws/whats-new/2020/02/aws-appsync-releases-integration-with-aws-x-ray-and-graphql-info-object-support/) it makes sense to allow it to be enabled through the CDK constructs, similarly to how it's enabled for Lambda constructs for example.

In other words, something like this should be possible:
```
new GraphQLApi(this, `graphql`, {
            name: `graphql`,
            tracing: Tracing.ACTIVE,
};
```

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by lielran** [comment]
also, Xray is supported by CFN https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html

**Comment by BryanPan342** [comment]
This should be a `good first issue` to tackle for first time contributors! 

- [ ] Adding a `boolean` prop for `xrayEnabled`
- [ ] Linking it to the `xrayEnabled` prop in class `CfnGraphQLApi` from `appsync.generated.ts` file that is generated on `yarn build`
- [ ] Writing a unit test to check whether that the boolean property is set in the CloudFormation Template

**Comment by tomoki10** [comment]
I may be able to implement this feature request.

**Comment by BryanPan342** [comment]
@tomoki10 fantastic! whenever you start please feel free to label the issue as `in-progress` :)
