### ISSUE TITLE
InterfaceVpcEndpoint Java CDK: Referencing Security Group will modify it

### ISSUE THREAD

**Issue by phrastnik** [aws/aws-cdk#7643]
We're trying to create an InterfaceVpcEndpoint using Java CDK and reference an existing SecurityGroup. Unfortunately, this referenced SecurityGroup will be modified on deploy, although the documentation says that it is just a reference ("The security groups to associate with this interface VPC endpoint.") and we don't want to modify it.
In our case, the underlying problem is that due to security restrictions, not everyone is allowed to modify SecurityGroups and for other CDK areas like Lambdas just referencing existing ones is working.

### Reproduction Steps
```
        InterfaceVpcEndpoint vpcEndpoint = InterfaceVpcEndpoint.Builder.create(this, "stackVpcEndpointId")
                .vpc(Vpc.fromLookup(this, "stackVpcId", VpcLookupOptions.builder().vpcId(theVpcId).build()))
                .subnets(SubnetSelection.builder().subnets(List.of(
                        Subnet.fromSubnetAttributes(this, "stackFirstSubnetId", SubnetAttributes.builder().subnetId("theSubnetId").availabilityZone("theAZ").build())
                        )).build()
                 )
                .securityGroups(List.of(SecurityGroup.fromSecurityGroupId(this, "stackSgID" , "sg-0f3ec55e3b11520ab")))
                .service(InterfaceVpcEndpointAwsService.APIGATEWAY)
                .privateDnsEnabled(Boolean.FALSE)
                .build();
```

### Error Log
```
Security Group Changes
┌───┬──────────────────────┬─────┬──────────┬───────────────┐
│   │ Group                │ Dir │ Protocol │ Peer          │
├───┼──────────────────────┼─────┼──────────┼───────────────┤
│ + │ sg-0f3ec55e3b11520ab │ In  │ TCP 443  │ 10.16.24.0/21 │
└───┴──────────────────────┴─────┴──────────┴───────────────┘
```
Created CF template:
```
    "sg0f3ec55e3b11520abstagefrom10162402144371766E0D": {
      "Type": "AWS::EC2::SecurityGroupIngress",
      "Properties": {
        "IpProtocol": "tcp",
        "CidrIp": "10.16.24.0/21",
        "Description": "from 10.16.24.0/21:443",
        "FromPort": 443,
        "GroupId": "sg-0f3ec55e3b11520ab",
        "ToPort": 443
      },
      "Metadata": {
        "aws:cdk:path": "rptSvcBackendStack-stage/sg-0f3ec55e3b11520abstage/from 10.16.24.0_21:443"
      }
    },
```

### Environment

  - **CLI Version      :** 1.35.0
  - **Framework Version:** 1.35.0
  - **OS               :** Windows 10
  - **Language         :** Java

### Other

In our case, the existing SecurityGroup already has Inbound `HTTPS | TCP | 443 | 10.0.0.0/8`, so adding `In  │ TCP 443  │ 10.16.24.0/21 │` as it is done in CDK makes no sense. 
Moreover, as in our special case it is not allowes to modify SecurityGroups for all users, it will throw some `API: ec2:CreateVpcEndpoint You are not authorized to perform this operation.`error.

As in other CDK projects referencing existing SecurityGroups without modifying them is possible (e.g. Lambdas), this seems like a Bug or a significant inconsistency for us.

**Comment by rix0rrr** [comment]
Configure `mutable(false)` when you call `fromSecurityGroupId`:

https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/ec2/SecurityGroup.html
