### ISSUE TITLE
Issue when adding Lambda destinations in the console 

### ISSUE THREAD

**Issue by milestojakovic** [aws/aws-cdk#7654]
When adding a destination in the console, if a destination already exists for the Async **onFailure** OR **onSuccess** and you try to add another destination of the same type and for the same execution status, it silently overwrites the previous one.  

 After adding the first destination of any execution status (Failure or Success) , the button "**+ Add destination**"  of the same type and status acts like an "**update**" instead of "**add**". 

This applies to all destination types: SNS topic, SQS queue or Lambda function.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hello - 

This repo is tracking issues related to the CDK. We don't own the AWS console experience; you will need to open an issue with AWS support for this.

**Comment by milestojakovic** [comment]
Hi,

Thanks for the update. I opened the ticket with AWS support. They said that this is beyond of the scope which they are able to handle and they are asking me to upgrade to paid support plan. I don't need to paid support plan, and I have workaround for this. This is a bug in AWS console. Is there any chance to forward this issue to developers who own the AWS console experience, so they can test and fix it.
