### ISSUE TITLE
logs: Allow overriding Role in `addSubscriptionFilter` 

### ISSUE THREAD

**Issue by jordanst3wart** [aws/aws-cdk#7661]
I'm trying to add a boundary permission to the IAM role created here:
https://github.com/aws/aws-cdk/blob/v1.36.0/packages/@aws-cdk/aws-logs-destinations/lib/kinesis.ts#L17

My code looks something like:
```
item.addSubscriptionFilter(generateID(),{destination: dest, filterPattern: log.FilterPattern.allEvents()} )
```
This creates an IAM role in the background.

It looks like you should be able to override the role like with the id:
```
        const id = 'CloudWatchLogsCanPutRecords';
        new iam.Role(this, id, {
            assumedBy: new iam.ServicePrincipal('logs.amazonaws.com'),
            permissionsBoundary: boundary
        });
```
But the scope (or `this`) used by `addSubscriptionFilter` is actually inaccessible.
https://github.com/aws/aws-cdk/blob/47c991949618d0e95bfafccb0ecd73687036b432/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L107

### Use Case
To add boundary permission to IAM role

### Proposed Solution

Allow optional iam role to be passed in with `addSubscriptionFilter`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by arnulfojr** [comment]
Hi, I'd like to add that if the kinesis stream has SSE encryption the role also requires permissions to generate data key.
Right now this can't be easily done by using this abstractions.
Is there an approx date for it?

**Comment by arnulfojr** [comment]
Oh, nvm on the KMS Key.

Found that I can import the stream by `kinesis.Stream.fromStreamAttributes(/* ... */)` then the `grant` call in the destination adds the required permissions.

Though, I think this issue it's still relevant from the security point of view and also being able to specify a role name when needed is not possible.
