### ISSUE TITLE
RoleMapping ProviderName or is not a configured provider.

### ISSUE THREAD

**Issue by georgeevans1995** [aws/aws-cdk#7670]
## :question: General Issue
I am trying to add a role attachment to a cognito identity pool using groups but keep getting:
"XXX is not a valid RoleMapping ProviderName or is not a configured provider." even though the userpool and app client I am using definitely exist.

### Environment

  - **CDK CLI Version:** aws-cdk@1.36.0
  - **Module Version:** @aws-cdk/aws-cognito": "^1.36.0
  - **OS:** OSX Mojave
  - **Language:**TypeScript

### Other information
As far as I can see it is something wrong with this part :  
"IdentityProvider": "cognito-idp.eu-west-2.amazonaws.com/USER_POOL_ID:CLIENT_ID"

but the docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypoolroleattachment-rolemapping.html)
state exactly this format.

Here is my cloud formation template output that CDK is creating any help on this would be greatly appreciated! 

`
"XXXXroleattachment": {
      "Type": "AWS::Cognito::IdentityPoolRoleAttachment",
      "Properties": {
        "IdentityPoolId": "eu-west-2:XXXXXXXXXXXXXXXX",
        "RoleMappings": {
          roleMapping: {
            "AmbiguousRoleResolution": "Deny",
           "IdentityProvider": "cognito-idp.eu-west-2.amazonaws.com/eu-west2_XXXXXXX:XXXXXXXXXXXXX",
            "RulesConfiguration": {
              "Rules": [
                {
                  "Claim": "cognito:groups",
                  "MatchType": "Contains",
                  "RoleARN": "arn:aws:iam::XXXXXXX:role/XXXXXXXX",
                  "Value": "XXXXXX"
                }
              ]
            },
            "Type": "Rules"
          }
        },
        "Roles": {
          "unauthenticated": "arn:aws:iam::XXXXXXXXX:role/XXXXXXXXXXXXX",
          "authenticated": "arn:aws:iam::XXXXXXXXX:role/XXXXXXXXXXXXX"
        }
      },
      "Metadata": {
        "aws:cdk:path": Stack/role-attachment"
      }
    }
`

**Comment by nija-at** [comment]
Hello @georgeevans1995 -

Unfortunately we have not implemented any higher level constructs for Identity Pool as yet. The constructs that are currently available are CFN Resource constructs.

This means that this maps 1-1 with CloudFormation resource types and there is nothing that happens with the CDK under the the hood. 

You will likely have to refer to and speak with the Cognito team to resolve this. 

However, if you still think this is an issue with the CDK, please provide us with the code to reproduce this issue, and what you are trying to achieve. Since this is a CFN Resource construct, the latter would mean what you expect to see in the CloudFormation template.

**Comment by georgeevans1995** [comment]
@nija-at thanks, makes sense, wasn't sure if this was the right place for this issue, are you able to point me in the direction of the best place to log this as a bug with the Cognito team?

**Comment by nija-at** [comment]
Unfortunately, you will need to reach out to AWS support and file a report with them. There is no way to report this directly.

**Comment by georgeevans1995** [comment]
Ok thanks

**Comment by leantorres73** [comment]
For the record, I faced this same issue but I was able to make it work, version 1.57.0

```
const roleMapping : cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty = {
    type: 'Token',
    ambiguousRoleResolution: 'Deny',
    identityProvider: `cognito-idp.${Stack.of(this).region}.amazonaws.com/${pool.userPoolId}:${client.userPoolClientId}`
};
```

**Comment by YvesIraguha** [comment]
This works too, in case you are using CloudFormation `.yml` template or `serverless.yml`

```    IdentityProvider:
              Fn::Join:
                - ''
                - - Fn::GetAtt: [CognitoUserPool, ProviderName]
                  - ':'
                  - Ref: CognitoUserPoolClient```

**Comment by FrankyCTY** [comment]
For the identityProvider, just the combination of userPoolProviderName and userPoolClientId is fine, no need to be fancy :)

```
const roleMapping : cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty = {
    type: 'Token',
    ambiguousRoleResolution: 'Deny',
    identityProvider: `${userPool.userPoolProviderName}:${userPoolClient.userPoolClientId}`
};
```

**Comment by efelipe402** [comment]
I need to do the same but instead of cognito groups or cognito as provider, I need to add google auth as provider any help?
