### ISSUE TITLE
Add a grantWrite to secretsmanager.Secret

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#7682]
I'd like to request the addition of a `grantWrite` method to `secretsmanager.Secret`. There is currently a `grantRead` but no `grantWrite`

### Use Case

In my particular case, I am writing a custom resource that generates something and stores that thing in a predefined secret. More generally, there will be customers that have reason to write the contents of a secret from deployed resources.

### Proposed Solution

```
  public grantWrite(grantee: iam.IGrantable): iam.Grant {
    // @see https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_identity-based-policies.html
    const result = iam.Grant.addToPrincipal({
      grantee,
      actions: ['secretsmanager:PutSecretValue'],
      resourceArns: [this.secretArn],
      scope: this,
    });

    if (this.encryptionKey) {
      // @see https://docs.aws.amazon.com/kms/latest/developerguide/services-secrets-manager.html
      this.encryptionKey.grantEncrypt(
        new kms.ViaServicePrincipal(`secretsmanager.${Stack.of(this).region}.amazonaws.com`, grantee.grantPrincipal),
      );
    }

    return result;
  }
```

### Other

I already have a PR ready to go for this, but it is blocked on https://github.com/aws/aws-cdk/issues/7677 -- which I submitted earlier today, with a corresponding PR. I'll post the PR once that issue is resolved.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Done in #7858 🙂
