### ISSUE TITLE
How to use NodejsFunction with AWS-SDK?

### ISSUE THREAD

**Issue by sdegutis** [aws/aws-cdk#7685]
### The Question

I think the NodejsFunction function in the `aws-lambda-nodejs` may need another parameter. It uses Parcel to package the NodeJS-based function, but if that function does `require('aws-sdk')` from within that Lambda's code, Parcel will bundle that too, even though that module is natively available inside the Lambda function when called by AWS.

### Environment

  - **CDK CLI Version:** 1.36.0 (build 47c9919)
  - **Module Version:** ^1.36.0
  - **OS:** macOS 10.15.4 (19E287)
  - **Language:** TypeScript

### Other information

I think if there was a way to tell Parcel to leave the `require` line as-is without transforming it, then the `aws-lambda-nodejs` module could include that as an option for its constructor props.

(Pinging @jogold as I was told that's who wrote this module and to bring this up to him.)

**Comment by sdegutis** [comment]
See also parcel-bundler/parcel#4547 because I'm not sure such a flag exists just yet (but it may, and I may have overlooked it in the Parcel docs).

**Comment by jogold** [comment]
Hi @sdegutis

For now I recommend using [`parcel-plugin-externals`](https://github.com/FlorianRappl/parcel-plugin-externals). Just add it as a dev dependency then in your `package.json` add either:
```json
{
  "peerDependencies": {
    "aws-sdk": "*"
  }
}
```

or:
```json
{
  "externals": [
    "aws-sdk"
  ]
}
```

With this setup, `aws-sdk` will not be bundled.

After #7169 gets merged, I have plans to add a `prop` to specify `externals`.

**Comment by sdegutis** [comment]
Thanks @jogold!

**Comment by sdegutis** [comment]
Also, [this solution](https://github.com/parcel-bundler/parcel/issues/4547#issuecomment-621452095) just now mentioned might already be viable for this module. Not sure if it's already been considered though.

**Comment by iDVB** [comment]
> After #7169 gets merged, I have plans to add a `prop` to specify `externals`.

Hey @jogold now that #7169 is merged... did you get a chance to work on adding that prop?

**Comment by jogold** [comment]
> > After #7169 gets merged, I have plans to add a `prop` to specify `externals`.
> 
> Hey @jogold now that #7169 is merged... did you get a chance to work on adding that prop?

Not yet, we now need #7898...

**Comment by iDVB** [comment]
Thanks @jogold , I did see that issue, just wasn’t positive on the relevancy. 
In the meantime is there some kind of Jacky workaround short of having all updates to anything trigger a new version?
