### ISSUE TITLE
L2 construct for Synthetics Canary

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#7687]
Add a L2 construct for [`AWS::Synthetics::Canary`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html) (needs #7664).

For the [code property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-code.html) there's a lot in common with Lambda.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@jogold that would be awesome! got #7664 merged. happy building!

**Comment by ookangzheng** [comment]
When will it release 👯

**Comment by hoegertn** [comment]
@jogold Hi, did you start implementing this? Otherwise, I could look into it.

**Comment by jogold** [comment]
> @jogold Hi, did you start implementing this? Otherwise, I could look into it.

Not yet, feel free to start working on this!

**Comment by NetaNir** [comment]
Hi There @jogold & @hoegertn!

We picked this up, @kaizen3031593  will be working on this for the next few months, we will share our high level design and would love to get your feedback.

**Comment by hoegertn** [comment]
@NetaNir @kaizen3031593 wonderful. I am happy to give feedback. Ping me whenever you need something. We can jump on a call if you like.

**Comment by jogold** [comment]
> @NetaNir @kaizen3031593 wonderful. I am happy to give feedback. Ping me whenever you need something. We can jump on a call if you like.

Same here.
