### ISSUE TITLE
Lambda@Edge functions try to bundle the whole directory

### ISSUE THREAD

**Issue by sdegutis** [aws/aws-cdk#7692]
When I had two lambda functions inside the same `./lambda` directory, one of them used in Lambda@Edge and requiring no modules, and the other being used with regular Lambda and requiring modules, the CDK gives me this error:

> The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 2445137 Max allowed: 1048576

It shouldn't care about the file that isn't included in or used by the Lambda@Edge function. That shouldn't count against its size limit.

### Reproduction Steps

See above.

### Error Log

See above.

### Environment

* CDK version 1.36.0 (build 47c9919)
* MacOS latest

### Other

n/a

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Can you provide the code snippets on how you're defining the lambda `Function` in both cases, specifically on how the `code` property is set? 
Could you also provide your directory structure under the `./lambda` folder?

**Comment by sdegutis** [comment]
I had a directory called `lambda` with `file1.js` and `file2.js`.

The `new lambda.Function` has:
```js
  code: lambda.Code.fromAsset('lambda'),
  handler: 'file1.handler',
```

The `new lambdaNode.NodejsFunction` has:
```js
  entry: './lambda/file2.js',
  handler: 'handler',
```

This is sufficient to have `lambdaNode.NodejsFunction` get confused by `file1.js` and trying to bundle its requires.

**Comment by sdegutis** [comment]
I think the problem probably lies in `lambda.Code.fromAsset('lambda')` in file1.js, which does not exclude `node_modules` by default. Thus it was bundling all node_modules with it. Most likely an issue with me and not CDK. Thanks for your patience as I figured this out.
