### ISSUE TITLE
Discrepancy in code and docs for encryptionMasterKey in sqs.Queue

### ISSUE THREAD

**Issue by shreyasdamle** [aws/aws-cdk#7694]
In sqs.Queue [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.Queue.html#encryptionmasterkey) for `encryptionMasterKey`, it is mentioned that `The 'encryption' property must be either not specified or set to "Kms". An error will be emitted if encryption is set to "Unencrypted" or "KmsManaged"`. However, in `queue.ts`, the following condition is specified:
```ts
      if (encryption !== QueueEncryption.KMS && props.encryptionMasterKey) {
        encryption = QueueEncryption.KMS; // KMS is implied by specifying an encryption key
      }
```

Hence, `KMS` is implied if both `encryption` and  `encryptionMasterKey` properties are mentioned and there is no error logged for this.

### Reproduction Steps
```ts
const fifo = new sqs.Queue(stack, 'FifoQueue', {
  fifo: true,
  encryption: sqs.QueueEncryption.UNENCRYPTED,
  encryptionMasterKey: new SecureKey(stack, 'EncryptionKey', {
    removalPolicy: RemovalPolicy.DESTROY,
    enableKeyRotation: true,
  }),
});
```

### Error Log
No error is logged.

### Fix

`if` condition can be modified as:
```ts
      if (encryption !== QueueEncryption.KMS && props.encryptionMasterKey) {
        throw new Error(`encryptionMasterKey is specified, so 'encryption' must be set to KMS (value: ${encryption})`);
      }
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
Changing the code here would result in breaking certain users. Seems like we will just have to change the documentation to reflect what is actually occuring. If `encryptionMasterKey` is provided, encryption type is always `KMS`.
