### ISSUE TITLE
Resource tags should be sorted - Order of adding TAGS can result in a change

### ISSUE THREAD

**Issue by argenstijn** [aws/aws-cdk#7707]
If you add two or more TAGS as below the order in which you add the tags matters:

 Tag.add( scope, tagname, tagvalue )
 Tag.add( scope, tagname1, tagvalue1 )

or

 Tag.add( scope, tagname1, tagvalue1 )
 Tag.add( scope, tagname, tagvalue )

It will result in a different cloudformation template and thus CDK will execute a change.

### Environment

  - **CLI Version      : 1.36.0
  - **Framework Version:**
  - **OS               :**
  - **Language         : Java

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
We should sort the tags when we synthesize.

**Comment by michaelbrewer** [comment]
Don't change this behavior again, but this was a breaking change as it forced a redeploy of all stacks that did not already have tags in alphabetical order.
