### ISSUE TITLE
cdk bootstrap - Bucket Deployment requires a directory to exist in a stack that is not being created

### ISSUE THREAD

**Issue by owenashurst** [aws/aws-cdk#7713]
### The Question

Running `cdk bootstrap` expects a folder to exist that an S3 bucket is pointing to when I thought it shouldn't need to check if the folder exists since it's not creating the resource.

### Environment

  - **CDK CLI Version:** 1.35.0 (build e0810c8)
  - **Module Version:** aws-cdk
  - **OS:** all
  - **Language:** TypeScript

### Other information

As far as I know, `cdk bootstrap` creates a stack that creates an S3 bucket that is used to upload assets to to deploy to lambda or S3 etc. 

I'm not sure why it's requiring a directory to be created that an S3 resource is pointing to when I am not deploying. If this is the correct behaviour, what should I be doing? The directory in question is a React website that only gets built once the website stack is being deployed. If the stack is not being deployed it shouldn't need to check that the output directory exists.

**Comment by shivlaks** [comment]
@owenashurst can you provide a bit more detail on how you're using `cdk bootstrap`? What's a minimal set of steps to repro what you're running into?

**Comment by owenashurst** [comment]
@shivlaks I'll create a github repo and give you an example

**Comment by shivlaks** [comment]
@owenashurst - I'm wondering if this was the bug that was fixed where running `cdk bootstrap` required `--app` that was closed by #7970. I'll take a look when I have the repro steps!

**Comment by owenashurst** [comment]
What I originally had was my backend code along with my "frontend" code, e.g. S3, cloudfront etc. What I ended up doing was splitting these out into two stacks for frontend and backend to avoid the issue of the S3 deployment resource having to have a valid directory during the bootstrap process.

This is because the site would be built after the bootstrap process.

Here's an example git repository with just an S3 bucket and the s3 deployment resources. Run `cdk bootstrap` and observe the error.
https://github.com/owenashurst/example-cdk-bootstrap

**Comment by owenashurst** [comment]
@shivlaks Any update? My CDK is onw failing entirely regardless of which stack my bucket deployment is in now.

**Comment by SomayaB** [comment]
Hi @owenashurst, I reproduced your issue and when using your code I am getting the same error. However, the error isn't coming from `cdk bootstrap` or the CLI at all for that matter. It is coming from the fact that you're not providing a real path to assets in the`BucketDeployment` [sources](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html#supported-sources). You can use this [test](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-s3-deployment/test) as an example. Basically you want to make sure that [sources](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3-deployment/test/integ.bucket-deployment-cloudfront.ts#L26) points to a real path that exists. 
I can see that you were copying the readme code, which we should definitely add a note to explaining that you need to provide a real path to an actual asset folder, even before you deploy. Sorry about the confusion. Hope this helps!
