### ISSUE TITLE
Issues with building Fargate Pipeline with importing existing resources

### ISSUE THREAD

**Issue by soheilhm** [aws/aws-cdk#7725]
Hi there, I have built a few of our infrastructures with CDK and it has been great but I am currently struggling with building a pipeline for new backend services in fargate from end to end. This pipeline will be used to spin up down new sandbox backends on demand and that is why the logical resources in the stack need to be contained together.

I will try to explain in detail and sorry for the long post. 

These are the steps that need to happen in the pipeline I am trying to make:
1.  create an ECR repo
2. create task definition, add a container to it and map container ports
3. create a fargate cluster and attach it to **existing** ecs cluster and use **existing** security groups for the service
4. Create new application target group and attach it to the fargate service created at step 3
5. Import the port 80 and port 443 listeners of **existing** ALB and add the target groups from step 4 and adjust the listener host header to match the DNS record 
6. create a Route53  DNS record in the primary zone

My first failed approach was to use _ApplicationLoadBalancedFargateService_ from the higher level ecs-patterns construct. This was roughly my implementation:
  
```
    // get existing cluster
    const clusterSG = SecurityGroup.fromSecurityGroupId(scope, ...);

    // create existing iam role
    const ecsRole = Role.fromRoleArn(scope, ...);

    // create a new ecr repo.
    const ecrRepo = new Repository(scope, ...);

    // get current security group
    const sg = SecurityGroup.fromSecurityGroupId(scope, ...);

    // create FG service with the ecr repor using existing cluster, IAM role and SG
    const loadBalancedFargateService = new ApplicationLoadBalancedFargateService(scope, `cdk-ecs-fg-${serviceIdentifier}`, {
        cluster: Cluster.fromClusterAttributes(scope, ...),
        taskImageOptions: {
            image: ContainerImage.fromEcrRepository(ecrRepo),
            ...,
        },
        // loadBalancer only works if I create a new one
        loadBalancer: new ApplicationLoadBalancer(scope, ...),
        ...,
    });

    loadBalancedFargateService.targetGroup.configureHealthCheck(...);
```

it mostly worked but there were these issues:

 1- Attaching to current ALB doesn't work and it works only if you create a new one
 2- Attaching existing security groups for both the ECS service and new ALB doesn't work (only works if you create new SGs)
 3- the task definition name and target group names are random and there is no way set them through the config props
 4- the stack takes forever to complete (is there a way to profile and optimize this?) even when there are no errors so I have to manually stop and delete it from the cloudfromation
5- After deleting stack, all the logical resources get cleaned up except for ECR repo which I have to manually go and delete it

My second failed approach was to use lower-level constructs from '@aws-cdk/aws-elasticloadbalancingv2' and '@aws-cdk/aws-ecs' so I get more control of the steps. Something like this:
```
    // create ECR repo  
    const ecrRepo = new Repository(scope, ...);

    // create existing iam role
    const ecsRole = Role.fromRoleArn(scope, ...);

    // create task definition, add container and do port mapping
    const taskDefinition = new FargateTaskDefinition(scope, ...);
    const container = taskDefinition.addContainer(serviceName, ...);
    container.addPortMappings(...);

    // get ecs cluster
    const clusterSG = SecurityGroup.fromSecurityGroupId(scope, ...);

    // create new fargate service
    const fargateService = new FargateService(scope, ...
    });
    const applicationTargetGroup = new ApplicationTargetGroup(scope, ...);

    const albListenerHTTP = ApplicationListener.fromApplicationListenerAttributes(scope, ...);
    const albListenerHTTPS = ApplicationListener.fromApplicationListenerAttributes(scope, ...);

    [albListenerHTTP, albListenerHTTPS].forEach((listener) => {
        listener.addTargetGroups(..., {
            targetGroups: [applicationTargetGroup],
            hostHeader: ...',
        });
    });

    fargateService.attachToApplicationTargetGroup(applicationTargetGroup);
```

This solved a bunch of problems e.g. task definition and target groups can now be more customized with names and everything and I can also use existing security groups and IAM roles. 

But there are still issues with this setup:

1. The cdk deployment takes forever so again I have to go and manually delete the stack from cloud formation (how can I profile/optimize this?)
![image](https://user-images.githubusercontent.com/17885979/80773383-98f1ae00-8b0e-11ea-88ad-ba631b459172.png)
(it will stay like this for hours)

2. I can see the progress as the resources get built but some are still missing e.g. the target group doesn't attach to the fg service and the ALB listener

I appreciate your attention to this also any pointers on how I can do this better to achieve my goal would be great.

Thanks,
Soheil

**Comment by soheilhm** [comment]
figured it out.

**Comment by dkboon01** [comment]
I'm trying to retrieve the listener that is created on port 80 when I create an application load balancer.
I'm trying to use this ApplicationListener.fromApplicationListenAttributes
When I try cdk synth it tells me that:
 AttributeError: type object 'ApplicationListener' has no attribute 'fromApplicationListenerAttributes'

Can you show me what you put after the word scope in your code on line:

>     const albListenerHTTP = ApplicationListener.fromApplicationListenerAttributes(scope, ...);

**Comment by jordanbice** [comment]
> ApplicationListener

@sohei1l How? Having the same issue.
