### ISSUE TITLE
[feature request] ability to reference future constructs

### ISSUE THREAD

**Issue by binarythinktank** [aws/aws-cdk#7730]
it would be useful, and lead to cleaner code, to be able to reference constructs that come later in the stack without it creating an error.

### Use Case
for example. I have 5 lambda X functions and 1 lambda Y function. 

In the environment variables of all of the X functions, I need to be able to refer to the lambda Y function. So i place the Y function first in the stack followed by the 5 X functions - so far so good.

But now, in the Y function i would like to have environment variables of the 5 X functions. If i simply refer to those functions it wont work, so i need to go and get the deployed names then manually put them into the environment variables. And if something changes with the X functions, or if i deploy it to a new environment, then i need to go back and update those references (not clean). 

### Proposed Solution
I assume CDK knows what the function names are going to be, so perhaps it first makes one sweep to generate all the relevant names/references, then on a 2nd sweep it can "know" what a param is referring to when it tries to reference a function further down in the stack.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
You should be able to use `function.addEnvironment` after you've defined what you need.

Closing for now.

**Comment by binarythinktank** [comment]
just wanted to add:
you are right that this can work **within the same stack**.... not so much across multiple stacks as then it throws a cyclic reference error.

**Comment by eladb** [comment]
> you are right that this can work within the same stack.... not so much across multiple stacks as then it throws a cyclic reference error.

Can you describe your use case?

**Comment by binarythinktank** [comment]
the use case is that i have multiple stacks.

There could be many reasons for that. Architecturally, I separate stacks by groups within a given solution: ingestion/processing/export for example. 

Or, in my current case with the lambdas, it's due to cloudformation limits. I have too many microservices so I need to split them into 2 stacks and i need references between some of the lambdas. So now, I need to hardcode the references in one of the stacks to avoid cyclic references. 

Could i re-organize them so the ones with references are all together? sure, which will work for a while until i run into the limits again, so i think a more scalable solution should at least be considered. 

in this particular project the stacks are all individual, not nested (each stack created in /bin with the "app" as the first param). not sure if this issue would be addressed with nested stacks but its a rather large project so i dont really want to reorganize the entire thing into nested stacks at this pointas that might have other side effects.
