### ISSUE TITLE
Is it Possible to Get ENI/Private IPs from a Network Load Balancer or Vpc Endpoint in CDK?

### ISSUE THREAD

**Issue by AmyFengAmazon** [aws/aws-cdk#7739]
## :question: General Issue:
Is it Possible to Get ENI/Private IPs from a Network Load Balancer or Vpc Endpoint in CDK?

### The Question

On the EC2 console,
1. I can go to the Network Interface tab
2. Put into the search/filter bar, the load balancer name or a vpc endpoint
3. See the ENIs associated with the load balancer or a vpc endpoint
4. Click on each ENI to see the private ip in the details view

How can do this in code with CDK? When I look at the fields for the load balancer or vpc endpoint, I don't see an accessible field to get these private ips. Is there a feature for this? If there is not feature, do I have to create my own custom resource with lambda to do so?

### Environment

  - **CDK CLI Version:** 1.23.0
  - **Module Version:** 1.23.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by hoegertn** [comment]
You cannot get the IPs directly but you can use a AWS custom resource for this. I use this to get the IP of a VPC endpoint for internal API Gateways here: https://github.com/taimos/cdk-constructs/blob/master/lib/serverless/internal-rest-api.ts#L117

**Comment by rix0rrr** [comment]
Thanks for chiming in @hoegertn.

Closing as I'm assuming this answers your question.

**Comment by davidagold** [comment]
@rix0rrr @hoegertn Do either of you know how to do this for a Network Load Balancer? I am trying to allow ingress from only the NLB IP address but cannot find how to access the latter through the CDK. The IP address is not included amongst the [NLB attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#load-balancer-attributes). I see that there is a [LoadBalancerAddress](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAddress.html) datatype, but can't find any way to access this. Any help would be appreciated 🙏

**Comment by hoegertn** [comment]
Can you elaborate on your use case? NLBs behave a little bit differently and you normally cannot restrict traffic by IP.

**Comment by davidagold** [comment]
Thanks for your response Thorsten. I am setting up an Airflow service, and the template I was following was using private subnets + NLB + NAT gateway, but I wanted to use public subnets + security group in place of NAT gateways since the latter are expensive. I ended up using an ALB, since I was having difficulty accommodating the desired pattern with the NLB.

**Comment by kenberkeley** [comment]
> You cannot get the IPs directly but you can use a AWS custom resource for this. I use this to get the IP of a VPC endpoint for internal API Gateways here: https://github.com/taimos/cdk-constructs/blob/master/lib/serverless/internal-rest-api.ts#L117

Now In AWS CDK v2 we have `outputPaths` which supports multiple paths so we no longer need to use a for-loop.

Here is an example:

```ts
import * as Iam from "aws-cdk-lib/aws-iam"
import { AwsCustomResource, PhysicalResourceId } from "aws-cdk-lib/custom-resources"
import { Construct } from "constructs"

export function getEniIpsByEniIds(
  scope: Construct,
  eniIds: string[],
): string[] {
  const outputPaths = eniIds.map(
    (_, index) => `NetworkInterfaces.${index}.PrivateIpAddress`,
  )
  const response = new AwsCustomResource(scope, `describe-enis`, {
    onUpdate: {
      service: "EC2",
      action: "describeNetworkInterfaces",
      outputPaths,
      parameters: { NetworkInterfaceIds: eniIds },
      physicalResourceId: PhysicalResourceId.of(Math.random().toString()),
    },
    policy: {
      statements: [
        new Iam.PolicyStatement({
          actions: ["ec2:DescribeNetworkInterfaces"],
          resources: ["*"],
        }),
      ],
    },
  })
  return outputPaths.map((outputPath) => response.getResponseField(outputPath))
}
```

**Comment by adminy** [comment]
would be nice to have proper cloudformation support for this.
