### ISSUE TITLE
lambda.AssetCode() does not preserve file permissions

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#7749]
I was trying to deploy my lambda code assets with custom runtime with my own `bootstrap` file which has to be executable(chmod +x).

However, it loos like when the folder was staged into `cdk.out` the executable permission will not be preserved.

<img width="1165" alt="圖片" src="https://user-images.githubusercontent.com/278432/80855353-1df5d800-8c73-11ea-927a-0b987225314f.png">

According to the document, if we are implementing the custom runtime, the `bootstrap` file has to be exetable.
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html

Looks like we have no property to enable the permission preservation in this scenario.

Not sure if it's related to https://github.com/nodejs/node/pull/27241

### Environment

  - **CLI Version      :** 1.36.1
  - **Framework Version:**
  - **OS               :** mac os x
  - **Language         :** typescript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @pahud - 

Can you provide the code snippet you are using for this?

**Comment by netroy** [comment]
@pahud This is most likely due to the changes on `copyFile` for osx.
Can you try to test this on node 10.*?
if that fixes the issue, [[here](https://github.com/libuv/libuv/pull/2578) is the ticket to follow.

**Comment by pahud** [comment]
Please don't close this issue. Will get back to it shortly.

**Comment by pahud** [comment]
this issue does not exist in my environment

tested with node `v10.20.1` on Cloud9 and `v13.10.1` in mac os x.

Closing this issue tentatively.
