### ISSUE TITLE
Option to specify the --toolkit-bucket-name for every CDK command

### ISSUE THREAD

**Issue by oonisim** [aws/aws-cdk#7756]
Capability for user to control which the CDK toolkit bucket(or bootstrap bucket? -> Please unify the name either bootstrap or tool as it appears to be the same) to use for CDK commands.

### Use Case

For the CDK user to be able to control which S3 tookkit bucket to use for the CDK commands.

Currently CDK assumes (not sure why) an environment is (AWS account, AWS region) and creates a toolkit bucket accordingly per (account, region). 

* [cdk bootstrap](https://github.com/aws/aws-cdk/blob/master/design/cdk-bootstrap.md)
> cdk bootstrap is a tool in the AWS CDK command-line interface responsible for populating a given environment (that is, a combination of AWS account and region) with resources required by the CDK to perform deployments into that environment.

While isolating an environment and its assets within a (account, region) would be an appropriate practice, in reality there are situations where we need to put multiple environments in the same (account, region).

Then we need to put assets from different environments in the same bucket losing the isolation of the environments. 

Hence would like to create a toolkit bucket by explicitly specify the name and also be able to tell the CDK command (deploy, destroy, etc) which toolkit bucket to use.

### Proposed Solution

Add -toolkit-bucket-name to the commands that refers to the assets in the S3 toolkit bucket such as deploy.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by moatazelmasry2** [comment]
> While isolating an environment and its assets within a (account, region) would be an appropriate practice, in reality there are situations where we need to put multiple environments in the same (account, region).
Could you please elaborate on that statement. An environment in cdk IS just an account and a region. Could you give a more concrete example?

**Comment by shivlaks** [comment]
@oonisim can you expand on what you mean by `environment`
as @moatazelmasry2 asked, perhaps a concrete example with some minimal code would help clarify the feature request. 

is it to have a toolkit bucket per app / set of apps so all CDK instrumentation is contained to a user specified bucket?

**Comment by oonisim** [comment]
An "environment" in CDK is (AWS account, Region). There are "dev", "test", "stage", "prod" environments to go through and there are situations we need to put "test" and "stage" in the same (AWS account, region). 

We like to specify the bucket to use for "test" and "stage" separately we we run "cdk deploy" in the "test" directory and "stage" directory which deploy AWS resource in the same (account, region).
