### ISSUE TITLE
[EKS Feature] Cluster Version Pinning

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#7762]
The `Cluster` resource in the eks construct library allows us to create Amaozn EKS cluster without specifying the `version`, however, when we create self-managed ASG nodegroup we need specify the version before we can construct correct ssm parameter store path for the AMI, which at this moment will honor the hardcoded `LATEST_KUBERNETES_VERSION` variable. However, if we version bump `LATEST_KUBERNETES_VERSION`, users with existing cluster and nodegroup will risk upgrading their self-managed nodegroup k8s version. For example `1.14` to `1.15` or even `1.14` to `1.16`, while their cluster may remain `1.14`.

However, for the `Nodegroup` resource,  we don't have to specify the version as cloudformation will determine the version from the cluster, which ensures the version consistency.

I guess we might need to make the [version](https://github.com/aws/aws-cdk/blob/1b8236ed8c7daa7aa41a8fa215357fba92787bd4/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L146) property mandatory for `Cluster` and let users determine the version for their cluster as well as self-managed nodegroups if any.

### Benefits

1. cluster version, managed nodegroup version and self-managed nodegroup version would be all consistent
2. version pinning would be possible
3. no forced version upgrade for self-managed NG
3. would be able to construct correct ssm parameter store path based on the user-provided `version` 

### Other

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Yes, this is exactly what I was thinking. We should get make `version` a required argument. 

If we want a nice experience we can offer an extensible enum-like type, which is a common pattern we use:

```ts
export class KubernetesVersion {
  public static of(version: string) { return new KubernetesVersion(version); }
  public static V1_14 = KubernetesVersion.of(“1.14”);
  public static V1_15 = KubernetesVersion.of(“1.15”);

  private constructor(public readonly version: string) {}
}
```

**Comment by pahud** [comment]
@eladb Let me make it :-)

**Comment by abelmokadem** [comment]
Nice to see this one 👍

**Comment by pahud** [comment]
PR WIP. Will create a PR draft today.
