### ISSUE TITLE
init template unit tests in all languages.

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#7776]
Current init templates for Python and C# dont create any unit tests. Typescript and Java templates have minimal tests setup for users to reference when building on top of the template.

Add some minimal unit tests to the Python and C# init templates.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Confirming this is still valid

**Comment by MrArnoldPalmer** [comment]
@NGL321 looks like this still is valid as those templates don't include any test files. It likely isn't something we are going to do soon so I'm okay with closing if we want to revisit this at a later date. I changed it to `p2` and we can alternatively just leave it in the backlog.
