### ISSUE TITLE
Using custom resource automatically capitalizes property names when setting props

### ISSUE THREAD

**Issue by S5f20RNcyX** [aws/aws-cdk#7778]
Create a custom resource backed by lambda that looks for a property with lower case name.  When creating the resource the lambda expecting lower case property will fail.   

The lambda is controlled by another account so it isn't possible for me to update their lambda that backs the resource.  

Since it is a custom resource the cdk should not enforcing capitalization on property names because  it is not a requirement that they begin with uppercase.

### Reproduction Steps

Create a custom resource backed by a lambda that requires lowercase properties.
Create the resource in cdk and will fail with the resource that is not uppercase does not exist.

In the below error log ip_permissions is being set by the cdk to Ip_permissions.
### Error Log

Failed to create resource. 'ip_permissions'

### Environment

  - **CLI Version      1.36.1 (build 4df7dac)
  - **Lib     @aws-cdk/aws-cloudformation@1.36.1
  - **OS               macos (10.14.6)
  - **Language         Javascript

### Other

I just changed line 60 to ...props.properties || {} and it is now working as a workaround.

--- 

This is :bug: Bug Report

**Comment by S5f20RNcyX** [comment]
Looks like it related to ...uppercaseProperties(props.properties || {}) in line 60 of custom-resource.js

**Comment by eladb** [comment]
This has been addressed in #7736. If you use `core.CustomResource` capitalization is disabled by default.
