### ISSUE TITLE
APIGateway Type Error "addBasePathMapping is not a function"

### ISSUE THREAD

**Issue by baer** [aws/aws-cdk#7787]
`DomainName.fromDomainNameAttributes` created an object that does not have the method `addBasePathMapping`. This appears to be because the [fromDomainNameAttributes](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/domain-name.ts#L85-L93) returns a stripped-down version of [IDomainName](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/domain-name.ts#L57-L78), not the full-fledged one you would get from a DomainName created in the CDK stack. 

This may be intentional, or a missing feature in the construct but the docs for [BasePathMapping](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.BasePathMapping.html) say that "In most cases, you will probably want to use DomainName.addBasePathMapping() to define mappings" so it's not something I was expecting. If the intention is that CDK functions `*.from<AWS Service>Attributes` like this one or the one defined in VPC read-only, that should be a bit more clear in the docs if possible.

### Reproduction Steps
```js
const { DomainName } = require(`@aws-cdk/aws-apigateway`);

const myDomain = DomainName.fromDomainNameAttributes(
  this,
  `myDomainResource`,
  { domainName: CERTIFICATE_URL }
);
myDomain.addBasePathMapping(excelProxyApi, {});
```

### Error Log

```
/some/path/index.js:79
  myDomain.addBasePathMapping(excelProxyApi, {
                   ^
TypeError: excelProxyDomain.addBasePathMapping is not a function
```

### Environment

  - **CLI Version     :2.0.9
  - **Framework Version:1.36.1
  - **OS               :OSX
  - **Language         :JavaScript

### Other

Some of the comments in this thread seem to be from other people who are confused by the same problem. https://github.com/aws/aws-cdk/issues/3103

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This API is not supported on imported `DomainName`. Instead you can use the constructor for `BasePathMapping` to achieve this.

The 'most cases' in the docs probably refers to when the domain is created is defined as part of the CDK app, and not imported.

**Comment by baer** [comment]
@nija-at The reason for using one of CDK's `*.from<AWS Service>Attributes` is because I do not have the option of building it from inside of CDK. There are a number of reasons for this, such as:

* An "infrastructure stack" created a service that an "application stack" is using
* The service was created before CDK was brought into the organization
* You've acquired a team/project/company who has preexisting services
* etc. 

CloudFormation recently launched the ability to [import existing resources into a CloudFormation stack](https://aws.amazon.com/blogs/aws/new-import-existing-resources-into-a-cloudformation-stack/), CDK does not support this at the time of writing and `*.from<AWS Service>Attributes` is the next-best option. I'm only suggesting that some clarity in communication might help folks.

**Comment by nija-at** [comment]
Thanks for the clarification @baer. I believe you are able to use the `BasePathMapping` constructor for all these use cases. Perhaps dropping that entire statement there would help.

**Comment by nija-at** [comment]
Are you able to submit a PR to us with some better phrasing here?

**Comment by baer** [comment]
You're correct that the `BasePathMapping` constructor will work for these cases. I created a PR to suggest `addBasePathMapping` only if they're not importing the Domain

https://github.com/aws/aws-cdk/pull/8017

**Comment by nija-at** [comment]
Resolving since we got the doc updates in - https://github.com/aws/aws-cdk/pull/8017.
