### ISSUE TITLE
StepFunction Lambda Integration doesn't support default behavior

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#7801]
The default behavior for a StepFunction integration with Lambda is to wait for the execution to finish (can also be forced with appending the `.sync` to the Lambda Arn). Since [this commit](https://github.com/aws/aws-cdk/commit/a1d98845a209e7ed650d8adaaa1a724a3109b6a2) that feature [seems to have been removed](https://github.com/aws/aws-cdk/blob/a1d98845a209e7ed650d8adaaa1a724a3109b6a2/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts#L20). Now it appears that someone should specify `FIRE_AND_FORGET` for a Lambda if they actually want a synchronous execution. (I don't know how they would specify an actual "fire and forget" type integration)

Also, the CDK docs for SFN are inaccurate. The example given shows a `WAIT_FOR_TASK_TOKEN` type integration, but running that code will throw an error because the `Context.taskToken` is not specified in the example.

```text
Task Token is missing in payload (pass Context.taskToken somewhere in payload)
```

### Environment

  - **CLI Version      :1.36.0
  - **Framework Version:1.36.0
  - **OS               :Amazon Linux
  - **Language         :TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@richardhboyd - yeah that's a point of confusion. I'll update the docs as well. The `FIRE_AND_FORGET`, `WAIT_FOR_TASK_TOKEN`, `SYNC` options are "set" on any service integration and correspond to this [table](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-service-integrations.html)

For Lambda specifically, there's a parameter you need to set. The [`InvocationType`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.InvocationType.html) property can specify whether you want `Request_Response` (synchronous), `Event` (which is really asynchronous), or `Dry Run`. Correspond Step Functions [documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_RequestParameters)

I'll drop the `FIRE_AND_FORGET` from the README examples, but I think we probably also need to simplify as the direct translation of Step Functions documentation is confusing for the Lambda experience. I imagine there are probably other service integrations that have similar quirks

**Comment by shivlaks** [comment]
@richardhboyd - I also realized I included some examples of `WAIT_FOR_TASK_TOKEN` in the `aws-stepfunctions-tasks` README already so I updated the TypeScript example.

Let me know if there's anything else you had in mind here.
