### ISSUE TITLE
vpcOptions on ElasticSearch CfnDomain results in: You must specify exactly one subnet.

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#7804]
On setting up a CfnDomain (ES) i am getting a weird error message on the property vpcOptions.subnetIds. See the following code:

```
    createCfnDomainProps(domain: string, vpc: Vpc): CfnDomainProps {
        return {
            ...
            vpcOptions: {
                subnetIds: ["subnet-01e75096fa3XXXXXX", "subnet-0b16f9acYYYYYYY"],
            },
    }
```

According to docs stated on attribute subnetIds (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-vpcoptions.html#cfn-elasticsearch-domain-vpcoptions-subnetids) its stated that:

**SubnetIds**
Provide one subnet ID for each Availability Zone that your domain uses. For example, you must specify three subnet IDs for a three Availability Zone domain. To learn more, see VPCs and Subnets in the Amazon VPC User Guide.

So i added my two private Subnets of my VPC (its a 2AZ VPC) to that property and got this:

> You must specify exactly one subnet. (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: 68f95602-d3db-4270-896f-0aa5e9de0618)

### Reproduction Steps

see above.

### Error Log

You must specify exactly one subnet. (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: 68f95602-d3db-4270-896f-0aa5e9de0618)

### Environment

  - **CLI Version      :**
  - **Framework Version: 1.36.1 (build 4df7dac)**
  - **OS               : Mac OS x**
  - **Language         :**

--- 

This is :bug: Bug Report

**Comment by logemann** [comment]
Closing issue because most likely it is because my already defined ES domain only had instancecount == 1 which means i cant define two subnets.

**Comment by jimmy-pelago** [comment]
Same issue.
I can not define more than 1 subnet
