### ISSUE TITLE
StepFunction DynamoDB Integration prevents dynamic path references

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#7807]
When using the DynamoDB Tasks within StepFunctions-Tasks, we force users to use the [DynamoAttributeValue](https://github.com/aws/aws-cdk/blob/a1d98845a209e7ed650d8adaaa1a724a3109b6a2/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/call-dynamodb.ts#L83) but it prevents users from being able to [dynamically specify the values](https://docs.aws.amazon.com/step-functions/latest/dg/connect-ddb.html) by replacing the `"S"` with `"S.$"`

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
I can't reproduce this bug. I was able to correctly generate a state machine definition with `"S.$"` when a dynamic value was specified.

Here's my typescript app - 

```ts
import { AttributeType, Table } from '@aws-cdk/aws-dynamodb';
import { Data, StateMachine, Task } from '@aws-cdk/aws-stepfunctions';
import { CallDynamoDB, DynamoAttributeValue } from '@aws-cdk/aws-stepfunctions-tasks';
import { App, Stack } from '@aws-cdk/core';

const app = new App();
const stack = new Stack(app, 'mystack');

new StateMachine(stack, 'my-state-machine', {
  definition: new Task(stack, 'dynamo-putitem', {
    task: CallDynamoDB.putItem({
      tableName: 'my-table',
      item: {
        'p-key': new DynamoAttributeValue().withS(Data.stringAt('$.a'))
      }
    })
  })
});
```

and here's the snippet on my state machine - 

```
    "mystatemachine15ECA539": {
      "Type": "AWS::StepFunctions::StateMachine",
      "Properties": {
        "DefinitionString": {
          "Fn::Join": [
            "",
            [
              "{\"StartAt\":\"dynamo-putitem\",\"States\":{\"dynamo-putitem\":{\"End\":true,\"Parameters\":{\"Item\":{\"p-key\":{\"S.$\":\"$.a\"}},\"TableName\":\"my-table\"},\"Type\":\"Task\",\"Resource\":\"arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":states:::dynamodb:putItem\"}}}"
            ]
          ]
        },
```

Changing the code to use a static value automatically changes the `"S.$"` to `"S"` in the state machine definition.

**Comment by richardhboyd** [comment]
I just have missed the `Data` Class. Happy to close. Thanks Niranjan!!

On May 13, 2020, at 7:59 AM, Niranjan Jayakar <notifications@github.com> wrote:

﻿

I can't reproduce this bug. I was able to correctly generate a state machine definition with "S.$" when a dynamic value was specified.

Here's my typescript app -

import { AttributeType, Table } from '@aws-cdk/aws-dynamodb';
import { Data, StateMachine, Task } from '@aws-cdk/aws-stepfunctions';
import { CallDynamoDB, DynamoAttributeValue } from '@aws-cdk/aws-stepfunctions-tasks';
import { App, Stack } from '@aws-cdk/core';

const app = new App();
const stack = new Stack(app, 'mystack');

new StateMachine(stack, 'my-state-machine', {
  definition: new Task(stack, 'dynamo-putitem', {
    task: CallDynamoDB.putItem({
      tableName: 'my-table',
      item: {
        'p-key': new DynamoAttributeValue().withS(Data.stringAt('$.a'))
      }
    })
  })
});

and here's the snippet on my state machine -

    "mystatemachine15ECA539": {
      "Type": "AWS::StepFunctions::StateMachine",
      "Properties": {
        "DefinitionString": {
          "Fn::Join": [
            "",
            [
              "{\"StartAt\":\"dynamo-putitem\",\"States\":{\"dynamo-putitem\":{\"End\":true,\"Parameters\":{\"Item\":{\"p-key\":{\"S.$\":\"$.a\"}},\"TableName\":\"my-table\"},\"Type\":\"Task\",\"Resource\":\"arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":states:::dynamodb:putItem\"}}}"
            ]
          ]
        },


Changing the code to use a static value automatically changes the "S.$" to "S" in the state machine definition.
