### ISSUE TITLE
Support for "EnableCloudwatchLogsExports" on DBCluster type

### ISSUE THREAD

**Issue by adunne-resilient** [aws/aws-cdk#7810]
Currently, there is no way to specify the EnableCloudwatchLogsExports on the DatabaseCluster type. The alternative is to use the low-level CfnDBCluster instead.

I am proposing supporting this configuration parameter on the DatabaseCluster type. 

### Use Case

I need to use this configuration parameter as part of a DatabaseCluster type, and I do not want to have to revert to using CfnDBCluster.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Links for reference - 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enablecloudwatchlogsexports
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_LogAccess.html#USER_LogAccess.Procedural.UploadtoCloudWatch

**Comment by njlynch** [comment]
_Implementation Notes:_

For Aurora MySQL, the valid log types are: `["error","general","slowquery","audit"]`( _source: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.CloudWatch.html_). Of these, only `error` logging is enabled by default; `general` and `slowquery` logs must be enabled via MySQL commands and the `audit` logs require setup via the parameter group (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Auditing.html#AuroraMySQL.Auditing.Enable).

For Aurora PostgreSQL, the valid log type is only: `["postgresql"]` (_source: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.CloudWatch.html_).

**Comment by skinny85** [comment]
> For Aurora MySQL, the valid log types are: `["error","general","slowquery","audit"]`( _source: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.CloudWatch.html_). Of these, only `error` logging is enabled by default; `general` and `slowquery` logs must be enabled via MySQL commands and the `audit` logs require setup via the parameter group (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Auditing.html#AuroraMySQL.Auditing.Enable).

What does that mean, exactly? Does it mean that if I pass `'audit'` logs in `cloudwatchLogsExports`, but I don't set the correct parameter in the ParameterGroup, it won't do anything?

**Comment by njlynch** [comment]
> Does it mean that if I pass `'audit'` logs in `cloudwatchLogsExports`, but I don't set the correct parameter in the ParameterGroup, it won't do anything?

Exactly. It'll set the configuration, but as there aren't any audit logs generated, nothing will be created or exported to CloudWatch.
