### ISSUE TITLE
Tests fail in local environment when CDPATH is set and includes `.`

### ISSUE THREAD

**Issue by keithlayne** [aws/aws-cdk#7828]
I have CDPATH set for convenience.  This breaks at least one test script.

### Reproduction Steps

```sh
cd packages/@aws-cdk/aws-s3-deployment && CDPATH=.:/tmp /bin/bash lambda/test.sh
```

### Error Log

```
cp: /.../aws-cdk/packages/@aws-cdk/aws-s3-deployment/lambda is a directory (not copied).
```

### Environment

  - **CLI Version      : 1.37.0**
  - **Framework Version: N/A**
  - **OS               : OSX**
  - **Language         : bash**

### Other

At https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3-deployment/lambda/test.sh#L7

with `set -x` it's easy to see that `scriptdir` becomes

```
+ scriptdir='/.../aws-cdk/packages/@aws-cdk/aws-s3-deployment/lambda
/.../aws-cdk/packages/@aws-cdk/aws-s3-deployment/lambda'
```

(it's duplicated with a newline).  This causes the `cp -f` later to prepend the dir, trying to copy it in addition to its contents.

Possible fix:

```patch
diff --git a/packages/@aws-cdk/aws-s3-deployment/lambda/test.sh b/packages/@aws-cdk/aws-s3-deployment/lambda/test.sh
index a11706a3c..f2b02d657 100755
--- a/packages/@aws-cdk/aws-s3-deployment/lambda/test.sh
+++ b/packages/@aws-cdk/aws-s3-deployment/lambda/test.sh
@@ -4,7 +4,7 @@
 #
 # prepares a staging directory with the requirements
 set -e
-scriptdir=$(cd $(dirname $0) && pwd)
+scriptdir=$(CDPATH= cd -- "$(dirname "$0")" && pwd -P)

 # prepare staging directory
 staging=$(mktemp -d)
```

--- 

This is :bug: Bug Report

**Comment by keithlayne** [comment]
Grepping the codebase shows that various incarnations of "find the script dir" are used in ~66 different files.  I'm not really sure what the one above has issues, it seems to be somehow inheriting my shell's env where others are not.  The only other problem I've run into in my environment is at https://github.com/aws/aws-cdk/blob/master/scripts/check-api-compatibility.sh#L5 - my build made it that far before failing because it couldn't find some files I think.

I'm trying a new run via `CDPATH= yarn build` to see if that works.  I guess I can report back in about 2 hours.

**Comment by keithlayne** [comment]
Another probable fix is to just unset `CDPATH` or export it with no value in `build.sh`.

**Comment by keithlayne** [comment]
Figured out it wasn't that `CDPATH` is set, but that it includes `.` (which is pretty common AFAIK).  Also confirmed that running `CDPATH= yarn build` succeeds.

**Comment by keithlayne** [comment]
I appreciate that this issue doesn't seem to be affecting anyone else, but it was pretty annoying for me - I wasn't able to follow the docs successfully.  I can send a small documentation PR if that's okay - @shivlaks do you have a preference on what that would look like?  I figure these are the options:

1. Add a note about if you have `CDPATH` set and it includes `.` (99.99% can ignore)
2. Just change the command to `CDPATH= yarn build` (safe to copy/paste...but probably not on Windows?)

**Comment by shivlaks** [comment]
@keithlayne - that sounds like a good start to start with a documentation PR with the options
