### ISSUE TITLE
[ElasticBeanstalk] RDS instance is not getting created inside the Elastic Beanstalk Environment

### ISSUE THREAD

**Issue by yatendragoel** [aws/aws-cdk#7838]
### The Question
RDS instance is not getting created inside the Elastic Beanstalk Environment but the rest of the Beanstalk environment is getting created successfully with the sample application working.

Here's how I am adding the options list to the Elasticbean Environment:

    private static List<Object> getRDSMySQlConfigs() {

            List<Object> ebEnvConfigs = new ArrayList<>();
		
		String rdsNamespace = "aws:rds:dbinstance";
		
		ebEnvConfigs.add(getOptionSetting(
				rdsNamespace,
				"DBEngine", "mysql"));
		
		ebEnvConfigs.add(getOptionSetting(
				rdsNamespace,
				"DBUser", "abc"));
		
		ebEnvConfigs.add(getOptionSetting(
				rdsNamespace,
				"DBPassword", "abc"));
		
		ebEnvConfigs.add(getOptionSetting(
				rdsNamespace,
				"DBDeletionPolicy", "Snapshot"));
		
		return ebEnvConfigs;
    }

    private static OptionSettingProperty getOptionSetting(String namespace, String optionName
			, String optionValue) {
		return getOptionSetting(namespace, optionName, optionValue, "");
	}
	
	private static OptionSettingProperty getOptionSetting(String namespace, String optionName
			, String optionValue, String resourceName) {
		return OptionSettingProperty.builder()
				.namespace(namespace)
				.optionName(optionName)
				.value(optionValue)
				.build();
	}

### Environment

  - **CDK CLI Version:** tried with both `1.36.1` and `1.37.0`
  - **Module Version:** 
  - **OS:** OSX Mojave
  - **Language:** Java

**Comment by skinny85** [comment]
Hello @yatendragoel ,

can you explain what error you get when you try to create the RDS resources inside the BeanStalk environment?

Thanks,
Adam

**Comment by yatendragoel** [comment]
No Error. As per the CDK CLI and the Cloudformation Events, the template request is executed successfully. When I go to the EB Env -> Configuration -> RDS, I don't find any RDS instance.

**Comment by neat-interactions** [comment]
Same problem over here

**Comment by nija-at** [comment]
It looks like you're using the `@aws-cdk/aws-elasticbeanstalk` module here. Unfortunately, we don't have higher level support for this module which means all the code you're using is autogenerated based off the CloudFormation spec. CDK does not add any additional logic on top of this.

Please check that the generated CloudFormation template is configured as you would have expected. It's unlikely that there would be discrepancy between the CloudFormation template and the CDK application. However, if you do find something please report back with more information around a snippet of the CloudFormation template and at least of the CDK app that produced it so we can take a look.

If everything seems in order and the problem still persists, this is unlikely a problem with the CDK and you will need to contact CloudFormation or ElasticBeanstalk via AWS support to help you with this.

Sorry, we're not able to help further here.

**Comment by HoukasaurusRex** [comment]
I experience this as well when deploying a db instance through the `@aws-cdk/aws-elasticbeanstalk` module. The cloudformation template generated in`cdk.out` seems to have a complete rds configuration, however no database is actually created. In the Cloudformation console, there are also no logs for deployed databases under the rds namespace.

Here is a gist of the cloudformation template generated by the elasticbeanstalk module: https://gist.github.com/HoukasaurusRex/4c57905fe6a52c984b30654bf719bbc6

**Comment by matiasvarela** [comment]
I'm having exactly the same problem. RDS Is not created using cdk (v2.80.0). Is there any known solution?
