### ISSUE TITLE
CDK init has snapshot dependency

### ISSUE THREAD

**Issue by vpoetai** [aws/aws-cdk#7844]
CDK init --language java creates a java project with compile errors caused by an snapshot dependency for Jackson. CDK version 1.37.0 (build e4709de)

The following artifacts could not be resolved: com.fasterxml.jackson.core:jackson-core:jar:2.11.0-SNAPSHOT, com.fasterxml.jackson.core:jackson-databind:jar:2.11.0-SNAPSHOT: Could not find artifact com.fasterxml.jackson.core:jackson-core:jar:2.11.0-SNAPSHOT

**Comment by shivlaks** [comment]
@vpoetai - can you provide a bit more detail on the repro steps for this behaviour that you're observing?

I tried to run through last few versions with:

```
> cdk init --l java
> mvn package
```

my output looks like the following
```
 mvn package                 
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.myorg:javasampleappagain >--------------------
[INFO] Building javasampleappagain 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ javasampleappagain ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/shiv/code/may/javasampleappagain/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ javasampleappagain ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ javasampleappagain ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/shiv/code/may/javasampleappagain/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ javasampleappagain ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ javasampleappagain ---
[INFO] Surefire report directory: /Users/shiv/code/may/javasampleappagain/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.myorg.JavasampleappagainStackTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.273 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ javasampleappagain ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.717 s
[INFO] Finished at: 2020-05-08T20:49:39-07:00
[INFO] ------------------------------------------------------------------------
```

Note that my java version is `1.8`

**Comment by abhinavdigital1** [comment]
@shivlaks I faced the above issue as well. 

`$ cdk init app --language java

Applying project template app for java
Executing mvn package...
[ERROR] Failed to execute goal on project cdk-sample: Could not resolve dependencies for project com.myorg:cdk-sample:jar:0.1: Could not find artifact com.fasterxml.jackson.core:jackson-databind:jar:2.11.0-SNAPSHOT -> [Help 1]
`
java version "1.8.0_211"

Unable to install the jackson-databind 2.11.0-SNAPSHOT

**Comment by shivlaks** [comment]
@abhinavdigital1 can you provide a bit more information? are you still facing this?
I'm trying to repro with the same versino of java and am not running into this issue.

can you also share your Node.js, CLI, and your Maven versions

**Comment by abhinavdigital1** [comment]
@shivlaks  - 

$ node --version
v10.16.0

$ mvn --version
Apache Maven 3.5.2 

$ cdk --version
1.45.0 (build 0cfab15)

The issue still exists and the work around I did was excluded the jackson dependency that comes along the cdk core.

<dependency>
            <groupId>software.amazon.awscdk</groupId>
            <artifactId>core</artifactId>
            <version>${cdk.version}</version>
            <exclusions>
            <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                           <artifactId>jackson-databind</artifactId>
            </exclusion>
            </exclusions>
        </dependency>
              <dependency>
                     <groupId>com.fasterxml.jackson.core</groupId>
                     <artifactId>jackson-databind</artifactId>
                     <version>2.11.0</version>
        </dependency>

**Comment by shivlaks** [comment]
@abhinavdigital1 thanks for the additional information! I'll dig a bit more and update when I reproduce the issue.

**Comment by gallaharsha** [comment]
I see the same issue on my machine.

**Comment by techthumb** [comment]
Same issue

```
$ cdk version
1.71.0 (build 953bc25)
```

**Comment by shivlaks** [comment]
@techthumb can you also share your maven and java version(s) ? 
i still haven't been able to reproduce this issue - help me find what i'm missing please!!
