### ISSUE TITLE
Running "cdk synth" can fail due to expired security credentials

### ISSUE THREAD

**Issue by ivoanjo** [aws/aws-cdk#7849]
Hello there!

We're using the CDK to generate some CloudFormation before we actually apply it, and whenever we try to use `cdk synth` and happen to have some old security credentials around our build fails with `The security token included in the request is expired`.

This shouldn't really fail the build since we're not actually doing anything to our account.

### Reproduction Steps

1. Have an `.aws/credentials` file with expired credentials
2. Run `cdk synth`

### Error Log

`The security token included in the request is expired`

### Environment

  - **CLI Version      :** 1.32.1
  - **Framework Version:** 1.32.1
  - **OS               :** Ubuntu 16.04.6 LTS
  - **Language         :** Java

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@ivoanjo thanks for reporting this issue! I'll take a deeper look into it by starting with a minimal repro.

Does your application make use of any of the [runtime context](https://docs.aws.amazon.com/cdk/latest/guide/context.html#context_methods) methods?

**Comment by asterikx** [comment]
@shivlaks My app doesn't make use of context methods. I experienced the same issue.

**Comment by ivoanjo** [comment]
> Does your application make use of any of the runtime context methods?

No, it doesn't. It can run fully offline.

**Comment by srikanthse** [comment]
I think similar to this, it happens when I attempt to login for the first time using `aws configure` and cancel login midway (without entering password and do a `ctrl+c`) and run `cdk synth` , it throws the same error.

**Comment by charlie-harvey** [comment]
I was using version 1.31.0 (and others previous to that) and `cdk synth` was working great. It didn't actually try to reach out to AWS to do anything. Which makes sense, I am only _synthesizing_ my app so I can take a look at the cloudformation template files.

But ever since upgrading to 1.42.1 (and newer), `cdk synth` now reaches out to AWS for some bizarre reason. I think that is where this issue is coming from. People who were using this peacefully at home now need credentials just to synth.

Try downgrading your deps.

Thanks.

**Comment by ivoanjo** [comment]
@charlie-harvey You don't really need the credentials -- if you go into the `.aws` directory and delete the outdated credentials, then `cdk synth` will happily succeed.

**Comment by charlie-harvey** [comment]
So, outdated credentials makes it fail, but no credentials is ok? Zoinks. How do I force it to not check?

Thanks - makes some kind of sense.

**Comment by ivoanjo** [comment]
> How do I force it to not check?

If you find that, you've fixed the bug ;)

**Comment by Stompf** [comment]
My work around for this was to add a profile that does not exist in the cdk.json file:

```
{
    "app": "ts-node index",
    "versionReporting": false,
    "profile": "do-not-exist"
}
```

**Comment by charlie-harvey** [comment]
Seemed ok in 1.60.0 but went bad again in 1.61.1.
