### ISSUE TITLE
consider parsing --tags with alternative to split

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#7852]
cdk deploy --tags team=Org=dev:Team=Aaron owner=user1234

results in resources will be tagged with team=Org and the rest is truncated because the current split operation limits to 2 dumps the remainder

also, using split removes the = totally which I would not expect to the intended parsing

### Reproduction Steps

deploy as follows

cdk deploy --tags team=Org=dev:Team=Aaron owner=user1234

view the result of the following line:

const tags = this.parseStringTagsListToObject(argv);

### Error Log

No error message.  Expected results differ.

### Environment

  - **CLI Version: 1.37.0 (build e4709de)
  - **Framework Version: nA
  - **OS:
             ProductName:    Mac OS X
             ProductVersion: 10.14.6
             BuildVersion:   18G1012
  - **Language: javascript

### Other

my local fix is the following:

```
    static parseStringTagsListToObject(argv) {
        const tags = [];
        for (const assignment of (argv.tags || [])) {
            const key  = assignment.match(/^[^=]*/)[0];
            const value = assignment.replace(/.*?=/, '');
            if (key && value) {
                logging_1.debug('CLI argument tags: %s=%s', key, value);
                tags.push({
                    Key: key,
                    Value: value
                });
            }
            else {
                logging_1.warning('Tags argument is not an assignment (key=value): %s', assignment);
            }
        }
        return tags;
    }
```

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@S5f20RNcyX thanks for reporting!  that's not ideal as `=` characters are valid to use in the tag value
