### ISSUE TITLE
CI build of PR is throwing error on Lint issue which isn't in adherence with lint convention of repo

### ISSUE THREAD

**Issue by SachinShekhar** [aws/aws-cdk#7886]
On my [recent PR](https://github.com/aws/aws-cdk/pull/7878), CI build is throwing [these errors](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=44d5374f-6f2b-4525-ae4d-79d26c9eca10%2Fbuild.log):

```
@aws-cdk/aws-appsync: /codebuild/output/src548895071/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts
@aws-cdk/aws-appsync:   294:56   error  Missing trailing comma                          comma-dangle
@aws-cdk/aws-appsync:   295:10   error  Missing trailing comma                          comma-dangle
@aws-cdk/aws-appsync:   315:1    error  Expected indentation of 12 spaces but found 14  @typescript-eslint/indent
```
First, why is build checking linting issues? I thought there was already a lint bot acting on PRs.

Second, if you look at [tslint.yaml file](https://github.com/aws/aws-cdk/blob/master/tslint.yaml#L40) in this repo, you'll find this:

```yaml
# Trailing comma gets into a fight with itself when splitting lists over multiple lines
    trailing-comma: false
```
Why this conflicting behavior? Please, choose one.

**Comment by shivlaks** [comment]
@SachinShekhar - we run several linters during build. As mentioned in our [`CONTRIBUTING` ](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#eslint) guide, we're in the midst of moving over to using eslint.

Learn more about the [deprecation of TSLint](https://medium.com/palantir/tslint-in-2019-1a144c2317a9)

The PR linter GitHub actions do not cover the scenarios linked above. They're evaluated as part of the PR build.

The rule you're running into comes from [here](https://github.com/aws/aws-cdk/blob/master/tools/cdk-build-tools/config/eslintrc.js#L38)

Based on your stack trace from the build you've linked, you should be able to run the failing command that ended with error code 1 again with `--fix` to fix your files up.
```
aws-cdk/aws-appsync: âœ– 26 problems (26 errors, 0 warnings)
@aws-cdk/aws-appsync:   26 errors and 0 warnings potentially fixable with the `--fix` option.
@aws-cdk/aws-appsync: Error: /codebuild/output/src548895071/src/github.com/aws/aws-cdk/node_modules/eslint/bin/eslint.js . --ext=.ts --resolve-plugins-relative-to=/codebuild/output/src548895071/src/github.com/aws/aws-cdk/tools/cdk-build-tools/lib exited with error code 1
@aws-cdk/aws-appsync: Build failed. ${timers.display()}
@aws-cdk/aws-appsync: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Hopefully that answers all your questions!
