### ISSUE TITLE
cdk deploy in AWS CodeBuild

### ISSUE THREAD

**Issue by IndikaUdagedara** [aws/aws-cdk#7889]
### The Question
`cdk deploy` fails on CodeBuild when build and deploy are run in different stages (different CodeBuild projects). [Replicated with a minimal cdk app.](https://github.com/IndikaUdagedara/CDKSample) 

### Environment

  - **CDK CLI Version:** 1.38
  - **OS:** Ubuntu (aws/codebuild/standard2.0 docker image)
  - **Language:** Typescript

### Other information
I'm trying to run `cdk deploy` in CodePipeline on a CodeBuild action. To replicate the issue I created a minimal cdk app with `cdk init`
```
├── README.md
├── app
│   ├── cdk.d.ts
│   ├── cdk.js
│   └── cdk.ts
├── cdk.context.json
├── cdk.json
├── jest.config.js
├── lib
│   ├──stack.d.ts
│   ├──stack.js
│   └──stack.ts
├── package-lock.json
├── package.json
├── test
│   ├── cdk.test.d.ts
│   ├── cdk.test.js
│   └── cdk.test.ts
└── tsconfig.json
```

The pipeline has 2 stages that use CodeBuild.
1. Build stage: Build the app and publish artifact

```
# buildspec
version: 0.2
phases:

  install:
    runtime_versions:
      nodejs: 12

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - npm install
      - npm run build
artifacts:
  base-directory: ${CODEBUILD_SRC_DIR}
  files:
    - '**/*'
```
Note: all files are copied (with `**/*`) including source and the compiled files.

2. Deploy stage: Run `cdk deploy`

```
# buildspec
version: 0.2
phases:

  install:
    runtime_versions:
      nodejs: 12
    commands:
      - npm install -g aws-cdk 
      - npm install -g typescript
      - cdk --version

  build:
    commands:    
      - cd ${CODEBUILD_SRC_DIR}/cdk
      - cdk ls
      - cdk deploy

```

However, any `cdk` command (`ls`/`deploy`) throws the following error.
```

[Container] 2020/05/09 10:20:45 Running command cdk --version
--
28 | 1.38.0 (build d5fa31f)
...
[Container] 2020/05/09 10:20:45 Running command cdk  ls
--
39 | Cannot find module './index'
40 | Subprocess exited with error 1
```

The build and deploy steps run as expected locally so I'm quite puzzled why it doesn't work on CodePipeline. 

I'm quite sure this has nothing to do with `cdk` itself but something's going wrong when artifacts are copied between CodeBuild projects. When build and deploy steps are run in the same CodeBuild stage it also works fine but this is not how I (and believe most others) would be using cdk to deploy applications, i.e. one build stage and multiple deploy stages for different environments.

Also, it would be good if there was an example in cdk documentation for running `cdk deploy` in CodePipeline. The current CodePipeline [example](https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html) uses a synthesized cloudformation template from build stage and deploys using Cloudformation in the deploy stage. This is not how I'd prefer to use cdk (why would you use `cloudformation deploy` when there is `cdk deploy` 😉 ).

**Comment by skinny85** [comment]
Hi @IndikaUdagedara ,

I believe the problem is extremely simple: you're missing compiling your files from TypeScript to JavaScript.

Can you show your `package.json` and `cdk.json` files?

Thanks,
Adam

**Comment by IndikaUdagedara** [comment]
Thanks @skinny85 I was quite sure this is something pretty simple but was scratching my head trying to figure out what...

```
$ cat cdk.json
{
  "app": "npx ts-node bin/cdk_sample.ts",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true"
  }
}
```
```
$ cat package.json
{
  "name": "cdk_sample",
  "version": "0.1.0",
  "bin": {
    "cdk_sample": "bin/cdk_sample.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assert": "1.38.0",
    "@types/jest": "^25.2.1",
    "@types/node": "10.17.5",
    "jest": "^25.5.0",
    "ts-jest": "^25.3.1"
  },
  "dependencies": {
    "@aws-cdk/aws-codebuild": "^1.38.0",
    "@aws-cdk/aws-codecommit": "^1.38.0",
    "@aws-cdk/aws-codepipeline": "^1.38.0",
    "@aws-cdk/aws-codepipeline-actions": "^1.38.0",
    "@aws-cdk/core": "1.38.0",
    "source-map-support": "^0.5.16",
    "aws-cdk": "1.38.0",
    "ts-node": "^8.1.0",
    "typescript": "~3.7.2"
  }
}
```

The weird thing is, if I run the build and deploy in the same stage it works fine but when I run build in one stage (CodeBuild project) copy everything (`${CODEBUILD_SRC_DIR}`) to deploy stage (CodeBuild project) it fails at the `cdk` command.  Here's a ready to run [sample](https://github.com/IndikaUdagedara/CDKSample)

**Comment by skinny85** [comment]
First of all - I would not `np install -g` packages, ever. Run `npm run cdk ...` instead.

Second, I'm a little worried about this statement:

> The strange thing is, if I run the build and deploy in the same stage it works fine but when I run build in one stage (CodeBuild project) copy everything (${CODEBUILD_SRC_DIR}) to deploy stage (CodeBuild project) it fails at the cdk command

First of all, why do this? And second, can you show how are you doing the copying?

What you want to do, is have the directory `cdk.out` from the `npm run cdk synth` command (called the Cloud Assembly), and then pass that in the `--app` argument to `cdk deploy`: `npm run cdk deploy <stack_name> --app cdk_out_dir`.

**Comment by IndikaUdagedara** [comment]
> First of all - I would not np install -g packages, ever. Run npm run cdk ... instead.

May be this shows my lack of experience with js/npm ecosystem.. I'm installing `cdk` globally so I can run `cdk deploy` instead of `npm run cdk` (this is what the [docs](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html) suggest too). Is the latter best practice?

The files are coped by the `artifacts` section in[ `buildspec.yml` ](https://github.com/IndikaUdagedara/CDKSample/blob/master/buildspec.yml)
```
artifacts:
  base-directory: ${CODEBUILD_SRC_DIR}
  files:
    - '**/*'
```

The reason I'm doing that is: I want to build once (`npm run build`) and use the same artifacts to deploy to multiple environments e.g. `cdk deploy Staging-App` then `cdk deploy Production-App` 

What I didn't actually think about is doing `cdk synth` in build stage and using `cdk deploy --app` to deploy those artifacts as you suggested. I guess that's the right approach to go about what I'm trying to do. Can you give me a hint on what I could possibly have been doing wrong (in doing `npm run build` and copying npm artifacts to deploy as opposed to doing what you suggested)? May be I misunderstood the lifecycle of a cdk app. I didn't realise `cdk synth` is necessary unless you want the cloudformation templates to be generated before hand and assumed `cdk deploy` does synthesis and deploy in one go.

**Comment by skinny85** [comment]
> May be this shows my lack of experience with js/npm ecosystem.. I'm installing cdk globally so I can run cdk deploy instead of npm run cdk (this is what the docs suggest too). Is the latter best practice?

If you run `npm install -g aws-cdk`, you will get the latest version of the CLI package, which might not be the same as the version you have in your `package.json`. Running `npm run cdk ...` after `npm install` ensures the version of the CDK (and same goes for TypeScript) is the one you've specified in `package.json`, which means everything is under version control - the entire point of Infrastructure as Code.

Notice that you linked to the "Getting started" guide. "Deploying my CDK app in CodePipeline" is not the same as "Getting started" 🙂.

> I didn't realise `cdk synth` is necessary unless you want the cloudformation templates to be generated beforehand. I assumed `cdk deploy` does synthesis and deploy in one go.

You're right - `cdk synth` is not required, `cdk deploy` does synthesis and deploy in one go. But why do synthesis over and over needlessly? You're just making your deployments slower. It's much better to `synth` in the build stage, and then just work on the Cloud Assembly (the contents of the `cdk.out` directory).

> So if synth is not really required why doesn't it work when the 2 steps are run in 2 directories that are supposedly identical because all files are copied from one to the other? I wonder if some files are missing when CodeBuild uploads artifacts but I'm not sure what.

That I don't know. Maybe do an `ls -al` in your build, and make sure all of the files you expected to see are there? Or, just hook up your `cdk deploy` stages directly to the source Action (if you're not using the output of the Cloud Assembly from `cdk.out`, I don't see much gain in having a build stage at all).

**Comment by IndikaUdagedara** [comment]
Thanks @skinny85 - I have the build stage to build the application in addition to the cdk app. Building the application takes quite some time so want to keep it separate. I'll follow your suggestion
1. build the cdk app and `cdk synth` and copy `cdk.out` as a stage artifcat (in build stage)
2. deploy the synthesized app to each environment (Staging, Production etc.) with `npm cdk deploy --app`

**Comment by skinny85** [comment]
No problem @IndikaUdagedara , good luck, let us know if you manage to make it work!

**Comment by IndikaUdagedara** [comment]
Apparently as someone suggested in [SO](https://stackoverflow.com/questions/61678086/aws-cdk-deploy-in-codepipeline-codebuild/61768828) this is due to an issue in CodeBuild where symlinks are not copied to artifacts. This clears my doubts 😉  

Still, copying the synthesized output (rather than just the compiled app) seems to be the right thing as avoiding the same steps in multiple deploy stages is what I wanted to avoid.

**Comment by skinny85** [comment]
Oh yeah, that explains it!

**Comment by hom-bahrani** [comment]
> What you want to do, is have the directory `cdk.out` from the `npm run cdk synth` command (called the Cloud Assembly), and then pass that in the `--app` argument to `cdk deploy`: `npm run cdk deploy <stack_name> --app cdk_out_dir`.

this was really helpful thanks, but the documentation doesn't mention this https://docs.aws.amazon.com/cdk/latest/guide/hello_world.html
