### ISSUE TITLE
📊Tracking: AWS CodeGuru Profiler

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#7914]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

Amazon CodeGuru Profiler collects runtime performance data from your live applications, and provides recommendations that can help you fine-tune your application performance. Using machine learning algorithms, CodeGuru Profiler can help you find your most expensive lines of code and suggest ways you can improve efficiency and remove CPU bottlenecks.

[AWS Docs](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html)  

### Maturity: CloudFormation Resources Only

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codeguruprofiler-readme.html) for more implementation details.

### Issue list:

- [ ] https://github.com/aws/aws-cdk/issues/6984 

--- 
This is a  📊Tracking Issue

**Comment by SeekerWing** [comment]
some baby steps have been taken at https://github.com/aws/aws-cdk/issues/6984 and https://github.com/aws/aws-cdk/issues/8851
