### ISSUE TITLE
Missing aws_cdk.aws_ses.TemplateProperty in Python

### ISSUE THREAD

**Issue by pberman-aws** [aws/aws-cdk#7916]
You seem to be missing this type definition in Python despite the definition in the Typescript docs https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ses.CfnTemplate.TemplateProperty.html. As such, I am not able to build an SES template successfully without overriding prop values. Is this by design?

### Environment

  - **CLI Version      :** 1.18.28
  - **Framework Version:** 1.32.2
  - **OS               :** MacOS 10.14.6
  - **Language         :** Python 3.7.4

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @pberman-aws. This unfortunately is a known issue with our Python documentation:

**Comment by iliapolo** [comment]
Related to https://github.com/aws/aws-cdk/issues/7463

**Comment by iliapolo** [comment]
Closing as duplicate of #7463 (kind of)
