### ISSUE TITLE
Stabilize API Gateway v2 module

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#7917]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

[AWS Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html) for more implementation details.

**Comment by SomayaB** [comment]
Duplicate of #6830

**Comment by xazhao** [comment]
The API Gateway v2 module has been stabilized. Closing the issue
