### ISSUE TITLE
State machine chaining gives an error "State 'X' already has a next state

### ISSUE THREAD

**Issue by harmohan-a** [aws/aws-cdk#7920]
### The Question
I was trying to create a state machine:
```
step1
.next(condition check (false), step1)
.next(step2).
.next(succeed("we are done"))
```
From the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html#task-chaining) i should be able to have steps after a conditional check.
but when i try to implement this, i get the error `State 'step1' already has a next state`
I dont think its an issue with the conditional step calling the first step again because this works

```
step1
.next(condition check (false), step1)
```

### Environment

  - **CDK CLI Version:** 1.36.1
  - **Module Version:** 1.36.1
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by shivlaks** [comment]
@harmohan-a [conditions](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Condition.html) are used with a Choice state but I can't quite see where that is in your sample snippet.

An example of the structure is in the [task chaining](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html#task-chaining) section of the documentation.

Can you share some code of your chain's definition?

**Comment by sudopla** [comment]
I believe this is currently a limitation in CDK Step Functions. If you try to use next(State1) more than once in the workflow you will get the following error `State 'State1' already has a next state`. This is related to this same issue - https://github.com/aws/aws-cdk/issues/9843

**Comment by rafalkrol-xyz** [comment]
I was able to make it work, with cdk `1.103.0 (build bc13a66)`, by appending `next` to [the `LambdaInvoke` class](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.LambdaInvoke.html) in the `const` declaration:

```typescript
const lambda1Step = new tasks.LambdaInvoke(this, 'Do something cool', {
  lambdaFunction,
}).next(lambda2Step)
```

Before, when trying to use `lambda1Step.next(lambda2Step` multiple times in my [State Machine's definition](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.StateMachine.html#definition) I was getting the `State 'lambda1Step' already has a next state` error that @sudopla mentioned.
