### ISSUE TITLE
Tags are not applied to EBS Volumes attached to EC2 instances

### ISSUE THREAD

**Issue by GrahamLea** [aws/aws-cdk#7930]
An EBS Volume created when a BlockDevice is added to an EC2 Instance does not have any tags applied, including a Name.

### Reproduction Steps

Create a stack that includes an EC2 Instance that has tags and a BlockDevice.
Deploy it.
Check the tags.

### Expected:
As with other resources, EBS Volumes should be tagged according to the scope they're in.
* EBS Volume should have the same tags as the Instance
* Also, EBS Volume should have a Name tag

### Tailgating Feature Request:
* It should probably be possible to remove some of the instance tags from the Volume, or have the BlockDevice inherit its tags from a specified scope rather than the Instance. It doesn't seem like it would be possible with the current API because BlockDevice is not a Construct.

### Environment

  - **CLI Version      :** 1.36.1
  - **OS               :** MacOS
  - **Language         :** Java

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I believe adding tags to EBS volumes is not possible in CloudFormation yet. Please correct me if I am mistaken.

**Comment by GrahamLea** [comment]
It looks like there's tags on AWS::EC2::Volume but not on AWS::EC2::Instance's BlockDeviceMapping.
So perhaps it's actually a request for the CFN team, rather than CDK? 😬

**Comment by J-Swift** [comment]
Semi related, semi not: it appears the standard tags (`aws:cloudformation:logical-id`, `aws:cloudformation:stack-name`, `aws:cloudformation:stack-id`) are applied to `AWS::EC2::Volume` but setting `volumeName` does not result in a tag of `Name` being applied. You have to manually add a `Name` tag.

**Comment by chris-bateman** [comment]
So is this something that has been escalated to the CFN team?
Ran into this issue today.

**Comment by finneon** [comment]
No way to tag BlockDeviceVolume so far, CFN function might  work but I'm using IInstance

**Comment by kashif-malik-data-engineering** [comment]
I am facing the same issue, I can see tags on the instance but none on the EBS Volume when creating the Instance in CDK. What is the best possible way to do that for now, if this feature is not yet implemented in CDK? thank you

**Comment by judebert** [comment]
The `Tags.of()` method lets me tag a `Volume`, but there's no way to convert that to a `BlockDevice` or `BlockDeviceVolume`, so it can't be attached to a `Instance`. Everything is in `software.amazon.awscdk.services.ec2`, so I'm really struggling to understand why they don't work together.

**Comment by GrahamLea** [comment]
It looks like this has been been fixed, though in an optional way, with the addition of `Instance.Builder. propagateTagsToVolumeOnCreation()` ?

**Comment by peterwoodworth** [comment]
Yes, this was shipped and is supported on the `propagateTagsToVolumeOnCreation` prop

**Comment by GrahamLea** [comment]
⚠️ WARNING:
For those who wanted this and now see that it is available, be aware that if you set this property to true on an _existing_ Instance and `deploy`, CDK will **DELETE AND RE-CREATE** the Instance!
So, you should only add this on new Instances, or on Instances which you are fine to trash and re-create from scratch.
