### ISSUE TITLE
S3Integration Object, extending apigateway.AWSIntegration 

### ISSUE THREAD

**Issue by dferguson992** [aws/aws-cdk#7938]
URL Path Parameter mapping for S3 Path Overrides for S3 API Gateway Integration requests.  At this time there is no way to deploy an API that maps URL path parameters to S3 Path Override variables.  This makes it difficult to create API endpoints that interact with S3 by proxy.

### Use Case

I need this feature to create an API Gateway endpoint that uploads files to an S3 bucket for downstream processing.  This is necessary because the process that uploads these files is external to the AWS infrastructure and our data store lives on S3.

### Proposed Solution

Create a class aws_apigateway package called S3Integration.  It would be similar to and extend  the AwsIntegration object:

```ts
export class S3Integration extends AWSIntegration
```

This class would explicitly set URL Path Parameter mappings to S3 Integration Path Overrides.  This allows for subtle, nuanced S3 proxies hosted on API Gateway and deployed via CDK

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Thanks for filing this issue. Look forward to seeing a PR for this 😊

**Comment by sachingill** [comment]
Is there any update for this. As I have similar use case and I need to create an API and map URL path parameters to the required S3 prefix.

**Comment by dferguson992** [comment]
No updates, thankfully my work has picked up a lot since the original submission so I haven't had much time to invest in this, unfortunately.  I will try to pick this up over the upcoming holidays.
