### ISSUE TITLE
Cognito: add username case sensitivity configuration

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#7945]
Implement the username case sensitivity [configuration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html) in the Cognito L2 constructs.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
This has been implemented here - https://github.com/aws/aws-cdk/commit/460394f3dc4737cee80504d6c8ef106ecc3b67d5.

It will be available with the next release of the CDK.

**Comment by emonhaider** [comment]
@nija-at I have this property set to true in CDK but the user pool doesn't seem to reflect that and I am still able to create user with same email address with different casing. Any idea how to address this issue?

CDK:
![image](https://user-images.githubusercontent.com/1793646/115179953-21f45300-a09a-11eb-9000-f077d1e977bb.png)

Cloudformation:
![image](https://user-images.githubusercontent.com/1793646/115179326-b52c8900-a098-11eb-9a6d-286c05cc1ec6.png)

User pool:
![image](https://user-images.githubusercontent.com/1793646/115179364-cd040d00-a098-11eb-86f6-73e6f44de559.png)
