### ISSUE TITLE
PrivateDNS support for VPCEndpointService construct

### ISSUE THREAD

**Issue by tsykora-verimatrix** [aws/aws-cdk#7954]
VPCEndpointService construct works well but it lacks PrivateDNS support so service consumers need to use the long generated DNS name which can change when redeploying the endpoint service. AWS supports PrivateDNS functionality for custom endpoint services.
Would it be possible to add PrivateDNS (with DNS validation) support to VPCEndpointService construct?

### Use Case

Service consumers can consume endpoint service via friendly private DNS name instead of generated DNS name that can change (which impacts any application that is using it).

### Proposed Solution

add support for PrivateDNS with validation to VPCEndpointService construct.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Looks like this was completed via https://github.com/aws/aws-cdk/pull/10780.
