### ISSUE TITLE
removalPolicy: RemovalPolicy.RETAIN

### ISSUE THREAD

**Issue by skulljoi** [aws/aws-cdk#7955]
When I try to import the resource like Table I cant access some methodos like addGlobalSecondaryIndex because its part of Table and not TableBase, the same for S3 Bucket but with addEventNotification

### Reproduction Steps

this.bucket = new Bucket(this, name, {
                bucketName: 'name',
                removalPolicy: RemovalPolicy.RETAIN
            })
this.bucket.addEventNotification(EventType.OBJECT_CREATED, new SnsDestination(topic))

deploy and destroy this stack. Then you can try to redeploy without success because you already have the resource, then you change your stack to

this.bucket = Bucket.fromBucketName(this, id, 'name') as Bucket;
this.bucket.addEventNotification(EventType.OBJECT_CREATED, new SnsDestination(topic))

but method does not exists error

### Error Log

TypeError: this.bucket.addEventNotification is not a function

### Environment

  - **CLI Version      :aws-cli/2.0.3 Python/3.7.5 Windows/10 botocore/2.0.0dev7
  - **Framework Version: cdk 1.38.0 (build d5fa31f)
  - **OS               :windows 10
  - **Language         :typescript

### Other

I not sure if this is a bug, but this is the only way I had found in the cdk documentation to use an existent resouce.
If this is not a BUG how can I reuse the resource left by the removalPolicy: RemovalPolicy.RETAIN and reattach it to the stack?

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@skulljoi 

The ability to adopt a resource into the stack is being tracked in aws/aws-cdk-rfcs#52

As you've gone through the exercise, you're right that existing resources that you're referencing using the `fromXyZ` methods which represent an object that can be used in your stack. In this case it's an [`IBucket`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.ITable.html). You can use methods to add grants and metrics on it.

The resource (table) itself is not governed by a stack (and therefore CDK).

**Comment by shivlaks** [comment]
Closing for now, feel free to reopen if you have any outstanding questions.
