### ISSUE TITLE
Use Multiple Lambdas When Role is Specified

### ISSUE THREAD

**Issue by starsolutions** [aws/aws-cdk#7956]
When using aws-cdk/custom-resource with a specified role, I think we should not be using the singleton lambda, since it means that only the first role specified the first time a custom resource is instantiated with a given stack is used for all downstream custom resources.

This is not ideal for those of us who want to have roles granting specific privileges and have a need for multiple custom resources with varying as it requires us to build a role with all of the privileges upfront.

### Use Case

If I am trying to use an API call that requires additional privileges, I want to be able to be specific when specifying the privileges.  Only allowing one role to be specified prevents me from having multiple custom resources that have separate roles.

### Proposed Solution

Split the creation of the lambda, such that a singleton lambda is only created if a role is not specified.  If a role is specified, then make a separate individual lambda for this resource using that role. That way if a role is specified the user is guaranteed that the resource will be created with that role, but if it is not specified the user doesn't lose any automated functionality.

### Other

I would imagine that a change like this would be required to implement https://github.com/aws/aws-cdk/issues/5173 as role assumption would also run into similar issues, and most likely not be desired for all resources in a given stack.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Which specific construct in @aws-cdk/custom-resources are you referring to?

**Comment by McDoit** [comment]
@starsolutions This is fixed by #13916
You can specify role per action for optimal separation!
