### ISSUE TITLE
Add PubliclyAccessible to InstanceProps type

### ISSUE THREAD

**Issue by adunne-resilient** [aws/aws-cdk#7958]
Currently, there is no way to specify the PubliclyAccessible value for instances within a DatabaseCluster type (defaults to false). The alternative is to use the low-level Cfn types instead.

I am proposing supporting this configuration parameter on the InstanceProps type, or, alternatively, on the DatabaseCluster type for all instances in that cluster.

### Use Case

I need to use this configuration parameter as part of a DatabaseCluster type, and I do not want to have to revert to using CfnDBCluster.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
You need to use the `vpcSubnets` prop to control whether your instances will be launched privately or publicly

https://github.com/aws/aws-cdk/blob/e93da2cf48a297b31f2ca0c1e96b905fc128914b/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L504

https://github.com/aws/aws-cdk/blob/e93da2cf48a297b31f2ca0c1e96b905fc128914b/packages/%40aws-cdk/aws-rds/test/integ.cluster.ts#L28-L31

**Comment by adunne-resilient** [comment]
That's great. Thank you for the information.
