### ISSUE TITLE
eks cluster to support private endpoint access

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#7972]
Add `endpointPrivateAccess` support for EKS cluster creation.

It's currently not possible to create an Amazon EKS cluster with private-only endpoint with AWS CDK and this gap stops some users and customers from using aws-eks construct lib to create their EKS cluster.

### Use Case

To secure the cluster endpoint in private network when creating the cluster with AWS CDK.

### Proposed Solution

To expose an additional property for `Cluster` resource.

Will make sure the kubectl provider in Lambda with vpc support can connect to the eks private endpoint. https://github.com/aws-samples/aws-lambda-layer-kubectl/issues/32

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Yeah the tricky part will be the lambda custom resources inside the vpc. That one will be fun!

**Comment by pahud** [comment]
Hi @eladb 

Looks like the custom-resource provider will be in a nested stack and we can't just pass the props.Vpc as `IVpc` from parent stack to nested stack. Is there any sample or pattern for this scenario? I need to pass the Vpc to the custom resource provider so it can create the Lambda function  with this Vpc.

https://github.com/aws/aws-cdk/blob/d126c46f8429b30e1937e2e970011bc6fac8b5a2/packages/%40aws-cdk/aws-eks/lib/cluster-resource-provider.ts#L17

thanks

**Comment by eladb** [comment]
You should technically be able to just reference the `vpc` object in the custom resource and the framework should rely all the information from the parent stack through paramaters.

**Comment by eladb** [comment]
Let's continue the discussion over #5220...

**Comment by iliapolo** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/9095
