### ISSUE TITLE
Creating Route53 A record for ApiGateway with aws-route53-targets ignores domain prefix

### ISSUE THREAD

**Issue by jimfum** [aws/aws-cdk#7982]
Using route53-targets with ApiGateway doesn't create the expected A record. Instead of abc.mycompany.com a record just for mycompany.com is created.

### Reproduction Steps

```
import * as targets from '@aws-cdk/aws-route53-targets';
import * as apigw from '@aws-cdk/aws-apigateway';

...

const api = new apigw.RestApi(this, 'tracking-proxy', {
  restApiName: "cdk-test",
  domainName: {
	domainName: 'abc.mycompany.com',
	certificate: cert,
  }
});
new route53.ARecord(this, 'tracking-route-record', {
  zone: hostedZone,
  target: route53.RecordTarget.fromAlias(new targets.ApiGateway(api))
});
```
### Environment

  - **CLI Version      :** 1.38.0
  - **Framework Version:** 1.38.0
  - **OS               :** Windows 10
  - **Language         :** Typescript

This is :bug: Bug Report

**Comment by jimfum** [comment]
Solved by adding `recordName: 'abc.mycompany.com'` property to route53.ARecord call.

**Comment by rob3c** [comment]
I also solved the problem by adding an explicit `recordName` value. Did you ever find an explanation for why this wasn't automatically assigned the api's `domainName` by default? It seems like the kind of smart-defaults boilerplate reduction the cdk aspires to.
