### ISSUE TITLE
ApplicationLoadBalancedFargateService does not allow targetGroup to have protocol/port other than HTTPS/80

### ISSUE THREAD

**Issue by jackm-ts** [aws/aws-cdk#7989]
The target group props listed here should be configurable by the ApplicationLoadBalancedFargateServiceProps. We have use cases where our containers are accepting traffic on HTTPS. 

https://github.com/aws/aws-cdk/blob/4e8271944468253f686bfc16e51b0d9c7bedd5bf/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L319-L321

**Comment by SoManyHs** [comment]
I believe this is addressed in https://github.com/aws/aws-cdk/pull/7417

**Comment by jtwolgamott** [comment]
Ran into this as well. My ApplicationLoadBalancedFargateService has the following definition:
`ecs_patterns.ApplicationLoadBalancedFargateService(
            self,
            "MyService",
            service_name=f"my-service-{env}",
            cluster=cluster,
            memory_limit_mib=1024,
            cpu=512,
            task_image_options=ecs_patterns.ApplicationLoadBalancedTaskImageOptions(
                image=ecs.ContainerImage.from_ecr_repository(
                    my_service_repo, tag=env
                ),
                container_port=443,
            ),
            domain_name="my-domain-name.com",
            domain_zone=route53.HostedZone.from_hosted_zone_attributes(
                self,
                "MyZone",
                hosted_zone_id=config["HOSTED_ZONE_ID"],
                zone_name=config["ROOT_DOMAIN"],
            ),
            security_groups=[ecs_sg],
            certificate=my_certificate,
            listener_port=443,
            protocol=elasticloadbalancingv2.ApplicationProtocol.HTTPS,
            redirect_http=True,
        )`

When I `synth` this, I get a Target Group with `Protocol: "HTTP"` and `Port: 80` as follows:
`    "MyServiceLBPublicListenerECSGroup29B5BAF2": {
      "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
      "Properties": {
        "HealthCheckPath": "/",
        "HealthCheckProtocol": "HTTP",
        "Matcher": {
          "HttpCode": "200,204"
        },
        "Port": 80,
        "Protocol": "HTTP",
        "TargetType": "ip",
        "VpcId": {
          "Fn::ImportValue": "my-vpc:ExportsOutputRefmihiniosvpcdevB1F54EAE4F14EF21"
        }
      },
      "Metadata": {
        "aws:cdk:path": "my-stack/MyService/LB/PublicListener/ECSGroup/Resource"
      }
    },`

I can't seem to find any way to set the Target Group Port and Protocol...

**Comment by jtwolgamott** [comment]
@MrArnoldPalmer @uttarasridhar Also, can we please change the issue title? I think @jackm-ts intended "HTTP/80" rather than "HTTPS/80".

**Comment by jtwolgamott** [comment]
https://github.com/aws/aws-cdk/pull/7417 Does not seem to relate to this: 7417 is related to the container listener not the Target Group listener, which this issue specifically pertains to.

**Comment by hoegertn** [comment]
Also #11381
