### ISSUE TITLE
[aws-eks] Allow user to configure source for KubectlLayer

### ISSUE THREAD

**Issue by kaylanm** [aws/aws-cdk#7992]
Currently the source of `KubectlLayer` is not configurable and it is not present in some AWS partitions.

### Use Case

To use programmatic kubectl support in AWS partitions where `aws-lambda-layer-kubectl` must be deployed manually, the source must be configurable.

### Proposed Solution

Export `KubectlLayer` and allow it to take a prop that overrides the source.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@pahud is this something you'd like to pick up?

**Comment by pahud** [comment]
@eladb Absolutely!
