### ISSUE TITLE
EKS: kubectlEnabled: false conflicts with addNodegroup

### ISSUE THREAD

**Issue by kaylanm** [aws/aws-cdk#7993]
Disabling `kubectlEnabled` conflicts with `addNodegroup`.

It is not possible to set `kubectlEnabled: false` and use `cluster.addNodegroup()` (including via `defaultCapacity`) due to the fact that `addNodegroup` initializes `awsAuth` for the cluster, which is incompatible with `kubectlEnabled: false`.

### Reproduction Steps

```
import * as cdk from '@aws-cdk/core';
import { Cluster } from '@aws-cdk/aws-eks';

export class TestCdkEksStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new Cluster(this, 'Cluster', {
      kubectlEnabled: false,
    });
  }
}
```

Setting `defaultCapacity: 0` prevents the error. Creating a `Nodegroup` construct without using `addNodegroup()` does not trigger the issue.

### Error Log

```
Cannot define aws-auth mappings if kubectl is disabled
```

### Environment

  - **CLI Version      :** 1.38.0
  - **Framework Version:** 1.38.0
  - **OS               :** macOS 10.15.4
  - **Language         :** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@pahud could you take a look at this?

**Comment by eladb** [comment]
@kaylanm as a workaround, you should be able to define the NodeGroup separately:

```ts
new eks.NodeGroup(this, 'MyNodeGroup', {
  cluster: myCluster,
  // options...
});
```

**Comment by eladb** [comment]
@pahud this line looks peculiar to me:

https://github.com/aws/aws-cdk/blob/1bfe70a66d1e1f19b514e412d5689d76057fb172/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L514

Can you explain why is this needed?

**Comment by pahud** [comment]
@eladb I believe it shouldn't be there. PR underway.
