### ISSUE TITLE
Support Secret with partial Arn

### ISSUE THREAD

**Issue by tuler** [aws/aws-cdk#7994]
When a container in a `TaskDefinition` uses a secret, it automatically adds to the taskDefinition generated `ExecutionRole` the IAM [permission to read the secret value](https://github.com/aws/aws-cdk/blob/ca90f5b8650815641c761eee9fa7d565ce0bc20c/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L394).

If the secret is imported from an existing resource, by using `secretsmanager.Secret.fromSecretAttributes` or `secretsmanager.Secret.fromSecretArn` the Arn can be an [partial Arn](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#API_GetSecretValue_RequestSyntax), without the `-` and 6 random chars AWS appends to the friendly name.

The problem is that [Secret.grantRead](https://github.com/aws/aws-cdk/blob/ca90f5b8650815641c761eee9fa7d565ce0bc20c/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L132) gives permission to the exact Arn only, so the task fails to execute.

### Use Case

It's common to use partial Arn when using secrets, because they represent friendly names.
### Proposed Solution

I tried to manually add a more relaxed policy to the taskDefinition execution role, but it did not work.

```
taskDefinition.addToExecutionRolePolicy(new iam.PolicyStatement({
  actions: ["secretsmanager:GetSecretValue"],
  resources: [secretArn + '*'],
}));
```

I don't know why it did not work, or if this is the best approach.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Related: #7444, https://github.com/aws/aws-cdk/issues/6889#issuecomment-604277642
