### ISSUE TITLE
Can't attach CfnAutoScalingGroup to an ECS Cluster

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#8005]
### Use Case

I've created an ASG via **CfnAutoScalingGroup** for my EC2 ECS hosts, why ? : 
- AutoScalingGroup Construct do not provide launch-templates
- aws-autoscaling.BlockDevice do not provide use of CMK
- aws-ecs.AddCapacityOptions don't provide UserData

So, I've created all my needed resources :
- **ASG** (_CfnAutoScalingGroup_, _autoscaling.CfnScheduledAction_)
- **Launch-template** (_CfnLaunchTemplate_)
- **UserData** (with Agent + custom configuration; CloudWatch for example)
- **Secrets** (secretsmanager.Secret)
- **KeyPair** (CustomResource.AwsCustomResource)
- **CMK** (kms.Key)
- **SSM** (ssm.StringParameter)
- **SGR** (SecurityGroup)
- **IAM** (iam.ManagedPolicy, iam.Role, _iam.CfnInstanceProfile_)
- **LogGroup** (logs.LogGroup)
- **EFS** (efs.FileSystem)
- **Cloudwatch** (logs.MetricFilter, cloudwatch.Alarm, cloudwatch.Metric, CloudwatchActions.SnsAction)
- **ACM** (certificatemanager.Certificate)
- **ALB** (elbv2.ApplicationLoadBalancer, elbv2.ApplicationTargetGroup)
- **ECS** (ecs.Cluster, ecs.TaskDefinition, ecs.ContainerDefinition, ecs.Ec2Service)

After all that resources creation, the last to be created is the **ecs.Ec2Service**, but unfortunatly, I have this error : 
`Cluster for this service needs Ec2 capacity. Call addXxxCapacity() on the cluster.`

Of course, my Cluster have my EC2 container instance up & available.

### Proposed Solution

You already have feature requests opened (some from me) for : 
- launch-template
- BlockDevice  (CMK)
- EFS (CMK from another account)

It'll also be interesting to be able to have : 
_UserData_ prop in **aws-ecs.AddCapacityOptions**.

Without these updates, I'm blocked.

And be able to attach an ASG to an ECS Service by Ref (his name in our case) ?

### Other

But now, how after all that lines of Typescript code... What can I do to have my ECS Service created ?

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
Related https://github.com/aws/aws-cdk/issues/1711
