### ISSUE TITLE
RDS password generation with option `excludePunctuation: true`

### ISSUE THREAD

**Issue by ivawzh** [aws/aws-cdk#8006]
I'd want to be able to configure the automatically-generated password for the RDS database. Especially being able to set `excludePunctuation: true` as a usual secretmanager string generation.  

### Use Case

Many languages and database clients have problems reading passwords with punctuations. Apps (e.g. Rails, Hasura, etc) will crash at runtime when a password happens to contain punctuations.

### Proposed Solution

Support some `SecretProps` in `RdsProps`, like 

```ts
       includeSpace: false,
       excludePunctuation: true,
       requireEachIncludedType: true,
```

---

This is a :rocket: Feature Request

**Comment by nicostouch** [comment]
I just hit this bug aswell. RDS generated a password including a character that caused my .NET Core application to crash when supplying the connection string to Npgsql.
