### ISSUE TITLE
Arn.format docs imply that stack is optional - mismatch with signature

### ISSUE THREAD

**Issue by scubbo** [aws/aws-cdk#8016]
This is a 📕 documentation issue

[Relevant snippet](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/arn.ts#L75-L79).

This issue has been opened purely for tracking purposes - I'm already working on the fix (and have confirmed via discussion with CDK developers that this is indeed incorrect). I made this a "Documentation issue" rather than a "Bug fix" (even though it represents "code not working as intended"), because the Bug fix template required steps-to-reproduce and they would be trivial in this case - "write code which does not pass a Stack to the method, and observe your IDE complaining"

**Comment by scubbo** [comment]
Hmm, ok - I tried implementing this as follows:

```
[Lines 75-85 of /aws-cdk/packages/@aws-cdk/core/lib/arn.ts]
   * The required ARN pieces that are omitted will be taken from the stack that
   * is passed in. If all required ARN pieces are supplied, the supplied stack can be 'undefined'.
   */
  public static format(components: ArnComponents, stack?: Stack): string {

    if (stack === undefined && (
      components.partition === undefined ||
      components.region === undefined ||
      components.account === undefined)) {
      throw new Error('Partition, Region, and Account must all be provided if stack is absent');
    }

---

[Lines 260-297 of /aws-cdk/packages/@aws-cdk/core/test/test.arn.ts]
  'stack can be omitted if partition, region, and account are provided'(test: Test) {

    const components: ArnComponents = {
      partition: 'aws',
      service: 'a4b',
      region: 'region',
      account: 'accountid',
      resource: 'resourcetype',
      resourceName: 'resource',
      sep: '/',
    }

    Arn.format(components) // No stack

    test.done();
  },

  'stack must be present if any of (partition, region, or account) are missing'(test: Test) {

    let components: ArnComponents = {
      partition: 'aws',
      service: 'a4b',
      region: 'region',
      account: 'accountid',
      resource: 'resourcetype',
      resourceName: 'resource',
      sep: '/',
    };

    for (const key of ['partition', 'region', 'account']) {
      let value = components[key];
      delete components[key];
      test.throws(Arn.format(components));
      components[key] = value;
    }

    test.done();
  },
```

but this gave errors both from the build output:

```
lib/arn.ts:87:83 - error TS2532: Object is possibly 'undefined'.

87     const partition = components.partition !== undefined ? components.partition : stack.partition;
                                                                                     ~~~~~
lib/arn.ts:88:74 - error TS2532: Object is possibly 'undefined'.

88     const region = components.region !== undefined ? components.region : stack.region;
                                                                            ~~~~~
lib/arn.ts:89:77 - error TS2532: Object is possibly 'undefined'.

89     const account = components.account !== undefined ? components.account : stack.account;
```

and in lines 290-293 of the test:

```
TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'ArnComponents'.   No index signature with a parameter of type 'string' was found on type 'ArnComponents'.
```

I don't know enough about TypeScript to know how to tell the compiler(?) that, no, `stack` cannot possibly be `undefined` in a way that matters at that point. [This answer](https://stackoverflow.com/a/15264573/1040915) suggests that I could change lines 87-89 to be `const foo = components.foo !== undefined ? components.foo : stack?.foo;` - but I'd like to get input from someone who actually knows what they're doing on whether that's correct.

As for the "No index signature" error - I've got no idea. 4.10 [here](http://bartvds.github.io/tsspec-html/0.9.1/dist/expressions.html) says "_If IndexExpr is a string literal_ [**which it is**] _or a numeric literal and ObjExpr is of a type that has a property with the name given by that literal (converted to its string representation in the case of a numeric literal)_ [**which it does**] _, the property access is of the type of that property._", so I'm not sure why I'm getting this error (in particular, string indices shouldn't come into play at all, since that bullet is lower down the specification) - but, in order to get this working, I'll just make three separate assertions (and hope for some guidance from a TypeScript guru during review!

**Comment by scubbo** [comment]
According to [this](https://stackoverflow.com/a/7020734/1040915), I also need to do:

```
test.throws(function() {test.throws(Arn.format(components))});
```

to avoid the error "bubbling up"? That can't be right...

**Comment by scubbo** [comment]
Apologies for the repeated closed Pull Requests - I had been assuming that `../../../scripts/buildup` would also run linters and tests, so it was only when I made a PR and got a failing build that I found a) I needed to run linters manually, and then b) that hitting "Run" from Cloud9 does not, in fact, run tests (note to self, it's `npm run build && npm run test`, from inside `~/environment/aws-cdk/packages/@aws-cdk/core`)

**Comment by scubbo** [comment]
Closing as duplicate of [this](https://github.com/aws/aws-cdk/pull/8022).

**Comment by peterwoodworth** [comment]
Per elad, changing the docs here is the right way to go about this. This is a pretty simple change, I'll assign this to myself so I can get to it at some point
