### ISSUE TITLE
APIGW - Method.methodArn not replacing path parameters with asterisks

### ISSUE THREAD

**Issue by willdady** [aws/aws-cdk#8036]
API Gateway `Method.methodArn` incorrectly returns the ARN with named path parameters where they should have been replaced with asterisk.

For example, currently returning this:

```
arn:aws:execute-api:ap-southeast-2:000000000000:trjpwtzjyb/prod/PUT/foo/{myvariable}/bar
```

Should be this:

```
arn:aws:execute-api:ap-southeast-2:000000000000:trjpwtzjyb/prod/PUT/foo/*/bar
```

### Reproduction Steps

```typescript
// SNIP
const method = resource.addMethod(props.method, integration, {
  authorizationType: apigateway.AuthorizationType.IAM,
});

authenticatedRole.addToPolicy(
  new iam.PolicyStatement({
    actions: ['execute-api:Invoke'],
    effect: iam.Effect.ALLOW,
    resources: [method.methodArn], // <- WRONG
  })
);

```

### Environment

  - **CLI Version      :** 1.33.1
  - **Framework Version:** 1.33.1
  - **OS               : ** Linux mint
  - **Language         : ** Typescript

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
@willdady - can you also include code on how you constructed this `Method` class and all of its constructor properties?

**Comment by nija-at** [comment]
Update - I was able to reproduce this error and the fix is here - https://github.com/aws/aws-cdk/pull/8206
