### ISSUE TITLE
Step Functions service integration for CodeBuild tasks

### ISSUE THREAD

**Issue by shivlaks** [aws/aws-cdk#8043]
AWS Step Functions recently announced support for calling [CodeBuild](https://docs.aws.amazon.com/step-functions/latest/dg/connect-codebuild.html) directly from a state machine.

### Use Case

It's powerful to be able to call CodeBuild as part of a state machine, specifically to manage builds as part of larger workflows.

per the what's new announcement: 
> Using AWS CodeBuild integration, you can easily create workflows with primitives such as branching, parallel execution, and timeouts to handle software changes from different repository branches. 

> AWS Step Functions supports built-in error handling, parameter passing, recommended security settings, and state management, reducing the amount of code you have to write and maintain.

### Proposed Solution

Support calling CodeBuild APIs through the service integration pattern in `aws-stepfunctions-tasks` Full table of supported APIs is available [here](https://docs.aws.amazon.com/step-functions/latest/dg/connect-codebuild.html)

- [ ] StartBuild
- [ ] StopBuild
- [ ] BatchDeleteBuilds
- [ ] BatchGetReports

---

This is a :rocket: Feature Request

**Comment by reisingerf** [comment]
Any update on this?
Or suggestions for possible workarounds?

We'd like to use this integration in a project in active development. A timeline (or alternative if needed) would be much appreciated.

**Comment by shivlaks** [comment]
@reisingerf I'm on it and will have it int' PR this week.

In terms of workaround, check out the escape hatch to use a [`Custom State`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html#custom-state) for scenarios where CDK first class support is not available yet (for full service integrations, APIs, parameters, etc). You could create a custom task state by supplying the JSON definition of the Amazon States Language (ASL).

The [Step Functions Console](https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-code-snippet.html#tutorial-code-snippet-1) provides code snippets that can be generated and plugged in.

**Comment by reisingerf** [comment]
@shivlaks thanks for the update! A PR this week sounds great!

**Comment by shivlaks** [comment]
@reisingerf - ran into some delays, but haven't forgotten about this. This integration is back in focus for me and I'm actively working on it

**Comment by reisingerf** [comment]
Thanks for the update!

**Comment by DaWyz** [comment]
I had to call CodeBuild StartBuild in one my CDK App recently. Decided to try to implement it myself. I will surely need to do some updates on the PR I just pushed.
