### ISSUE TITLE
@aws-cdk/ecs: Override container name

### ISSUE THREAD

**Issue by karupanerura** [aws/aws-cdk#8044]
Allow to override container name by constructor property.

### Use Case

With the current implementation, these will be the same value implicitly.
This is confusing for our team because the naming conventions for the names in our current(exists) configuration and the Construct IDs are different.
So we need to manage the Construct ID and the name separately.

### Proposed Solution

Add `containerName` property to `ContainerDefinitionProps` and override `containerName` by this.

```typescript
this.containerName = props.containerName ?? this.node.id;
```
https://github.com/aws/aws-cdk/blob/v1.39.0/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L380

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by timohirt** [comment]
Hey folks! 👋 

Can I help here to get this done? It doesn't look too hard. I would volunteer to implement it and open a PR. What do you think?

**Comment by karupanerura** [comment]
Great! Unfortunately, I haven't been able to find the time to work on it. So I'm happy if you work on it.

**Comment by timohirt** [comment]
@karupanerura looking forward to your feedback. I just copy and paste your code in the description.

**Comment by karupanerura** [comment]
Looks good!

**Comment by timohirt** [comment]
So, what to do next? This is my first contribution to CDK. Do you review / approve the PR, do I need to find someone else, or are there reviews who will pick up the PR eventually?

**Comment by karupanerura** [comment]
please fix it: https://github.com/aws/aws-cdk/runs/2216420393

**Comment by timohirt** [comment]
This error is already fixed. I don't think this is a feature and thus changed the title of the PR.

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/aws-cdk/issues/13681

**Comment by betancourtl** [comment]
Was this ever merged? Are we able to change the container name using overrides?
