### ISSUE TITLE
secretsmanager.Secret support name prefix on creation

### ISSUE THREAD

**Issue by ranman** [aws/aws-cdk#8050]
I'd like to be able to call:
```
this.secret = new secretsmanager.Secret(this, "somesecret", {
  prefix: "/production/MyApp/"
})
```

That way I still get a unique name but I can have an app specific prefix to make it easier to find my secret.

### Use Case

I don't want to specify a name for my secret - I want the autogenerated one. I do want my secret to be name spaced to the prefix I use for other components.

### Proposed Solution

Modify: https://github.com/aws/aws-cdk/blob/v1.39.0/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L219-L222

To accept a prefix:

e.g.

```
  constructor(scope: Construct, id: string, props: SecretProps = {}) {
    super(scope, id, {
      physicalName: `{props.secretPrefix || ""}props.secretName`,
    });
```

? I'm not really sure if that is the right way to do it - I am not a typescript expert.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hi @ranman ,

thank you for the feature request, but this is not possible using the CDK today 😕. CDK relies on CloudFormation to generate physical names on our behalf, and you can't really control the exact name it generates. Generally, the name usually contains the stack name and the logical ID of the resource, but there's no way to give it a well-known prefix.

Apologies I don't have better news here.

Thanks,
Adam

**Comment by ranman** [comment]
@skinny85 are you certain on that one?

I can add prefixes to different constructs using the method I showed above... why not secrets?

My idea, given the nature of secrets manager, is to just make that prefix a prop instead of making folks extend the default secrets construct just for this functionality.

**Comment by skinny85** [comment]
Yes, I am. Your method is not adding a prefix, you're just setting the physical name to a specific value (`${props.prefix}${id}` in your case).

**Comment by ranman** [comment]
Gotcha so the physical name is enough for me in this case because with secrets manager most customers organize their secrets (and/or parameters in SSM) by "/" delimited namespaces.

So this:
```typescript
import * as cdk from "@aws-cdk/core";
import * as secretsmanager from "@aws-cdk/aws-secretsmanager";

export interface IRandallSecret extends secretsmanager.SecretProps {
  readonly prefix?: string;
}
export class RandallSecret extends secretsmanager.Secret {
  public readonly prefix?: string;

  constructor(scope: cdk.Construct, id: string, props: IRandallSecret) {
    const superProps = {
      ...(props.prefix && { secretName: `${props.prefix}${id}` }),
      ...props,
    };
    super(scope, id, superProps);
  }
}

export class SecretsmanagertestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new RandallSecret(this, "supersecret", {
      prefix: "/prod/something/",
    });
  }
}
```

Results in this:
<img width="206" alt="Screenshot 2020-06-29 14 56 20" src="https://user-images.githubusercontent.com/175163/86060097-ec9e4c00-ba18-11ea-967b-e966d988a0fe.png">

Which is the desired outcome.


Since this pattern of prefixing is so common among parameters and secrets I was thinking the L2 construct could support a "prefix" prop to enable this.

**Comment by skinny85** [comment]
I'm sorry, but I don't see a point in the class `RandallSecret`. It's the same as doing

```ts
new secretsmanager.Secret(this, 'supersecret', {
  secretName: '/prod/something/supersecret',
});
```

**Comment by ranman** [comment]
Right, but I don't want to specify the secretName most of the time - most of the time I just want to make sure it is in the same namespace as the other things in the stack. If I specify the name then, with tokenization, it gets harder to deal with importing/exporting later.

The only reason I need the "RandallSecret" is that I can't set a namespace for the secret in the existing Secret construct.

I don't care what the name of the secret is - I just want to make sure it's in the right namespace. This means I can restrict which IAM users can access it and update it with a single namespace based policy.

**Comment by skinny85** [comment]
> Right, but I don't want to specify the secretName most of the time - most of the time I just want to make sure it is in the same namespace as the other things in the stack. If I specify the name then, with tokenization, it gets harder to deal with importing/exporting/updating later.

Sorry, I don't understand what you're saying here. `RandallSecret` is also passing `secretName`. It's right there in the constructor. So there is no difference in tokenization anywhere.

> I don't care what the name of the secret is - I just want to make sure it's in the right namespace. This means I can restrict which IAM users can access it and update it with a single namespace based policy.

I hope it's clear that was just an example. You're free to model this how you want. For example:

```ts
new secretsmanager.Secret(this, 'supersecret', {
  secretName: `${props.namespace}/supersecret',
});
```

**Comment by thetoolsmith** [comment]
@skinny85 I'm not following the solution. From what I can tell, and correct me if I'm wrong. 

Using the cdk secretsmanager.Secret() class does NOT allow us to specify a secret value. It generates this error: Object literal may only specify known properties, and 'secretValue' does not exist in type 'SecretProps'.

Using the L1 CfnSecret class does allow us to specify the secretValue. But, it does NOT allow us to specify the secretName. It throws this error: Object literal may only specify known properties, and 'secretName' does not exist in type 'CfnSecretProps'

So PLEASE correct me if I am wrong, but it seems that in neither of these two implementations can we specify BOTH the secretName and secretValue.
I totally agree with @ranman in that having automation create secrets in the form of foo/bar/my-secret-key-name is a very common practice. And doing this allows us to perform lookups on "known" secrets and retrieve the values.

Am I missing something here?

**Comment by skinny85** [comment]
@thetoolsmith I believe what you want is the [`name` property of the `CfnSecret`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_secretsmanager.CfnSecret.html#name) class. [`secretName` is used by the `Secret` class](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_secretsmanager.Secret.html#secretname).

**Comment by thetoolsmith** [comment]
@skinny85 The problem with the name property of the CnfSecret class is this... "Secrets Manager automatically adds a hyphen and six random characters after the secret name at the end of the ARN". 
So when using that class we cannot create a secret key name of our own choosing. We can specify the prefix, but Secrets Manager always appends a random string. This doesn't work well when you need a known keyname for lookup to get a secret value.

In contrast, the problem with the secretName property of the Secret class is that it does NOT allow us to specify the secretValue. I get this error: Object literal may only specify known properties, and 'secretValue' does not exist in type 'SecretProps'.
The doc also says we can set secretStringValue, https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-secretsmanager.SecretProps.html#secretstringvalue.But I get the same error when trying to set this.
So maybe I just haven't found the way to do it yet, but the goal is simple....Create a Secret in Secrets manager where I can specify the exact keyname (aka secret name) AND specify an exact secret value (not take an auto-generated one from AWS).
Is this possible? If so, I haven't been able to find an example.

**Comment by skinny85** [comment]
No, it is not possible. This is just how the SecretsManger service works; there is nothing CDK-specific here (using `secretName` and `Secret` will result in the same suffix being added to the ARN).

May I ask why is the suffix a problem?

**Comment by thetoolsmith** [comment]
@skinny85 We have other pieces of code that use discovery of "known" secret names. So not being able to lookup a secret by name because of the random added suffix breaks that flow. This is a pretty standard use of a secret store from my perspective. In any case, I've found a way to do what I wanted using the SecretStringValueBeta1 class in aws-cdk-lib/aws-secretsmanager lib.
This code lets us create secret names and values of our choosing without the added random characters that otherwise would have been added.
```
import { Secret, SecretStringValueBeta1 } from 'aws-cdk-lib/aws-secretsmanager'

const secretkey = '/my/product/secrets/test-user'
const myname = 'paul'
const myid = '999'
const secret = SecretStringValueBeta1.fromToken(JSON.stringify({ id: myid, name: myname })) 
new Secret(this, secretkey, {
  secretName: secretkey,
  secretStringBeta1: secret,
  description: `test user name ${myname}`
})
```
