### ISSUE TITLE
AutoScaling notificationTypes props

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#8053]
### Use Case

Like **autoscaling.CfnAutoScalingGroup**, I don't have seen the propertie to be able to set **notificationTypes**, like : 

```
      notificationConfigurations: [{
        topicArn: SnsTopicAutoScaling.topicArn,
        notificationTypes: [
        'autoscaling:EC2_INSTANCE_LAUNCH_ERROR',
        'autoscaling:EC2_INSTANCE_TERMINATE_ERROR'
        ]
      }],
```

It seems that we can only target an SNS Topic : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.AutoScalingGroup.html#notificationstopic

### Proposed Solution

Maybe it's me or maybe it'll be a good thing to be able to set that **notificationTypes** propertie :)

### Other

Indeed, I don't want to have all notifications about a fleet : 

> notificationsTopic?
> Type: ITopic (optional, default: No fleet change notifications will be sent.)
> 
> SNS topic to send notifications about fleet changes.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
Hi @Cloudrage!

Yes you are right, I have created a [PR](https://github.com/aws/aws-cdk/pull/8294) with a fix, should be in this week.

**Comment by Cloudrage** [comment]
Thanks again @NetaNir , perfect now :)
