### ISSUE TITLE
[apigateway] ApiKey should implement grant*() APIs

### ISSUE THREAD

**Issue by whimzyLive** [aws/aws-cdk#8060]
ApiKey Construct should implement IGrantable interface to grant Read write permissions to other constructs.

### Use Case

I usually create a number of microservices like stacks and inter-connect them using API gateway secured with API Key. 

Consider following scenario where `service A` and `service B` are microservices like stacks and so only interact with each other over HTTPS.
Now if `service B` needs to talk to `service A`, it will have to make requests to api exposed by `service A` with api key created in `service A`. 

Right now I do this by creating  
```typescript
      new PolicyStatement({
        effect: Effect.ALLOW,
        actions: ['apigateway:GET'],
        resources: [
          `arn:aws:apigateway:${this.region}::/apikeys/${apiKey.keyId}`,
        ],
      })
```
on Lambda role for  `serviceB`.

### Proposed Solution
Implement IGrantable interface to allow for `apiKey.grantRead(serviceHandler)`. This is much simpler to read and is commonly used throughout cdk. 
### Other

I can try implementing this feature if approved.😉️

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hey @whimzyLive -

Thanks for filing this issue. 

I suppose what you want need to do here is implement a `grantRead()` APIs for `ApiKey`, and not implement the `IGrantable` interface which will be implemented by the other operand.

> Implement IGrantable interface to allow for apiKey.grantRead(serviceHandler)

What type would the `serviceHandler` be in this case?

**Comment by whimzyLive** [comment]
@nija-at Thanks for the quick reply.

A simple example of serviceHander is a lambda function in my case.

**Comment by nija-at** [comment]
An `IFunction` already implements `IGrantable`, so all that's remaining to do to achieve your use case to is to implement `grantRead()` and any other grant methods on the [`ApiKey`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/api-key.ts#L83) class.

**Comment by whimzyLive** [comment]
Okay thanks, I will start work on this tonight
