### ISSUE TITLE
Not possible to use alarm with anomaly detector within alarm widget of a Cloudwatch dashboard

### ISSUE THREAD

**Issue by oleksii-donoha** [aws/aws-cdk#8061]
Currently I cannot find explicit support of anomaly detectors in CW Alarms in CDK, only this related issue: https://github.com/aws/aws-cdk/issues/6562

Issue's author created [SO thread](https://stackoverflow.com/questions/60548344/aws-cdk-example-of-cloudwatch-alarm-with-anomaly-detection), in which following working snippet can be found:

```
anomaly_cfnalarm = cw.CfnAlarm(self, "AnomalyAlarm",
                               actions_enabled=True,
                               alarm_actions=[slack_topic.topic_arn],
                               alarm_description="<..>",
                               alarm_name="AnomalyAlarm",
                               comparison_operator="LessThanLowerOrGreaterThanUpperThreshold",
                               datapoints_to_alarm=1,
                               evaluation_periods=1,
                               insufficient_data_actions=[slack_topic.topic_arn],
                               metrics=[
                                   cw.CfnAlarm.MetricDataQueryProperty(
                                       expression="ANOMALY_DETECTION_BAND(m1, 2)",
                                       id="ad1"
                                   ),
                                   cw.CfnAlarm.MetricDataQueryProperty(
                                       id="m1",
                                       metric_stat=cw.CfnAlarm.MetricStatProperty(
                                           metric=cw.CfnAlarm.MetricProperty(
                                               metric_name=anomaly_detector.metric_name,
                                               namespace=anomaly_detector.namespace
                                           ),
                                           period=core.Duration.minutes(5).to_seconds(),
                                           stat="Sum"
                                       )
                                   )
                               ],
                               ok_actions=[slack_topic.topic_arn],
                               threshold_metric_id="ad1",
                               treat_missing_data="breaching"
                               )
```
This code works by itself.
But if we reference this alarm inside `AlarmWidget` and add this widget to `Dashboard`, then synth passes, but deployment fails. 

### Reproduction Steps

1. Define resources similar to this

```
anomaly_detector = aws_cloudwatch.CfnAnomalyDetector(
            self,
            id="Error anomaly detector",
            metric_name="Errors",
            namespace="AWS/Lambda",
            stat="Average",
            dimensions=[
                aws_cloudwatch.CfnAnomalyDetector.DimensionProperty(
                    name="FunctionName",
                    value=some_function.function_name
                )
            ]
        )

error_alarm = aws_cloudwatch.CfnAlarm(
            self,
            id="Error alarm",
            metrics=[
                aws_cloudwatch.CfnAlarm.MetricDataQueryProperty(
                    expression="ANOMALY_DETECTION_BAND(m1, 2)",
                    id="ad1"
                ),
                aws_cloudwatch.CfnAlarm.MetricDataQueryProperty(
                    id="m1",
                    metric_stat=aws_cloudwatch.CfnAlarm.MetricStatProperty(
                        metric=aws_cloudwatch.CfnAlarm.MetricProperty(
                            metric_name=anomaly_detector.metric_name,
                            namespace=anomaly_detector.namespace
                        ),
                        period=300,
                        stat="Average"
                    )
                )
            ],
            evaluation_periods=2,
            threshold_metric_id="ad1",
            comparison_operator="GreaterThanUpperThreshold"
        )

error_rate_alarm_widget = aws_cloudwatch.AlarmWidget(
            alarm=error_alarm,
            height=6,
            width=6,
            title="Collector error rate alarm status",
            region=core.Aws.REGION
        )

dashboard = aws_cloudwatch.Dashboard(
            self,
            id="Monitoring dashboard",
            dashboard_name="foobar"
        )
dashboard.add_widgets(error_rate_alarm_widget)
```

2. Try to deploy

### Error Log
```
The dashboard body is invalid, there are 2 validation errors:
[
  {
    "dataPath": "/widgets/0/properties",
    "message": "The metric widget should have specified a region and a data source or an alarm annotation"
  },
  {
    "dataPath": "/widgets/0/properties",
    "message": "Should have required property 'metrics' or 'insightRule'"
  }
] (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterInput; Request ID: f2fb5110-095b-495e-aeec-7d8db031e65b)
        new Dashboard (/tmp/jsii-kernel-fioN2e/node_modules/@aws-cdk/aws-cloudwatch/lib/dashboard.js:38:9)
        \_ obj._wrapSandboxCode (../lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7853:49)
        \_ Kernel._wrapSandboxCode (../lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8313:20)
        \_ Kernel._create (../lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7853:26)
        \_ Kernel.create (../lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7600:21)
        \_ KernelHost.processRequest (../lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7388:28)
        \_ KernelHost.run (../lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7328:14)
        \_ Immediate.setImmediate [as _onImmediate] (../lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7331:37)
        \_ runCallback (timers.js:705:18)
        \_ tryOnImmediate (timers.js:676:5)
        \_ processImmediate (timers.js:658:5)
```

### Environment

  - **CLI Version      :1.38.0 (build d5fa31f)**
  - **Framework Version:1.38.0**
  - **OS               :Linux**
  - **Language         :Python**

### Other

My digging led me to the fact that within JSON document of dashboard body generated by CDK there is no annotation for the alarm: `"annotations":{"alarms":[]}`.

If one were to use regular `Alarm`, not `CfnAlarm`, this field is populated correctly: 

```
..."annotations":{"alarms":["'
            - Fn::GetAtt:
                - mycoolalarm677232EC
                - Arn
            - '"]}...
```
Which leads me to believe that `CfnAlarm` is not transformed into annotation the right way.
Ideally `Alarm` should support anomaly detection, or if it does - there should be an accessible example.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Looks like you are mixing [CloudFormation Resource classes with Construct Library Classes](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib). 

Classes and interfaces that start with the name `Cfn` are CloudFormation Resources classes (also called L1 classes), which map directly onto CloudFormation. They generally only work in primitives, so they'll accept strings and numbers and structs of strings and numbers, but never other classes. For example, classes at the L1 level will take a Log Group ARN as a string, not a LogGroup object.

Classes and interfaces that do not start with `Cfn` are the AWS Construct Library classes (also called L2 classes), which are higher level classes written by hand, which have more abstractions and features written in them. They generally favor taking other L2 resources as object references, instead of accepting strings and numbers. For example, classes at the L2 level will take a `LogGroup` object, not an ARN string.

Passing an L1 class to an L2 construct, or an L2 class to an L1 construct, will never work. Most of the time your type checker will warn you that you are passing the wrong object, but if you are using Python you may see this as properties not showing up where you expect them to.

GitHub issues is not a support forum. If you need support to achieve what you want to do, please ask for support on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question there, please bring the StackOverflow post to our attention again and we will do our best to answer it there.

**Comment by oleksii-donoha** [comment]
@rix0rrr 

I understand that mixing Cfn and L2 constructs isn't a good idea. But for this particular functionality (alarm based on anomaly detection) there is no L2 support. One other issue https://github.com/aws/aws-cdk/issues/4569 points user to ... using Cfn resources. 

But there is no `CfnAlarmWidget`, only L2 `AlarmWidget`. Alternative way would be to rewrite entire dashboard logic to `CfnDashboard`, but writing huge JSON document for dashboard body by hand defeats the purpose of using CDK.

I would open feature request to add this functionality to `Alarm`, but it's been done in https://github.com/aws/aws-cdk/issues/4569 and it was closed. 

@SomayaB should I open separate feature request issue with this use case?

**Comment by SomayaB** [comment]
Hi @oleksii-donoha Sorry for the late reply. Yes opening a new feature-request and mentioning that what you're looking for is for it to be added to the L2 would be great.

**Comment by mrsiejas** [comment]
@oleksii-donoha also stumbled against same problem, did you managed to get it running? My anomaly detector and cloudwatch alarms are being created but alarm state shows "Insufficient data".

@rix0rrr mentioned "but if you are using Python you may see this as properties not showing up where you expect them to." which is a bummer as would like to see some type errors when running diff. Here's my snippet

```        billing_anomaly_detector = aws_cloudwatch.CfnAnomalyDetector(
            scope=self,
            id='BillingAnomalyDetector',
            metric_name='EstimatedCharges',
            namespace='AWS/Billing',
            stat='Maximum',
            dimensions=[
                aws_cloudwatch.CfnAnomalyDetector.DimensionProperty(
                    name='Currency',
                    value='USD'
                )
            ]
        )

        aws_cloudwatch.CfnAlarm(
            scope=self,
            id='BillingAnomalyAlarm',
            threshold_metric_id='ad1',
            alarm_name=app.get_account() + '-BillingAnomalyAlarm',
            alarm_actions=[billing_alarm_topic.topic_arn],
            ok_actions=[billing_alarm_topic.topic_arn],
            comparison_operator='GreaterThanUpperThreshold',
            evaluation_periods=1,
            metrics=[
                aws_cloudwatch.CfnAlarm.MetricDataQueryProperty(
                    expression='ANOMALY_DETECTION_BAND(m1, 1)',
                    id='ad1',
                    label='EstimatedCharges (expected)'
                ),
                aws_cloudwatch.CfnAlarm.MetricDataQueryProperty(
                    id='m1',
                    metric_stat=aws_cloudwatch.CfnAlarm.MetricStatProperty(
                        metric=aws_cloudwatch.CfnAlarm.MetricProperty(
                            metric_name=billing_anomaly_detector.metric_name,
                            namespace=billing_anomaly_detector.namespace
                        ),
                        period=core.Duration.hours(360).to_minutes(),
                        stat='Maximum'
                    )
                )
            ]
        )```

**Comment by oleksii-donoha** [comment]
@mrsiejas I haven't touched this topic in quite a while. But if you are able to deploy the code, then "Insufficient data" is probably just a case of thresholds being in the need of tweaking

**Comment by mrsiejas** [comment]
Managed to fix it by moving the dimensions from CfnAnomalyDetector construct to CfnAlarm under `metrics` parameter

```
            metrics=[
                aws_cloudwatch.CfnAlarm.MetricDataQueryProperty(
                    id='m1',
                    metric_stat=aws_cloudwatch.CfnAlarm.MetricStatProperty(
                        metric=aws_cloudwatch.CfnAlarm.MetricProperty(
                            metric_name=billing_anomaly_detector.metric_name,
                            namespace=billing_anomaly_detector.namespace,
                            dimensions=[
                                aws_cloudwatch.CfnAlarm.DimensionProperty(
                                    name='Currency',
                                    value='USD'
                                )
                            ]
                        ),
                        period=core.Duration.hours(360).to_minutes(),
                        stat='Maximum'
                    )
                ),
