### ISSUE TITLE
cognito: custom attributes missing the `required` field

### ISSUE THREAD

**Issue by markcarroll** [aws/aws-cdk#8064]
Trying to move customAttribute definitions from CFN escape hatch into UserPool properties. We now have the ability to create mutable properties which is great, but the `required` field is missing so it is not yet possible to move CFN schema over to CDK native, Cognito complains that it cannot change an existing field. 

### Use Case

Custom attributes should be able to be defined as required or not. 

### Proposed Solution

Propose adding the required field as so:

      customAttributes: {
       company: new cognito.StringAttribute({ minLen: 1, maxLen: 1024, mutable: true, required:false }),
      },

### Other

Trying to move this: 
```
    cfnUserPool.schema = [
      {
        name: "company",
        attributeDataType: "String",
        required: false,
        mutable: true,
        stringAttributeConstraints: { minLength: "1", maxLength: "1024" },
      } 
    ]
```
to this:
```
    const userPool = new cognito.UserPool(this, userPoolName, {
      signInAliases: { email: true },
      autoVerify: { email: true, phone: false },
      userPoolName,
      requiredAttributes: {
        email: true,
      },
      customAttributes: {
        // ====== Can't enable these next rows yet as CDK does not support "requires:true/false" attribute. Without it Cognito fails to update
       company: new cognito.StringAttribute({ minLen: 1, maxLen: 1024, mutable: true, required:false }),
      },
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by markcarroll** [comment]
This turns out to have been a different issue.

**Comment by wxharry** [comment]
Hi, I am having the same issue, how did you solve it?
