### ISSUE TITLE
Browse documentation by version

### ISSUE THREAD

**Issue by ap00rv** [aws/aws-cdk#8083]
https://docs.aws.amazon.com/cdk/api/latest/docs/

It would be really helpful if we could browse documentation by version since CDK is always evolving. Thank you. 

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
You can download old copies of the documentation from the GItHub Releases Page: https://github.com/aws/aws-cdk/releases

**Comment by cnmoise** [comment]
This is not very helpful, I unzipped the documentation for the version I'm interested in but there isn't actually any content when I open index.html in the browser

Some actual written instructions would go a long way

**Comment by hafbau** [comment]
> This is not very helpful, I unzipped the documentation for the version I'm interested in but there isn't actually any content when I open index.html in the browser
> 
> Some actual written instructions would go a long way

This experience is painful. I don't know how to use my downloaded docs, should I be using some server to serve the pages? I think this should be reopened please @rix0rrr

**Comment by tf-cambria** [comment]
@hafbau, thank you for clarifying how to access the documents. This was helpful.

**Comment by tylerwalts** [comment]
Created a related request for these past versions to be hosted and available to web users: https://github.com/aws/aws-cdk/issues/12341
