### ISSUE TITLE
New aws-appsync.GraphQLApi method to create object from ARN

### ISSUE THREAD

**Issue by sudopla** [aws/aws-cdk#8088]
Would it be possible to implement a method to create a GraphQLApi object from its ARN?

### Use Case

I need to be able to add Lambdas data sources and resolvers dynamically to existing AppSync API. 

### Proposed Solution

This can be something very similar to what is already implemented for SNS topics - sns.Topic.fromTopicArn

Maybe -> appsync.GraphQLApi.fromArn(scope, id, APIArn)

**Comment by BryanPan342** [comment]
Closing this in favor of #6959
