### ISSUE TITLE
cli should report a warning on all deprecated APIs being used

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8103]
So users can know the set of APIs they should get off, to be on the greatest and latest.

This can either be a separate subcommand, or print automatically during `synth` and `deploy`.

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
I think the mechanism to do this exists.

i.e adding a warning to a construct
```ts
this.node.addWarning('tread carefully use <myOtherAPI>');
```

which gets printed when you do `cdk synth`. This also has a `--strict` flag that can fail the synth or deploy on warnings for those working in a CI environment, and a `--trace`which provides the path metadata to the problematic construct.

The gap that I believe we need to address is the `@deprecated` APIs and constructs don't report warnings up.
