### ISSUE TITLE
add support for logical construct groups for tagging

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#8104]
Currently, when tagging a construct, all of its children automatically inherit the tag. For example, when tagging an `App`, all stacks added to it will be tagged. We would like the ability to have some intermediate construct between `App` and `Stack` so we can easily apply tags to groups of related stacks. This construct only needs to be logical: we do not expect it to be reflected in CloudFormation in any way, but rather just want something we can pass to `core.Tag.Add(...)`.

### Use Case

We have stacks that logically go together, and we would like to be able to leverage tags to be able to search for and organize them more easily.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
You can just use `Construct` to bundle together other constructs:

```ts
class MyStack extends Stack {
  constructor(...) {
    const group1 = new Construct(this, 'Group2');
    new Resource(group1, 'Resource1InGroup1');
    new Resource(group1, 'Resource2InGroup1');

    const group2 = new Construct(this, 'Group2');
    new Resource(group2, 'Resource1InGroup2');

    Tag.add(group1, 'group', 'group1');
    Tag.add(group2, 'group', 'group2');
    
  }
}
```
