### ISSUE TITLE
NodejsFunction broken on Windows

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#8107]
NodejsFunction doesn't work on Windows. There's some sort of problem with the way it translates Windows paths (backslash) to Docker.

### Reproduction Steps
`lib/my-stack.ts`:
```ts
export class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    new NodejsFunction(this, 'handler');
  }
}
```
`lib/my-stack.handler.ts`:
```ts
export const handler = () => 'anything';
```

### Error Log

```
PS E:\p\break> yarn cdk synth                                                                                                                                                                                                  yarn run v1.22.4
warning package.json: No license field
$ cdk synth
Failed to build file at E:\p\break\lib\my-stack.handler.ts: Error: [Status 125] stdout:


stderr: docker: Error response from daemon: the working directory '\project\lib' is invalid, it needs to be an absolute path.
See 'docker run --help'.
Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

  - **CLI Version      :** 1.40.0
  - **Framework Version:** 1.40.0
  - **OS               :** Windows 10
  - **Language         :** TypeScript on NodeJS v12.1.0

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
The problem is here:
https://github.com/aws/aws-cdk/blob/395c07c0cac7739743fc71d71fddd8880b608ead/packages/%40aws-cdk/aws-lambda-nodejs/lib/builder.ts#L114

`containerEntryPath` is constructed using a `path.join()` but it should always use forward slashes.
