### ISSUE TITLE
Lambda: Principal conditions don't get translated to AWS::Lambda::Permissions fields

### ISSUE THREAD

**Issue by w-** [aws/aws-cdk#8116]
Trying to great a ServicePrincipal for use in a Function.grantInvoke call.

Want to add conditions so that it is scoped to a particular bucket ala e.g. here https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html

I've tried varaitions in conditions for the keys like
`arnLike`
`awsSourceArn`

tried using this as reference 

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ARN

How is this supposed to work? No examples in docs or elsewhere on interwebs

### Reproduction Steps

```
        const spOptions = {
            conditions:{
                'arn:like':{
                    "aws:SourceArn" : bucketName
                }
            }
        }
        const sp = new ServicePrincipal('s3.amazonaws.com', spOptions)
        console.log('Service Principal', sp.policyFragment)
        this.launcherFunction.grantInvoke(sp)
```
doing this i see my conditions in the policyFragment output but doesn't generate any conditions in the resulting cloudformation

```
{
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Fn::GetAtt": [
            "xxxLauncher5BB90C90",
            "Arn"
          ]
        },
        "Principal": "s3.amazonaws.com"
      },
      "Metadata": {
       ...
      }
    }
````

### Environment

  - **CLI Version      : aws-cli/2.0.9 
  - **Framework Version:** 1.40.0
  - **OS               :**ubuntu 16.04
  - **Language         :** typescript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Good point. We support those conditions for IAM policies, but they don't get properly translated to Lambda Permission objects.

For the time being, I'd recommend you use `launcherFunction.addPermission()` instead.

**Comment by rbingham** [comment]
I am seeing the same thing, but while using the `launcherFunction.addPermission()` that @rix0rrr recommended.

My code:
```typescript
const servicePrincipal = new ServicePrincipal('apigateway.amazonaws.com', {
  conditions: {
    ArnEquals: {
      'aws:SourceArn': `arn:aws:execute-api:${this.region}:${this.account}:${proxy.restApiId}/*/*`,
    }
  }
});

lambda.addPermission('test', {
  principal: servicePrincipal,
});
```

Resulting cloudformation output:
```json
{
  "testlambdafunctiontest3C0029AA": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Fn::GetAtt": [
            "testlambdafunction82C8D643",
            "Arn"
          ]
        },
        "Principal": "apigateway.amazonaws.com"
      },
      "Metadata": {
        "aws:cdk:path": "stack-name/test-lambda-function/test"
      }
    }
  }
}
```

CLI Version : aws-cli/1.16.256
Framework Version: 1.44.0
OS : Darwin/19.2.0
Language : typescript

**Comment by david-wang-1** [comment]
Any updates on prioritization for this fix? The workaround from @rix0rrr does not appear to work.

**Comment by ScDavid** [comment]
I experienced the same problem. Additionally using PrincipalWithConditions seems no to be supported as principal in Lambda permission: 
Invalid principal type for Lambda permission statement: PrincipalWithConditions. Supported: AccountPrincipal, ArnPrincipal, ServicePrincipal

**Comment by zacyang** [comment]
I got the same issue, as @ScDavid , any update on this one?

I am basically loading a OenAPI spec into apigateway, so all the permissions have to be added, by the looks of this bug, it is not possible to do so (grant apigateway access to invoke lambda ) from the API?

**Comment by zacyang** [comment]
I have to go to the cdk source code to figure this out, https://github.com/aws/aws-cdk/blob/4684c8311cd10f512bbc0904825faadfd14c2626/packages/%40aws-cdk/aws-apigateway/lib/authorizers/lambda.ts#L100
this is really inconsistently ....

**Comment by ola-mymed** [comment]
Any updates on a fix for this? I've got the same issue as @ScDavid and @w-

**Comment by ScDavid** [comment]
This problem might correspond to the limited condition options that exist with the [https://docs.aws.amazon.com/cli/latest/reference/lambda/add-permission.html](cli). We can only use source-arn and source-account with Lambda (and I did not get it working with source-arn in my case). I opened a support ticket and got to the conclusion that for my case it was not possible at all to work with conditions in the Lambda policy. We created a feature request to enable more flexibility there. It feels like it is not meant to use Lambda permissions with conditions and due to the limited CLI options, the CDK is also quite limited.

However, my workaround was to create an IAM role and set the conditions in the roles trust policy to only allow specific entities to assume the role and then only this role can trigger my Lambda function. I described the problem in my scenario and my solution in more detail [https://aws-blog.de/2021/01/cross-account-resource-access-invalid-principal-in-policy.html](here)

**Comment by dimon89ch** [comment]
That's my workaround : 

```
    new CfnPermission(this, `{{id}}`, {
      action: 'lambda:InvokeFunction',
      functionName: {{functionName}},
      principal: 'cognito-idp.amazonaws.com',
      sourceArn: {{source.arn}}
    });
 ```

**Comment by Pythoner6** [comment]
It seems like pretty bad behavior to me to silently drop the conditions here. I'd have expected CDK to either special case support for the supported conditions like SourceArn and throw an error if other conditions are present, or even just throw an error if any condition is present saying that they're currently not supported by cdk. But silently ignoring the condition seems dangerous.
