### ISSUE TITLE
stack.synthesizer undefined

### ISSUE THREAD

**Issue by binarythinktank** [aws/aws-cdk#8118]
unable to deploy code using s3-deployment
this is a brand new project, just initialised and not deployed yet

### Reproduction Steps
in lib/[stackname]-stack.js

```
const cdk = require('@aws-cdk/core');
const s3 = require("@aws-cdk/aws-s3");
const s3deploy = require('@aws-cdk/aws-s3-deployment');

class ImageanalysisStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);

    const s3bucket = new s3.Bucket(this, "mybucket", {
      websiteIndexDocument: "index.html",
      websiteErrorDocument: "index.html",
      publicReadAccess: true
    });

    new s3deploy.BucketDeployment(this, "mydeployment", {
      sources: [s3deploy.Source.asset(source_path)], // path is correct
      destinationBucket: s3bucket
    });
  }
}

```

then run cdk synth

### Error Log

[project_dir]/node_modules/@aws-cdk/aws-s3-assets/lib/asset.js:30
const location = stack.synthesizer.addFileAsset({
                                           ^
TypeError: Cannot read property 'addFileAsset' of undefined

### Environment

  - **CLI Version      : aws-cli/2.0.8 Python/3.7.3 Linux/5.3.0-7648-generic botocore/2.0.0dev12
  - **Framework Version: 1.40.0 (build b2c3043)
  - **OS               : ubuntu 18/popos
  - **Language         : javascript

### Other

TypeError: Cannot read property 'addFileAsset' of undefined
    at new Asset ([project_dir]/node_modules/@aws-cdk/aws-s3-assets/lib/asset.js:30:44)
    at AssetCode.bind ([project_dir]/node_modules/@aws-cdk/aws-lambda/lib/code.js:136:26)
    at new Function ([project_dir]/node_modules/@aws-cdk/aws-lambda/lib/function.js:69:33)
    at SingletonFunction.ensureLambda ([project_dir]/node_modules/@aws-cdk/aws-lambda/lib/singleton-lambda.js:51:16)
    at new SingletonFunction ([project_dir]/node_modules/@aws-cdk/aws-lambda/lib/singleton-lambda.js:19:36)
    at new BucketDeployment ([project_dir]/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.js:19:25)
    at new ImageanalysisStack ([project_dir]/lib/[mystack]-stack.js:37:26)
    at Object.<anonymous> ([project_dir]/bin/[mystack].js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

--- 

This is :bug: Bug Report

**Comment by franco948** [comment]
I get the same error when trying to use the `AwsCustomResource` object.

**Comment by alfallouji** [comment]
I had the same issue. I was using an older version of  the '@aws-cdk/core' package and I was getting the same error as you.

Could you check your package.json?  What version are you using for the various cdk packages ? If you are using an old one (as I was), try to update them and do a npm install.

This is what I had initially (not working):
>   "dependencies": {
>     "@aws-cdk/aws-cloudformation": "^1.40.0",
>     **"@aws-cdk/aws-lambda": "^1.34.1",**
>     "@aws-cdk/core": "^1.40.0"
>   }

This is how I updated it (working version):
>   "dependencies": {
>     "@aws-cdk/aws-cloudformation": "^1.40.0",
>     **"@aws-cdk/aws-lambda": "^1.40.0",**
>     "@aws-cdk/core": "^1.40.0"
>   }

**Comment by binarythinktank** [comment]
@alfallouji nice! you were right, looks like "cdk init" set "@aws-cdk/assert": "^1.30.0" and "@aws-cdk/core": "1.30.0" as the defaults in package.json

this still feels like a bug though as i went through fairly standard steps of "cdk init" then "npm install [cdk modules]". Wouldnt it be better to use the latest cdk on init?

**Comment by shivlaks** [comment]
@binarythinktank hey! glad you were able to figure out the issue with misaligned versions. `cdk init` fixes dependencies to the version of the CLI that's being used.

The reason we switched to this is because the Cloud Assembly [schema](https://docs.aws.amazon.com/cdk/api/latest/docs/cloud-assembly-schema-readme.html) might change in future versions. In the past, bumping the cloud assembly schema version has been problematic with older versions of the CLI as it would subsequently force users to update their CLI to use the new project that was created.

We went with fixed versions as the project that is produced by `cdk init` should always work with the version of the CLI it was generated with. It was a result of  #5986

I don't believe there's any further action we need to take on this one.
Closing for now, feel free to reopen if I missed something or if you have any unanswered questions!
