### ISSUE TITLE
CDK CLI produces invalid tokens in eu-south-1 region

### ISSUE THREAD

**Issue by flavioleggio** [aws/aws-cdk#8131]
Every CLI command on the new `eu-south-1` region (Italy - Milan) fails with errors regarding the security token, when you use the `--profile` option.

### Reproduction Steps

Configure your ~/.aws/credentials like this
```
[default]
aws_access_key_id = myaccesskeyid
aws_secret_access_key = mysecretaccesskey
```
and your ~/.aws/config like this
```
[profile myprofile]
role_arn = arn:aws:iam::123456789012:role/MyAccessRole
region = eu-south-1
source_profile = default
```

Then run the following command
```
$ cdk --profile myprofile bootstrap aws://123456789012/eu-south-1 --no-execute
```

### Error Log

```
 ⏳  Bootstrapping environment aws://123456789012/eu-south-1...
 ❌  Environment aws://123456789012/eu-south-1 failed bootstrapping: InvalidClientTokenId: The security token included in the request is invalid
The security token included in the request is invalid
```

### Environment

  - **CLI Version: 1.39.0 (build 5d727c1)**
  - **Framework Version: 1.19.0** (does not really matter here)
  - **OS: Linux Mint 19.3 (Tricia)**
  - **Language: Typescript**

### Other

My aws CLI works fine with its own `--profile` option on the same configuration.

I've managed to make this work by authenticating "manually", using STS and then exporting environment variables for authorization.
```
$ aws --profile myprofile sts assume-role --role-arn arn:aws:iam::123456789012:role/MyAccessRole --role-session-name test
$ export AWS_ACCESS_KEY_ID=<myAccessKeyId>
$ export AWS_SECRET_ACCESS_KEY=<mySecretAccessKey>
$ export AWS_SESSION_TOKEN=<generatedSessionToken>
$ cdk bootstrap aws://123456789012/eu-south-1 --no-execute
```

By looking at session token length I can guess that STS is releasing version 2 STS tokens.

In fact, as documented [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html)

> Version 1 tokens are valid only in AWS Regions that are available by default. These tokens do not work in manually enabled Regions, such as Asia Pacific (Hong Kong). Version 2 tokens are valid in all Regions. However, version 2 tokens include more characters and might affect systems where you temporarily store tokens.

it seems like new regions may only accept version 2 tokens.

I assume that CDK CLI is not using version 2 tokens here - at least when using the `--profile` option - resulting in security errors on API calls.

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@flavioleggio thanks for the report! I think you're right in that we are not using the version 2 tokens. I'll dig a little and provide an update this week. stay tuned!

**Comment by shivlaks** [comment]
@flavioleggio - it seems we aren't using regional endpoints. I was testing this out a bit earlier today. So i followed the documentation and set the [security token preferences](https://docs.aws.amazon.com/cli/latest/reference/iam/set-security-token-service-preferences.html)

> aws iam set-security-token-service-preferences --global-endpoint-token-version v2Token --profile myprofile

After that I was able to to use the `eu-south-1` region. can you give that a try and let me know how it goes!

---

prior to making that API call to set the preference, I was getting hit with the error:
```
The security token included in the request is invalid
InvalidClientTokenId: The security token included in the request is invalid
```

I'm not sure that the CDK *should* enable that preference on behalf of users (at least not without warning) as it has implications, but we can improve error messaging and direction we provide so it's less cryptic and more prescriptive on the direction

As an aside, we should also consider using regional endpoints (I'm not quite sure if this has already been considered in the past, but will check and follow-up).

Let me know how it goes!

**Comment by flavioleggio** [comment]
@shivlaks - i tried clearing my `~/.aws/cli/cache` and setting token preferences as you suggested, but I am still getting the `InvalidClientTokenId` error you quoted.
Is there something else I should check to be sure this is not some config-related issue?

**Comment by shivlaks** [comment]
@flavioleggio perhaps also clear out your ~/.cdk/cache

confirming that this is after running
> aws iam set-security-token-service-preferences --global-endpoint-token-version v2Token --profile myprofile

when I flip this back to v1, then I run into errors

if you're using `1.42.0` (latest release), we also started wrapping failures using the SDK into the verbose output. running the command with `-v` should provide you with a stack trace with a more specific error.

**Comment by flavioleggio** [comment]
@shivlaks I tried clearing out both aws cli and cdk cache but with no luck.
This is the stack trace

> InvalidClientTokenId: The security token included in the request is invalid
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

I tried with both `1.41.0` and `1.42.0` releases. Any insights?

**Comment by flavioleggio** [comment]
@shivlaks as an addition for troubleshooting I can actually see that AWS CLI is now using v2 tokens after calling the `set-security-token-service-preferences` API, while CDK CLI still produces that invalid token error.Is there any chance that CDK CLI ignores the security token preferences set by AWS CLI?

**Comment by shivlaks** [comment]
@flavioleggio The CLI does use the AWS CLI under the hood, but I don't believe it does anything to explicitly ignore preferences. I'm able to make these calls without an error. I'm going to try creating a fresh account to repro. I'm able to bootstrap and deploy stacks. 

does it work If you assign credentials directly as your default credentials. Wondering if I missed a repro step. Is there any mode of operation where the CLI works for you? Could I take a look at the full stack trace from the time the default account/region is determined? There should be an error message ahead of the `InvalidClientTokenId` message.

**Comment by flavioleggio** [comment]
@shivlaks As you suggested, if I try to use the CLI on my production account with no role assumption (default creds) it actually works.

Unfortunately, I cannot always use default credentials because there is no user in my develop account. It just holds a role that I can assume with my credentials from the production account, therefore I need that profile assumption.

Here you have the whole verbose output (excluding settings and context information)
```
merged settings: { versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  context: {},
  tags: [],
  assetMetadata: true,
  profile: 'myprofile',
  toolkitBucket: {},
  staging: true }
Determining whether we're on an EC2 instance.
Does not look like EC2 instance.
Toolkit stack: CDKToolkit
 ⏳  Bootstrapping environment aws://************/eu-south-1...
Resolving default credentials
Looking up default account ID from STS
Default account ID: (same as env account)
Waiting for stack CDKToolkit to finish creating or updating...
Call failed: describeStacks({"StackName":"CDKToolkit"}) => The security token included in the request is invalid
 ❌  Environment aws://************/eu-south-1 failed bootstrapping: InvalidClientTokenId: The security token included in the request is invalid
The security token included in the request is invalid
InvalidClientTokenId: The security token included in the request is invalid
    at Request.extractError (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/.npm-global/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by slyfoxza** [comment]
I ran into a similar issue with `af-south-1` when dealing with a cross-account configuration (where the IAM user credentials were in account A, assuming a role in account B). I had to enable v2 global endpoint tokens in the _source_ account A (and wait for the change to propagate) to have EC2 accept credentials used for a context lookup in account B. Failing to do so resulted in the same "security token ... is invalid" error.

**Comment by flavioleggio** [comment]
@slyfoxza, you are definitely my hero of the day!
Setting the v2 tokens configuration in my production account, which holds my identities, I managed to use the CDK CLI with no issues. I actually had to specify the `eu-south-1` region when setting security token preferences on my production account.

@shivlaks I think we can close this issue, this is related with the CDK CLI.
Still I believe this procedure is not well documented. Is there some place in where we should move this?

**Comment by shivlaks** [comment]
@flavioleggio I'm going to resolve this. Perhaps we could improve the documentation a bit by adding to the [README](https://github.com/aws/aws-cdk/tree/master/packages/aws-cdk)

also copying @Jerry-AWS as we could probably also update our documentation pages to guide users in setting up and using `v2` tokens

**Comment by cohena100** [comment]
for an existing CDK project this helped:
1. delete the folder:  ~/.aws/cli/cache
2. add: --profile.         for examle: npx cdk bootstrap --profile default --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
