### ISSUE TITLE
CloudFormation reports the arn returned by LogGroup.logGroupArn is invalid

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#8137]
In my case, I am importing a `LogGroup` and using the `logGroupArn` as the log group arn for another resource.

### Reproduction Steps

In my case, I am creating a log group elsewhere in the stack ahead of time to attach metric filters.

```
const myLogGroup = LogGroup.fromLogGroupArn(
      this,
      'MyLogGroup',
      '<arn>'
    );

...

// Some resource that uses a log group arn
myLogGroup.logGroupArn
```

### Error Log

In CloudFormation:

> The CloudWatch Logs ARN referring to the log group is invalid.
> Please specify a valid ARN.

### Environment

  - **CLI Version      : 1.41.0**
  - **Framework Version: 1.41.0**
  - **OS               : macOS**
  - **Language         : TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by cmckni3** [comment]
For some reason a `Fn::Join` is being inserted with a `:*`. The documentation for `logGroupArn` says `:*` will be appended.

Worked around by using CloudFormation `GetAttr` directly.

```
cdk.Token.asString(
  cdk.Fn.getAtt(myLogGroup.node.id, 'Arn')
)
```

**Comment by cmckni3** [comment]
Related to https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/206 maybe? Not sure why `Fn::GetAtt` directly works though.

**Comment by rix0rrr** [comment]
Grrr! Yes, CloudWatch Log Group ARNs are a mess.

But I was 100% convinced that `{Fn:: GettAtt}` also returned the `:*` variant, to make it easy to stick them into IAM policies, which is why we are mirroring that behavior.

Can you give me a little more info on how/when this is not happening in your account? Can you try to deploy a silly template like this:

```
Resources:
    SomeLogGroup:
        Type: AWS::Logs::LogGroup
Outputs:
    TheArn:
        Value: { 'Fn::GetAtt': [SomeLogGroup, Arn] }
```

And tell me what the value of the Output looks like in your account?

In mine it looks like this:

```
arn:aws:logs:eu-west-1:*****:log-group:TestLogGroup-SomeLogGroup-5BW1FPUY9S9H:*
```

I sure hope it's not account-specific behavior... 😓

**Comment by cmckni3** [comment]
Yes, that returns the correct value in the format:

```
arn:aws-us-gov:logs:us-gov-west-1:******:log-group:LogGroup-Test-SomeLogGroup-DRUXKAFRRPP0:*
```

In particular, my issue came from importing the LogGroup from another nested stack and using `LogGroup.logGroupArn`.

What happens when I call `logGroupArn` is that CDK generates an extra `:*` at the end via `Fn::Join` which I am passing to `ES_APPLICATION_LOGS`.

Let me reproduce the template real quick to grab a snippet of the template itself.

**Comment by cmckni3** [comment]
```
// ...
        "LogPublishingOptions": {
          "ES_APPLICATION_LOGS": {
            "CloudWatchLogsLogGroupArn": {
              "Fn::Join": [
                "",
                [
                  {
                    "Fn::GetAtt": [
                      "ElasticSearchLogGroupImport037E156D",
                      "Arn"
                    ]
                  },
                  ":*"
                ]
              ]
            },
            "Enabled": true
          }
        }
```

**Comment by cmckni3** [comment]
> Related to aws-cloudformation/aws-cloudformation-coverage-roadmap#206 maybe? Not sure why Fn::GetAtt directly works though.

Ah I misunderstood this the first time. That's a proposal for `Fn::GetAtt` to drop the `:*` so it can be used in places (such as IAM policies) that error on `:*` at the end.

In my case, I was relying on the imported log group (an `ILogGroup`) and calling `logGroupArn` to get the value. This behavior changed in #7668 (for the better) to match it.

I was caught off guard at the change but have fixed it in my CDK app.

What a mess.

**Comment by cmckni3** [comment]
I wasn't expecting this as a breaking change in 1.37.0 but makes sense.

Feel free to close.

**Comment by rix0rrr** [comment]
You are correct that should have been marked as a BREAKING CHANGE. Silly I forgot about that, sorry!

Glad to hear you figured it out. Closing.
