### ISSUE TITLE
Is it possible to pull in a python dependency for a CDK asset?

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#8138]
## :question: General Issue

There is a construct I would like to create which is based on this AWS blog post:

https://aws.amazon.com/blogs/networking-and-content-delivery/using-static-ip-addresses-for-application-load-balancers/

The construct will create a lambda function, whose code will be checked into CDK. That code requires a dependency on dnspython (available below)

https://pypi.org/project/dnspython/

### The Question
Is it possible to pull in a python library as a dependency to CDK, to be used in an asset for a Lambda function?

### Environment

  - **CDK CLI Version:** 1.39
  - **OS:** <!-- all
  - **Language:** all

**Comment by Lutrome** [comment]
Actually, yes. There’s a reddit post on using third party Python dependencies in lambdas.


https://www.reddit.com/r/aws/comments/93jhgi/how_can_i_add_third_party_python_dependencies_to

**Comment by flemjame-at-amazon** [comment]
Here is the associated git repo: https://github.com/rthalley/dnspython

**Comment by eladb** [comment]
You can technically create a .zip bundle that contains anything you want for your lambda code, including any deps.

#7898 will make it easier through. Coming soon.

**Comment by flemjame-at-amazon** [comment]
> You can technically create a .zip bundle that contains anything you want for your lambda code, including any deps.
> 
> #7898 will make it easier through. Coming soon.

does this apply to developing for the core CDK library too?

**Comment by eladb** [comment]
> > You can technically create a .zip bundle that contains anything you want for your lambda code, including any deps.
> 
> > 
> 
> > #7898 will make it easier through. Coming soon.
> 
> 
> 
> does this apply to developing for the core CDK library too?

Why actually have a case where we bundle a python lambda with deps into the CDK (s3-deployment). But usually we prefer to keep it to typescript if possible.
