### ISSUE TITLE
StateMachine - support for definition string or JSON

### ISSUE THREAD

**Issue by erik-sab** [aws/aws-cdk#8146]
When creating Step Functions [StateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.StateMachine.html) there is no possibility to provide already created definition string.

Also there is no way of creating [IChainable](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.IChainable.html) from definition string of JSON which would also solve the issue.

That would be extremely useful for our use-case, when it is more convenient to define initial flow steps in JSON file and then edit them programmatically.

When using low-level [CfnStateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CfnStateMachine.html) there is no way of getting state machine ARN, so workaround is to construct it by hands, also we loose some helpers there.

### Use Case

1. We have JSON file template for creating EMR execution step functions taking care of: cluster creation, initialisation, error handling, and shutdown logic. 
1. Template is parsed and actual work steps are being added programmatically based on external configuration.
1. Also some project parts define whole flow in JSON file, and use CDK to create supporting resources only.

Having possibility to convert [IChainable](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.IChainable.html) to and from JSON would also help a lot for early state machine testing and debugging.

### Proposed Solution

a) Add JSON input support to [Chain](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Chain.html) similar to one we have in [CustomState](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CustomState.html) which does accept JSON as input, but works only for single state.

b) Add support for definitionString in [StateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.StateMachine.html) similar to one we have in [CfnStateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CfnStateMachine.html)

c) Add support for definitionJson in [StateMachine](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.StateMachine.html) similar to one we have in [CustomState](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CustomState.html) 

### Other

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@erik-telesoftas thanks for logging the issue! I think that's an interesting use case and one that would be useful. I like option `a` as getting a `Chain` back as you do in custom state allows you to manipulate and reuse a definition or partial definition of a state machine in addition to using the definition json directly. 

for option `b` I'm more hesitant because we have introduced a few new concepts in authoring state machines within the CDK and it feels like we might be taking a step back into the L1. I think it's the least flexible of the group.

**Comment by erik-telesoftas** [comment]
Another motivation point is that AWS have nice support for working with JSON definition, so would be great to have possibility to import it nicely into CDK

https://aws.amazon.com/blogs/compute/aws-step-functions-support-in-visual-studio-code/

**Comment by jabrennem** [comment]
I would also like this feature. My team really only uses CfnStateMachine because it supports the JSON string and VSCode allows you to visualize the state machine definition locally.

**Comment by mmuller88** [comment]
that sounds like a really cool use case for a CDK custom construct. Let me know if you need help with those I build a couple of htose: https://github.com/p6m7g8/awesome-projen#awscdkconstructlibrary , https://martinmueller.dev , 
I even put a custom construct course on Udemy. Send me you mail and I create a voucher for you :)

**Comment by djjolicoeur** [comment]
Wanted to add another voice in favor of this feature, it would be very helpful to our use case.

**Comment by shivlaks** [comment]
there's enough activity on this issue that we'll need to prioritize it soon.

@djjolicoeur can you expand on your use case at a high level? I'm trying to aggregate all the desired features to set ourselves up for designing a solution.

**Comment by romanolux** [comment]
We wanted to add this vote as well to support this feature request; this would be very useful in several projects!

**Comment by jbvsmo** [comment]
This would be a very useful feature

**Comment by pchot** [comment]
+1

**Comment by Craig1f** [comment]
Need the same thing here. We didn't start with CDK. I'm trying to add it in now that our dev has created the step functions we need in the console. I don't want to re-write 20+ step functions with JS function-chaining.

**Comment by feini-helix** [comment]
+1

**Comment by dejvid-smth** [comment]
Would it be possible to add option to use TOKENs in the state machine source string ?
Better yet, I would like to maintain state machine definition in separate file so I can visualize it using VS Code plugin. In that case I would like to be able to parametrize the state machine source. This is already possible in SAM.

**Comment by jaidisido** [comment]
+1

**Comment by qinjie** [comment]
+1

**Comment by nicofabre** [comment]
+1

**Comment by tobyDickinson** [comment]
+1 on this.

Currently I can't see a way of defining a `StateMachine` via `cdk` from JSON which is triggered by EventBridge. The `SfnStateMachine` target in `aws-cdk-lib/aws-events-targets` requires an `IStateMachine` which the interface for `CfnStateMachine` (only way to currently deploy a StateMachine from ASL JSON) doesn't conform to

**Comment by oshaughnessy** [comment]
+1 as well.

I have a state machine defined as YAML and deployed from SAM. I'm looking at moving the project to SAM+CDK, and I'd like to move all of my infrastructure definitions to the Python CDK. I'd love to be able to keep the state machine definition as a standalone text file.

**Comment by gsanchez2141** [comment]
+1

**Comment by koDaegon** [comment]
+1

**Comment by nicofabre** [comment]
+1

**Comment by ChristophrK** [comment]
+1

**Comment by cwise89** [comment]
+1

**Comment by JuanMartinElorriaga** [comment]
+1

**Comment by ChristophrK** [comment]
As pointed out by @mmuller88 this is a great use case for a CDK custom construct and even better there is already are finished construct available on [Construct Hub](https://constructs.dev/packages/@matthewbonig/state-machine/v/0.0.16?lang=python) / [GitHub](https://github.com/mbonig/state-machine). To install it you can simply use pip with the following command: `pip install mbonig.state-machine==0.0.16`.

**Simply creating a Step Function from a definition in a json file can be done like this:**
```python
import mbonig.state_machine
class Your_Stack(Stack):
    def __init__(
        self, scope: Construct, id: str, **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

    with open('sample.json', 'r+', encoding='utf-8') as sample:
              sample_dict = json.load(sample)
    state_machine = mbonig.state_machine.StateMachine(
              self,
              'A nice state machine',
              definition = sample_dict,
              logs= None)
```
But the Construct allows you to also override values from the definition file, so that you can still leverage the AWS CDK as the source of truth for the state machine. For example you could replace the `FunctionName` for the `Lambda: Invoke` API so that you can seamlessly switch between DEV/PROD enviroments.  

**Creating a Step Function from a definition with overwrite looks like this:**
```python
import mbonig.state_machine
class Your_Stack(Stack):
    def __init__(
        self, scope: Construct, id: str, **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

    with open('sample.json', 'r+', encoding='utf-8') as sample:
        sample_dict = json.load(sample)
    lambda_arn = str(global_tm_kpi.function_arn)
    state_machine = mbonig.state_machine.StateMachine(self,
            'A nice state machine', definition=sample_dict, logs=None,
            overrides={'Trigger Lambda': {'Parameters': {'FunctionName': lambda_arn}}})
```
I hope this solution is also useful for others:)

**Comment by rodolfo-picoreti** [comment]
> +1 on this.
> 
> Currently I can't see a way of defining a `StateMachine` via `cdk` from JSON which is triggered by EventBridge. The `SfnStateMachine` target in `aws-cdk-lib/aws-events-targets` requires an `IStateMachine` which the interface for `CfnStateMachine` (only way to currently deploy a StateMachine from ASL JSON) doesn't conform to

I was able to go around it by defining my own IRuleTarget:

Java Example:
```java
    public class CfnStateMachineTarget implements IRuleTarget {

        private CfnStateMachine stateMachine;
        private Role role;

        public CfnStateMachineTarget(CfnStateMachine stateMachine, Role role) {
            this.stateMachine = stateMachine;
            this.role = role;
        }

        @Override
        public @NotNull RuleTargetConfig bind(@NotNull IRule rule, @Nullable String id) {
            return RuleTargetConfig.builder()
                    .arn(stateMachine.getAttrArn())
                    .role(role)
                    .build();
        }

        @Override
        public @NotNull RuleTargetConfig bind(@NotNull IRule rule) {
            return bind(rule, null);
        }

    }
 ````

**Comment by paulluuk** [comment]
> I was able to go around it by defining my own IRuleTarget (Java)

In Python I was able to do this:
```
state_machine_cfn = _step.CfnStateMachine(
            scope=self,
            id=machine_id,
            definition_string=definition_string,
            role_arn=role.role_arn,
        )

schedule_rule = _event.Rule(
            scope=self,
            id=id,
            schedule=schedule,
            rule_name=rule_name,
            targets=[
                _target.SfnStateMachine(
                    _step.StateMachine.from_state_machine_arn(
                        scope=self,
                        id=rule_id,
                        state_machine_arn=state_machine_cfn.attr_arn,
                    )
                )
            ],
        )
```
In other words, I just create the "right" type of state machine by importing it from the "wrong" type of state machine right above it.

**Comment by leandrosalo** [comment]
+1

we should not do hacks to solve this, this is common sense... If you give me a lovely AWS Console to diagram step functions and then the result is a json definition why should I be forced to translate that to Code?

**Comment by infinitedreams9586** [comment]
This can be achieved with the steps as follows,

1. First create a cloudformation  using definition string

 /```
/ create base state machine using cloudformation
        const cfnStateMachine = new sfn.CfnStateMachine(this, "CFN_STATEMACHINENAME", {
            roleArn: ssmFullAccessRole.roleArn,
            definition: {YOUR_STATE_MACHINE_DEFINITION_HERE_CLOUDFORMATION}}},
            stateMachineName: "CFN_STATEMACHINENAME",
            stateMachineType: "STANDARD",
        });
```
2. Use the state machine declared before,
`const stateMachineObject = sfn.StateMachine.fromStateMachineName(this, 'statemachineid', "CFN_STATEMACHINENAME");`

3. Now stateMachineObject can be used in further steps,
` const task1 = new tasks.StepFunctionsStartExecution(this, "Task1", {
            name: "Task1",
            stateMachine: stateMachineObject,
            integrationPattern: sfn.IntegrationPattern.WAIT_FOR_TASK_TOKEN
        });`

**Comment by SamStephens** [comment]
@hoegertn unfortunately your change doesn't update the example in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.StateMachine.html , which still uses the deprecated `definition` property.

**Comment by infinitedreams9586** [comment]
> @hoegertn unfortunately your change doesn't update the example in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.StateMachine.html , which still uses the deprecated `definition` property.

I see 'definition' marked as deprecated and 'definitionBody' in construct props.

**Comment by SamStephens** [comment]
> > @hoegertn unfortunately your change doesn't update the example in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.StateMachine.html , which still uses the deprecated `definition` property.
> 
> I see 'definition' marked as deprecated and 'definitionBody' in construct props.

@infinitedreams9586 I said it does not update **the example**:

```
const simpleStateMachine  = new stepfunctions.StateMachine(this, 'SimpleStateMachine', {
  definition: startState,
});
```

**Comment by hoegertn** [comment]
Good catch. Will supply a fix asap.
