### ISSUE TITLE
cdk synth doesnt display second stack

### ISSUE THREAD

**Issue by pagilan** [aws/aws-cdk#8148]
cdk synth doesnt display second stack
I have created two stacks
public class Stacks {
    public static void main(final String[] args) {
       System.out.println("Building stacks");
       App scope = new App();
       InfraStack infra = new InfraStack(scope, "InfraStack");
       AppInfraStack appInfra = new AppInfraStack(scope, "AppInfraStack",infra);
       System.out.println("Complete..");
       scope.synth();
    }
}

### Reproduction Steps
---------------------- First stack works ----------------------
cdk synth InfraStack
Building stacks
...Building Stack:InfraStack
...Building Stack:AppInfraStack
Complete..
Resources:
  VPCB9E5F0B4:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 15.0.0.0/16
........

----------------------Second stack doesn't work ----------------------
cdk synthesize AppInfraStack
Building stacks
...Building Stack:InfraStack
...Building Stack:AppInfraStack
Complete..
Including dependency stacks: InfraStack
Successfully synthesized to ...\ckdtest\cdk.out
Supply a stack id (InfraStack, AppInfraStack) to display its template.

### Error Log
Supply a stack id (InfraStack, AppInfraStack) to display its template.

### Environment
  - **CLI Version      :1.41.0 (build 9e071d2)
  - **Framework Version:1.41.0 (build 9e071d2)
  - **OS               :windows
  - **Language         :java

### Other
Please note cdk deploy works fine. cdk synth doesn't support * like deploy

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
dupliate of #3721
