### ISSUE TITLE
Add support for S3 Bucket Inventory

### ISSUE THREAD

**Issue by sagiba** [aws/aws-cdk#8154]
Would be nice to have native support for configuring S3 Bucket Inventory. Managed to do it by falling back to CfnBucket constructs, but the configuration is pretty verbose and can be simplified with CDK.

Cfn example:
```typescript
const inventoryBucket = new s3.Bucket(this, 'InventoryBucket');
const dataBucket = new s3.Bucket(this, 'DataBucket');
(dataBucket.node.defaultChild as s3.CfnBucket).inventoryConfigurations = [
  {
    destination: {
      bucketArn: inventoryBucket.bucketArn,
      format: 'Parquet'
    },
    enabled: true,
    id: 'DataBucketInventory',
    includedObjectVersions: 'All',
    scheduleFrequency: 'Daily'
  }
];
```

**Comment by joekiller** [comment]
@sagiba thanks for the example

**Comment by arnulfojr** [comment]
any updates?

**Comment by arnulfojr** [comment]
I took the liberty to create a PR for it. I still have some doubts in how to add permissions to the inventory bucket but I guess that's something we can discuss in the PR.

Feel free to comment on it :)
