### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by neg3ntropy** [aws/aws-cdk#8156]
It's unclear how to use async js operations with constructs and still be able to run cdk commands.

### Use Case

I want to add a rule to a security group allowing my current public IP and I need to do a network request to discover it.

### Proposed Solution

Maybe constructs that need async operations could override some lifecycle method and return a promise there.

### Other

I am new to CDK, sorry if this has been abundantly discussed elsewhere, I could not find it.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pofallon** [comment]
I've been churning on this same issue (needing to do async operations in a Construct) and would also be interested in a solution for this (either explicit support, or some existing pattern/guidance).  Thanks!

**Comment by hoegertn** [comment]
You should be able to instantiate your CDK stack inside an immediately invoked async function expression.

```
(async () => {
	const myIp = await something();
	new MyStack(app, myIp);
})()
```

**Comment by neg3ntropy** [comment]
@hoegertn throwing a promise without anyone looking after it may or may not work depending on the order of things. CDK has to be aware of the moment constructs are finalized.
Furthermore this pattern would require to do all IO essentially in one place then pass parameters from construct to construct, which is not great for encapsulation.

If we are showing code I would hope for something like this:
```typescript
class MyConstruct extends cdk.Construct {

     protected async onPrepare(): Promise<void> {
          const res = await something();
          new OtherConstruct(this, {res});
     }
}
```

**Comment by eladb** [comment]
This is not something we will be able to support with the current programming model of the CDK.

**Comment by sam-goodwin** [comment]
> This is not something we will be able to support with the current programming model of the CDK.

@eladb I understand why we can't support promises in the constructor, but why not in `onSynthesize`? Why can't the framework that is interpreting the Construct tree be implementing using asynchronous APIs?

**Comment by eladb** [comment]
We've removed support for `onSynthesize()` in `constructs@10.x` and basically moved all responsibility related to synthesis to the domain-specific engine. We've realized this hook is potentially hazardous since it can easily be abused to mutate the tree _during_ synthesis and then we get ourselves into issues related to dependencies and ordering which are very hard to model and get right.
