### ISSUE TITLE
What is the recommended singleton declaration pattern of custom resource providers?

### ISSUE THREAD

**Issue by sudhirjena** [aws/aws-cdk#8160]
### The Question
A few days ago, the pattern for defining singleton provider handler was changed [See commit feat(core): custom resource provider helper · aws/aws-cdk@4a76973 · GitHub](https://github.com/aws/aws-cdk/commit/4a7697370c9d04fdbb2c9fb0be71d67122573390#diff-d83b308b08cab9405c7132249b23d0c8)

In parallel, there examples of custom resource providers using `SingletonFunction`  [See aws-cdk/log-retention.ts at 986e2814e072f0334d8470a2d60ea73dcceadfe4 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/aws-lambda/lib/log-retention.ts):

```
const provider = new SingletonFunction(this, 'Provider', {

      code: Code.fromAsset(path.join(__dirname, 'log-retention-provider')),

      runtime: Runtime.NODEJS_10_X,

      handler: 'index.handler',

      uuid: 'aae0aa3c-5b4d-4f87-b02d-85b201efdd8a',

      lambdaPurpose: 'LogRetention',

      role: props.role,

    });
```

In addition to the newly documented [See aws-cdk/README.md at v1.41.0 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/blob/v1.41.0/packages/%40aws-cdk/core/README.md)

```
function getOrCreate(scope: Construct): sns.Topic {
  const stack = Stack.of(this);
  const uniqueid = 'GloballyUniqueIdForSingleton';
  return stack.node.tryFindChild(uniqueid) as sns.Topic  ?? new sns.Topic(stack, uniqueid);
}
```

**Main question** : 
1. At this point, it is very confusing as whether I should use `SingletonFunction` or non `SingletonFunction` with `getOrCreate` method.
2. Documentation doesn't clearly explain why `getOrCreate` should be used over `SingletonFunction`

### Environment

  - **CDK CLI Version:** 1.39.0
  - **Example:** Custom Resources with aws_cdk.custom_resources module
  - **Example Version:** 1.41.0
  - **OS:** OSX Mojave
  - **Language:** Python

**Comment by eladb** [comment]
Those are both supported. Happy to accept any contributions to our docs to make that clearer. Closing for now.
