### ISSUE TITLE
Add UserData in AutoScalingGroup from a file

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#8161]
- First, I've created a UserData for an **ec2.CfnLaunchTemplate** from a file, successfully.

- Now, I try to add a UserData for an ASG :
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.AutoScalingGroup.html#add-wbr-user-wbr-datacommands

But it seems that I have some encoding issues.

Here a sample of my code to add a the UserData from a file : 
```
cdk.Fn.base64(cdk.Fn.sub(fs.readFileSync('data/userdata/ecs-host-cloudwatch-logs-and-efs.sh','utf8'), {
          'EfsId': Efs.fileSystemId,
[...]
```
When created that way, it seems that in reality, it's not correctly generated : 
```
#!/bin/bash
Q29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSI9PUJPVU5EQVJZPT0iDQpNSU1FLVZl......
```
Even if a "cdk synth" generate it correctly.

- When using that code : 
```
cdk.Fn.sub(fs.readFileSync('data/userdata/ecs-host-cloudwatch-logs-and-efs.sh','utf8'), {
          'EfsId': Efs.fileSystemId,
[...]
```
UserData seems to be correct in  the Launch Configuration.

But in the server logs : 
```
/var/lib/cloud/instance/scripts/part-001: line 36: $'\r': command not found
=========== Preparing for ECS container agent updates ===========^M
/var/lib/cloud/instance/scripts/part-001: line 38: aws: command not found
[...]
```

Maybe you can add more example  with the correct way ?

---

This is a 📕 documentation issue

**Comment by sagiba** [comment]
Try something like:
```typescript
const vars = {efsId: Efs.fileSystemId};
const rawData = fs.readFileSync('data/userdata/ecs-host-cloudwatch-logs-and-efs.sh', 'utf8');
const userData = ec2.UserData.custom(cdk.Fn.sub(rawData, vars));
const asg = new AutoScalingGroup(this, 'ASG', {userData: userData});
```

**Comment by Cloudrage** [comment]
Many thanks for the advice @sagiba , it's wotking as expected now :)

When using **addUserData** Method, the pb was that it added a " _#!/bin/bash_ " at the beginning of the UserData.

It'll be interesting to add an example in ASG README : 
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-autoscaling-readme.html

**Comment by infinitydon** [comment]
@sagiba - Any idea if there is a variable in the **_rawData_** (i.e. inside data/userdata/ecs-host-cloudwatch-logs-and-efs.sh) that needs to be substituted, how can I go about this?
