### ISSUE TITLE
Adding a topic (mocked) to the cloudwatch alarm actions without an arn produces an empty list

### ISSUE THREAD

**Issue by jsauter** [aws/aws-cdk#8163]
When testing I discovered you can add a topic to an alarmaction and then add it to the cloudwatch alarmactions list without an ARN.  This appears to work, but nothing gets added to the list.  There should be a validation to prevent this from happening as the list of actions is a list of arns.   

### Reproduction Steps

` 
   const topic = {   topicName: 'UnhealthyHostTopic'   } as sns.Topic;
   const cloudwatchAction = new cloudwatchActions.SnsAction(topic);

    const metric = new cloudwatch.Metric({
      namespace: 'AWS/ApplicationELB',
      metricName: 'UnHealthyHostCount',
      dimensions: {
        LoadBalancer: props.alb.loadBalancerFullName,
        TargetGroup: albTarget.targetGroupFullName
      },
      period: cdk.Duration.seconds(300),
    });

    const alarm = new cloudwatch.Alarm(this, 'UnhealthyhHostAlarm', {
      alarmName: '${this.stackName}AlbUnhealthyHostCount',
      metric: metric,  
      evaluationPeriods: 1,
      statistic: cloudwatch.Statistic.AVERAGE,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      threshold: 0,
    });

    alarm.addAlarmAction(cloudwatchAction);
    console.log(alarm);
`

### Error Log

No error perse, but the test fails because we expect there to be something in the alarm actions list.

### Environment

  - **CLI Version      :1.40.0
  - **Framework Version: 1.40.0
  - **OS               : macOS 10.15.4
  - **Language         :Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@jsauter how are you testing and verifying your resources? can you share some code.
Here's an [example](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudwatch-actions/test/sns.test.ts#L17-L25) of how we test it, which runs and passes as a part of our current build.

**Comment by rix0rrr** [comment]
This is the offending line. You're bypassing the type system here, and specifically passing a `topic` objet that has no `topicArn`, so I'm not sure where you would expect the ARN to be coming from. Maybe `as` does something different than you are expecting?

```ts
const topic = { topicName: 'UnhealthyHostTopic' } as sns.Topic;
```

I think you are looking for `sns.Topic.fromTopicName()`.

**Comment by jsauter** [comment]
My issue is that I was able to add the topic, without an ARN to the cloudwatch action.  When I add the ARN to the topic instantiation, it works as expected.  Not sure what the stance is on validation on the passing of a resource into another resource.  Should there be validation there prevent from doing so?  Also, where is sns.Topic.fromTopicName() in the api, not seeing it?

**Comment by shellscape** [comment]
@rix0rrr `fromTopicName` doesn't exist in this repository aside from this issue. It doesn't appear to be a valid method on `Topic` according to the code here and the documentation. Perhaps you closed this one too quickly as well.

**Comment by rix0rrr** [comment]
You’re right that fromTopicName does not exist. It could, and does for other resources, but apparently it does not exist for Topic.

Sorry for referencing a nonexistent function. Topic.fromTopicArn is the one you want

**Comment by shellscape** [comment]
That would be a welcome addition. For the time being, if we need to look up a Topic by name, we have to use the aws-sdk:

```ts
  const sns = new SNS({ apiVersion: '2010-03-31', region: 'us-east-1' });
  const { TopicArn } = await sns.createTopic({ Name: topicName }).promise();

  if (!TopicArn) {
    console.error('Cannot lookup TopicArn for the SNS Topic:', topicName);
    return;
  }

  const topic = Topic.fromTopicArn(scope, `${topicName}-grantRemote`, TopicArn);
```

The kicker here is that `sns.createTopic` will simply return the ARN for a topic if it already exists. Note that this method may not play well with deployments that have multiple stacks, where a topic may be created for the first time along side of a stack that is attempting to look up the `TopicArn`.
