### ISSUE TITLE
add support for Blue/Green deployments in ECS

### ISSUE THREAD

**Issue by SeekerWing** [aws/aws-cdk#8170]
CFN recently added support for Blue Green deployments. https://aws.amazon.com/about-aws/whats-new/2020/05/aws-cloudformation-now-supports-blue-green-deployments-for-amazon-ecs/

It'll be valuable to have this feature added in CDK.

Detailed documentation in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html

This feature seems to use 2 top level keys in CFN template ```Hooks``` and ```Transform```, i'm not sure if they're already supported by CDK, if not that'll need to be built too. 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Hey there, we have an open issue for this. Gonna close to consolidate. https://github.com/aws/aws-cdk/issues/1559
