### ISSUE TITLE
Unable to deploy a ApplicationLoadBalancedEc2Service with gelf log driver

### ISSUE THREAD

**Issue by DanielWagner87** [aws/aws-cdk#8175]
It seems that it is not possible to deploy an `ApplicationLoadBalancedEc2Service` with gelf log driver. The deployment simply hangs shortly before the end. The started EC2 instance cannot be added to the cluster. 

The service event message is: _service (service-name) was unable to place a task because no container instance met all of its requirements. Container instance missing required attribute._

On <https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-event-messages.html> I have found the following information:

_(...) Others, such as the logging driver options, require the container instances to register those log drivers with the `ECS_AVAILABLE_LOGGING_DRIVERS` agent configuration variable. If your task definition contains a parameter that requires a specific container instance attribute, and you do not have any available container instances that can satisfy this requirement, the task cannot be placed._

I would have expected that the gelf log driver is registered automatically during deployment process.

### Reproduction Steps

I deploy the ECS service with the following code:

```typescript
  const cluster = new Cluster(this, "ec2-cluster-demo", {
      clusterName: "ec2-cluster-demo",  
      vpc: Vpc.fromLookup(this, "vpc-lookup", { vpcId: "vpc-id" }),
      containerInsights: true,
      capacity: {
        instanceType: InstanceType.of(InstanceClass.T3, InstanceSize.SMALL),
        vpcSubnets: {
            subnetType: SubnetType.PRIVATE
        }
      }
  });

  const ec2Service = new ApplicationLoadBalancedEc2Service(this, "my-service", {
      cluster: cluster,
      memoryLimitMiB: 1024,
      cpu: 512,
      serviceName: "my-service",
      publicLoadBalancer: true, 
      taskImageOptions: {
          image: ContainerImage.fromRegistry("my-repo/my-image"),
          containerPort: 8080,
          containerName: "my-service",
          enableLogging: true,
          logDriver: LogDrivers.gelf({
            address: "udp://my-logging-server:12201",
            compressionType: GelfCompressionType.GZIP,
            compressionLevel: -1
          })
        },
        desiredCount: 1
  });
```

### Error Log

The stack deployment hangs. The service event message is: _service (service-name) was unable to place a task because no container instance met all of its requirements. Container instance missing required attribute._

### Environment

  - **CLI Version      :** 1.41.0 (build 9e071d2)
  - **Framework Version:** 1.41.0
  - **OS               :** macOS Catalina (10.15.2) 
  - **Language         :** TypeScript

--- 

This is :bug: Bug Report

**Comment by Mickael-van-der-Beek** [comment]
I believe that his this issue is still valid.
