### ISSUE TITLE
Elasticache.CfnParameterGroup cannot be initialized with a parameter_group_name

### ISSUE THREAD

**Issue by tonyhammainen** [aws/aws-cdk#8180]
I wanted to initialize an `Elasticache.CfnCacheCluster` with a specific `Elasticache.CfnParameterGroup`. `Elasticache.CfnCacheCluster` has an optional init parameter called `cache_parameter_group_name`. However, `Elasticache.CfnParameterGroup` does not allow defining its name in its initialization. Furthermore, it does not have an attribute called `parameter_group_name`, which would be intuitive.

Not being able to define `parameter_group_name` results in having a gibberish name visible in AWS Console under the view: Elasticache > Parameter Groups.

It also makes the initialization of `Elasticache.CfnCacheCluster` with a `Elasticache.CfnParameterGroup` very unintuitive.

### Reproduction Steps
```

redis_parameter_group = elasticache.CfnParameterGroup(
    self,
    "RedisParameterGroup",
    description="Redis parameter group for ...",
    cache_parameter_group_family="redis5.0",
    properties={ },
)

redis_subnet_group = elasticache.CfnSubnetGroup(
    self,
    "RedisClusterPrivateSubnetGroup",
    cache_subnet_group_name="redis-subnet-group",
    description="Redis subnet for ...",
    subnet_ids=[subnet.subnet_id for subnet in vpc.private_subnets],
)

self.redis = elasticache.CfnCacheCluster(
    self,
    "RedisCacheCluster",
    engine="redis",
    cache_node_type="cache.r5.xlarge",
    num_cache_nodes=1,
    cluster_name="redis",
    vpc_security_group_ids=[self.redis_security_group.security_group_id],
    cache_subnet_group_name=redis_subnet_group.cache_subnet_group_name,
    cache_parameter_group_name=redis_parameter_group.????????,
)
```
### Workaround for inputting into CfnCacheCluster:
One needs to figure out that `.ref` resolves to the name
```
ref | string | Return a string that will be resolved to a CloudFormation { Ref } for this element.
-- | -- | --
```
Which with further digging resolves to
```
Return Values
Ref
When the logical ID of this resource is provided to the Ref intrinsic function, Ref returns the resource name.
```
so 
`cache_parameter_group_name=redis_parameter_group.ref`
works

### Environment

  - **CLI Version      : 1.32.2 (build e19e206)**
  - **Framework Version:**
  - **OS               : MacOS Catalina**
  - **Language         : Python**

### Suggestion

`Elasticache.CfnParameterGroup` should take `parameter_group_name` in its initialization, and it should be a callable attribute.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @tonyhammainen 

It seems the configuring the group name isn't supported by CloudFormation. 

See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-parameter-group.html

Regarding your suggestion:

> Elasticache.CfnParameterGroup should take parameter_group_name in its initialization, and it should be a callable attribute.

While this intuitively makes sense, all the `Cfn*` resources are actually auto-generated from the CloudFormation spec, so as long as its not supported, the `Cfn*` will remain the same.

To that end, I suggest you also [open](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/new) a feature request for CloudFormation.

In the meantime, we have an [issue](https://github.com/aws/aws-cdk/issues/8196) for implementing higher level constructs in the `aws-elasticache` module, where you can keep track of possibly a native CDK workaround for this issue.

**Comment by tonyhammainen** [comment]
Thanks for the speedy reply!

Opened a CFN feature request: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/484

Wishing to see a higher level construct soon!
