### ISSUE TITLE
aws-lambda-nodejs: Allow to pass .npmrc options in Dockerfile

### ISSUE THREAD

**Issue by civilizeddev** [aws/aws-cdk#8181]
For those who are using private npm repositories in their project,

It is good to have some way to override or append to `.npmrc`

```
//npm.pkg.github.com/:_authToken=302030989d098e80f098098a90b80
```

> Note: the `_authToken` in the description was randomly typed.

- [configuring-npm-for-use-with-github-packages](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#authenticating-with-a-personal-access-token)
- [npmrc - The npm config files](https://docs.npmjs.com/configuring-npm/npmrc.html)

### Use Case

Currently, it works well with the public npm repository.

But it doesn't work with private npm repositories because it requires additional access token specified in `.npmrc` file to access the private repository.

### Proposed Solution

```
new NodejsFunction(scope, 'id', {
  ...,
  npmrc: ...string[]
})
```

### Other

* [x] :wave: @jogold may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Your dependencies are normally already installed and available locally when running your CDK app. The container mounts your "project root" so they should be available. Your `npmrc` should be located in your project.

Do you have a different setup? 

Note: is the shared token a real one? You should redact it...

**Comment by civilizeddev** [comment]
I have already `.npmrc` in my project root.

But there is another one in my home directory: `~/.npmrc`, too. (usually for storing credentials)

I think it would be better to manually pass as an option, instead of crawling it from my home directory.

**Comment by jogold** [comment]
I don't understand your use case. How this `npmrc` config that you pass to the `NodejsFunction` would influence its behavior?

**Comment by civilizeddev** [comment]
Like this:

```
$ docker build ... --build-arg EXTRA_NPMRC=(from NodejsFunctionProps)
```

```
ARG EXTRA_NPMRC
RUN echo $EXTRAN_NPMRC >> .npmrc
```

**Comment by civilizeddev** [comment]
Adding additional Babel configurations does not respect my `~/.npmrc` files that contain credentials from my personal package repository.

That's why I don't add babel configuration.
