### ISSUE TITLE
Allow customization of export/import names

### ISSUE THREAD

**Issue by ccurrie-amzn** [aws/aws-cdk#821]
When defining the interfaces between stacks, it would be helpful to be able to define the export name for an exported value, so that importing stacks have a known value to depend on.

A simple use case:
* Package A defines a Lambda for Authentication that could be re-used by multiple APIs
* Package B defines a Lambda and API Gateway that uses the Auth lambda

So each package is its own App. If each package defines its own infra-code, and I don’t want to have to manually track the Auth Lambda arn, then Package A has to export something that Package B can use, either a Stack output, or ???.

Challenges:
* Package A should deploy only lambda code, not infra code
* Package B only needs to consume Package A infra output, not code

**Comment by ccurrie-amzn** [comment]
From @eladb:

> What I would do here is basically a shared package that will act as the “interface package” of the common stack. Practically it will just export a bunch of Output IDs that will serve as the bridge. Both the common stack (in your case the shared authenticator) and the consumers will depend on this “interfaces” package. The auth stack will use these constants as Ourput names and the consumers will use in ImportValue
As I am writing this, I am realizing we don’t have a simple way to customize the output names when you use our “export/import” pattern, which means you’ll have to hand roll this yourself.

This will work in the short term, assuming the export/import issue is managed. What I've been *looking* for, and I accept I may need to adjust my expectations, would be a means to depend on the auth stack at the code level, in a way that the CDK is aware that the current project isn't using that stack in its App, but will generate the IDs in the same way. This dependency may be environment specific (as in, a Beta API stack would depend on a Beta Auth stack, etc).

**Comment by rix0rrr** [comment]
This would help some use cased I'm working on as well

**Comment by eladb** [comment]
Please reopen if this is still desirable
