### ISSUE TITLE
stack.tags type mismatch while creating an A record using customDomain.

### ISSUE THREAD

**Issue by azimiester** [aws/aws-cdk#8211]
I am trying to point a subdomain to a restApi in api gateway using custom domain, the stack creation fails with an incompatible type of tags. 

### Reproduction Steps

```
    const fullSubdomain = `${subdomain}.${hostedZone.zoneName}`;

    const zone = HostedZone.fromHostedZoneAttributes(this, 'Zone', hostedZone);
    const certificate = new DnsValidatedCertificate(this, 'Certificate', {
      domainName: fullSubdomain,
      hostedZone: zone,
    });
    const customDomain = new DomainName(this, 'CustomDomain', {
      domainName: fullSubdomain,
      certificate: certificate,
    });

    new BasePathMapping(this, 'CustomBasePathMapping', {
      domainName: customDomain,
      restApi: api,
    });
    new ARecord(this, 'ApiGatewayRecordSet', {
      zone,
      recordName: fullSubdomain,
      target: RecordTarget.fromAlias(new ApiGatewayDomain(customDomain)),
    });
```

### Error Log

TS2345: Argument of type 'ApiGatewayDomain' is not assignable to parameter of type 'IAliasRecordTarget'.
  Types of property 'bind' are incompatible.
    Type '(_record: IRecordSet) => AliasRecordTargetConfig' is not assignable to type '(record: IRecordSet) => AliasRecordTargetConfig'.
      Types of parameters '_record' and 'record' are incompatible.
        Type 'import("node_modules/@aws-cdk/aws-route53/lib/record-set").IRecordSet' is not assignable to type 'import("node_modules/@aws-cdk/aws-route53-targets/node_modules/@aws-cdk/aws-route53/lib/record-set").IRecordSet'.
          Types of property 'stack' are incompatible.
            Type 'import("node_modules/@aws-cdk/core/lib/stack").Stack' is not assignable to type 'import("node_modules/@aws-cdk/aws-route53-targets/node_modules/@aws-cdk/core/lib/stack").Stack'.

[tsl] ERROR in PATH.ts(64,59)
      TS2345: Argument of type 'DomainName' is not assignable to parameter of type 'IDomainName'.
  The types of 'stack.tags' are incompatible between these types.
    Type 'import("node_modules/@aws-cdk/core/lib/tag-manager").TagManager' is not assignable to type 'import("node_modules/@aws-cdk/core/lib/tag-manager").TagManager'.
      Types have separate declarations of a private property 'tags'.

### Environment

  - **CLI Version      :1.41.0**
  - **Framework Version:**
  - **OS               :Mac 10.15.3**
  - **Language         : Typescript**

### Other

Its the same error if I use the restApi instead of customdomain.

--- 

This is :bug: Bug Report

**Comment by azimiester** [comment]
I had a hunch that this is related to mismatched version of dependencies but updating everything to latest didn't fix it. But deleting node_modules and a fresh install of dependencies fixed it.

**Comment by fourgates** [comment]
I also had a similar issue. This was caused by mixing and matching diff cdk versions. I referenced the follow ticket:

https://github.com/aws/aws-cdk/issues/542#issuecomment-449694450

I resolved the issue by making sure every cdk dependency was on the same version.
