### ISSUE TITLE
eks: allow specifying timeouts for HelmCharts

### ISSUE THREAD

**Issue by gibbster** [aws/aws-cdk#8215]
For long running helm charts the creation times out. 

### Reproduction Steps

I had this issue with the following resource (based on a minimal cluster defined through the CDK Cluster component).

    new eks.HelmChart(this, 'spinnaker', {
      cluster,
      chart: 'spinnaker',
      repository: 'https://kubernetes-charts.storage.googleapis.com/',
      version: '2.0.0-rc3',
      namespace: 'spinnaker'
    });

### Error Log

3/9 | 3:05:54 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | spinnaker/Resource/Default (spinnakerC4B2DB2C) Failed to create resource. TimeoutError: Connection timed out after 120000ms

### Environment

  - **CLI Version      :1.41.0 (build 9e071d2)
  - **Framework Version: 1.41.0
  - **OS               : macOS 10.14.6
  - **Language         : typescript

### Other

The helm command has an option for timeout, and in fact the chart I was trying to run (stable/spinnaker) suggests a timeout of 600s: https://github.com/helm/charts/blob/master/stable/spinnaker/README.md. I believe that the chart should add timeout as a option:

https://github.com/aws/aws-cdk/blob/86eac6af074bf78a921c52d613eca0dd4a514a49/packages/%40aws-cdk/aws-eks/lib/helm-chart.ts#L8-L50
1.41.0 (build 9e071d2)

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
It would be possible to allow timeouts of up to 15m. @pahud is this something you'd be interested to pick up?

**Comment by pahud** [comment]
@eladb  Sure!

The interesting thing is the Kubelctl Provider default timeout is 15min now.

https://github.com/aws/aws-cdk/blob/99e7330fc5fc140964c47d8c6dbaee2b46b382e1/packages/%40aws-cdk/aws-eks/lib/kubectl-provider.ts#L26

And the error message provided doesn't seem to be a lambda timeout

3/9 | 3:05:54 PM | CREATE_FAILED | Custom::AWSCDK-EKS-HelmChart | spinnaker/Resource/Default (spinnakerC4B2DB2C) Failed to create resource. TimeoutError: Connection timed out after 120000ms

I'll try re-produce it in my environment and check the logs.

**Comment by eduardomourar** [comment]
We are getting the same error while running:
```typescript
cluster.addChart('Prometheus', {
  chart: 'prometheus-operator',
  repository: 'https://kubernetes-charts.storage.googleapis.com/',
  version: '8.13.8',
  namespace: 'default'
});
```

**Comment by eduardomourar** [comment]
I can confirm that there is a timeout from the AWS SDK (as specified [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property)) and it can solved by adding to the provider framework code:

```ts
lambda.config.update({httpOptions: { timeout: 900000 }});
```

I will make a PR soon to fix this.

**Comment by pahud** [comment]
It sounds like an underlying http timeout between the provider framework and the kubectl provider which executes the helm cmand. Is the fix working in your environment? @eduardomourar

**Comment by eduardomourar** [comment]
Yes, so far so good. My helm charts are taking about 3 minutes to deploy and without any issue now.

I believe the issue is that the invokeFunction used by the provider framework has this 2 minutes timeout, so it was not honoring the overall timeout (15 minutes) set for the target lambda.
