### ISSUE TITLE
Support for Chunks in TXT Records (Route53, DNS)

### ISSUE THREAD

**Issue by OG84** [aws/aws-cdk#8244]
As there is a 255 character limitation of values in TXT records, `TxtRecord` should support creating chunked TXT values.

e.g. currently if we try like this ...

```
new TxtRecord(this, 'gmailDomainkeyTxt', {
      recordName: 'google._domainkey',
      zone: hostedZone,
      values: [
        'very long dkim string'
      ],
    });
```

... this will lead to a `CharacterStringTooLong` exception when deploying.
In cloudformation or when doing it manually there is a workaround to use chunks. See [route53-resolve-dkim-text-record-error](https://aws.amazon.com/de/premiumsupport/knowledge-center/route53-resolve-dkim-text-record-error/).

So instead of having `"too long string"` it's possible to split the string: `"first part" "second part"`.
But this is still a single value and not a separate line.

Currently the cdk escapes strings, so this approach is not possible.

### Use Case

To verify my domain with google. (Requires a dkim txt record, which is more than 255 chars)

### Proposed Solution

We could introduce e.g. a `values: TxtRecordValue[]` instead of a string[] array for the `values` property.
E.g. like the `MxRecord` is doing it for its values.
Some mechanism to support chunks for TXT Records would be great.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by niklaswallerstedt** [comment]
Any updates on this? I'm unable to deploy a stack with a DKIM-value of 410 characters.

```
route:  0/2 | 3:05:12 PM | CREATE_IN_PROGRESS   | AWS::Route53::RecordSet  | DKIM (DKIM785B3340) 
route:  0/2 | 3:05:14 PM | CREATE_FAILED        | AWS::Route53::RecordSet  | DKIM (DKIM785B3340)
[Invalid Resource Record: FATAL problem: CharacterStringTooLong (Value is too long) encountered with '"v=DKIM1; ...
```

**Comment by niklaswallerstedt** [comment]
I can confirm that the fix works in v1.62.0 🎉 Thank you for your work on the CDK, much appreciated!

**Comment by timwelch** [comment]
This doesn't work if you're reading in DKIM strings from ssm parameters. It appears that the substitution and subsequent checks for string length >255 doesn't happen in the right order, so when you go to deploy this is the synthesized CFN and the route53 commands fail.

I've tried a few things to no avail. I've even tried lazy loading the strings, but that doesn't work either.

Is there another workaround, or do I need to just use a lambda w/boto3 for this?


`  "dxxxxjxjxjxjxj658F1B03": {
   "Type": "AWS::Route53::RecordSet",
   "Properties": {
    "Name": "outbound._domainkey.develop.somedomain.com.",
    "Type": "TXT",
    "HostedZoneId": "Z30303030303",
    "ResourceRecords": [
     {
      "Fn::Join": [
       "",
       [
        "\"v=DKIM1; k=rsa; p=",
        {
         "Ref": "dkimpublic1ssmdevelopParameter"
        },
        {
         "Ref": "dkimpublic2ssmdevelopParameter"
        },
        "\""
       ]
      ]
     }
    ],
    "TTL": "300"
   },
   "Metadata": {
    "aws:cdk:path": "coreDev/smtpdout/dkim-txt-develop.somedmain.com/Resource"
   }
  },`

**Comment by timwelch** [comment]
The expected output should include quotes between the parameters, like this...


```
"dxxxxjxjxjxjxj658F1B03": {
   "Type": "AWS::Route53::RecordSet",
   "Properties": {
    "Name": "outbound._domainkey.develop.somedomain.com.",
    "Type": "TXT",
    "HostedZoneId": "Z30303030303",
    "ResourceRecords": [
     {
      "Fn::Join": [
       "",
       [
        "\"v=DKIM1; k=rsa; p=",
        {
         "Ref": "dkimpublic1ssmdevelopParameter"
        },
        "\" \"",
        {
         "Ref": "dkimpublic2ssmdevelopParameter"
        },
        "\""
       ]
      ]
     }
    ],
    "TTL": "300"
   },
   "Metadata": {
    "aws:cdk:path": "coreDev/smtpdout/dkim-txt-develop.somedmain.com/Resource"
   }
  },
```
