### ISSUE TITLE
cloudtrail: Construct does not account for partitions

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#8247]
Trail construct `logAllS3DataEvents` does not account for partition.

### Reproduction Steps

```
    const trail = new cloudtrail.Trail(this, `Trail`, {
      bucket: this.cloudTrailBucket,
    });

    trail.logAllS3DataEvents();
```

### Error Log

In GovCloud CloudFormation console:

```
Value arn:aws:s3::: for DataResources.Values is invalid. 
```

### Environment

  - **CLI Version      : 1.41.0**
  - **Framework Version: 1.41.0**
  - **OS               : macOS**
  - **Language         : TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
@cmckni3 would you like to make a PR out of that?

**Comment by cmckni3** [comment]
Already made PR last week.

See #8248
