### ISSUE TITLE
cdk diff cannot select a stack

### ISSUE THREAD

**Issue by oonisim** [aws/aws-cdk#8249]
CDK diff has STACKS option but specifying a stack still show diff of all stacks.

```
$ cdk diff --help
cdk diff [STACKS..]
```

### Reproduction Steps

```
cdk diff ${STACK_NAME}
```

### Error Log

None

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

```
MAC OS 10.15.4
$ aws --version
aws-cli/2.0.7 Python/3.7.4 Darwin/19.4.0 botocore/2.0.0dev11

$ cdk version
1.41.0 (build 9e071d2)
(venv) WS226440:application onishim4p$ 
```

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@oonisim by default `diff` will diff all of the stacks if no arguments are provided

If you run `cdk ls` and supply any of the listed stacks, it should only display the diff for that stack

i.e.
```console
$ cdk ls            
FooStack
FooStack2

$ cdk diff dasf     
No stack found matching 'dasf'. Use "list" to print manifest

$ cdk diff FooStack
Stack FooStack
There were no differences

$ cdk diff Foostack2
Stack Foostack2
IAM Statement Changes
...
Resources
[+] AWS::IAM::Role my-role myrole97476C1B 
[+] AWS::IAM::InstanceProfile emr-ec2-instance-profile emrec2instanceprofile 
```

can you provide some repro steps for the scenario you're running into as well as the error output. you can also run your command with the `-v` flag to get more verbose output that will display the command line arguments that were read in.
