### ISSUE TITLE
imagebuilder: Not able to add components to an image recipe

### ISSUE THREAD

**Issue by jimistry123** [aws/aws-cdk#8250]
### The Question

I am trying to add components using the ```components(java.util.List<java.lang.Object> components)``` method of ```CfnImageRecipe```, but when I look at the generated CFN template, I see an empty list under ```Components``` property. 

Since the image recipe takes in components as a list of [ComponentConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-imagebuilder-imagerecipe-componentconfiguration.html), I tried to provide the list as follows:

```java
CfnImageRecipeProps imageRecipeProps = CfnImageRecipeProps.builder()
        .name("Image Recipe")
        .parentImage(parentImageId)
        .components(Arrays.asList(new HashMap<String, String>(){{
          put("ComponentArn", firstComponent.getAttrArn());
          // ...
        }}))
        .version(IMAGEBUILDER_RECIPE_VERSION)
        .build();

  CfnImageRecipe imageRecipe = new CfnImageRecipe(this, "Image Recipe", imageRecipeProps);
```

But when I look at the generated CFN template, I see an empty list under Components:

```json
"ImageRecipe": {
      "Type": "AWS::ImageBuilder::ImageRecipe",
      "Properties": {
        "Components": [
          {}
        ],
```

And since there is no ```ComponentArn``` property available inside CFN template, an attempt to deploy the stack fails with the following:

```
1/6 | 5:31:04 PM | CREATE_FAILED        | AWS::ImageBuilder::ImageRecipe | EMR AMI Image Recipe (EMRAMIImageRecipe) The value supplied for parameter 'components[0]' is not valid. 'component]' must contain ['componentArn'] properties (Service: Imagebuilder, Status Code: 400...
```

Can you please check if this a bug or am I providing the component list incorrectly?

### Environment

  - **CDK CLI Version:**  1.42.0
  - **Module Version:**  1.42.0
  - **OS:**  macOS Mojave
  - **Language:**  Java

### Other information

On the other hand, if I create the image recipe directly as ```cdk.CfnResource```, then it works:

```java
List<HashMap<String, String>> componentConfigurationList = new ArrayList<>();
for (Reference arn : getComponentArns()) {
  componentConfigurationList.add(new HashMap<String, String>(){{
    put("ComponentArn", arn.toString());
  }});
}
CfnResource.Builder.create(this, "ImageBuilderRecipe")
    .type("AWS::ImageBuilder::ImageRecipe")
    .properties(new HashMap<String, Object>() {{
      put("Name", "Image Recipe");
      put("ParentImage", parentImageId);
      put("Components", componentConfigurationList);
      put("Version", IMAGEBUILDER_RECIPE_VERSION);
    }}).build();
```

**Comment by rix0rrr** [comment]
The type you're looking for is probably called [`CfnImageRecipe.ComponentConfigurationProperty`](https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/appstream/CfnImageBuilder.html) and it has a builder too.

**Comment by ryanwilliams83** [comment]
I came across this issue when troubleshooting a similar problem in C#

Components must be set to an array of CfnImageRecipe.ComponentConfigurationProperty.
A List<CfnImageRecipe.ComponentConfigurationProperty> will not work.
