### ISSUE TITLE
TypeError raised when try to create a VpcEndpoint in Python

### ISSUE THREAD

**Issue by jmferrete** [aws/aws-cdk#8254]
### The Question

I was unable to create a VpcEndpoint by using the `aws_cdk.aws_ec2.VpcEndpoint` python class.
It is raising me the next TypeError exception:
```
TypeError: Can't instantiate abstract class VpcEndpoint with abstract methods vpc_endpoint_id
```

Steps to reproduce:

Simply, try to instantiate the class VpcEndpoint by giving the minimal required parameters (scope, id) following [the documentation link](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/VpcEndpoint.html#vpcendpoint).

```python
from aws_cdk import (
    core,
    aws_ec2 as ec2
)

class MyStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        my_endpoint = ec2.VpcEndpoint(self, 'MyVPCEndpoint')
```

### Environment

  - **CDK CLI Version:** 1.42.0 (build 3b64241)
  - **Module Version:** aws-cdk.aws-ec2==1.42.0
  - **Node.js Version:** v12.14.1
  - **OS:** Ubuntu 20.04 LTS
  - **Language:** Python 3.8.2

### Possible solution

It works for me if I remove the `abc.abstractmethod` decorator for the `vpc_endpoint_id` method in the `aws_cdk.aws_ec2.VpcEndpoint` class:

```python
    @builtins.property
    @jsii.member(jsii_name="vpcEndpointId")
    @abc.abstractmethod # <- Removing this line to make this method not abstract
    def vpc_endpoint_id(self) -> str:
        """The VPC endpoint identifier."""
        ...
```

**Comment by rix0rrr** [comment]
You need either `GatewayVpcEndpoint` or `InterfaceVpcEndpoint`

**Comment by jmferrete** [comment]
> You need either `GatewayVpcEndpoint` or `InterfaceVpcEndpoint`

It worked perfectly with `InterfaceVpcEndpoint`. Thanks a lot!
