### ISSUE TITLE
Support for other cloud such as Azure and GCE

### ISSUE THREAD

**Issue by sseshachala** [aws/aws-cdk#8260]
CDK with its flexibility of generating state could work wonders if we can have it support ARM templates for Azure. CDK8s already support K8 compliant yaml. So in a way google is already covered.Extending CDK to support other cloud platforms should be of immense help for enterprises to codify the infra in a standardized way.

### Use Case
CDK apis currently support only AWS and generates CF templates and deploys them. We should plan to extend CDK to generate Arm templates for Azure.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
The AWS CDK is designed to define infrastructure on AWS, but like you noted, there is nothing that precludes anyone from using the core tech of the CDK (namely [constructs] and [jsii]) to create CDKs for any domain.

[constructs]: https://github.com/aws/constructs
[jsii]: https://github.com/aws/jsii
