### ISSUE TITLE
ECS-Pattern ignores protocol in Port Mapping

### ISSUE THREAD

**Issue by mitch-dm** [aws/aws-cdk#8265]
ECS Pattern ApplicationMultipleTargetGroupsFargateService ignores protocol in port mapping when passed FargateTaskDefinition. This prevents using ports besides these defaults:

https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/util.ts#L33-L48

### Reproduction Steps

```typescript
const myTaskDefinition = new ecs.FargateTaskDefinition(this, 'MyTask', {})
const myContainer = myTaskDefinition.addContainer('MyContainer', {
    essential: true,
    image: ecs.ContainerImage.fromRegistry("httpd:2.4")
})
myContainer.addPortMappings({
    containerPort: 3001,
    protocol: ecs.Protocol.TCP
})

new ApplicationMultipleTargetGroupsFargateService(this, 'MyService', {
    taskDefinition: myTaskDefinition
})
```

### Error Log

```
Don't know default protocol for port: 3001; please supply a protocol
```

### Environment

  - **CLI Version      :** 1.38.0
  - **Framework Version:** 1.38.0
  - **OS               :** macOS 10.13.3
  - **Language         :** TypeScript 3.8.3

### Other

Missing protocol as argument:
https://github.com/aws/aws-cdk/blob/09ae5ab4c24f2c50d6e124a449608c286d841497/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts#L161-L164

--- 

This is :bug: Bug Report

**Comment by hencrice** [comment]
Related to #6428

**Comment by hencrice** [comment]
Hey @mitch-dm were you trying to terminate TLS at the container level? As David explained in #6428, this pattern aims to terminate TLS at the the load balancer level and trusts the security within VPC.

**Comment by mitch-dm** [comment]
Hey @hencrice, this not about trying to terminate TLS at the container. Our container exposes port 3001, but we are only able to use a default port (80, 8008, 8080). Changing the port mapping in the example works:
```
myContainer.addPortMappings({
    containerPort: 8080,  // works with 80, 8008, 8080 but not with 3001, 3002, ...
    protocol: ecs.Protocol.TCP
})
```

**Comment by hencrice** [comment]
Hey @mitch-dm in that case, seems like you can specify the `targetGroups` [property](https://github.com/aws/aws-cdk/blob/cb03a601599b56539081caf602647d1f431d2d59/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts#L157), which in terms allows you to supply both `port` and `protocol`.

**Comment by woodyatmove** [comment]
Hi @hencrice, I've run into the same issue as @mitch-dm described. Would you mind posting an example using the targetGroups property as a solution?  The `defaultProtocolForPort` function doesn't appear to take the protocol property into account, and I'm not sure how to property map any port outside of those referenced in the `defaultProtocolForPort` function.  Many thanks!
