### ISSUE TITLE
Do EC2 and RDS modules support tagging for VPC and database instance?

### ISSUE THREAD

**Issue by zulhfreelancer** [aws/aws-cdk#8267]
### The Question

How to add a tag to a VPC (`new ec2.Vpc()`) and to a RDS instance (`new rds.DatabaseInstance()`)?

From the [EC2](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html) and [RDS](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstance.html) docs, I can't see `tag` or `tags` defined inside the props table.

But when I checked [this page](https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html), looks like _AWS::EC2::VPC_ and _AWS::RDS::DBInstance_ can be tagged.

So, I'm just checking here, am I missing something here or they are not yet implemented inside `@aws-cdk/aws-ec2` and `@aws-cdk/aws-rds` modules?

### Environment

  - **CDK CLI Version:** 1.39.0 (build 5d727c1)
  - **Module Version:** ^1.39.0
  - **OS:** ^1.39.0
  - **Language:** TypeScript

### Other information

I can proceed with tagging when using Elasticache's CfnCacheCluster since it has `tags` listed in the props table ([docs page](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticache.CfnCacheCluster.html)).

**Comment by jogold** [comment]
Tagging is managed at the `Construct` level.

Have a look at https://docs.aws.amazon.com/cdk/latest/guide/tagging.html

**Comment by zulhfreelancer** [comment]
Thanks @jogold. Other than tagging, what else should be managed at construct level? Any reference for me? Just curious.

**Comment by jogold** [comment]
> Thanks @jogold. Other than tagging, what else should be managed at construct level? Any reference for me? Just curious.

Tagging is implemented using [Aspects](https://docs.aws.amazon.com/cdk/latest/guide/aspects.html). Aspects are a way to apply an operation (such as tagging) to all constructs in a given scope.

**Comment by zulhfreelancer** [comment]
Noted. Thanks @jogold for the info. Appreciate it.
