### ISSUE TITLE
Compatibility issues with aws-cloudformation/cfn-lint

### ISSUE THREAD

**Issue by guidola** [aws/aws-cdk#8269]
### The Question

The generated templates do not comply with rules W3010 & E3012 as enforced by cfn-lint.

* **W3010 Warning** is hit when defining the environment parameter when instantiating a stack as per recommended for production stacks. 
``` typescript
new Stack(scope, "stackId", {
     ...,
    env: {
        account: <account_id>,
        region: <region>
    }
})
```
That makes the generated template reference the availability zones when used as:
```
resources:
    resource-logical-id: {
        ...,
        properties: {
            ...,
            AvailabilityZone: "<region-id>"
         }
    }
}
```
which violates W3010 rule:
```console
W3010 Don't hardcode <region-id> for AvailabilityZones
```

* **E3012 Error** is hit when using the _TTL_ property of the  **ARecord** Construct. Since that property is implemented by the parent class **RecordSet** that issue would extend to any Construct that extends RecordSet.
> This affects the **@aws-cdk/route53** module

The ttl is given as a `Duration` when instantiating the construct and later processed and transformed to a `string` value in the `RecordSet` constructor as shown below:

```typescript
export class RecordSet extends Resource implements IRecordSet {
  public readonly domainName: string;

  constructor(scope: Construct, id: string, props: RecordSetProps) {
    super(scope, id);

    const ttl = props.target.aliasTarget ? undefined : ((props.ttl && props.ttl.toSeconds()) || 1800).toString();
```
which makes it then after be rendered in the template as a `string`:

```
...,
logical-id: {
    Properties: {
        ...,
        TTL: "60"
    }
```
while `cfn-lint` enforces it to be a `long`:
```console
E3012 Property ********/RecordSet/Properties/TTL should be of type Long
```

### Environment

  - **CDK CLI Version:** 1.42.0 (build 3b64241)
  - **Module Version:** 1.42.0 (build 3b64241)
  - **OS:** Windows 10
  - **Language:** Typescript

### Other information

* **cfn-lint version**: 0.32.1

> Related to https://github.com/aws/aws-cdk/issues/5309

**Comment by eladb** [comment]
We currently don't have a systemic way to comply with cfn-init (this is #5309), so I am going to break this issue down into two separate issues and we can address them case-by-case.

**Comment by eladb** [comment]
Split to https://github.com/aws/aws-cdk/issues/8431 and https://github.com/aws/aws-cdk/issues/8430
