### ISSUE TITLE
ALB: Lambda permissions should use aws:SourceArn

### ISSUE THREAD

**Issue by argenstijn** [aws/aws-cdk#8271]
This is both more secure and makes the ALB show up in the Lambda console.

----------------

If you create a Lambda with ALB integration 
you don't see the ALB popping up in the AWS console in the designer TAB.

![afbeelding](https://user-images.githubusercontent.com/130732/83248453-5ec70b00-a1a5-11ea-8407-0be2400735c0.png)

Should be like this:

![afbeelding](https://user-images.githubusercontent.com/130732/83248514-7605f880-a1a5-11ea-86f1-210fea36b939.png)

I think you should explicit give the TG access to the lambda.

 {
      "Sid": "WhaTEVER",
      "Effect": "Allow",
      "Principal": {
        "Service": "elasticloadbalancing.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "LAMBDA",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "TARGET GROUP"
        }
      }
    }

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by argenstijn** [comment]
It;s CDK 1.39 by the way. I am using Java 11 with CDK!

**Comment by rix0rrr** [comment]
Sure. But I'm a little confused. 

Can you explain to me how it is that the TargetGroup/LoadBalancer can apparently *call* the Lambda (since handling requests works, no?) but not *see* it to render it in the console?

**Comment by argenstijn** [comment]
Because of the permission below. But this is not enough clearly for AWS to show the ALB in the designer view of the LAMBDA

{
      "Sid": "iapi-dev-nec-test-CDKStack-awsLambdaLambdaAliasInvokeServicePrincipalelasticloadbalanc-J0ER6SMD8G8Y",
      "Effect": "Allow",
      "Principal": {
        "Service": "elasticloadbalancing.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:eu-west-1:124905771571:function:iapi-dev-nec-test-lambda:life"
    },
