### ISSUE TITLE
Expose minimum and maximum healthy percent property for QueueProcessingService

### ISSUE THREAD

**Issue by plastic-karma** [aws/aws-cdk#8277]
In ecs patterns, application load-balanced service can specify [minimum healthy percentage](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L119). This is missing for [queue based services](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts#L10).

### Use Case

We want to have a queue based service, but have a more conservative deployment strategy with 2/3 of tasks being up during deployments.

### Proposed Solution

Add minimum and maximum healthy percentage in [QueueProcessingServiceBaseProps](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts#L10) and pass these values to service creation in [Fargate](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L99) and [EC2](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts#L94)

### Other

- [x] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by plastic-karma** [comment]
Is this being worked upon? Otherwise, I would love to contribute.

**Comment by hencrice** [comment]
@plastic-karma We just finished triaging but I haven't started anything yet. Feel free to take a stab and thanks for the contribution!
