### ISSUE TITLE
Why doesn't CfnDistribution aliases accept an IResolvable as well as an array?

### ISSUE THREAD

**Issue by acarlton** [aws/aws-cdk#8284]
### The Question

I am using CDK for the express purpose of outputting a final deliverable in the form of a CloudFormation template. As such, most of my cdk code uses Cfn* resource types.

For the CfnDistibution CloudFront resource, why does the optional aliases? parameter accept only an array and not an IResolvable like many other cases? The use case I am working on is to optionally set that property in the CloudFormation template using core.Fn.condition_if(...).to_string(), like I have been doing elsewhere in my code. Right now I'm having to resort to add_override() to write the logic at the template level, but it seems cleaner and more inline with the other parts of CDK to support an IResolvable for that parameter...

### Environment

  - **CDK CLI Version:** 1.34.1
  - **Module Version:** 1.34.1
  - **OS:** Ubuntu 18.04
  - **Language:** Python

**Comment by skinny85** [comment]
Hey @acarlton ,

thanks for opening the issue. The reason we don't support `IResolvable` for properties who have type `string[]` (and also `string` and `number`) is that those are encoded as Tokens directly, without going through an `IResolvable` object. So, if you want to use an `IResolvable` for the `aliases` property, you need to use the `Token.asList()` method:

```ts
import * as cfront from '@aws-cdk/aws-cloudfront';
import * as core from '@aws-cdk/core';

new cfront.CfnDistribution(this, 'Distribution', {
  distributionConfig: {
     aliases: core.Token.asList(core.Fn.conditionIf(...)),
  },
});
```

Let me know if this solves your issue!

Thanks,
Adam

**Comment by acarlton** [comment]
Thanks @skinny85 -- that's exactly what I was looking for! Solved :)
