### ISSUE TITLE
Getting template validation errors when creating AppSync resources

### ISSUE THREAD

**Issue by DennisSkoko** [aws/aws-cdk#8289]
### Description

When trying to creating AppSync resources, it is unable to be deployed to AWS since a validator is emitting an error saying that the template contains unknown resource types.

### Reproduction Steps

1. Execute `npx cdk --language javscript`
2. Open the `***-stack.js` file within the `lib` folder.
3. Add the code snippet (see snippet below) into the `constructor` function within the class.
4. Execute `npm run cdk deploy`

**Code snippet**
```js
constructor(scope, id, props) {
  super(scope, id, props);

  new appsync.CfnGraphQLApi(this, 'HelloWorld', {
    name: 'HelloWorld',
    authenticationType: 'API_KEY'
  })
}
```

### Error Log

```
Template format error: Unrecognized resource types: [AWS::AppSync::GraphQLApi]
```

### Environment

  - **CLI Version      :** 2.0.17 (*guessing this is `aws-cli`*)
  - **Framework Version :** 1.42.0 (*guessing this is `aws-cdk`*)
  - **OS               :** macOS Catalina
  - **Language         :** Javascript

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Could it be that you're deploying in a region where AWS AppSync is not available?

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

**Comment by DennisSkoko** [comment]
@jogold  I have `eu-north-1` set as my default but when running the deploy command, I use `npm run cdk deploy -- --profile eu-central-1`. I have tested by removing the GraphQL resource and deploying again and it created the stack in `eu-central-1`.

**Comment by DennisSkoko** [comment]
Can also note, I just tried deploying the stack manually with aws-cli. I did this by deploying the generated template file in `cdk.out` with `aws cloudformation deploy --stack-name *** --template-file ***Stack.template.json` and it successfully deployed it.

**Comment by BryanPan342** [comment]
@DennisSkoko have you experienced this with using `GraphQLApi` instead of `CfnGraphQLApi`?
