### ISSUE TITLE
AppSync: support TransactWriteItems

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#8292]
Support `TransactWriteItems` in DynamoDB resolvers.

### Use Case

To make a `TransactWriteItems` request to DynamoDB to write multiple items.

### Proposed Solution

Add a `TransactItem` class that wraps the table name and `MappingTemplates` for the Put, Update and Delete operations. This requires some refactoring to reuse the `dynamoDbXxxItem` functions, which include the "version" and "operation" attributes.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Confirming this is still valid

@BryanPan342 I see this is on a closed project board, are you still intending to do this?

**Comment by MrArnoldPalmer** [comment]
@peterwoodworth this is still needed yes.

**Comment by BryanPan342** [comment]
Will this be needed after this [feature](https://github.com/aws/aws-appsync-community/issues/147#issuecomment-768437610)?

**Comment by MrArnoldPalmer** [comment]
I believe it still will be as users will still want to use TransactWriteItems in VTL.

**Comment by redjonzaci** [comment]
Is this done?
