### ISSUE TITLE
‼️ NOTICE: grantInvoke on SingletonFunction fails with "No child with id"

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8295]
Please add your +1 👍 to let us know you have encountered this

---

### Overview:

Calling `grantInvoke` on `SingletonFunction` produces the error `No child with id: ...`.

This bug was introduced in version `1.39.0`.

### Workaround:

No workaround available

### Solution:

PR for the fix - https://github.com/aws/aws-cdk/pull/8296/

### Related Issues:

https://github.com/aws/aws-cdk/issues/8240

**Comment by nija-at** [comment]
Reproduction code -

```ts
import { ServicePrincipal } from '@aws-cdk/aws-iam';
import { Code, Runtime, SingletonFunction } from '@aws-cdk/aws-lambda';
import { App, Stack } from '@aws-cdk/core';

const app = new App();
const stack = new Stack(app, 'mystack');

const fn = new SingletonFunction(stack, 'fn', {
  code: Code.fromInline('foo'),
  runtime: Runtime.NODEJS_12_X,
  handler: 'index.handler',
  uuid: '92e0bbf2-10d2-427c-9f79-79f671303428',
});

fn.grantInvoke(new ServicePrincipal('events.amazonaws.com'));
```

Regression introduced in `1.39.0`.

**Comment by nija-at** [comment]
Bug introduced here - https://github.com/aws/aws-cdk/commit/1819a6b5920bb22a60d09de870ea625455b90395#diff-73cb0d8933b87960893373bd263924e2

**Comment by nija-at** [comment]
PR for the fix - https://github.com/aws/aws-cdk/pull/8296/

**Comment by shivlaks** [comment]
[1.42.1](https://github.com/aws/aws-cdk/releases/tag/v1.42.1) has been released and includes the fix for this issue.
