### ISSUE TITLE
Adding an AWS account Id to an SQS queue?

### ISSUE THREAD

**Issue by owenashurst** [aws/aws-cdk#8297]
### The Question

I'm trying to follow this simple [guide here](https://docs.developer.amazonservices.com/en_US/subscriptions/Subscriptions_ReceivingNotifications.html) that explains how to add an AWS account Id for MWS (Marketplace web services) to the SQS permissions, however when looking at the interfaces for SQS I don't see anything for "permissions". I thought it'd be a policy but I think I'm going down the wrong road there.

### Environment

  - **CDK CLI Version:** 1.42.0
  - **Module Version:** "@aws-cdk/aws-sqs": "^1.42.0"
  - **OS:** all
  - **Language:** TypeScript

**Comment by michaelwiles** [comment]
This should sort you out:

```
abc_queue = sqs.Queue(self, 'ABC')

abc_queue.grant(AccountPrincipal('437568002678'), 'sqs:SendMessage', 'sqs:GetQueueAttributes')
```

This is python - I'm sure you can figure out what it looks like typescript.

**Comment by owenashurst** [comment]
> This should sort you out:
> 
> ```
> abc_queue = sqs.Queue(self, 'ABC')
> 
> abc_queue.grant(AccountPrincipal('437568002678'), 'sqs:SendMessage', 'sqs:GetQueueAttributes')
> ```
> 
> This is python - I'm sure you can figure out what it looks like typescript.

Thank you, that helped out a lot! It's very similar in TypeScript;

```
import { AccountPrincipal } from '@aws-cdk/aws-iam';
import { Queue } from '@aws-cdk/aws-sqs';

const myQueue = new Queue(this, 'queue', {
      queueName: 'my-queue'
});

myQueue.grant(new AccountPrincipal('437568002678'), 'sqs:SendMessage', 'sqs:GetQueueAttributes');
```

**Comment by MrArnoldPalmer** [comment]
Looks like you’re good here. Reopen if otherwise.
