### ISSUE TITLE
Support "cooldown" parameter for QueueProcessingServiceBaseProps in aws-ecs-patterns lib

### ISSUE THREAD

**Issue by astafev** [aws/aws-cdk#8298]
At the moment in the constructor of QueueProcessingFargateService scaling steps can be defined, but `cooldown` parameter from autoscaling cannot:
```
this.service = new ecsPatterns.QueueProcessingFargateService(this, 'Service', {
      scalingSteps: [{...}, {...}],
      ....
    });
```

### Proposed Solution

As far as I can see, the parameter should be provided here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts#L270 in a similar fashion as `scalingSteps`.

### Other

* I see that the behavior can be modified by extending QueueProcessingFargateService and overriding `configureAutoscalingForService`, but I believe that if `scalingSteps` is defined in the config, `cooldown` should be defined as well.
* While reading the code of the component QueueProcessingServiceBase, I found out that it has CpuScaling defined which cannot be affected anyhow by configuration, I believe it also should be modifiable. For my use case, scaling based on the queue size is enough.

---

This is a :rocket: Feature Request

**Comment by fitzchak** [comment]
I would like to add to this feature request a support for different cooldown value for scaling up and scaling down.

The reason for the need of a bigger value for cooldown period for scaling down of QueueProcessingFargateService as when the task is taking long to complete and I set scaling down to 0 if there are no messages in the queue, the running tasks will be killed upon scaling down unless I have an option to configure longer period of scaling down.

**Comment by phishy** [comment]
Oh yeah, just hit this wall. I would love for the policy to at least be exposed as a property so we can modify it, if not in the constructor.
