### ISSUE TITLE
Allow passing cloudformation removal policy at the stack level

### ISSUE THREAD

**Issue by michaelday008** [aws/aws-cdk#8326]
In cloudformation you can specify the stack resource removal policy at the stack level.

It would be great if cdk could do this.

Something like 
```
new VPCStack(app, 'VPCStack', {
    env: {region: 'ca-central-1', account: '123456},
    removalPolicy: cdk.RemovalPolicy.RETAIN
});
```

### Use Case

We may at times need to rebuild our internal subnets and VPC configuration, while retaining the external EIPs associated with the NAT gateways.

CDK does not seem to currently have this functionality, so at the very minimum it would be nice to create the stack initially with CDK, then remove the stack without removing the resources so we can take over manual management and re-create the implementation without deleting the EIPs.

### Proposed Solution
```
new VPCStack(app, 'VPCStack', {
    env: {region: 'ca-central-1', account: '123456},
    removalPolicy: cdk.RemovalPolicy.RETAIN
});
```

### Other

Related: https://github.com/aws/aws-cdk/issues/4067
Related: https://github.com/aws/aws-cdk/issues/4705

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can write an Aspect to do this. Iterate through all constructs and if you see a `CfnResource`, change the `cfnresource.options.removalPolicy`.
