### ISSUE TITLE
Allow passing EIP configuration into VPC creation

### ISSUE THREAD

**Issue by michaelday008** [aws/aws-cdk#8327]
Allow passing elastic IPs into VPC configuration.

### Use Case

We may at times need to rebuild our internal subnets and VPC configuration, while retaining the external EIPs associated with the NAT gateways.

CDK does not seem to currently have this functionality. I would love to be able to provide EIPs with the subnet configuration when specifying a VPC so I don't have to make the choice between:
A) Go to all our partners who whitelist us and give them new IPs to whitelist
B)Manually create all our VPCs and subnets and NAT gateways so we can keep the same IPs when the internal implementation details change.

### Proposed Solution

Something like this:
```
const vpc = new ec2.Vpc(this, 'VPC', {
  maxAzs: 2,
  natGatewayConfiguration: {
    EIP: [
      {'12.12.12.12/32'},
      {'13.13.13.13/32'}
    ]
  }
});
```

### Other
Related Issues:
https://github.com/aws/aws-cdk/issues/4067
https://github.com/aws/aws-cdk/issues/4705
https://github.com/aws/aws-cdk/issues/8326
---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can write your own `NatGatewayProvider` which creates the NAT gateways with the desired EIP configuration.

**Comment by pramidi11** [comment]
use below in VPC
```
natGatewayProvider: NatProvider.gateway({
        eipAllocationIds: [ id1, id2, id3
]
      }),
```
