### ISSUE TITLE
SNS: Support for overriding subscription

### ISSUE THREAD

**Issue by cheevs** [aws/aws-cdk#8332]
Feature request to add an extendibility method to `TopicBase` with the ability to override the `Subscription` on the method `addSubscription`

### Use Case
The ability to extend `Subscription`. It would be great to use the connivence methods on `Topic`

### Proposed Solution
Proposed solution is to add a method `createSubscription` to the class `TopicBase`
**protected createSubscription(scope: Construct, id: string, props: SubscriptionProps): Subscription** 

```
abstract class TopicBase extends Resource implements ITopic {

...

  /**
   * Subscribe some endpoint to this topic
   */
  public addSubscription(subscription: ITopicSubscription) {
    const subscriptionConfig = subscription.bind(this);

    const scope = subscriptionConfig.subscriberScope || this;
    let id = subscriptionConfig.subscriberId;
    if (Token.isUnresolved(subscriptionConfig.subscriberId)) {
      id = this.nextTokenId(scope);
    }

    // We use the subscriber's id as the construct id. There's no meaning
    // to subscribing the same subscriber twice on the same topic.
    if (scope.node.tryFindChild(id)) {
      throw new Error(`A subscription with id "${id}" already exists under the scope ${scope.node.path}`);
    }

    this.createSubscription(scope, id, {
      topic: this,
      ...subscriptionConfig,
    });
  }

  protected createSubscription(scope: Construct, id: string, props: SubscriptionProps): Subscription {
    return new Subscription(scope, id, props);
  }

...

}
```

Example Code of use case with proposed solution:
```
class MyCustomSubscription extends Subscription { ... }

class MyCustomTopic extends Topic { 
    createSubscription(scope: Construct, id: string, props: SubscriptionProps): Subscription {
        return new MyCustomSubscription(scope, id, props);
    }
}

const topic = new MyCustomTopic(...);
topic.addSubscription(new SqsSubscription(...));
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Hey there. Could you provide more details on the specific use case here? What specific overrides are you trying to implement etc?

**Comment by niamiot** [comment]
> Is it possible to open this issue again ? I have an issue with aws cdk redeploying an sqs subscribtion to an sns on a stack . if ever the sns is deleted ( so the sqs subscription remove) when deploying the sqs subscription , the lost of the subscription is not detected by aws cdk .

I also suggest reopen this issue.
At least, a dirty workaround would be to be able to unsubscribe topic subscription and then subscribe it again. But AFAIK there is no possibility to unsubscribe a topic with CDK.
