### ISSUE TITLE
Enable CloudTrail Insights on Trail

### ISSUE THREAD

**Issue by tofijak** [aws/aws-cdk#8335]
Enable CloudTrail Insights when creating a Trail. 

### Proposed Solution

Could be a property of TrailProps.

```
const trail = new cloudtrail.Trail(this, 'CloudTrail', {
  enableInsights: true
});
```

---

This is a :rocket: Feature Request

**Comment by pgollucci** [comment]
This is not yet in CfnTrailProps which is generated

I have it implemented minus that.

**Comment by pgollucci** [comment]
It is not yet in the roadmap

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/projects/1

**Comment by andrestone** [comment]
AwsCustomResource to the rescue?

**Comment by pgollucci** [comment]
I mean you can always do anything that way, but not in the official release........

**Comment by andrestone** [comment]
> I mean you can always do anything that way, but not in the official release........

I actually meant to suggest AwsCustomResource as a way to implement it in the construct library.

**Comment by tvb** [comment]
@SomayaB The `enableInsights` parameter now exists in CloudFormation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-insightselectors

**Comment by jej2003** [comment]
I have not seen any solutions for addressing this, does anyone have an example of how to enable given CDK doesn't yet support it?

**Comment by watany-dev** [comment]
I want this feature and will work on it.
