### ISSUE TITLE
aws_stepfunctions_tasks.LambdaInvoke not working as intended

### ISSUE THREAD

**Issue by phrasper** [aws/aws-cdk#8337]
aws_stepfunctions_tasks.LambdaInvoke will throw an error, when given the same input lambda arn that does work for RunLambdaTask. However seeing how RunLambdaTask is deprecated, I would prefer to work with LambdaInvoke

Code based on https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions_tasks/LambdaInvoke.html
```
lambda_task = sfn.Task(
  self, "Lambda Name",
  task=sfn_tasks.LambdaInvoke(self, "lambdaInvoke",lambda_function=lambda_.Function.from_function_arn(self,"import-lambda",function_arn="arn:aws:lambda:eu-west-1:accountnumber:function:LambdaName")),
  result_path="$.guid"
)
```
However using the same arn for RunLambdaTask works, and they both require an IFunction as input
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions_tasks/RunLambdaTask.html :
```
lambda_task = sfn.Task(
  self, "Lambda Name",
  task=sfn_tasks.RunLambdaTask(lambda_function=lambda_.Function.from_function_arn(self,"import-lambda",function_arn="arn:aws:lambda:eu-west-1:accountnumber:function:LambdaName")),
  result_path="$.guid"
)
```

Running it using lambdaInvoke i get the following error:
`jsii.errors.JSIIError: props.task.bind is not a function`

### Environment

  - **CLI Version      :1.18.26**
  - **Framework Version:1.41.0**
  - **OS               : Windows 10 x64**
  - **Language         :Python**

### Other

From SO: https://stackoverflow.com/questions/62040102/error-when-calling-lambdainvoke-in-aws-cdk-stepfunction
AWS support looked at it as well, and they ran into the same error and were unable to help me further

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@phrasper - the usage of `LambdaInvoke` is not to embed it inside `sfn.Task` - instead you should directly create it as `sfn.LambdaInvoke(...)` 

i.e.

```python
tasks.LambdaInvoke(self, "Invoke with state input",
    lambda_function=my_lambda
)
```

full example is in the [module overview](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions_tasks.README.html#lambda)

marking this as guidance for now. let me know how it goes!

**Comment by phrasper** [comment]
Ah yes, That does the trick.

I got confused by the documentation, seeing how RunLambdaTask points to LambdaInvoke since it is deprecated and both are tasks, both state: "Invoke a Lambda function as a Task". But RunLambdaTask is imbedded as a task, and LambaInvoke is not. 
Maybe the LambdaInvoke example could be moved to the LambdaInvoke documentation as well, since I missed it by not looking at the overview.
Anyway thanks for the guidance, I'll close the issue.
