### ISSUE TITLE
Amazon CloudWatch Logs Exports propertie not available for class DatabaseCluster

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#8339]
### Use Case

It'll be interesting to add the propertie to be able to enable CloudWatch Logs Export in class DatabaseCluster (construct) : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseCluster.html

### Proposed Solution

Be able to set Cloudwatch logs exports with **EnableCloudwatchLogsExports** prop :
error/audit/general..

### Other

Offer by CFN :
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enablecloudwatchlogsexports

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Closing as duplicate of: #7810
