### ISSUE TITLE
EKS - add resource via URL

### ISSUE THREAD

**Issue by sssd-dev** [aws/aws-cdk#8340]
While adding resources to an EKS cluster, addResource() works fine with manifest definition however, I am not able to apply from a URL. 

### Use Case

Commands such as below avoids duplication of efforts - 
```
kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/flux-helm-release-crd.yaml
```

### Proposed Solution

Will be great if EKS addResource() can also support `URL` prop to allow apply from URLs.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by zxkane** [comment]
You can load the resources from url at synthesis time as workaround.

For example,

```typescript
 const yaml = require('js-yaml');
    const rbacRoles = yaml.safeLoadAll(request('GET', `${albBaseResourceBaseUrl}rbac-role.yaml`).getBody())
      .filter((rbac: any) => { return rbac['kind'] != 'ServiceAccount' });
    const albDeployment = yaml.safeLoad(request('GET', `${albBaseResourceBaseUrl}alb-ingress-controller.yaml`).getBody());

    const albResources = cluster.addResource('aws-alb-ingress-controller', ...rbacRoles, albDeployment);
```

**Comment by eladb** [comment]
I would recommend @zxkane's approach (load the YAML during synthesis).

@zxkane would you be interested in contributing a short example to the aws-eks README which describes this pattern?

**Comment by zxkane** [comment]
> I would recommend @zxkane's approach (load the YAML during synthesis).
> 
> @zxkane would you be interested in contributing a short example to the aws-eks README which describes this pattern?

Sure thing. Will submit a PR for it.

**Comment by zxkane** [comment]
Submitted PR https://github.com/aws/aws-cdk/pull/8802.
