### ISSUE TITLE
Overriding allocateLogicalId not Working Python

### ISSUE THREAD

**Issue by SKIIDK** [aws/aws-cdk#8343]
### The Question

I am trying to override the allocateLogicalId method in order to have an ARN without extraneous hash characters afterwards, but this does not seem to be working in Python. The TypeScript version was described by @skinny85 in #1424 , but when translating to Python, overriding allocate_logical_id does not seem to have an impact on the logical id's or the ARN's made from those id's. 

### Environment

  - **CDK CLI Version:**  1.41.0
  - **Module Version:** 
  - **Node.js Version:**  12.16.3
  - **OS:**  Ubuntu
  - **Language (Version):**  Python 3.6.9

### Other information

Doing `my_resource.node.default_child.override_logical_id('new name')` also doesn't seem to actually modify the names in the CDK and the names continue to have the hash characters following them.

**Comment by SKIIDK** [comment]
I think I was able to get around it by setting the specific name parameters for the construct, but I'm not sure if that's the proper way to approach it.

**Comment by eladb** [comment]
@RomainMuller any idea?

**Comment by RomainMuller** [comment]
@SKIIDK - would you be able to show us the code you're using for your override attempt that is not working? Bonus points if that is stripped to a minimal reproduction 😬

**Comment by SKIIDK** [comment]
I ended up being able to get around it just by specifying the name parameters, but the override methods mentioned in that other thread don't seem the actual way to do it.

**Comment by sarjarapu** [comment]
@RomainMuller here is my sample.

`queue_name = 'my-queue'
        queue = sqs.Queue(self, queue_name,
            visibility_timeout=core.Duration.seconds(300),
            receive_message_wait_time=core.Duration.seconds(20),
            encryption=sqs.QueueEncryption.KMS
        )
        cfnQueue = queue.node.default_child
        cfnQueue.override_logical_id("myqueue")
`

after running `cdk deploy` the queue got created with similar my-cdk-myqueue-XXXXXXXXXXX. 

I am not sure about @SKIIDK recommendation there is no `name` parameter in the Queue constructor.

**Comment by mw-vmaffet** [comment]
I was able to override `allocateLogicalId` in Python. The method is "protected" so its name is `_allocate_logical_id`.

Here is the example code translated:
```python
class TestStack(Stack):

    def _allocate_logical_id(self, cfn_element: CfnElement) -> str:
        return cfn_element.node.id
```

Environment:
 - Python: 3.10.6
 - aws-cdk-lib: 2.37.0
