### ISSUE TITLE
Add DMS endpoint password to support dynamic parameter

### ISSUE THREAD

**Issue by yiantony** [aws/aws-cdk#8349]
Password property in Data Migration Services endpoint doesn't support dynamic parameters. Using a static value will also trigger cfn-lint rule. We have to use the custom resource to assign the password.

### Use Case

We look forward to having more passwords added to support dynamic reference.

### Proposed Solution
Add support for the dynamic parameter like other passwords on this page.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hello @yiantony -

Can you provide details on which dynamic reference you tried to use, an example of the code where you tried to use this and what the corresponding values in the synthesized CloudFormation template look like?

**Comment by nija-at** [comment]
Unfortunately, the `Cfn` classes in the CDK are a direct mapping to CloudFormation. They are autogenerated from the CloudFormation specification and there is additional we do here. We don't have support for higher level constructs in DMS yet. If you would like better support of DMS in the CDK, please upvote here - https://github.com/aws/aws-cdk/issues/6906.

If this feature was announced that it supports dynamic values, but it does not, you will need to report this with cloudformation - https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap. I'm unaware of the `cfn-python-lint` code base either.

**Comment by nija-at** [comment]
See the section 'Resources that support dynamic parameter patterns for Secure Strings ' at the bottom of this page - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings.

It looks like CloudFormation doesn't support dynamic references yet for the `Password` field on DMS.

**Comment by yiantony** [comment]
OK Thanks, I will raise an issue in CloudFormation.

**Comment by yiantony** [comment]
Closing this issue.
