### ISSUE TITLE
ApplicationLoadBalancedFargateService - support redeployment of ECS service with Code Deploy

### ISSUE THREAD

**Issue by kastork** [aws/aws-cdk#8352]
Allow for the construction of CodePipelines that use the `EcsDeployAction` in their deploy stages.

### Use Case

I''d like my CDK stack to create a code pipeline that automates redeployment of FARGATE services after a build stage that pushes a new (tagged) image into ECR.

Specifically, I'd like to make a CDK project that contains a pipeline similar to the one demonstrated here:

 https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-ecs-ecr-codedeploy.html#tutorials-ecs-ecr-codedeploy-cluster

### Proposed Solution

In the linked example, the service definition does not specify the docker image.  Instead, it specifies

```
"deploymentController": {
        "type": "CODE_DEPLOY"
    },
```

This allows code pipeline to re-deploy the service, specifying the new container image to use. 

But the current version of ApplicationLoadBalancedFargateService requires a task definition that identifies the container image, or else and instance of ApplicationLoadBalancedTaskImageOptions that specifies the container.

---

This is a :rocket: Feature Request

**Comment by kastork** [comment]
Well, after further research, this issue might be invalid.

I've been able to get a CDK project to create a pipeline that deploys with the ECR deployer type.

The key things I was missing were:

## 1

`ApplicationLoadBalancedFargateService` sets the container name to "web" unless you change it. You must make this container name match up with whatever your CodeBuild project names the image.  This can be done as follows

(I'm using the Java CDK, writing my code in in Kotlin)

```kotlin
private fun createFargateService(): ApplicationLoadBalancedFargateService {
  val s = ApplicationLoadBalancedFargateService.Builder.create(this, "Service")
      .publicLoadBalancer(true)
      .cluster(cluster)
      // Can't configure without a zone and domain name -- this simply can't be done in gov region.
      // .certificate(Certificate.fromCertificateArn(this, "acm", "arn:aws-us-gov:acm: ... ))
      .taskImageOptions(
          ApplicationLoadBalancedTaskImageOptions.builder()
              .image(ContainerImage.fromEcrRepository(containerRepository))
              .containerPort(8080)
              // Important. This name must match the name in the buildspec's output `imagedefinitions.json`
              // If this is unspecified here, the name will be `web`
              .containerName(containerName)
              .build()
      )
      .build()
  return s
}
```

## 2

The way to grant pull permissions is to use the `grant...` methods on the container repository.

(I'm using the Java CDK, writing my code in in Kotlin)

```kotlin
containerRepository.grantPull(fargateService.taskDefinition.executionRole!!.grantPrincipal)
```

I'm still trying to get the Private Link endpoints figured out because it is too expensive to have NAT gateways simply to permit pulling containers from ECR,  that's a different problem, but I'll put it here for completeness.

### 3 Endpoints (this doesn't work, but I don't yet know what's wrong with it)
(I'm using the Java CDK, writing my code in in Kotlin)

```kotlin
val s3EcrEndpoint = vpc.addGatewayEndpoint("s3ecr", GatewayVpcEndpointOptions.builder()
    .service(GatewayVpcEndpointAwsService.S3)
    .build())

s3EcrEndpoint.addToPolicy(PolicyStatement.Builder.create()
    .resources(listOf("arn:aws-us-gov:s3:::prod-us-gov-west-1-starport-layer-bucket/*"))
    .actions(listOf("s3:GetObject"))
    .effect(Effect.ALLOW)
    .principals(listOf(AnyPrincipal()))
    .build())

val ecrInterfaceEndpoint = vpc.addInterfaceEndpoint(
    "EcrDockerEndpoint",
    InterfaceVpcEndpointOptions.builder()
        .service(InterfaceVpcEndpointAwsService.ECR_DOCKER)
        .build()
)


ecrInterfaceEndpoint.connections.allowDefaultPortFromAnyIpv4()
```

**Comment by skinny85** [comment]
@kastork ,

thanks for opening the issue. Since you've solved the CodePipeline part, can this be closed, and maybe open a new issue about the Endpoints problem?

Thanks,
Adam
