### ISSUE TITLE
SES missing regions

### ISSUE THREAD

**Issue by DrLuke** [aws/aws-cdk#8362]
SES had new regions [added ](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-ses-is-now-available-in-three-additional-aws-regions), but this change isn't yet reflected in CDK.

### Use Case

I would like to deploy SES in `eu-central-1`, but when deploying I get:
```
Template format error: Unrecognized resource types: [AWS::SES::ReceiptRuleSet]
```

### Proposed Solution

Add the missing regions.

### Other

Where are the regions for each service defined? I tried to look it up in the code, but couldn't find it. I would like to try my first PR on this, but don't know where to start.

Additionally, is there a quick workaround to convince CDK to allow using those resources in the region anyway until this feature is released?

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
I don't believe this is supported in CloudFormation yet as I don't see it in the [CloudFormation resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) for [eu-west-1](https://d1mta8qj7i28i2.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json)

I only see `AWS::SES:ConfigurationSet` in there. Can the resource be created in CloudFormation?

**Comment by DrLuke** [comment]
@shivlaks Indeed it can not be created in CloudFormation itself. Well, I guess I'll try to raise the issue with the CF team then?

**Comment by shivlaks** [comment]
@DrLuke it seems like there's already an issue in the [cloudformation roadmap](aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/326). Perhaps you can comment on that issue and add to it to help move it along.

**Comment by peterwoodworth** [comment]
Hey @DrLuke, going through old feature requests. Is this still a relevant issue for you?

**Comment by DrLuke** [comment]
@peterwoodworth I'm not sure if this request is still useful, as the underlying problem lies with cloudformation.

**Comment by peterwoodworth** [comment]
Thanks for getting back to me @DrLuke, and sorry I didn't make myself clear enough in the first comment. I understand this is CFN's issue to solve, I was more wondering if this is something you still need or would like to see, and if so I can try to see what the timeline on this might be. It looks to me like it's still not available in the region you want availability in

Either way, this looks like it's completely out of our hands and CFN seems to at least be tracking this issue so I will close this once I do everything I can (not much) to push this along in CFN or to at least see if it's on the timeline for the near future.

**Comment by DrLuke** [comment]
@peterwoodworth

>Either way, this looks like it's completely out of our hands and CFN seems to at least be tracking this issue so I will close this once I do everything I can (not much) to push this along in CFN or to at least see if it's on the timeline for the near future.

Sounds good to me. Nothing to do but wait here. Thank you very much!

**Comment by khaledev** [comment]
Hello,
I had a similar issue here using aws-cdk-lib.aws_ses module on eu-west-3.
Error: `Unrecognized resource types: [AWS::SES::ReceiptRule, AWS::SES::ReceiptRuleSet]`
Any news on integrating support for new regions for SES using CDK?
Thank you!

**Comment by peterwoodworth** [comment]
Support in each region is up to [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). Check out the [CFN coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) to see if they plan to address this soon.

There's nothing CDK can do about this, so I'm going to close the issue. Feel free to ping me with any additional questions

**Comment by shivlaks** [comment]
per the [linked issue comment](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/326#issuecomment-1048727007) in the CloudFormation coverage roadmap, support for SES resources is available in all regions where SES is there as of Feb 23, 2022.
