### ISSUE TITLE
cdk destroy from command line gets confused when used with --app

### ISSUE THREAD

**Issue by tbartley** [aws/aws-cdk#8365]
`cdk destroy` reports usage errors when used with --app

### Reproduction Steps

Run `cdk -a "some app command" destroy "*" --force` 

In my case `"some app command"` is like `"yarn ts-node path/to/cdk-app.ts"`

Also tried:
 `cdk -a "some app command" destroy --force "*"`
 `cdk -a "some app command" --force destroy "*"`

### Error Log

Usage: cdk -a <cdk-app> COMMAND

### Environment

  - **CLI Version      :** 1.42.1
  - **Framework Version:**
  - **Node.js Version:** v13.8.0 
  - **OS               :** MacOS and Linux
  - **Language (Version):** TypeScript (3.8.3/3.9.3) 

### Other

Used to work though I can't tell you what version of CDK we had when this was working .

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@tbartley - I'm currently testing this with v1.44.0 and I'm not running into any usage errors. Can you share the error you're running into? That might help with a repro. 

In my case I'm using `yarn ts-node bin/blah.ts` and `npx ts-node bin/blah.ts` with and without the force flag and it succeeded in all scenarios.

Are you still running into this issue. What am I missing?

**Comment by tbartley** [comment]
Thanks for looking in to this @shivlaks . Can you please post the full command you're using so I can see exactly where you specify `--app` etc. I'll try with 1.44.0 tomorrow (my morning).

The error I get is just `Usage: cdk -a COMMAND`

**Comment by shivlaks** [comment]
@tbartley  - apologies, i totally missed your response. I was just using `cdk -a yarn ts-node bin.blah.ts destroy '*'`

**Comment by tbartley** [comment]
Thanks for looking in to this. I think I had some crossover between cdk.json and command line that may have caused confusion. I didn't realize until recently the project I was using had an app specification in a cdk.json file as well me trying to specify app on the command line. I'm happy to have this closed though there possibly is still a minor bug with both command line options and cdk.json file is in play?

**Comment by shivlaks** [comment]
@tbartley I'm resolving this issue for now. feel free to reopen. We can revisit if it's more of a pain point than I'm currently reading it to be. 

settings should be resolved when they are merged (merged settings can be inspected by running your cdk command with `-v`). Settings in `cdk.json` take precedence over settings in `~/.cdk.json`.
