### ISSUE TITLE
hostedZoneNameServers can be undefined in PublicHostedZone

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#8373]
### Reproduction Steps

Using _Route53_ > **PublicHostedZone.hostedZoneNameServers**.

Unfortunatly, I can't export these NS as a **CfnOutput** because **hostedZoneNameServers** can be undifiened (why ? I'm using PublicHostedZone) :
`Type 'undefined' is not assignable to type 'string'`

And I have to set NS as records in another account (who drive the Main Public HostedZone).

So, is it a bug for the PublicHostedZone ?
And of course, can't write the output in a file (with CDK _--outputs-file_) to use it in my other Account.

So, what can I do ?

Thanks in advance.

### Environment

  - **CLI Version      : CDK 1.42.1 (build a4797b4)**
  - **Framework Version: 6.14.5**
  - **Node.js Version: v12.15.0** 
  - **OS               : Linux**
  - **Language (Version): TypeScript** 

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@Cloudrage is your hostedZone imported from another stack?

it can be undefined if it's imported from another stack as per the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.PublicHostedZone.html#hostedzonenameservers)

> This attribute will be undefined for private hosted zones or hosted zones imported from another stack.

**Comment by Cloudrage** [comment]
Hello @shivlaks ,

Yes I've seen that but I just can't write/execute my code even if my hostedZone is created or not in the same account; Like I've said : **hostedZoneNameServers** can be undefined (optional), this is the pb : 
![image](https://user-images.githubusercontent.com/30436750/83859922-e6b99180-a71e-11ea-9527-5ef967895c07.png)

And at the end to answer you, no, my Hosted Zone is in the same account.
I'm creating a PublicHostedZone, so why that prop is optional then ?

**Comment by Cloudrage** [comment]
Waiting for a solution about that, I've made a workaround with a CustomResource doing a **getHostedZone**.

After that I've exported **NameServers** with _CfnOutput_ in the CFN Stack.
The best way now is the release of [that Feature Request](https://github.com/aws/aws-cdk/issues/7484) to be able to retrieve them from my other account.

Waiting for that, I'm using **CDK --outputs-file** alternative (dirty for me).

**Comment by shivlaks** [comment]
`PublicHostedZone` implements [`IHostedZone`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.IHostedZone.html) which represents the properties for all hosted zones. The reason the property may be undefined is because any hosted zone should be usable in an API that accepts IHostedZone.

Can you share the code that you're trying to write and use. Assuming it was defined, you're still attempting to assign a list of strings to the `value` property to your output which only allows type `string`.

something like the following is what you'd want to do - sketch

```ts
const hostedZone = new r53.HostedZone(this, 'my-hosted-zone', {
  zoneName: 'www.shivexample.com',
});

if (hostedZone.hostedZoneNameServers) {
  new cdk.CfnOutput(this, 'MyOutput', {
    value: Fn.join(', ', hostedZone.hostedZoneNameServers),
  });
}
```

let me know how it goes!

**Comment by Cloudrage** [comment]
Yes you're right !
It's working with your proposal; many thanks.

So, now to be perfect, we need to have the capability to get Cfn Ouputs between accounts; because actually, I've to get the output from a file in the Repo. So it means that the "Builder" (another one than me) have to launch CDK with the correct option (that implies that the entire code can't be valid until prerequisites resources & outputs are created. So, some snippets have to be comment...).
