### ISSUE TITLE
Unable to set targetPipelineVersion dynamically using CfnWebhook

### ISSUE THREAD

**Issue by froilan** [aws/aws-cdk#8377]
### The Question
I'm trying to setup a github source webhook using the CfnWebhook class.

However, the builder only allows a Number on the targetPipelineVersion field and pipeline.getPipelineVersion() returns a string.

I need this to be sourced dynamically from the Pipeline object.

```java
CfnWebhook.Builder.create(this, "githubWebhook")
                //other properties...
                .targetPipelineVersion(pipeline.getPipelineVersion())
                .build();
```
Are there any alternatives to go around this?

### Environment

  - **CDK CLI Version:** 0.42.1
  - **Module Version:** 0.42.1
  - **Node.js Version:** 6.14.5
  - **OS:** Ubuntu 20
  - **Language (Version):** Java 11

**Comment by fulcrum-stelios-papadopoulos** [comment]
@froilan how did you go around this?

**Comment by tractorcow** [comment]
Apparently the answer is just to put a literal `1` as this is what cdk does internally.

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-codepipeline-actions/lib/github/source-action.ts#L145
