### ISSUE TITLE
java: Maven plugin and archetype for the CDK

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#840]
@arun-gupta proposed that we will write a maven plugin for the CDK that will make the CDK java experience more idiomatic:

- [ ] Maven archetype for cdk projects instead of `cdk init -l java`
- [ ] Maven goals for the various cdk operations such as synthesis, deploy, diff
- [ ] Remove the need for `cdk.json`, `app.sh`, etc.
- [ ] Don't require to install node and the toolkit (we can do that by bundling the toolkit via the likes of [pkg](https://github.com/zeit/pkg) and then bundle into the Maven plugin for all architectures

**Comment by arun-gupta** [comment]
@eladb Gradle is pretty cool but Maven would capture significant part of the developer community IMHO. So for prioritization, start with Maven. If the code is modular then Gradle plugin would be just another wapper on top of the base code.

**Comment by digitalsanctum** [comment]
+1 for Gradle as well as Kotlin for language. For orgs that are standardized on Gradle this is an impediment. Even better would be support for Gradle Kotlin DSL. I could see cli args being something like: 

`cdk init --language=java --build-tool=gradle dsl=kotlin`

**Comment by digitalsanctum** [comment]
I created #1293 to propose adding a Gradle plugin as well

**Comment by kavukcutolga** [comment]
Hi All,

Do you know of any initiative around a maven plugin for cdk commands? As you indicated at the beginning, having npm installed in java developer's machine or Jenkins machines is not a common approach. So we need a maven plugin to generate cloud formation template during build and we will publish generated template to s3 in our pipeline. 

I know there is an option to do it via cdk command but we already have an existing codedeploy pipeline /flow triggered by s3 event. So we want to keep the same flow

**Comment by RoKish** [comment]
Hi guys,

I've created a [aws-cdk-maven-plugin](https://github.com/LinguaRobot/aws-cdk-maven-plugin) which solves some the issues described above. It eliminates the need of having Node.js and CDK toolkit installed on the machine. Please take a look and feel free to contribute.

**Comment by eladb** [comment]
> Hi guys,
> 
> 
> 
> I've created a [aws-cdk-maven-plugin](https://github.com/LinguaRobot/aws-cdk-maven-plugin) which solves some the issues described above. It eliminates the need of having Node.js and CDK toolkit installed on the machine. Please take a look and feel free to contribute. 
> 
> 

Looks great! Let’s add this to https://github.com/eladb/awesome-cdk 

Wondering if we should also change our java unit template to use this

**Comment by RoKish** [comment]
@eladb Thanks!

I wouldn't update the java init template to use the plugin as it's not that stable. Besides it, you guys make a lot of changes in CDK and if the changes are related to CDK CLI, the plugin needs to be updated as well. 

It could be added as an additional init template (i.e. `app-maven-plugin`), but in that case, the template will make sense only with `--language=java`.

**Comment by eladb** [comment]
I love the idea of an additional template. Would you be interested in submitting a PR for that?

**Comment by RoKish** [comment]
Sure, I'll create a PR.
