### ISSUE TITLE
IAM/PolicyDocument does not inline props

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#8400]
This is a 📕 documentation issue

link to reference doc page: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PolicyDocument.html

Most classes in the CDK have their props inlined. PolicyDocument doesn't, which was a little jarring. I would expect the table from https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PolicyDocumentProps.html to be inlined into https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PolicyDocument.html

I can also send a PR if that's okay with you.

**Comment by rix0rrr** [comment]
Thanks for the notification.

You can't send a PR though, because this behavior comes from a documentation generator you don't have access to.
