### ISSUE TITLE
CodeBuild "LINUX_GPU_CONTAINER" environment type

### ISSUE THREAD

**Issue by ajaykarpur** [aws/aws-cdk#8408]
The [CodeBuild documentation](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html) indicates that there is support for builds running in a GPU container with the environment type `LINUX_GPU_CONTAINER`. Support for this should be added to the CDK.

### Use Case

Some of our tests require a GPU environment to run. Currently, we accomplish this using Amazon Deep Learning AMIs on an EC2 instance, but the DLAMIs are out of date and don't support Python 3.7, which we now need to run our tests. We thought that we'd be able to switch to CodeBuild for these GPU tests, but it looks like the GPU environment type isn't yet supported by the CDK.

### Proposed Solution

Analogous to eg. `codebuild.ComputeType.LARGE`, there could be a value like `codebuild.EnvironmentType.LINUX_GPU_CONTAINER`.

### Other

Links for context:
- https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html
- https://aws.amazon.com/about-aws/whats-new/2019/11/aws-codebuild-adds-support-for-arm--gpu--and-x-large-compute-typ/

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @ajaykarpur ,

thanks for opening the issue. The problem here is not adding something to `ComputeType`, but adding a new `Image` class, similarly like we did for `ARM_CONTAINER` in #5541.

Is there any chance you could submit us a PR with this change?

Thanks,
Adam
