### ISSUE TITLE
ComputeEnvironment computeResourcesTags generate incorrect definition

### ISSUE THREAD

**Issue by damonmaria** [aws/aws-cdk#8416]
Trying to use `computeResourcesTags` in an aws-batch `ComputeEnvironment` results in the following error when deploying:
```
Parameter validation failed: Invalid type for parameter computeResources.tags.props, value: {}, type: <type 'dict'>, valid types: <type 'basestring'>
```

### Reproduction Steps

```typescript
          new ComputeEnvironment(this, `computeEnvSpot`, {
            computeResources: {
              allocationStrategy: AllocationStrategy.BEST_FIT, // Only BEST_FIT will create SpotFleetRole for us
              desiredvCpus: 0,
              instanceRole: modelEtlInstanceProfile.ref, // TODO: let it be auto created
              instanceTypes: its.map((it) => new InstanceType(it)),
              spotFleetRole: amazonEC2SpotFleetRole,
              computeResourcesTags: new Tag('key', 'value'),
              type: ComputeResourceType.SPOT,
              vpc,
            },
```

### Error Log

```
Parameter validation failed: Invalid type for parameter computeResources.tags.props, value: {}, type: <type 'dict'>, valid types: <type 'basestring'>
```

### Environment

  - **CLI Version      : 1.44.0**
  - **Framework Version: 1.44.0**
  - **Node.js Version: v12.18.0** 
  - **OS               : MacOS 10.15.4**
  - **Language (Version): Typescript 3.9.5** 

### Other

The tags in the resulting template looks like this, which is obvioously wrong:
```json
          "Tags": {
            "key": "key",
            "props": {},
            "defaultPriority": 100,
            "value": "value"
          },
```

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @damonmaria - Thanks for reporting this!

This is indeed a (rather embarrassing) bug. Filing it.

The actual structure seems to be a simple dictionary:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html#cfn-batch-computeenvironment-computeresources-tags

In the meantime, I can offer a workaround using an [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html).

```typescript
const computeEnvironment = ...
const child = computeEnvironment.node.defaultChild as batch.CfnComputeEnvironment;
(child.computeResources as any).tags = {
  'key': 'value'
}
```

Thanks!
