### ISSUE TITLE
efs.Filesystem to expose the subnet list of the mount targets

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#8417]
efs.Filesystem resource now creates multiple `CfnMountTargets` under the hood but doesn't expose them to the surface. The EFS client will encounter errors if the mount targets are not ready. Would be great if the `efs.Filesystem` can epose those resources so the efs clients can `addDependency` on them.

https://github.com/aws/aws-cdk/blob/f44ae607670bccee21dfd390effa7d0e8701efd4/packages/%40aws-cdk/aws-efs/lib/efs-file-system.ts#L257-L265

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Why is 

```ts
efsClient.node.addDependency(efs);
```

Not good enough?

**Comment by pahud** [comment]
Sorry. I am closing this issue for now.
