### ISSUE TITLE
Add native reference documentation like javadocs, typedoc, etc

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#842]
We should include "native" reference documentation for each language. Some users would prefer to use javadocs instead of our language-agnostics sphinx documentation.

Proposed by @arun-gupta

**Comment by eladb** [comment]
@jmhummel generated a typedoc version: http://dr6je23q67zj.s3-website-us-west-2.amazonaws.com

**Comment by NGL321** [comment]
@rix0rrr Is this separate from current implementation?

**Comment by rix0rrr** [comment]
No, I think this is that.
