### ISSUE TITLE
aws cdk --profile  use toolkit set default_account error

### ISSUE THREAD

**Issue by MarryYou** [aws/aws-cdk#8420]
Ec2 Instance IAM in CDK environment does not have any permissions, all permissions come from AWS CLI credentials, and credentials are obtained through credential_process. How do I make it applicable in CDK

### Reproduction Steps

such as: .aws/config profile 
[profile staging]
region=ap-northeast-1
output=json
credential_process = "/home/ubuntu/staging.sh" "--username staging"

but found this error :
this is my cmd code 
![image](https://user-images.githubusercontent.com/17715691/83963275-422e7f80-a8d7-11ea-9888-fc5ca969fc10.png)
![image](https://user-images.githubusercontent.com/17715691/83963306-946fa080-a8d7-11ea-875c-cc0130dec2ae.png)

### Error Log

error info 
![image](https://user-images.githubusercontent.com/17715691/83963317-b406c900-a8d7-11ea-955e-553db1a0364d.png)

### Environment

  - **CLI Version      :*1.44.0*
  - **Framework Version:**
  - **Node.js Version:*v10.21.0* 
  - **OS               :*ubuntu *
  - **Language (Version):*python(3.7)* 

### Other

The account of ec2 instance is not the account of profile specified by me. How can I change it to make CDK run successfully?

### Implement way
use python subprocess command line

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@MarryYou - have you already looked through #1656
Are you using `credential_source`? A workaround is suggested for getting around that as it's not currently supported.

**Comment by MarryYou** [comment]
@shivlaks Hi shivlaks  thank you for your reply. According to the issue you provided, I changed the way of using the certificate and now it can work normally.I suggest that assme Role be added to the credential usage of CDK, which is a common usage scenario.

**Comment by shivlaks** [comment]
We do support assuming a role but I think I'll make some updates to our documentation and add some better examples. 
Resolving this issue for now. Feel free to reopen if you have any outstanding questions or concerns.
