### ISSUE TITLE
[Question] How to allow EC2 instance to launch ECS task?

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#8422]
### The Question

What is the best way to allow an EC2 instance role to launch specific ECS task?

### Other information

I’m trying to allow an EC2 instance role to run specific ECS task definition, but it doesn’t like ARN of the task definition with `:version` suffix attached.

i.e. `arn:aws:ecs:us-west-2:1234567890:task-definition/FargateRunnerStackFargateGitlabRunnerTaskDefinition4C03774D:1`

![image](https://user-images.githubusercontent.com/31543/83975923-d8e94500-a8b3-11ea-9cab-576781c67dea.png)

```ts
// cluster, task definition, container, ASG created above
...

 asg.role.attachInlinePolicy(new iam.Policy(this, "ECSPermissionsInlinePolicy", {
    statements: [
        new iam.PolicyStatement({
            effect: iam.Effect.ALLOW,
            actions: [
                "ecs:RunTask",
                "ecs:StopTask",
            ],
            sid: "ExecuteECSTasks",

            // doesn't work because it contains `:version` suffix which prompts CFN error (see below)
            resources: [ taskDefinition.taskDefinitionArn ],  

            // works but it's hardcoded and without `:version` suffix
            // resources: [ "arn:aws:ecs:us-west-2:1234567890:task-definition/FargateRunnerStackFargateGitlabRunnerTaskDefinition4C03774D" ],
        })
    ]
}));
```

```bash
Error:
starting new Fargate task: running new task on Fargate: error starting AWS Fargate Task: AccessDeniedException: 
User: arn:aws:sts::1234567890:assumed-role/FargateRunnerStack-FargateGitlabRunnerASGInstanceR-14X1BOT8XT292/i-0347e674e37c2a6a0 is not authorized to perform: 
ecs:RunTask on resource: arn:aws:ecs:us-west-2:1234567890:task-definition/FargateRunnerStackFargateGitlabRunnerTaskDefinition4C03774D”
```

If I hardcode it without `:version` suffix everything works just fine. It looks like CFN doesn't like ECS' different ARN format.

I've also tried to remove `:version` suffix, but `taskDefinition.taskDefinitionArn.split(":")[0]` doesn't return desired outcome. Attaching `AmazonECS_FullAccess` managed policy is too permissive. Same goes for `resources: [ "*"]`.

Suggestions on how to accomplish this are greatly appreciated. 👍 

### Environment

  - **CDK CLI Version:** 1.44.0 (build 1cd832b)
  - **Node.js Version:** v14.4.0
  - **OS:** OSX Mojave
  - **Language (Version):** TypeScript (3.8.3)

cc @pahud @skinny85 @rix0rrr

**Comment by pahud** [comment]
Hi @robertd 

Happy to help. But I think we should post general questions on [StackOverflow](https://stackoverflow.com/questions/tagged/aws-cdk) or [Gitter](https://gitter.im/awslabs/aws-cdk). Feel free to @ me on Gitter if the question remains unanswered.

**Comment by robertd** [comment]
@pahud I did on Gitter on May 19th, but I didn't get an answer. I'll reach out to you on Gitter.

**Comment by robertd** [comment]
Big thanks to @pahud 

Solution:

![image](https://user-images.githubusercontent.com/31543/84049855-2f18bf80-a96a-11ea-9b22-f6aeb194ae22.png)
