### ISSUE TITLE
route53: cfn-lint error Property ********/RecordSet/Properties/TTL should be of type Long

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#8431]
From #8269:

* **E3012 Error** is hit when using the _TTL_ property of the  **ARecord** Construct. Since that property is implemented by the parent class **RecordSet** that issue would extend to any Construct that extends RecordSet.
> This affects the **@aws-cdk/route53** module

The ttl is given as a `Duration` when instantiating the construct and later processed and transformed to a `string` value in the `RecordSet` constructor as shown below:

```typescript
export class RecordSet extends Resource implements IRecordSet {
  public readonly domainName: string;

  constructor(scope: Construct, id: string, props: RecordSetProps) {
    super(scope, id);

    const ttl = props.target.aliasTarget ? undefined : ((props.ttl && props.ttl.toSeconds()) || 1800).toString();
```
which makes it then after be rendered in the template as a `string`:

```
...,
logical-id: {
    Properties: {
        ...,
        TTL: "60"
    }
```
while `cfn-lint` enforces it to be a `long`:
```console
E3012 Property ********/RecordSet/Properties/TTL should be of type Long
```

**Comment by sagarthoratcg** [comment]
Hello Team,

Any updates on this issue?

**Comment by namankumar2** [comment]
Hello, do we have a workaround/fix for this issue yet?
