### ISSUE TITLE
Add subnetSelection for both the LoadBalancer and Service in ecs-patterns constructs

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#8433]
I understand that there is a possibility to "bring your own" loadbalancer for the ecs-patterns, but I think it would really help if you can just select the subnets for the loadbalancer and the services that are being created as part of this pattern.

### Use Case

To be able to use these constructs in settings where there are multiple private and public subnets.

### Proposed Solution

Include 2 additional options one for the loadbalancer vpcSubnets and one for the service vpcSubnets.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
This should have been fixed by https://github.com/aws/aws-cdk/pull/11823!
