### ISSUE TITLE
Programatically expose the output of CDK list

### ISSUE THREAD

**Issue by benwainwright** [aws/aws-cdk#8436]
Currently, I can get a list of stacks that will be generated by my project **in the order they should be deployed** (this is important; see below) by running the command `cdk list`

It would be useful if the output from this command could be exposed as an api in a way that doesn't require full synthesis of the templates under the hood.

### Use Case
On my team in the BBC, we are currently using the CDK to generate templates for 17 CodeBuild projects associated with various different Github repositories, along with three other templates that the others all depend on. Typically in the BBC, we deploy CloudFormation stacks via an internal service that acts as an intermediary between the developer or CI service and the AWS API.

When we first started developing the project that generates the CodeBuild templates, none of them had any dependencies on each other, and so a deployment solution was written that first runs `cdk synth` to generate the templates, then deploys the templates in filesystem order.

As our use case became more complicated, we started introducing dependencies between templates and we learned that, under the hood, this resulted in imports/exports between templates being *implicitly generated*

This obviously left us with the problem that we had no guarantee that we would deploy the templates in the correct order, and we quickly ran into deployment failures. We reached out to our AWS account team about this and after a quick call, we got a response identifying that we should use the output of `cdk list`, since this not only lists the stacks to be generated, but does so in the **order they should be deployed**.

While this solves our immediate problem (and so this is not a *high* priority issue for us), it would be really useful to be able to do this programmatically without having to shell out. This would make our tests much cleaner/simpler, and it is also worth noting that `cdk list` took approx 4 seconds when I ran it which seems surprisingly slow given what it does.

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@benwainwright - I believe we shoudl track the use case in #601 
I'd like to collect and consolidate the use cases in a single point. This is the most desired feature in the tools space and will likely need an RFC before we get to implementing a solution.

That's an interesting point about cdk list taking 4 seconds. Can you help me understand the layout and organization of your infrastructure a bit better? I think that's worth following up on to see if there are optimizations we can make.
