### ISSUE TITLE
AWS Solutions Konstruk modules namespace change

### ISSUE THREAD

**Issue by hnishar** [aws/aws-cdk#8438]
AWS Solutions Konstruk has been renamed to AWS Solutions Constructs for GA release. Hence the NPM namespace/scope will change from @aws-solutions-konstruk/* to @aws-solutions-constructs/*

### Use Case
Currently AWS::CDK::Metadata is reporting the metadata related to (@aws-solutions-konstruk/*) usage, it will require an update to also include (@aws-solutions-constructs/*) usage going forward, since that will be the new namespace used for NPM publishing.

### Proposed Solution

Submit the PR request against the following code & documentation

1 – Code: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/private/runtime-info.ts#L6

Add (@aws-solutions-constructs/*) to the list of WHITELIST_SCOPES for Metadata version reporting

2 - Documentation: https://github.com/awsdocs/aws-cdk-guide/blob/master/doc_source/tools.md#version-reporting

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/8454
