### ISSUE TITLE
Thanks for bringing this to our attention! Definitely let us know if you're willing to work on the PR; otherwise someone from our team will pick it up.

### ISSUE THREAD

**Issue by 1z2x3c4v5b6n7m8** [aws/aws-cdk#8452]
Thanks for bringing this to our attention! Definitely let us know if you're willing to work on the PR; otherwise someone from our team will pick it up.

_Originally posted by @bvtujo in https://github.com/aws/aws-cdk/issues/7366#issuecomment-615389291_

**Comment by 1z2x3c4v5b6n7m8** [comment]
> Thanks for bringing this to our attention! Definitely let us know if you're willing to work on the PR; otherwise someone from our team will pick it up.
> 
> _Originally posted by @bvtujo in [#7366 (comment)](https://github.com/aws/aws-cdk/issues/7366#issuecomment-615389291)_
#8441

**Comment by SomayaB** [comment]
Hi @1z2x3c4v5b6n7m8, I'm not sure what the ask is here? Are you saying you are going to pick up this PR?
