### ISSUE TITLE
API Gateway using HttpIntegration proxy on root creates invalid configuration

### ISSUE THREAD

**Issue by TikiTDO** [aws/aws-cdk#8453]
When adding a API Gateway HttpIntegration as a proxy for an s3 hosted website to the root of an API, the generated API creates a MOCK ANY method, which then fails to return a valid result when accessing the root URL.

Note: The use case is for development, in order to speed up deploy times, which can be upwards of 10 minutes when putting a CloudFront resources in front of the s3 bucket.

### Reproduction Steps

The following configuration will work correctly when I access `example.com/file` or `example.com/path/file`, but will fail when I try to access `example.com`.

```ts
// Typescript
      const exampleApi = new apigateway.RestApi(
        this,
        "exampeApi",
        {
          domainName: {
            certificate: exampleCertificate,
            domainName: "example.com",
          },
          endpointConfiguration: {
            types: [apigateway.EndpointType.REGIONAL],
          },
          restApiName: "Example API",
        },
      )

      exampleApi.root.addProxy({
        anyMethod: true,
        defaultIntegration: new apigateway.HttpIntegration(
          `${appBucket.bucketWebsiteUrl}/{proxy}`,
          {
            httpMethod: "GET",
            options: {
              requestParameters: {
                "integration.request.path.proxy": "method.request.path.proxy",
              },
            },
            proxy: true,
          },
        ),
        defaultMethodOptions: {
          methodResponses: [{ statusCode: "200" }],
          requestParameters: {
            "method.request.path.proxy": true,
          },
        },
      })
```

The following code works around the issue:

```ts
// Typescript
      const exampleApi = new apigateway.RestApi(
        this,
        "exampleApi",
        {
          domainName: {
            certificate: exampleCertificate,
            domainName: "example.com",
          },
          endpointConfiguration: {
            types: [apigateway.EndpointType.REGIONAL],
          },
          restApiName: "Example API",
        },
      )


      const proxyIntegration = new apigateway.HttpIntegration(
        `${appBucket.bucketWebsiteUrl}/{proxy}`,
        {
          httpMethod: "GET",
          options: {
            requestParameters: {
              "integration.request.path.proxy": "method.request.path.proxy",
            },
          },
          proxy: true,
        },
      )

      const proxyMethodOptions = {
        methodResponses: [{ statusCode: "200" }],
        requestParameters: {
          "method.request.path.proxy": true,
        },
      }

      const proxyResource = exampleApi.root.addProxy({
        anyMethod: false,
        defaultIntegration: proxyIntegration,
        defaultMethodOptions: proxyMethodOptions,
      })
      proxyResource.addMethod("ANY", proxyIntegration, proxyMethodOptions)

```

### Error Log

When accessing `example.com` the api returns a server error, and cloudwatch shows:

```
Execution failed due to configuration error: statusCode should be an integer which defined in request template
```

because it tries to access a MOCK method with no integration or method configuration.

### Environment

  - **CLI Version      :** 1.44.0
  - **Framework Version:**  1.44.0
  - **Node.js Version:**  v12.18.0
  - **OS               :** Arch Linux
  - **Language (Version):** TypeScript (3.9.2)

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
From some initial investigation, it looks like the [`MethodResponses` section](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-methodresponses) is missing in the `AWS::ApiGateway::Method` when [`anyMethod` property in `ProxyResourceOptions`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.Resource.html#add-wbr-proxyoptions) is set, causing this error.
