### ISSUE TITLE
s3-deployment uses wrong metadata prefix

### ISSUE THREAD

**Issue by magJ** [aws/aws-cdk#8459]
s3-deployment adds the prefix `x-amzn-meta` to user metadata, the correct prefix is `x-amz-meta`(no `n`).  

This results in metadata being set with a double prefix, see screenshot:
![image](https://user-images.githubusercontent.com/1804354/84221919-a3de2c00-ab19-11ea-8e29-6a68335fcbd7.png)

### Reproduction Steps

Use s3-deployment to upload a file with user defined metadata, inspect the file metadata to see double prefix.

### Environment

  - **CLI Version      :`1.44.0`**
  - **Framework Version:`1.44.0`**
  - **Node.js Version:`v13.8.0`** 
  - **OS               : macOS**
  - **Language (Version): Typescript**

## Other

The s3-deployment lambda also annoyingly formats user metadata keys to lowercase, S3 supports varied case keys, so this is an unnecessarily imposed limitation that should be removed.

--- 

This is :bug: Bug Report

**Comment by ayush987goyal** [comment]
@magJ Regarding
> The s3-deployment lambda also annoyingly formats user metadata keys to lowercase, S3 supports varied case keys, so this is an unnecessarily imposed limitation that should be removed.

This is what I found in [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html):
> User-defined metadata is a set of key-value pairs. Amazon S3 stores user-defined metadata keys in lowercase.

Not sure if this is a documentation issue. I will leave the implementation of lowercasing as is.
