### ISSUE TITLE
docs: make cloudformation in sidebar expandable

### ISSUE THREAD

**Issue by jmhummel** [aws/aws-cdk#846]
It would be great if the "cloudformation" section within the Reference section in the sidebar was expandable, especially for services which don't have L2 resources at the moment. 

Without a TOC or list, it can be difficult to find classes within long cloudformation sections in the reference.

It could also be useful to group the L2 constructs within a collapsible section as well.

**Comment by SomayaB** [comment]
Closing because outdated.
