### ISSUE TITLE
[ecs-patterns] ApplicationLoadBalancerProps "name" doesnt work for ApplicationMultipleTargetGroups service pattern

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#8464]
when supplying **name** attribute on ApplicationLoadBalancerProps while creating new ecspatterns.ApplicationMultipleTargetGroupsEc2Service(..), the **name** is not reflected in the created LoadBalancer.

### Reproduction Steps

Create a MultiTargetGroupLoadBalancer and supply a ApplicationLoadBalancerConfig like so:

```
new ecspatterns.ApplicationMultipleTargetGroupsEc2Service(this, "someResourceId", {
  ...
  loadBalancers: {
    ... 
    name: "MyLoadBalancerName"
  }
});

```

**MyLoadBalancerName** is not set for the created LB.

### Proposed Solution

set **loadBalancerName** attribute to **application-multiple-target-groups-service-base.ts** (Line 517+)

```
  private createLoadBalancer(name: string, publicLoadBalancer?: boolean): ApplicationLoadBalancer {
    const internetFacing = publicLoadBalancer !== undefined ? publicLoadBalancer : true;
    const lbProps = {
      loadBalancerName: name,
      vpc: this.cluster.vpc,
      internetFacing,
    };
    
   return new ApplicationLoadBalancer(this, name, lbProps);
  }

```

I would do it myself but your current master fails on:
docker build -t aws-cdk .

So i cant fire up a dev environment currently. 

### Environment

  - **Framework Version: 1.44.0 (build 1cd832b)**

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
Hi @logemann! Would you mind submitting your proposed changes as a PR? Thanks!

**Comment by logemann** [comment]
I can do it but i cant write tests for it.

**Comment by SoManyHs** [comment]
The fix for this was reverted https://github.com/aws/aws-cdk/commit/092373a818f4a9524953e5095a185709e2dcc6a8
Re-opening to keep track of this issue.
