### ISSUE TITLE
Cyrillic email domain in Cognito UserPool does not work

### ISSUE THREAD

**Issue by oliora** [aws/aws-cdk#8473]
It's not possible to use Cyrillic domain name  like `домен.рф` in Cognito UserPool email settings. 

### Reproduction Steps

```typescript
const cyrillic_domain = 'пример.рф';

export class SomeInfraStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    cognito.UserPool(this, 'userpool', {
      userPoolName: 'someuserpool',
      emailSettings: { from: 'noreply@' + cyrillic_domain }
  });
});
```

### Error Log

```
 3/4 | 4:06:29 PM | CREATE_FAILED        | AWS::Cognito::UserPool | userpool (userpool0AC4AA96) Provided From email address is invalid (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 84fa010b-8029-42f4-bc13-07d5273f1322)
```

The generated CloudFormation template (as seen in AWS Console) has question marks instead of Cyrillic characters.

### Environment

  - **CLI Version      : 1.45.0 (build 0cfab15)**
  - **Node.js Version: v13.8.0**
  - **OS               : macOS Mojave 10.14.6 (18G4032)**
  - **Language (Version): TypeScript**

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Can you paste the section with `AWS::Cognito::UserPool` from the CloudFormation template here?

**Comment by oliora** [comment]
Sorry, @nija-at but I don't have it anymore. But that domain parameter was simply `??????.??` instead of `пример.рф` so each Cyrillic character has been replaced with question mark.

**Comment by nija-at** [comment]
This worked just fine for me. Here's the generated CloudFormation template -

```
< -- snip -- >
"myuserpool01998219": {
  "Type": "AWS::Cognito::UserPool",
  "Properties": {
    "EmailConfiguration": {
      "From": "noreply@myawesomeapp.com",
      "ReplyToEmailAddress": "support@домен.рф"
    },
< -- snip -- >
```

You'll need to check the encoding settings in your environment or provide more details.

**Comment by oliora** [comment]
Is this what you see locally or in cloud formation console? The question marks I’ve seen are on CF console stack’s template tab

**Comment by nija-at** [comment]
This is what is shown locally on CF template. It's possible that the the console web UI mangles the characters but is actually correctly set up.

Can you check whether an email sent via this user pool is actually correctly set up?

**Comment by oliora** [comment]
No it was not. As you can see in original post, there was `CREATE_FAILED` CloudFormation event.

**Comment by rix0rrr** [comment]
I'm going to gander a guess and say this is where the confusion happened:

> The generated CloudFormation template (as seen in AWS Console) has question marks instead of Cyrillic characters.

I'm guessing that Niranjan saw that remark, missed the error message, and thought the template had deployed successfully.

@nija-at as a reminder of one of those niggling CloudFormation gotchas, if a stack fails to create (so not fails to *update*, but fails to  *create*, on the first attempt) then it will still show the template you were trying to deploy. So it is possible for a stack to NOT be successfully created an still have template for you to look at in the console.

At the same time, I'll bet the CloudFormation console doesn't handle unicode characters properly and shows `?????.???` for them, but that is a different issue from the one that's reported here, which is that the service doesn't accept unicode and we could help the user out by somewhat more eagerly validating with a hint to punycode (or punycode-encode for them automically, if we dare to)

**Comment by rix0rrr** [comment]
I mean, automatically encoding unicode -> punycode for domain names would totally be in the "do the right thing" charter for CDK to do. I'm just a little worried about the dependencies required to do it. Let me have a look-see.

**Comment by nija-at** [comment]
>> The generated CloudFormation template (as seen in AWS Console) has question marks instead of Cyrillic characters.
>>
> I'm guessing that Niranjan saw that remark, missed the error message, and thought the template had deployed successfully.

Correct.

The deployment indeed fails.

**Comment by rix0rrr** [comment]
Okay [punycode](https://www.npmjs.com/package/punycode) package has 0 dependencies. That's not too shabby...

**Comment by nija-at** [comment]
A validation in the CDK here would be the correct first step.

Open for anyone who wants to submit a PR.
