### ISSUE TITLE
Slow CDK synth performance due to stack trace collection

### ISSUE THREAD

**Issue by benmunro** [aws/aws-cdk#8479]
### The Question
I have a CDK stack which includes a large number of resources. This takes several minutes to complete a `cdk synth` operation. After investigating the slowness I found that this was due to the stack trace collection that the CDK performs [when each `IResolvable` is created](https://github.com/aws/aws-cdk/search?q=captureStackTrace&unscoped_q=captureStackTrace) to populate the [`creationStack`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/resolvable.ts#L43) property. Patching the [`captureStackTrace`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/stack-trace.ts#L2) method to be a noop instead (just immediately return `[]`) takes the synth time from minutes to seconds.

I have created a sample repo which contains code demonstrating this issue at https://github.com/benmunro/slow-cdk-synth-example. For me this shows

```
+ NUMBER_OF_CONSTRUCTS=1000
+ time npm run-script cdk synth
        5.79 real         7.29 user         0.51 sys
+ NO_STACKS=true
+ NUMBER_OF_CONSTRUCTS=1000
+ time npm run-script cdk synth
        2.36 real         3.26 user         0.36 sys
+ NUMBER_OF_CONSTRUCTS=10000
+ time npm run-script cdk synth
       32.93 real        37.12 user         1.51 sys
+ NO_STACKS=true
+ NUMBER_OF_CONSTRUCTS=10000
+ time npm run-script cdk synth
        4.49 real         6.02 user         0.42 sys
```

From what I could see this is just used to make nicer error messages when there are failures. I noticed there was the `aws:cdk:disable-stack-trace` feature flag but this only seems to make a difference for [the `Construct` class](https://github.com/aws/constructs/blob/8f2b556db79f2823542afe210ee40bea57f29bea/lib/construct.ts#L244-L246). Would it be possible to extend this feature flag to also disable the collection in all the other locations where `captureStackTrace` is used?
### Environment

  - **CDK CLI Version:** 1.45.0 (build 0cfab15)
  - **Module Version:** 1.45.0
  - **Node.js Version:** v14.1.0
  - **OS:** OSX Mojave
  - **Language (Version):** TypeScript (3.7.5)

**Comment by NetaNir** [comment]
Hi!

Thanks for diving into this and sharing your test results!
To address this, version 1.46.0 introduced a flag for disabling stack trace collection, out early testing shows it improves synth time:
```bash
CDK_DISABLE_STACK_TRACE=1 cdk synth
```
This will allow turning on stack trace collection only when required.

**Comment by eladb** [comment]
Duplicate #8792

**Comment by ionscorobogaci** [comment]
> Hi!
> 
> Thanks for diving into this and sharing your test results! To address this, version 1.46.0 introduced a flag for disabling stack trace collection, out early testing shows it improves synth time:
> 
> ```shell
> CDK_DISABLE_STACK_TRACE=1 cdk synth
> ```
> 
> This will allow turning on stack trace collection only when required.

turning on, or turning OFF ? DISABLE=1, looks like turning OFF not ON
