### ISSUE TITLE
Confusing Deprecations: IDeploymentEnvironment / Stack.addDockerImageAsset / DockerImageAsset.repositoryName

### ISSUE THREAD

**Issue by rrrix** [aws/aws-cdk#8483]
`DockerImageAssetOptions.repositoryName` is deprecated, instructing to override `Stack.addDockerImageAsset`.

https://github.com/aws/aws-cdk/blob/de5e406798b5f90147a7f9744ee626a0a91f2f10/packages/%40aws-cdk/aws-ecr-assets/lib/image-asset.ts#L20-L22

Interface property `DockerImageAssetSource.repositoryName` is also deprecated with a confusing message. 

https://github.com/aws/aws-cdk/blob/de5e406798b5f90147a7f9744ee626a0a91f2f10/packages/%40aws-cdk/core/lib/assets.ts#L153

However `Stack.addDockerImageAsset()` is also deprecated with a confusing deprecation warning: 

https://github.com/aws/aws-cdk/blob/de5e406798b5f90147a7f9744ee626a0a91f2f10/packages/%40aws-cdk/core/lib/stack.ts#L605-L606

I assume `IDeploymentEnvironment` is an interface I need to implement. However I cannot find this interface in the CDK source code **anywhere** and can only find references to it in the JSDoc's mentioning it in the `@aws-cdk/core/lib/stack.ts` file. 

I did find one other mention in an (Outdated!) PR: https://github.com/aws/aws-cdk/pull/6366#discussion_r382131917 

From reviewing reviewing #6366 it seems that that `IDeploymentEnvironment` was renamed to [`IStackSynthesizer`](https://github.com/aws/aws-cdk/blob/de5e406798b5f90147a7f9744ee626a0a91f2f10/packages/%40aws-cdk/core/lib/stack-synthesizers/types.ts#L8).

So... that means if I want to change what my docker image repository name is, I have to implement an entire stack synthesizer class? I just want a custom repository name for each image... :)

### Reproduction Steps

```
import { Repository } from '@aws-cdk/aws-ecr';
import { DockerImageAsset } from '@aws-cdk/aws-ecr-assets';
import { Construct, DockerImageAssetLocation, DockerImageAssetSource, Stack, StackProps } from '@aws-cdk/core';

class MyStack extends Stack {
  // deprecated
  addDockerImageAsset(asset: DockerImageAssetSource): DockerImageAssetLocation {
    return super.addDockerImageAsset(asset);
  }
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const repo = new Repository(this, 'repo', {
      repositoryName: 'my-repo',
    });
    new DockerImageAsset(this, 'containerImageAsset', {
      directory: './containerImageSrc',
      // deprecated
      repositoryName: repo.repositoryName,
    });
  }
}
```
### Error Log

```
[Warning at /ecr/apiAsset] DockerImageAsset.repositoryName is deprecated. Override "core.Stack.addDockerImageAsset" to control asset locations
```

### Environment

  - **CLI Version      :** 1.45.0 (build 0cfab15)
  - **Framework Version:** 1.45.0
  - **Node.js Version:**  v14.4.0
  - **OS               :** MacOS 10.15.5
  - **Language (Version):**  TypeScript (3.9.3)

### Other

I need to create multiple ECR repositories, one repo per "application image", ideally with a custom (human friendly) repository name. I need this for several reasons:

- Security (access control via IAM and Resource Policies)
- User access (`docker pull repo-url/image:tag`)
- External (non-CDK) tools access to image URI's 
- Ability to use the `latest` tag for each of my images & repositories (`docker pull repo-url/image:latest`)
- Managing individual Repository Tags for Billing and IAM Security

We have many different images for various applications, and pushing them all into `aws-cdk/assets` makes it impossible to distinguish one application image from another. This also means that I cannot use the `latest` tag (since only one image can have a unique tag in a repository). 

I need to be able to reference / find my images from outside of my CDK Application / Constructs, so that users and external (non-CDK) tools can easily find and pull these images.

With a single ECR repository, I can no longer effectively manage security on my individual images, since that's typically done [_per-repository_](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policy-examples.html), not per individual image hash/tag. If all of my images for different containers are in `aws-cdk/assets`, that makes granting access all-or-nothing.

Regarding the new Stack Synthesizer changes, why should my _Docker Image Repository Name_ be specified at the environment-level and not at the image level? I think specifying a _Container Registry_ at the environment level makes more sense (but not an image repository.)

Lastly, how do I properly override the repository name at the environment level? There's no documentation to do this AFAIK, although from reading through `@aws-cdk/core/lib/stack-synthesizers/legacy.ts` I _think_ I can set the context key `assets-ecr-repository-name` (which defaults to `aws-cdk/assets`) to a custom value. I think I could get this to sufficiently solve my use case, with an per-stack context value and one image/repository per stack.

I feel like this whole thing might all be a CDK-specific anti-pattern (even though it's the _norm_ for most container workflows). Should I avoid using the CDK and exclusively manage my container images completely outside of the CDK for this use case?

--- 

This is :bug: Bug Report and a 📕 documentation issue

**Comment by eladb** [comment]
Transferring to @rix0rrr

**Comment by rix0rrr** [comment]
At the moment the CDK comes with 2 asset systems:

* **The legacy one** (currently still the default), where you get to specify a repositoryName per asset, and the CLI will create and push to whatever ECR repository you name.

* **The new one** (will become the default in the future), where a *single* ECR repository will be created by doing `cdk bootstrap` and all images will be pushed into it. The CLI will not create the repository any more, it must already exist. 

If you want to deviate from this pattern then yes, you will have to implement your own subclass of `IStackSynthesizer` and use that.

**Comment by rrrix** [comment]
Thanks @rix0rrr for the explanation. I'm also curious as to the background / reasoning of this mechanism (given my requirements above). 

Is the CDK Context Key `assets-ecr-repository-name` also deprecated? Or is this an undocumented "internal-use-only" Context Key that end-users shouldn't be using anyways? 

https://github.com/aws/aws-cdk/blob/b0286e96076b298868686a1582e0bebdc3a82ddd/packages/%40aws-cdk/core/lib/stack-synthesizers/legacy.ts#L18-L24

Overriding the repository name with a simple context key would be _much_ more convenient than having to subclass `IStackSynthesizer` and all of the dragons that go with building and maintaining such a thing. I may be overestimating the effort needed to subclass the new stack synthesizer though.  

For today, until it's clear how to do this the "right way" and/or the new stack synthesizer is turned on by default, I temporarily have moved away from using CDK ECR Image Assets and setup a simple multi-step script to:

1) Create my ECR Repositories (using `@aws-cdk/aws-ecr`) via `cdk deploy ecr-stack1 ecr-stack2`
2) Simple shell script to several `docker build -t my-image:latest . && docker push 123456789012.dkr.ecr.region.amazonaws.com/my-image:latest`
3) Continue with the rest of the `cdk deploy stack1 stack 2` ... 

The ugly downside is that it's no longer a single command to deploy everything, and I have to manage my docker builds outside of my CDK App.

**Comment by rix0rrr** [comment]
As I mentioned in the other issue, I think a better way to go would be to replicate the container from a "temporary" repository to a controlled repository using a custom resource.

I get that this might feel a little wasteful, but given the use cases we're targeting with the provided built-ins that is probably the best you can do for now.

**Comment by gregorypierce** [comment]
If one already has a repository in the stack, wouldn't it be agreeable to allow that to be passed to the DockerImageAsset? In many cases I just need that asset to land in an already created repository. In my case I have an environment that created its own ECR Repository and I want those images to go there and NOT into a default cdk/asset repository as the Repository that I want those images to land in will have other ways of scanning images and such. 

If those images go elsewhere, a project's resources bleed out into a general location where they really shouldn't be. Is it at least agreeable to let one pass in the repository where those resources should land? I don't need CDK to create it, but if I have to later fish the resources out of cdk/assets - that has a bunch of other implications.

**Comment by p8a** [comment]
I second this, if you have multiple applications/stacks (like in a "dev" environment for example) everything will be merged into one place and since the original image name and tags are not kept it's hard to keep track of what's obsolete and needs to go vs what is still needed.

**Comment by okonon** [comment]
@rix0rrr @SomayaB any feedback on @gregorypierce comments? I am running into same issue were i would like to use ECR created in my stack for lambda deployments. We have multiple developers working on a lot of separate lambda microservices projects and do not want to bundle all 20+ of them in a single CDK project and rather manage them in their own  sub project so to speak and deploy using cli.

**Comment by rix0rrr** [comment]
We consciously decided not to do this, and this is the wrong ticket for it. You can reopen a new feature request and we may consider it given enough upvotes, but right now this is not really on the docket.

We recommend you don't care about ECR repositories the same way you don't care about the file asset S3 bucket.

----

If you need dev and prod resources in the same account separated (keeping in mind mixing dev and prod resources in a single account is strongly disrecommended!), you can bootstrap multiple sets of resources with different **qualifiers** to keep them separate.

**Comment by luxaritas** [comment]
@rix0rrr Before I open a new issue unnecessarily: While I understand this, does this leave any recommended way of cleaning up unused resources? It's seems like currently there is no way to even know what each image even _is_ (there's no human readable name or tag). I guess #6692 and/or #2663 is needed, and hopefully that is resolved before repositoryName is finally removed? Just want to make sure I understand the current situation.

**Comment by farajfarook** [comment]
Readable names and tags are required to maintain a clean solution. Call me OCD, but cleaner solution means one can login to the console and figure out issues or roll back stuff faster when sh*t hits the fan. It's stupid to have all the images pushed into a single ECR repo with tags being some hash which is not human readable. Seriously who takes these decisions. At least can someone please explain the reason behind this. What am I missing here? 
Also I feel like I'm using an Apple product here. :D

**Comment by wchaws** [comment]
@gregorypierce @okonon I wrote a `cdk-ecr-deployment` https://github.com/wchaws/cdk-ecr-deployment. See if this can help you.
With this you can replicate your ECR to another location
```ts
const image = new DockerImageAsset(this, 'CDKDockerImage', {
  directory: path.join(__dirname, 'docker'),
});

new ecrDeploy.ECRDeployment(this, 'DeployDockerImage', {
  src: new ecrDeploy.DockerImageName(image.imageUri),
  dest: new ecrDeploy.DockerImageName(`${cdk.Aws.ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/test:nginx`),
});
```
See if this can help.
