### ISSUE TITLE
HttpApi httpApiId fails to resolve

### ISSUE THREAD

**Issue by dbcfd** [aws/aws-cdk#8484]
When creating an AmazonApiGateway V2 HttpApi httpApiId will contain `${Token[TOKEN.21]}` or when using resolve, `[Object object]`. I would expect httpApiId to be a valid id either when HttpApi is created or when resolved, of the form `abcdefgh`. 

CDK Version: 1.45

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Unforunately, the `httpApiId` is a value that can only be resolved to the final id after deployment. 

In the CDK, the raw value will be a token and after resolution, it will resolve to a [CloudFormation Ref intrinsic](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html).

Read more about tokens here - https://docs.aws.amazon.com/cdk/latest/guide/tokens.html
