### ISSUE TITLE
Change name of default branch

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk#8485]
## :question: General Issue

Would it be possible to change the name of the default branch in this repo from "master" to "mainline" or some other alternative? This is already a convention at Amazon internally, and would be compliant with the recommendation by the IETF: https://tools.ietf.org/id/draft-knodel-terminology-00.html

Thanks!

**Comment by SomayaB** [comment]
https://github.com/aws/jsii/issues/1733

**Comment by iph** [comment]
Isn't "master" based off of the equivalent ["master recording"](https://simple.wikipedia.org/wiki/Master_recording) or `masters` being the first while all else are copies? This fits more in line with what git is about (copies) vs what perforce/cvs is about. Fun fact: Amazon had a history with perforce/cvs before git, which is probably why mainline exists as the default branch (#frugal).

It would be nice to get consensus by the people who submitted the original draft terminology. It's unclear in the draft, as all the github samples referenced there that merged new terminology for `master-slave` (which we all totally agree with),  all use `master` as the branch, which sends mixed signals.

**Comment by iph** [comment]
Seems github is all onboard with "main": https://twitter.com/lgarron/status/1271212268294823938

Should we follow what the platform will be going toward and use that instead of mainline?

**Comment by RomainMuller** [comment]
@iph this is kind of what I personally lean towards, but we're consulting with the rest of AWS in order to avoid a proliferation of standards from our end.

It might take a little while for us to change as we need to coordinate this with our CI/CD infrastructure, etc (as well as investigate impact on all open PRs against `master`).

**Comment by nija-at** [comment]
FWIW - we're using the combination `master`-`release` with our branch naming indicating that the use here is along the lines of the 'master recording' that @iph pointed at. From what I can tell, the IETF draft suggests to avoid a different interpretation of the word 'master'.

There is the cost of compatibility to historical tooling to consider.

**Comment by rix0rrr** [comment]
Update on this issue: `master` is on its way out. For V2 (which is being developed on a separate branch), we are switching to the `main` nomenclature.
