### ISSUE TITLE
EMR cfnCluster steps hadoopJarStep args is created with " at start and end of Arguments

### ISSUE THREAD

**Issue by fmcmac** [aws/aws-cdk#8490]
EMR Step created with arguments has arguments including quotes as
```Arguments : "spark-submit --deploy-mode cluster s3://...script.py"``` this fails
Should be ```Arguments : spark-submit --deploy-mode cluster s3://...script.py```
Succeeds with no quotes. When the step is created manually there are no "".

The appear to cause cause error: Caused by: java.io.IOException: Cannot run program "spark-submit --deploy-mode cluster s3://emr-vpc-s3bucketscripts86fda855-nhjwrxp55888/scripts/csv_to_parquet.py" (in directory "."): error=2, No such file or directory

### Reproduction Steps

```
        # create emr cluster
        self.emr_cluster = emr.CfnCluster(
            self,
            "emr_cluster",
           ...steps=[
                {
                    "actionOnFailure": "CONTINUE",
                    "hadoopJarStep": {
                        "jar": "command-runner.jar",
                        "args": [
                            "spark-submit --deploy-mode cluster s3://mybucket/scripts/script.py"
                        ],
                    },
                    "name": "pyspark_script",
                }
            ],
        )
```
Then deploy the stack

### Error Log

Status:Failed
Start time:2020-06-11 17:27 (UTC+12)
ID:s-1TH7MISIFN3YU
Elapsed time:2 seconds
Log files:controller | syslog* | stderr | stdout*
JAR location : command-runner.jar
Main class : None
Arguments : "spark-submit --deploy-mode cluster s3://mybucket/scripts/script.py"
Action on failure: Continue

Caused by: java.io.IOException: Cannot run program "spark-submit --deploy-mode cluster s3://mybucket/scripts/script.py" (in directory "."): error=2, No such file or directory

### Environment

  cdk --version >> 1.45.0 (build 0cfab15)
  python --version >> Python 3.8.1
  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by fmcmac** [comment]
I have found that the below works correctly. If this is correct behavior then this can be closed.
```
        # create emr cluster
        self.emr_cluster = emr.CfnCluster(
            self,
            "emr_cluster",
            ...,
            steps=[
                {
                    "actionOnFailure": "CONTINUE",
                    "hadoopJarStep": {
                        "jar": "command-runner.jar",
                        "args": [
                            "spark-submit",
                            "--deploy-mode",
                            "cluster",
                            "s3://mybucket/scripts/script.py",
                        ],
                    },
                    "name": "job_name",
                }
            ],
        )
```

**Comment by iliapolo** [comment]
Hi @fmcmac 

Yes, the solution you posted is definitely the correct way to configure this. The fact `args` is an array and not simply a string, is exactly to allow this way of configuration and avoiding escaping problems. 👍 

Closing the issue.
