### ISSUE TITLE
Support cdk deploy stack update without change set - speed up deployments

### ISSUE THREAD

**Issue by ottokruse** [aws/aws-cdk#8493]
It would be great if there was an option for `cdk deploy` to do a direct CloudFormation deployment and not use a change set.

I was using serverless framework this morning and was amazed by how fast deployments were. For a second I thought AWS had implemented a general performance boost to CloudFormation :D But it turn out serverless is quicker in deploying than I was used to with CDK because serverless framework does not use change sets. That makes a ton of difference in deployment speed.

For most projects I am on we do not review change sets anyway (reviews are done as part of PR's and within the deployment pipeline).

### Proposed Solution

Add a flag e.g. `--no-changeset` to `cdk deploy` command.

If specified, upon deployment a change set will not be created. If the stack exists, the stack is updated without change set.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by mikestopcontinues** [comment]
It's been a while. Any thoughs @shivlaks ?

**Comment by rix0rrr** [comment]
Not possible. We use a number of CFN features that require a change set.

**Comment by egglestonbd** [comment]
I understand `--no-execute` accomplishes the same thing.

**Comment by kichik** [comment]
#22079 resolved this. If you're here from Google like me, this is how:

```
cdk deploy --method direct
```

Or:

```
export CDK_METHOD=direct
cdk deploy
```

**Comment by ottokruse** [comment]
Thanks for the heads up !
