### ISSUE TITLE
Enable 'AccountRecoverySetting' attribute on UserPool (L2 Construct)

### ISSUE THREAD

**Issue by smunukuntla** [aws/aws-cdk#8502]
### Description - New Feature Request
Enable 'AccountRecoverySetting' attribute on UserPool (L2 Construct)

### Reproduction Steps

```
const cfnUserPool = PHONE_ONLY_PASSWORD_LESS_USER_POOL.node.defaultChild as CfnUserPool;
    cfnUserPool.accountRecoverySetting = {
      recoveryMechanisms: [{
        name: 'admin_only',
        priority: 1
      }]
    }
```

### Environment

  - **CDK Framework Version:* 1.45.0 (build 0cfab15)*
  - **Node.js Version:*12.16* 
  - **OS               :*macOS*
  - **Language (Version):*TypeScript (~3.7.2)*

**Comment by civilizeddev** [comment]
## Use `class UserPool` with property `lambdaTriggers`

It seems like you are using `class CfnUserPool` (L1 - cloudformation resource).

To which you just passed the lambda function without granting a permission to invoke it.

The user pool must have permission to invoke the lambda function.

You can achieve it by using `class UserPool` (L2 - cdk construct)

### Example

```
import * as cognito from '@aws-cdk/aws-cognito'

new cognito.UserPool(this, 'userPool', {
  ...,
  lambdaTriggers: {
    preSignUp: new lambda.Function(this, 'preSignUp', {
      ...
    }),
  },
})
```

> Resolution: Not a bug

**Comment by smunukuntla** [comment]
@civilizeddev Thank you. As you said, this time I used `class UserPool` (L2 - cdk construct) and it worked as expected. 

On a side note, I tried to set **tags** and **accountRecoverySetting** but I don't see these attributed on L2 - cdk construct. For this, again I have to use `class CfnUserPool` (L1 - cloud formation resource).like below : 

```
    const cfnUserPool = PHONE_ONLY_PASSWORD_LESS_USER_POOL.node.defaultChild as CfnUserPool;
    cfnUserPool.accountRecoverySetting = {
      recoveryMechanisms: [{
        name: 'admin_only',
        priority: 1
      }]
    }
    cfnUserPool.tags.setTag("project","phone-only-password-less-userpool");
```

Personally, I didn't like to user L1 & L2 together for solving different needs that is why I started looking into 
class CfnUserPool` (L1 - cloud formation resource) because it will have every single attribute available.

is this expected? thoughts please?

**Comment by civilizeddev** [comment]
@smunukuntla

`UserPool` is taggable.

### Example

```
import * as cdk from '@aws-cdk/core'
import * as cognito from '@aws-cdk/cognito'

consg userPool = new cognito.UserPool(this, 'userPool', { ... })
cdk.Tag.add(userPool, 'project', 'phone-only-password-less-userpool');
```

**Comment by civilizeddev** [comment]
@smunukuntla 

As for the property `AccountRecoverySetting`, I'll make a pull request for it.

You should change the title of the issue and the description to be relevant on it.

**Comment by smunukuntla** [comment]
@civilizeddev updated title and description.
