### ISSUE TITLE
Need a way to upload user public key to access codecommit

### ISSUE THREAD

**Issue by bmVsc29u** [aws/aws-cdk#8504]
![image](https://user-images.githubusercontent.com/46260795/84419133-c1f77980-ac4a-11ea-987a-badd8b3950ec.png)

### Use Case

No need to login console and upload the key.

### Proposed Solution

I checked there is a upload ssh key cli feature, but seems not in cloudformation yet.
Maybe a custom resource build with lambda may work.

This is a :rocket: Feature Request

**Comment by indrora** [comment]
This doesn't seem to be possible: There is no CLI or CloudFormation structure to specify an SSH key for a user. This appears to be a console-only action.

**Comment by moharam-dev** [comment]
@indrora are you sure about that?

[CLI - IAM User](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/upload-ssh-public-key.html)
[API - IAM User](https://docs.aws.amazon.com/IAM/latest/APIReference/API_UploadSSHPublicKey.html)
