### ISSUE TITLE
Add support for Zeppelin notebook servers dev-endpoints

### ISSUE THREAD

**Issue by ali-habibzadeh** [aws/aws-cdk#8505]
AWS Glue has a featured for creating testing notebooks via Zeppelin and SageMaker so data folks can test queries out etc. before moving ETL scripts into prod. 

It seems this functionality is missing from CDK Glue module. 

### Use Case

So when a stack is deployed we can get a dev endpoint URL in the output and provide it to data scientists who want to work on data lakes in an automated and neat fashion. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Hi @ali-habibzadeh 

Can you please provide some more detail on the requested feature? 

From what I gather, you are talking about an option to extract specific runtime data from Glue resources and expose them as stack outputs. Is that right?

If so, what data exactly? can you refer us to the Glue API that exposes this data? It would also help a lot if you could provide a sample CDK stack that can be used to deploy the use-case you are talking about.

If not, are you referring to some feature that is supported by `CloudFormation` but is missing from CDK?

Thanks

**Comment by ali-habibzadeh** [comment]
Keep open

**Comment by ali-habibzadeh** [comment]
Keep open

**Comment by ali-habibzadeh** [comment]
Keep open
