### ISSUE TITLE
RDS Engine abstraction design issue

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#8506]
This issue is a spinoff from #8412.

We want to use this issue to discuss proposed designs for RDS' Engine concept, and how to model it most effectively in the CDK.

Here's the first proposal, from the original PR:

```ts
export interface IClusterEngine {
  readonly engineType: string;
  readonly engineVersion?: string;
  readonly parameterGroupFamily: string;
  readonly singleUserRotationApplication: secretsmanager.SecretRotationApplication;
  readonly multiUserRotationApplication: secretsmanager.SecretRotationApplication;
  readonly defaultInstanceType: ec2.InstanceType;
  withVersion(engineVersion: string): IClusterEngine;
  bindToCluster(scope: core.Construct, options: ClusterEngineOptions): ClusterEngineConfig;
}
```

Example of a more specialized engine:

```ts
export interface IAuroraClusterEngine extends IClusterEngine {
  withVersion1dot17dot9(): IClusterEngine;
}
```

And then, not much changes in the existing `DatabaseClusterEngine`:

```ts
export class DatabaseClusterEngine {
  // all these constants exist in the code today

  public static readonly AURORA: IAuroraClusterEngine = new AuroraClusterEngine();

  public static readonly AURORA_MYSQL: IClusterEngine = new AuroraMySqlClusterEngine();

  public static readonly AURORA_POSTGRES: IClusterEngine = new AuroraPostgresClusterEngine();
}
```

`IInstanceEngine` is very similar.

#### Pros

* Very backwards compatible (all of the existing constants in `DatabaseClusterEngine` and `DatabaseInstanceEngine` are preserved; the user-facing API is the same).
* Well-suited for additional degrees of freedom added to Engine later; for example, adding support for EngineModes would be as simple as adding `withEngineMode()` to `IClusterEngine`.
* Well-suited for engine-specific properties; for example, we could add a `withFoobar()` to `IAuroraClusterEngine` if it starts to support an engine-specific `foobar` property.

#### Cons

* JSII does not allow an instance method name like `withVersion_1_17_9()`, which means we have to go with the uber-ugly `withVersion1dot17dot9()` 😕.
* The fluent style might cause some type issues (for example, `withVersion_1_17_9()` returns an `IClusterEngine`, not an `IAuroraClusterEngine`, because it's implemented in terms of `withVersion()`).

**Comment by skinny85** [comment]
cc @nija-at @rix0rrr @jogold

**Comment by nija-at** [comment]
Can you provide a few examples on how this would look when a customer wants to instantiate a specific engine type - starting with the common/simplest case and going all the way to where a user wants a specific version with specific features chosen?

**Comment by skinny85** [comment]
> Can you provide a few examples on how this would look when a customer wants to use these APIs - starting with the common/simplest case and going all the way to where a user wants a specific version with specific features chosen?

Sure.

The basic use case is the same as today. This uses the Aurora default engine without a specific version of the engine, and without any specific features enabled:

```ts
new rds.DatabaseCluster(this, 'Cluster', {
  engine: rds.DatabaseClusterEngine.AURORA,
  // ...
});
```

On the other hand of the spectrum, here's the same Aurora default engine, but with a specific version, a custom engine mode, and an Aurora-specific feature `foobar` enabled:

```ts
new rds.DatabaseCluster(this, 'Cluster', {
  engine: rds.DatabaseClusterEngine.AURORA
    .withFoobarEnabled()
    // yuck - we could do something like withVersion(AuroraClusterEngineVersion.VER_1_17_9) instead
    .withVersion1dot17dot9(),
    .withEngineMode(rds.EngineMode.SERVERLESS), 
  // ...
});

**Comment by nija-at** [comment]
What about bringing it closer to our existing CDK patterns?

```ts
new rds.DatabaseCluster(this, 'Cluster', {
  engine: new rds.AuroraClusterEngine({
    foobar: true,
    version: '1.19.1' // or AuroraVersion.1_19_1,
    // ...
  }),
});
```

This feels more like the existing CDK experience. Further, we already have the `withXXX()` builder pattern generated for Java. These two can seem similar but be slightly different and confuse.

How does engine mode affect the list of features that are available on a specific database cluster (e.g. aurora)? Are there cases where specific features are available (or unavailable) in specific engine modes?

Are engine and engine modes the only dimensions on which features are available? Are there other dimensions? Can versions of a specific engine support (or not support) specific features?

**Comment by skinny85** [comment]
> What about bringing it closer to our existing CDK patterns?
> 
> ```ts
> new rds.DatabaseCluster(this, 'Cluster', {
>   engine: new rds.AuroraClusterEngine({
>     foobar: true,
>     version: '1.19.1' // or AuroraVersion.1_19_1,
>     // ...
>   }),
> });
> ```
> 
> This feels more like the existing CDK experience. Further, we already have the `withXXX()` builder pattern generated for Java. These two can seem similar but be slightly different and confuse.

Two clarifying questions.

1. What do you want to do with the existing constants like `DatabaseClusterEngine.AURORA`? Leave them unchanged, deprecate them, remove them?
2. How about using static factory methods instead of `new ClassName`? So, your example would be:

```ts
new rds.DatabaseCluster(this, 'Cluster', {
  engine: rds.DatabaseClusterEngine.auroraClusterEngine({
    foobar: true,
    version: '1.19.1' // or AuroraVersion.1_19_1,
    // ...
  }),
});

**Comment by nija-at** [comment]
> What do you want to do with the existing constants like DatabaseClusterEngine.AURORA? Leave them unchanged, deprecate them, remove them?

In the interest of existing customers who have been using this for a while, we should probably deprecate `engine` property and introduce a new `dbEngine` (or something like that). Interested in hearing other opinions here.

> How about using static factory methods instead of `new ClassName`?

Not terribly opposed to this. However, I'm curious why do this here when we don't do this for integration classes in other places across the CDK?

**Comment by skinny85** [comment]
We discussed this offline, here are the action items stemming from that discussion:

1. We will add interfaces `IClusterEngine` and `IInstanceEngine`, similarly like they were introduced in the first PR.
2. The property `engineVersion` will be removed from `ClusterProps` and `InstanceProps`. Instead, `engineVersion` will be tied to a specific Engine.
3. The `IClusterEngine` and `IInstanceEngine` interfaces will **not** have methods like `withVersion()`, `withEngineMode()`, etc.
4. Instead, we will add public classes implementing the interfaces mentioned in point 1, for example `AuroraClusterEngine`. It will take a props object as its only constructor argument, where all of the relevant properties of a given engine will be passed.
5. Existing constants in `DatabaseClusterEngine` and `DatabaseInstanceEngine` will be retrofitted to implement the new interfaces.
6. We will also add static factory methods in `DatabaseClusterEngine` and `DatabaseInstanceEngine` returning instances of classes like `AuroraClusterEngine` from point 4 above, taking the same props interface as the sole argument. Their goal is aiding in the discoverability of the new classes for customers using constants in `DatabaseClusterEngine` and `DatabaseInstanceEngine`.

**Comment by nija-at** [comment]
Instead of concluding on code changes, can we express the conclusions in the format of the APIs?

**Comment by skinny85** [comment]
> Instead of concluding as a set of code changes, can we express the conclusions in the as real world customer facing APIs?

I don't see the value in this issue anymore. Let's continue the discussion in #8686 , that contains the customer-facing API.
