### ISSUE TITLE
Backoff/Retry for Custom Domain deletion via CDK

### ISSUE THREAD

**Issue by bcondley-verimatrix** [aws/aws-cdk#8516]
When there are multiple Custom Domain Names owned by a single stack, updates to that stack will fail due to the hard limit on deletions for Custom Domains with API Gateway (2 every 30 seconds).  Boto3 and other utilities already have exponential backoff and/or retry capabilities, but deployment automation via CDK is missing this functionality.  When the stack update fails, often times the stack is left in an state where the rollback failed, requiring manual intervention.

### Use Case

Full automation via CDK is not possible for CFN stacks deploying API Gateways with multiple Custom Domain Name entries.

### Proposed Solution

This functionality currently exists in Boto3 and CloudFormation when a stack is destroyed through the console.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Unfortunately, we use CloudFormation to execute stack updates, and don't interact with these services directly, so this will have to be an issue opened with CloudFormation. Reach out to AWS support for urgent issues or open an issue [here](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/).

Let us know if there's something else I missed here.
