### ISSUE TITLE
Docker build fails for creating local CDK dev environment

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#8518]
According to CONTRIBUTION.md if you want to bootstrap a local CDK dev environment with docker, its just doing (on a fresh checkout of master):

docker build -t aws-cdk .

The build fails with the error mentioned in the section below.

### Reproduction Steps

just do: 
docker build -t aws-cdk .

### Error Log

awslint: Done in 8.69s.
cdk-dasm: PASS test/dasm.test.js
cdk-dasm:   ✓ basic test (26ms)
cdk-dasm:   ✓ no props (2ms)
cdk-dasm:   ✓ multiple of same type (2ms)
cdk-dasm:   ✓ bucket-and-key (5ms)
cdk-dasm: Test Suites: 1 passed, 1 total
cdk-dasm: Tests:       4 passed, 4 total
cdk-dasm: Snapshots:   4 passed, 4 total
cdk-dasm: Time:        0.874s
cdk-dasm: Ran all test suites.
cdk-dasm: Done in 9.47s.
pkglint: Done in 10.13s.
yarn-cling: yarn run v1.22.4
yarn-cling: $ npm run build && npm test
yarn-cling: > yarn-cling@0.0.0 build /app/tools/yarn-cling
yarn-cling: > tsc
yarn-cling: > yarn-cling@0.0.0 test /app/tools/yarn-cling
yarn-cling: > ln -sf ../../package2 test/test-fixture/package1/node_modules/ && jest
yarn-cling: ln: target ‘test/test-fixture/package1/node_modules/’ is not a directory: No such file or directory
yarn-cling: npm ERR! Test failed.  See above for more details.
yarn-cling: error Command failed with exit code 1.
yarn-cling: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in 'yarn-cling'

real    0m34.214s
user    1m2.256s
sys     0m8.297s
❌  Last command failed. Scroll up to see errors in log (search for '!!!!!!!!').
The command '/bin/sh -c ./build.sh ${BUILD_ARGS} && ./link-all.sh' returned a non-zero code: 1

### Environment

  - **Framework Version: 1.45.0 (build 0cfab15)**
  - **OS               : Mac OS**

--- 

This is :bug: Bug Report

**Comment by am29d** [comment]
This is because `.dockerignore` has `**/**/node_modules`. During docker build the context is filtered by this rule and so the node_modules in the test-fixture are missing. 

One way to solve it is to add `!tools/yarn-cling/test/**/node_modules` exception entry in the `.dockerignore`.

**Comment by rrrix** [comment]
I thought this was just me... good to know it's not!

**Comment by am29d** [comment]
I was about to submit a PR, but the build still fails, because of `@aws-cdk/aws-s3-assets`, during the build it tries to run docker.

**Error Log:**

```
@aws-cdk/aws-s3-assets: Ran all test suites.
@aws-cdk/aws-s3-assets: /app/packages/@aws-cdk/core/lib/bundling.js:77
@aws-cdk/aws-s3-assets:         throw new Error(`[Status ${proc.status}] stdout: ${(_b = proc.stdout) === null || _b === void 0 ? void 0 : _b.toString().trim()}\n\n\nstderr: ${(_c = proc.stderr) === null || _c === void 0 ? void 0 : _c.toString().trim()}`);
@aws-cdk/aws-s3-assets:         ^
@aws-cdk/aws-s3-assets: Error: [Status 1] stdout:
@aws-cdk/aws-s3-assets: stderr: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
@aws-cdk/aws-s3-assets:     at dockerExec (/app/packages/@aws-cdk/core/lib/bundling.js:77:15)
@aws-cdk/aws-s3-assets:     at Function.fromAsset (/app/packages/@aws-cdk/core/lib/bundling.js:33:24)
@aws-cdk/aws-s3-assets:     at new TestStack (/app/packages/@aws-cdk/aws-s3-assets/test/integ.assets.bundling.lit.js:14:51)
@aws-cdk/aws-s3-assets:     at Object.<anonymous> (/app/packages/@aws-cdk/aws-s3-assets/test/integ.assets.bundling.lit.js:28:1)
@aws-cdk/aws-s3-assets:     at Module._compile (internal/modules/cjs/loader.js:778:30)
@aws-cdk/aws-s3-assets:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
@aws-cdk/aws-s3-assets:     at Module.load (internal/modules/cjs/loader.js:653:32)
@aws-cdk/aws-s3-assets:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
@aws-cdk/aws-s3-assets:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
@aws-cdk/aws-s3-assets:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
@aws-cdk/aws-s3-assets: Subprocess exited with error 1
@aws-cdk/aws-s3-assets: Error: Command exited with status 1
@aws-cdk/aws-s3-assets:     at exec (/app/tools/cdk-integ-tools/lib/integ-helpers.js:229:15)
@aws-cdk/aws-s3-assets:     at IntegrationTest.invoke (/app/tools/cdk-integ-tools/lib/integ-helpers.js:91:20)
@aws-cdk/aws-s3-assets: Error: cdk-integ-assert exited with error code 1
@aws-cdk/aws-s3-assets: Tests failed. Total time (11.4s) | /app/node_modules/jest/bin/jest.js (10.0s) | cdk-integ-assert (1.4s)
@aws-cdk/aws-s3-assets: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@aws-cdk/aws-s3-assets: npm ERR! Test failed.  See above for more details.
@aws-cdk/aws-s3-assets: Verifying integ.assets.bundling.lit.js against integ.assets.bundling.lit.expected.json ... info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@aws-cdk/aws-s3-assets: error Command failed with exit code 1.
lerna ERR! yarn run build+test exited 1 in '@aws-cdk/aws-s3-assets'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.

real	10m6.655s
user	53m33.703s
sys	7m7.137s
❌  Last command failed. Scroll up to see errors in log (search for '!!!!!!!!').
The command '/bin/sh -c ./build.sh ${BUILD_ARGS} && ./link-all.sh' returned a non-zero code: 1
```

While the base image does provide `dockerd` (I checked your `buildspec.yaml`), I cant start the daemon during the build phase: 

```
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.2 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
```
I also saw an [`dockerd-entrypoint.sh`](https://github.com/aws/jsii/blob/7d0b987f7e24ecce7a6a83139920d4e754f7fc93/superchain/Dockerfile#L87) in the base image, but it also leads to a timeout due to permission (you must be root). I am not sure how to bypass this problem, since we cant have `privileged` or `cap-add` flag during the build phase 😕 .

**Comment by shivlaks** [comment]
I'm sorry you ran into this pain point... we're working on simplifying this test so it doesn't need Docker as a unit test *should* be self contained.

a workaround for now would be to run:
```
docker build -t aws-cdk --build-arg BUILD_ARGS='--skip-test --no-bail' .
```

**Comment by logemann** [comment]
still not able to finish the build.

```
@monocdk-experiment/assert: Error: /app/node_modules/typescript/bin/tsc --build exited with error code 1
@monocdk-experiment/assert: Build failed. ${timers.display()}
@monocdk-experiment/assert: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@monocdk-experiment/assert: error Command failed with exit code 1.
```

**Comment by nathanpeck** [comment]
I was able to make it much further into the build process without the tests however the build still failed with the following error:

```
@aws-cdk/cloudformation-include: $ cdk-build
decdk: internal/modules/cjs/loader.js:638
decdk:     throw err;
decdk:     ^
decdk: Error: Cannot find module '/app/packages/@aws-cdk/.DS_Store/package.json'
decdk:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
decdk:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
decdk:     at Module.require (internal/modules/cjs/loader.js:692:17)
decdk:     at require (internal/modules/cjs/helpers.js:25:18)
decdk:     at Object.<anonymous> (/app/packages/decdk/deps.js:17:16)
decdk:     at Module._compile (internal/modules/cjs/loader.js:778:30)
decdk:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
decdk:     at Module.load (internal/modules/cjs/loader.js:653:32)
decdk:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
decdk:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
decdk: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
decdk: error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in 'decdk'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

It looks like the build process is picking up the .DS_Store hidden folder automatically created by Mac OS X. I can delete it manually to workaround this but we should make the build process more resilient

**Comment by rrrix** [comment]
@nathanpeck try to add a `.dockerignore` file:

```gitignore
**/.DS_Store
```

https://docs.docker.com/engine/reference/builder/#dockerignore-file

**Comment by am29d** [comment]
I think the best way to run a dockerized build right now is to run a container in interactive mode and execute `build.sh`. 

```
docker run --rm --net=host -it -v $PWD:$PWD -w $PWD jsii/superchain
```

It is also stated in the contributing doc, but lots of people try to run docker build which has issues right now. We can also pass the privilege flag and execute docker in docker builds for the tests.

**Comment by logemann** [comment]
In order to run something in a docker container you have to build the image right?

**Comment by am29d** [comment]
> In order to run something in a docker container you have to build the image right?

No, we use the [jsii/superchain](https://hub.docker.com/r/jsii/superchain) docker image, it is available on docker hub.

**Comment by logemann** [comment]
thanks for pointing out @am29d . But to be honest. The only reference to that docker image is in the partial build section. Not the first thing you will read when you want to start building this project.  I contributed to a lot of oss projects over the years, but this one here is definitely one of the tougher ones to get going and CONTRIBUTING.md doesnt help much as it is right now. To attract more outside devs, i would stronly encourage to make it easier for them.

**Comment by am29d** [comment]
> thanks for pointing out @am29d . But to be honest. The only reference to that docker image is in the partial build section. Not the first thing you will read when you want to start building this project. I contributed to a lot of oss projects over the years, but this one here is definitely one of the tougher ones to get going and CONTRIBUTING.md doesnt help much as it is right now. To attract more outside devs, i would stronly encourage to make it easier for them.

I completely agree, there should be a better documentation to make the life of contributors easier. It was also hard for me to start and find these details, and I am not a contributor (yet) :). Right now the steps in documentation can not lead to successful builds and we should fix that.

I will try to submit a PR for clearer documentation steps.

**Comment by shivlaks** [comment]
@am29d @logemann absolutely agree. I'm already on it (PR to improve the documentation of `CONTRIBUTING`, let me know if you'd like to write it. I'm happy to yield way to avoid duplication of effort)

**Comment by am29d** [comment]
@shivlaks if you are already on PR then I will wait. I am sure there more details you want to put into it, that I am not aware of. I can provide feedback by running through the new `CONTRIBUTING` on a clean dev machine.

**Comment by MichaelWalker-git** [comment]
I'm not sure if this helps someone else, but the issue for me was that my docker image was previously for the intel chip. I had upgraded to an M1, making the version of Docker incompatible. 

Uninstalling, and reinstalling the M1 apple silicon Docker version fixed this.

https://docs.docker.com/desktop/mac/apple-silicon/

**Comment by TheRealAmazonKendra** [comment]
Given the lack on interaction on this action and the update made to the contributing guide, it seems like this is no longer an issue. I'm going to go ahead and close it. If this is in error and you are still experiencing the issue, please feel free to open a new issue.
