### ISSUE TITLE
EKS Managed NodeGroup failed to stabilize: Instances failed to join the kubernetes cluster

### ISSUE THREAD

**Issue by yjw113080** [aws/aws-cdk#8520]
In some of us regions (us-east-1, us-west-1, us-west-2), I experienced NodeCreationFailure with my EKS cluster construct.
The error does not happen always, but time to time, which frustrates me even more.
I got error once, but I don't next time even though I did not change my source at all...
It feels totally random so far. Could you direct me which to look into?

### Reproduction Steps

Here is my cluster construct part.

```
    const cluster = new eks.Cluster(this, 'demogo-cluster', {
      clusterName: `demogo`,
      mastersRole: clusterAdmin,
      defaultCapacity: 2,
      defaultCapacityInstance: cdk.Stack.of(this).region==primaryRegion? 
                                  new ec2.InstanceType('r5.2xlarge') : new ec2.InstanceType('m5.2xlarge')
    });

    cluster.addCapacity('spot-group', {
      instanceType: new ec2.InstanceType('m5.xlarge'),
      spotPrice: cdk.Stack.of(this).region==primaryRegion ? '0.248' : '0.192'
    });
```

### Error Log

```
 55/56 | 오후 11:01:21 | CREATE_FAILED        | AWS::EKS::Nodegroup                   | demogo-cluster/NodegroupDefaultCapacity (demogoclusterNodegroupDefaultCapacity2DF84DF0) Nodegroup demogoclusterNodegroupDefau-GPw0xO4poCqV failed to stabilize: [{Code: NodeCreationFailure,Message: Instances failed to join the kubernetes cluster,ResourceIds: [i-06a079287ab0a10f4, i-079f41c97ba8d60c1]}]
        new Nodegroup (/Users/jiwony/multi-cluster-ts/node_modules/@aws-cdk/aws-eks/lib/managed-nodegroup.ts:242:22)
        \_ Cluster.addNodegroup (/Users/jiwony/multi-cluster-ts/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:512:12)
        \_ new Cluster (/Users/jiwony/multi-cluster-ts/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:446:14)
        \_ new ClusterStack (/Users/jiwony/multi-cluster-ts/lib/cluster-stack.ts:21:23)
        \_ Object.<anonymous> (/Users/jiwony/multi-cluster-ts/bin/multi-cluster-ts.ts:15:24)
        \_ Module._compile (internal/modules/cjs/loader.js:945:30)
        \_ Module.m._compile (/Users/jiwony/multi-cluster-ts/node_modules/ts-node/src/index.ts:837:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:962:10)
        \_ Object.require.extensions.<computed> [as .ts] (/Users/jiwony/multi-cluster-ts/node_modules/ts-node/src/index.ts:840:12)
        \_ Module.load (internal/modules/cjs/loader.js:798:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:711:12)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
        \_ main (/Users/jiwony/multi-cluster-ts/node_modules/ts-node/src/bin.ts:226:14)
        \_ Object.<anonymous> (/Users/jiwony/multi-cluster-ts/node_modules/ts-node/src/bin.ts:485:3)
        \_ Module._compile (internal/modules/cjs/loader.js:945:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
        \_ Module.load (internal/modules/cjs/loader.js:798:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:711:12)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
        \_ /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:** 1.45.0
  - **Node.js Version:** v12.11.1
  - **OS               :** Mojave 10.14.6
  - **Language (Version):**  TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by Marakai** [comment]
Adding a "me too":

```
        cluster_admin = iam.Role(self, 'AdminRole', assumed_by=iam.AccountRootPrincipal())
        cluster = eks.Cluster(self, "EKSCluster",
                              vpc=vpc,
                              vpc_subnets=[ec2.SubnetType.PUBLIC],
                              masters_role=cluster_admin,
                              output_cluster_name=True
                              )
```

Cluster is created, the Nodegroup as well, I see the instances reach healthy states - then nothing until it finally fails.

**Comment by eladb** [comment]
I suspect this was fixed by https://github.com/aws/aws-cdk/pull/8548 - please reopen if this is still an issue.

**Comment by taotao1995** [comment]
I dont find the link/reference is helping.
The issue exists with node group. And even if I add the role that was describe to work with fargate group, it doesn't change the error.

**Comment by iliapolo** [comment]
@taotao1995 Could you please share the code you are using? specifically the VPC configuration and its usage in the cluster definitions.

**Comment by taotao1995** [comment]
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EKS Cluster - role to cluster and cluster
Mappings:
  RegionMap:
    ap-southeast-2:
      2aCIDR: 10.1.0.0/23
      2bCIDR: 10.1.2.0/23
      2cCIDR: 10.1.4.0/23
      2aCorednsCIDR: 10.1.6.0/23
      2bCorednsCIDR: 10.1.8.0/23
      2cCcorednsCIDR: 10.1.10.0/23
Resources:
  CoreDnsFargatePrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref EksVPC
      CidrBlock: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - 2aCorednsCIDR
      AvailabilityZone: !Select 
        - 0
        - 'Fn::GetAZs': ''
      Tags:
        - Key: kubernetes.io/cluster/development
          Value: shared
        - Key: Name
          Value: !Sub '${AWS::StackName}/CoreDnsFargatePrivateSubnet1'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0edbeb74-5856-400e-b916-335c6cc3c09a
  CoreDnsFargatePrivateSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref EksRouteTableForPrivateSubnet
      SubnetId: !Ref CoreDnsFargatePrivateSubnet1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6707c63e-ecbe-4b13-92f5-c0da20bd9436
  CoreDnsFargatePrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref EksVPC
      CidrBlock: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - 2bCorednsCIDR
      AvailabilityZone: !Select 
        - 1
        - 'Fn::GetAZs': ''
      Tags:
        - Key: kubernetes.io/cluster/development
          Value: shared
        - Key: Name
          Value: !Sub '${AWS::StackName}/CoreDnsFargatePrivateSubnet2'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dca59765-71ff-47af-88a5-f00c2d212b60
  CoreDnsFargatePrivateSubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref EksRouteTableForPrivateSubnet
      SubnetId: !Ref CoreDnsFargatePrivateSubnet2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 42bea788-7ea0-4f07-9957-1a9ff4f94d9d
  CoreDnsFargatePodExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks-fargate-pods.amazonaws.com
                - eks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 12506953-4dd0-4cb3-90b0-09ba7939f451
  EksVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: vpc
          Value: eks-in-vpc
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 44282776-46d6-46df-868b-028fee486a0e
  EksPrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: EksVPC
      CidrBlock: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - 2aCIDR
      AvailabilityZone: !Select 
        - 0
        - 'Fn::GetAZs': ''
      Tags:
        - Key: kubernetes.io/role/internal-elb
          Value: '1'
        - Key: Name
          Value: !Sub '${AWS::StackName}/PrivateSubnet1'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: be680f6b-59c3-4ecd-8494-d86e561635f0
  EksRouteTableForPrivateSubnet:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: EksVPC
      Tags:
        - Key: name
          Value: !Sub '${AWS::StackName}/EksRouteTableForPrivateSubnet'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7e460963-80ba-4089-b55c-2e939678fb1b
  NATPrivateSubnetRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
      RouteTableId: !Ref EksRouteTableForPrivateSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9f5dac91-d8e8-4985-b828-9373edea9a19
  EksPrivateSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref EksRouteTableForPrivateSubnet
      SubnetId: !Ref EksPrivateSubnet1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e976176a-8810-482b-b539-9156b466ca55
  NatIp:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/NatIp'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0160cfdb-2da9-4a92-a15f-2e60a647c581
  NatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt 
        - NatIp
        - AllocationId
      SubnetId: !Ref EksPublicSubnet2ContainsNat
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/NatGateway'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 56d0547a-0780-4212-a644-4d3b38fa409c
  EksPublicSubnet2ContainsNat:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: EksVPC
      CidrBlock: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - 2cCIDR
      AvailabilityZone: !Select 
        - 2
        - 'Fn::GetAZs': ''
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/EksPublicSubnet2ContainsNat'
        - Key: kubernetes.io/role/elb
          Value: '1'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3007d7d4-5a09-4db9-8ac9-ce137f8241d9
  EksPublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: EksVPC
      CidrBlock: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - 2bCIDR
      AvailabilityZone: !Select 
        - 1
        - 'Fn::GetAZs': ''
      MapPublicIpOnLaunch: true
      Tags:
        - Key: kubernetes.io/role/elb
          Value: '1'
        - Key: Name
          Value: !Sub '${AWS::StackName}/PublicSubnet1'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6932f9ba-7bba-462d-905f-26caa042b5bb
  EksPublicSubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId:
        Ref: EksPublicSubnet1
      RouteTableId:
        Ref: EksRouteTableForPublicSubnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 27d0f21c-daa9-4737-8e5d-f3814ce23b49
  EksRouteTableForPublicSubnet:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: EksVPC
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/EksRouteTableForPrivateSubnet'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 807654ce-b4e7-481d-b0c2-c7e0b302dfbb
  PublicSubnetRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref EksInternetGateway
      RouteTableId: !Ref EksRouteTableForPublicSubnet
    DependsOn:
      - EksVPCGatewayAttachment
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ee1a0123-4254-4fba-89aa-4bc10c9fdeaf
  EksInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/EksInternetGateway'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5430d3bb-56a3-4928-8978-0897525879b9
  EksVPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref EksInternetGateway
      VpcId: !Ref EksVPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2b95a84d-5405-44cf-809b-780d831d9f84
  EksClusterRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
                - eks-fargate-pods.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKSVPCResourceController'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 83a3f76f-49ce-41f7-a525-f733ed603a58
  EksCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: development
      Version: '1.17'
      RoleArn:
        'Fn::GetAtt':
          - EksClusterRole
          - Arn
      ResourcesVpcConfig:
        SubnetIds:
          - Ref: EksPrivateSubnet1
          - Ref: EksPublicSubnet1
          - Ref: CoreDnsFargatePrivateSubnet1
          - Ref: CoreDnsFargatePrivateSubnet2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 44b80cd0-fddd-42c9-a0a0-51d92df3d153
Outputs:
  EksClusterName:
    Description: Name of the cluster as resource
    Value: !Ref EksCluster
    Export:
      Name: !Sub '${AWS::StackName}-EksClusterName'
  EksVpcId:
    Description: eks vpc id
    Value: !Ref EksVPC
    Export:
      Name: !Sub '${AWS::StackName}-EksVpcId'
  WorkerNodesSubnetsIds:
    Description: private Subnets for worker nodes
    Value: !Ref EksPrivateSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-WorkerNodesSubnetsIds'
  EksVpcCidr:
    Description: eks vpc CidrBlock
    Value: !GetAtt EksVPC.CidrBlock
    Export:
      Name: !Sub '${AWS::StackName}-EksVpcCidr'
  NatGatewayId:
    Description: nat gateway id
    Value: !Ref NatGateway
    Export:
      Name: !Sub '${AWS::StackName}-NatGatewayId'
  EksRouteTableForPrivateSubnetId:
    Description: 'eks route table id, the route table is for private subnet'
    Value: !Ref EksRouteTableForPrivateSubnet
    Export:
      Name: !Sub '${AWS::StackName}-EksRouteTableForPrivateSubnetId'
Metadata:
  'AWS::CloudFormation::Designer':
    83a3f76f-49ce-41f7-a525-f733ed603a58:
      size:
        width: 60
        height: 60
      position:
        x: 990
        'y': 90
      z: 1
      embeds: []
    5430d3bb-56a3-4928-8978-0897525879b9:
      size:
        width: 60
        height: 60
      position:
        x: 980
        'y': 200
      z: 1
      embeds: []
    0160cfdb-2da9-4a92-a15f-2e60a647c581:
      size:
        width: 60
        height: 60
      position:
        x: 990
        'y': 330
      z: 1
      embeds: []
    44282776-46d6-46df-868b-028fee486a0e:
      size:
        width: 870
        height: 870
      position:
        x: 60
        'y': 90
      z: 1
      embeds:
        - 807654ce-b4e7-481d-b0c2-c7e0b302dfbb
        - 6932f9ba-7bba-462d-905f-26caa042b5bb
        - 3007d7d4-5a09-4db9-8ac9-ce137f8241d9
        - 7e460963-80ba-4089-b55c-2e939678fb1b
        - be680f6b-59c3-4ecd-8494-d86e561635f0
        - dca59765-71ff-47af-88a5-f00c2d212b60
        - 0edbeb74-5856-400e-b916-335c6cc3c09a
    2b95a84d-5405-44cf-809b-780d831d9f84:
      source:
        id: 44282776-46d6-46df-868b-028fee486a0e
      target:
        id: 5430d3bb-56a3-4928-8978-0897525879b9
      z: 1
    807654ce-b4e7-481d-b0c2-c7e0b302dfbb:
      size:
        width: 240
        height: 240
      position:
        x: 90
        'y': 450
      z: 2
      parent: 44282776-46d6-46df-868b-028fee486a0e
      embeds:
        - ee1a0123-4254-4fba-89aa-4bc10c9fdeaf
      iscontainedinside:
        - 44282776-46d6-46df-868b-028fee486a0e
        - 44282776-46d6-46df-868b-028fee486a0e
    ee1a0123-4254-4fba-89aa-4bc10c9fdeaf:
      size:
        width: 60
        height: 60
      position:
        x: 120
        'y': 510
      z: 3
      parent: 807654ce-b4e7-481d-b0c2-c7e0b302dfbb
      embeds: []
      isassociatedwith:
        - 5430d3bb-56a3-4928-8978-0897525879b9
      iscontainedinside:
        - 807654ce-b4e7-481d-b0c2-c7e0b302dfbb
        - 807654ce-b4e7-481d-b0c2-c7e0b302dfbb
      dependson:
        - 2b95a84d-5405-44cf-809b-780d831d9f84
    6932f9ba-7bba-462d-905f-26caa042b5bb:
      size:
        width: 150
        height: 150
      position:
        x: 390
        'y': 660
      z: 2
      parent: 44282776-46d6-46df-868b-028fee486a0e
      embeds: []
      iscontainedinside:
        - 44282776-46d6-46df-868b-028fee486a0e
        - 44282776-46d6-46df-868b-028fee486a0e
    27d0f21c-daa9-4737-8e5d-f3814ce23b49:
      source:
        id: 807654ce-b4e7-481d-b0c2-c7e0b302dfbb
      target:
        id: 6932f9ba-7bba-462d-905f-26caa042b5bb
      z: 2
    3007d7d4-5a09-4db9-8ac9-ce137f8241d9:
      size:
        width: 240
        height: 240
      position:
        x: 390
        'y': 150
      z: 2
      parent: 44282776-46d6-46df-868b-028fee486a0e
      embeds:
        - 56d0547a-0780-4212-a644-4d3b38fa409c
      iscontainedinside:
        - 44282776-46d6-46df-868b-028fee486a0e
        - 44282776-46d6-46df-868b-028fee486a0e
    56d0547a-0780-4212-a644-4d3b38fa409c:
      size:
        width: 60
        height: 60
      position:
        x: 420
        'y': 210
      z: 3
      parent: 3007d7d4-5a09-4db9-8ac9-ce137f8241d9
      embeds: []
      iscontainedinside:
        - 3007d7d4-5a09-4db9-8ac9-ce137f8241d9
        - 3007d7d4-5a09-4db9-8ac9-ce137f8241d9
    7e460963-80ba-4089-b55c-2e939678fb1b:
      size:
        width: 240
        height: 240
      position:
        x: 90
        'y': 150
      z: 2
      parent: 44282776-46d6-46df-868b-028fee486a0e
      embeds:
        - 9f5dac91-d8e8-4985-b828-9373edea9a19
      iscontainedinside:
        - 44282776-46d6-46df-868b-028fee486a0e
        - 44282776-46d6-46df-868b-028fee486a0e
    9f5dac91-d8e8-4985-b828-9373edea9a19:
      size:
        width: 60
        height: 60
      position:
        x: 120
        'y': 210
      z: 3
      parent: 7e460963-80ba-4089-b55c-2e939678fb1b
      embeds: []
      isassociatedwith:
        - 56d0547a-0780-4212-a644-4d3b38fa409c
      iscontainedinside:
        - 7e460963-80ba-4089-b55c-2e939678fb1b
        - 7e460963-80ba-4089-b55c-2e939678fb1b
    be680f6b-59c3-4ecd-8494-d86e561635f0:
      size:
        width: 150
        height: 150
      position:
        x: 690
        'y': 150
      z: 2
      parent: 44282776-46d6-46df-868b-028fee486a0e
      embeds: []
      iscontainedinside:
        - 44282776-46d6-46df-868b-028fee486a0e
        - 44282776-46d6-46df-868b-028fee486a0e
    e976176a-8810-482b-b539-9156b466ca55:
      source:
        id: 7e460963-80ba-4089-b55c-2e939678fb1b
      target:
        id: be680f6b-59c3-4ecd-8494-d86e561635f0
      z: 2
    12506953-4dd0-4cb3-90b0-09ba7939f451:
      size:
        width: 60
        height: 60
      position:
        x: 990
        'y': 450
      z: 1
      embeds: []
    dca59765-71ff-47af-88a5-f00c2d212b60:
      size:
        width: 150
        height: 150
      position:
        x: 600
        'y': 450
      z: 2
      parent: 44282776-46d6-46df-868b-028fee486a0e
      embeds: []
      iscontainedinside:
        - 44282776-46d6-46df-868b-028fee486a0e
        - 44282776-46d6-46df-868b-028fee486a0e
    42bea788-7ea0-4f07-9957-1a9ff4f94d9d:
      source:
        id: 7e460963-80ba-4089-b55c-2e939678fb1b
      target:
        id: dca59765-71ff-47af-88a5-f00c2d212b60
      z: 2
    0edbeb74-5856-400e-b916-335c6cc3c09a:
      size:
        width: 150
        height: 150
      position:
        x: 390
        'y': 450
      z: 2
      parent: 44282776-46d6-46df-868b-028fee486a0e
      embeds: []
      iscontainedinside:
        - 44282776-46d6-46df-868b-028fee486a0e
        - 44282776-46d6-46df-868b-028fee486a0e
    44b80cd0-fddd-42c9-a0a0-51d92df3d153:
      size:
        width: 60
        height: 60
      position:
        x: 990
        'y': 570
      z: 1
      embeds: []
    6707c63e-ecbe-4b13-92f5-c0da20bd9436:
      source:
        id: 7e460963-80ba-4089-b55c-2e939678fb1b
      target:
        id: 0edbeb74-5856-400e-b916-335c6cc3c09a
      z: 2

**Comment by taotao1995** [comment]
I manually created the managed node group in a private subnet, which is connected with the cluster. And I expect that the group in the private subnet will talk through the NAT to the public internet. And the cluster should be able to detect the node group.

**Comment by iliapolo** [comment]
What happens here is that the `vpc_subnets` property doesn't actually determine the subnets of the node group, it is only used for the subnets of the control plane (i.e the cluster itself). 

The subnets of node groups are determined via its own [`subnets`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.NodegroupProps.html#subnets) property. The kink here is that when a cluster is initialized, it also creates a default node group, but doesn't expose an option to set its subnets, which means that the [default selection mechanism](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/vpc.ts#L534) is applied.

This mechanism will select the first type of `PRIVATE`, `ISOLATED`, `PUBLIC` (in that order) that has any subnets. So in this case, it selects `ISOLATED`. 

To address this, you'd need to instantiate the cluster without any capacity, and add it afterwards, specifying the correct subnets. 

```ts
const vpc = new ec2.Vpc(this, 'Vpc', {
  subnetConfiguration: [
    {
      name: 'DB',
      subnetType: ec2.SubnetType.ISOLATED,
      cidrMask: 21,
    },
    {
      name: 'Cluster',
      subnetType: ec2.SubnetType.PUBLIC,
      cidrMask: 21,
    }
  ]
});

const cluster = new eks.Cluster(this, 'Cluster', {
  version: eks.KubernetesVersion.V1_18,
  defaultCapacity: 0,
  vpc,
  vpcSubnets: [{ subnetType: ec2.SubnetType.PUBLIC }]
});

cluster.addNodegroupCapacity('node-group', {
  subnets: { subnetType: ec2.SubnetType.PUBLIC },      
});
```
