### ISSUE TITLE
Tags not applied in aspects in 1.45

### ISSUE THREAD

**Issue by henrist** [aws/aws-cdk#8536]
I have an aspect to add tags to all resources in the app.

It worked in 1.44, but in 1.45 tags are not added.

### Reproduction Steps

```ts
app.node.applyAspect({
  visit(construct: cdk.IConstruct) {
    if (cdk.Construct.isConstruct(construct)) {
      const stack = construct.node.scopes.find((it): it is cdk.Stack =>
        cdk.Stack.isStack(it),
      )
      if (stack != null) {
        console.info("Adding tag")
        cdk.Tag.add(construct, "Test", "Value")
      }
    }
  },
})
```

No tag added. Full reproduction repo from sample-app: https://github.com/henrist/cdk-aspect-tag-issue - the commits shows it working in 1.44 before not producing tags in 1.45.

### Error Log

No error seen. However, the log statement shown above is triggered, so the cdk.Tag.add is called.

### Environment

  - **CLI Version      :** 1.45
  - **Framework Version:** 1.45
  - **Node.js Version:**  v12.13.0
  - **OS               :** Arch Linux
  - **Language (Version):**  TypeScript, not tested other

### Other

The same code worked fine in 1.44, but no tags are emitted in 1.45.

In our setup I have a helper to simplify this found at https://github.com/capralifecycle/liflig-cdk/blob/9032da75b67d4d5ffa1b518034cf3150091c398a/src/tags.ts

We commit snapshots of the templates in the Cloud Assembly, which led us to catch this during update to 1.45.

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
Hi!

Tags are implemented using aspects, so in the code you pasted, which uses aspects to tag constructs you are actually applying an aspect via an aspect, this was never truly in the CDK and would only work in very specific cases,  depending on the order in which the construct tree was built. 
We did introduce a [change](https://github.com/aws/aws-cdk/pull/8423) to the CDK in `v1.45.0` that might have changed this behavior. 

While we investigate this,  it seems like you are trying to tag all constructs which are defined inside a stack? If so, could you try applying the tag on the stacks? Let me know if I missed something in the use case you are trying to achieve.

**Comment by henrist** [comment]
> While we investigate this, it seems like you are trying to tag all constructs which are defined inside a stack? If so, could you instead add the tag to the stacks? Let me know if I missed something in your use case.

What I am trying to achieve is to tag all resources in the application, without having to change the stacks or maintain an extra statement per stack. The tag value also includes the stack name, or otherwise I could have worked around this by `cdk.Tag.add(app, "Name", "Value")` at the end.

Maybe there should be some error if an aspect is applied while already applying a aspect?

For my use case I can probably solve this by creating a custom Tag implementation.

**Comment by henrist** [comment]
I've worked around this by avoiding the nested aspects (by using `construct.tags.setTag` directly, as seen in the linked commit). For my part I'm fine with closing this as wont-fix (unsupported).

**Comment by NetaNir** [comment]
Im glad to hear you found a workaround, Im closing this in favor of https://github.com/aws/aws-cdk/pull/8639
