### ISSUE TITLE
Bucket multiple notifications

### ISSUE THREAD

**Issue by IndikaUdagedara** [aws/aws-cdk#8538]
I'm trying to subscribe a lambda function to multiple prefixes in a single bucket. But `bucket.addEventNotification()` throws the following error. Bucket and lambda functions are created in the same stack. 

### Reproduction Steps

```
    const bucket = new s3.Bucket(...)
    const lambda = new lambda.SingletonFunction(...)
    
    const lambdaDestination = new s3n.LambdaDestination(lambda);
    
    bucket.addEventNotification(s3.EventType.OBJECT_CREATED, lambdaDestination, { prefix: "v1/"})
    bucket.addEventNotification(s3.EventType.OBJECT_CREATED, lambdaDestination, { prefix: "v2/"})

```

### Error Log
`cdk synth` returns the error:

`There is already a Construct with name 'AllowBucketNotificationsFromBucket3E8F7BBA' in Function [SingletonLambda8d4cbf0bc03e4460b43ab4696174d04b`

Verbose output:
```
$ npm run build && npm run cdk synth -- -v

  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '5.0.0',
  CDK_CLI_VERSION: '1.45.0' }
There is already a Construct with name 'AllowBucketNotificationsFromBucket3E8F7BBA' in Function [SingletonLambda8d4cbf0bc03e4460b43ab4696174d04b]
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.proc.on.code (/mnt/c/Repos/geku/RedenlabPlatform/deploy/cdk/node_modules/aws-cdk/lib/api/cxapp/exec.ts:118:23)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

### Environment

  - **CLI Version      :**1.45
  - **Framework Version:**1.45
  - **Node.js Version:** 10.20
  - **OS               :**Linux
  - **Language (Version):** TypeScript

### Other

It's not clear why multiple notifications aren't allowed. Seems the error is due the same lambda permission being created for both notifications. I suppose I could work around this by creating 2 lambda functions with the same code (didn't try) but I'd prefer to have a single lambda function so monitoring etc. becomes simpler. 

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @IndikaUdagedara - Thanks for reporting this!

Definitely looks like a bug. Adding to our docket 👍
