### ISSUE TITLE
custom-resources-readme.html link problems

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#8539]
In the documentation on https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html there are two links:

test/provider-framework/integration-test-fixtures/s3-file.ts
test/provider-framework/integration-test-fixtures/s3-file-handler/index.ts

both of them dont work in the browser. The files are both in the repo and from the README, the links should be ok wrt to the folder structure, but somehow they dont work.

The related text is:

"Provisions an object in an S3 bucket with textual contents. See the source code for the construct and handler."

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @logemann, thanks for noticing this and notifying us, much appreciated! 👍 
I will put in a fix.
