### ISSUE TITLE
ContainerImage.fromAsset in new asset system after 1.45

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#8540]
When using ContainerImage.fromAsset the generated CFN template looks like this:

```
            "Image": {
              "Fn::Sub": {
                "Fn::Join": [
                  "",
                  [
                    "<id>.dkr.ecr.eu-central-1.",
                    {
                      "Ref": "AWS::URLSuffix"
                    },
                    "/cdk-<my-asset-ecr>:<hash>"
                  ]
                ]
              }
            },
```
This is invalid CloudFormation as Join is not valid inside Sub:

E1019 Sub should be a string or array of 2 items for Resources/TaskDef3BF4F22B/Properties/ContainerDefinitions/0/Image/Fn::Sub

The problem might be here https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts#L281 as it creates an `Fn::Sub` containing an `Fn::Join` which is not valid.

@rix0rrr see https://github.com/aws/aws-cdk/issues/3463#issuecomment-643502229

### Reproduction Steps

Use any `ContainerImage.fromAsset`

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:** 1.45.0
  - **Node.js Version:** v14
  - **OS               :** MacOS
  - **Language (Version):** TypeScript

--- 

This is :bug: Bug Report

**Comment by agdimech** [comment]
+1 - Confirm this is happening for me also.
