### ISSUE TITLE
Improve build performance of NodejsFunction on Mac (@aws-cdk/aws-lambda-nodejs package)

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#8544]
Using volumes in Docker on Mac specifically is a huge pain point due to performance issues. CPU often spikes to above 100% utilization when there is heavy read or write operations inside the container (as it happens with the `parcel-builder` Docker container that the CDK construct NodejsFunction uses internally.

This has been very well documented in https://docs.docker.com/docker-for-mac/osxfs-caching/ and the workarounds are also described.

I suggest we force Docker volume mounts within this construct to start using Docker volume in "delegated" mode, to improve build performance (speed) on Mac based deployment environments.

I think a good starting point is:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-nodejs/lib/builder.ts#L118

### Use Case
Developing and deploying CDK stacks with many lambdas on a Mac machine.

### Proposed Solution
Replace `-v sourcevolume:targetvolume` with `-v sourcevolume:targetvolume:delegated`

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
@Dzhuneyt would this apply to other OS as well? Can you propose the change in `core` (`lambda-nodejs` is going to be refactored to use the bundling in `core`)? Should be an option in `DockerVolume`:

https://github.com/aws/aws-cdk/blob/4521ae3734f7e76c864d2b883fc290091b5fcf3d/packages/%40aws-cdk/core/lib/bundling.ts#L128-L131

cc @eladb

**Comment by Dzhuneyt** [comment]
Other OSs don't suffer from this performance issue and the ":cached" or ":delegated" flag is a no-op for them.

**Comment by Dzhuneyt** [comment]
@jogold could you point me to another GitHub issue or a place where I can learn more about this upcoming refactoring? Regardless, I think this fix should go forward with the current implementation until such refactoring happens (because it's tiny and the benefit for developers that use MacOS as a dev env of choice are pretty obvious).

**Comment by jogold** [comment]
> @jogold could you point me to another GitHub issue or a place where I can learn more about this upcoming refactoring?

Not opened yet, will try to start the discussion in an issue/PR this week or next week.

**Comment by moltar** [comment]
Is there a reason why it runs inside a Docker container anyways? Seems to be a bit heavy handed. I think there should be an option to run it locally.

**Comment by jogold** [comment]
@Dzhuneyt see #8576 



> Is there a reason why it runs inside a Docker container anyways?

See **Why we use Docker?** in https://github.com/aws/aws-cdk/issues/8460
See also https://github.com/aws/aws-cdk-rfcs/issues/7

**Comment by Dzhuneyt** [comment]
@jogold I plan on working on the implementation in "core" at some point. Does this mean this PR is unnecessary? Personally, I still see value in it being pushed live until such refactoring comes into effect, but the decision is with you.

**Comment by Dzhuneyt** [comment]
> @Dzhuneyt would this apply to other OS as well? Can you propose the change in `core` (`lambda-nodejs` is going to be refactored to use the bundling in `core`)? Should be an option in `DockerVolume`:
> 
> https://github.com/aws/aws-cdk/blob/4521ae3734f7e76c864d2b883fc290091b5fcf3d/packages/%40aws-cdk/core/lib/bundling.ts#L128-L131
> 
> cc @eladb

Has any work started on this part "lambda-nodejs is going to be refactored to use the bundling in core"?

**Comment by jogold** [comment]
@Dzhuneyt #8576 has been merged, `lambda-nodejs` now uses the bundling from `core`.

**Comment by jogold** [comment]
@Dzhuneyt do you still want to propose this change? Let met know if you need some help.

**Comment by Dzhuneyt** [comment]
Yes, I will try to implement this. It's my first major contribution to AWS CDK, so I might need some guidance. I'll write here if i need any help.
