### ISSUE TITLE
multi_az_enabled is missing for elasticache.CfnReplicationGroup

### ISSUE THREAD

**Issue by arestuzi** [aws/aws-cdk#8545]
Environement: Python 3.7 CDK 1.45.0

I am using CDK (Cloud Development Kit) for ElastiCache Redis development. However, when
I am trying to add "'multi_az_enabled" to "CfnReplicationGroup"

```
case_redis = elasticache.CfnReplicationGroup(
self, "case_Test_CDK", engine="redis", engine_version="5.0.6", cache_node_type="cache.m4.large", num_cache_clusters=2,
automatic_failover_enabled=True, replication_group_description="test for sumsang", multi_az_enabled=True)
```

It will return following errors:
```
(node:3476) ExperimentalWarning: The fs.promises API is experimental
Traceback (most recent call last):
File "app.py", line 10, in <module>
Ec2CloudwatchStack(app, "ec2-cloudwatch", env=env)
File "C:\Users\Administrator\Desktop\CDKexample\CDK-example\aws-cdk-examples\python\ec2-cloudwatch\.env\lib\site-packages\jsii\_runtime.py", line 66, in __call__
inst = super().__call__(*args, **kwargs)
File "C:\Users\Administrator\Desktop\CDKexample\CDK-example\aws-cdk-examples\python\ec2-cloudwatch\ec2_cloudwatch\ec2_cloudwatch_stack.py", line 77, in __init__
automatic_failover_enabled=True, replication_group_description="test for teli", multi_az_enabled=True)
File "C:\Users\Administrator\Desktop\CDKexample\CDK-example\aws-cdk-examples\python\ec2-cloudwatch\.env\lib\site-packages\jsii\_runtime.py", line 66, in __call__
inst = super().__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'multi_az_enabled'
Subprocess exited with error 1
```

I checked boto3, which already has "MultiAZEnabled=True"
doc:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elasticache.html?highlight=elasticache#ElastiCache.Client.create_replication_group

And I also tested to add "MultiAZEnabled=True" to CloudFormation Template, it works well.

Action Required:
Add multi_az_enabled option to CDK typescript SDK.

**Comment by RomainMuller** [comment]
According to the [CloudFormation docs](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html) as of writing, there is no `MultiAZEnabled` property on the `AWS::ElastiCache::ReplicationGroup` resource type. CDK cannot support this feature until CloudFormation does (at which point CDK should have the feature on the `CfnReplicationGroup` class shortly after the CloudFormation resource specification has it published)

**Comment by RomainMuller** [comment]
In the meantime, assuming the CloudFormation resource *already* supports the feature (but the Spec does not reflect that just yet - in this case it's typically just the matter of a couple of days), you can "patch" up your resource using the following:

```py
case_redis.add_property_override('MultiAZEnabled', 'true')
```

**Comment by peterwoodworth** [comment]
This feature is now supported so I'll be closing this.
