### ISSUE TITLE
SQS - Unknown Attribute FifoQueue when setting fifo to false in Queue Props

### ISSUE THREAD

**Issue by HassanMahmud** [aws/aws-cdk#8550]
Setting fifo to false in QueueProps when creating an SQS queue causes the deploy to fail. 

### Reproduction Steps
This is the code used to create the queue. It is part of a reusable component, I have made a workaround of only setting the fifo prop if it is set to true and everything works as expected.
```
return new sqs.Queue(stack, name, {
      encryption: encrypted ? sqs.QueueEncryption.KMS_MANAGED : sqs.QueueEncryption.UNENCRYPTED,
      fifo,
      queueName: name,
      retentionPeriod,
      visibilityTimeout
    });
```
### Error Log
This error shows up under CloudFormation events as the reason why creating the queue failed.
Unknown Attribute FifoQueue. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidAttributeName; Request ID: <REQUEST_ID>)

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:** 1.45.0
  - **Node.js Version:** v14.3.0
  - **OS               :** macOS Catalina v10.15.15
  - **Language (Version):** TypeScript (^3.9.5)

### Other
I found a similar issue report here: [AWS PHP SDK Github issue](https://github.com/aws/aws-sdk-php/issues/1331)

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
Hey there. Looks like this is a known issue with cloudformation. They have an [issue in their roadmap](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/165) for it.

We can potentially perform some logic inside of the construct to pass `undefined` to the L1 when the user passes `false` to cover this from our side. I can't imagine that causing any conflicts in the future. @eladb opinions on diverging from CFN here to prevent this error? Should be non-breaking as far as I can tell.

**Comment by suankan** [comment]
I've just bumped into this issue as well.

It would make a lot of sense to reflect this in the docs.
Currently docs for interface QueueProps reads: `fifo? | boolean`.
Would be better to make it some enum like `true` or `undefined`.

**Comment by bitsofinfo** [comment]
experience same

**Comment by ParallelPlatypus** [comment]
bump - same issue, in python 3.7 using:
```Python
 self._queue=sqs.Queue(
            scope, 
            QUEUE_ID_PREFIX + name, 
            fifo=True if FIFO_ENABLED else None,
            removal_policy=REMOVAL_POLICY
        )
```
fixed this for me.

**Comment by JordanRickman** [comment]
same, Python 3.9

**Comment by z00dev** [comment]
Had the same issue, python 3.9, still unclear that it needs None

**Comment by noam-alchemy** [comment]
Seeing this as well in typescript.

**Comment by cdstamper** [comment]
Seeing this as well. The documentation is **literally incorrect** in claiming that FifoQueue is boolean.

**Comment by jmurzy** [comment]
Same issue when `contentBasedDeduplication=false`.

**Comment by wilhen01** [comment]
Just encountered this in CDK v2 using Typescript. Agree with comments elsewhere in the thread - update docs and/or make this an enum of `true | undefined`. Minor issue but easily fixed.

**Comment by gwin003** [comment]
Also ran into this in CDK v2 Typescript. Not exactly the same issue since my FifoQueue is currently always `false`, but I just removed the property altogether and it solved my issue.

**Comment by JussiLem** [comment]
Hello. Saw the same issue here and yeah removing the property helps, but still confusing

**Comment by mtp1376** [comment]
So if it's not `true`, then it should be `undefined`. Got it. Thanks for the great API design and keeping it like this since 2020.

**Comment by pietrorea** [comment]
I also ran into this issue. I see that it's been open for almost 2 years

**Comment by peterwoodworth** [comment]
It appears this issue has moved to `Coming Soon` on the CloudFormation roadmap. We should continue to wait for CloudFormation to push this as it appears the wait will not be much longer

**Comment by cyber-gh** [comment]
Workaround in Typescript CDK

```
const additionalProperties = props.fifo
            ? {
                  fifo: true,
              }
            : {};

queue = new aws_sqs.Queue(this, `SomeQueue`, {
            queueName: name,
            ...additionalProperties
})
```

**Comment by mappingvermont** [comment]
Any movement on this?

**Comment by matt-challe** [comment]
Bump, same issue. Fixed using @ParallelPlatypus's method (thank you!)
`fifo=True if fifo_enabled==True else None`

**Comment by lennard0011** [comment]
Bump, had to remove the property `fifo` as it was set to `false`. Can we get an ETA when this is resolved in CDK?
