### ISSUE TITLE
Deploy previously created changeset

### ISSUE THREAD

**Issue by Guitarkalle** [aws/aws-cdk#8567]
It would be nice to be able to execute a changeset that was previously created with the `cdk deploy --no-execute` command. Especially in a CI flow.

For example:
```
STACK_INFO = cdk deploy --no-execute
// see #601 for better output from the CLI also
// let's assume you can get the stack id, change set name etc back from the cli. Currently you have to parse it from the output so it's possible one way or another

// go look at the changeset manually

// proceed to execute
// we got the change_set_id somehow, from parsing the output or from the future added STACK_INFO variable
cdk deploy --execute CHANGE_SET_ID
```

### Use Case

In a CI flow it would be nice to be able to create the change set and look at it, but then also execute the same change set with the tool. Now you have to do a new deploy which creates another change set, which theoretically will be the same as the one created with --no-execute but it would feel better if you could execute the same one.

### Proposed Solution

Add an optional parameter to the execute flag or a new flag which takes the CHANGE_SET_NAME or ID that was created previosuly

### Other

N/A

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
At that point CDK CLI would just be a deployment monitor. Might be useful, but not something we'll likely address.
