### ISSUE TITLE
ec2: allow importing a VPC from CFN parameters

### ISSUE THREAD

**Issue by nicl** [aws/aws-cdk#8568]
Unable to use parameter to set subnets for an imported VPC.

### Reproduction Steps

```
    const publicSubnets = new cdk.CfnParameter(this, "Subnets", {
      type: "List<AWS::EC2::Subnet::Id>",
      description: "Subnets where instances will run",
    });

    const vpc = ec2.Vpc.fromVpcAttributes(this, "vpc", {
      vpcId: vpcId.valueAsString,
      availabilityZones: this.availabilityZones,
      publicSubnetIds: publicSubnets.valueAsList,
    });
```

### Error Log

`Number of publicSubnetIds (1) must be a multiple of availability zones (2)`

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:** ???
  - **Node.js Version:** 
  - **OS               :** 12.14
  - **Language (Version):**  Typescript

### Other

This is desirable as it seems like a common use case when importing a VPC to want to parameterise things as well.

--- 

This is :bug: Bug Report

**Comment by nicl** [comment]
Just as a comment for anyone encountering the same, a 'fix' is to parameterise the AZs too:

```
    const availabilityZones = new cdk.CfnParameter(this, "AZs", {
      type: "List<AWS::EC2::AvailabilityZone::Name>",
      description: "List of AZs",
    });

    const vpc = ec2.Vpc.fromVpcAttributes(this, "vpc", {
      vpcId: vpcId.valueAsString,
      availabilityZones: availabilityZones.valueAsList,
      publicSubnetIds: publicSubnets.valueAsList,
    });
```

**Comment by rix0rrr** [comment]
I agree that this doesn't work very well, but I'm going to mark it as a feature request.
