### ISSUE TITLE
How to export and import class over 2 different file, Guidance needed.

### ISSUE THREAD

**Issue by ookangzheng** [aws/aws-cdk#8569]
### The Question
Is there any way to split over 2 file which only contain `IAM.ts` policy, the other contain `Lambda.ts`. Lambda role gonna import from `IAM.ts`.  (I'm newbie in Typescript... thanks)

**IAM.ts**
```javascript
import * as cdk from '@aws-cdk/core';
import * as iam from '@aws-cdk/aws-iam';

export interface IAMProps extends cdk.StackProps {
  BridgeApiLambdaExecutionRole?: iam.Role;
  BridgeApiLambdaUtilsRole?: iam.Role;
}

export class IAM extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: IAMProps) {
    super(scope, id, props);
    const BridgeApiLambdaExecutionRole = new iam.Role(
      this,
      'BridgeApiLambdaRole',
      {
        roleName: `BridgeApiLambdaExecutionRole`,
        assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
        managedPolicies: [
          iam.ManagedPolicy.fromAwsManagedPolicyName(
            'service-role/AWSLambdaVPCAccessExecutionRole',
          ),
        ],
      },
    );

    const Lambda_KMS_Policy = new iam.Policy(this, 'LambdaKMSPolicy', {
      policyName: `BridgeKMS`,
      roles: [BridgeApiLambdaExecutionRole],
      statements: [
        new iam.PolicyStatement({
          resources: ['*'],
          actions: [
            'kms:DescribeKey',
            'kms:GetPublicKey',
            'kms:Sign',
            'kms:Verify',
          ],
        }),
      ],
    });


```

**Lambda.ts**
```javascript
import * as IAM from './IAM.ts';
export class ApiV2 extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const utilSbToBe = new lambda.Function(this, 'utilSbToBe', {
      functionName: `utilSbToBe`,
      runtime: lambda.Runtime.NODEJS_10_X,
      role: IAM.BridgeApiLambdaExecutionRole, // <-- Is it possible ?????
      code: lambda.AssetCode.fromAsset('../source'),
      handler: 'entry_point/util_sb_to_beneficiary.handler',
    });

  }
}
```

### Environment

  - **CDK CLI Version:** 1.45.0
  - **Node.js Version:** v14.4.0
  - **OS:**  OSX Catalinaa
  - **Language (Version):** TypeScript (3.8.3)

**Comment by ookangzheng** [comment]
🍻

**Comment by ookangzheng** [comment]
Thanks for your help.

**Comment by nkumarkr01** [comment]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

> Hey @ookangzheng,
> 
> Sorry for the delay in response. Not sure if you are still struggling with this, but it appears you are trying to split your stack into constructs. I recommend you read through the [authoring constructs](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_author) section of our developer guide for more detailed information.
> 
> Given the example code though, I would recommend you do the following.
> 
> **IAM.ts**
> 
> ```ts
> import * as cdk from '@aws-cdk/core';
> import * as iam from '@aws-cdk/aws-iam';
> 
> export class IAM extends cdk.Construct { // <-- Notice we are inheriting Construct rather than stack
>   public readonly BridgeApiLambdaExecutionRole: iam.Role;
>   public readonly BridgeApiLambdaUtilsRole: iam.Role;
> 
>   constructor(scope: cdk.Construct, id: string, props?: IAMProps) {
>     super(scope, id, props);
>    BridgeApiLambdaExecutionRole = new iam.Role(
>       this,
>       'BridgeApiLambdaRole',
>       {
>         roleName: `BridgeApiLambdaExecutionRole`,
>         assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
>         managedPolicies: [
>           iam.ManagedPolicy.fromAwsManagedPolicyName(
>             'service-role/AWSLambdaVPCAccessExecutionRole',
>           ),
>         ],
>       },
>     );
> 
>    Lambda_KMS_Policy = new iam.Policy(this, 'LambdaKMSPolicy', {
>       policyName: `BridgeKMS`,
>       roles: [BridgeApiLambdaExecutionRole],
>       statements: [
>         new iam.PolicyStatement({
>           resources: ['*'],
>           actions: [
>             'kms:DescribeKey',
>             'kms:GetPublicKey',
>             'kms:Sign',
>             'kms:Verify',
>           ],
>         }),
>       ],
>     });
> ```
> 
> This is because `props` are designed to represent the inputs for your given stack or construct. Sharing values outside of said construct is better done with `public readonly` values (that way they are exposed, but immutable after initialization.
> 
> You can then use the construct like follows:
> 
> **Lambda.ts**
> 
> ```ts
> import * as IAM from './IAM.ts';
> export class ApiV2 extends cdk.Stack {
>   constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
>     super(scope, id, props);
> 
> 	const iam = new IAM(this, 'CustomRoles');
> 
>     new lambda.Function(this, 'utilSbToBe', {
>       functionName: `utilSbToBe`,
>       runtime: lambda.Runtime.NODEJS_10_X,
>       role: iam.BridgeApiLambdaExecutionRole, // <-- Now its possible
>       code: lambda.AssetCode.fromAsset('../source'),
>       handler: 'entry_point/util_sb_to_beneficiary.handler',
>     });
> 
>   }
> }
> ```
> 
> Please let me know if you need any more help!
> 
> 😸 😷

The above code is ending with errors.
