### ISSUE TITLE
[aws-eks]: reliable nodegroup rolling update for EKS

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#8570]
## Background

Amazon EKS construct lib uses the latest Amazon EKS-optimized AMI from SSM parameter store by default. When newer AMI is available, `cdk deploy` will trigger the nodegroup rolling update, which imposes impact on the workload if the node draining is not well handled.

## Considered Solution(s)

The AutoscalingGroup lifecycle hook should invoke a handler for the node draining and continue to proceed the termination on instance drained.

## amazon-eks-serverless-drainer
https://github.com/awslabs/amazon-eks-serverless-drainer

amazon-eks-serverless-drainer leverages the kubectl lambda layer which we already have for the cluster resource creation. It should be not too difficult to integrate it into the eks cluster. The benefit is everything could be automatically configured behind the scene including the ASG lifecycle hooks.

## node-termination-handler
https://github.com/aws/aws-node-termination-handler

We already have this as a daemonset for spot instances in the self-managed nodegroup. Users may opt-in to deploy it on all instances including the ondemand. However, it looks like the node-termination-handler will not work with ASG lifecycle hook and this might be a risk. Another drawback is the node-termination-handler will cost one pod, and the max number of pod is limited for nodes running AWS VPC CNI.

Any comments or suggestions are welcome.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by RicoToothless** [comment]
sometimes we didn't know a small change will change all worker nodes' AMI. (`cdk diff` can't show AMI change)

Is there any way to improve this?

**Comment by pahud** [comment]
Close in favor of managed nodegroups.
