### ISSUE TITLE
cli: improve usability of --cloudformation-execution-policies

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#8571]
Deploy an app via new asset system `"@aws-cdk/core:newStyleStackSynthesis": true,`, got below errors,

```
6/22 | 5:39:27 PM | CREATE_FAILED        | AWS::IAM::Role                            | Nexus3-Execution-Role (Nexus3ExecutionRole7D7DCE03) API: iam:CreateRole User: arn:aws-cn:sts::034068960621:assumed-role/cdk-hnb659fds-cfn-exec-role-034068960621-cn-northwest-1/AWSCloudFormation is not authorized to perform: iam:CreateRole on resource: arn:aws-cn:iam::034068960621:role/EcsSonatypeNexus3Stack-Nexus3ExecutionRole7D7DCE03-PPD1G31B45J9
8/22 | 5:39:27 PM | CREATE_FAILED        | AWS::ECS::Cluster                         | Nexus3Cluster (Nexus3ClusterE4F27F99) User: arn:aws-cn:sts::034068960621:assumed-role/cdk-hnb659fds-cfn-exec-role-034068960621-cn-northwest-1/AWSCloudFormation is not authorized to perform: ecs:DescribeClusters on resource: arn:aws-cn:ecs:cn-northwest-1:034068960621:cluster/EcsSonatypeNexus3Stack-Nexus3ClusterE4F27F99-0FoUr3S2HsAt (Service: Ecs, Status Code: 400, Request ID: 204508a4-29cd-425c-9ec6-527464a04f9d)
9/22 | 5:39:40 PM | CREATE_FAILED        | AWS::EFS::FileSystem                      | Nexus3FileSystem (Nexus3FileSystemEFB61BFC) User: arn:aws-cn:sts::034068960621:assumed-role/cdk-hnb659fds-cfn-exec-role-034068960621-cn-northwest-1/AWSCloudFormation is not authorized to perform: elasticfilesystem:CreateFileSystem on the specified resource (Service: Efs, Status Code: 403, Request ID: a2f803d1-c166-45c2-84d6-d2e15c905025, Extended Request ID: null)
```

### Reproduction Steps

1. Specify the current aws profile via below env,
```
export AWS_DEFAULT_PROFILE=
```
2. enable new asset system in `cdk.json`
```
{
  "context": {
    "@aws-cdk/core:newStyleStackSynthesis": true
  }
}
```
3. Deploy the app `npx cdk deploy`

### Error Log

See above

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Did you bootstrap and passed `--cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess` to give sufficient permissions to the CloudFormation execution role?

**Comment by zxkane** [comment]
> Did you bootstrap and passed `--cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess` to give sufficient permissions to the CloudFormation execution role?

Yes. I did reran the bootstrap with new asset system via below command.

```
env CDK_NEW_BOOTSTRAP=1 npx cdk bootstrap \
  --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
```

I find the permission issue only happening when updating the existing stack `CDKToolkit`, the CloudFormationExecutionRole role `cdk-xxx-cfn-exec-role-<accountid>-ap-southeast-1` is not associated with the given policy `arn:aws:iam::aws:policy/AdministratorAccess`. I deleted the existing stack `CDKToolkit`, then bootstraping from scratching it works.

Also the bootstrap runs without error if I specify a non-existing policy `arn:aws:iam::aws:policy/AdministratorAccess` when bootstraping in China region. The ARN of administrator policy is `arn:aws-cn:iam::aws:policy/AdministratorAccess` in China region, it would be helpful printing out error message if the given policy does not exist or the permission of policy is insufficient for deploying cloudformation stack.

**Comment by rix0rrr** [comment]
Your last 2 concerns are hard to work around. IAM should validate whether the referenced policy exists, but apparently it doesn't.

Also, we have no way to know beforehand whether the given policy is going to give enough permissions, because we won't know what kind of permissions you need.

In some other environments you may legitimately want to use a narrower policy than `AdministratorAccess`.

**Comment by rix0rrr** [comment]
> I find the permission issue only happening when updating the existing stack `CDKToolkit`, the CloudFormationExecutionRole role `cdk-xxx-cfn-exec-role-<accountid>-ap-southeast-1` is not associated with the given policy `arn:aws:iam::aws:policy/AdministratorAccess`. I deleted the existing stack `CDKToolkit`, then bootstraping from scratching it works.

This is concerning to me, and goes against everything I thought I knew.

Can you reproduce this? If you bootstrap using the old stack and then upgrade, using the `--cloudformation-execution-policies` flag, and the policy is not attached? I'm asking because we have a test that does that and it works, so there must be something else going on in your environment.

**Comment by zxkane** [comment]
I can reproduce it if bootstrapping with enabling new asset system without specifying the arn of execution role in first time.

Then the `CDKToolkit` won't be updated after bootstrapping with specifying another execution role. 
```bash
env CDK_NEW_BOOTSTRAP=1 npx cdk bootstrap
 ⏳  Bootstrapping environment aws://034068960xxx/cn-north-1...
CDKToolkit: creating CloudFormation changeset...
  0/11 | 10:11:52 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole
  0/11 | 10:11:52 AM | CREATE_IN_PROGRESS   | AWS::ECR::Repository  | ContainerAssetsRepository
  0/11 | 10:11:52 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | CloudFormationExecutionRole
  0/11 | 10:11:52 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole
  0/11 | 10:11:52 AM | CREATE_IN_PROGRESS   | AWS::ECR::Repository  | ContainerAssetsRepository Resource creation Initiated
  0/11 | 10:11:52 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole Resource creation Initiated
  0/11 | 10:11:53 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | CloudFormationExecutionRole Resource creation Initiated
  1/11 | 10:11:53 AM | CREATE_COMPLETE      | AWS::ECR::Repository  | ContainerAssetsRepository
  1/11 | 10:11:53 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole Resource creation Initiated
  2/11 | 10:12:02 AM | CREATE_COMPLETE      | AWS::IAM::Role        | FilePublishingRole
  3/11 | 10:12:02 AM | CREATE_COMPLETE      | AWS::IAM::Role        | CloudFormationExecutionRole
  4/11 | 10:12:02 AM | CREATE_COMPLETE      | AWS::IAM::Role        | ImagePublishingRole
  4/11 | 10:12:04 AM | CREATE_IN_PROGRESS   | AWS::KMS::Key         | FileAssetsBucketEncryptionKey
  4/11 | 10:12:04 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | DeploymentActionRole
  4/11 | 10:12:04 AM | CREATE_IN_PROGRESS   | AWS::KMS::Key         | FileAssetsBucketEncryptionKey Resource creation Initiated
  4/11 | 10:12:04 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | DeploymentActionRole Resource creation Initiated
  4/11 | 10:12:04 AM | CREATE_IN_PROGRESS   | AWS::IAM::Policy      | ImagePublishingRoleDefaultPolicy
  4/11 | 10:12:05 AM | CREATE_IN_PROGRESS   | AWS::IAM::Policy      | ImagePublishingRoleDefaultPolicy Resource creation Initiated
  5/11 | 10:12:14 AM | CREATE_COMPLETE      | AWS::IAM::Policy      | ImagePublishingRoleDefaultPolicy
  6/11 | 10:12:14 AM | CREATE_COMPLETE      | AWS::IAM::Role        | DeploymentActionRole
 6/11 Currently in progress: FileAssetsBucketEncryptionKey
  7/11 | 10:13:04 AM | CREATE_COMPLETE      | AWS::KMS::Key         | FileAssetsBucketEncryptionKey
  7/11 | 10:13:09 AM | UPDATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket Requested update requires the creation of a new physical resource; hence creating one.
  7/11 | 10:13:09 AM | UPDATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket Resource creation Initiated
  8/11 | 10:13:31 AM | UPDATE_COMPLETE      | AWS::S3::Bucket       | StagingBucket
  8/11 | 10:13:33 AM | CREATE_IN_PROGRESS   | AWS::IAM::Policy      | FilePublishingRoleDefaultPolicy
  8/11 | 10:13:34 AM | CREATE_IN_PROGRESS   | AWS::IAM::Policy      | FilePublishingRoleDefaultPolicy Resource creation Initiated
  8/11 | 10:13:35 AM | UPDATE_IN_PROGRESS   | AWS::S3::BucketPolicy | StagingBucketPolicy Requested update requires the creation of a new physical resource; hence creating one.
  8/11 | 10:13:36 AM | UPDATE_IN_PROGRESS   | AWS::S3::BucketPolicy | StagingBucketPolicy Resource creation Initiated
  9/11 | 10:13:36 AM | UPDATE_COMPLETE      | AWS::S3::BucketPolicy | StagingBucketPolicy
 10/11 | 10:13:42 AM | CREATE_COMPLETE      | AWS::IAM::Policy      | FilePublishingRoleDefaultPolicy
 10/11 | 10:13:44 AM | UPDATE_COMPLETE_CLEA | AWS::CloudFormation::Stack | CDKToolkit
 10/11 | 10:13:45 AM | DELETE_IN_PROGRESS   | AWS::S3::BucketPolicy | StagingBucketPolicy
 ✅  Environment aws://034068960xxx/cn-north-1 bootstrapped.

(base) base ❯ env CDK_NEW_BOOTSTRAP=1 npx cdk bootstrap \
  --cloudformation-execution-policies arn:aws-cn:iam::aws:policy/AdministratorAccess
 ⏳  Bootstrapping environment aws://034068960xxx/cn-north-1...
 ✅  Environment aws://034068960xxx/cn-north-1 bootstrapped (no changes).
```

**Comment by zxkane** [comment]
> Your last 2 concerns are hard to work around. IAM should validate whether the referenced policy exists, but apparently it doesn't.
> 
> Also, we have no way to know beforehand whether the given policy is going to give enough permissions, because we won't know what kind of permissions you need.
> 
> In some other environments you may legitimately want to use a narrower policy than `AdministratorAccess`.

How about checking the existence of given execution role in synthesis phase? It should be doable via IAM API.

And how about using the managed `AdministratorAccess` policy as default permission of execution role? It does not make sense creating an execution role without any permission.

**Comment by rix0rrr** [comment]
I know, but this is a requirement from our security department. YOU need to be the person who opts in to giving a role potentially dangerous permissions. We cannot do that for you.

**Comment by hoegertn** [comment]
Could this opt-in be in the form of an interactive confirmation?

**Comment by rix0rrr** [comment]
> Could this opt-in be in the form of an interactive confirmation?

That is something we'll pursue but due to organizational reasons it may be a couple of weeks before we can get an answer to that question.

**Comment by hoegertn** [comment]
Ok, can you then make the cli argument mandatory to prevent users from creating exec roles without permissions?

**Comment by rix0rrr** [comment]
It was supposed to default to "admin" if you didn't establish any `--trust`s, we need to investigate why that doesn't work.
