### ISSUE TITLE
SNS notifications on stack events

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#8581]
## :question: General Issue

I am playing around with different ways to hook into lifecycle events of Stacks / Components. Of course there is the AwsCustomResource or ProviderFramework way. While AwsCustomResource is only viable for a simple SDK calls, ProviderFramework offers a lot more but with more complexity involved.

Now i noticed notificationArns on Stack level. What i recall you can attach them via command line on deployment (not what i am looking for) or programatically via NestedStack Construct. I wonder why this requirement is in place? Why cant we add them on our main stacks? (i think you can only read them)

This way one could easily setup a topic and a consumer and one should be able to hook into those lifecycle events pretty easily. 

### proposed idea

Why not having a method like this on Stack construct:

```
let myStack = new MyStack(app,...);
myStack.addNotificationArns(...);
```

Not sure why this method is not available in the construct when at the end it will synth to AWS::CloudFormation::Stack

**Comment by eladb** [comment]
Relabeled as feature. This is something we should be able to support.

**Comment by yashghatti** [comment]
Hey guys, any update on this?

**Comment by stephankaag** [comment]
@rix0rrr Can you give us a pointer where to implement this? I can look into building a pull-request.

**Comment by yashghatti** [comment]
@stephankaag thanks for looking into this, so right now notification ARNs are only supported as a command-line arg to the cdk command. But it'd be nice (as the first comment mentioned) to have a method in the core.Stack class or even a constructor field to pass in notificationArns

**Comment by AustinZhu** [comment]
+1

**Comment by domfie** [comment]
AFAIK: Currently only possible through the cli:
`cdk deploy stackID --notification-arns='arn:aws:sns:{region}:{aws-id}:{sns-name}'`
(Replace the placeholders with your values)

On subsequent calls the arn can be omitted.

**Comment by logemann** [comment]
Thats why it would make up a good feature Request. Think should be part of the AWS CDK.

**Comment by kornicameister** [comment]
Wouldn't this be a bit of chicken & egg problem? I mean something gotta provide SNS topic?

**Comment by domfie** [comment]
> Wouldn't this be a bit of chicken & egg problem? I mean something gotta provide SNS topic?

Not really since you first need to deploy the sns with another stack or create it by hand. A check if this sns exists and a corresponding error message should not be the problem

**Comment by kornicameister** [comment]
Given that it seems to be already supported on nested stack it shouldn't bee to much of a trouble to add this for top-level stacks, right?

**Comment by shubhamk1997** [comment]
Any updates on this ? I agree this should be a part of the Stack construct rather than the NestedStack construct.

**Comment by tedgonzalez** [comment]
+1

**Comment by driseley** [comment]
Now that this has been added to the Security Best Practices: 

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-cloudformation-1

it would be great to see better support for this.

As a simpler fix, could the notification arns be configurable in the cdk.json file, so that defaults can be configured without having to always supply them on the command line for each new stack:

https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-config

**Comment by antonio-masotti** [comment]
Is there an update on this? Both the integration in the CDK or in the context file seem very good features for me.

It would be great, especially for projects where many devs are working on the same cdk app.

**Comment by RajasGujarathi** [comment]
This is definitely a needed feature.

**Comment by iamgabeortiz** [comment]
+1

**Comment by tim-g-provectusalgae** [comment]
Yes, this is being picked up by [KICS](https://github.com/Checkmarx/kics) as a `MEDIUM` severity issue and our pipelines are failing. We will have to outright ignore `CloudFormation.1`, which is a against AWS Security Best Practices.

**Comment by shazib-summar** [comment]
Its been 2 and a half years and still no update on this????

**Comment by markusl** [comment]
Hey! Is this on the roadmap? We'd like to use this in certain stacks which have a security impact

**Comment by rix0rrr** [comment]
Closed in https://github.com/aws/aws-cdk/pull/31107
