### ISSUE TITLE
Add route to TransitGateway failed

### ISSUE THREAD

**Issue by zaghost** [aws/aws-cdk#8584]
In Python language, create two VPCs and a TransitGateway , 
then add a route to TransitGateway for RouteTable of Subnets of VPC1
 it will fail with the following message:

> vpc1-routetgw1 (vpc1routetgw1) The transitGateway ID 'tgw-0a1f4b4ba8f209ae6' does not exist. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidTransitGatewayID.NotFound; Request ID: bf5e9144-a952-4f79-9cc0-be7cbe45d0c5)

Actually, the transitGateway ID is correct, 
because if you create VPCs and a TransitGateway in one Stack, and add route in another Stack,
it will success.

### Reproduction Steps
```
class CdkTestStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc1 = ec2.Vpc(self, "VPC1",
                           cidr="10.10.0.0/16")
        vpc2 = ec2.Vpc(self, "VPC2",
                           cidr="10.11.0.0/16")

        transitGateway = ec2.CfnTransitGateway(self, "TransitGateway")

        for index,subnet in enumerate(vpc1.private_subnets):
            ec2.CfnRoute(self, "vpc1-routetgw"+str(index),
                        route_table_id = subnet.route_table.route_table_id,
                        destination_cidr_block = vpc2.vpc_cidr_block,      #vpc1 -> vpc2
                        transit_gateway_id = transitGateway.ref)

```

### Error Log

>  41/51 | 3:26:04 | CREATE_FAILED        | AWS::EC2::Route                       | vpc1-routetgw1 (vpc1routetgw1) The transitGateway ID 'tgw-0a1f4b4ba8f209ae6' does not exist. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidTransitGatewayID.NotFound; Request ID: bf5e9144-a952-4f79-9cc0-be7cbe45d0c5)
>         D:\Python38\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7877:49
>         \_ Kernel._wrapSandboxCode (D:\Python38\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:8350:20)
>         \_ Kernel._create (D:\Python38\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7877:26)
>         \_ Kernel.create (D:\Python38\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7621:21)
>         \_ KernelHost.processRequest (D:\Python38\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7411:28)
>         \_ KernelHost.run (D:\Python38\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7349:14)
>         \_ Immediate._onImmediate (D:\Python38\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7352:37)
>         \_ processImmediate (internal/timers.js:456:21)

 

### Environment
Nodejs v12.16.3
Python 3.8.3(pip 19.2.3)
cdk 1.45.0
OS Windows 10

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This seems like it would have to be an eventual consistency issue. 

I'm assuming the exact same thing would happen if you tried the same operation in CloudFormation, which means it's not really a CDK issue and not actionable for us.

**Comment by am29d** [comment]
> This seems like it would have to be an eventual consistency issue.
> 
> I'm assuming the exact same thing would happen if you tried the same operation in CloudFormation, which means it's not really a CDK issue and not actionable for us.

Yep, if you create a TransitGateway it is pending state and you can not use it. Running this in two different stacks helps to resolve the race condition.
