### ISSUE TITLE
Naming of the CfnUserPoolClient.callbackUrLs

### ISSUE THREAD

**Issue by zamzterz** [aws/aws-cdk#8586]
## :question: General Issue

The unusual letter casing in [`CfnUserPoolClient.callbackUrLs`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts#L308) is confusing. In the Python SDK `callbackUrLs` becomes [`callback_ur_ls`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cognito/CfnUserPoolClient.html), which quite unintuitive.

It would be easier to find and use if it was named `callbackUrls`.

**Comment by RomainMuller** [comment]
I see why this was tagged as `jsii`, but in fact the problematic name was generated by `cfn2ts` and not by `jsii`.

**Comment by eladb** [comment]
We should be able to patch that up in cfn2ts
