### ISSUE TITLE
stepfunctions tasks x EMR - service integration improvements

### ISSUE THREAD

**Issue by shivlaks** [aws/aws-cdk#8598]
### Use Case

In migrating the EMR service integration in #8177 to using a merged set of properties for task and state, we came across a few issues

However, due to the size of the existing implementation (particularly `CreateCluster`), we deferred these improvements to a follow-up PR. 

### Proposed Solution

General: 
* resolve naming inconsistencies
* address existing bugs for the EMR service integration
* remove jsii incompatible functions
* ensure strong typing across all of the service integration APIs
* break out integration tests
* JSII does not support namespaces (https://github.com/aws/aws-cdk/pull/8177#discussion_r442370969)

EmrCreateCluster:
* refactor types out into a separate file (`emr-types.ts`)
* reuse strong types in `aws-s3` (i.e. https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudtrail/lib/cloudtrail.ts#L415

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by fmcmac** [comment]
EmrCreateCluster is missing a Construct Props for Steps (similar to https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-emr.CfnCluster.html#steps). Is this planned or should this be added here?

**Comment by shivlaks** [comment]
@fmcmac thank you for adding that information! It was not on my radar but absolutely belongs here.

This is the right place to collect anything we're missing, modeled incorrectly, presents a usability issue, etc.
We likely need to rewrite/redesign parts of the integration to start driving it towards the direction of stability.

**Comment by fmcmac** [comment]
The apparent inability to inject parameters into step args is a significant issue for adaptable step functions:
```
# add emr step
add_cluster_step = sfn.Task(
    self,
    "add_cluster_step",
    task=sfn_tasks.EmrAddStep(
        cluster_id=sfn.Data.string_at("$.create_cluster.ClusterId"),
        jar="command-runner.jar",
        name=sfn.Data.string_at("$.set_parameters.job_name"),
        args=[
            "spark-submit",
            "--deploy-mode" "cluster",
            sfn.Data.string_at("$.set_parameters.script_path"),
            ],
    ),
    input_path="$",
    result_path="$.add_cluster_step",
    output_path="$",
)
```
This fails with "jsii.errors.JSIIError: Cannot use JsonPath fields in an array, they must be used in objects"

**Comment by soumoks** [comment]
This issue still exists and significantly limits how step functions to EMR service integration can be used.
