### ISSUE TITLE
Dummy-value (returned by StringParameter.FromValueLookup(), for example) results in exception

### ISSUE THREAD

**Issue by OlegBoulanov** [aws/aws-cdk#8604]
So I want to lookup a value in SSM Parameter Store, and use it as a bucket name. The problem is that cdk synth then runs my app twice, first lookup returning a dummy-value for parameter path, and then attempting to run again with actual parameter value, after storing it in context.

Since parameter path contains slashes, new Bucket() triggers exception on the first run, context is never updated.

### Reproduction Steps

 internal CdkTestAppStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
 {
    var bucketName = StringParameter.ValueFromLookup(this, "/bucket/name");
    Console.WriteLine($"Bucket name: {bucketName}");
    new Bucket(this, "TestBucket", 
       new BucketProps { BucketName = $"Bucket-{bucketName}", });
...
}

### Error Log

Unhandled exception. Amazon.JSII.Runtime.JsiiException: Invalid S3 bucket name (value: bucket-dummy-value-for-/bucket/name)
Bucket name must be at least 3 and no more than 63 characters
Bucket name must only contain lowercase characters and the symbols, period (.) and dash (-) 

### Environment

  - **CLI Version      : 1.45.0
  - **Framework Version: 1.45.0
  - **Node.js Version: v12.7.0
  - **OS               : Windows 10
  - **Language (Version): C#

### Other

--- 

This is :bug: Bug Report

**Comment by OlegBoulanov** [comment]
It would be nice if information about operation (synth, deploy, ...) and pass number was available to the app.

**Comment by rix0rrr** [comment]
Yeah the dummy value should be a token. There is a different issue about the exact same thing.
