### ISSUE TITLE
[EKS Feature] how to add resource to imported eks cluster

### ISSUE THREAD

**Issue by Mantrapps** [aws/aws-cdk#8608]
https://github.com/aws/aws-cdk/blob/d6190f23b7cc17b005de6295cc2c35c703054b44/packages/%40aws-cdk/aws-eks/lib/k8s-resource.ts#L13

https://github.com/aws/aws-cdk/blob/d6190f23b7cc17b005de6295cc2c35c703054b44/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1047

**Question:**
ImportedCluster return `ICluster`  type , but add resource using `Cluster`, how to add resource to imported EKS cluster

**Environemnt:**
ÇDK: 1.45.0
EKS: 1.15.*

**Comment by eladb** [comment]
It is currently not possible to add resources to clusters not created in your CDK app. Relabeled as a feature request.

**Comment by eladb** [comment]
Duplicate #5383
