### ISSUE TITLE
FargatePlatformVersion not getting respected in StepFunctions when using CDK

### ISSUE THREAD

**Issue by yashwanthkp** [aws/aws-cdk#8610]
FargatePlatformVersion not getting respected in StepFunctions when using CDK

### Reproduction Steps

I have a fargate task as a step in my step-function with the below code which tries to start the task on FargatePlatform version 1.4.

```
return new sfn.Task(app, props.id, {
    task: new tasks.RunEcsFargateTask({
        cluster: props.cluster,
        taskDefinition: props.taskDef,
        subnets: props.cgpVpc.selectSubnets({subnetType: SubnetType.PRIVATE}),
        integrationPattern: props.integrationPattern,
        containerOverrides: [
            {
                containerName: "containerId",
                environment: getSfnEnvValues(props.envValueKeys)
            }],
        platformVersion: FargatePlatformVersion.VERSION1_4
    }),
    resultPath: props.resultPath,
    timeout: timeout
});
```

After I run ```cdk deploy```, I end up getting the below ASL code

```
"TaskRun": {
      "Next": "X",
      "Parameters": {
        "Cluster": "arn: aws: ecs: us-west-2:...",
        "TaskDefinition": "arn: aws: ecs: us-west-2: ....",
        "NetworkConfiguration": {
          "AwsvpcConfiguration": {
            "Subnets": [
              "subnet-...."
            ],
            "SecurityGroups": [
              "sg-...."
            ]
          }
        },
        "Overrides": {
          "ContainerOverrides": [
            {
              "Name": "Container",
              "Environment": [
                {
                  "Name": "STAGE",
                  "Value": "devo"
                }
              ]
            }
          ]
        },
        "LaunchType": "FARGATE"
      },
      "Type": "Task",
      "Resource": "arn: aws: states: : : ecs: runTask.waitForTaskToken",
      "TimeoutSeconds": 900
    },
```
I was expecting a new line ```"PlatformVersion": "1.4.0"``` in the generated ASL. 

### Error Log

There are no errors on ```cdk deploy```. However the stepfunction created does not have ```"PlatformVersion": "1.4.0"``` override in ASL. 

### Environment

  - **CLI Version      :**
  - **Framework Version:** : 1.39
  - **Node.js Version:** 12.x
  - **OS               : Linux
  - **Language (Version):** Typescript: 3.6.4

### Other

NA

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@yashwanthkp thanks for reporting the issue and detailed repro steps. I'd expect the output to include the fargate version as well. I'll investigate to see why that property is not being honoured and provide an update.

**Comment by yashwanthkp** [comment]
@shivlaks

Thanks for the response!

Is there a tentative date for the fix for this?

**Comment by shivlaks** [comment]
@yashwanthkp added a commit to #8451 that honors the fargate platform version. Note that this is the newer style of calling service integrations with Step Functions, which we are aligning so we can push Step Functions towards `stable` and drop the `experimental` tag

**Comment by yashwanthkp** [comment]
@shivlaks Thanks for the response! Why version of CDK will the above change be rolled out in?

**Comment by shivlaks** [comment]
@yashwanthkp there's still some feedback to work through before it'll be merged and i'm currently on it.
After it's merged, it'll be included in the next released version of the CDK. you can follow [release notes](https://github.com/aws/aws-cdk/releases) to keep an eye out for the new ECS service integration with Step Functions when it pops up.
