### ISSUE TITLE
Roles obtained with `fromRoleArn` should provide a `roleId`

### ISSUE THREAD

**Issue by kevinfguo** [aws/aws-cdk#8612]
`fromRoleArn` should return the `roleId` property.

### Use Case

The current `fromRoleArn` function returns an `IRole` instead of a `Role`. This is problematic because an `IRole` does not have the `roleId` property, which is necessary to [restrict s3 bucket permissions to a specific role](https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/), particularly if you'd like to do that [in a VPC](https://aws.amazon.com/premiumsupport/knowledge-center/block-s3-traffic-vpc-ip/). 

There is also appears to be no way to get the Role via CfnRole, to get that property.

### Proposed Solution

Have [`fromRoleArn`](https://github.com/aws/aws-cdk/blob/1819a6b5920bb22a60d09de870ea625455b90395/packages/%40aws-cdk/aws-iam/lib/role.ts#L175) return a `Role` instead of an `IRole`. 

Or, have `IRole` contain the `roleId` property.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
`Role.fromRoleArn()` doesn't actually do any work. It takes the information you give in and spit it back out.

We would need to do an actual lookup to support this.

**Comment by rix0rrr** [comment]
I'm afraid this is going to be out of scope for a while. I recommend a custom resource to in order to look up the roleId during deployments if you need them.
