### ISSUE TITLE
add_managed_policy

### ISSUE THREAD

**Issue by pchevallier** [aws/aws-cdk#8613]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Role.html

Documentation doesn't reflect the proper construct. 
In the documentation we have: **addManagedPolicy**
while the API seems to refer **add_managed_policy**

---
This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
I will assume you are using Python, where it actually is `add_managed_policy`.

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/Role.html#aws_cdk.aws_iam.Role.add_managed_policy
