### ISSUE TITLE
[AppSync]: dynamodb source doesn't support imported table

### ISSUE THREAD

**Issue by nirvana124** [aws/aws-cdk#8618]
Adding dynamodb source to graphQL api doesn't support imported table.

### Use Case
I have a table lets say 'Customer' that is created in another application and i want to add customer table as a data source in graphql api in another application. 

### Proposed Solution
Change `table: Table` argument to `table: ITable` in `addDynamoDbDataSource` method and `DynamoDbDataSourceProps`.

### Other

* [✔️] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by tyroneerasmus** [comment]
I am facing the same issue.

Am trying to import a table from another stack and get
```
Error: Object of type @aws-cdk/core.Resource is not convertible to @aws-cdk/aws-dynamodb.Table
```

P.S. Using Python CDK

**Comment by tyroneerasmus** [comment]
A similar issue was solved here: https://github.com/aws/aws-cdk/pull/6635

**Comment by kennu** [comment]
I'm having the same problem, because I want to create my DynamoDB tables in a separate stack (and possibly import orphaned tables after CloudFormation migrations in the future).

**Comment by MrArnoldPalmer** [comment]
Yeah changing from accepting `Table` to `ITable` is the right way to go here. Should be relatively simple to implement and non-breaking for users.
