### ISSUE TITLE
[stepfunctions]: simulate state machines in unit tests

### ISSUE THREAD

**Issue by shivlaks** [aws/aws-cdk#8620]
### Use Case

The current mechanism to test state machines within the CDK is to leverage the `toStateJson()` API that all states produce as well as the template itself. It would be useful to improve on this by enabling the ability to simulate a state machine in a unit test so the state machine itself and not the definition that is produced can be tested.

Capturing this issue from the `Future Work` section in the README.
This will allow us to collect interest and user feedback to drive prioritization

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-docker.html

https://hub.docker.com/r/amazon/aws-stepfunctions-local

**Comment by shivlaks** [comment]
@jogold it's been on my list to investigate and play with sfn local! have you tinkered with it yet? 
related: Localstack also has a Step Functions endpoint that I haven't had a chance to play with yet

**Comment by jogold** [comment]
> have you tinkered with it yet?

No, not yet.

> Localstack also has a Step Functions endpoint

interesting!

**Comment by lanefelker** [comment]
+1 

I would love a solution to more easily unit test step functions
