### ISSUE TITLE
[billing]: Construct to generate alarms from billing metrics

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#8623]
## :question: General Issue

I have a construct I would like to contribute to CDK, which creates Cloudwatch alarms based on whether total account spending is above a certain threshold. This just requires creating an [Alarm](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Alarm.html) construct with the metric and thresholds set.

I am already using the construct for my own projects and it makes it very easy to track accidental overspending.

Here are the AWS billing metrics that make it possible.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html

### The Question

Which module would such a construct go in? I see a couple modules for aws-budgets and aws-ce, but they have a " ¹ "  next to their name which makes it seem like they're under development. Also, this wouldn't use any constructs from aws-budgets or aws-ce.

### Environment

  - **CDK CLI Version:** 1.44
  - **OS:** all
  - **Language (Version):** all

**Comment by SomayaB** [comment]
Hi @flemjame-at-amazon, in this case the best way to go about it is to self publish it yourself.

**Comment by menge101** [comment]
@flemjame-at-amazon I would love to know if this billing construct ever ended up anywhere.

**Comment by alvyn279** [comment]
@menge101 @flemjame-at-amazon

I built a `BillingAlarm` construct that is now in beta. Let me know what you think!

https://www.npmjs.com/package/aws-cdk-billing-alarm
