### ISSUE TITLE
'mutable' property of user pool attribute has multiple defaults

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8624]
Documenting weird inconsistencies with Cognito defaults.

A CloudFormation template contains this for the `Schema` property - 

```
<-- snip -->
"Schema": [
  {
    "Name": "email",
    "Required": true
  }
],
<-- snip -->
```

Deploying this template results in a user pool whose attributes look like this -

`aws cognito-idp describe-user-pool --user-pool-id eu-west-1_TFtKWJ0oL`

```
<-- snip -->
{
    "Name": "website",
    "AttributeDataType": "String",
    "DeveloperOnlyAttribute": false,
    "Mutable": true,
    "Required": false,
    "StringAttributeConstraints": {
        "MinLength": "0",
        "MaxLength": "2048"
    }
},
{
    "Name": "email",
    "AttributeDataType": "String",
    "DeveloperOnlyAttribute": false,
    "Mutable": false,
    "Required": true,
    "StringAttributeConstraints": {
        "MinLength": "0",
        "MaxLength": "2048"
    }
},
<-- snip -->
```

Look closely and you'll see that `Mutable` has two different defaults. The default value for `Mutable` when the `Schema` property is specified for an attribute is `false`, but when no `Schema` property is specified, the default is `true`.

**Comment by nija-at** [comment]
Further, I was able to test and confirm that the defaults does in fact change based on whether it is specified in the `Schema` or not.

Tested that by swapping `email` attribute with `website` and seeing the same behaviour, and tested by marking `Required` to `false`. In both cases, the `Mutable` field's behaviour persists.

To conclude, `Mutable` defaults to `true` for standard attributes not explicitly specified under `Schema`, and defaults to `false` for attributes when explicitly specified.

**Comment by nija-at** [comment]
This seems to occur only via CloudFormation and not the CLI. The CLI always sets the default `Mutable` to `true`.

```
⇒ aws cognito-idp create-user-pool --pool-name 'test-pool-1' --schema Name=email,Required=true

⇒ aws cognito-idp describe-user-pool --user-pool-id eu-west-1_fLC6ixBzT
<-- snip -->
{
    "Name": "website",
    "AttributeDataType": "String",
    "DeveloperOnlyAttribute": false,
    "Mutable": true,
    "Required": false,
    "StringAttributeConstraints": {
        "MinLength": "0",
        "MaxLength": "2048"
    }
},
{
    "Name": "email",
    "AttributeDataType": "String",
    "DeveloperOnlyAttribute": false,
    "Mutable": true,
    "Required": true,
    "StringAttributeConstraints": {
        "MinLength": "0",
        "MaxLength": "2048"
    }
},
<-- snip -->
```

**Comment by rix0rrr** [comment]
> This seems to occur only via CloudFormation and not the CLI.

Damning if true!

**Comment by rix0rrr** [comment]
I'd say we skip the CloudFormation but then, and restore the service's behavior.

**Comment by nija-at** [comment]
> I'd say we skip the CloudFormation but then, and restore the service's behavior.

The current behaviour of the CDK is consistent with the service.

**Comment by corymhall** [comment]
Closing since there is nothing to be done here.
