### ISSUE TITLE
📊Tracking: Cognito - Identity Pools

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8630]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

Amazon Cognito provides authentication, authorization, and user management for your web and mobile apps. Your users can sign in directly with a user name and password, or through a third party such as Facebook, Amazon, Google or Apple.

Cognito Identity pools provide authorization via identity federation

[AWS Docs for Identity Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html)

[CDK API reference page](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html)

### Maturity: CloudFormation only

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Features & Support

| Done | Item | Needed for Graduation | Link to issue or docs |
| ---- | ---- | ---- | ---- |
| | initialization & import | ✔️ | |
| | [public identity providers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html) & access control | ✔️ | |
| | role mapping & mapping rules | ✔️ | |
| | [OpenIdConnect & SAML and developer-authenticated identity providers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html) | ❓ | |

### Issues

All open Cognito issues can be found [here](https://github.com/aws/aws-cdk/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%2Fcognito)

--- 
This is a  📊Tracking Issue

**Comment by gradybarrett** [comment]
Having openid capabilities would be fantastic since it enables us to bring our own identity provider. That's a major use case for large orgs where user pools are blacklisted for use in favor of centralized IdPs.
