### ISSUE TITLE
📊Tracking: AWS Resource Groups

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#8638]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

You can use resource groups to organize your AWS resources. Resource groups make it easier to manage and automate tasks on large numbers of resources at one time. This guide shows you how to create and manage resource groups in AWS Resource Groups. 

[AWS Docs](https://docs.aws.amazon.com/ARG/latest/userguide/welcome.html)  

### Maturity: CloudFormation Resources Only

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-resourcegroups-readme.html) for more implementation details.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by oliversalzburg** [comment]
What's the point in closing stale tracking issues? Does that mean you're just giving up on the idea?
