### ISSUE TITLE
Stabilize Amazon CloudWatch Synthetics module

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#8640]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

You can use Amazon CloudWatch Synthetics to create canaries, configurable scripts that run on a schedule, to monitor your endpoints and APIs. Canaries follow the same routes and perform the same actions as a customer, which makes it possible for you to continually verify your customer experience even when you don't have any customer traffic on your applications. By using canaries, you can discover issues before your customers do. 

[AWS Docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries.html)  

### Maturity: CloudFormation Resources Only

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-synthetics-readme.html) for more implementation details.

### Issue list:

- [#7687]

**Comment by AaronHarris** [comment]
Do we even have low-level constructs for this service yet?
