### ISSUE TITLE
(cdk): build docker assets in parallel

### ISSUE THREAD

**Issue by AlexCheema** [aws/aws-cdk#8649]
Build docker assets in parallel

### Use Case

Currently docker assets are built sequentially. If your app has a lot of docker asssets, it can take a very long time to build everything. Building in parallel would speed things up a lot.

### Proposed Solution

?

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
This is something much better achieved through a CI/CD system, and in fact will be the default set up for the upcoming CI/CD feature.

Closing for now.

**Comment by AlexCheema** [comment]
> This is something much better achieved through a CI/CD system, and in fact will be the default set up for the upcoming CI/CD feature.
> 
> Closing for now.

Is there somewhere I can track the progress of this feature?
