### ISSUE TITLE
(aws-ecr): ecr.Repository.from_repository_name() method not returning the reference to repository

### ISSUE THREAD

**Issue by rahul-ve** [aws/aws-cdk#8652]
### The Question

Got the below repo in ECR
```
{
  "repositoryArn": "arn:aws:ecr:us-east-1:xxxxxxxxxxxx:repository/airflow",
  "registryId": "xxxxxxxxxxxx",
  "repositoryName": "airflow",
  "repositoryUri": "xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/airflow",
  "createdAt": "2020-06-18T05:11:10+10:00",
  "imageTagMutability": "MUTABLE",
  "imageScanningConfiguration": {
      "scanOnPush": false
  }
}
```

and when building a cdk script, I need to reference this repo, I tried the below:

```
repo_1 = ecr.Repository.from_repository_name(self, id='airflow_repo', repository_name= 'airflow')
print(repo_1.repository_arn)
print(repo_1.repository_uri)
```
and the output is:
```
arn:${Token[AWS::Partition.3]}:ecr:${Token[AWS::Region.4]}:${Token[AWS::AccountId.0]}:repository/airflow
${Token[TOKEN.15]}.dkr.ecr.${Token[TOKEN.14]}.${Token[AWS::URLSuffix.1]}/airflow
```

below works as expected:
```
repo_ = ecr.Repository.from_repository_arn(self, id = 'airflow', repository_arn='arn:aws:ecr:us-east-1:xxxxxxxxxxxx:repository/airflow')
print(repo_.repository_arn)
print(repo_.repository_uri)
```
and the output is:
```
arn:aws:ecr:us-east-1:xxxxxxxxxxxx:repository/airflow
xxxxxxxxxxxx.dkr.ecr.us-east-1.${Token[AWS::URLSuffix.1]}/airflow
```

I am using this method incorrectly? 
ecr.Repository.from_repository_name()

 

### Environment

  - **CDK CLI Version:** 1.45.0 (build 0cfab15)
  - **Module Version:**  1.45.0 (all of them)
  - **Node.js Version:** v12.17.0
  - **OS:** Windows 10 
  - **Language (Version):** Python (3.8.2)

**Comment by MrArnoldPalmer** [comment]
@rahul-ve The output looks like its what is expected unless I'm missing something. Is the imported `IRepository` construct not working as expected when passed to another construct or otherwise breaking your app?

CDK uses a system of `Token`s  to reference values that may or may not be present during stack synthesis. That is what you're seeing when you `print` the repository arn of the imported resource.

**Comment by rahul-ve** [comment]
@MrArnoldPalmer  Using either of the methods  allows for proper synchronization but deployment fails when the from_repository_name()  method is used. Is there a way to identify the cause?

**Comment by MrArnoldPalmer** [comment]
@rahul-ve what is the error that comes up during deploy?

**Comment by rahul-ve** [comment]
@MrArnoldPalmer  I will have to do another test and cut down my stack to keep it specific. Will report back in the next couple of days.

**Comment by SomayaB** [comment]
Hi @rahul-ve, do you have any updates?

**Comment by rahul-ve** [comment]
> 
> 
> Hi @rahul-ve, do you have any updates?

Sorry, I am unable to spend time on this issue right now, we can close this for now, if I encounter this issue again, will reopen it.
Thank you.
