### ISSUE TITLE
aws-ecs-patterns: multiple services with one application load balancer

### ISSUE THREAD

**Issue by ChristophMalassa** [aws/aws-cdk#8669]
### The Question
While the official documentation is getting more and more really helpful examples[1], I am missing guidance or an example for a slightly more difficult setup:
- I need to run multiple services within one ECS cluster (Fargate)
- Each service runs at least two containers
- There is one application load balancer (ALB) for the entire cluster
- The ALB forwards the traffic the to correct service (each service is a target group) via path based routing

[1]: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-patterns-readme.html

Can someone provide an example on how that is possible? I have successfully set this up through the console but I need to now recreate it using the CDK.

Thank you very much for your time and support!
Christoph

**Comment by zxkane** [comment]
You can add multiple target groups to the listener of application load balancer. The target group can be different ECS services. You can refer to [this example](https://github.com/zxkane/cdk-collections/blob/44f37afa8ae60e3e5680a19292cb27e82380ca3e/ecs-sonatype-nexus3/lib/ecs-sonatype-nexus3-stack.ts#L236) though it has only one target group.

**Comment by ChristophMalassa** [comment]
thank you zxkane. We will give it a shot but are probably going to go the the low level Cfn implementations as those give us more control over every detail, e.g. naming conventions

**Comment by bvtujo** [comment]
Hi Chistoph, 

Currently the ecs patterns support the use case of a single load balancer and single service (`*LoadBalanced*Service` constructs) or a load balancer with multiple target groups on the same container (`*LoadBalancedMultipleTargetGroups*Service` constructs). 

There are a lot of configuration options involved in path-based routing, so I think your best bet may be to create the ALB, service, cluster, and VPC via the `ApplicationLoadBalancedFargateService` construct, then use the `.loadBalancer`, `.cluster`, and `.vpc` properties of the created ALBService to add your own target groups. There is an example from a past issue you may be able to use [here (#7327)(https://github.com/aws/aws-cdk/issues/7327#issuecomment-614322050). 

Hope this helps with your use case!

**Comment by drissamri** [comment]
What if I don't want multiple services but want to customize the context path for the Fargate Service? 
(run it on my.domain.com/customContextPath instead of my.domain.com)

**Comment by escarbor** [comment]
@drissamri I unless I misunderstand what you are asking, you could use ALB listener [rules](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#listener-rules) to redirect to your service's target group based on the path.

**Comment by drissamri** [comment]
How can I set this or override it in the ApplicationLoadBalancedFargateService pattern? I'm new to the CDK and still trying to figure it out :) 

```
       const service = new ecs_patterns.ApplicationLoadBalancedFargateService(this, "fargateService", {
            cluster: this.getCluster(),
            certificate: this.getCertificate(props.certificateArn),
            domainZone: this.getDomainZone(props.domainName),
            domainName: 'dev.'+props.domainName,
            desiredCount: 1,
            taskImageOptions: {
                image: ecs.ContainerImage.fromEcrRepository(props.repository, 'LATEST'),
                containerPort: 8080
            },
        });

        service.targetGroup.configureHealthCheck({
            path: "/actuator/health",
        });
    }
```

**Comment by escarbor** [comment]
Your `service` has a number of helpful methods/properties which allow you to access the various structs it creates. [See here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html#loadbalancer-1). So you can do something like this: 
`service.loadBalancer.addListener(id: string, props: BaseApplicationListenerProps)`
Alternatively, you can define your Loadbalancer else where, and pass it into the `ApplicationLoadBalancedFargateService` as one of the props. 
I am also pretty new to CDK so if I steer you wrong, I apologize. Hope this helps.

**Comment by SomayaB** [comment]
Closing this issue since it seems to have been resolved. Feel free to reopen.

**Comment by agalazis** [comment]
> @drissamri
> Your `service` has a number of helpful methods/properties which allow you to access the various structs it creates. [See here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html#loadbalancer-1). So you can do something like this:
> `service.loadBalancer.addListener(id: string, props: BaseApplicationListenerProps)`
> 
> Alternatively, you can define your Loadbalancer else where, and pass it into the `ApplicationLoadBalancedFargateService` as one of the props, like so:
> 
> ```
>  const ecsPatternProps: ApplicationLoadBalancedFargateServiceProps = {
>             cluster: cluster,
>             loadBalancer: albInstance,
>             serviceName: serviceName,
>             taskDefinition: taskDefinition }
> ```
> 
> I am also pretty new to CDK so if I steer you wrong, I apologize. Hope this helps.
You definitely can't do the second option since identifiers are hardcoded ie Public Listener/ target group I think we need to reopen and facilitate @escarbor 's suggestion( since it's just a suggestion not currently supported with multiple services)
https://github.com/aws/aws-cdk/blob/89a505524ae3fe1c726d6988df07da6167493480/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L376
