### ISSUE TITLE
aws_apigatewayv2: add authorizer to route with HttpApi

### ISSUE THREAD

**Issue by stilren** [aws/aws-cdk#8670]
### The Question
How do I add an authorizer to a route in my HttpApi (with cdk using python)?
```
http_api = _apigw2.HttpApi(self, "ApiGwId",
                                   api_name="HttpGateway",
                                   cors_preflight=cors_preflight,
                                   )

authorizer = _apigw2.CfnAuthorizer(self, "MyAuthorizer",
                              api_id=http_api.http_api_id,
                              authorizer_type="JWT",
                              jwt_configuration={
                                  "audience": [user_pool_client.user_pool_client_id], "issuer": "myissuer"},
                              identity_source=[
                                  '$request.header.Authorization'],
                              name="Myauthorizer",
                              )

http_api.add_routes(
            path='/example',
            methods=[_apigw2.HttpMethod.GET],
            integration=my_lambda_integration,
        )
```
-->

### Environment

  - **CDK CLI Version:** 1.45.0
  - **Module Version:** 1.45.0
  - **Node.js Version:** v14.0.0
  - **OS:** WSL2 in Windows 10
  - **Language (Version):** Python (3.7.3)

**Comment by stilren** [comment]
Figured it out:
```
    for route in routes:
        routeCfn = route.node.default_child
        routeCfn.authorizer_id=authorizer.ref
        routeCfn.authorization_type = 'JWT'
```

**Comment by AjkayAlan** [comment]
Can I put a plug that I think this should still should be open? Ultimately I would like to see an authorizer property within add_routes, and within HttpRoute. Until it exists, we have to fall back to the Cfn implementation.

Until then, I can vouch that the workaround @stilren suggested does work well. Here is what I did (based on @stilren 's example):

```
        route = aws_apigatewayv2.HttpRoute(
            self,
            "my-id",
            http_api=apigateway_http_api,
            route_key=aws_apigatewayv2.HttpRouteKey.with_("/MyAwesomeAPIPath", aws_apigatewayv2.HttpMethod.GET),
            integration=lambda_proxy_integration
        )
        route.node.default_child.authorizer_id = authorizer.ref
        route.node.default_child.authorization_type = "JWT"
```

http_api is created from aws_apigatewayv2.HttpApi
integration is created from aws_apigatewayv2.LambdaProxyIntegration
authorizer is created from aws_apigatewayv2.CfnAuthorizer

**Comment by noorsheikh** [comment]
@stilren @AjkayAlan I tried the same solution with Typescript, but looks like it is not working. What do you guys suggest a Typescript workaround for above?

**Comment by stilren** [comment]
@noorsheikh 
Here is a sample project in typescript with auth
https://github.com/stilren/typescript-cdk-react/blob/master/backend/lib/backend-stack.ts

**Comment by noorsheikh** [comment]
> @noorsheikh
> Here is a sample project in typescript with auth
> https://github.com/stilren/typescript-cdk-react/blob/master/backend/lib/backend-stack.ts

This actually helped me, Thanks a lot @stilren!

**Comment by make-ing** [comment]
> Figured it out:
> 
> ```
>     for route in routes:
>         routeCfn = route.node.default_child
>         routeCfn.authorizer_id=authorizer.ref
>         routeCfn.authorization_type = 'JWT'
> ```

I have the exact same problem as @stilren . But i struggle to implement your workaround! Where do you get the routes object from?

I have the api object from HttpApi and the authorizer object from CfnAuthorizer
