### ISSUE TITLE
(aws-lambda): Allow writing Lambda logs to existing Log Group

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#8672]
Our project relies heavily on many Lambdas (that back AppSync as Data Sources). We'd love to be able to have a centralized "log" of all these lambdas. Currently, such logs are scattered across multiple Log groups (one per lambda). In other words, the Lambda construct currently creates its own log group and has no way of referring to an existing Log group where Lambda logs should be written.

### Proposed Solution

```
new Function(this, 'fn', {
    code: ...,
    handler: ....,
    logGroup: LogGroup.fromLogGroupArn(...),
})
```

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Unfortunately, the Lambda service reports logs to a specific log group, named after the function - https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs.html.

As far as I know, there is no way to control which log group this goes to. 

> the Lambda construct currently creates its own log group

Not technically. In the default case, the Lambda service creates this log group. When you specify the [`logRetention` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#logretention), we create the log group if it doesn't already exist and specify a retention policy; however, the log group name must be what Lambda expects it to be.

Let me know if there's something that I missed here.

**Comment by sith** [comment]
nija-at, could you explain why this limitation exists.

I have a state machine with multiple lambda functions and I want to have logs in one place rather going and querying them in corresponding lambda log groups.

**Comment by Dzhuneyt** [comment]
@sith this is a limitation of the AWS Lambda service itself, not something that can be solved with CloudFormation or AWS CDK (which all are built on top of AWS services like Lambda). [See this for further information](https://stackoverflow.com/a/39233203/1364793).

If you want to achieve true aggregation of logs for your whole State Machine that is composed of Lambdas that write to multiple `LogGroup`s, you can either query across multiple LogGroups using something like the [CloudWatch Logs Insights](https://aws.amazon.com/about-aws/whats-new/2019/07/cloudwatch-logs-insights-adds-cross-log-group-querying/) tool or implement your own logging layer inside the application runtime code (so e.g. replace your `console.log()` lines with `Logger.getInstance().log(message)`)

**Comment by lefnire** [comment]
I'm looking at [cdk-lib/lambda/Function](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html) and I see a `{logGroup?: ILogGroup}` prop:

> The LogGroup where the Lambda function's logs are made available.
 
I'm wondering if maybe this prop became available after this discussion took place? Unless I'm misunderstanding its functionality. If I'm not mistaken, one can just:

```typescript
import * as logs from '@aws-cdk/aws-logs';
import * as lambda from '@aws-cdk/aws-lambda';

const aggregatedLogGroup = new logs.LogGroup(this, 'AggregatedLogGroup', {
  logGroupName: '/aws/lambda/aggregated',
});

const myFunction = new lambda.Function(this, 'MyFunction', {
  ...
  logGroup: aggregatedLogGroup,
});
```

sst.Function doesn't have a `.cdk` prop (cdk escape), which I think I've seen elsewhere; otherwise I'd just give this a whirl. Was `.cdk` removed to prevent certain "won't work how you think" scenarios?

**Comment by Dzhuneyt** [comment]
@lefnire you are probably mistaking the `lambda.logGroup` [getter](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#loggroup) function for a prop. The [FunctionProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.FunctionProps.html) interface (which declares the input configuration for the created lambda) does not accept any logGroup configuration. Only logGroup expiration settings.

**Comment by lefnire** [comment]
@Dzhuneyt you're absolutely correct. Thanks for pointing that out!

**Comment by tilak-puli** [comment]
Just an update:

I see a change in CDK API to set a custom log group from v2.10. 

 https://github.com/aws/aws-cdk/commit/3278c190e1d63d0a99d60c1ae8a2ae690d64113f

**Comment by BoarCub** [comment]
@tilak-puli Were you able to specify a custom log group?
