### ISSUE TITLE
Cannot deploy stack after upgrade from 1.45.0 to 1.46.0

### ISSUE THREAD

**Issue by damonmcminn** [aws/aws-cdk#8678]
On upgrading to 1.46.0 from 1.45.0, I can no longer deploy due to some bootstrap failure.

### Reproduction Steps

`cdk deploy ProjectFoo`

### Environment

  - **CLI Version      : aws-cli/1.16.280 Python/3.8.0 Linux/4.15.0-106-generic botocore/1.13.16**
  - **Framework Version: 1.46.0 (build 63860b2)**
  - **Node.js Version: v12.14.0**
  - **OS               : Ubuntu 18.04**
  - **Language (Version): TypeScript (3.9.3)**

### Other

Deploy fails with the following error:

```sh
ProjectFoo failed: Error: ProjectFoo: publishing assets requires bootstrap stack version '3', found '2'. Please run 'cdk bootstrap' with a newer CLI version.
```

I run `cdk bootstrap` per error message and get the error message:

```sh
Environment aws://123456789012/eu-west-1 failed bootstrapping: Error: Not downgrading existing bootstrap stack from version '2' to version '0'. Use --force to force.
```

I have been deploying successfully with 1.45.0 using the new style stack synthesis as documented [here](https://github.com/aws/aws-cdk/issues/3463#issuecomment-643226516).

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
You need to run the whole command given in the linked comment not only `cdk bootstrap`

**Comment by damonmcminn** [comment]
> You need to run the whole command given in the linked comment not only `cdk bootstrap`

Many thanks - I was unclear that was a need beyond the initial bootstrap - works perfectly now.

**Comment by shivlaks** [comment]
seems like you're all set @damonmcminn - thanks for jumping in and providing guidance @hoegertn 
I'm resolving this issue as I don't believe further action is required.

Feel free to reopen if I missed something.

**Comment by mariusingjer** [comment]
Am I completely blind? Where is the linked comment specifying the correct syntax?

**Comment by mirgj** [comment]
@mariusingjer is referring at the linked comment in the OP message:

You can find it here: https://github.com/aws/aws-cdk/issues/3463#issuecomment-643226516
