### ISSUE TITLE
cdk diff doesn't report any policy created within a role in a included cfn template

### ISSUE THREAD

**Issue by gmiretti** [aws/aws-cdk#8683]
`cdk diff` should report any policy to be created by a deploy. 
This doesn't happen when policy are created in a included template

### Reproduction Steps

Empty python project with stack only doing core.CfnInclude() of template
https://s3.amazonaws.com/aws-transfer-resources/custom-idp-templates/aws-transfer-custom-idp-secrets-manager-apig.template.yml
from https://aws.amazon.com/blogs/storage/enable-password-authentication-for-aws-transfer-for-sftp-using-aws-secrets-manager/

### Error Log

`cdk diff` doesn't report any policy created with a role when template defines 3 roles with their respective policy

### Environment

  - **CLI Version      :** cdk 1.45
  - **Framework Version:** aws-cdk.core==1.45.0
  - **Node.js Version:** v12.18.0
  - **OS               :** Ubuntu 18.04.4
  - **Language (Version):** Python 3.6.9

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @gmiretti ,

when you say `cdk diff` - do you mean the IAM prompt that we show for permission changes?

Thanks,
Adam

**Comment by gmiretti** [comment]
> when you say `cdk diff` - do you mean the IAM prompt that we show for permission changes?

Yes, Adam, sorry for the late reply.
