### ISSUE TITLE
(aws-backup): Incorrect validation of backupvault name

### ISSUE THREAD

**Issue by neharungta** [aws/aws-cdk#8685]
The validation of ```BackupVaultName``` incorrectly allows spaces in the name when creating a ```BackupVault```. The documentation - https://docs.aws.amazon.com/aws-backup/latest/devguide/creating-a-vault.html

The validation needs to be updated.

### Reproduction Steps

```
        @NotNull IBackupVault backupVault = BackupVault
                .fromBackupVaultName(this, "backupvault", "Random Backups");
 ``` 

### Error Log
when running `cdk deploy`

```
backup plan (backupplan0E3CC861) Error in rule Daily : Backup vault name Random Backups is not valid (Service: AWSBackup; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 46443f9d-f5e3-4d8d-9434-bcefaee556da)
```

### Environment

  - **CLI Version      :** `aws-cli/1.16.291 Python/3.7.6 Darwin/17.7.0 botocore/1.13.27` and ```cdk --version``` is `1.45.0 `
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :** Mac
  - **Language (Version):** Java (8)

### Other

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
Closed via #8689
