### ISSUE TITLE
(aws-cdk/aws-ecs): Enable adding custom IAM policies to Task Role

### ISSUE THREAD

**Issue by mutovkin** [aws/aws-cdk#8695]
Ability to add a managed IAM policy to the Fargate FargateTaskDefinition Task Role.

### Use Case

A separate stack is managing access permissions for all roles controlling our environment.  A list of ARNs to managed policies is exported from that stack. Fargate task definition stack is importing that list and attempts to import individual managed IAM policies through ARNs.

Currently, it is only possible to add individual policies to the task role through `addToTaskRolePolicy()` an attempt to add it through direct access to the task role is failing:

`taskDefinition.taskRole.addManagedPolicy(managedPolicy);`

The snippet of the code how I'm trying to add managed policies exported from another stack:

```typescript
    const policiesArns = Fn.importValue(`${policyEnv}-policies-stack-ARNs`);
    policiesArns.split(',').forEach((mpolArn, idx) => {
      const managedPolicy = iam.ManagedPolicy.fromManagedPolicyArn(
          this,
          `${policyEnv}-policies-stack-arn-${idx}`,
          mpolArn
      );
      taskDefinition.taskRole.addManagedPolicy(managedPolicy);
    });
```

### Proposed Solution

Either allow to specify a custom Fargate Task Role or allow to attach managed policies to the auto-created role.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by suankan** [comment]
This would be a handy feature.

**Comment by suankan** [comment]
Without this feature you have to do something like this:
```
import * as iam '@aws-cdk/aws-iam'
import * as ecs '@aws-cdk/aws-ecs'

export class MyApp extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    ...
    const execRole = new iam.Role(this, 'MyAppTaskExecutionRole-', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com')
    })
    execRole.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonECSTaskExecutionRolePolicy'))

    const containerTaskRole = new iam.Role(this, 'MyAppTaskRole-', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com')
    })
    taskRole.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonDynamoDBFullAccess'))
    taskRole.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonSQSFullAccess'))

    const taskDefinition = new ecs.FargateTaskDefinition(this, "MyAppFargateTask-", {
      executionRole: execRole,
      taskRole: taskRole,
    })
    ...

  }
}


```

**Comment by NGL321** [comment]
The feature you are requesting already exists. If you take a look [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateTaskDefinition.html#taskrole), you can see that `taskRole` is of type [`IRole`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.IRole.html) which has a method called `addManagedPolicy()`.

I am not certain whether this was added after the request was made or if this was confusion based on documentation error, but I hope this resolves your concerns!

😸 😷
