### ISSUE TITLE
[CLI] display issues with new deployment monitoring in the CDK CLI

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8696]
_Originally posted by @robertd in https://github.com/aws/aws-cdk/pull/8165#issuecomment-647178526_

It's not working really well on iTerm2 with zsh (using robbierussel/oh-my-zsh)?

Is there a way to use more verbose output (~for CI/CD purposes too~)?

```zsh
➜  sipp-api-cdk git:(master) ✗ cdk deploy
SippApiStack: deploying...
SippApiStack: creating CloudFormation changeset...








 ✅  SippApiStack

Outputs:
SippApiStack.ServiceServiceURL250C0FB6 = https://sipp-api-alb.acme.com
SippApiStack.ServiceLoadBalancerDNSEC5B149E = internal-SippA-Servi-1X2ZSXSR3W328-1234567890.us-west-2.elb.amazonaws.com

Stack ARN:
arn:aws:cloudformation:us-west-2:1234567890:stack/SippApiStack/3841b3e0-b271-11ea-aae2-065639e88e5c
```

.
.
.

**edit**: Luckily everything looks fine in Gitlab's CI/CD pipeline.

![image](https://user-images.githubusercontent.com/31543/85236354-7d9e7300-b3da-11ea-9461-8f68b400374d.png)

**Comment by nija-at** [comment]
_Originally posted by @slotnick in https://github.com/aws/aws-cdk/pull/8165#issuecomment-647998179_

Encountering exactly the same here. Is there an option to disable this mode and revert to the previous display? It’s also useful to understand what happened during the build, which is lost with this update. My working model is to kick off a build, then check back after awhile to see what happened. This change makes that very difficult.

**Comment by Ophirr33** [comment]
I'm seeing a bunch of escape codes being dumped when running `cdk deploy --no-color` in a jenkins job. e.g.,
```
Stack ARN:
arn:aws:cloudformation:eu-central-1:account-num:stack/stack-name/uuid
stack-name
stack-name: deploying...
stack-name: creating CloudFormation changeset...

[K
[K
[K
[K[
[K·
[K·
[K·
[K·
[K·
[K·
[K·
[K·
[K]
[K
[K(
[K0
[K/
[K2
[K)
[K

[20A[K
[K
[K
[K[
[K·
[K·
[K·
[K·
[K·
[K·
[K·
[K·
[K]
[K
[K(
[K0
[K/
[K2
[K)
[K

[20A[K
[K
[K
[K[
[K·
[K·
[K·
[K·
[K·
[K·
[K·
[K·
[K]
[K
[K(
[K0
[K/
[K2
```
Is there a way to revert to the prior display mode when running with `--no-color`?

**Comment by nsstensoriot** [comment]
I agree. While this is very pretty, it's a bit of a hit to usefulness when doing complex debugging of stacks if I can't see what was actually deployed after it's been deployed. Adds a lot of friction to the process.

**Comment by elgordino** [comment]
I would like to add to the request to have an option to revert to the previous behaviour. In the event of a failed deploy it gives basically no feedback as to what went wrong.
```
xxxx: creating CloudFormation changeset...
[████▍·····················································] (1/13)


 ❌  xxxx failed: Error: The stack named xxxx is in a failed state: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStack (/xxx/cdk/node_modules/aws-cdk/lib/api/util/cloudformation.ts:266:11)
```

Previously I could see which components had been deployed and rolled back, now I need to login to the console to find out.

**Comment by blimmer** [comment]
Agreed. In addition to providing an option for people to choose, I think non-interactive terminals (like CI) should default to the other output style. Most (all?) CI platforms set the `CI` environment variable, so maybe when the `CI` variable is set (or another non-interactive terminal is detected), CDK automatically reverts to the old behavior?

**Comment by andreialecu** [comment]
I opened a PR at https://github.com/aws/aws-cdk/pull/9516 that detects whether the `CI` environment variable is set and reverts the output to previous behavior.

It's a minor change, so to anyone that is affected by this: 
* you can install `aws-cdk` locally in the project and use https://www.npmjs.com/package/patch-package to patch it. see https://github.com/aws/aws-cdk/pull/9516/files
