### ISSUE TITLE
[cognito] Invalide check in domainPrefix for cognitoDomain can contain only lowercase alphabets, numbers and hyphens

### ISSUE THREAD

**Issue by evanwieren** [aws/aws-cdk#8703]
**The test is not valid**

Based on the dynamic nature of CDK, the url cannot be properly vetted before deployment. 

https://github.com/aws/aws-cdk/blob/681b3bbc7de517c06ac0bd848b73cc6d7267dfa1/packages/%40aws-cdk/aws-cognito/lib/user-pool-domain.ts#L97

It is actually in lines 93 - 98.  You are testing for the value of the domain.
```
    if (props.cognitoDomain?.domainPrefix &&
      !Token.isUnresolved(props.cognitoDomain?.domainPrefix) &&
      !/^[a-z0-9-]+$/.test(props.cognitoDomain.domainPrefix)) {

      throw new Error('domainPrefix for cognitoDomain can contain only lowercase alphabets, numbers and hyphens');
    }
```

However, this is CDK, and even in cloudformation, and you can generate the domain name dynamically.  As such, validating the url input at this time is not valid. 

To work around the issue I had to use a UUID.

**Comment by nija-at** [comment]
A [fix for this](https://github.com/aws/aws-cdk/commit/681b3bbc7de517c06ac0bd848b73cc6d7267dfa1) has been released in [`1.45.0`](https://github.com/aws/aws-cdk/releases/tag/v1.45.0). Can you check if this fixes the issue?

If not, can you explain what you mean by 'generate the domain name dynamically'.

**Comment by evanwieren** [comment]
Will check. we were running 1.42

**Comment by evanwieren** [comment]
We get the name from a MAP based on account, and a predefined prefix.  This means that the validation will always fail, as the value generated is a token to be evaluated at deployment time. 

There should actually not be a validation here in that case. Only if a hard coded value is used.

For example.  If you set the domainPrefix to  'myuniquestring-${this.account}'   it should be valid.  Actually it would be 
`“pmt-${Token[AWS::AccountId.0]}"`

The string would get rendered in cloudformation as myuniquestring-123456789012. And that would be valid as a domain prefix in cognito and in CFN.

So, the fix that was implemented:

`   if (props.cognitoDomain?.domainPrefix &&
      !Token.isUnresolved(props.cognitoDomain?.domainPrefix) &&
      !/^[a-z0-9-]+$/.test(props.cognitoDomain.domainPrefix)) {

`

However, that is not how ours renders as it is a string with a token in it.  The test does not look at that situation.

**Comment by nija-at** [comment]
`Token.isUnresolved('pmt-${Token[AWS::AccountId.0]}')` will return `true` so this check should not get triggered.

Can you check if that the version of your framework is `1.46.0` and not the version of the CLI? The version of the framework can be found in `package-lock.json` or `yarn.lock` (assuming javascript/typescript).
