### ISSUE TITLE
[cli] cdk synth should allow for an option to compact the template file (remove whitespaces)

### ISSUE THREAD

**Issue by mcliff1** [aws/aws-cdk#8712]
When producing JSON output cdk synth should have an option to minimize the output template file size.

### Use Case
AWS Cloudformation  has a limit on the template body size for an template on S3 at 460,800 bytes.

I had attempted to inject this type of filtering after cdk synth in the `cdk deploy` flow, but quickly got lost.

This will allow deployment of larger stacks.

### Proposed solution
Add an option on CDK Synth that will strip out all white spaces from the output template JSON (in my use case this reduced the size from 500k to 250k).
 
Possibly this could be an option for *cdk.json*

### Other

Using Nested Stacks is the most common way to reduce stack size, in my use case I was doing a lot of with Cross Account CodePipelines which created many permissions objects and was very sensitive to repacking in nested stacks.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rrrix** [comment]
In another life in another project, I was using the AWS Amplify CLI, which also outputs everything as very spacey CloudFormation JSON and had hit that same CloudFormation template file size limit. 

I ended up added a "hook" (hack?) in the Amplify CLI to use `cfn-flip` (https://github.com/awslabs/aws-cfn-template-flip) which converts everything to YAML, and has a `--clean` option (which allows it to fixup Intrinsic Functions to use the shorthand YAML versions). 

Perhaps that might be an option worth looking at? 

A quick test was able to reduce a random template I have from `64K` to `38K` (~40% reduction):

```sh
$ cfn-flip -y -c pipeline.template.json pipeline.template.yaml
$ ll pipeline.template.*
-rw-r--r--  1 user  staff    64K Jun 23 18:24 pipeline.template.json
-rw-r--r--  1 user  staff    38K Jun 24 12:23 pipeline.template.yaml
```

**Comment by mcliff1** [comment]
> In another life in another project, I was using the AWS Amplify CLI, which also outputs everything as very spacey CloudFormation JSON and had hit that same CloudFormation template file size limit.
> 
> I ended up added a "hook" (hack?) in the Amplify CLI to use `cfn-flip` (https://github.com/awslabs/aws-cfn-template-flip) which converts everything to YAML, and has a `--clean` option (which allows it to fixup Intrinsic Functions to use the shorthand YAML versions).
> 
> Perhaps that might be an option worth looking at?
> 
> A quick test was able to reduce a random template I have from `64K` to `38K` (~40% reduction):
> 
> ```shell
> $ cfn-flip -y -c pipeline.template.json pipeline.template.yaml
> $ ll pipeline.template.*
> -rw-r--r--  1 user  staff    64K Jun 23 18:24 pipeline.template.json
> -rw-r--r--  1 user  staff    38K Jun 24 12:23 pipeline.template.yaml
> ```

**Comment by mcliff1** [comment]
@rrrix re: approach of plugging in a hook into `cdk deploy`

I spent a fair amount of time trying to do that and quickly discovered that *deploy* action is pretty complex;  I think a great solution to this feature request could be to enable a hook for 'post-processing' with the deploy.
