### ISSUE TITLE
(aws-appmesh):  Appmesh health check protocol enum does not support GRPC or HTTP/2

### ISSUE THREAD

**Issue by NickBlow** [aws/aws-cdk#8714]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appmesh.Protocol.html does not support GRPC or HTTP/2 even though Cloudformation does

### Reproduction Steps
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appmesh.Protocol.html differs from

https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_HealthCheckPolicy.html

### Error Log
N/A

### Environment

  - **CLI Version      : 1.46.0 (build 63860b2)
  - **Framework Version:** 1.46
  - **Node.js Version:** 12.12
  - **OS               :** Mac OSX 10.14.6
  - **Language (Version):** Javascript, Node 12.12

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by NickBlow** [comment]
I've added the enums in the following PR - let me know if there's anything else I need to do 
https://github.com/aws/aws-cdk/pull/8716

**Comment by MrArnoldPalmer** [comment]
Fixed by #8716
