### ISSUE TITLE
(core): CustomResource - expose ICustomResource public interface

### ISSUE THREAD

**Issue by gradybarrett** [aws/aws-cdk#8717]
Expose the public interface of CustomResource.

### Use Case

Exposing this interface makes it possible to implement patterns like proxy and decorator when building out our own CustomResource interfaces. This is useful because we're encouraged to [subclass CustomResource][cr-docs] and supply our own strongly typed props object to define accepted properties. If we need to perform operations on those properties (e.g. validations, transformations, setting defaults, etc.), then it quickly becomes messy when we have more than one level in our class hierarchy and want to try and clean that up by employing OO patterns (e.g. template methods, etc.).

We also have an interesting scenario where we want to allow consumers to override the resourceType. The two ways I see of doing that currently are to either have them extend our Class and override a template method (only possible if we employ a proxy-like base class), or expose all or part of CustomResourceProps to them as part of our custom resource props - or a secondary props object. Edit: A third option is to expose a setter for resourceType that just does a CfnResource cast and 'Type' Override - this is the option we've gone with.  Is one of these options more preferred?

Perhaps a good summary of this problem statement as a question is, what's the best way to allow extension of our CustomResources while still providing a strongly typed props interface?

### Proposed Solution

Expose the public interface of CustomResource (via ICustomResource?).

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

[cr-docs]: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CustomResource.html

**Comment by bomkamp** [comment]
Also Interested in understanding the best (or intended) approach to implementing CustomResources i.e. Extending CustomResource & setting values or implementing the abstract interface behind the scenes.

+1 👍

**Comment by eladb** [comment]
@gradybarrett Could you please add a concrete example? I am not sure I fully understand the use case/problem.

**Comment by gradybarrett** [comment]
Hi @eladb. Sorry for the delayed response.

Here's a stripped-back class structure sans implementation to keep things simple. Comments in the different Props interfaces indicate implementation needs.  I can fill in more details if needed.

The below code extends CustomResource, which means if I want to do any coercion, defaulting, or validation of props I have to do so before calling `super` and can only use constructor-scoped code or abstract methods to accomplish it. This precludes any ability to use OO patterns to accomplish these tasks, leading to repetitive props handling code in every child class.

If instead, I implemented the public interface of CustomResource and delegated to a this.resource, exactly as CustomResource itself does, then all of a sudden the world is my oyster when it comes to implementing OO patterns. Almost all the constructors disappear from my child classes and code moves into my BaseCustomResource.

Happy to detail out the two paths in code if you'd like, just let me know.

```typescript
class BaseCustomResource extends CustomResource {
  constructor(scope: Construct, id: string, properties: { [key: string]: any }) {
    const crProps: CustomResourceProps = {
      serviceToken: `arn:aws:sns:${Aws.REGION}:571458333875:custom-resource`
    }

    super(scope, id, {
      ...crProps,
      properties: {
        ...properties
      }
    });
  }
}

// Use case base class

interface UseCaseBaseProps {
  /**
   * @default - Default value provided in UseCaseBase
   */
  Name?: string;

  /**
   * @default - Default value provided in UseCaseBase
   */
  Number?: string;
}

class UseCaseBase extends BaseCustomResource {}

// Use Case 1 class

interface SpecificUseCase1Props extends UseCaseBaseProps {
  Action: string;
  /**
   * Secret Data structure must be validated based on value of Action
   */
  SecretData?: { [id: string] : { [id: string] : string } } | { [id: string]: string[] };
}

class SpecificUseCase1 extends UseCaseBase {}

// Use Case 2 class

interface SpecificUseCase2Props extends UseCaseBaseProps {
  /**
   * SearchTags must be filtered, formatted, and validated - e.g. must have at least one search tag
   */
  SearchTags?: string;
}

class SpecificUseCase2 extends UseCaseBase {}
```

**Comment by eladb** [comment]
I am not sure I fully understand the use case for *accepting* an object which implements `ICustomResource`. Custom resources are normally an implementation detail of another abstraction and as such usually do not appear in the public API of another type.

Perhaps a _concrete_ (rather then a conceptual) example would help use better understand how you plan to use this.

**Comment by eladb** [comment]
Closing for now. @gradybarrett follow up when ready.

**Comment by gradybarrett** [comment]
Hi eladb, here's a concrete example from our org. Again, apologies for the delay and let me know. I've put it in a [public repo](https://github.com/gradybarrett/custom-resource-examples).

If you have a different code-sharing preference, then I'm happy to comply.

**Comment by gradybarrett** [comment]
Hey @eladb, just circling back on this to see if there's still potential.
