### ISSUE TITLE
"cdk bootstrap --public-access-block-configuration false" is throwing an error

### ISSUE THREAD

**Issue by ywauto83** [aws/aws-cdk#8728]
```console
cdk bootstrap --public-access-block-configuration false
 ⏳  Bootstrapping environment aws://xxxxxxxxxx/ap-southeast-2...
CDKToolkit: creating CloudFormation changeset...
12:20:33 PM | CREATE_FAILED        | AWS::S3::Bucket       | St
agingBucket
Value of property PublicAccessBlockConfiguration must be an obj
ect
```

### Error Log

```console
 ⏳  Bootstrapping environment aws://xxxxxxxxxx/ap-southeast-2...
CDKToolkit: creating CloudFormation changeset...
12:20:33 PM | CREATE_FAILED        | AWS::S3::Bucket       | St
agingBucket
Value of property PublicAccessBlockConfiguration must be an obj
ect
```

### Environment

  - **CLI Version      :**  1.47.0 (build c2b499a)
  - **Framework Version:** 
  - **Node.js Version:**  12.8
  - **OS :** MAC
  - **Language (Version):** typescript 3.8.3 

### Other

--- 

This is :bug: Bug Report

**Comment by ywauto83** [comment]
1.46.0 is having the same issue

**Comment by RomainMuller** [comment]
Turns out the feature was not tested (and is broken) with "legacy" bootstrap templates. The fix is pretty straight forward... I'm adding an integration test and will ship a PR soon.

**Comment by RomainMuller** [comment]
The faulty feature was added in aws/aws-cdk#8171. The culprit is a missing `Ref:` in front of an `AWS::NoValue` marker.
