### ISSUE TITLE
[codepipeline] Insufficient permissions while pulling source from GitHub

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#8731]
_Originally posted by @jayakumarselvan in https://github.com/aws-samples/aws-cdk-examples/issues/307

I'm trying to make pipeline through AWS CDK with python.

That pipeline simply pulling source from GitHub and deploy to S3 bucket.

When I'm deploy the pipeline (like 'cdk deploy cdkabc'), the pipeline is creting.

But trying to release the pipeline, i'm getting error

**Insufficient permissions**
Unable to connect to the GitHub repository '_reponame_'. Use the console to reconnect your pipeline to GitHub.
The I'm editing the source same pipeline through AWS Console and connect to the GitHub. It is working.

Reference code: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codepipeline_actions.README.html#github

Kindly share the solution or links to resolve this.

**Comment by jayakumarselvan** [comment]
i got the solution from below code

`oauth_token=core.SecretValue.secrets_manager('**secrets_manager_name**', json_field='**secrets_manager_key**'),`

**Comment by skinny85** [comment]
Hey @jayakumarselvan ,

is the Secret you're referencing above for an access token that has read permissions to your GitHub repositories? Like this:

<img width="851" alt="Screen Shot 2020-06-29 at 2 56 47 PM" src="https://user-images.githubusercontent.com/460937/86060039-cc6e8d00-ba18-11ea-8e25-d1a7978f1792.png">

**Comment by jayakumarselvan** [comment]
Yes I given full access to **repo**. (Full control of private repositories).

**Comment by jayakumarselvan** [comment]
> i got the solution from below code
> 
> `oauth_token=core.SecretValue.secrets_manager('**secrets_manager_name**', json_field='**secrets_manager_key**'),`

It is working fine.

**Comment by skinny85** [comment]
I'm glad. Is there anything else we can help you here @jayakumarselvan ?

**Comment by jayakumarselvan** [comment]
Thanks @skinny85 But the thing is need to update document.

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codepipeline_actions.README.html#github

**Comment by skinny85** [comment]
@jayakumarselvan do you mean this part?

```python
    oauth_token=cdk.SecretValue.secrets_manager("my-github-token"),
```

?

**Comment by jayakumarselvan** [comment]
Yes. I think

**Comment by skinny85** [comment]
Well, this depends on how you store your token in SecretsManger. You can store it as PlainText, and it this case `cdk.SecretValue.secrets_manager("my-github-token")` works fine. Or, you can store it as a JSON key-value pair, and in that case you need `cdk.SecretValue.secrets_manager("my-github-token", json_field="my_key")`.

Wondering how to make it clear in the docs the difference between the 2 cases.
