### ISSUE TITLE
[CLI] unable to get local issuer certificate

### ISSUE THREAD

**Issue by ManuLdb** [aws/aws-cdk#8733]
Hi!

I try to learn how to use CDK CLI for AWS but everytime I do an action with the cdk command (cdk ls, cdk synth...) I have this error that show up in the cmd:
`unable to get local issuer certificate`

I'm really new on this. Do you know how I can fix this ? 

Thanks a lot for your help

**Comment by NGL321** [comment]
Hi @ManuLdb!

It looks like this error code is also generated in the [AWS VSCode Toolkit](https://github.com/aws/aws-toolkit-vscode/issues/899). There it is an issue with using the tools with a proxy. 
Are you using a proxy? If so, this may be a bug in the CLI (we [should support](https://github.com/aws/aws-cdk/issues/645) working through a proxy).

Other reproduction information would be helpful as described in our issue templates (operating system, CDK version, npm version, log of errors, etc.).

Please let me know!

😸 😷

**Comment by ManuLdb** [comment]
Hi @NGL321 :)

I'm actually in my company environment so yes with have a Proxy.
 
I have also a bug with this Proxy when I try to update the main plugin/Core of Wordpress: "cURL error 60 SSL certificate problem: unable to get local issuer certificate"

So what you mean is for the moment I can't work with the CDK because of a bug through proxy ? If so I will train myself on another computer and wait for the correction 😸

Thanks a lot

**Comment by satushe** [comment]
Any resolution made over here. or still the issue is in open state.
