### ISSUE TITLE
Template format error: Parameter count 63 is greater than max allowed 60

### ISSUE THREAD

**Issue by reni11111** [aws/aws-cdk#8736]
Cloud formation seems to have limit of 60 parameters, but these parameters are set by DEFAULT by CDK.
I'm just creating lambdas like this:

```
const adminAddUserToGroup = new lambda.Function(this, 'adminAddUserToGroup', {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'changeUserGroup.handler',
      code: lambda.Code.fromAsset('./lambda/AdminAddUserToGroup/'),
      functionName: 'adminAddUserToGroup'
})
```
and 3 parameters for each lambda are created (see **hash** at the picture).

Cloud formation seems to suggest using maps when limit is reached, but this is set by CDK and **there is no documentation** how to modify these default parameters.
(please no solution like just create 2 stacks...)

![image](https://user-images.githubusercontent.com/56836680/85723566-a634ae80-b6f3-11ea-8156-b2c39a072415.png)

**Comment by SomayaB** [comment]
Hi @reni11111, thanks for opening an issue. I wonder if any of the solutions provided here would be helpful? #3266 #3463 
Let us know.

**Comment by eladb** [comment]
Duplicate #3463
