### ISSUE TITLE
[elb] I'm trying to retrieve the listener that is created on port 80 when I create an application load balancer.

### ISSUE THREAD

**Issue by dkboon01** [aws/aws-cdk#8743]
I'm trying to retrieve the listener that is created on port 80 when I create an application load balancer.
I'm trying to use this ApplicationListener.fromApplicationListenAttributes
When I try cdk synth it tells me that:
 AttributeError: type object 'ApplicationListener' has no attribute 'fromApplicationListenerAttributes'

Can you show me what you put after the word scope in your code on line:

>     const albListenerHTTP = ApplicationListener.fromApplicationListenerAttributes(scope, ...);

_Originally posted by @dkboon01 in https://github.com/aws/aws-cdk/issues/7725#issuecomment-649791202_

**Comment by rix0rrr** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.

**Comment by dkboon01** [comment]
Rico
I have
https://stackoverflow.com/questions/62586337/aws-application-load-balancer-finding-the-automatically-generating-a-listener
I'm using the  loadbalancerBuild = elb.ApplicationLoadBalancer(
                    self,
                   f"{ECR_REPO_NAME}-{APP_STAGE_BUILD}-ALB-Fargate1",

# load_balancer_name=f"{ECR_REPO_NAME}-{APP_STAGE_BUILD}-ALB-Fargate1",
                    internet_facing= True,
                    vpc=gbm_vpc,

                )
This generates a default listener on port 80.
In the cdk retrieving something from the same stack is my problem. I dont
see a method that allows "loadbalancerBuild.from_listeners"
I know that you can in yaml do Import_Value - to get values from another
stack. !Ref !GetAtt -- to get values from the same stack.
I've dropped using the cdk now since I couldn't find an answer.Now I'm
using cloudformation and yaml
