### ISSUE TITLE
[cloudformation-include] Add support for YAML templates

### ISSUE THREAD

**Issue by comcalvi** [aws/aws-cdk#8745]
Adding support for YAML templates, since cloudformation accepts both JSON and YAML.

### Use Case

Cloudformation supports both YAML and JSON templates, so the CDK should as well.

### Proposed Solution

I will be opening a PR to address this.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by asterikx** [comment]
What's the motivation for this?

**Comment by skinny85** [comment]
> Btw, what's the motivation for this? Since the synthesized templates are "internal" to CDK, shouldn't you care too much about their format?

This is for the [`cloudformation-include`module](https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html) - this adds support for ingesting a CloudFormation template in YAML format, in addition to JSON. So it's not changing anything in CDK internals, it's about accepting another format as input.

**Comment by asterikx** [comment]
Sorry, missed the module prefix in the title. Please ignore my comment ;-)
