### ISSUE TITLE
[apigateway] WebSocket url output missing from generated cloudformation json

### ISSUE THREAD

**Issue by wzr1337** [aws/aws-cdk#8750]
When you create a RESTApi with APIGateway, the cloud formation template does contain something like:
 
```json
"Outputs": {
    "Endpoint<Id>": {
      "Value": {
        "Fn::Join": [
          "",
          [
            "https://",
            {
              "Ref": "<HTTPEndpoint>"
            },
            ".execute-api.",
            {
              "Ref": "AWS::Region"
            },
            ".",
            {
              "Ref": "AWS::URLSuffix"
            },
            "/",
            {
              "Ref": "EndpointDeploymentStageprod<Id>"
            },
            "/"
          ]
        ]
      }
    }
  }
```

### Use Case

When deploying, you will be prompted the REST API Endpoints but you miss the WebSocket connection endpoints.

### Proposed Solution

Please add a similar output for the WebSocket endpoint so that the cloudformation template contains:

```json
"Outputs": {
    "Endpoint<Id>": {
      "Value": {
        "Fn::Join": [
          "",
          [
            "wss://",
            {
              "Ref": "<WebSocketEndpoint>"
            },
            ".execute-api.",
            {
              "Ref": "AWS::Region"
            },
            ".",
            {
              "Ref": "AWS::URLSuffix"
            },
            "/",
            {
              "Ref": "EndpointDeploymentStageprod<Id>"
            },
            "/"
          ]
        ]
      }
    }
  }
```

* [x] :wave: I may be able to implement this feature request, if someone points me to where "OutPuts" is generated., currently I am blind, do not find the handle
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
What is a websocket endpoint url on a REST API?

**Comment by wzr1337** [comment]
> What is a websocket endpoint url on a REST API?

The WebSocket endpoint is the `wss://....` uri you are connecting to, it is presented in the APIGateway console for your WebSocket API. Very similar to the `https://..` endpoints of a REST API, just a different protocol is reported.

based on 
[AWS API GateWay WebSocket documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-set-up-websocket-deployment.html)

we just need to add

`wss://{api-id}.execute-api.{region}.amazonaws.com/{stageName}`

To the `Outputs` section of the CF

**Comment by nija-at** [comment]
Hi @wzr1337 -

We do not have higher level construct for web socket at this time. This is being tracked here - https://github.com/aws/aws-cdk/issues/2872.

When this is ready, we will provide this URI. Closing in favour of the linked issue.
