### ISSUE TITLE
[CodeBuild] CodePipeline + CodeBuild + SecretsManager/SSM seems to have permission issues

### ISSUE THREAD

**Issue by mikkotikkanen** [aws/aws-cdk#8752]
Trying to add SecretsManager secret (same applies for SSM Parameter Store) to CodeBuild runs into AccessDeniedException when trying to run the CodePipeline. Weird thing is that the env varible is correctly visible and set in Environment Variables in CodeBuild but still can't be accessed by the CodeBuild project. I have also checked that the grantRead actually creates required policies to access the secret but alas, it still keeps complaining that the CodeBuild role can't access it. 

### Reproduction Steps

Stack CodeBuild configuration:
```TypeScript
const roleCodeBuildCdk = new Role(this, 'CodeBuildRole', {
  assumedBy: new ServicePrincipal('codebuild.amazonaws.com'),
});

const secretGithubAccessToken = new Secret(this, 'GithubAccessToken', {
  secretName: 'GithubAccessToken',
});
secretGithubAccessToken.grantRead(roleCodeBuildCdk);

const projectNpmCommand = new PipelineProject(this, 'CdkBuildStage', {
  buildSpec: RunNpmCommand,
  environment: {
    buildImage: LinuxBuildImage.STANDARD_2_0,
    computeType: ComputeType.SMALL,
    environmentVariables: {
      NODE_AUTH_TOKEN: {
        value: secretGithubAccessToken.secretValue,
        type: BuildEnvironmentVariableType.SECRETS_MANAGER,
      },
    },
  },
  role: roleCodeBuildCdk,
});
```

### Error Log

`[Container] 2020/06/26 12:24:35 Phase context status code: Secrets Manager Error Message: AccessDeniedException: User: arn:aws:sts::12...cd2 is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-west-1:12...K11`

### Environment

  - **Framework Version:** v1.45.0
  - **Language (Version):** TypeScript v3.9.5

--- 

This is :bug: Bug Report

**Comment by mikkotikkanen** [comment]
Also, same thing happens when manually setting the policy

```TypeScript
roleCodeBuildCdk.addToPolicy(new PolicyStatement({
  effect: Effect.ALLOW,
  resources: [
    secretGithubAccessToken.secretArn,
  ],
  actions: [
    'secretsmanager:GetSecretValue',
  ],
}));
```

**Comment by skinny85** [comment]
Hi @mikkotikkanen ,

can you try changing this line:

``ts
        value: secretGithubAccessToken.secretValue,
```

to:

```ts
        value: secretGithubAccessToken.secretValue.toString(),
```

and see if that changes anything?

Thanks,
Adam

**Comment by Ray0427** [comment]
I got the same problem.

```
value: credential.secretValueFromJson('BITBUCKET_USERNAME').toString()
```
Got error
`Secrets Manager Error: ResourceNotFoundException: Secrets Manager can't find the specified secret. `

and I fixed it using buildSpec.env.secrets-manager
```
buildSpec: codebuild.BuildSpec.fromObject({
  env: {
    'secrets-manager': {
      BITBUCKET_USERNAME: 'SECRET_ID:BITBUCKET_USERNAME',
    },
  },
})
```

**Comment by zgajo** [comment]
I had the same problem and solved it by adding a policy to CodeBuild

```
  const secret = new secretsmanager.Secret(scope, `Api ${branch} Secret`, {
    secretName: `secret-secrets`,
  });

const cdk_build = new codebuild.PipelineProject(scope, `Build Api Website ${branch}`, {
    buildSpec: codebuild.BuildSpec.fromSourceFilename('./buildspec.yml'),
    environment: {
      buildImage: codebuild.LinuxBuildImage.STANDARD_3_0,
      environmentVariables: {
        SECRET_MANAGER_ARN: { value: secret.secretArn },
      },
    },
  });

  // add policy to allow fetching from secrets manager
  cdk_build.addToRolePolicy(
    new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'secretsmanager:GetRandomPassword',
        'secretsmanager:GetResourcePolicy',
        'secretsmanager:GetSecretValue',
        'secretsmanager:DescribeSecret',
        'secretsmanager:ListSecretVersionIds',
      ],
      resources: [secret.secretArn],
    })
  );

```

**Comment by jaredjj3** [comment]
> I had the same problem and solved it by adding a policy to CodeBuild
> 
> ```
>   const secret = new secretsmanager.Secret(scope, `Api ${branch} Secret`, {
>     secretName: `secret-secrets`,
>   });
> 
> const cdk_build = new codebuild.PipelineProject(scope, `Build Api Website ${branch}`, {
>     buildSpec: codebuild.BuildSpec.fromSourceFilename('./buildspec.yml'),
>     environment: {
>       buildImage: codebuild.LinuxBuildImage.STANDARD_3_0,
>       environmentVariables: {
>         SECRET_MANAGER_ARN: { value: secret.secretArn },
>       },
>     },
>   });
> 
>   // add policy to allow fetching from secrets manager
>   cdk_build.addToRolePolicy(
>     new iam.PolicyStatement({
>       effect: iam.Effect.ALLOW,
>       actions: [
>         'secretsmanager:GetRandomPassword',
>         'secretsmanager:GetResourcePolicy',
>         'secretsmanager:GetSecretValue',
>         'secretsmanager:DescribeSecret',
>         'secretsmanager:ListSecretVersionIds',
>       ],
>       resources: [secret.secretArn],
>     })
>   );
> ```

This only works because `SECRET_MANAGER_ARN` is implicitly a `PLAINTEXT` variable, which is different from OP, which is explicitly a `SECRETS_MANAGER` variable.

For the `value` of a `SECRETS_MANAGER` variable, use the build-spec secrets manager pattern: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.env.secrets-manager
