### ISSUE TITLE
[custom-resources] How to call cfnresponse.send

### ISSUE THREAD

**Issue by amitksahu** [aws/aws-cdk#8760]
As per the latest documents "https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html" cfnresponse is now part of CDK construct. Could you please share some examples of how to implement it using python.
How to call `cfnresponse.send`?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by eladb** [comment]
If you are using `@aws-cdk/custom-resources.Provider` to implement your custom resource, you don't need to interact with `cfnresponse`. 

If the operation succeeds, your lambda handler should return, and optionally return `PhysicalResourceId` and `Data` (attributes). The provider framework will issue a SUCCESS response to CFN. 

If the operation fails, your code should simply throw an error, and the provider framework will issue a FAILED response to CFN.
