### ISSUE TITLE
[ECS] Task definition is generating an extra port mapping that is empty

### ISSUE THREAD

**Issue by thedevopsguyblog** [aws/aws-cdk#8762]
When creating a TaskDef with a container port but no host port, CDK will create an empty port mapping.

Here is the CDK output: https://pastehub.me/S3ScevBrNj 
Original StackOverflow question: https://stackoverflow.com/questions/62498346/ecs-taskdefinition-creation-fails-with-error-invalid-containerport

### Reproduction Steps

```
const taskDefinition = new ecs.Ec2TaskDefinition(this, 'TaskDef',{
      networkMode: "awsvpc",
    });

const prerenderContainer = taskDefinition.addContainer('prerenderContainer', {
      image: ecs.ContainerImage.fromEcrRepository(prerenderRepo),
      cpu: 1024,
      memoryReservationMiB: 8192,

    prerenderContainer.addPortMappings('ports',{
      containerPort: 3000,
    });

const prerenderFleetTGroup = listener.addTargets('ECS', {
      protocol: "HTTP",
      targets:[service.loadBalancerTarget({
        containerName: 'prerenderContainer',
        containerPort: 3000
```

### Error Log

16/31 | 6:03:05 PM | CREATE_FAILED        | AWS::ECS::TaskDefinition                  | TaskDef (TaskDef54694570) Invalid 'containerPort' setting for container 'prerenderContainer'. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 3b24a0da-2834-427e-bb14-29d65469b0d4)

### Environment

  - **CLI Version      :1.44.0**
  - **Framework Version:**
  - **Node.js Version: v10.16.3** 
  - **OS: Mac Catalina 10.15.5 **
  - **Language (Version): Javascript** 

### Other

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
Hi @thedevopsguyblog,

I see here that you have awsvpc network mode. This is relatively unusual for EC2 launch type -- was this intentional?

**Comment by thedevopsguyblog** [comment]
Hi @SoManyHs,

For my troubleshooting and more context please see (this StackOverflow Question)[https://stackoverflow.com/questions/62498346/ecs-taskdefinition-creation-fails-with-error-invalid-containerport]

Originally I tried 'bridge' networking mode but that didn't work. 
Then I tried 'awsvpc' but no luck.

It was then recommended to use awsvpc.

**Comment by DevOtts** [comment]
still waiting for this fix
