### ISSUE TITLE
[ec2] unable to tag subnet created by SubnetConfiguration

### ISSUE THREAD

**Issue by houranii** [aws/aws-cdk#8770]
After creating the subnet with SubnetConfiguration

subnet_public_1 = SubnetConfiguration(cidr_mask=24, name=f'public-1-{namespace}',
                                              subnet_type=SubnetType.PUBLIC)

### Use Case

I'd like to be able to add custom tags to resources created.

        core.Tag.add(subnet_public_1,key='Project',value=f'{namespace}-envname')

### Other

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can, just not on the SubnetConfiguration object but on the Subnets that get created (and are available via the public member publicSubnets) after Vpc instantiation.

We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
