### ISSUE TITLE
ability to add policy statements to RestApi after initialization

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8781]
Originally opened from https://github.com/aws/aws-cdk/issues/2387

From @brettswift - "The resource policy is readonly in the RestApi. It's only injectable at the constructor. This is a problem because I can't get the ARN into the policy to control method level invocations. It seems like there's a chicken/egg situation."

This can be fixed by allowing of `PolicyStatement`s as new methods on RestApi and computing the policy at synthesis time.

**Comment by aereal** [comment]
Hello. I have an intention to implement this, has anyone already worked?

My (abbreviated) solution is:

- Make `policy` to use Lazy value
- add an `addToPolicy` method to `RestApi` and `SpecRestApi`

**Comment by nija-at** [comment]
@aereal - go right ahead

**Comment by aereal** [comment]
@nija-at Thank you!

**Comment by david-wang-1** [comment]
Couldn't "execute-api:/*" be used instead in the policy? Believe that wildcards out to "arn:aws:execute-api:[region]:[account]:[stageid]/*"
