### ISSUE TITLE
[aws-eks] regression in 1.47.0 breaks awsAuth.addRoleMapping

### ISSUE THREAD

**Issue by winjer** [aws/aws-cdk#8786]
calling awsAuth.addRoleMapping clobbers existing role mappings for nodes, which means they can no longer connect to the cluster.

### Reproduction Steps

```
        cluster.awsAuth.addRoleMapping(role, { groups});
```

### Error Log

AccessDenied

### Environment

  - **CLI Version      : 1.47.0**
  - **Framework Version: 1.47.0**

### Other

This worked fine in 1.46.0

--- 

This is :bug: Bug Report

**Comment by winjer** [comment]
Well it looked like it was only in 1.47.0, but I just ran it in 1.46.0 where awsAuth.addRoleMapping was called twice, and that seems to have clobbered the node roles as well.

**Comment by eladb** [comment]
Can you please provide a few more details on what exactly happened to the role mapping? What did you expect and what is the actual result?

**Comment by eladb** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/8901
