### ISSUE TITLE
[appsync] MappingTemplate.dynamoDbGetItem can't specify sortKey (only partitionKey)

### ISSUE THREAD

**Issue by kennu** [aws/aws-cdk#8789]
The AppSync module's MappingTemplate.dynamoDbGetItem and .dynamoDbDeleteItem are missing a way to specify sortKey in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L1242.

The [underlying template](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html#aws-appsync-resolver-mapping-template-reference-dynamodb-getitem) accepts multiple key attributes to specify the full key (partitionKey + sortKey).

### Use Case

Needed for basic DynamoDB tables that use both partitionKey and sortKey.

### Proposed Solution

I made my own template function using the PrimaryKey class like this:

```
function dynamoDbGetItem(primaryKey: PrimaryKey): MappingTemplate {
  return MappingTemplate.fromString(`{"version": "2017-02-28", "operation": "GetItem", ${primaryKey.renderTemplate()}}`);
}
```

By the way, the whole high-level interface to create AppSync APIs is really cool. It looks like a very productive way to create GraphQL APIs fast, with minimal boilerplate.

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Seems this should be fairly easy to fix in a non-breaking way.

Thanks for the report! Additionally, @duarten is working on a proposal for a higher level interface for mapping templates for any interested in checking that out and providing feedback. https://github.com/aws/aws-cdk-rfcs/pull/177

**Comment by duarten** [comment]
Btw, this duplicates https://github.com/aws/aws-cdk/issues/6227.

**Comment by kennu** [comment]
True, I didn't find it with the keywords I searched for before reporting.

**Comment by MrArnoldPalmer** [comment]
Gotcha, closing in favor of #6277. Forgot we had this already.
