### ISSUE TITLE
Reduce the amount of stack trace collection by default

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#8792]
We currently collect stack traces in:
- Every time metadata is added to a construct. This is primarily used to track back CFN deployment issues from L1 to code.
- Every time a token is created. This is used to improve diagnosability when tokens cannot be resolved (the creation stack trace is attached to the error).

I would recommend to:
- Remove stack trace collection from metadata entries
- Only keep stack trace collection in the L1 "logiclID" metadata (this is what we use to show stack traces during deployment in the CLI)
- Disable token stack trace collection by default, but enable when `--debug` or `--verbose` are used.

There are a few switches/context keys that configure this so some due diligence will be needed.

---

This is a :rocket: Feature Request

**Comment by srinivasreddych** [comment]
Hello team. My current CDK project has more than 50 stacks (CDK in python). We are hit by this issue and the response gets slowed when we run cdk ls/synth commands. I have tried setting `disable_traces=False` on the app instantiation, but dint help much. @shivlaks 
- - -
Snippet from app.py
app = core.App(stack_traces=False)
