### ISSUE TITLE
[aws-stepfunctions-tasks] SageMakerCreateTrainingJob AlgorithmSpecification missing EnableSageMakerMetricsTimeSeries

### ISSUE THREAD

**Issue by Samrose-Ahmed** [aws/aws-cdk#8794]
The `AlgorithmSpecification` is missing `EnableSageMakerMetricsTimeSeries` which should be present as per docs (https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_AlgorithmSpecification.html#SageMaker-Type-AlgorithmSpecification-EnableSageMakerMetricsTimeSeries). 

### Other

Need to modify [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/base-types.ts#L20) and [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts#L232).

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@Samrose-Ahmed thanks for the report. This is an experimental service integration so likely has other feature gaps. I'm removing the `bug` label and adding `feature` so we can track exposing these properties.

**Comment by shaeqahmed** [comment]
Hi, I will be contributing to CDK for the first time and would like to pick this one up. Working on it now!
