### ISSUE TITLE
[custom-resources] Allow setting of provider lambda's log retention

### ISSUE THREAD

**Issue by pofallon** [aws/aws-cdk#8815]
Defining a new custom resource provider creates a lambda to wrap the user-provided `onEventHandler` lambda.  The CloudWatch log group for this wrapper lambda has a default retention policy of 'Never Expire'.  It would be helpful if ProviderProps were extended to include a `logRetention` property that could be used to set the log retention of this wrapper lambda.

### Use Case

Without this property, custom resource providers create log groups with logs that will only accumulate over time.

### Proposed Solution

Add a new `logRetention` Provider property that can be used to determine the log retention when creating the wrapper lambda.  This would mimic the lambda property of the same name.  It may also be helpful to create a sensible default when this property is not provided.

### Other

Here's [an example](https://github.com/pofallon/cdk-twitter-activity/blob/7b64e848172d13fc29e800b9adf436f1f27eb490/lib/subscription.ts#L36-L38) of where I would expect to add such a property in my project.  Thank you!

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Sounds good. @pofallon is this something you'd be interested to submit a PR for?

**Comment by pofallon** [comment]
Sure, I'll give it a shot!
