### ISSUE TITLE
[glue] Tags on CfnTrigger not working python (support for tag_resource)

### ISSUE THREAD

**Issue by webysther** [aws/aws-cdk#8832]
Support Glue TagResource:

They create the tags as said in documentation, but only in resource creation, change resource don't do nothing if you change tags.

https://docs.aws.amazon.com/glue/latest/webapi/API_TagResource.html

https://docs.aws.amazon.com/glue/latest/dg/monitor-tags.html

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-glue.CfnTrigger.html#properties

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.tag_resource

**Comment by iliapolo** [comment]
Hi @webysther .

Could you please clarify exactly what you mean? The best way is to provide a code snippet and describe the expected vs the actual behavior. 

I understand you imply there is some issue with tagging a `CfnTrigger`, is it the fact that the `tags` property accepts a `TagManager` rather than a JSON? Please be more specific.

**Comment by webysther** [comment]
@iliapolo They actually work, but only on creation, when you change the tags the cdk apply the changes but not on glue, you need to destroy and recreate.

**Comment by webysther** [comment]
- Create a sample trigger

```python
tags = {
    'project': 'sample',
    'area': 'sales'
}

action = aws_glue.CfnTrigger.ActionProperty(
    job_name=job_client.ref,
)
aws_glue.CfnTrigger(
    self,
    id+project_name,
    name=project_name,
    type='ON_DEMAND',
    actions=[action],
    tags=tags
)
```

- cdk deploy
- change the content of tag, add new one or any change on tags object
- cdk deploy
- nothing happens with tags

**Comment by iliapolo** [comment]
@webysther Gotcha. Thanks for reporting this.
