### ISSUE TITLE
[aws-efs] Getting error while creating efs using aws-cdk and attaching this efs to a lambda created subsequently 

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#8835]
### Environment

  - **CDK CLI Version:** 1.47.0
  - **Module Version:** 1.47.0
  - **Node.js Version:**  12.18.1
  - **OS:**  Windows 10 
  - **Language (Version):** TypeScript (3.9.5)

### Other information
HiTeam,
  I am creating a efs using aws-efs cdk lib and adding a accesspoint to that post creation. After this i am creating a new lambda using cdk and trying to attach the newly created efs in above step. But while deploying my chnages using cdk deploy getting below error.

Error : 
EFS file system <*ARN of efs*> referenced by access point <*ARN of access point of EFS*> has
mount targets created in all availability zones the function will execute in, but not all are in the available life cycle
state yet. Please wait for them to become available and try the request again. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4b74d181-4ef6-4c7a-a2c8-6a08c92d041e)

Can you please help me out in this ?

**Comment by devendra-kumar1** [comment]
I followed below article to solve my issue.
https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#dependencies.

**Comment by revolutionisme** [comment]
@devendra-kumar1 Could you please clarify what exactly you did to fix this issue?

**Comment by devendra-kumar1** [comment]
@revolutionisme : I followed below approach to solve this issue.

1. Create an efs and add access point to it. After this i added below code block to created dependency of Mount target.

const efsDependency = new ConcreteDependable();

fileSystem.node.findAll().forEach((element: any) => {
            if (element.cfnResourceType && element.cfnResourceType === 'AWS::EFS::MountTarget') {
                efsDependency.add(element as IConstruct);
            }
 });

2. Create lambda and add dependency to it using below code block
       tempLambda.node.addDependency(dependency);

It will result lambda creation to be hold until efs and its mount target are in available state.

**Comment by revolutionisme** [comment]
Aah! Right, setting the dependency. Thanks a lot that helps.

**Comment by kitkat729** [comment]
For cloudformation template, add the DependsOn to the Lambda properties waiting for the accesspoint and the all the mount points.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html
