### ISSUE TITLE
[aws-lambda] Cannot get ARN of version obtained via currentVersion

### ISSUE THREAD

**Issue by rigsbyt** [aws/aws-cdk#8841]
`.currentVersion` causes the logical ID of the version resource to be overridden in the prepare step.

I am trying to get the ARN of a version resource elsewhere via `.functionArn` on the resource retrieved by `.currentVersion`

This is causing: `Error [ValidationError]: Template format error: Unresolved resource dependencies [MyFunctionCurrentVersionCAC64D50] in the Resources block of the template`

I can see in the generated template that it's trying to retrieve the Arn via: `Ref MyFunctionCurrentVersionCAC64D50`
But the resource's logical ID is now: `MyFunctionCurrentVersionCAC64D5034e479583e6893cf9f24d9284e5bb773`

### Reproduction Steps

const lambda1 = new Lambda(scope, 'Lambda1', {...})
const lambda2 = new Lambda(scope, 'Lambda2', { enviornment: { dependentLambda: lambda1.currentVersion.functionArn }})

### Error Log

This is causing: `Error [ValidationError]: Template format error: Unresolved resource dependencies [Lambda1CAC64D50] in the Resources block of the template`

### Environment

  - **CLI Version      : 1.47.1**
  - **Framework Version: 1.47.1 **
  - **Node.js Version: 14.2.0** 
  - **OS               : Mac OS X Catalina**
  - **Language (Version): 3.9.2 ** 

### Other

--- 

This is :bug: Bug Report

**Comment by lanefelker** [comment]
I'm encountering the same problem

**Comment by nija-at** [comment]
Unfortunately, I'm unable to reproduce this error. I was able to deploy the following app and check that the environment variable is correctly set.

```ts
```

**Comment by nija-at** [comment]
Unfortunately, I'm unable to reproduce this error. I was able to deploy the following app and check that the environment variable is correctly set.

```ts
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { Code, Function, Runtime } from '@aws-cdk/aws-lambda';

const app = new App();
const stack1 = new Stack(app, 'myfirststack');

const fn1 = new Function(stack1, 'fn1', {
  code: Code.fromInline('foo'),
  runtime: Runtime.NODEJS_12_X,
  handler: 'index.handler'
});

new Function(stack1, 'fn2', {
  code: Code.fromInline('foo'),
  runtime: Runtime.NODEJS_12_X,
  handler: 'index.handler',
  environment: {
    dependentLambda: fn1.currentVersion.functionArn 
  }
});
```

Checking the environment variable after deployment -

```
⇒  aws lambda get-function-configuration --function-name myfirststack-fn2BD2E493A-1X4YEDLT2XJUE --query Environment
{
    "Variables": {
        "dependentLambda": "arn:aws:lambda:eu-west-1:664773442901:function:myfirststack-fn117719295-GG6MWZJF1YB4:1"
    }
}
```

If you're still seeing this error, please provide a similar minimal reproduction CDK app.

**Comment by manhcuogntin4** [comment]
Hi, I have the same problem with when I pass a variable enviroment to lambda to take the first lambda enviroment.
 const COMMAND_LAMBDA_ARN = addCommandUserLambda.functionArn;

    const addCommandUserAsynLambda  = new lambda.Function(this, 'addCommandUserAsynLambda', {
      code: lambda.Code.fromAsset(path.join(__dirname, '../../code/recos')),
      handler: 'add_command_asyn.main_handler',
      runtime: lambda.Runtime.PYTHON_3_8,
      environment: {
        'addCommandUserLambdaArn': COMMAND_LAMBDA_ARN
      }
    })
