### ISSUE TITLE
[wafv2]  Argument of type 'this' is not assignable to parameter of type 'Construct'

### ISSUE THREAD

**Issue by jldsLopez** [aws/aws-cdk#8842]
### The Question

We are facing this error:

>  Argument of type 'this' is not assignable to parameter of type 'Construct'

![image](https://user-images.githubusercontent.com/15650645/86276086-4716e400-bba2-11ea-9ae1-d2ab42fa09d0.png)

when we run a: `npm run build`. 

All our dependencies are set to **1.48.0** version, except **aws-cdk/aws-wafv2** than is set to **1.47.0** version.

![image](https://user-images.githubusercontent.com/15650645/86276347-b8ef2d80-bba2-11ea-8976-f62b03f88373.png)

Usually this error occur when we have some dependencies with different versions in the package.json and we can solve it, setting all dependencies with the same version, as mentioned in this issue: [https://github.com/aws/aws-cdk/issues/7280](https://github.com/aws/aws-cdk/issues/7280)

If  we try to upgrade the wafv2 version to **1.48.0** we get the error:

> No matching version found for @aws-cdk/aws-wafv2@1.48.0

The question is: why is not available @aws-cdk/aws-wafv2@1.48.0 ?

### Environment

  - **CDK CLI Version:** `1.48.0 (build 6080fa8)`
  - **Module Version:** `1.47.0`

  - **Node.js Version:** `v10.16.3`
  - **OS:** Windows 10
  - **Language (Version):** TypeScript (3.8.3)

**Comment by NetaNir** [comment]
I have verified now and version `1.48.0` of `@aws-cdk/aws-wafv2` does exist:
```bash
 neta@ npm view @aws-cdk/aws-wafv2 versions                                                    

[
  '1.19.0', '1.20.0', '1.21.0', '1.21.1',
  '1.22.0', '1.23.0', '1.24.0', '1.25.0',
  '1.26.0', '1.27.0', '1.28.0', '1.29.0',
  '1.30.0', '1.31.0', '1.32.0', '1.32.1',
  '1.32.2', '1.33.0', '1.33.1', '1.34.0',
  '1.34.1', '1.35.0', '1.36.0', '1.36.1',
  '1.37.0', '1.38.0', '1.39.0', '1.40.0',
  '1.41.0', '1.42.0', '1.42.1', '1.43.0',
  '1.44.0', '1.45.0', '1.46.0', '1.47.0',
  '1.47.1', '1.48.0', '1.49.0', '1.49.1'
]

```

Can you try again? Maybe you hit a a point in time where version `1.48.0` was being published? We published all of the `@aws-cdk/*` modules at the same time, but theoretically since each is a separate module, there could be a (short) point in time where not all modules are available in the latest published version.

**Comment by rix0rrr** [comment]
You have found the issue. It is not possible to mix and match CDK library versions.
