### ISSUE TITLE
[apigateway] methodResponses is missing from AwsIntegration

### ISSUE THREAD

**Issue by emurphy58** [aws/aws-cdk#8843]
adding method responses to AWSIntegration options causes this: "Object literal may only specify known properties, and 'methodResponses' does not exist in type 'IntegrationOptions'"

### Reproduction Steps

```
click.addMethod('POST', new apigateway.AwsIntegration({
    service: 'sns',
    path: "arn:aws:apigateway:'us-east-1':sns:path//",
    integrationHttpMethod: 'POST',
    options: {
        credentialsRole: formRedirectRole,
        passthroughBehavior: apigateway.PassthroughBehavior.NEVER,
        requestTemplates: {
            "application/json": "Action=Publish&TopicArn=$util.urlEncode('" + formRedirectSnsTopic.topicArn + "')&Message=$util.urlEncode($input.body)"
        },
        requestParameters: {
            "integration.request.header.Content-Type": "'\'application/x-www-form-urlencoded\''"
        },
        integrationResponses: [{
            statusCode: "200",
            responseTemplates: {
                "application/json": "{\"body\": \"Message received.\"}"
            }
        }],
        methodResponses: [{
            statusCode: "200",
            responseModels: {
                "application/json": "Empty"
            }
        }]
    }
}))
```

The methodResponses part causes the error

### Environment

  - **CLI Version      :** aws-cli/1.18.36
  - **Framework Version:** cdk version 1.48.0 (build 6080fa8)
  - **Node.js Version:** v12.14.1
  - **OS               :** macOS 10.15.5 (19F101)
  - **Language (Version):** TypeScript 3.9.4

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @emurphy58 -

Can you format the code you've pasted so it's more readable and can you describe if the error was during compilation, synthesis or deployment?

**Comment by emurphy58** [comment]
> Hi @emurphy58 -
> 
> Can you format the code you've pasted so it's more readable and can you describe if the error was during compilation, synthesis or deployment?

Reformatted code. It comes from compiling:

```
Type '{ credentialsRole: iam.Role; passthroughBehavior: apigateway.PassthroughBehavior.NEVER; requestTemplates: { "application/json": string; }; requestParameters: { "integration.request.header.Content-Type": string; }; integrationResponses: { ...; }[]; methodResponses: { ...; }[]; }' is not assignable to type 'IntegrationOptions'.
  Object literal may only specify known properties, and 'methodResponses' does not exist in type 'IntegrationOptions'.ts(2322)
aws.d.ts(54, 14): The expected type comes from property 'options' which is declared here on type 'AwsIntegrationProps'
```

**Comment by nija-at** [comment]
The `methodResponses` property is available in the 3rd parameter of the `addMethod()` API.

Your code should instead look like -

```ts
click.addMethod('POST', new apigateway.AwsIntegration({
    service: 'sns',
    path: "arn:aws:apigateway:'us-east-1':sns:path//",
    integrationHttpMethod: 'POST',
    options: {
        credentialsRole: formRedirectRole,
        passthroughBehavior: apigateway.PassthroughBehavior.NEVER,
        requestTemplates: {
            "application/json": "Action=Publish&TopicArn=$util.urlEncode('" + formRedirectSnsTopic.topicArn + "')&Message=$util.urlEncode($input.body)"
        },
        requestParameters: {
            "integration.request.header.Content-Type": "'\'application/x-www-form-urlencoded\''"
        },
        integrationResponses: [{
            statusCode: "200",
            responseTemplates: {
                "application/json": "{\"body\": \"Message received.\"}"
            }
        }],
    }
}), {
  methodResponses: [{
    statusCode: "200",
    responseModels: {
      "application/json": "Empty"
    }
  }],
})
```

**Comment by medaboub** [comment]
below a complete sample in python 👍 


import os
from constructs import Construct
import aws_cdk.aws_ssm as ssm
from aws_cdk import (  
    CfnOutput,
    RemovalPolicy,  
    aws_lambda as _lambda,
    aws_s3 as s3,
    aws_apigateway as apigw,
    aws_iam as iam ,
    Stack 
)

class MYAWSLambdas(Stack):

    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)  
      
        # aws lambda function : https://gitlab.com/tt4605738/aws_lambda    
        self.lambda_function1()

    

    # aws lambda function : https://gitlab.com/tt4605738/aws_lambda  
    def lambda_function1(self):            
        function1=_lambda.Function(self,                                                                    
                        'function1',
                        current_version_options=_lambda.VersionOptions(
                               removal_policy=RemovalPolicy.RETAIN,  # retain old versions
                               retry_attempts=1
                        ),
                        runtime=_lambda.Runtime.PYTHON_3_12,
                        code=_lambda.Code.from_bucket(s3_bucket,key),
                        handler='app.lambda_handler'
                        )   
        _lambda.Alias(self,"dev",alias_name="dev",version=function1.current_version)
        _lambda.Alias(self,"prod",alias_name="prod",version=function1.current_version)

        stageLambda=_lambda.Function.from_function_arn(self,"function1-stage",function1.function_arn+":${stageVariables.alias}")
        
        credentialsRole=iam.Role(self,'apigateway-api-role',assumed_by=iam.ServicePrincipal("apigateway.amazonaws.com"))
        credentialsRole.add_to_policy(iam.PolicyStatement(actions=['lambda:InvokeFunction'],resources=[function1.function_arn,function1.function_arn+":*"],effect=iam.Effect.ALLOW))
         
        integration = apigw.AwsIntegration(service='lambda',path="2015-03-31/functions/"+stageLambda.function_arn+"/invocations",options=apigw.IntegrationOptions(credentials_role=credentialsRole))  
        
        api =  apigw.RestApi(self, "function1_api") 
        api.root.add_method('ANY', integration)

        mydeployment=apigw.Deployment(self,"my_deployment",api=api)
        devStage=apigw.Stage(self,"devStage",deployment=mydeployment,variables={"alias":"dev"})
        prodStage=apigw.Stage(self,"prodStage",deployment=mydeployment,variables={"alias":"prod"})

        CfnOutput(self, "function1-arn", value=function1.function_arn)      
        CfnOutput(self, "dev-api-url", value=devStage.url_for_path)
        CfnOutput(self, "prod-api-url", value=prodStage.url_for_path)
