### ISSUE TITLE
Improve error messages for missing build dependencies

### ISSUE THREAD

**Issue by ericzbeard** [aws/aws-cdk#8847]
I'd like to spend some time working on the experience for a new contributor who misses some of our dependencies. You end up getting pretty deep into a build before you discover things like missing .net core, or that you have a globally installed version of typescript/tslint that is not compatible. The error messages you get from the build are hard to interpret.

### Proposed Solution

Add checks early in the build process to look for the correct version of all dependencies and emit a clear error message.

### Other

Here's an example that I think is the result of not installing .net core:

FAIL test/init.test.js (6.873s)
aws-cdk:   ● verify "future flags" are added to cdk.json
aws-cdk:     Could not add project AwsCdkTestHnYKc5.csproj to solution AwsCdkTestHnYKc5.sln. Error code: 127
aws-cdk:       at ChildProcess.<anonymous> (../../../../../../private/var/folders/hw/7qx39xm96h719bjttttbf_903hyzmd/T/aws-cdk-testHnYKc5/tmp/add-project.hook.ts:29:16)

* [ x] :wave: I may be able to implement this feature request
---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
P.S. we don't consider this a "core" issue. Perhaps "build"

**Comment by ericzbeard** [comment]
Fixed by #8929
