### ISSUE TITLE
[core] Inconsistent context type(s)

### ISSUE THREAD

**Issue by fogfish** [aws/aws-cdk#8865]
The CDK context is defined as a pair `string -> any`

```
ConstructNode.setContext(key: string, value: any): void
ConstructNode.tryGetContext(key: string): any
```

However `AppProps` defines a context as `string -> string` pair.

```
export interface AppProps {
  ...
  readonly context?: {
        [key: string]: string;
    };
}
```

### Reproduction Steps

Once an application start to use JSON structs as a context value then it becomes almost impossible to mock an application with the context (everything works with deployment because context is passed via cdk.json):

```
const app = new cdk.App({ context: { /* do not allow to pass anything then string -> string pairs */  }  })
app.node.setContext() // fails with error message "unable to modify a tree (or something like that)
```   

Here two major question:
1. Is the usage of JSON structs is valid in the context? I believe yes, because of `Vpc.fromLookup` does it.
2. Should we change the `cdk.App` to accept `string -> any` pair so that we can mock the context

### Environment

  - **CLI Version      :** 1.47.1 (build 8bb7c0d)
  - **Framework Version:**
  - **Node.js Version:** v12.12.0
  - **OS               :** Mac
  - **Language (Version):**TypeScript (3.8.3)

**Comment by eladb** [comment]
Let's change to `any`. @fogfish would you like to submit a PR?
