### ISSUE TITLE
[aws-codebuild]  Codebuild source Github PR doesn't work with FILE_PATH 

### ISSUE THREAD

**Issue by Nikamura** [aws/aws-cdk#8867]
Trying to create codebuild project with github source and adding pull request created/updated trigger with file_path filter results in an error, while this succeeds doing in the UI.

### Reproduction Steps

```codebuild.FilterGroup.inEventOf(codebuild.EventAction.PULL_REQUEST_UPDATED).andFilePathIsNot("^my_path.*")```

### Error Log

```
node_modules/@aws-cdk/aws-codebuild/lib/source.ts:411
      throw new Error('A file path condition cannot be added if a Group contains any event action other than PUSH');
            ^
Error: A file path condition cannot be added if a Group contains any event action other than PUSH
    at FilterGroup.addFilePathFilter (node_modules/@aws-cdk/aws-codebuild/lib/source.ts:411:13)
    at FilterGroup.andFilePathIsNot (node_modules/@aws-cdk/aws-codebuild/lib/source.ts:360:17)
    at new CodebuildStack (src/codebuild-stack.ts:16:93)
    at Object.<anonymous> (bin/codebuild.ts:9:15)
```

### Environment

  - **CLI Version      :** 
  - **Framework Version:** 1.49.0
  - **Node.js Version:** 
  - **OS               :** 
  - **Language (Version):**  TypeScript (3.9.5)

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @Nikamura ,

thanks for opening the issue. Looks like this changed since we introduced our validation. [The docs now say](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_WebhookFilter.html#CodeBuild-Type-WebhookFilter-type):

> #### `FILE_PATH`
>
> A webhook triggers a build when the path of a changed file matches the regular expression pattern.
>
> **Note**
> Works with GitHub and Bitbucket events push and pull requests events. Also works with GitHub Enterprise push events, but does not work with GitHub Enterprise pull request events.

Looks like we're still validating GitHub (and most likely BitBucket) sources the same way we do GitHub Enterprise ones.

This needs a code change from our side. It should be a simple change [here](https://github.com/aws/aws-cdk/blob/c49c39c4e6fc1b1340b0f7a2eeaec1337cfced82/packages/%40aws-cdk/aws-codebuild/lib/source.ts#L410-L412), so if you want to open is a Pull Request, that would be awesome - see [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#getting-started) for more info on how to get started with developing the CDK.

In the meantime, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) in the CDK to unblock yourself.

Thanks,
Adam

**Comment by VishnuSM** [comment]
> Hi @Nikamura ,
> 
> thanks for opening the issue. Looks like this changed since we introduced our validation. [The docs now say](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_WebhookFilter.html#CodeBuild-Type-WebhookFilter-type):
> 
> > #### `FILE_PATH`
> > A webhook triggers a build when the path of a changed file matches the regular expression pattern.
> > **Note**
> > Works with GitHub and Bitbucket events push and pull requests events. Also works with GitHub Enterprise push events, but does not work with GitHub Enterprise pull request events.
> 
> Looks like we're still validating GitHub (and most likely BitBucket) sources the same way we do GitHub Enterprise ones.
> 
> This needs a code change from our side. It should be a simple change [here](https://github.com/aws/aws-cdk/blob/c49c39c4e6fc1b1340b0f7a2eeaec1337cfced82/packages/%40aws-cdk/aws-codebuild/lib/source.ts#L410-L412), so if you want to open is a Pull Request, that would be awesome - see [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#getting-started) for more info on how to get started with developing the CDK.
> 
> In the meantime, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) in the CDK to unblock yourself.
> 
> Thanks, Adam

@skinny85 Can we use FILE_PATH filter with Github Enterprise one's still???

**Comment by skinny85** [comment]
> @skinny85 Can we use FILE_PATH filter with Github Enterprise one's still??? I am not using CDK but configuring my codebuild from the UI.

@VishnuSM I believe the answer is "no", according to the [CodeBuild documentation](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_WebhookFilter.html#CodeBuild-Type-WebhookFilter-type).

**Comment by VishnuSM** [comment]
@skinny85 Following is a question regarding AWS CodeBuild.
I have configured a Webhooks which will trigger my build on pull requests events. During the build I need the list of changed files in the PR to do certain operations on them. Do we have anything which we can use in CodeBuild.

The closest I encountered is CODEBUILD_RESOLVED_SOURCE_VERSION environment variable. But this refers only to the recent commit SHA.

Additionally I was also thinking of consuming the GitHub Webhook payload URL to get the data regarding the changed files etc.

Any help around this is highly appreciated.

Thanks & Regards,
Vishnu.S

**Comment by skinny85** [comment]
You will have to use the GitHub API to get this data inside of your CodeBuild job.

**Comment by VishnuSM** [comment]
@skinny85 
I'm using a Lambda Function (written in Python) and connecting to an RDS instance. This Lambda Function is highly used(i.e invocations per minute is close to 7k -8k), but sometimes my lambda gets a connection timeout issue when trying to make an RDS connection.
Please note that this is an intermittent issue and the Lambda function and RDS are under the same VPC.
**NOTE: I'm using pymysql to create a mysql connection**

Any help around this is highly appreciated.

Thanks & Regards,
Vishnu.S

**Comment by skinny85** [comment]
@VishnuSM I think this is outside the purview of CDK. Sine it "usually" works, I think the CDK setup is correct, and you need to dig into the details of the services that you are using (in this case, Lambda and RDS) to figure out why is this happening.
