### ISSUE TITLE
[ec2]  Reference Subnets CIDR Block

### ISSUE THREAD

**Issue by kferrone** [aws/aws-cdk#8873]
Allow user to reference the CidrBlock from a subnet. 

### Use Case

I want to use the subnet value elsewhere, e.g. a security group.

### Proposed Solution

Make the cidr block a token like other props on subnet.

I would like to use the following:
```typescript
subnet.cidrBlock
```
instead of
```typescript
(subnet.node.defaultChild as ec2.CfnSubnet).cidrBlock
```

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Duplicate of #3951
