### ISSUE TITLE
[CLI] generate environment settings on cdk init

### ISSUE THREAD

**Issue by arjanschaaf** [aws/aws-cdk#8875]
I learned today that several issues I encountered are all related to the same root cause: I forgot to set the environment as documented: https://docs.aws.amazon.com/cdk/latest/guide/environments.html

I assumed that using `cdk --profile` would have configured the cdk with all the information about my environment. But it turns out you need to point the environment of your stack to the settings provided by `--profile`:

```
new MyDevStack(app, 'dev', { 
  env: { 
    account: process.env.CDK_DEFAULT_ACCOUNT, 
    region: process.env.CDK_DEFAULT_REGION 
}});
```

Not setting this environment leads to environment-agnostic stacks, which is fine but can result in really strange behaviour. For example when filtering subnets on availability zones.

### Use Case

Prevent easy to make mistakes that leads to hard to debug situations.

### Proposed Solution

Why not generate code on `cdk --profile myprofile init app --language=typescript` that includes the environment. Currently the generated code for the generate App looks like:

```
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { TestCdkStack } from '../lib/test-cdk-stack';

const app = new cdk.App();
new TestCdkStack(app, 'TestCdkStack');
```

if that could be changed to:

```
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { TestCdkStack } from '../lib/test-cdk-stack';

const app = new cdk.App();
new TestCdkStack(app, 'TestCdkStack', {
  env: { 
    account: process.env.CDK_DEFAULT_ACCOUNT, 
    region: process.env.CDK_DEFAULT_REGION 
}});
```

this could save people starting out with the CDK quite a bit of frustration.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by arjanschaaf** [comment]
Another suggestion might be to warn users when executing CDK commands that these settings aren't set and therefore the created stack is _environment-agnostic_

**Comment by shivlaks** [comment]
@arjanschaaf is there a reason why the `--profile` would matter in the suggestion above to include an environment.

I believe the current init templates are environment agnostic, but I could certainly see some value in generating a default environment configuration as you've suggested. However, I'd expect it to work regardless of whether `--profile` is used. i.e. If I were to configure credentials by running `aws configure` with the AWS CLI

**Comment by arjanschaaf** [comment]
@shivlaks : you're right: the fact that I pass the environment with `--profile` should not matter. The issue is the different behaviour of the CDK when creating environment agnostic configuration or not.
I wasn't expecting that difference in behaviour at all. Looking back at it, the distinction is made in documentation but I think the CDK can better support its users by making the difference in behaviour more explicit one way or another.
