### ISSUE TITLE
[lambda] IFunctionOptions and IEventInvokeConfigOptions in C# library not forcing my class to implement public properties

### ISSUE THREAD

**Issue by cal5barton** [aws/aws-cdk#8880]
When trying to create my own class that implements IFunctionOptions and IEventInvokeConfigOptions my class is not forcing me to implement any properties.

### Reproduction Steps

    /// <summary>
    /// My class
    /// </summary>
    public class MyClass : IFunctionOptions
    {

    }

### Error Log

No errors

### Environment

  - **CLI Version      :** 1.47.1
  - **Framework Version:** 1.47.1
  - **Node.js Version:**  12.16.3
  - **OS               :** Windows 10
  - **Language (Version):**  C#

### Other

https://stackoverflow.com/questions/62704780/c-sharp-not-forcing-class-to-implement-public-interface

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
That's likely because, in both cases, all of the properties are optional. So an empty class with none of the defined is valid.

**Comment by cal5barton** [comment]
It appears to be using the C# 8 feature of[ interface default implementations.](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods#:~:text=Members%20with%20bodies%20permit%20the,are%20not%20permitted%20in%20interfaces.) The optional/nullable properties doesn't make it valid necessary. See the following code:

```
class MyClass : IFunctionOptions, IMyOptions
{
    public string? SomeProp => throw new System.NotImplementedException();
}

interface IMyOptions
{
    string? SomeProp { get; }
}
```

If I don't have a default implementation it still forces me to implement the property on the class or it will not compile. Since I have no idea what the default implementations are for the properties of IFunctionOptions and IEventInvokeConfigOptions I'm unsure of what I would need to set in order for it to function properly.

**Comment by nija-at** [comment]
> Since I have no idea what the default implementations are for the properties of IFunctionOptions and IEventInvokeConfigOptions

All of the defaults are documented here - https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.Lambda.IFunctionOptions.html#properties

>  I'm unsure of what I would need to set in order for it to function properly.

Why are you trying to set the values for all properties here? 

You should only need to set the properties for the ones that you are interested in. Not setting any of the optional properties should set the function up correctly.

Sometimes, we may add error messages for missing properties that will be thrown when the app is synthesized.
This is usually done when one optional property is configured by the user but expects another one to also be configured is or configured incorrectly.

**Comment by cal5barton** [comment]
@nija-at  do you have a working example of setting a property like FunctionName for the interface? The property on the interface is not settable, when inherited on the class it's not available to set, so I'm still unclear how I'm supposed to set this.

Also the documentation you linked shows that those properties are virtual, however, I'm not able to override any of those.

**Comment by nija-at** [comment]
We have quite a few examples in the 'aws-cdk-examples' repository. Here's one - https://github.com/aws-samples/aws-cdk-examples/blob/master/csharp/random-writer/src/RandomWriter/RandomWriterStack.cs#L40

**Comment by SomayaB** [comment]
@cal5barton Were you able to solve your issue with the example provided? If so, I'd like to close this issue.

**Comment by cal5barton** [comment]
Not exactly. I ended up going a different route because the examples provided did not solve the problem of implementing my own version of IFunctionOptions.

**Comment by SomayaB** [comment]
@cal5barton I'm sorry the examples didn't work out for you but I'm glad you figured out another way. I will close this issue for now. Feel free to reopen.
