### ISSUE TITLE
[aws-events] Don't render undefined 'enabled' state 

### ISSUE THREAD

**Issue by ben-eb** [aws/aws-cdk#8890]
Hello :wave:

Currently, the implementation of [`Rule`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.Rule.html) means that if the `enabled` property is not set, it is defaulted to `true`. 

### Use Case

We have a use case where we want to turn off rules at certain times of the year, and would like to do this independently of deploying the stack. We are planning to write a script that looks at a list of EventBridge rules across multiple stacks and so our implementation would be simpler if it didn't have to co-ordinate changes across those repositories.

### Proposed Solution

In CloudFormation, the `State` is optional: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

I would like to propose that this property can be left unset and a default value not provided, in order to allow state changes independently of deploying the stack.

### Other

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Aha interesting. I take it that leaving the value out will "leave the current enabled state" alone.

That makes sense, but what is the default behavior if the rule is created for the first time and `enabled` is not set? Is it created as enabled or disabled?

As a wordaround, you can use the escape hatch mechanism to delete the property.

**Comment by ben-eb** [comment]
@rix0rrr Hello, thanks for getting back to me 🙂 

I've double checked the behaviour and indeed, the Rule is created `enabled` if you do not set a value. You can verify for yourself with this stack:

```ts
import * as cdk from '@aws-cdk/core';
import {Code, Function as AWSLambda, Runtime} from '@aws-cdk/aws-lambda';
import {CfnRule, Rule, Schedule} from "@aws-cdk/aws-events";
import {LambdaFunction} from "@aws-cdk/aws-events-targets";

const lambdaCode = `
const handler = async event => {
  console.log(event);
  return event;
};

exports.handler = handler;
`;

export class DemoStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const handler = new AWSLambda(this, 'lambda', {
      functionName: 'log-event-lambda',
      runtime: Runtime.NODEJS_12_X,
      code: Code.fromInline(lambdaCode),
      handler: 'index.handler',
    });

    const trigger = new Rule(this, 'lambda-trigger', {
      description: 'Triggers the log event lambda automatically',
      schedule: Schedule.cron({
        minute: '25',
      }),
      targets: [new LambdaFunction(handler)],
    });

    const cfnRule = trigger.node.defaultChild as CfnRule;

    cfnRule.addDeletionOverride('Properties.State');
  }
}
```

Thanks for the tip about the escape hatches, this unblocks me for now! 🎉
