### ISSUE TITLE
[aws-elasticloadbalancingv2] Constructing a ListenerRule Condition value from SecretValue runs into character limit error

### ISSUE THREAD

**Issue by dammg** [aws/aws-cdk#8904]
Hi,

I'm currently trying to generate a forward rule with basic authentication for my load balancer and since I don't want the user and password in my source code I'm using a SecretValue from the SecretManager. Unfortunately when I try to deploy the stack update, I get an error telling me that I used to many characters for the http-header value (see log below).

Is it maybe possible to validate the character length at a later stage, when the value has been resolved?

I could not find anything regarding this issue (neither stackoverflow nor issues in here) and it is also not quite clear not me, whether dynamic references such as these are allowed in this instance or not.

### Reproduction Steps
Here is the relevant part of the generated cdk JSON:

```
"MyListenerRuleBasicauth" : {
  "Type" : "AWS::ElasticLoadBalancingV2::ListenerRule",
  "Properties" : {
	"Actions" : [ {
	  "TargetGroupArn" : {
		"Ref" : "MyTargetGroup"
	  },
	  "Type" : "forward"
	} ],
	"Conditions" : [ {
	  "Field" : "http-header",
	  "HttpHeaderConfig" : {
		"HttpHeaderName" : "Authorization",
		"Values" : [ {
		  "Fn::Join" : [ "", [ "Basic ", {
			"Fn::Base64" : "{{resolve:secretsmanager:arn:aws:secretsmanager:eu-central-1:xxxxxxxxx:secret:my/secret-??????:SecretString:USER::}}:{{resolve:secretsmanager:arn:aws:secretsmanager:eu-central-1:xxxxxxxxx:secret:my/secret-??????:SecretString:PASSWORD::}}"
		  } ] ]
		} ]
	  }
	}, {
	  "Field" : "path-pattern",
	  "PathPatternConfig" : {
		"Values" : [ "/mypath/*" ]
	  }
	} ],
	"ListenerArn" : {
	  "Fn::ImportValue" : "MyListenerArn"
	},
	"Priority" : 123
  }
}
```

### Error Log

Here is the relevant part of the cdk deploy log:

```
eop-core: creating CloudFormation changeset...
 0/5 | 11:02:22 | UPDATE_IN_PROGRESS   | AWS::ElasticLoadBalancingV2::ListenerRule        | EopWebdavEopWebContentListenerRule-basicauth (EopWebdavEopWebContentListenerRulebasicauth) 
 0/5 | 11:02:22 | UPDATE_FAILED        | AWS::ElasticLoadBalancingV2::ListenerRule        | EopWebdavEopWebContentListenerRule-basicauth (EopWebdavEopWebContentListenerRulebasicauth) Condition value for 'http-header' cannot contain more than 128 characters (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: 09ca9ac3-def1-4208-bc71-79f8841c4183)
	obj._wrapSandboxCode (/tmp/jsii-java-runtime3396676308723859268/jsii-runtime.js:7915:49)
	\_ Kernel._wrapSandboxCode (/tmp/jsii-java-runtime3396676308723859268/jsii-runtime.js:8388:20)
	\_ Kernel._create (/tmp/jsii-java-runtime3396676308723859268/jsii-runtime.js:7915:26)
	\_ Kernel.create (/tmp/jsii-java-runtime3396676308723859268/jsii-runtime.js:7659:21)
	\_ KernelHost.processRequest (/tmp/jsii-java-runtime3396676308723859268/jsii-runtime.js:7439:28)
	\_ KernelHost.run (/tmp/jsii-java-runtime3396676308723859268/jsii-runtime.js:7377:14)
	\_ Immediate.setImmediate [as _onImmediate] (/tmp/jsii-java-runtime3396676308723859268/jsii-runtime.js:7380:37)
	\_ runCallback (timers.js:705:18)
	\_ tryOnImmediate (timers.js:676:5)
	\_ processImmediate (timers.js:658:5)
```

### Environment

  - **CLI Version      :** aws-cli/1.16.230 Python/2.7.13 Linux/4.12.14-95.48-default botocore/1.12.220
  - **Framework Version:** AWS CDK 1.47.0
  - **Node.js Version:** v10.14.2
  - **OS               :** Linux
  - **Language (Version):** Java (8) (1.8.0_202)

### Other

PS: I also tried to use the full base64-encoded value as a single secret value (so without the fn:join and fn:base64), which then barely fits the 128 characters limit. But then I get an error telling me that I'm using invalid characters: 
`Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@! (Service: AWSSecretsManager; Status Code: 400; Error Code: ValidationException; Request ID: bf0c3a3a-2177-4ef4-9c4e-091995596316)`

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.

-------

Having said that, as far as I can tell what you're doing looks fine. It should be easy enough to get your secret down to under 128 characters.

The second error looks like it has to be something else. Looks like it's complaining about the SecretsManager Secret name you used there.

It is not possible to validate the value after resolving (at least not as far as I know), and I *think* dynamic references to Secrets Manager Secrets are allowed anywhere.

**Comment by dammg** [comment]
Hey, thanks for your reply. The hint about the Secret name was correct and I was able to fix the issue with invalid characters.

Unfortunately I still have to use the entire base64-encoded auth header as a secret value, in order to keep the length of the dynamic reference to under 128 characters. That was my original issue and it was not meant as a support question but rather to showcase an inconsistency in the Cloudformation validation. Since dynamic references do work in this instance it does not make a lot of sense to limit the character length of the value to 128. Dynamic references can get a lot longer than that.

**Comment by VibinBVD** [comment]
@dammg  could you please let me know what solved the invalid characters issue, running into same error and not able to figure out

**Comment by dammg** [comment]
@VibinBVD It's been a while, so I'm having trouble recollecting the issue in its entirety. But I believe my last comment says it all. We used the full base64-encoded auth header as a secret, which just about fits the 128 characters. My second issue with the invalid characters was resolved, by normalizing the secret name (I believe it had bracket characters in it).

I hope this helps.
