### ISSUE TITLE
[apigateway v2] Custom domain for API Gateway V2

### ISSUE THREAD

**Issue by salsa2k** [aws/aws-cdk#8908]
Custom domain for API Gateway V2.

### Use Case

Here we have the documentation to create custom domains for API Gateway and routes on Route 53. But sadly the same thing doesn't work for Api Gateway V2.

I have tried to apply the same config using v2.

```
const certificate = Certificate.fromCertificateArn(
      this,
      "Certificate",
      CERTIFICATE
    );

    const customDomain = new CfnDomainName(this, "CustomDomain", {
      domainName: 'dev.mydomain.com',
      domainNameConfigurations: {
        certificateArn: certificate.certificateArn,
        endpointType: EndpointType.REGIONAL,
      },
    });

    const mappings = new CfnApiMapping(this, "Mapping", {
      apiId: this.api.ref,
      domainName: customDomain.domainName,
      stage: this.stage.stageName,
    });
    mappings.addDependsOn(customDomain);

    new ARecord(this, "CustomDomainApiRecord", {
      zone: props.zone,
      recordName: 'dev.mydomain.com',
      target: RecordTarget.fromAlias({
        bind: (_record) => ({
          hostedZoneId: props.zone.hostedZoneId,
          dnsName: this.api.ref,
        }),
      }),
    });
```

There is 2 problems here:
1. In CfnDomainName I'm not able to use domainNameConfigurations, looks like this interface is broken.
2. For route 53 ARecord, in @aws-cdk/aws-route53-targets there is no support for Api Gateway V2.

* [ x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by salsa2k** [comment]
With the cdk 1.5.0 I'm now able to "create" like that:

```
    const domainName = new DomainName(this, "CustomDomain", {
      domainName: 'dev.mydomain.com',
      certificate,
    });

    const mappings = new CfnApiMapping(this, "Mapping", {
      apiId: this.api.ref,
      domainName: 'dev.mydomain.com',
      stage: 'development',
    });

    const record = new ARecord(this, "CustomDomainApiRecord", {
      recordName: 'dev.mydomain.com',
      zone: props.zone,
      target: RecordTarget.fromAlias({
        bind: () => ({
          dnsName: domainName.regionalDomainName,
          hostedZoneId: domainName.regionalHostedZoneId,
        }),
      }),
    });
```

The only problem here is, that mapping doesn't get applied at the same time of the api.
This means, that I need comment out the mapping section, deploy the stack, then uncomment the mapping section and deploy again to make it work.

I'm getting this error:
```
Invalid stage identifier specified (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 595ea925-3097-4e80-b4dc-7f571c0d7314; Proxy: null
```

**Comment by nija-at** [comment]
> In CfnDomainName I'm not able to use domainNameConfigurations, looks like this interface is broken.

Could you expand on this? What are you looking for? What is `domainNameConfigurations`?

> For route 53 ARecord, in @aws-cdk/aws-route53-targets there is no support for Api Gateway V2.

I've opened a separate issue to track this - https://github.com/aws/aws-cdk/issues/8941

**Comment by salsa2k** [comment]
Hi @nija-at as I have mentioned in my [last comment](https://github.com/aws/aws-cdk/issues/8908#issuecomment-655073685), CfnDomainName now can be replaced by DomainName (v 1.5.0), this one looks fine.

The problem now is with Mappings, that cannot be created at the same time of api, and the ARecord that don't have support in @aws-cdk/aws-route53-targets

**Comment by nija-at** [comment]
> The problem now is with Mappings, that cannot be created at the same time of api.

Mappings are also supported in the API - [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html#custom-domain) and [HttpApiMapping](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpApiMapping.html)

Does this satisfy? If not, can you expand what specifically is missing?

**Comment by rorcores** [comment]
"No value exists in scope for the shorthand property 'certificate'. Either declare one or provide an initializer." is now always displayed when trying to create new domain.
