### ISSUE TITLE
[aws-cloudwatch] Incorrect comparison operator for alarm annotation label

### ISSUE THREAD

**Issue by jebaney** [aws/aws-cdk#8913]
[Alarm.OPERATOR_SYMBOLS](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudwatch/lib/alarm.ts#L72) has the incorrect string value for `LessThanOrEqualToThreshold`.  Instead of `<=` (less than, equal to) it has `>=` (greater than, equal to).  

```
const OPERATOR_SYMBOLS = {
    GreaterThanOrEqualToThreshold: '>=',
    GreaterThanThreshold: '>',
    LessThanThreshold: '<',
    LessThanOrEqualToThreshold: '>=',   <-- incorrect
};
```

When the annotation is eagerly created (Alarm Line 201)[https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudwatch/lib/alarm.ts#L201] `label: `${this.metric} ${OPERATOR_SYMBOLS[comparisonOperator]} ${props.threshold} for...`  the incorrect string value is added to the annotation's label, which causes confusion as to what the alarm is actually doing since it is the exact opposite of what the alarm is doing.

### Reproduction Steps

* create a metric
* create an alarm with the provided metric and the comparison operator of `LessThanOrEqualToThreshold`
* create a graph widget for the metric and add the alarm as an annotation (I used horizontal annotations)
* Viewing the alarm itself shows the proper monitoring of `metric <= threshold`
* Viewing graph widget shows the annotation with incorrect label `metric >= threshold`

### Environment

  - **CLI Version     cdk 1.23.0 :**
  - **Framework Version:**
  - **Node.js Version:** 2.0.202680.0 (npm-pretty-much)
  - **OS         AL2      :**
  - **Language (Version):** "typescript": "^3.6.4" -->

### Other

* Flip the operator from `>=` to `<=`

Cloudwatch alarm with the correct condition (so the alarm itself is fine)
![alarm_correct_comparison](https://user-images.githubusercontent.com/4571429/86608408-5cec2680-bf5f-11ea-88d1-04bf312b234f.png)

Cloudwatch graph widget with same alarm as an annotation with incorrect comparison operator
![annotation_incorrect_comparison](https://user-images.githubusercontent.com/4571429/86608429-65446180-bf5f-11ea-81e5-1172b39e273a.png)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Thanks for the research and the thorough bug report.

Could I tempt you to turn that research into a PR? :)
