### ISSUE TITLE
[jsii] Use abstract base classes (ABCs) to implement interfaces in Python

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#8914]
Python abstract base classes (`abc` module) can be used to prevent Aspects and other types from being instantiated if they don't have the required methods, and bring Python support closer to parity with languages that support interfaces. It will also help improve the experience in popular IDEs (I know PyCharm can create stubs for required methods, for example).

This was suggested by a customer using a feedback link in the Developer Guide.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
[JSII Tracking Issue](https://github.com/aws/jsii/issues/1780)
