### ISSUE TITLE
[lambda-nodejs] AWS CDK TypeScript project. "cdk synth/deploy" hangs when there is a NodejsFunction construct in the stack.

### ISSUE THREAD

**Issue by th3r10n** [aws/aws-cdk#8922]
After adding a NodejsFunction construct to my stack and having successfully ran "npm run build", If I try to synthesize or deploy the stack the process just hangs without ever returning. 

### Reproduction Steps

Synthesize the attached [controller.zip](https://github.com/aws/aws-cdk/files/4883316/controller.zip)

### Error Log

No errors are displayed after executing "cdk synth" or "cdk deploy". Neither of the 2 processes returns.

### Environment

  - **CDK CLI Version      :** 1.49.1
  - **Framework Version:**
  - **Node.js Version:** v12.16.2
  - **OS               :** macOS 10.12.6
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
@th3r10n can you close this one in favor of #8921, is it the same?

**Comment by eladb** [comment]
Dup #8921
