### ISSUE TITLE
[assets]: exclude glob from project root directory 

### ISSUE THREAD

**Issue by hugomallet** [aws/aws-cdk#8923]
Hello,

I try to exclude a file only from the root directory of the project but it does not seem to work.

Example 
```js
// project/cdk/Stack.js
// ...
Code.fromAsset(
    `${__dirname}/../`,
     {
        exclude: [
            '/a-file'
        ]
     }
)
// ...
```

It should exclude the file "a-file" from the "project" root directory and it should keep "a-file" files in sub directories.

But the exclusion seems ignored.

What is the root directory for the glob matching ? I tried to exclude "../a-file" as well but it didn't work either.

**Comment by naiduarvind** [comment]
@hugomallet - from what I can see, exclude options during copying assets have been deprecated.

<img width="831" alt="Screenshot 2020-10-13 at 10 38 55 PM" src="https://user-images.githubusercontent.com/6829472/95875742-f1f38c80-0da4-11eb-92de-7683ad0dc48c.png">

**Comment by eladb** [comment]
The deprecation was only because we moved this type to @aws-cdk/core
