### ISSUE TITLE
[cloudwatch]  position of the widget in a dashboard cannot be changed

### ISSUE THREAD

**Issue by pushthat** [aws/aws-cdk#8938]
### Description of the bug
The position of the widget in the cloudwatch dashboard cannot be changed using the method described in the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.AlarmWidget.html#positionx-y).

### Reproduction Steps

```typescript
    initApiErrorWidgget(apiGateways: ApiGatewayConfig[]): cloudwatch.IWidget {
        let let apiErrorWidget = new cloudwatch.GraphWidget({
        // implem details
        })
        return apiErrorWidget;
    }


    constructor(scope: cdk.Construct, id: string, props: GlobalDashboardConfig) {
        super(scope, id);

        let globalDashboard = new cloudwatch.Dashboard(this, "globalDashboard", {
            dashboardName: props.name,
        })
        let apiErrorWidget = this.initApiErrorWidgget(props.apiGateways)
        globalDashboard.addWidgets(apiErrorWidget)
        apiErrorWidget.position(9, 0)
    }
```

### Environment

  - **CLI Version      :*1.50.0*
  - **Framework Version:*1.50.0*
  - **Node.js Version:*v12.18.1* 
  - **OS               :*Darwin*
  - **Language (Version):*TypeScript (3.9.6)* 

--- 

This is :bug: Bug Report

**Comment by nbenaglia** [comment]
I confirm this behaviour.

**Comment by cc189** [comment]
1. implement the `position` function
```ts
class GraphWidgetWithPosition extends GraphWidget {
    position(x: number, y: number): void {
        this.x = x;
        this.y = y;
    }
}
```

2. use `GraphWidgetWithPosition` instead of `GraphWidget`

3. change back to `GraphWidget` if this get fixed

**Comment by SMisra92** [comment]
I was trying to create LogQueryWidget where I am trying to set the "position(x, y)" by passing the x and y values dynamically but facing an jsii error. 
eg. Valid case where i am able to create the widget but however the Position parameters i.e. x and y are automatically set by cdk.
widget= cloudwatch.LogQueryWidget(log_group_names=[xyz],
                                    height=6,
                                    width=6,
                                    query_lines=query.split('|'),
                                    title=xyz_test,
                                    view=cloudwatch.LogQueryVisualizationType.TABLE,
                                    region=ap-south-1
                                )

Invalid Case:
If i try to set the position parameter it's create the cloudformation template. But the position parameters are not modified as per the values provide by us.

eg.
widget=cloudwatch.LogQueryWidget(log_group_names=[xyz],
                                    height=6,
                                    width=6,
                                    query_lines=query.split('|'),
                                    title=xyz_test,
                                    view=cloudwatch.LogQueryVisualizationType.TABLE,
                                    region=ap-south-1
                                )
widget.position(0,6)


Please have a look into this.

**Comment by jain98** [comment]
Instead of hard-coding position using the position method inherited from the ConcreteWidget class a workaround and probably easier way to position widgets is to use [Columns](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Column.html) and [Rows](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Row.html) which can be used to set the widgets matrix in a dashboard. 

Example usage -

```
        const dashboard = new Dashboard(this, "dashboard", {
            dashboardName: "foo",
            widgets: [
                [
                    new Column(widget1),
                    new Column(widget2, widget3, widget4)
                    new Column(widget5, widget6, widget7)
                ],
                [
                    widget8
                ],
                [
                    widget9,
                    widget10
                ]
            ]
        });
```

**Comment by Kifah** [comment]
case confirmed here as well.

**Comment by smalik2043** [comment]
case confirmed still not fixed.

**Comment by renzroque** [comment]
still not working

**Comment by peterwoodworth** [comment]
We've identified where the problem is.

The L2 construct is building a CfnDashboard object. In [Cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-dashboard.html#cfn-cloudwatch-dashboard-dashboardbody), widgets in the dashboard are built [with a string](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html#Dashboard-Body-Overall-Structure). The CDK is building that string on line 101:

https://github.com/aws/aws-cdk/blob/6179ac16f2fcab5bf5e03a3629db281018d7585b/packages/%40aws-cdk/aws-cloudwatch/lib/dashboard.ts#L95-L109

Widgets are imported into that dashboard via `rows`:

https://github.com/aws/aws-cdk/blob/6179ac16f2fcab5bf5e03a3629db281018d7585b/packages/%40aws-cdk/aws-cloudwatch/lib/dashboard.ts#L125-L132

These widgets are turned into strings via the `Column` object as seen on line 99 of the first snippet. However, column position is adjusted in the following line.

And as you can see here:

https://github.com/aws/aws-cdk/blob/6179ac16f2fcab5bf5e03a3629db281018d7585b/packages/%40aws-cdk/aws-cloudwatch/lib/layout.ts#L83-L89

When column position is adjusted, it adjusts the position of individual widgets as well, thereby always setting them to 0.

We are investigating a possible fix

**Comment by peterwoodworth** [comment]
The intended way to position widgets is as @jain98 said above. 
This:
```ts
const widget1 = new AlarmWidget({ alarm: alarm, width: 16, height: 9 })
const widget2 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
const widget3 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
const widget4 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
const widget5 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
const widget6 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
const widget7 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
const widget8 = new AlarmWidget({ alarm: alarm, width: 24, height: 4 })
const widget9 = new AlarmWidget({ alarm: alarm, width: 12, height: 4 })
const widget10 = new AlarmWidget({ alarm: alarm, width: 12, height: 4 })

new cloudwatch.Dashboard(this, "dashboard", {
  dashboardName: "foo",
  widgets: [
    [
      new Column(widget1),
      new Column(widget2, widget3, widget4),
      new Column(widget5, widget6, widget7)
    ],
    [
      widget8
    ],
    [
      widget9,
      widget10
    ]
  ]
})
```
will look like this:
<img width="1556" alt="Screen Shot 2021-05-26 at 3 53 19 PM" src="https://user-images.githubusercontent.com/44349620/119741682-0e779d00-be3b-11eb-986f-3f854124182f.png">
Each array of widgets is a new `Row`. [Let the autofilling work for you](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudwatch-readme.html#dashboard-layout) 😄 

The documentation having [this](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.AlarmWidget.html#positionx-y) is misleading, as the user is not supposed to be able to set the position manually.

**Comment by max258-new** [comment]
const wd1 = new GraphWidget({  "width": 12,"height": 5, title: 'lamba 1', left: [new Metric({ metricName: 'Error', namespace: 'AWS/Lambda',
            dimensions: {'lambda_name': 'lambda_name'},
            statistic: 'avg',
          })
          ]})
          
          dashboard.addWidgets(wd1)
How should I add position as X and Y ?

**Comment by Roseidon** [comment]
Still an issue. What is the `.position()` command used for anyway?

**Comment by Hektor-V** [comment]
still seems to be an issue. 

example below. 

`invocation_graph_widget = aws_cloudwatch.GraphWidget(
            title=f"Invocations - 1 hour",
            height=6,
            width=8,
            left=Invocations_metric_graph,
        )
errors_widget.position(x=2,y=0)
`

**Comment by citosid** [comment]
> The intended way to position widgets is as @Jain98 said above. This:
> 
> ```ts
> const widget1 = new AlarmWidget({ alarm: alarm, width: 16, height: 9 })
> const widget2 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
> const widget3 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
> const widget4 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
> const widget5 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
> const widget6 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
> const widget7 = new AlarmWidget({ alarm: alarm, width: 4, height: 3 })
> const widget8 = new AlarmWidget({ alarm: alarm, width: 24, height: 4 })
> const widget9 = new AlarmWidget({ alarm: alarm, width: 12, height: 4 })
> const widget10 = new AlarmWidget({ alarm: alarm, width: 12, height: 4 })
> 
> new cloudwatch.Dashboard(this, "dashboard", {
>   dashboardName: "foo",
>   widgets: [
>     [
>       new Column(widget1),
>       new Column(widget2, widget3, widget4),
>       new Column(widget5, widget6, widget7)
>     ],
>     [
>       widget8
>     ],
>     [
>       widget9,
>       widget10
>     ]
>   ]
> })
> ```
> 
> will look like this: <img alt="Screen Shot 2021-05-26 at 3 53 19 PM" width="1556" src="https://user-images.githubusercontent.com/44349620/119741682-0e779d00-be3b-11eb-986f-3f854124182f.png"> Each array of widgets is a new `Row`. [Let the autofilling work for you](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudwatch-readme.html#dashboard-layout) 😄
> 
> The documentation having [this](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.AlarmWidget.html#positionx-y) is misleading, as the user is not supposed to be able to set the position manually.

Thanks @peterwoodworth ! I was having a hard time positioning widgets with different heights, but this made it super simple.
