### ISSUE TITLE
[route53-targets] support APIGatewayV2 as a domain target

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8941]
*(forked off https://github.com/aws/aws-cdk/issues/8908)*

Something like this already exists for RestApi - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53-targets.ApiGatewayDomain.html

Need similar support for APIGatewayV2.

---

This is a :rocket: Feature Request

**Comment by kennu** [comment]
I have the same need. While waiting for official support, I used my own function to bind to DomainName:

    target: RecordTarget.fromAlias({
      bind: (_record: IRecordSet) => ({
        dnsName: httpDomainName.regionalDomainName,
        hostedZoneId: httpDomainName.regionalHostedZoneId,
      })
    })

**Comment by christophgysin** [comment]
I just copied the ApiGatewayDomain class from aws-apigateway:
```typescript
class ApiGatewayDomain implements route53.IAliasRecordTarget {
  constructor(private readonly domainName: apigwv2.IDomainName) { }

  public bind(_record: route53.IRecordSet): route53.AliasRecordTargetConfig {
    return {
      dnsName: this.domainName.regionalDomainName,
      hostedZoneId: this.domainName.regionalHostedZoneId,
    };
  }
}

new route53.ARecord(this, 'AliasRecord', {
  zone: hostedZone,
  recordName: 'api',
  target: route53.RecordTarget.fromAlias(new ApiGatewayDomain(domainName)),
});
```

**Comment by davidsteed** [comment]
This is easy to do in v1 apigateway
const domain = new apigateway.DomainName(this, "myApiDomain", {
      domainName: restAPIDomain,
      certificate: certificate,
      endpointType: apigateway.EndpointType.REGIONAL,
    });
const api = new apigateway.RestApi( "RestAPI", {
      restApiName: "API",
      description: "REST API",
    });

domain.addBasePathMapping(api);

Want an equally straight forward way of doing it for v2.  Can't find how to easily specify Endpoint REGIONAL for v2 either.

**Comment by sladg** [comment]
Solved by following code:
```
// Manual type overwrite to allow for alias target for newer HTTP API.
;(apiGwDomain as any).domainName = apiGwDomain.name
;(apiGwDomain as any).domainNameAliasDomainName = apiGwDomain.regionalDomainName
;(apiGwDomain as any).domainNameAliasHostedZoneId = apiGwDomain.regionalHostedZoneId

const apiGwTarget = RecordTarget.fromAlias(new ApiGatewayDomain(apiGwDomain as any))
```

Basically, remapped V2 regional props to V1.

CC: https://github.com/aws/aws-cdk/issues/17244
