### ISSUE TITLE
[codepipline] [ec2] Security Group changes silently fails CodePipeline's CloudFormation deploy

### ISSUE THREAD

**Issue by mikestopcontinues** [aws/aws-cdk#8945]
I have a CodePipeline stack that deploys a resource stack via a CloudFormation deploy step. I recently added a SecurityGroup to my resource stack. Upon deploy, CodePipeline reports a success, but no changes were actually deployed.

When I tried to deploy the stack from my local machine, I found that a warning (see below) seems to be blocking my deploy. However, I granted my deploy step `adminPermissions: true`, so it doesn't seem like this should've happened.

### Reproduction Steps

Here's the new code:

```js
  devStack.vpc = new Vpc(stack, 'DevVpc', {maxAzs: 2});
  devStack.securityGroup = new SecurityGroup(stack, 'DevSecurityGroup', {vpc: stack.vpc});
```

And here's my deploy step. (You'll notice a circular reference that helps me deploy changes to the pipeline itself. This works, and regarding the current issue, I made no changes to the pipeline stack. Admin permissions have been in place.)

```js
  devPipelineStack.addDependency(devStack);

  devPipelineStack.pipeline.addStage({
    stageName: 'Deploy',
    actions: [
      new CloudFormationCreateUpdateStackAction({
        actionName: 'StackDeploy',
        templatePath: stack.stackBuildArtifact.atPath('DevPipelineStack.template.json'),
        stackName: 'DevPipelineStack',
        adminPermissions: true,
      }),
    ],
  });
```

### Error Log

As I mentioned above, my main issue is that CodePipeline reports a success even though this issue prevents it from even attempting to build the CloudFormation template. Below is what I saw when deploying the update locally:

```
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

Security Group Changes
┌───┬─────────────────────────────┬─────┬────────────┬─────────────────┐
│   │ Group                       │ Dir │ Protocol   │ Peer            │
├───┼─────────────────────────────┼─────┼────────────┼─────────────────┤
│ + │ ${DevSecurityGroup.GroupId} │ Out │ Everything │ Everyone (IPv4) │
└───┴─────────────────────────────┴─────┴────────────┴─────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)?
```

### Environment

  - **CLI Version      :** 1.47.1
  - **Framework Version:** 1.50.0
  - **Node.js Version:** remote 12.X, local 14.4.0
  - **Language (Version):** JS

### Other

I'd prefer `adminPermissions: true` to handle this issue. Failing that, I'd like CloudFormationCreateUpdateStackAction to fail if it can't run the update.

Thanks!

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It is unlikely that a CloudFormation Deploy Action in your pipeline would have silently failed. Those things are generally pretty loud about unexpected situations.

Best guesses I can make are:

- For whatever reason, the SecurityGroup was already considered part of your template, and hence no changes were made (clarification: even if the SecurityGroup didn't really exist, if CloudFormation "remembers" it for whatever reason, it will not try to create it again. CloudFormation does not look at the actual state of the resources, just at what it remembers having done previously). This is unlikely, given that a `cdk deploy` does show the diff and it works based on the same template, but it might be worth double-checking nevertheless. You can do it by hand or try running a Drift Detection.

- For whatever other reason, `DevPipelineStack.template.json` in your pipeline either does not contain the stack you think it does, or is run based on old code, or gets generated differently in the pipeline than on your dev machine.

All of these are unlikely, but I don't think there's anything wrong with the construct per se. Feels like it has to be something in your setup.

**Comment by mikestopcontinues** [comment]
Hi @rix0rrr, thanks for your reply! Unfortunately, I also don't see either one of those things being true. 

On the first point, this is the first SecurityGroup I've created, and it has an id that was never used before. Also, when I ran the template locally, it properly detected the change and asked me what to do about it.

On the second point, I checked the file, as I considered the same possibility. It links to the full DevStack (the resource stack), which I include a specific dependency to (`devPipelineStack.addDependency(devStack);`) to ensure that if I change my indirect references, the binding remains. 

I should've said earlier, I added a VPC in the same commit, and it too wasn't detected. In an effort to get it unstuck, I also changed an unrelated line, with no success. Since deploying from my local machine, future updates have gone through as expected via codepipeline. These contribute to why I think its that warning that's gunking up the system. 

Is there anything else you can think of? What else can I provide to try to make sense of this? Thanks!

**Comment by mikestopcontinues** [comment]
Actually, my apologies! You were right all along. `DevPipelineStack.template.json` doesn't have any reference to my resource stack. That's concerning to me, as I'm fairly certain my deploys were working as I previously expected. I'm investigating now what the right way to deploy a stack and its dependencies is.

**Comment by mikestopcontinues** [comment]
Hey, I just checked the source code, and there doesn't seem to be any handling for stack dependencies in the CloudFormation build actions. Is this worth a feature request? I may be biased, but it seems like this would be the expected behavior. When you deploy from the CLI, dependencies are handled automatically.

**Comment by rix0rrr** [comment]
You're not wrong, but the CodePipeline library is low-level and makes no assumptions on what you are trying to do with it.

Fortunately we've just released a new library made especially for deploying CDK apps using CodePipeline. Check it out: [@aws-cdk/pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html)
