### ISSUE TITLE
[aws-s3] bucket.grantWrite does not grant sufficient permissions to perform multipart upload on a bucket with SSE enabled

### ISSUE THREAD

**Issue by gethinw** [aws/aws-cdk#8947]
When creating an S3DeployAction in CodePipeline that targets a bucket with encryption (SSE-KMS) enabled, the action's permissions aren't sufficient to upload large files, as these use multipart uploads, which require `kms:Decrypt`: https://aws.amazon.com/premiumsupport/knowledge-center/s3-multipart-kms-decrypt/.

This seems to be a more general problem with the `bucket.grantWrite` method.

### Reproduction Steps

TBC

### Error Log

```
You do not have sufficient permissions to call s3.putObject for the deployment bucket, XXXXX. Verify that the policy on the resource allows you to perform this task. If you choose a canned ACL for your Amazon S3 deployment action, the policy must include the PutObjectAcl action. If the object already exists, the policy must also include the PutObjectVersionAcl action. Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: XXXXX; S3 Extended Request ID: XXXXXXXXX)
```

### Environment

  - **CLI Version      : ** `aws-cli/1.16.69 Python/3.7.1 Darwin/18.7.0 botocore/1.12.59`
  - **Framework Version: ** `"aws-cdk": "1.23.0"`
  - **Node.js Version:** `v13.11.0`
  - **OS               : ** `MacOS`
  - **Language (Version):** TypeScript (3.7.2)

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting @gethinw . I wonder whether this is more of a bug in the KMS library than in CodePipeline, though (the KMS library is the one who should make sure all of the necessary permissions are granted).

**Comment by gethinw** [comment]
good point, or perhaps in S3:

https://github.com/aws/aws-cdk/blob/be1094b4f4ef1eb194333faaf804db610535fea1/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L499
https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/aws-s3/lib/perms.ts#L26

Will rename ticket to better reflect this.
