### ISSUE TITLE
[aws-elasticbeanstalk] Elastic Beanstalk environment not detaching security group

### ISSUE THREAD

**Issue by denisdifazio** [aws/aws-cdk#8950]
I created a EBS application with a custom security group and after removing the same security group from code, it wasn't removed from the environment causing the CloudFormation to hang on 'resource sg-09909b16d271784f4 has a dependent object' until a manually unchecked the security dependency on EBS environment.

### Reproduction Steps

Create and add a security group as seen below:
```typescript
const stackVpc = Vpc.fromLookup(this, 'vpc', { vpcId: process.env.VPC_ID });

const securityGroup = new SecurityGroup(this, 'securityGroup', {
  vpc: stackVpc,
});

environmentConfiguration.push(
  {
    namespace: 'aws:autoscaling:launchconfiguration',
    optionName: 'SecurityGroups',
    value: securityGroup.securityGroupId,
  },
);

const environment = new elasticbeanstalk.CfnEnvironment(this, 'environment', {
    environmentName: serviceName,
    applicationName: application.applicationName,
    solutionStackName: '64bit Amazon Linux 2 v5.0.1 running Node.js 12',
    optionSettings: environmentConfiguration,
});
```

Remove security group from code:
```typescript
const environment = new elasticbeanstalk.CfnEnvironment(this, 'environment', {
    environmentName: serviceName,
    applicationName: application.applicationName,
    solutionStackName: '64bit Amazon Linux 2 v5.0.1 running Node.js 12',
    optionSettings: environmentConfiguration,
});
```
AWS CDK will not uncheck previous security group from environment configuration causing CloudFormation to being stuck.

### Error Log

![image](https://user-images.githubusercontent.com/11673757/86950895-2b25bc00-c127-11ea-9be4-283ef2f9d8eb.png)

### Environment

  - **CLI Version      :**
  - **Framework Version:** 1.50.0
  - **Node.js Version:**  12.18.2
  - **OS               :** Windows 10
  - **Language (Version):**  TypeScript (3.9.6)

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @denisdifazio ,

thanks for opening the issue. I think what you want to do is:

1. Keep the security group, but remove it from the EBS environment (the `environmentConfiguration.push()` part).
2. Do a deploy.
3. Remove the security group from your code.

Thanks,
Adam
