### ISSUE TITLE
[aws-eks] Create Cluster: S3 error: Access Denied

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-cdk#8957]
I'm able to use CDK to create a VPC and IAM Role without issue. I'm trying to use CDK to deploy an EKS Cluster. CDK uses Nested Stacks, but I'm seeing a weird S3 Permission issue when creating the NestedStack. Any suggestions for further debugging? I don't have much beyond the NestedStack creation error. 

### Reproduction Steps
```
    const vpc = new ec2.Vpc(this, 'EKSVpc');  // Create a new VPC for our cluster

    const eksCluster = new eks.Cluster(this, 'eks-scalability', {
      vpc: vpc,
      kubectlEnabled: true,  // we want to be able to manage k8s resources using CDK
      defaultCapacity: 0  // we want to manage capacity our selves
    });
```

### Error Log
```
4:02:30 PM | CREATE_FAILED        | AWS::CloudFormation::Stack            | awscdkawseksCluste...ckResource9827C454
S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

	new NestedStack (/.../node_modules/@aws-cdk
/aws-cloudformation/lib/nested-stack.js:34:25)
	\_ new ClusterResourceProvider (/.../@aws-cdk/aws-eks/lib/cluster-resource-provider.js:19:9)
	\_ Function.getOrCreate (/.../node_modules/
@aws-cdk/aws-eks/lib/cluster-resource-provider.js:45:48)
	\_ new ClusterResource (/.../node_modules/@
aws-cdk/aws-eks/lib/cluster-resource.js:23:78)
	\_ new Cluster (/.../node_modules/@aws-cdk/
aws-eks/lib/cluster.js:74:24)
	\_ new EKSClusterStack (/.../dist/lib/eks-c
```

### Environment

  - **CLI Version      :** 1.23.0
  - **Framework Version:** 1.32.2
  - **Node.js Version:** node v14.5.0
  - **OS               :** Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by ellistarn** [comment]
Digging a little deeper into the template, it looks like the S3 URI of the NestedStack doesn't exist. How does the CDK typically upload NestedStacks to S3?

**Comment by eladb** [comment]
> Digging a little deeper into the template, it looks like the S3 URI of the NestedStack doesn't exist. How does the CDK typically upload NestedStacks to S3?

Nested stacks are modeled as s3 assets and are uploaded by `cdk deploy` automatically. 

Are you using `cdk deploy`?

**Comment by ellistarn** [comment]
I am. I'm using some internal tooling that added an additional step. All smooth now thank you!
