### ISSUE TITLE
[aws-codepipeline-actions] How to synth 'TaskDefinitionTemplateArtifact' and 'AppSpecTemplateArtifact' by using 'CodeDeployEcsDeployAction'?

### ISSUE THREAD

**Issue by tp6m4fu6250071** [aws/aws-cdk#8971]
This [doc](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html) indicates that the **CodeDeployToECS** action should include:
- ApplicationName
- DeploymentGroupName
- TaskDefinitionTemplateArtifact
- AppSpecTemplateArtifact
- AppSpecTemplatePath

It seems no argument is for generating **TaskDefinitionTemplateArtifact** and **AppSpecTemplateArtifact**. Am I missing something here?

### Reproduction Steps

I'm using Python.
```
...
deployment_group = codedeploy.EcsDeploymentGroup.from_ecs_deployment_group_attributes(pipeline_stack, "EcsDepGroup",
    application = codedeploy.EcsApplication(pipeline_stack, "EcsDepApp"),
    deployment_group_name = 'CdkEcsDeploymentGroup'
)
deploy_stage = pipeline.add_stage(stage_name="DeployECS")
deploy_container_image_input = codepipeline_actions.CodeDeployEcsContainerImageInput(
    input=build_output,
    task_definition_placeholder='IMAGE1_NAME'
)
deploy_stage.add_action(codepipeline_actions.CodeDeployEcsDeployAction(
    action_name = 'DeployToECS',
    app_spec_template_input=build_output,
    task_definition_template_input=build_output,
    deployment_group=deployment_group,
    container_image_inputs=[deploy_container_image_input],
))
```

### Error Log

The synth template will be:
```
        - Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeployToECS
                Version: "1"
              Configuration:
                ApplicationName:
                  Ref: EcsDepApp6BB5E38F
                DeploymentGroupName: CdkEcsDeploymentGroup
                TaskDefinitionTemplatePath: taskdef.json
                AppSpecTemplatePath: appspec.yaml
                Image1ContainerName: IMAGE1_NAME
              InputArtifacts:
                - Name: Artifact_build_CodeBuild
              Name: DeployToECS
              RoleArn:
                Fn::GetAtt:
                  - CodePipelineDeployECSDeployToECSCodePipelineActionRoleA615EFA9
                  - Arn
              RunOrder: 1
          Name: DeployECS
```

I submitted it in 'Bug Report' category because the [test script](https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/aws-codepipeline-actions/test/codedeploy/test.ecs-deploy-action.ts#L105) on the github shows that it should return these two properties.

### Environment

  - **CLI Version      :**1.46.0 and 1.50.0
  - **Framework Version:**1.46.0 and 1.50.0
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @tp6m4fu6250071 ,

thanks for opening the issue. You're correct, this is a bug. You can work around it by naming the input artifact(s) to your ECS deploy action, in your case it's the `build_output` artifact, like so: `codepipeline.Artifact('SomeName')`.

Thanks,
Adam
