### ISSUE TITLE
[core] Move Schedule classes to core and remove duplicates

### ISSUE THREAD

**Issue by civilizeddev** [aws/aws-cdk#8979]
### The Question

https://github.com/aws/aws-cdk/blob/d80efae6cca60bb5c1979d28c180ef991c02eb38/packages/%40aws-cdk/aws-applicationautoscaling/lib/schedule.ts#L3-L6

https://github.com/aws/aws-cdk/blob/d80efae6cca60bb5c1979d28c180ef991c02eb38/packages/%40aws-cdk/aws-autoscaling/lib/schedule.ts#L1-L4

https://github.com/aws/aws-cdk/blob/d80efae6cca60bb5c1979d28c180ef991c02eb38/packages/%40aws-cdk/aws-events/lib/schedule.ts#L3-L6

The classes above are almost the same.

What about moving them all to `@aws-cdk/core` and remove duplicates?

It will be more useful in the core module.

### Environment

  - **CDK CLI Version:** 1.50.0
  - **Module Version:** 1.50.0
  - **Node.js Version:** 14.5.0 
  - **OS:** macOS Catalina 
  - **Language (Version):** TypeScript (3.9.6) 

### Other information

- #1181
- #2538
- https://github.com/aws/aws-cdk/issues/8698#issuecomment-653332910

**Comment by eladb** [comment]
Sounds good. Happy to take a contribution.
