### ISSUE TITLE
[EC2] - More specific error message if incorrect AMI id used.

### ISSUE THREAD

**Issue by flowtrader2016** [aws/aws-cdk#8985]
More specific error message for incorrect AMI id.
### Use Case

If an incorrect AMI id is selected (I had used an AMI from another region) the following generic error message is given:

custom-ec2: creating CloudFormation changeset...
18:01:30 | CREATE_FAILED        | AWS::EC2::Instance        | webServerId0608AA65
The requested configuration is currently not supported. Please check the documentation for supported configurations.

### Proposed Solution

Is it possible to give an error stating "incorrect AMI id reference used" or similar?

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Unfortunately, no. This happens at a time when CDK is no longer in control, and is a configuration that also cannot be checked by us.

You could write yourself a Custom Resource to check the AMI ID.
