### ISSUE TITLE
[awslint] Linter Rule Plugins

### ISSUE THREAD

**Issue by grbartel** [aws/aws-cdk#9003]
I would like the ability to create my own rules for awslint which don't make sense to be upstreamed to the main CDK repository.  

Currently in order to accomplish this I would be required to fork awslint project and add the rules directly into the main repository however this will make maintaining more difficult.

### Use Case
I am currently working on creating my own construct library and I would like the ability to create extra rules such as the requirement to have specific tags in the documentation of all exposed classes.

### Proposed Solution

My proposed solution for this is to add a config option for aws lint which specifies a list of plugins that awslint should load and a list of awslint.Linter objects from those plugins that should be added to the aggregate linter that runs all of the rules.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Not opposed to this if you want to take a crack at it, but not likely something we'll be doing soon.

**Comment by JeremyJonas** [comment]
Any updates/progress on this?

Would be useful linting constructs for permissive policies and other security issues without requiring synth with cfn_nag

As well as enforcing other best practices defined by teams.
