### ISSUE TITLE
[aws-stepfunctions-tasks] Problem with mapping a boolean and a number from an input event in a step function to insert into dynamodb 

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-cdk#9007]
So thank you for upgrading the dynamodb integration from step functions.

I'm now starting to use it.

Firstly, when doing this - the recommended way to map values in a step function:

"alarm_id": DynamoAttributeValue.from_number(JsonPath.number_at("$.detail.alarm_id")),

This is synthesized as "alarm_id":{"N":"-1.8881545897087864e+289"}}

Very weird. Especially since that is what is actually deployed... 

Surely that should be 

"alarm_id":{"N.$":"$.detail.alarm_id"}}

Then what about when I want to map a boolean?

There is no boolean_at in JsonPath...

So what I really want to know is why access to the constructor of DynamoAttributeValue is not provided because this would solve all my problems...

  - **CDK CLI Version:1.51.0
  - **Node.js Version: 12.16.3
  - **OS: Ubuntu 20.04
  - **Language (Version): Python 3.8

**Comment by shivlaks** [comment]
@michaelbrewer - `from_number` is for the case where you have a number to directly plug in, you'd want to use `number_from_string` and pass it the parameter you're currently giving it. can you give that a go and let me know how it turns out?

I'll need to dig into the boolean case a bit more, will take a look a bit later today

**Comment by michaelwiles** [comment]
Yes, thank you @SomayaB - I looked at some of the tests and ascertained that is the way to do it.

> "alarm_id": DynamoAttributeValue.number_from_string(JsonPath.string_at("$.detail.alarmId")),

works great...

Please let me know if you have something on booleans as I can't find an example mapping a boolean in the tests.

**Comment by shivlaks** [comment]
@michaelwiles are you attempting to set a boolean based on state input (by selecting part of the path?) we might need to add a `booleanFromJsonPath` method to support that as there's only `fromBoolean` that's currently available, which will allow you to set a value, but not select it from the state input.

**Comment by michaelwiles** [comment]
Yes, that's what I am doing - and that's what is needed -> "booleanFromJsonPath"

**Comment by michaelwiles** [comment]
@shivlaks I've created a pull request for this though it's going to need a bit more attention as I don't think I've followed the process properly.

**Comment by shivlaks** [comment]
@michaelwiles took a quick glance and provided some feedback. let me know if you're running into any issues iterating.
I'm happy to help get this PR filled out and past the goal line :)

**Comment by michaelwiles** [comment]
thank you. will follow up
