### ISSUE TITLE
[aws-cloudtrail] cross-region OR cross-account Cloudtrail with SNS Topic for delivery notifications generates 400 error

### ISSUE THREAD

**Issue by estorey11** [aws/aws-cdk#9013]
Creating OR Updating a Cloudtrail with an SNS Topic for delivery notifications that is cross-region OR cross-account generates a 400 error (InsufficientSnsTopicPolicyException) causing the deployment to fail. Manually entering the SNS Topic arn in the console works as usual. Cloudtrail delivery notification to cross-region and cross-account SNS Topics was functional in CDK v1.21.1, when the cloudtrail property snsTopic required the topicArn as a string instead of an ITopic. After the CDK v1.42.0 update, which changed the cloudtrail snsTopic property type from string to ITopic, passing sns.Topic.fromTopicArn(this, 'crossAccountTopic', crossAccountTopicArn) as the snsTopic property to the cloudtrail fails on deployment with an InsufficientSnsTopicPolicyException error code.

### Reproduction Steps

        const tempTrailBucket = s3.Bucket.fromBucketArn(this,'tempTrailBucket',props.bucketArn);
        const crossAccountSnsTopic= sns.Topic.fromTopicArn(this, 'crossAccountSnsTopic', props.crossAccountSnsTopicArn)
        const kmsKey= kms.Key.fromKeyArn(this, 'keyArn', props.keyArn)

        const trail = new cloudtrail.Trail(this, 'CloudTrail', {
            bucket: tempTrailBucket,
            kmsKey: kmsKey
            sendToCloudWatchLogs: true,
            cloudWatchLogsRetention: logs.RetentionDays.ONE_YEAR,
            enableFileValidation: true,
            includeGlobalServiceEvents: true,
            isMultiRegionTrail: true,
            managementEvents: cloudtrail.ReadWriteType.ALL,
            snsTopic: crossAccountSnsTopic,
        });

### Error Log

> 464 | 3/6 \| 3:17:17 PM \| UPDATE_IN_PROGRESS   \| AWS::CloudTrail::Trail \| CloudTrail (CloudTrailA62D711D)
> 465 | 3/6 \| 3:17:18 PM \| UPDATE_FAILED        \| AWS::CloudTrail::Trail \| CloudTrail (CloudTrailA62D711D) SNS Topic does not exist or the topic policy is incorrect! (Service: AWSCloudTrail; Status Code: 400; Error Code: InsufficientSnsTopicPolicyException; Request ID: 8dbc3172-f9b4-4a6d-bf4e-15cbeb989f37)

### Environment

  - **CLI Version:** 1
  - **Framework Version:** N/A
  - **Node.js Version:**  v12.13.0 
  - **OS:** aws/codebuild/amazonlinux2-aarch64-standard:1.0
  - **Language (Version):** typescript@3.9.6

### Other

**SNS Topic Access Policy**
```
{
  "Version": "2008-10-17",
  "Id": "__default_policy_ID",
  "Statement": [
    {
      "Sid": "__default_statement_ID",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "SNS:Subscribe",
        "SNS:ListSubscriptionsByTopic",
        "SNS:DeleteTopic",
        "SNS:GetTopicAttributes",
        "SNS:Publish",
        "SNS:RemovePermission",
        "SNS:AddPermission",
        "SNS:Receive",
        "SNS:SetTopicAttributes"
      ],
      "Resource": "arn:aws:sns:us-east-1:crossAccountID:crossAccountSnsTopic",
      "Condition": {
        "StringEquals": {
          "AWS:SourceOwner": "865269043642"
        }
      }
    },
    {
      "Sid": "AWSCloudTrailSNSPolicy20150319",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudtrail.amazonaws.com"
      },
      "Action": "SNS:Publish",
      "Resource": "arn:aws:sns:us-east-1:crossAccountID:crossAccountSnsTopic"
    }
  ]
}
```

**Full Error with Stacktrace**

> cisTrail: creating CloudFormation changeset...
> 457 | 0/6 \| 3:16:56 PM \| CREATE_IN_PROGRESS   \| AWS::Logs::LogGroup    \| CloudTrail/LogGroup (CloudTrailLogGroup2F0A1829)
> 458 | 0/6 \| 3:16:56 PM \| CREATE_IN_PROGRESS   \| AWS::Logs::LogGroup    \| CloudTrail/LogGroup (CloudTrailLogGroup2F0A1829) Resource creation Initiated
> 459 | 0/6 \| 3:16:56 PM \| UPDATE_IN_PROGRESS   \| AWS::CDK::Metadata     \| CDKMetadata
> 460 | 2/6 \| 3:16:57 PM \| CREATE_COMPLETE      \| AWS::Logs::LogGroup    \| CloudTrail/LogGroup (CloudTrailLogGroup2F0A1829)
> 461 | 2/6 \| 3:16:58 PM \| UPDATE_COMPLETE      \| AWS::CDK::Metadata     \| CDKMetadata
> 462 | 2/6 \| 3:16:59 PM \| UPDATE_IN_PROGRESS   \| AWS::IAM::Policy       \| CloudTrail/LogsRole/DefaultPolicy (CloudTrailLogsRoleDefaultPolicyD9019B15)
> 463 | 3/6 \| 3:17:15 PM \| UPDATE_COMPLETE      \| AWS::IAM::Policy       \| CloudTrail/LogsRole/DefaultPolicy (CloudTrailLogsRoleDefaultPolicyD9019B15)
> 464 | 3/6 \| 3:17:17 PM \| UPDATE_IN_PROGRESS   \| AWS::CloudTrail::Trail \| CloudTrail (CloudTrailA62D711D)
> 465 | 3/6 \| 3:17:18 PM \| UPDATE_FAILED        \| AWS::CloudTrail::Trail \| CloudTrail (CloudTrailA62D711D) SNS Topic does not exist or the topic policy is incorrect! (Service: AWSCloudTrail; Status Code: 400; Error Code: InsufficientSnsTopicPolicyException; Request ID: 8dbc3172-f9b4-4a6d-bf4e-15cbeb989f37)
> 466 | new Trail (/codebuild/output/src696392947/src/cis_compliance/node_modules/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts:268:19)
> 467 | \_ new cisTrail (/codebuild/output/src696392947/src/cis_compliance/lib/cis_trail.ts:27:23)
> 468 | \_ Object.<anonymous> (/codebuild/output/src696392947/src/cis_compliance/bin/cis_compliance.ts:118:15)
> 469 | \_ Module._compile (internal/modules/cjs/loader.js:778:30)
> 470 | \_ Module.m._compile (/codebuild/output/src696392947/src/cis_compliance/node_modules/ts-node/src/index.ts:858:23)
> 471 | \_ Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> 472 | \_ Object.require.extensions.(anonymous function) [as .ts] (/codebuild/output/src696392947/src/cis_compliance/node_modules/ts-node/src/index.ts:861:12)
> 473 | \_ Module.load (internal/modules/cjs/loader.js:653:32)
> 474 | \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> 475 | \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
> 476 | \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> 477 | \_ main (/codebuild/output/src696392947/src/cis_compliance/node_modules/ts-node/src/bin.ts:227:14)
> 478 | \_ Object.<anonymous> (/codebuild/output/src696392947/src/cis_compliance/node_modules/ts-node/src/bin.ts:513:3)
> 479 | \_ Module._compile (internal/modules/cjs/loader.js:778:30)
> 480 | \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> 481 | \_ Module.load (internal/modules/cjs/loader.js:653:32)
> 482 | \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> 483 | \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
> 484 | \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> 485 | \_ findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
> 486 | 3/6 \| 3:17:19 PM \| UPDATE_ROLLBACK_IN_P \| AWS::CloudFormation::Stack \| cisTrail The following resource(s) failed to update: [CloudTrailA62D711D].
> 487 | 2/6 \| 3:17:37 PM \| UPDATE_IN_PROGRESS   \| AWS::CDK::Metadata     \| CDKMetadata
> 488 | 2/6 \| 3:17:37 PM \| UPDATE_IN_PROGRESS   \| AWS::IAM::Policy       \| CloudTrail/LogsRole/DefaultPolicy (CloudTrailLogsRoleDefaultPolicyD9019B15)
> 489 | 2/6 \| 3:17:38 PM \| UPDATE_COMPLETE      \| AWS::CDK::Metadata     \| CDKMetadata
> 490 | 2/6 \| 3:17:54 PM \| UPDATE_COMPLETE      \| AWS::IAM::Policy       \| CloudTrail/LogsRole/DefaultPolicy (CloudTrailLogsRoleDefaultPolicyD9019B15)
> 491 | 2/6 \| 3:17:55 PM \| UPDATE_COMPLETE      \| AWS::CloudTrail::Trail \| CloudTrail (CloudTrailA62D711D)
> 492 | 2/6 \| 3:17:55 PM \| UPDATE_ROLLBACK_COMP \| AWS::CloudFormation::Stack \| cisTrail
> 493 |  
> 494 | ❌  cisTrail failed: Error: The stack named cisTrail is in a failed state: UPDATE_ROLLBACK_COMPLETE
> 495 | The stack named cisTrail is in a failed state: UPDATE_ROLLBACK_COMPLETE
> 496 |  
> 497 | [Container] 2020/07/10 15:17:57 Command did not exit successfully cdk deploy cisTrail --require-approval never exit status 1
> 498 | [Container] 2020/07/10 15:17:57 Phase complete: BUILD State: FAILED
> 499 | [Container] 2020/07/10 15:17:57 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk deploy cisTrail --require-approval never. Reason: exit status 1
> 

--- 

This is :bug: Bug Report

**Comment by estorey11** [comment]
I'm still receiving this error in cdk v1.60.0

**Comment by bryanhelix** [comment]
This does not seem to have been fully fixed.

When referencing an external SNS topic (cross-account notification) while creating a trail, the CF template only references the topic by name, when it should reference it by its ARN. 
CF official documentation is also confusing as it only mentions the topic name: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html

I've confirmed with two AWS support engineers that you need to pass the topic ARN and not the name for cross-account notifications (which makes sense). If the CF template is manually updated to update the name to the full ARN, deployment is successful.

**Comment by NGL321** [comment]
New issue created specifically to track continued multi-region failures #11387 11387
