### ISSUE TITLE
[aws-lambda] Make `AssetCode.fromAsset` accept and zip multiple files and directory patterns 

### ISSUE THREAD

**Issue by asterikx** [aws/aws-cdk#9020]
Make `lambda.AssetCode.fromAsset` accept multiple files/directory patterns and transparently zip them.

### Use Case

I have Lambda made up of a Go executable and multiple HTML templates that need to be zipped. But this also applies to any Lambda that needs to be ship with config or any other files.

### Proposed Solution

Using variadic arguments (or arrays), we could specify multiple files/directories. The CDK would zip all matching files/folders transparently so that the user does not need to do this manually.

```ts
const code = new lambda.AssetCode(
  path.join(__dirname, './lambda/bin/sendemail'),
  path.join(__dirname, './mail/dist/*.html')
);
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
This is already being tracked here https://github.com/aws/aws-cdk/issues/984
