### ISSUE TITLE
[@aws-cdk/pipelines] Add ability to subscribe to action.onStateChange

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#9028]
When building a pipeline manually you have access to all the actions that get created and therefore can subscribe an SNS topic to `action.onStateChange`. However, with the new `@aws-cdk/pipelines` package, which nicely wraps all the actions for you, does not allow you to access those underlying actions and therefore cannot call `action.onStateChange`

### Use Case

This is handy for being able to get notified on state changes during pipeline deployment.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by karthikns16** [comment]
Using onEvent instead triggers the event rule for pipeline, stage and actions. Perhaps we could subscribe it to SNS and process the messages using lambda to filter the messages and take appropriate actions
