### ISSUE TITLE
[aws-codebuild] Add support for COMMIT_MESSAGE on FilterGroup

### ISSUE THREAD

**Issue by jacques-** [aws/aws-cdk#9033]
Codebuild FilterGroup (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.FilterGroup.html) contains methods to filter on all attributes except COMMIT_MESSAGE.

### Use Case

Would like to set a COMMIT_MESSAGE filter on builds - need to do this manually at the moment.

### Proposed Solution

Propose adding an `andCommitMessageIs` method to FilterGroup.

Current workaround is to set this manually in console.

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @jacques- ,

thanks for opening the issue. Any chance you can open us a PR with this? 😃 Should be a simple change in this class: https://github.com/aws/aws-cdk/blob/4a714eea4becfee45c71fb6c68144dc6d8275082/packages/%40aws-cdk/aws-codebuild/lib/source.ts#L192-L192 . See our docs on how to get started with a contribution: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#getting-started

Let me know if this is something that might be interesting for you!

Thanks,
Adam

**Comment by jacques-** [comment]
Ok cool, I don't know typescript yet but I'll give it a go.

**Comment by jorge-barreto** [comment]
Hey, I just ran into a use case with the same need. I'm happy to look into creating a PR for this in the next day or so if it isn't being worked by anyone else.

One question I have (and excuse my ignorance here): my project works with the .NET implementation of CDK. What is the process for getting these changes in there?

**Comment by skinny85** [comment]
@jorge-barreto if you submit a change to the TypeScript code, it will be released for .NET - the logic is written only once and then distributed using [JSII](https://github.com/aws/jsii).

**Comment by jorge-barreto** [comment]
> the logic is written only once and then distributed using [JSII](https://github.com/aws/jsii).

Thanks for giving me the skinny on that; cool tech!

**Comment by skinny85** [comment]
You're welcome @jorge-barreto , thanks for the great PR!
