### ISSUE TITLE
[aws-kinesis] Unable to use CfnParameter valueAsNumber in Kinesis Stream 

### ISSUE THREAD

**Issue by dscpinheiro** [aws/aws-cdk#9038]
I'm running into a problem similar to this one: https://github.com/aws/aws-cdk/issues/7126

### Reproduction Steps
```ts
import * as cdk from '@aws-cdk/core';
import * as kinesis from '@aws-cdk/aws-kinesis';

export class KinesisTestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const shardCount = new cdk.CfnParameter(this, 'ShardCount', {
      type: 'Number',
      default: 2,
      minValue: 1,
      maxValue: 200
    });

    const dataRetention = new cdk.CfnParameter(this, 'RetentionHours', {
      type: 'Number',
      default: 24,
      minValue: 24,
      maxValue: 168
    });

    new kinesis.Stream(this, 'TestStream', {
      shardCount: shardCount.valueAsNumber,
      retentionPeriod: cdk.Duration.hours(dataRetention.valueAsNumber)
    });
  }
}
```

### Error Log
```
retentionPeriod must be between 24 and 168 hours. Received -1.8881545897087524e+289
```

### Environment
  - **CLI Version      :** 1.51.0
  - **Framework Version:** 1.51.0
  - **Node.js Version:** v12.18.1
  - **OS               :** macOS Mojave 10.14.6
  - **Language (Version):** TypeScript (3.7.2)

### Other
Similar issue in SQS: https://github.com/aws/aws-cdk/issues/7126
Another possible related issue: https://github.com/aws/aws-cdk/issues/3448

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@dscpinheiro - As you've linked to the similar issue, it will likely need a similar fix (to make validation token aware) and skip it if it contains an unresolved token
