### ISSUE TITLE
[aws-cloudwatch] Support region and account in MathExpression 

### ISSUE THREAD

**Issue by arnulfojr** [aws/aws-cdk#9039]
When trying to specify a cross region/cross account math expression the MathExpression requires also reference to the region and account.

### Use Case

Creating cross account and cross region math expressions.

### Proposed Solution

The Metric class already supports specifying region and accountId but the MathExpression metric doesnt, we could simply just add it

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by arnulfojr** [comment]
Is there a reason why when generating the metrics graph JSON the check `regionIfDifferentFromStack` and `accountIfDifferentFromStack` is made?

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudwatch/lib/private/env-tokens.ts#L3,L15

this seems to be breaking xaxr stacks e.g.,

* stack a in [account x, region f]
* stack b in [account y, region g]
* monitoring stack c in [account z, region g]

`regionIfDifferentFromStack` in monitoring stack will not render a region for the metric and the graph will not entirely work.

**Comment by rix0rrr** [comment]
I would have expected `account` and `region` to be independent. Are you saying they must both be present or both be absent?

Otherwise I don't really see how:

```
{ metric: B, account: Y }
```

Will fail to locate the metric when deployed into `(account Z, region G)`.

**Comment by priyajeet** [comment]
Hi, is this still being worked on?

**Comment by CDillinger** [comment]
I created a wrapper class as a workaround for my use case (using CDK version `1.97.0`). Hoping this can help anyone else who is blocked.

```ts
import * as cloudwatch from 'monocdk/aws-cloudwatch';

export interface XaxrMathExpressionProps extends cloudwatch.MathExpressionProps {
    /**
     * (experimental) Account which this metric comes from.
     *
     * @default - Deployment account.
     * @experimental
     */
    readonly account?: string;
    /**
     * (experimental) Region which this metric comes from.
     *
     * @default - Deployment region.
     * @experimental
     */
    readonly region?: string;
}

export class XaxrMathExpression implements cloudwatch.IMetric {
    private mathExpression: cloudwatch.MathExpression;

    constructor(private readonly props: XaxrMathExpressionProps) {
        this.mathExpression = new cloudwatch.MathExpression(props);
    }

    toAlarmConfig(): cdk.aws_cloudwatch.MetricAlarmConfig {
        throw new Error('Method not implemented.');
    }
    toGraphConfig(): cdk.aws_cloudwatch.MetricGraphConfig {
        throw new Error('Method not implemented.');
    }

    public toMetricConfig(): cloudwatch.MetricConfig {
        const defaultMetricConfig = this.mathExpression.toMetricConfig();
        return {
            ...defaultMetricConfig,
            renderingProperties: {
                ...defaultMetricConfig.renderingProperties,
                accountId: this.props.account,
                region: this.props.region
            }
        }
    }
}
```
