### ISSUE TITLE
[CLI] Automate "cdk bootstrap"

### ISSUE THREAD

**Issue by SachinShekhar** [aws/aws-cdk#9051]
Remove requirement to run `cdk bootstrap` before first deployment to an AWS environment.

### Use Case

Before expanding my CDK app to new regions and accounts, I need to run `cdk bootstrap` which is repeatative & annoying. Lots of times, my CI/CD pipelines for new account fail just because I had forgotten to run `cdk bootstrap` before.

### Proposed Solution

CLI can detect whether an AWS environment has been bootstrapped (that's why it's able to throw error). Instead of throwing error, it can run `cdk bootstrap` and retry deployment.

---

This is a :rocket: Feature Request

**Comment by aritranagnordcloud** [comment]
This is a true blocker for automating CDK Construct creation. We need a way ahead to remove the manual step of cdk bootstrap for 1000 accounts
