### ISSUE TITLE
[pipelines] SelfMutate fails if bootstrapStackName is nonstandard

### ISSUE THREAD

**Issue by J11522** [aws/aws-cdk#9053]
When using a name other than CDKToolkit for the toolkit stack, the Selfupdate build fails waiting for the CDKToolkit stack to finish creating or updating

We should be able to pass this as a property into the build process.

### Reproduction Steps

Follow guideline on how to use the pipeline module, but pass `--toolkit-stack-name some-other-name` in the `cdk `bootstrap` step.

### Error Log

```
Waiting for stack CDKToolkit to finish creating or updating...
StackName failed: Error: StackName: publishing assets requires bootstrap stack version '3', found '0'. Please run 'cdk bootstrap' with a newer CLI version.
```

### Environment

  - **CLI Version      : 1.51.0**
  - **Framework Version: 1.51.0**
  - **Node.js Version:** 14.4.0
  - **OS:**
  - **Language (Version):** TypeScript (3.8.3) 

### Other

We must pass the correct toolkit stack name when calling the cdk deploy here:
 https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts#L66

--- 

This is :bug: Bug Report

**Comment by nonken** [comment]
I can confirm running into the same issue.

**Comment by bryan-hunter** [comment]
any updates on this?  Running into same issue :)

**Comment by mrpackethead** [comment]
I have found a work around to this issue.. that got us out of a whole but hopefully Rico will get something better 
https://github.com/aws/aws-cdk/issues/12205
