### ISSUE TITLE
[@aws-cdk/pipelines] have ability to use the same IAM role for multiple deploying assets

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#9066]
Currently a new role gets created for every asset being uploaded gets it's own Role. This causes a problem when you have a lot of assets being deployed. The template that gets created becomes too large for CF to deploy it correctly.

### Use Case
To deploy a larger amount of assets with the new aws-cdk/pipelines

### Proposed Solution
Be able to pass in a role, or have the construct reuse the same one under the hood.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nonken** [comment]
I am seeing this issue as well with about 35 Lambdas and respective API Gateway routes. Nothing much else. 
I am getting a template size of about 800kB.

**Comment by eladb** [comment]
@njlynch can you take a look at this?

**Comment by seawatts** [comment]
I dug a little deeper and it turns out it's not the KMS keys that are taking up too much space it's the Roles that get created for each asset.

**Comment by srethira** [comment]
Similar issue that I created today: https://github.com/aws/aws-cdk/issues/9237
