### ISSUE TITLE
[@aws-cdk/pipelines] Incorrect CodeBuild image used in default synth action

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9070]
When creating a CDK pipeline the default CodeBuild image in use is the old 1.0 one; 4.0 is the latest and specifying it manually allows the pipeline to build successfully. The issue is the 1.0 build image has an older version of node that is no longer supported by `ts-jest`.

### Reproduction Steps
Follow the readme for `aws-cdk/pipelines` and create a single s3 bucket in the target stack

To resolve the error, change the following on the `synthAction`:
```
environment: { buildImage: codebuild.LinuxBuildImage.STANDARD_4_0 },
```

### Error Log
During the codebuild phase right after the source stage I get the following error: 
```
error ts-jest@26.1.2: The engine "node" is incompatible with this module. Expected version ">= 10.21.0". Got "10.19.0"
```

### Environment

  - **CLI Version:** 1.51
  - **Framework Version:** 1.51
  - **Node.js Version:** v12.13.1
  - **OS               :** MacOS
  - **Language (Version):** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by ericzbeard** [comment]
@justin8 Is this causing the stack to fail? I don't see any errors when I test it.

**Comment by justin8** [comment]
Here is a repo that shows a repro. deploy it, push the repo to the created CodeCommit repo and click release in CodePipeline to reproduce the issue: https://github.com/justin8/cdk-pipeline-bug
