### ISSUE TITLE
[apigatewayv2] Custom Domain example results in 400 due to faulty mappingKey value

### ISSUE THREAD

**Issue by MichaelHindley** [aws/aws-cdk#9077]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html#custom-domain

Example code
```
const certArn = 'arn:aws:acm:us-east-1:111111111111:certificate';
const domainName = 'example.com';

const dn = new DomainName(stack, 'DN', {
  domainName,
  certificate: acm.Certificate.fromCertificateArn(stack, 'cert', certArn),
});

const api = new HttpApi(stack, 'HttpProxyProdApi', {
  defaultIntegration: new LambdaProxyIntegration({ handler }),
  // https://${dn.domainName} goes to prodApi $default stage
  defaultDomainMapping: {
    domainName: dn,
    mappingKey: '/',
  },
});
```

results in error:

An ApiMapping key may contain only letters, numbers and one of $-_.+!*'()

According to docs at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-apimapping.html, the default behaviour is attained by not passing any value to mappingKey.

The mappingKey property however is a non-nullable string.
---

This is a 📕 documentation issue

**Comment by nakedible** [comment]
Empty string will achieve wanted behavior - however, just not passing the value would be preferable.

**Comment by nija-at** [comment]
This is already being tracked here - https://github.com/aws/aws-cdk/issues/9077

**Comment by pahud** [comment]
We are tracking this issue at https://github.com/aws/aws-cdk/issues/8983
