### ISSUE TITLE
[aws-elasticloadbalancingv2] - Assign Target Group to existing ASG

### ISSUE THREAD

**Issue by citosid** [aws/aws-cdk#9089]
### The Question

I have the following code: 

```typescript
    this.nlb = new NetworkLoadBalancer(
      this.parent,
      this.id,
      {
        vpc: this.vpc,
        vpcSubnets: {
          subnets: subnets,
        },
        internetFacing: true,
      }
    );

    const targetGroup = new NetworkTargetGroup(
      this.parent,
      `${this.id}-TG-${listenerPort}-${targetPort}`,
      {
        port: targetPort,
        protocol: Protocol.TCP_UDP,
        targetType: TargetType.INSTANCE,
        vpc: this.vpc,
      },
    );

    const listener = this.nlb.addListener(`${this.id}-TG-${listenerPort}`, {
      port: listenerPort,
      protocol: Protocol.TCP_UDP,
      defaultTargetGroups: [
        targetGroup,
      ]
    });
```

It works as expected creating the network load balancer, the target group and the listener tied to the NLB.

What I cannot accomplish is adding this new TG to an existing AutoScaling Group. 

The ASG is managed by a different project, but I need to add my TG to it.

If I try:

```typescript
    const asg = AutoScalingGroup.fromAutoScalingGroupName(
      this.parent,
      `${this.id}-ASG-${listenerPort}-${targetPort}`,
      config.autoScalingGroup, // This has the name of the autoscaling group
    );

    const targetGroup = new NetworkTargetGroup(
      this.parent,
      `${this.id}-TG-${listenerPort}-${targetPort}`,
      {
        port: targetPort,
        protocol: Protocol.TCP_UDP,
        targets: [asg], // Add the imported ASG as target
        targetType: TargetType.INSTANCE,
        vpc: this.vpc,
      },
    );

```

It does not work because the imported SG does not offer the right methods.

### Environment

  - **CDK CLI Version:** 1.49.1 (build 7d6321f)
  - **Module Version:** 1.49.1
  - **Node.js Version:** v14.5.0
  - **OS:** OSX Catalina
  - **Language (Version):** Typescript (3.7.2)

### Other information

Same issue in [StackOverflow][1]

[1]: https://stackoverflow.com/posts/62777535/edit

**Comment by njlynch** [comment]
Your one other alternative option -- to keep it all within the CDK -- would be to create an [`AwsCustomResource`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html) that makes the CLI call for you.

I'm going to close this out, feel free to comment if you have further questions and we can re-open.
