### ISSUE TITLE
[cdk-pipelines] Manual approval steps are not getting the right RunOrder

### ISSUE THREAD

**Issue by JFox** [aws/aws-cdk#9101]
When using `pipeline.addAdpplicationStage({manualApprovals: true})` the resulting RunOrder for the actions is causing the deploys to be performed without waiting for the manual action to be done

### Reproduction Steps

```typescript
    pipeline.addApplicationStage(
      new WorkloadAccountApplication(this, 'WorkloadAccount', {
        env: { account: '1111111111', region: 'eu-central-1' },
      }),
      {
        manualApprovals: true,
      },
    );
```

### Error Log

![image](https://user-images.githubusercontent.com/376484/87666829-9d228480-c769-11ea-854f-7418a58a1591.png)

### Environment

* **CLI Version      : 1.51.0 (build [8c2d53c](https://github.com/aws/aws-cdk/commit/8c2d53c1830eea396be45d742443623aeb1294c1))**
* **Framework Version: 1.51.0 (build [8c2d53c](https://github.com/aws/aws-cdk/commit/8c2d53c1830eea396be45d742443623aeb1294c1))**
* **Node.js Version: v12.18.0**
* **OS               : aws/codebuild/standard:4.0**
* **Language (Version): TypeScript (3.9.5)**

### Other

--- 

This is :bug: Bug Report

**Comment by woodstock3368** [comment]
When I tried this:
```
    const prodStage = pipeline.addApplicationStage(prod);
    prodStage.addActions(new ManualApprovalAction({
        actionName: 'ApproveChanges'
    }));

```
This at least put the manualApproval BEFORE the execution of Deploy.  However, it also put it with the same runOrder as the Prepare, which is also undesirable, IMHO.  It would be ideal to have this:

```
Myservice.Prepare -> ManualApproval -> Myservice.Deploy
```
Thus allowing for the human reviewer to inspect the ChangeSet after it is completed AND before making the approval to do the Deploy.
