### ISSUE TITLE
[CloudFront] Distribution - Advanced cache behavior control

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#9107]
Expand the new Distribution behaviors to support custom TTLs, configuring forwarded values, and other caching properties.

For completeness, the following are the set of L1 properties that are missing from the current L2:
* cachedMethods
* compress
* defaultTtl
* fieldLevelEncryptionId
* maxTtl
* minTtl
* smoothStreaming
* trustedSigners
* viewerProtocolPolicy
* forwardedValues
  * cookies
  * headers

(This ignores Lambda, which is being tracked separately in #9108)

### Proposed Solution

See aws/aws-cdk-rfcs#171.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ivawzh** [comment]
I think this is a bug (at least a documentation bug).

`allowedMethods`, `defaultTtl` and `viewerProtocolPolicy` are documented everywhere at https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html. E.g. 
```ts
const myWebDistribution = new cloudfront.Distribution(this, 'myDist', {
  defaultBehavior: {
    origin: cloudfront.Origin.fromBucket(myBucket),
    allowedMethods: AllowedMethods.ALLOW_ALL,
    viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
  }
});
```

But it's not in type declarations

```ts
export interface AddBehaviorOptions {
    /**
     * HTTP methods to allow for this behavior.
     *
     * @default - GET and HEAD
     */
    readonly allowedMethods?: AllowedMethods;
    /**
     * Whether CloudFront will forward query strings to the origin.
     * If this is set to true, CloudFront will forward all query parameters to the origin, and cache
     * based on all parameters. See `forwardQueryStringCacheKeys` for a way to limit the query parameters
     * CloudFront caches on.
     *
     * @default false
     */
    readonly forwardQueryString?: boolean;
    /**
     * A set of query string parameter names to use for caching if `forwardQueryString` is set to true.
     *
     * @default []
     */
    readonly forwardQueryStringCacheKeys?: string[];
}
/**
 * Options for creating a new behavior.
 *
 * @experimental
 */
export interface BehaviorOptions extends AddBehaviorOptions {
    /**
     * The origin that you want CloudFront to route requests to when they match this behavior.
     */
    readonly origin: Origin;
}
```

**Comment by njlynch** [comment]
This work is going to be split into 2 (or 3) different PRs:

1. Add the "simple" top-level properties: `cachedMethods`, `compress`, `smoothStreaming`, and `viewerProtocolPolicy`.
2. Add support for the new cache policies and origin request policies. These two new features (released July 21) replace many of the cache control properties (e.g., ttls, forwarded values) and origin behaviors (e.g., origin headers). This may be better suited to two different PRs.

The remaining two properties (`trustedSigners` and `fieldLevelEncryptionId`) require pre-work in the console or SDK to create and manage public keys prior to associating them with a Distribution. Supporting this in a high-quality way is significantly more work and research suggests this are not widely used properties; this are currently considered out of scope for dev preview.

**Comment by njlynch** [comment]
Related to #9644 and #9647, which will add support for the new policies.

**Comment by nabedge** [comment]
I would be very happy if "forwarded cookies" configuration method support !
Regards.

**Comment by salihoglu87** [comment]
@njlynch is it possible  forward QueryStrings or Cookies? as the @nabedge mentioned.
