### ISSUE TITLE
[application-autoscaling] Scale on metric does not return the policy

### ISSUE THREAD

**Issue by gandroz** [aws/aws-cdk#9111]
https://github.com/aws/aws-cdk/blob/d30fa9dda0726230f077c181833fddd40450d6ae/packages/%40aws-cdk/aws-applicationautoscaling/lib/base-scalable-attribute.ts#L72-L75

This is annoying when using en ecs autoscale task as the created scalingpolicy has an evaluation period of 1 by default and it cannot be changed (see https://github.com/aws/aws-cdk/issues/5505)

If the metric was returned, it could hackily been updated according to the proposed solution https://github.com/aws/aws-cdk/issues/5505#issuecomment-596940613

**Comment by NetaNir** [comment]
Can you share a code sample to explain the use case?

**Comment by gandroz** [comment]
```typescript
const cluster = new ecs.Cluster(this, 'myCluster', {            
            vpc: myVpc,
            clusterName: "myCluster"
        });

const taskDefinition = new ecs.Ec2TaskDefinition(this, "myTaskDefinition, {
            networkMode: ecs.NetworkMode.AWS_VPC,
            taskRole: myTaskRole
        });

const ecsService = new ecs.Ec2Service(this, "myService", {
            cluster: cluster,
            taskDefinition: taskDefinition,
            desiredCount: 0,
            securityGroup: mySg,
            serviceName: "myService",
            vpcSubnets: myVpc.selectSubnets({subnetType: ec2.SubnetType.PRIVATE})
        }); 

const queue = new sqs.Queue(this, "myQueue", {
            queueName: "myQueue",
            visibilityTimeout: cdk.Duration.minutes(30)
        });

const queueMetric = queue.metricApproximateNumberOfMessagesVisible({
            period: cdk.Duration.minutes(1),
            statistic: "Average"
        });

const serviceScaling = ecsService.autoScaleTaskCount({minCapacity: 0, maxCapacity: 2});
serviceScaling.scaleOnMetric("myServiceStepScaling", {
            metric: queueMetric,
            scalingSteps: [
                { upper: 0, change: 0 },
                { lower: 1, change: 1 }
            ],
            cooldown: cdk.Duration.minutes(15),
            adjustmentType: appautoscaling.AdjustmentType.EXACT_CAPACITY
        });
```

By defaut, the method `scaleOnMetric` does not return the scaling policy. Furthermore, the created policy has an evaluation period of `1` and it cannot be changed unless you access directly the node children by

```
cfn_alarm = scalingPolicy.lower_alarm.node.default_child
cfn_alarm.evaluation_periods = 5
```

Even this workaround cannot be used as the scaling policy is not returned by the method `scaleOnMetric`, and because the pointed code in the `base-scalable-attribute.ts` does not return the policy either.

**Comment by fschollmeyer** [comment]
This would be highly appreciated. We face the same issue, that we would like to modify evaluation duration and periods.

**Comment by gandroz** [comment]
Another better option would be to add properties in `BasicStepScalingPolicyProps` for the `scaleOnMetric` method to control the `evaluationPeriods` and `treadMissingData` when the upper and lower policies are created under the hood. It is nice to have default parameters, but it would be great to be able either to adjust them during instantiation or afterwards.
