### ISSUE TITLE
[EC2] default role does not allow access to cdk-toolkit S3 Bucket

### ISSUE THREAD

**Issue by jake-jester-nih** [aws/aws-cdk#9118]
https://github.com/aws/aws-cdk/blob/8c2d53c1830eea396be45d742443623aeb1294c1/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L153

I could add the role I guess, but when I use this helper method, it kind of implies it's going to take care of things no?

Even worse, there is no error to respond to when this fails silently. Cloud-init-output.log has nothing. cloud-init.log has an unexpected script run failure with no good information. 

So when you go find the userdata script in /var/lib/cloud/instance/scripts/part-01 and you try and run it, even then the error is mysterious:

```
# /var/lib/cloud/instance/scripts/part-001
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

So then you have to open up the part-0001 and go "hey, its trying to do a aws s3 cp, i bet there's no permissions for that"

I guess my point is that because the error is so difficult to track down, you would probably save people a lot of anguish by including some kind option to let the add s3 download commands method implicitly or explicitly set the correct permissions to the bucket you give it. Or at the least include something in the method documentation.  One should expect their asset downloads to work, and not have to hunt down error logs and run scripts directly on the created resource.

**Comment by jake-jester-nih** [comment]
I found the easy way to do it, but the documentation and implicit/explicit option points still stand I think. If anyone else cares about this:

The easy way to make sure you are good (pseudo code)

asset = new asset()

userdata = new userdata()

instance = new instance( userdata )

userdata.addS3DownloadCommand( asset )

// This is the important one. I think it should probably occur in the addS3DownloadCommand or the need at least be documented.
asset.grantRead( instance )

**Comment by rix0rrr** [comment]
I agree that this is not ideal. I'm actually not super happy with the way we generate UserData right now, but it's unlikely we'll be able to address it in short order.
