### ISSUE TITLE
[@aws-cdk/core] Official guidance on deploying dynamic copies of a stack to one dev environment

### ISSUE THREAD

**Issue by silversteez** [aws/aws-cdk#9124]
## :question: General Issue

Hi there. I'm looking for some official guidance/stance on how one ought to go about deploying dynamic/ephemeral copies of stacks to one CDK dev or test "environment" (account + region) - **the use-case is deploying dynamic copies of stacks for feature-branches with pull requests in CI** (and then adding dynamic path or subdomain like [https://my-awesome-feature-123.example-app.com](https://my-awesome-feature-123.example-app.com) for testing and review).  

All of the CDK docs and examples I've seen make the assumption that organizations will have a few static environments (dev, stage, prod, etc.) that are generally corollated with static account/region combos.

I know that I can simply parameterize the stack ID like this, for example:

```jsx
const app = new cdk.App();
new MyAwesomeAppStack(app, `${GIT_FEATURE_BRANCH_ID}-DashboardServiceStack`);
```

I can deploy copies of my stack this way, but I don't want to push too far down this path if there's a better way to approach the problem. I've searched for docs/example/articles to find prior art on this and I can't seem to find anything, but I feel like this should be a commonly sought-after pattern...

### The Question

Am I missing something? Are there better ways to solve this?

Thanks very much!

### Environment

  - **CDK CLI Version:**  1.51.0
  - **Module Version:** 
  - **Node.js Version:**  10.19.0
  - **OS:**  OSX Catalina
  - **Language (Version):**

**Comment by eladb** [comment]
I think your approach is viable
