### ISSUE TITLE
[aws-lambda-nodejs] when interrupting cdk commands (synth), package.json is left "dirty"

### ISSUE THREAD

**Issue by vvo** [aws/aws-cdk#9130]
Hi there, when using aws-lambda-nodejs, one of the step of the program is to add some configuration for parcel inside the user package.json:

```js
  "cdk-lambda": "/asset-output/index.js",
  "targets": {
    "cdk-lambda": {
      "context": "node",
      "includeNodeModules": {
        "aws-sdk": false
      },
      "sourceMap": false,
      "minify": false,
      "engines": {
        "node": ">= 12"
      }
    }
  }
```

I can see that when running `cdk synth`, my package.json gets updated and then the configuration is removed.

The issue is that if you interrupt cdk synth, for example if it is slow with CTRL+C in a terminal, and it has not yet finished what it needs to do, then your package.json is left dirty with all the parcel configuration still present in it.

I first thought it was some configuration that was needed to be here every time, and then understood it's only temporary configuration.

### Reproduction Steps

- use aws-lambda-nodejs
- launch cdk synth
- stop it in the middle with ctrl + c

### Error Log

no errors

### Environment

  - **CLI Version      :** 1.5.1
  - **Framework Version:** 1.5.1
  - **Node.js Version:** 12.18.2
  - **OS               :** 10.15.5
  - **Language (Version):** JavaScript

### Other

n/a

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Copy @jogold - any way we can avoid writing `package.json` and perhaps reference a copy instead? It it possible to tell parcel to look for package.json elsewhere?

**Comment by jogold** [comment]
https://github.com/parcel-bundler/parcel/issues/5023
