### ISSUE TITLE
How do you vet cdk dependencies?

### ISSUE THREAD

**Issue by eldargab** [aws/aws-cdk#9132]
Hello,

CDK code has a potential to modify critical infrastructure, what makes me wondering how do you maintain dependency hygiene? Are you manually reviewing every updated package or how does it work?

**Comment by NGL321** [comment]
Hi @eldargab,

A combination of our integ testing and Dependabot takes care of most of our dependency evaluation, however we review package licenses before adding anything.

😸 😷

**Comment by eldargab** [comment]
Hello, thanks for response.
