### ISSUE TITLE
[ssm] BucketName: "dummy-value-for-" results in unpredictable behavior

### ISSUE THREAD

**Issue by OlegBoulanov** [aws/aws-cdk#9138]
SystemsManager parameter lookup returns "dummy-value-for-XXXX" at first run.
But if used as a part of BucketName, this throws an exception on invalid bucket name

This results in **_unpredictable behavior_**
- synth/deploy may work for several code changes in a row,
- and fail miserably after **cdk context --clear**

### Reproduction Steps

```
var bucketName = StringParameter.ValueFromLookup(stack, "/ssm/param/bucketName");
var bucketProps = new BucketProps { BucketName = bucketName, }
```

### Error Log

```console
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Invalid S3 bucket name (value: logs.dummy-value-for-/ssm/param/bucketName)
Bucket name must be at least 3 and no more than 63 characters
Bucket name must only contain lowercase characters and the symbols, period (.) and dash (-) (offset: 21)
```

### Environment

 - > cdk --version 1.51.0 (build 8c2d53c)
  - **Node.js Version:** v12.7.0
  - **OS:** Windows
  - **Language (Version):** C#

### Other

Can you please check for dummy and not throw from resource constructors?
You do check for tokens already, don't you?

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
related to https://github.com/aws/aws-cdk/issues/8699

**Comment by mspolitaev** [comment]
Hi team! Still planned to be fixed or waiting for better times?)

**Comment by gel1123** [comment]
Almost the same problem occurs when specifying a custom domain in API Gateway.

**Comment by jsamarziya** [comment]
A potential workaround might be to use `StringParameter.valueForStringParameter()` instead of `StringParameter.valueFromLookup()`. That method returns a token instead of a string, and I found that it worked for me in the case of
```
s3.Bucket.fromBucketName(stack, "MyBucket", ssm.StringParameter.valueForStringParameter(stack, "myBucketParamName"))
```
