### ISSUE TITLE
[aws-appsync]: update/write more comprehensive unit/integration tests

### ISSUE THREAD

**Issue by BryanPan342** [aws/aws-cdk#9139]
## :question: General Issue
We need better unit tests and integration tests for the appsync repo.

- [ ] Resolvers
- [ ] GraphQLAPI
- [ ] Data Sources
- [ ] Mapping Templates

**Comment by alan-cooney** [comment]
You might want to look at https://github.com/skyhookadventure/appsync-template-tester
