### ISSUE TITLE
[batch] aws_batch.JobDefinition to keep previous revisions Active on update

### ISSUE THREAD

**Issue by jabrennem** [aws/aws-cdk#9144]
I tried to look for issues/bugs with this, but I was not able to find any. I am not sure if this is a bug fix or just a feature request. Most of the projects that I work on consist of managing AWS Batch Job Definitions and State Machines to orchestrate large batches of docker containers at once. Each revision of a job definition points to a particular tag of an ECR image for backwards compatibility. In my CDK stack, any time there is any edit to my JobDefinition construct, the stack registers a new job definition revision but deregisters the previous revisions. Is there a way to prevent cdk from deregistering the previous revisions? I can implement this is boto3, but I want to try a native cdk approach.

### Reproduction Steps

Initial cdk deploy which creates revision 1 pointing to image:0.0.0

```python
self._job_def = JobDefinition(self, 'JobDef', 
     job_definition_name="job-definition-name",
     container=JobDefinitionContainer(
            image=ecr_image,  # using tag 0.0.0
))
```

Second cdk deploy which creates revision 2 properly pointing to image:0.0.1, but deregisters revision 1

```python
self._job_def = JobDefinition(self, 'JobDef', 
     job_definition_name="job-definition-name",
     container=JobDefinitionContainer(
            image=ecr_image,  # using tag 0.0.1
))
```

### Error Log

No errors, but there is an unwanted deregister step.

### Environment

  - **CLI Version      :** 1.48.0 (build 6080fa8)
  - **Framework Version:** 1.51.0
  - **Node.js Version:** node - 12.16.1, npm 6.13.4
  - **OS               :** Mac OS Mojave 10.14.6
  - **Language (Version):** Python 3.8.3

### Other

[JobDefinition CF](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html)

Above is a link to CloudFormation Resource type page for JobDefinition. The only property I could find for update requires Replacement is job definition name. However, the job definition is always the same in my example.

--- 

This is :bug: Bug Report

**Comment by jabrennem** [comment]
I was experimenting with the underlying CfnJobDefinition using node.children and changed for Removal Policy to retain. I wanted to add another discovery that I thought might pertain to this.  

```bash
cdk deploy
```
```python
self._job_def = JobDefinition(self, 'JobDef', 
     job_definition_name="job-definition-name",
     container=JobDefinitionContainer(
            image=ecr_image,  # using tag 0.0.1
))

# a little hacky, but it worked 
for child in self._job_def.node.children:
    if hasattr(child, 'apply_removal_policy') and hasattr(child, 'cfn_resource_type') and child.cfn_resource_type == 'AWS::Batch::JobDefinition':  # search for CfnBatchJobDefinition
        child.apply_removal_policy(policy=core.RemovalPolicy.RETAIN)
```

This repeats the same functionality as in the issue. Creates a revision 1 pointing to tag v0.0.1 and deregisters the previous revision. However, after I run
```bash
cdk destroy
```
The batch job definition is retained. When I run again
```bash
cdk deploy
``` 
It adds a new revision 2 to the pre-existing JobDefinition pointing to tag 0.0.1, but does not remove the previous revision. I am not sure how cdk works in the backend, but it's almost as if 'updating' uses a different removal policy? I'd love to hear an expert's analysis of it.

**Comment by iliapolo** [comment]
Hi @jabrennem - Thanks for reporting this. Just wanted to reach out and let you know i'll be looking into it this week and share my conclusions.

**Comment by iliapolo** [comment]
Hi @jabrennem - Sorry for the long delay. 

It does seem that the CloudFormation behavior for `JobDefinition` is to create a new revision for every change that doesn't require a replacement, and **delete** all other **managed** revisions. When a `JobDefinition` is deployed, CloudFormation looks up the latest revision, and creates a new one on top of that, leaving any **unmanaged** revisions as is.

By **managed**, I mean those created by CloudFormation as well. This is why when you destroy the stack with `RETAIN`, what effectively happens is you turn the previously **managed** revision, to an **unamanged** one, and is therefore ignored on subsequent deploys. The same thing will happen if you create a revision from the console or any other tool, those revisions will remain when you destroy and deploy the stack.

CloudFormation doesn't expose any configuration pertaining to versions, so i'm afraid there is no way to change this behavior.
CDK itself has no additional backend logic that interacts with the AWS Batch API. 

So my suggestion would be as follows:

1. Create a support ticket on the AWS Forum describing this behavior.
2. Create a [CloudFormation Coverage Issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/new) requesting specific support for `JobDefinition` revisions. Maybe a new resource: `JobDefinitionRevision`.
3. If possible, create a new `JobDefinition` in CDK for every new image tag.

It would be good if you detail your exact use-case and flow that requires to retain old revisions. I imagine you have jobs running with the old revision definition during deployment of new ones? Can you share the full code?

**Comment by sumpfork** [comment]
To note, we have a similar issue: We run batch jobs from step functions that can take a long time prior to starting the batch job. When our continuous deployment deploys a new version of the step function, this step function will in many cases point to a new revision of the batch job definition. However, any currently running step function that hasn't reached the batch job yet will fail because it points to a now inactive job definition revision.

**Comment by jabrennem** [comment]
Thank you @iliapolo for looking into this. 

I cannot share any code, but your description has helped a lot. I will submit a CloudFormation Coverage Issue to hopefully gain more control over the batch job revisions. I like the idea of a JobDefinitionRevision resource.

For right now, creating a separate batch job definition for each new image:tag will work, and at least it is still a native CDK implementation.

**Comment by rpbarnes** [comment]
Is there any follow up on this? It seems like a serious bug? 

I have a very similar use case. I have a step function definition that runs many potentially long running aws batch jobs in serial. This is all defined in aws cdk. Any time I deploy code, any step function that is currently running fails on the next step because the batch job's jobDefinition is no longer in an active state. 

Is there any suggested way to keep old jobDefinitions in an Active state on deploy? I tried creating a new Job definition on each deploy (by incrementing the jobDefinition `id`) however the old job definitions are still set to Inactive.

**Comment by rpbarnes** [comment]
I also do not see a way to set old `Inactive` jobDefinitions to `active`. Is there any way to do that?

**Comment by sumpfork** [comment]
> I also do not see a way to set old `Inactive` jobDefinitions to `active`. Is there any way to do that?

No, I don't believe so. I did implement what I alluded to above: I set all the batch job definitions to be retained and then register a custom resource that finds all definitions that have not been used in some time and deregisters them.

**Comment by rpbarnes** [comment]
> > I also do not see a way to set old `Inactive` jobDefinitions to `active`. Is there any way to do that?
> 
> No, I don't believe so. I did implement what I alluded to above: I set all the batch job definitions to be retained and then register a custom resource that finds all definitions that have not been used in some time and deregisters them.

How did you do that? I can't seem to find any docs for aws-cli or boto3 that describe how to change status of a job.

**Comment by sumpfork** [comment]
> > > I also do not see a way to set old `Inactive` jobDefinitions to `active`. Is there any way to do that?
> > 
> > 
> > No, I don't believe so. I did implement what I alluded to above: I set all the batch job definitions to be retained and then register a custom resource that finds all definitions that have not been used in some time and deregisters them.
> 
> How did you do that? I can't seem to find any docs for aws-cli or boto3 that describe how to change status of a job.

In essence, the resource uses https://docs.aws.amazon.com/batch/latest/APIReference/API_DescribeJobDefinitions.html to find all job definitions and their statuses, https://docs.aws.amazon.com/batch/latest/APIReference/API_ListJobs.html and https://docs.aws.amazon.com/batch/latest/APIReference/API_DescribeJobs.html to find recently run jobs that use definitions that are still active in the first list, then https://docs.aws.amazon.com/batch/latest/APIReference/API_DeregisterJobDefinition.html to get rid of definitions that appear active but unused after all that filtering.

**Comment by rpbarnes** [comment]
Oh sorry, how did you re-activate an inactive job? I saw the API_registerJobDefinition but that looked like it would only work for creating new jobDefinitions

**Comment by sumpfork** [comment]
> Oh sorry, how did you re-activate an inactive job? I saw the API_registerJobDefinition but that looked like it would only work for creating new jobDefinitions

I don't, I just change the policy to keep everything active until the custom resources deactivates them.

**Comment by rpbarnes** [comment]
How do you keep every job active?

**Comment by sumpfork** [comment]
> How do you keep every job active?

With something like
```
for child in job_definition.node.children:
    if (
        hasattr(child, "apply_removal_policy")
        and hasattr(child, "cfn_resource_type")
        and child.cfn_resource_type == "AWS::Batch::JobDefinition"
    ):
        child.apply_removal_policy(policy=aws_cdk.RemovalPolicy.RETAIN)
```
-- haven't checked for updated batch support in the CDK for a while, I admit. One additional bit is that we make each job definition name unique with a known prefix so we can identify which ones are relevant in the custom resource. It's all a big hack.

**Comment by rpbarnes** [comment]
ahh I got you thanks for sharing. I misunderstood the comments above to think that this wouldn't work.

**Comment by ChristopheBougere** [comment]
@iliapolo would it be possible to reopen the issue?
It is still not handled by CDK/CloudFormation, and the proposed workaround is pretty hacky

**Comment by MacHu-GWU** [comment]
I personally think these kind of versioned resource should not be managed by CloudFormation either CDK. I have experiences devops the following resources:

- AWS Lambda Layer Version
- AWS Lambda version and alias
- Parameter Store version
- Batch Version

Based on my own experience, you should add a post CDK hook shell script ( I use Python ) after the ``cdk deploy`` command, and create a new version via the API.

Because, those versioned resources are designed to be immutable (otherwise what's the point) for rollback or version control. Resources are managed by CDK or CloudFormation is considered as "Managed" and "Mutable". Using Infrastructure as Code to manage immutable resource natively is a bad idea and you should avoid.

**Comment by MacHu-GWU** [comment]
> for child in job_definition.node.children:
>     if (
>         hasattr(child, "apply_removal_policy")
>         and hasattr(child, "cfn_resource_type")
>         and child.cfn_resource_type == "AWS::Batch::JobDefinition"
>     ):
>         child.apply_removal_policy(policy=aws_cdk.RemovalPolicy.RETAIN)

this doesn't work .

**Comment by miltonhit** [comment]
> > for child in job_definition.node.children:
> > if (
> > hasattr(child, "apply_removal_policy")
> > and hasattr(child, "cfn_resource_type")
> > and child.cfn_resource_type == "AWS::Batch::JobDefinition"
> > ):
> > child.apply_removal_policy(policy=aws_cdk.RemovalPolicy.RETAIN)
> 
> this doesn't work .

You need to do this:

[java example]
```
        this.taskDefinition.applyRemovalPolicy(RemovalPolicy.RETAIN, RemovalPolicyOptions.builder()
                .applyToUpdateReplacePolicy(true)
                .build());
```

**Comment by paul-michalik** [comment]
> I personally think these kind of versioned resource should not be managed by CloudFormation either CDK. I have experiences devops the following resources:
> 
> * AWS Lambda Layer Version
> * AWS Lambda version and alias
> * Parameter Store version
> * Batch Version
> 
> Based on my own experience, you should add a post CDK hook shell script ( I use Python ) after the `cdk deploy` command, and create a new version via the API.
> 
> Because, those versioned resources are designed to be immutable (otherwise what's the point) for rollback or version control. Resources are managed by CDK or CloudFormation is considered as "Managed" and "Mutable". Using Infrastructure as Code to manage immutable resource natively is a bad idea and you should avoid.

I believe, given the current capabilities of CloudFormation and the correctness constraints, this is the best proposal.

**Comment by paul-michalik** [comment]
> > How do you keep every job active?
> 
> With something like
> 
> ```
> for child in job_definition.node.children:
>     if (
>         hasattr(child, "apply_removal_policy")
>         and hasattr(child, "cfn_resource_type")
>         and child.cfn_resource_type == "AWS::Batch::JobDefinition"
>     ):
>         child.apply_removal_policy(policy=aws_cdk.RemovalPolicy.RETAIN)
> ```
> 
> -- haven't checked for updated batch support in the CDK for a while, I admit. One additional bit is that we make each job definition name unique with a known prefix so we can identify which ones are relevant in the custom resource. It's all a big hack.

Hm, setting a resource deletion policy to "RETAIN" does not prevent CloudFormation from setting the old "unmanaged" resource into "INACTIVE" state. So how did you achieve that?

**Comment by paul-michalik** [comment]
Note: the solution is to use [`UpdateReplacePolicy: Retain`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html). Somehow this is very well hidden in the documentation. You can set it in CDK in exactly the same as `DeletionPolicy`

**Comment by elephant-seal** [comment]
Found that the other important change here besides just setting the CloudFormation policy to `RETAIN` was to set a different unique name for the job definition so that it creates a new one. 

When doing this, each previous job definition with a different name stays active, whereas only setting `RETAIN` with the same job definition name would deactivate the old versions.

**Comment by PravinthAWS** [comment]
AWS Batch has released the ability to skip deregistering the previous revision on update events for AWS::Batch::JobDefinition resources. 

This feature can be utilized via these properties: `ResourceRetentionPolicy` and its child attribute `SkipDeregisterOnUpdate`.

Here are the CDK docs on these properties: 
- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.CfnJobDefinition.html#resourceretentionpolicy
- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.CfnJobDefinition.ResourceRetentionPolicyProperty.html
