### ISSUE TITLE
[ecs] Cannot disable containerInsights of a cluster whose setting is enabled

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#9149]
I tried disabling containerInsights of an ECS cluster but it failed.
It seems CFn doesn't support removing the setting but replacing.

### Reproduction Steps
1. deploy a cluster with containerInsights enabled:

```ts
new ecs.Cluster(this, "cluster", {
    clusterName: "cluster",
    vpc: vpc,
    containerInsights: true,
});
```

2. re-deploy the cluster after switching containerInsights to disabled:
```ts
new ecs.Cluster(this, "cluster", {
    clusterName: "cluster",
    vpc: vpc,
    containerInsights: false,
});
```

c.f. cdk diff when deploying in 2nd step

```
Resources
[~] AWS::ECS::Cluster cluster cluster611F8AFF 
 └─ [-] ClusterSettings
     └─ [{"Name":"containerInsights","Value":"enabled"}]
```

### Error Log
When deploying in 2nd step, an error occurs:

```
11:34:57 | UPDATE_FAILED        | AWS::ECS::Cluster       | cluster611F8AFF
Error occurred during operation 'Settings can only be modified, not removed. Required Settings: [containerInsights]'.
```

### Environment

  - **CLI Version      :1.50.0**
  - **Framework Version:1.50.0**
  - **Node.js Version:v13.11.0** 
  - **OS               :macOS 10.15.4**
  - **Language (Version): TypeScript** 

### Other
The cdk diff is supposed to be below:

```
[~] AWS::ECS::Cluster cluster cluster611F8AFF 
 └─ [~] ClusterSettings
     └─ @@ -1,6 +1,6 @@
        [ ] [
        [ ]   {
        [ ]     "Name": "containerInsights",
        [-]     "Value": "enabled"
        [+]     "Value": "disabled"
        [ ]   }
        [ ] ]
```

--- 

This is :bug: Bug Report

**Comment by chrisb87** [comment]
I see there's an unreleased fix for this (https://github.com/aws/aws-cdk/pull/9151). 

Until that's released, what's the process for manually fixing this? I have a service deployed with CDK that has container insights enabled, and I want to disable it. If I do this outside the CDK, it will never know the value was changed and continue to fail deployments.

**Comment by tmokmss** [comment]
@chrisb87 
I think there's no workaround as long as you use CDK.
To disable the setting there's only two ways: 
1. Re-create the cluster
2. disable it using AWS-CLI and allow CFn drift

anyway hope it'll be merged soon:(
