### ISSUE TITLE
[aws-appsync] Add Relational Database (rds) datasource 

### ISSUE THREAD

**Issue by kochie** [aws/aws-cdk#9152]
Currently the `GraphQLApi` only supports dynamo, HTTP, none, and lambda data sources and is missing the Relational Database source.

### Use Case

When setting up an RDS datasource currently can't use CDK to create that datasource.

### Proposed Solution

Create an RDS datasource. I'm happy to get moving on this if no one has started yet.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
@kochie go for it! i dont think anyone is working on it

**Comment by kochie** [comment]
Currently working on it in #9258
