### ISSUE TITLE
[aws-cloudwatch] The period of a MathExpression is not respected on CloudWatch

### ISSUE THREAD

**Issue by jrmcornish** [aws/aws-cdk#9156]
The `period` of a `MathExpression` CloudWatch metric that is used in a `GraphWidget` is currently not respected. In particular, it is possible to specify a period of 1 minute, but for data points still to be spaced every 5 minutes.

### Reproduction Steps

Assume below that `queue` is some `aws_sqs.Queue`, and `dashboard` is some `aws_cloudwatch.Dashboard`. Then consider the following:

    metric = queue.metric_approximate_number_of_messages_visible()

    dashboard.add_widgets(
        aws_cloudwatch.GraphWidget(
            left=[
                aws_cloudwatch.MathExpression(
                    expression=f"2 * x",
                    using_metrics={"x": metric},
                    period=core.Duration.minutes(1)
                )
            ]
        )
    )

In CloudWatch, this produces a widget showing data points every 5 minutes, rather than every 1 minute as expected.

### Error Log

The actual JSON produced for the widget above will be similar to the following (apart from QueueName and region changes):

```
{
    "view": "timeSeries",
    "region": "us-east-1",
    "metrics": [
        [ { "label": "2 * x", "expression": "2 * x", "region": "us-east-1" } ],
        [ "AWS/SQS", "ApproximateNumberOfMessagesVisible", "QueueName", "MY_QUEUE_NAME", { "period": 60, "stat": "Maximum", "visible": false, "id": "x" } ]
    ],
    "period": 300
}
```

This corresponds to showing measurements spaced every 5 minutes by default. 

If the first `metrics` item in the dictionary above is replaced with

```
        [ { "label": "2 * x", "expression": "2 * x", "region": "us-east-1", "period": 60 } ],
```

then data points are spaced correctly every 1 minute. However, the code produced by the CDK does not generate this.

### Environment

  - **CLI Version      :** `aws-cli/1.18.8 Python/3.7.4 Linux/5.3.0-62-generic botocore/1.15.8`
  - **Framework Version:** `1.45.0 (build 0cfab15)`
  - **Node.js Version:**  `v10.16.3`
  - **OS               :** `Linux 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
  - **Language (Version):**  `Python 3.7.4`

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Well we completely generated it like this on purpose, where the math expression would get rendered at the resolution of the underlying metrics. I remember testing this, and I wonder if CloudWatch changed its behavior here.

The fix is probably to always emit a `period` for the math expression.
