### ISSUE TITLE
[cdk-pipelines] CdkPipelines SimpleSynthAction.standardYarnSynth incorrectly maps `options.synthCommand` to `installCommand`

### ISSUE THREAD

**Issue by JeremyJonas** [aws/aws-cdk#9162]
https://github.com/aws/aws-cdk/blob/cb5dad8854b59bf89e41348a5e8010ff2e4612f3/packages/%40aws-cdk/pipelines/lib/synths/simple-synth-action.ts#L156

`installCommand` command is not overridable and incorrectly mapped to `options.synthCommand`
```
  public static standardYarnSynth(options: StandardYarnSynthOptions) {
    return new SimpleSynthAction({
      ...options,
      // BUG: this should be `options.installCommand` instead of `options.synthCommand`
      installCommand: options.synthCommand ?? 'yarn install --frozen-lockfile',
      synthCommand: options.synthCommand ?? 'npx cdk synth',
    });
  }
```

**Comment by njlynch** [comment]
Thanks for the bug report, @JeremyJonas! The fix has been merged and will go out with the next release.
