### ISSUE TITLE
[cdk-pipelines] SimpleSynthAction unable to set role or add policies to it.

### ISSUE THREAD

**Issue by JeremyJonas** [aws/aws-cdk#9163]
https://github.com/aws/aws-cdk/blob/cb5dad8854b59bf89e41348a5e8010ff2e4612f3/packages/%40aws-cdk/pipelines/lib/synths/simple-synth-action.ts#L164

Is there a way to set the role or add policies to it for SimpleSynthAction?

Currently when I create a new SimpleSynthAction, and even after it is bound, the `actionProperties.role` is always undefined. Additionally the props don't accept a role or policies to set during instatiation.

My synth action depends on getting permissions to a CodeArtifact repo (aws codeartifact login...).

Thank you!

**Comment by njlynch** [comment]
> Is there a way to set the role or add policies to it for SimpleSynthAction?

Not at this time. Marking this as a feature request; we could add an optional role to the `SimpleSynthOptions` to be used for the CodeBuild action. PRs welcome!
