### ISSUE TITLE
[certificatemanager] `validationDomains` ignored if validation method is DNS

### ISSUE THREAD

**Issue by aereal** [aws/aws-cdk#9164]
`validationDomains` ignored at v1.52.0 if `validationMethods` is DNS but not ignored if is EMAIL.

The below line that introduced by #8552 may cause that issue:

https://github.com/aws/aws-cdk/blob/cb5dad8854b59bf89e41348a5e8010ff2e4612f3/packages/%40aws-cdk/aws-certificatemanager/lib/certificate.ts#L197

### Reproduction Steps

1. aws-cdk@<1.52.0: create `Certificate` with `validationDomains`
2. update aws-cdk with 1.52.0
3. encountered `Certificate` change with replacement and missing `DomainValidationOptions` property if run `cdk diff` (or some tests)

See https://github.com/aereal/bug-aws-cdk-acm-validation-domains/pull/1 for details with `@aws-cdk/assert` reproducing steps.

### Error Log

(no errors)

### Environment

  - **CLI Version      :1.52.0 (build 5263664)**
  - **Framework Version:1.52.0**
  - **Node.js Version:v14.5.0**
  - **OS               :macOS 10.15.6**
  - **Language (Version):TypeScript (3.8.3)**

### Other

I think this is a bug because of #8552 is introduced as new feature instead of breaking change so we expect that feature brakes no existent code.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Hi @aereal, thanks for the bug report!

> validationDomains ignored at v1.52.0 if validationMethods is DNS but not ignored if is EMAIL.

This actually represents a bug in how pre-v1.52.0 handled the `validationDomains` field; `validationDomains` is an email-specific validation field, as seen in [the ACM docs](https://docs.aws.amazon.com/acm/latest/APIReference/API_DomainValidation.html#ACM-Type-DomainValidation-ValidationDomain), and is only used to control which domain receives the validation emails. It does not have any impact on certificates that use DNS-based validation.

To workaround the impact and prevent replacement, you can override the logical ID and re-add the (unused) domain validation options block back to your certificate.

```ts
const cfnCert = (cert.node.defaultChild as CfnCertificate);
cfnCert.overrideLogicalId('CertificateId12345');
cfnCert.domainValidationOptions = [{
  domainName: 'mdomain.example.com',
  validationDomain: 'example.com',
}];
```

Closing this out, as the 1.52 behavior is as expected.

**Comment by aereal** [comment]
I got it, thank you.
