### ISSUE TITLE
[aws-lambda] Generated python example does not work

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#9169]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda.README.html

If I copy the code I get the following error message:
```
import aws_cdk.aws_lambda as lambda
                                      ^
SyntaxError: invalid syntax
```

`lambda` is a keyword in python. This documentation is probably generated and works fine in TypeScript, but it doesn't work for python.

---

This is a 📕 documentation issue

**Comment by Jerry-AWS** [comment]
FWIW, in the Developer Guide I have used `lambda_` to translate this to Python.

**Comment by abelmokadem** [comment]
@Jerry-AWS I normally use and teach CDK with TypeScript, but I'm currently teaching CDK with Python and discovered that the examples are "generated" from TypeScript code. There are other things like `__dirname`, that also needs to be translated to Python. For the students, it's a bit difficult to take in all the new stuff on CDK and then struggle with the documentation examples as well. Is it possible to make the code generation generate code that works?

**Comment by Jerry-AWS** [comment]
It's a really tough problem to translate code from one programming language to another, and it's not perfect, but it's better than just having TypeScript code examples in the Python API reference.  :-)

I'm not involved in the API reference (I work on the [Dev Guide](https://docs.aws.amazon.com/cdk/latest/guide/home.html)) but I've +1'd this issue as `lambda` is something that will crop up regularly in code examples.

In the Dev Guide I use auto-translation for TypeScript to JavaScript, but even that sometimes needs a little manual touching up. The Python, Java, and C# examples I translate by hand, and you shouldn't find this kind of problem there.

The [CDK Workshop](https://cdkworkshop.com/) is also translated by hand and might be a better place to start students.
