### ISSUE TITLE
[custom-resources] Allow AwsCustomResource with cross account calls

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [aws/aws-cdk#9170]
Currently it is possible to set a role for the AwsCustomResource construct. But this role is then applied to all AwsCustomResources. This makes it impossible to use custom resources for the same and different accounts together.

### Use Case

Imaging deploying a website to S3 where the Cloudfront CDN is in a different account and you want to run a cache invalidation in response to a deployment.

Or an API Gateway that you want to register to CloudMap after deployment, but the CloudMap registry is in another account.

### Proposed Solution

A current workaround is of course to write a fully custom resource that assumes a role in a different account and issues the api call.

A solution would be add a prop to the `SdkCall` type called something like `assumedRole` or  `crossAccountRole` of type `iam.Role`. This role must then be assumable by the execution role of the lambda (but this is out of scope of the CDK). Then the lambda checks for the presence of this field and optionally assumes the role and passes the credentials to the client.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by McDoit** [comment]
@matthias-pichler-warrify 
Fixed by #13916 , great minds think alike (but i was late on the ball)
