### ISSUE TITLE
Reference examples for C#/.NET show "new Struct" when it should be "new <module>Props"

### ISSUE THREAD

**Issue by Doug-AWS** [aws/aws-cdk#9185]
https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.Cognito.html

Example of creating a user pool:
```
new UserPool(this, "myuserpool", new Struct {
    UserPoolName = "myawesomeapp-userpool"
});
```

This should be:
```
new UserPool(this, "myuserpool", new UserPoolProps {
    UserPoolName = "myawesomeapp-userpool"
});
```

This problem is all over the place in the .NET reference examples. Very annoying.

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Oh gosh. This looks broken.

This is not just for Cognito but in other places as well - https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.APIGateway.html#aws-lambda-backed-apis

**Comment by nija-at** [comment]
Correction: It seems that the examples in the README need to be made 'buildable' for the translation to work correctly. Looks like at the moment, none of the Cognito examples compile in our doc translation system.

**Comment by rix0rrr** [comment]
It shouldn't be all that much work to make them compilable. Mostly consists of adding one (or more) fixture files and annotating the snippet, if there is more than one fixture:

Default fixture file example: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/rosetta/default.ts-fixture

Subsequent fixture file: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/rosetta/with-vpc.ts-fixture

Annotated snippet: https://github.com/aws/aws-cdk/blame/master/packages/%40aws-cdk/aws-ec2/README.md#L516

**Comment by rix0rrr** [comment]
@Doug-AWS you could help with this if you want. Or maybe @Jerry-AWS can find the time.

**Comment by Jerry-AWS** [comment]
@rix0rrr Yeah, I'll have a look. Need to learn how this works anyway.

**Comment by peterwoodworth** [comment]
This issue was never fixed; the docs still say `struct` on the .NET [Cognito](https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.Cognito.html) and [RDS](https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.RDS.html) docs, as well as the locations @nija-at mentioned.

**Comment by corymhall** [comment]
I think this has been fixed now. I've looked at all the links mentioned and can't find any remaining issues. I think all the work with rosetta has ended up fixing this.
