### ISSUE TITLE
[aws-lambda-nodejs] LambdaNodeJs corrupts STDOUT

### ISSUE THREAD

**Issue by dave-graham** [aws/aws-cdk#9186]
When running 

`cdk synth --no-staging > template.yaml`

The following is output into the template.yaml file at the top:

> Building widgets.ts...
> Bundling...
> ✨ Built in 19.44s
> 
> ../../asset-output/index.js    4.89 KB    645ms

This causes the template.yaml to be broken.

Can the output from bundling not be output when running the synth with --no-staging?

This is :bug: Bug Report

**Comment by eladb** [comment]
@jogold we should get this output to STDERR...

**Comment by eladb** [comment]
@dave-graham What language are you using?

**Comment by dave-graham** [comment]
Typescript

**Comment by dave-graham** [comment]
Is is possible to look at how it updates "aws:asset:path" when using --no-staging too?

I would expect the aws:asset:path to still refer to the original file, rather than bundled version when adding --no-staging, but it's looking like:

`aws:asset:path: /Users/user-name/path-to-project/.cdk.staging/asset-bundle-L5zSs8`

This is preventing me from using breakpoints in vscode to debug, using for example:

`echo '{}' | sam local invoke -d 9999 ServerlessFunctionName  `

**Comment by eladb** [comment]
> Is is possible to look at how it updates "aws:asset:path" when using --no-staging too?
> 
> 
> 
> I would expect the aws:asset:path to still refer to the original file, rather than bundled version when adding --no-staging, but it's looking like:
> 
> 
> 
> `aws:asset:path: /Users/user-name/path-to-project/.cdk.staging/asset-bundle-L5zSs8`
> 
> 
> 
> This is preventing me from using breakpoints in vscode to debug, using for example:
> 
> 
> 
> `echo '{}' | sam local invoke -d 9999 ServerlessFunctionName  `
> 
> 
> 
> Or even just general debugging, as I need to run a cdk synth each time I make a change to the lambda.

Can you please raise a separate issue for this?

**Comment by dave-graham** [comment]
Sure @eladb

**Comment by jogold** [comment]
The problem is here
https://github.com/aws/aws-cdk/blob/489eae64f6613cac85da2a70b33435052901255b/packages/%40aws-cdk/core/lib/bundling.ts#L124

Looking for a way to redirect `stdout` to `stderr`
