### ISSUE TITLE
[aws-cdk] rds module not able to add proxy 

### ISSUE THREAD

**Issue by I2olanD** [aws/aws-cdk#9195]
Hey,
i'm currently trying to add a RDS proxy to my db cluster. Apparently, i get following error:
Cannot read property 'engine' of undefined.

### Reproduction Steps

```ts
		const vpc = ec2.Vpc.fromLookup(myScope, 'someId', { 
			vpcId: 'vpc-id'
		});

		const securityGroup = ec2.SecurityGroup.fromSecurityGroupId(myScope, 
			'someId', 
			'securit-group-id'
		);

		const cluster = DatabaseCluster.fromDatabaseClusterAttributes(myScope, 'someId', {
			port,
			securityGroups: [securityGroup],
			clusterIdentifier: 'cluster-identifier',
			instanceIdentifiers: ['instance-identifier'],
			clusterEndpointAddress: ''writer-endpoint,
			readerEndpointAddress: 'reader-endpoint',
			instanceEndpointAddresses: ['instance endpoint']
		});

		const secret = new Secret(myScope, 'Secret');

		cluster.addProxy('testProxy', {
			borrowTimeout: cdk.Duration.seconds(30),
			maxConnectionsPercent: 50,
			secrets: [secret],
			vpc
		});
```

### Error Log

Cannot read property 'engine' of undefined.

### Environment

  - **CLI Version      :*1.53.0*
  - **Framework Version: *1.53.0*
  - **Node.js Version: *10.19.0*
  - **OS               :**
  - **Language (Version): *all*

This is :bug: Bug Report

**Comment by civilizeddev** [comment]
### Sorry, currently not available

`DatabaseCluster.fromDatabaseClusterAttributes` returns `IDatabaseCluster`, which doesn't have `engine` in it.

There's no way to read `engine` from imported RDS instance/cluster resource at the moment.

Its' unstable that it currently rely on `(this.dbCluster.node.defaultChild as CfnDBCluster).engine`.

https://github.com/aws/aws-cdk/blob/489eae64f6613cac85da2a70b33435052901255b/packages/%40aws-cdk/aws-rds/lib/proxy.ts#L69-L75

Ideas and suggestions are welcome.

**Comment by I2olanD** [comment]
Would it be possible to add the engine property to the IDatabaseCluster?

**Comment by I2olanD** [comment]
Any updates on this @civilizeddev ?

Best,

Roland

**Comment by civilizeddev** [comment]
@I2olanD I'm sorry for late response.

As for this issue, @skinny85 suggested a better solution.

**Comment by I2olanD** [comment]
hey @civilizeddev,

i've set it up now like this but don't really know how to proceed:

             const vpc = ec2.Vpc.fromLookup(myScope, 'someId', { 
			vpcId: 'vpc-id'
		});

		const securityGroup = ec2.SecurityGroup.fromSecurityGroupId(myScope, 
			'someId', 
			'securit-group-id'
		);

		const cluster = DatabaseCluster.fromDatabaseClusterAttributes(myScope, 'someId', {
			port,
			securityGroups: [securityGroup],
			clusterIdentifier: 'cluster-identifier',
			instanceIdentifiers: ['instance-identifier'],
			clusterEndpointAddress: ''writer-endpoint,
			readerEndpointAddress: 'reader-endpoint',
			instanceEndpointAddresses: ['instance endpoint'],
			engine: {
				singleUserRotationApplication: secretsmanager.SecretRotationApplication.MYSQL_ROTATION_SINGLE_USER,
				multiUserRotationApplication: secretsmanager.SecretRotationApplication.MYSQL_ROTATION_MULTI_USER,
				supportedLogTypes: []
			}
		});

		const secret = new Secret(myScope, 'Secret');

		cluster.addProxy('testProxy', {
			borrowTimeout: cdk.Duration.seconds(30),
			maxConnectionsPercent: 50,
			secrets: [secret],
			vpc
		});`

How does the bindToCluster expect from me to be set? I don't want to create a new cluster. I want to add a proxy to a existing cluster.

`Type '{ singleUserRotationApplication: SecretRotationApplication; multiUserRotationApplication: SecretRotationApplication; supportedLogTypes: never[]; }' is missing the following properties from type 'IClusterEngine': bindToCluster, engineType`

**Comment by aws-apradana** [comment]
Any solution for this? Im impacted with the same issue as well
