### ISSUE TITLE
[cdk pipelines] CDK - failed bootstrapping: Error: --cloudformation-execution-policies can only be passed for the new bootstrap experience.

### ISSUE THREAD

**Issue by srethira** [aws/aws-cdk#9196]
### The Question

Following this documentation https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/

Running bootstrap command result in error:

```
npx cdk bootstrap \
  --profile account1-profile \
  --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
  aws://ACCOUNT1/us-east-2
```

Please note that I'm trying to use CDK Pipelines for existing application.

### Environment

  - **CDK CLI Version:** 1.51.0
  - **Module Version:** 1.51.0
  - **Node.js Version:** v14.5.0
  - **OS:** OSX Mojave
  - **Language (Version):** Python (3.7.3) 

### Other information
 ⏳  Bootstrapping environment aws://XXXXXX/us-east-2...
 ❌  Environment aws://XXXXXX/us-east-2 failed bootstrapping: Error: --cloudformation-execution-policies can only be passed for the new bootstrap experience.
    at bootstrapEnvironment (/usr/local/lib/node_modules/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts:24:11)
    at /usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:359:98
    at Array.map (<anonymous>)
    at CdkToolkit.bootstrap (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:356:36)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:241:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:185:9)
--cloudformation-execution-policies can only be passed for the new bootstrap experience.

**Comment by ericzbeard** [comment]
@srethira Do you have this in cdk.json?

```
"@aws-cdk/core:newStyleStackSynthesis": true
```

**Comment by srethira** [comment]
My bad! I missed that setup. It is working now!
