### ISSUE TITLE
Add metadata for AWS constructs are defined with a physical name

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#92]
When an AWS construct is defined with an explicit physical name, we'd like to annotate the construct with metadata that contains that physical name, so that tools and aspects will be able to reason about it. We have a few examples throughout the library which add the `aws:cdk:hasPhysicalName` metadata entry for physical names, but we should normalize this though a common library.

**Comment by jungseoklee** [comment]
I am wondering how to normalize this.

I would like to solve a problem where we miss adding physical names to metadata. For example, DynamoDB and Kinesis L2 constructs add physical names to metadata, but SQS does not.

It is specific to service whether physical name is supported or not, so it seems tricky to handle it in a common library level.

**Comment by eladb** [comment]
We will reopen if this is relevant in the future.
