### ISSUE TITLE
[ec2] get the latest AmazonLinux 2 AMI for ARM64 CPU type 

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#9204]
To get the latest AMI ID for ARM64.

### Use Case

AWS Graviton(a1) and Graviton2 instances such as m6g, c6g and r6g will need arm-64 AMI.

### Proposed Solution

Add a `cpuType` for `AmazonLinuxImageProps`

```ts
  /**
   * CPU Type
   * 
   * @default X86_64
   */
  readonly cpuType?: AmazonLinuxCpuType;
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NinoSkopac** [comment]
I'm also in need of starting an arm64 ec2 machine for ECS via the CDK.

**Comment by NinoSkopac** [comment]
This worked:

```typescript
    const autoScalingGroup = new autoscaling.AutoScalingGroup(this, 'ASG', {
      vpc,
      instanceType: new ec2.InstanceType("t4g.micro"),
      machineImage: ec2.MachineImage.fromSsmParameter(
          '/aws/service/ecs/optimized-ami/amazon-linux-2/arm64/recommended/image_id'
      ),
      desiredCapacity: 1,
      keyName: 'linux',
      securityGroup: securityGroup,
    });
```
