### ISSUE TITLE
[lambda] Use the official lambda build docker images

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#9205]
The Lambda team has released official docker images for Lambda builds:

https://github.com/awslabs/aws-sam-cli/tree/v1.0.0/build-image-src

### Use Case

Maintain compatibility through the official images.

### Proposed Solution

The default bundling image for lambda is currently [lambci/docker-lambda](https://github.com/lambci/docker-lambda) and I think it should be moved to the new official images.

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@jogold fyi

**Comment by jogold** [comment]
Great!

The naming is `amazon/aws-sam-cli-build-image-<runtime>` (https://github.com/awslabs/aws-sam-cli/pull/2066).
