### ISSUE TITLE
VPC reference Missing in imported VPC from another stack during deploy

### ISSUE THREAD

**Issue by IPyandy** [aws/aws-cdk#921]
Hi,

I'm encountering an issue when deploying the second stack `EksStack` from the below output. Maybe I'm missing something from a logical perspective or it's an order of operations thing.

```shell
via ⬢ v8.12.0 is 📦  v0.0.1 [I] cdk ls -l
-
    name: VpcStack
    environment:
        name: [account-id]/us-east-1
        account: 'acount-id'
        region: us-east-1
-
    name: EksStack
    environment:
        name: [account-id]/us-east-1
        account: 'account-id'
        region: us-east-1

•100% ➜ in AwsCdk/typescript/aws-infra took 4s on  master [!]
via ⬢ v8.11.0 is 📦  v0.0.1 [I] cdk --version
0.12.0 (build 2dc324e)
```

I've tried with node 8.11.0 and 8.12.0, just as an FYI.

When `cdk synth --output yaml` is run, the cloudformation templates are computed and outputted. What seems to be "correctly" (just testing to make sure a deploy can be run).

Once the `cdk deploy` happens, the first stack executes with no issues, but the second crashes before even attempting to send to cloudformation online.

```shell
•100% ➜ in AwsCdk/typescript/aws-infra on  eks [⇡!?]
via ⬢ v8.12.0 is 📦  v0.0.1 [I] cdk deploy 2>&1 | tee deployLogs/deploy.txt
....SOME OUTPUT REMOVED AND ACCOUNT ID CHANGED...
 ✅  Deployment of stack VpcStack completed successfully, it has ARN arn:aws:cloudformation:us-east-1:99999999999:stack/VpcStack/cc8347d0-ce3e-11e8-84a9-50fae9882035
VpcStack.VPCPrivateSubnetIDsA55EE406 = subnet-0438e202159d0c843,subnet-02af57a298a0c782a,subnet-081fb9cc24bab4fad
VpcStack.VPCIsolatedSubnetIDs0BAB2DBD = subnet-086bfdd38922f7899,subnet-09b10c53f8faad7e4,subnet-03e9d1f52682b0f95,subnet-025b17c341549ac99,subnet-0475da4bd670ae4e2,subnet-069e4e5d576c54b33
VpcStack.VPCPublicSubnetIDs428979F9 = subnet-038fc7c11c0f1c2c6,subnet-079c8913ee2ef0d27,subnet-0aa802b553d310caf
VpcStack.VPCVpcId2F75874A = vpc-026661425ff3f4209
EksStack
 ⏳  Starting deployment of stack EksStack...
 ❌  Deployment of stack EksStack failed: ValidationError: Template format error: Unresolved resource dependencies [VPCB9E5F0B4] in the Resources block of the template
Template format error: Unresolved resource dependencies [VPCB9E5F0B4] in the Resources block of the template
```

## Code for Stacks

```typescript
import * as cdk from "@aws-cdk/cdk";
import * as eks from "./lib/eks";
import * as infra from "./lib/infra";

const app = new cdk.App();

const net = new infra.Network(
  app,
  "VpcStack",
  {
    cidr: "10.244.0.0/16",
    maxAZs: 3,
    natGateways: 1,

    // subnets are created 1 per maxAzs
    subnetConfiguration: [
      {
        name: "pub",
        cidrMask: 24,
        subnetType: infra.isPublic
      },
      {
        name: "priv",
        cidrMask: 24,
        subnetType: infra.isPrivate
      },
      {
        name: "iso",
        cidrMask: 24,
        subnetType: infra.isIsolated
      },
      {
        name: "rds",
        cidrMask: 26,
        subnetType: infra.isIsolated
      }
    ],
    tags: {
      env: "dev"
    }
  },
  {
    enableIPv6: false
  }
);

const cluster = new eks.EksCluster(app, "EksStack", { net });

app.run();
```

I'm attaching the `lib/infra` and `lib/eks` files as well so I don't make this too long. But will happily paste the code here if needed. I only separated them into files for readability, the code is crude I know, but just starting out with this and will refactor once the I figure out the issue.

I'm also attaching the YAML files and the full log output for reference.
[attach.zip](https://github.com/awslabs/aws-cdk/files/2473976/attach.zip)

may be easier to see them in the GitHub repo... [aws-cdk-infr](https://github.com/IPyandy/aws-cdk-infra)

P.S - I've attempted to run this in the same stack flat file, had a different issue where the cluster would attempt to created before anything else.. definitely order of creation thing. Tried two stacks but moving the code to more of patter like so...

const app = new cdk.App();
const VpcStak = new cdk.Stack(app, 'VpcStack');
// CODE FOR VPC HERE ALL INLINE, NO NETWORK CLASS CREATED

const EksStack = new cdk.Stack(app, 'EksStack');
// CODE FOR EKS SPECIFIC THINGS HERE

Had the same exact issue as first describe with reference error.

**Comment by IPyandy** [comment]
Ok, so after stepping aside for a bit, then testing again.

I wanted to see if this was specific to a cloudformation resource or anything else. So I added an autoscaling stack and imported the VPC. I kept getting the same error, which led me to believe that I was doing something wrong.

After a bit, I was able to get the autoscaling stack to work.

```typescript
// Test import with auto scaling group
const asgStack = new Stack(app, `AsgStack`);
const vpc = ec2.VpcNetworkRef.import(asgStack, `VPC`, net.vpcProps);
const group = new asg.AutoScalingGroup(asgStack, `AsgGroup`, {
  vpc: vpc,
  instanceType: new ec2.InstanceType(`t3.micro`),
  machineImage: new ec2.AmazonLinuxImage()
});
group.connections.allowFromAnyIPv4(new ec2.TcpPort(80));
```

The way I got it to work however is passing `VpcNetworkRefProps` to the import statement and not `VpcNetworkRef`. This is a bit misleading as the `vpc` property expects a `VpcNetworkRef`.

I updated the code for the EksStack and now that deploys correctly.

`index.ts`

```typescript
const cluster = new EksCluster(app, "EksStack", { vpc: net.vpcProps });
```

`lib/eks.ts`

```typescript
if (vpc.publicSubnets) {
  // const subnetIDs = vpc.export().publicSubnetIds;
  const subnetIDs: string[] = [];

  for (const subnet of vpc.publicSubnets) {
    subnetIDs.push(subnet.subnetId);
  }

  if (subnetIDs) {
    const cluster = new eks.cloudformation.ClusterResource(this, `EKS`, {
      roleArn: role.roleArn,
      resourcesVpcConfig: {
        securityGroupIds: [clusterSG.securityGroupId],
        subnetIds: subnetIDs
      }
    });
  }
}
```

One thing to note though, and maybe it's because I'm misusing it. The commented code above in the if statement `const subnetIDs = vpc.export().publicSubnetIds;` does not work as "expected?". 

I had to do the `for of` loop in order to gather the correct subnetIds, otherwise, I get this error at deployment time.

```shell
[ 0/11] Fri Oct 12 2018 16:54:55 GMT-0400 (EDT)  ROLLBACK_IN_PROGRESS  [AWS::CloudFormation::Stack] EksStack No export named EksStack:VPCPublicSubnetIDs428979F9 found. Rollback requested by user.
[ 1/11] Fri Oct 12 2018 16:55:11 GMT-0400 (EDT)  ROLLBACK_COMPLETE   [AWS::CloudFormation::Stack] EksStack
 ❌  Deployment of stack EksStack failed: Error: The stack named EksStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
The stack named EksStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

Though if I'm misusing that and it's intended to be for a different use case, that's fine.

**Comment by SomayaB** [comment]
@IPyandy I'm sorry this has gone so long without response. Are you still experiencing any issues?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen.
