### ISSUE TITLE
[core] console.error on asset-staging.ts

### ISSUE THREAD

**Issue by dscpinheiro** [aws/aws-cdk#9210]
### The Question
I'm building a Lambda function, and using Docker (https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#bundling-asset-code) to bundle the code. It works, but I noticed that when I run my tests I get some error messages in the console (even though the tests succeed):

```
  console.error
    Bundling asset TestStack/TestFunction/Function/Code/Stage...

      51 |         const nodeRuntime = lambda.Runtime.NODEJS_12_X;
    > 52 |         this.Function = new lambda.Function(this, 'Function', {
         |                         ^

      at AssetStaging.bundle (node_modules/@aws-cdk/core/lib/asset-staging.ts:175:15)
      at new AssetStaging (node_modules/@aws-cdk/core/lib/asset-staging.ts:92:29)
      at new Asset (node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:117:21)
      at AssetCode.bind (node_modules/@aws-cdk/aws-lambda/lib/code.ts:180:20)
      at new Function (node_modules/@aws-cdk/aws-lambda/lib/function.ts:535:29)
      at new LambdaConsumer (lib/lambda-construct.ts:52:25)
      at test/lambda.test.ts:89:18

---------------------------|---------|----------|---------|---------|-------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------------|---------|----------|---------|---------|-------------------
All files                  |     100 |      100 |     100 |     100 |                   
 lambda-construct.ts.ts    |     100 |      100 |     100 |     100 |                   
---------------------------|---------|----------|---------|---------|-------------------
```

It looks like that console.error is coming from this file: https://github.com/aws/aws-cdk/blob/2cc46d58c09981c0258f5fc9d2d540165c722aea/packages/%40aws-cdk/core/lib/asset-staging.ts#L175
Is that expected?

### Environment

  - **CDK CLI Version:** 1.54.0
  - **Module Version:** 1.54.0
  - **Node.js Version:** v12.18.1
  - **OS:** macOS Mojave 10.14.6
  - **Language (Version):** TypeScript (3.7.2)

### Other information
This is the code for the Lambda function itself:
```javascript
new lambda.Function(this, 'Function', {
    runtime: lambda.Runtime.NODEJS_12_X,
    handler: 'index.handler',
    code: lambda.Code.fromAsset('lambda', {
        bundling: {
            image: lambda.Runtime.NODEJS_12_X.bundlingDockerImage,
            user: 'root',
            command: [
                'bash', '-c',
                'cp -r . /asset-output && cd /asset-output && npm ci --only=prod'
            ]
        }
    })
});
```

**Comment by eladb** [comment]
Copy @jogold. Should we emit through `process.stderr.write` instead? so test runners which capture `console.error()` like jest will not treat this as the end of the world?

**Comment by jogold** [comment]
> Copy @jogold. Should we emit through `process.stderr.write` instead? so test runners which capture `console.error()` like jest will not treat this as the end of the world?

Yes
