### ISSUE TITLE
[cloudfront] Update Suported Security Protocol Enum

### ISSUE THREAD

**Issue by Xarno** [aws/aws-cdk#9212]
Recently the List of Supported Security Protocols got extended. Please follow https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers and update this enum:

```js
export declare enum SecurityPolicyProtocol {
    SSL_V3 = "SSLv3",
    TLS_V1 = "TLSv1",
    TLS_V1_2016 = "TLSv1_2016",
    TLS_V1_1_2016 = "TLSv1.1_2016",
    TLS_V1_2_2018 = "TLSv1.2_2018"
}
```

### Use Case

Cloudfront setup.

### Proposed Solution

```js
export declare enum SecurityPolicyProtocol {
    SSL_V3 = "SSLv3",
    TLS_V1 = "TLSv1",
    TLS_V1_2016 = "TLSv1_2016",
    TLS_V1_1_2016 = "TLSv1.1_2016",
    TLS_V1_2_2018 = "TLSv1.2_2018",
    TLS_V1_2_2019 = "TLSv1.2_2019"
}
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
This also needs to be updated: 
https://github.com/aws/aws-cdk/blob/345389f9948846906ccc561070f3ec7973628277/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L805-L811

Btw it blocks users from using a policy not yet included in the CDK code.
