### ISSUE TITLE
[CDK Pipelines] Asset bundling (running Docker during 'synth') doesn't work

### ISSUE THREAD

**Issue by srethira** [aws/aws-cdk#9217]
I’m trying out new CDK Pipelines in developer preview. I have a question on how to bundle assets that are using docker container during the build process. Currently during “synth_action”, getting following error:

### Reproduction Steps

```
pipelines.CdkPipeline(self,
                       "Pipeline",
                       pipeline_name="Test",
                       cloud_assembly_artifact=cloud_assembly_artifact,
                       source_action=codepipeline_actions.CodeCommitSourceAction(
                               action_name="CodeCommit_Source",
                               repository=code,
                               branch="cdkpipeline",
                              output=source_artifact),
                       synth_action=pipelines.SimpleSynthAction.standard_npm_synth()
                               source_artifact=source_artifact,
                               cloud_assembly_artifact=cloud_assembly_artifact,
                               build_command="npx cdk synth")

```

### Error Log

```
stderr: docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.   
See 'docker run --help'. 
at AssetStaging.bundle (/tmp/jsii-kernel-O8ZKbG/node_modules/@aws-cdk/core/lib/asset-staging.js:121:19) 
at new AssetStaging (/tmp/jsii-kernel-O8ZKbG/node_modules/@aws-cdk/core/lib/asset-staging.js:38:35)
 at new Asset (/tmp/jsii-kernel-O8ZKbG/node_modules/@aws-cdk/aws-s3-assets/lib/asset.js:21:25)

```

### Environment

  - **CDK CLI Version:** 1.51.0
  - **Module Version:** 1.51.0
  - **Node.js Version:** v14.5.0
  - **OS:** OSX Mojave
  - **Language (Version):** Python (3.7.3) 

--- 

This is :bug: Bug Report

**Comment by srethira** [comment]
Is there any workaround to run privileged CodeBuild container using these command ?
 
`nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2& - timeout 15 sh -c "until docker info; do echo .; sleep 1; done" ``
 
Since CodeBuild is created dynamically during synth action.

**Comment by justin8** [comment]
You should be able to add this in the synth definition to get a privileged container:

```
environment: {privileged: true}
```

**Comment by srethira** [comment]
@justin8 argh! I overlooked this property. I leave this ticket open since @eladb mentoined that this feature could be automated.

**Comment by eladb** [comment]
Since bundling is a framework feature, We should automatically identify if docker is required for asset bundling and configure your synth environment accordingly.

**Comment by eikeon** [comment]
@justin8, @srethira, Adding `environment: {privileged: true}` to `SimpleSynthAction.standardNpmSynth`didn't seem to help. Was that the wrong place to add it? /me continues to dig

**Comment by eikeon** [comment]
Ah, I have to add it and deploy before depending on it ;) -- working now.

**Comment by rix0rrr** [comment]
> Since bundling is a framework feature, We should automatically identify if docker is required for asset bundling and configure your synth environment accordingly.

I don't quite get why we would need docker during the `synth` step. iirc we should only need it during asset packaging.

Are you using the `aws-lambda-nodejs` package by any chance?

**Comment by justin8** [comment]
I'm seeing it during the synth when using the `aws-lambda-python` package. It appears the nodejs one works in a very similar fashion.

**Comment by eladb** [comment]
Asset bundling uses docker during synthesis.

**Comment by blastedcode** [comment]
I too was having the same issue when deploying a Ruby Lambda function that required extra Gems and the CDK code was written in Python. It uses what @justin8 its just an example if people need it.

`synth_action=pipelines.SimpleSynthAction(
    source_artifact=source_artifact,
    cloud_assembly_artifact=cloud_assembly_artifact,
    install_command='npm install -g aws-cdk && pip install -r requirements.txt',
    synth_command='cdk synth',
    environment={
        'privileged': True
     }
)` 

The Lambda deployment code is as follows:

`aws_lambda.Function(self, 'EmailHandler',
    code=_lambda.Code.from_asset(path.join(os.getcwd(), 'lambda_resources'),
    bundling={
         'image': _lambda.Runtime.RUBY_2_7.bundling_docker_image,
         'command': ['bash', '-c', 'bundle install  && cp -au . /asset-output']
         }),
    runtime=_lambda.Runtime.RUBY_2_7,
    handler='app.lambda_handler'
)`

You do have to do 1 deployment synth run with only the privileged code included first otherwise it always fails

**Comment by Zirkonium88** [comment]
I need this feature as well ... boto3 is not always update to date within Lambda so we need to deal with our own deployment packages

**Comment by blastedcode** [comment]
> I need this feature as well ... boto3 is not always update to date within Lambda so we need to deal with our own deployment packages

You should be able to use this already using the following bit of code in your synth process

`environment={
        'privileged': True
     }
 `

**Comment by aax** [comment]
I get this error during the self-mutate stage, because my CdkPipeline stack depends on another stack which needs docker. Is there a way to either use privileged mode for the self-mutate build or use the --exclusively option with the cdk deploy command in the self-mutate stage?

**Comment by blastedcode** [comment]
> I get this error during the self-mutate stage, because my CdkPipeline stack depends on another stack which needs docker. Is there a way to either use privileged mode for the self-mutate build or use the --exclusively option with the cdk deploy command in the self-mutate stage?

Do you have any more information or a snippet of code that can be viewed. The code should work as all it is doing is bring in docker containers.

**Comment by aax** [comment]
> > I get this error during the self-mutate stage, because my CdkPipeline stack depends on another stack which needs docker. Is there a way to either use privileged mode for the self-mutate build or use the --exclusively option with the cdk deploy command in the self-mutate stage?
> 
> Do you have any more information or a snippet of code that can be viewed. The code should work as all it is doing is bring in docker containers.

Here's a project that reproduces this problem: https://github.com/aax/codebuilt-issue
Find the complete log of the self-mutate codebuild action in readme.md. Also the steps to reproduce this error.

Many thanks for having a look!

**Comment by blastedcode** [comment]
> > > I get this error during the self-mutate stage, because my CdkPipeline stack depends on another stack which needs docker. Is there a way to either use privileged mode for the self-mutate build or use the --exclusively option with the cdk deploy command in the self-mutate stage?
> > 
> > 
> > Do you have any more information or a snippet of code that can be viewed. The code should work as all it is doing is bring in docker containers.
> 
> Here's a project that reproduces this problem: https://github.com/aax/codebuilt-issue
> Find the complete log of the self-mutate codebuild action in readme.md. Also the steps to reproduce this error.
> 
> Many thanks for having a look!

Thanks for the info, I will look tonight once I have finished work.

**Comment by otaviomacedo** [comment]
We have a circular dependency problem here: in order to tell whether the app bundles assets (or uses constructs like `NodeJsFunction`), the CLI needs to synthesize it and inspect the generated cloud assembly. But to guarantee that the synthesis works in CodeBuild, it first needs to know whether the app needs to do bundling (to configure the CodeBuild project to run in privileged mode).

So, as suggested by @justin8, the solution is to set the `privileged` environment variable yourself. README updated with this solution.

**Comment by dillonharlessCORE** [comment]
> I get this error during the self-mutate stage, because my CdkPipeline stack depends on another stack which needs docker. Is there a way to either use privileged mode for the self-mutate build or use the --exclusively option with the cdk deploy command in the self-mutate stage?

I resolved this by temporarily removing my lambda that required bundling, allowed the pipeline to update itself, and then added it back in afterwards. I believe this issue is introduced when you create a pipeline without a privileged build server, and then you add something like a Lambda function that requires docker to bundle dependencies. This causes you to end up with a pipeline that gets halted and never updates itself properly.

Hope that helps!

**Comment by justin8** [comment]
@honeybadger91  I don't believe that applies to CDK pipelines which this bug was for; they're different from raw CodePipelines constructs and that is the problem.

**Comment by vermontkidsdata** [comment]
I am still having this problem, trying to compile TypeScript. My project is here:

https://github.com/vermontkidsdata-org/vermontkidsdata_census

As you can see, I'm using ShellStep for synth, and I have env: {privileged: 'true'} set. When I look at the environment variables in the CodeBuild project execution, I can see it is set.

![image](https://user-images.githubusercontent.com/98333272/152700671-67af5940-b3cc-4345-b716-9df492e05bca.png)

However, the build still fails with:

```
46 | [Container] 2022/02/06 20:42:25 Running command npx cdk synth
47 | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
48 | docker exited with status 1
49 | Subprocess exited with error 1
```

Do I need to run a docker start command or something? CDK version is 2.10.0 (build e5b301f).

**Comment by ram4031** [comment]
> We worked it out. We ended up doing an npm install of `esbuild` locally in package.json. Apparently if you don't have it locally, it tries to use docker.

Installing `esbuild` fixed the issue.

**Comment by RLashofRegas** [comment]
> For those using Python and the CodePipeline object, you can pass `docker_enabled_for_synth=True` to accomplish this. For example:
> 
> ```
>     def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
>         super().__init__(scope, construct_id, **kwargs)
>         pipeline = pipelines.CodePipeline(self, "Pipeline",
>                                           pipeline_name="MySupercoolPipeline",
>                                           docker_enabled_for_synth=True,
>                  ............. 
> ```

while this wasn't specifically relevant to this issue, this is the issue I was taken to when googling for my problem related to the synth action of normal `CodePipeline` and this comment helped me solve it. Thanks!

**Comment by evaldezg** [comment]
Thank you. I had same issue w/NodeJsFunction but adding esbuild to my dev dependencies fixed the issue.

**Comment by satyamkondle** [comment]
For CodeBuildStep, it goes under buildEnvironment: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.BuildEnvironment.html#privileged

**Comment by ianbrumby** [comment]
Just adding this here in case it helps anyone else: I was having the same issue with cross-account deployment of NodeJsFunction Lambdas using CDK Pipelines. It turns out my issue was that I had added `cdk ls` to the end of my build commands for debugging, which was causing problems with file paths for the assets.

**Comment by djhelfrich** [comment]
I was having this error I deleted all my node_modules and re did npm i, fixed the issue

**Comment by cdohotaru** [comment]
If case you stumble upon this: with "aws-cdk-lib": "2.94.0", it looks to work without problems if the docker lines are added

`const pipeline = new CodePipeline(this, 'Pipeline', {
            pipelineName: 'MyPipeline',
            **dockerEnabledForSynth: true,
            dockerEnabledForSelfMutation: true,**
            synth: new ShellStep('Synth', {
                input: CodePipelineSource.gitHub('MyUsername/MyRepoName', 'main', {
                    authentication: secret,
                }),
                commands: [
                    'npm ci', 
                    'sh ./lib/scripts/installDeps.sh', 
                    'npm run synth',
                ],
            }),
        });`

Hope this helps!
