### ISSUE TITLE
[CDK Pipelines] Changes are deployed and published using global STS endpoints

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9223]
CDK Pipelines currently uses global STS endpoints to publish artifacts and also to deploy the self-mutating pipeline changes instead of the correct regional endpoints

### Reproduction Steps

Create a CDK pipeline, using the demo example in the docs is fine. Check your CloudTrail logs and you can see v1 API calls to the us-east-1 endpoint for STS (auth tokens that start with an `F`) are going to be visible.

### Environment

  - **CLI Version:** 1.51.0
  - **Framework Version:** 1.51.0
  - **Node.js Version:** v12.13.1
  - **OS:** Mac
  - **Language (Version):** Typescript 3.8.3

### Other

--- 

This is :bug: Bug Report

**Comment by ericzbeard** [comment]
I don't think this is a bug, since switching to regional endpoints is more of an optimization than a necessity.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html

**Comment by justin8** [comment]
It means we have created a single point of failure that is outside of the region a pipeline is configured to use as the “global” endpoint is dependent on us-east-1. 

If CDK is supposed to have best practices as a default then this is a bug.

**Comment by rix0rrr** [comment]
I agree. Thanks for the report.
