### ISSUE TITLE
[aws-ecs] Allow setting encryption on the hooktargets SNS

### ISSUE THREAD

**Issue by yashda** [aws/aws-cdk#9230]
The FunctionHook class creates a new SNS Topic internally but does not allow users to pass a CMK to encrypt it.

### Proposed Solution

The class should accept an optional `props` parameter which can be used to pass CMK and similar other properties to customize the SNS topic being created.

This change will can be implemented by all the implementations of `ILifecycleHookTarget` class.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
Since  `TopicHook` accepts a `Topic` you can  create a  `Topic`  and pass it a  `masterKey`:


```ts
const topic = new sns.Topic(stack, 'Topic', {
    masterKey: new kms.Key(this, 'Key');
});

asg.addLifecycleHook('Hook', {
  lifecycleTransition: autoscaling.LifecycleTransition.INSTANCE_LAUNCHING,
  notificationTarget: new hooks.TopicHook(topic),
});
```

**Comment by NetaNir** [comment]
To make this more configurable we can change `InstanceDrainHook` to accept a `LifecycleHook` and have `FunctionHook` accepts a kms key. 
Happy to accept PRs, let me know if you are want to take this one!

**Comment by ddneilson** [comment]
I'm taking this over from Yash.

The ticket was created in response to a finding during an automated audit of resources that were deployed with the CDK. Deep diving on the contents of these SNS topics, I'm of the opinion that there is nothing sensitive in the topic that warrants the work required to encrypt the SNS topic.

ASG lifecycle events contain:
* LifecycleHookName
* AccountId
* RequestId
* LifecycleTransition (ex: autoscaling:EC2_INSTANCE_LAUNCHING)
* AutoScalingGroupName
* Originating service
* A timestamp
* EC2InstanceId
* LifecycleActionToken

Nothing in that list is sensitive.

Sorry for the false alarm. I recommend that we stand-down, and close this ticket.

**Comment by ddneilson** [comment]
Discussed off-line with @NetaNir -- we're keeping this open. It's possible that we may still need to fix this.
