### ISSUE TITLE
[aws-events-targets] Add flag for Auto-assign public IP to EcsTask

### ISSUE THREAD

**Issue by ryanvade** [aws/aws-cdk#9233]
With ECS tasks I ran into an issue where ECS is unable to pull images from ECR even though the task is set to run in a PUBLIC subnet. In the console it appears that it is possible to set the Auto-assign public IP for an Event target. 

### Use Case

I have a cloudwatch event that is set to run every week that fires an ECS task. The ECS task needs to be able to pull the ECR image and communicate with external resources and therefore needs a public IP address. 

My current event and target: 

```typescript
    const encryptionEventRule = new Rule(this, `${this.projectTag}-encryption-event-rule`, {
      schedule: Schedule.expression("rate(7 days)"),
    });

    encryptionEventRule.addTarget(
      new EcsTask({
        cluster,
        taskDefinition: encryptionTaskDefinition,
        taskCount: 1,
        subnetSelection: VPC.selectSubnets({
          subnetType: SubnetType.PUBLIC,
        }),
      })
    );
```

### Proposed Solution

Just like ECS services I believe a flag for the Auto-assign public IP can be added

In an ECS Service
```typescript
    const service = new FargateService(this, SERVICE_NAME, {
      serviceName: SERVICE_NAME,
      taskDefinition: taskDefinition,
      cluster: cluster,
      desiredCount: SERVICE_DESIRED_CONTAINER_COUNT,
      assignPublicIp: SERVICE_ASSIGN_PUBLIC_IP,
      securityGroup: serviceSecurityGroup,
      vpcSubnets: VPC.selectSubnets({
        subnetType: SubnetType.PUBLIC,
      }),
    });
```

My proposal for an ECS Task event target:
```typescript
    encryptionEventRule.addTarget(
      new EcsTask({
        cluster,
        taskDefinition: encryptionTaskDefinition,
        taskCount: 1,
        assignPublicIp: SERVICE_ASSIGN_PUBLIC_IP,
        subnetSelection: VPC.selectSubnets({
          subnetType: SubnetType.PUBLIC,
        }),
      })
    );
```

### Other

The CloudWatch console allows for setting the Auto-assign public IP value when creating an Event Rule that triggers ECS tasks as described [here](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_AwsVpcConfiguration.html).

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
What I want to know is why ECS doesn't honor the subnet default of "assign public IP", which should be `true` for public subnets.

But yes, sounds good.

**Comment by shaftoe** [comment]
> What I want to know is why ECS doesn't honor the subnet default of "assign public IP", which should be `true` for public subnets.
> 
> But yes, sounds good.

Yeah, good question, probably it was chosen as default for security reasons? It's definitely counter intuitive and took me quite some time to troubleshoot.

Also, fun fact: when you run a new ECS Task from the console and select Fargate as launch type, `Auto-assign public IP` is set to `ENABLED` by default.

**Comment by Stvad** [comment]
are there any workarounds for this? or it it not possible to trigger the EcsTask with public ip assigned to it atm?

**Comment by renrut** [comment]
@Stvad it's possible to trigger the task with right now if you're okay with your Task not having a public IP. You can do it by having the task in a private subnet and using [VPC endpoints](https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html) which may be a better pattern anyways rather than relying on your VPC security groups with a public ip.

Something like this should do it.
```
// Add S3/ECR interface endpoint to pull docker images
vpc.addGatewayEndpoint("S3Endpoint", {
  service: ec2.GatewayVpcEndpointAwsService.S3
});
// Add ECR interface endpoint to pull docker images
vpc.addInterfaceEndpoint("ECREndpoint", {
  service: ec2.InterfaceVpcEndpointAwsService.ECR
});
vpc.addInterfaceEndpoint("ECRDockerEndpoint", {
  service: ec2.InterfaceVpcEndpointAwsService.ECR_DOCKER
});
// Add ECS interface endpoints - instances allocated within an isolated subnet will need to reach out to ECS in
// order to register themselves with clusters.
vpc.addInterfaceEndpoint("ECSInterfaceEndpoint", {
  service: ec2.InterfaceVpcEndpointAwsService.ECS
});
vpc.addInterfaceEndpoint("ECSInterfaceTelemetryEndpoint", {
  service: ec2.InterfaceVpcEndpointAwsService.ECS_TELEMETRY
});
vpc.addInterfaceEndpoint("ECSInterfaceAgentEndpoint", {
  service: ec2.InterfaceVpcEndpointAwsService.ECS_AGENT
});

//Define the task target inside the vpc private subnets.
const ecsTaskTarget = new targets.EcsTask({
  cluster: cluster,
  taskDefinition: taskDefinition,
  role: targetInvocationRole,
  platformVersion: ecs.FargatePlatformVersion.LATEST,
  subnetSelection:vpc.selectSubnets({
    subnetType: ec2.SubnetType.PRIVATE,
  }),
  securityGroups: [securityGroup]
});
```

**Comment by Stvad** [comment]
@renrut Thanks, that's a great suggestion! For the moment I need my task to access things on the public internet though (and I don't want to pay for the NAT 😛 ).   
I may be able to reshuffle things to stay within Amazon network at some point though 🤔

**Comment by vmourac** [comment]
Any updates on this?
The company I work for is currently on early stages of adopting CDK, but this issue is currently having a negative impact on our analysis

**Comment by ZeldaZach** [comment]
This just came up for us when trying to deploy a crawler via ECSTask (and ScheduledFargateTask). Manually setting the CloudWatch/EventBridge Rule's "Auto-assign Public IP" to "ENABLED" worked, but this isn't a long term viable solution.

**Comment by trompx** [comment]
Hey everyone,

That is sad to see it has not yet been implemented.
I don't know if this is by lack of time or they really try to push the NAT gateway/Private Link instead...

Anyway, I found a way to raw edit the CFN via CDK after a resource has already been created. The use of `cdk.CfnResource` as advertised on the escape hatches doc page : https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html are for creating new resources, not for editing a resource that has already been created by either L1 or L2 construct.

So here is my solution:
```js
const ecsTaskTarget = new EcsTask({
  cluster: cluster,
  taskDefinition: taskDefinition,
  ...
});
const scheduledTask = new events.Rule(this, "MySchedule", {
  schedule: events.Schedule.expression("cron(0/10 * * * ? *)"),
  description: "Starts the task",
  targets: [
    ecsTaskTarget
  ],
});
(scheduledTask.node.defaultChild as cdk.CfnResource).addPropertyOverride(
  "Targets.0.EcsParameters.NetworkConfiguration.AwsVpcConfiguration.AssignPublicIp",
  "ENABLED"
);
```

**Comment by kalanjdjordje** [comment]
Also if for ScheduledFargateTask you need to add something like this to work:

```typescript
const scheduledFargateTask = new ScheduledFargateTask(this, 'ScheduledFargateTask', {
      cluster,
      vpc,
      ruleName: 'ScheduledFargateTask',
      scheduledFargateTaskDefinitionOptions: {
        taskDefinition: taskDefinition,
      },
      schedule: Schedule.expression('rate(10 minutes)'),
      platformVersion: FargatePlatformVersion.LATEST,
      subnetSelection: vpc.selectSubnets({ subnetType: SubnetType.PUBLIC,  })
  
    });
    
    (scheduledFargateTask.eventRule.node.defaultChild as CfnResource).addPropertyOverride(
      "Targets.0.EcsParameters.NetworkConfiguration.AwsVpcConfiguration.AssignPublicIp",
      "ENABLED"
    );
```

**Comment by mhkafadar** [comment]
This issue continues to persist, and as a workaround, we are compelled to set assignPublicIp to true, which is not ideal.

**Comment by ymhiroki** [comment]
I'm implementing this feature! Please wait a minute.
