### ISSUE TITLE
[aws-cloudfront] Cloudfront.CustomOriginConfig.originHeaders

### ISSUE THREAD

**Issue by dwbelliston** [aws/aws-cdk#9235]
Trying to use origin Headers on 'customOriginSource' didnt work: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CustomOriginConfig.html

Looks like its deprecated? https://github.com/aws/aws-cdk/blob/f99c3271ed2b4c68f3cd2970a1b38571f5ddc911/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L202

Once i put them outside of custom origin it worked.

```json
        originConfigs: [
          {
            originHeaders: {
              Referer: `cloudfront-${config.environment}`,
            },
            customOriginSource: {
            }
         ]
```

---

This is a 📕 documentation issue

**Comment by iliapolo** [comment]
@dwbelliston Thanks for reporting this. `originHeaders` on the `Source` is indeed deprecated and moved to each individual `Origin`. They should still both work though. Are you saying that what actually worked in the deprecated property?

**Comment by dwbelliston** [comment]
gotcha - yes, my intent was just to add in documentation where it is deprecated. 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CustomOriginConfig.html#originheaders-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span
That didnt work for me, and in code it says deprecated, maybe there is a way to get that status on docs.

**Comment by iliapolo** [comment]
@dwbelliston Could you please share the exact configuration that didn't work? I suspect this might be a bug.

**Comment by dwbelliston** [comment]
This is deprecated and didnt work, from what i can tell:

```json
originConfigs: [
    {
    customOriginSource: {
        originHeaders: {
          Referer: refererHeader,
        },
        domainName: bucket.bucketWebsiteDomainName,
        originProtocolPolicy: cloudfront.OriginProtocolPolicy.HTTP_ONLY,
    },
    behaviors: [{ isDefaultBehavior: true }],
    }
]
```


This is working:

```json
originConfigs: [
    {
    originHeaders: {
        Referer: refererHeader,
    },
    customOriginSource: {
        domainName: bucket.bucketWebsiteDomainName,
        originProtocolPolicy: cloudfront.OriginProtocolPolicy.HTTP_ONLY,
    },
    behaviors: [{ isDefaultBehavior: true }],
    },
]
```

**Comment by iliapolo** [comment]
Thanks @dwbelliston - I'll look into it.

**Comment by njlynch** [comment]
I tried to replicate this bug and (so far) haven't been able to. What version of the CDK are you using? Can you share the relevant section (Origins) of the generated template(s)?

I wrote up two tests comparing both approaches, and got the same output in the two synthesized stacks:
```ts
  'issue9235-1'(test: Test) {
    const stack = new cdk.Stack();
    new CloudFrontWebDistribution(stack, 'AnAmazingWebsiteProbably', {
      originConfigs: [
        {
          customOriginSource: {
            originHeaders: {
              MyHeader: 'MyHeaderValue',
            },
            domainName: 'www.example.com',
            originProtocolPolicy: OriginProtocolPolicy.HTTP_ONLY,
          },
          behaviors: [{ isDefaultBehavior: true }],
        },
      ],
    });

    expect(stack).to(haveResourceLike('AWS::CloudFront::Distribution', {
      'DistributionConfig': {
        'Origins': [{
          'OriginCustomHeaders': [{
            HeaderName: 'MyHeader',
            HeaderValue: 'MyHeaderValue',
          }],
        }],
      },
    }));

    test.done();
  },

  'issue9235-2'(test: Test) {
    const stack = new cdk.Stack();
    new CloudFrontWebDistribution(stack, 'AnAmazingWebsiteProbably', {
      originConfigs: [
        {
          originHeaders: {
            MyHeader: 'MyHeaderValue',
          },
          customOriginSource: {
            domainName: 'www.example.com',
            originProtocolPolicy: OriginProtocolPolicy.HTTP_ONLY,
          },
          behaviors: [{ isDefaultBehavior: true }],
        },
      ],
    });

    expect(stack).to(haveResourceLike('AWS::CloudFront::Distribution', {
      'DistributionConfig': {
        'Origins': [{
          'OriginCustomHeaders': [{
            HeaderName: 'MyHeader',
            HeaderValue: 'MyHeaderValue',
          }],
        }],
      },
    }));

    test.done();
  },
```

**Comment by dwbelliston** [comment]
Sounds good. Must have been a user error on this. Thanks for the help.
