### ISSUE TITLE
[aws-ecr-assets] Ability to add docker build CLI command arguments for Docker image assets

### ISSUE THREAD

**Issue by levahim** [aws/aws-cdk#9236]
Ability to add `docker build` CLI command arguments for Docker image assets.

### Use Case

You want to be able to customize the Docker image build process. For example, you may want to use `--network host` argument for the `docker build` command.

### Proposed Solution

Options pass to the methods that create Docker image asset from the build directory should include an option with additional command line arguments to the `docker build` command.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a additional `docker build` command arguments Feature Request

**Comment by eladb** [comment]
Copy @jogold
