### ISSUE TITLE
[redshift] Create a new cluster in an existing cluster subnet group

### ISSUE THREAD

**Issue by dirkgomez** [aws/aws-cdk#9241]
My AWS account comes with a Redshift subnet group preinstalled, let's assume it is called accountsetup-dirk-redshift-subnet-group

When using the Cluster construct, I try to pass in the subnet group:

```
    new redshift.Cluster(this, 
      `Cluster${this.stackName}`,
      {
        vpc: vpc,
...
        vpcSubnets: {subnetName: 'accountsetup-dirk-redshift-subnet-group'},

```

Running cdk synth returns:

`There are no subnet groups with name 'accountsetup-dirk-redshift-subnet-group' in t
`

Looking at what the code here does, it incorrectly fetches the EC2 subnet groups, doesn't find my Redshift subnet group and errors out.

My current workaround is letting the construct create a new subnet group.

### Environment

  - **CLI Version      :** 1.53.0
  - **Framework Version:** 1.53.0
  - **Node.js Version:**  14.5.0
  - **OS               :** Mac Os X
  - **Language (Version):**  Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
The property `vpcSubnets` is referring to [subnets in a VPC](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html) and not redshift subnets. The [current logic](https://github.com/aws/aws-cdk/blob/b1b9d23f442b674df97c1aadb4f84cc0251bb826/packages/%40aws-cdk/aws-redshift/lib/cluster.ts#L401) is to create a new redshift cluster in the given VPC subnets.

We don't yet support specifying your own redshift cluster subnet group. However, this should be easy to add in the CDK.

You could work around this using [escape hatches and overrides](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw), however, a new redshift cluster subnet group will be created.
If you would not want this, you will need to use the lower level [`CfnCluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-redshift.CfnCluster.html).
