### ISSUE TITLE
[aws-stepfunctions-tasks] In DynamoAttributeValue mapping methods are missing

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-cdk#9246]
I need to produce the following dynamo put item mapping:

> "SS.$":"$.list"

I required something akin to the other mapping functions.

This is so that I can map input data store as a list of strings to a dynamo function.

There is an existing DynamoAttributeValue.fromStringSet but this is only for inserting static values.

We need to be able to map from input data:
so 

`DynamoAttributeValue.stringSetFromJsonPath` (like the other json path methods).

This particular method would look like this:

```
  public static stringSetFromJsonPath(value: string) {
    validateJsonPath(value);
    return new DynamoAttributeValue({ SS: value.toString() });
  }
```

Though the reality is the following are still required (and there my be more like binary for example).

- listFromJsonPath
- numberSetFromJsonPath

So you don't need stringFromJsonPath as you can just pass a string in as the mapping (and use fromString) but maybe we should have a stringFromJsonPath to make it more explicit.

What I would really like is a catch all method...

something like: fromJsonPath(<TYPE>, <JsonPath as a string>)

Instead of loads of different methods - this could maybe use an enum to specify the TYPE to ensure that invalid types are not passed in.

**Comment by michaelwiles** [comment]
So as it turns out the functionality Im looking for is actually availble...

```
DynamoAttributeValue.from_string_set(
     JsonPath.list_at('$.detail.emergencyContacts')
)
```

I guess the api is a little inconsistent as for non string types you need to use from_jsonpath but for all the string types it is not requried even though you are actually mapping a json path.

So this immediate use case of the string set is possible but I do suspect that things like mapping a number set is not available.

**Comment by shivlaks** [comment]
@michaelwiles is the missing functionality that we want to add a function like `stringSetFromJsonPath` that allows state input to be mapped to a string set?

**Comment by michaelwiles** [comment]
Yes.

Though as I said, it'd be worth doing a scan of what is still missing to make sure we cover all the bases.

I did suggest that we create a more generic method to handle all the scenarios...

What do you think? Do we continue with this approach and just add methods or can we add 1 method that can handle all the scenarios?

I can take a look if I get the chance - though for me, it's not so pressing as because python is dynamic I can use the methods for types they weren't designed for...

And while I'm at it, can also do these methods - which I think are also missing: listFromJsonPath and numberSetFromJsonPath

**Comment by shivlaks** [comment]
I think those 3 seem like a reasonable start. The generic method is something we considered but may not translate well across all languages. It's the reason we went with specific methods in this static enum like class to generate the specific attribute that the user wants to leverage.

for now, let's make the scope of this issue to add:

`stringSetFromJsonPath`
`listFromJsonPath`
`numberSetFromJsonPath`

and add any other `*fromJsonPath` methods that are missing

**Comment by michaelwiles** [comment]
Thanks for the clarification.


Cool

**Comment by dejonghe** [comment]
I ran into this issue today. 
The documents say that from_string accepts JsonPath, but it doesn't change the key to 'S.$' if json_path is used:

https://github.com/aws/aws-cdk/blob/a5e77e47d3bc7a326be56eef527db6f988b8ac9f/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/shared-types.ts#L120-L126

It seems like we could add a pre-check to these 
```
  public static fromString(value: string) {
    if (validateJsonPath(value)) {
      return new DynamoAttributeValue({ 'S.$': value });
    } else {
      return new DynamoAttributeValue({ S: value });
    }
  }
```
