### ISSUE TITLE
[cli] Allow dynamic stack name generation during cdk synth 

### ISSUE THREAD

**Issue by mohdarshad** [aws/aws-cdk#9261]
Is there anyway I can keep stack name dynamic and not hardcoded in the code? Is there any way I can pass stackName during cdk synth? I have defined a single stack in my code but want to run the same stack for multiple project, hence I want different stackname to be created in cloudformation for different project. Language = Java
I am unable to find any documentation supporting this.

**Comment by mohdarshad** [comment]
Apparently I can pass the stack name in context, and use the context value to set the stack name in StackProps. 
Kindly confirm.

**Comment by mohdarshad** [comment]
Apparently I can pass the stack name in context, and use the context value to set the stack name in StackProps.

**Comment by stevestorey** [comment]
This was the top result when I was searching for a solution to the same issue, and I did find a way to do it which I'll leave here - you can pass context parameters when you run the `cdk` script, so you can do something like `cdk deploy -c myParam=some-value` and pick up the context value as you're creating the stack - something like this (Typescript, but I would assume the same applies to the other runtimes as well):

```
const app = new cdk.App();

const myParam = app.node.tryGetContext("myParam");
if (myParam === undefined || !(typeof(myParam) === 'string') || myParam.trim() === '') {
  throw new Error("Must pass a '-c myParam=<MyParam>' context parameter");
}

new XyzStack(app, `xyz-${myParam}`, {
  env: { account: '1234567890', region: 'eu-west-1' },
});
```
which would produce a stack called `xyz-some-value`. It will also apply to `cdk synth -c myParam=some-value`
