### ISSUE TITLE
[apigateway] Expose domain and path seperately

### ISSUE THREAD

**Issue by Gaelan** [aws/aws-cdk#9266]
Expose a `RestApi.defaultDomain` method that returns just the domain portion of `RestApi.urlForPath("/")`.

### Use Case

I'm setting up an API Gateway behind a CloudFront deployment. CloudFront asks for the domain and path separately, but API Gateway only exposes a pre-built URL. This leaves me with two unappetizing options:

1. Assemble the domain myself with [code copy-pasted from the API Gateway module](https://github.com/aws/aws-cdk/blob/dac9bb312f5b0a9c83d929c862e30b49f3b8654a/packages/%40aws-cdk/aws-apigateway/lib/stage.ts#L263) (`${this.restApi.restApiId}.execute-api.${Stack.of(this).region}.${Stack.of(this).urlSuffix}`)
2. Parse the result of `urlForPath` myself (Node's URL library can't be used for this, because it contains tokens, making it an invalid URL)

### Proposed Solution

It should be fairly simple to extract the domain name generation in `urlForPath` into a separate public method. As always, the hard part is naming it--RestApi already has a `domainName` property, which contains any custom domain name added with `addDomainName`. Maybe `defaultDomain` or `awsDomain` would work? I'm happy to hear a better idea.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
`baseUrl` is the word APIGateway [uses](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-call-api.html). However, this includes the `stageName`.

Does this work?

**Comment by Gaelan** [comment]
The base URL with the stageName included is already exposed (as `urlForPath("/")`). The issue is that I need the domain and path (i.e. stage name) separately to configure CloudFront.

**Comment by peterwoodworth** [comment]
Hey @Gaelan , is this something you'd still like to see?
