### ISSUE TITLE
Support AWS Chime (SDK version)

### ISSUE THREAD

**Issue by 0xdevalias** [aws/aws-cdk#9268]
Looking at the current [CDK API reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html), there doesn't appear to be any high level support for the AWS Chime (SDK), and I could only find [one other issue](https://github.com/aws/aws-cdk/issues/8636) mentioning it within this repo.

In trying to google for it, I also can't seem to come across any CloudFormation support for AWS Chime (SDK), but unsure if I just missed it.

I assume that it requires some 'setup' to be able to use from an application, though when I attempted to manually open the AWS Chime service in the AWS Console to check this, it just [linked to a page](https://chime.aws.amazon.com/console/index.jsp) that gave me a 400 error, so i'm not even perfectly sure of that.

References:

- https://aws.amazon.com/chime/chime-sdk/
  - https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html
- https://pages.awscloud.com/Building-Real-Time-Audio-and-Video-Calling-in-Your-Applications-with-the-Amazon-Chime-SDK_2020_0329-BAP_OD.html
- https://github.com/aws/amazon-chime-sdk-js
  - https://aws.github.io/amazon-chime-sdk-js/modules/gettingstarted.html
- https://github.com/aws-samples?q=chime&type=&language=

### Use Case

I was wanting to explore using AWS Chime (SDK) for embedding video chat features within my web application.

### Proposed Solution

N/A

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @0xdevalias, thanks for opening this issue. Unfortunately it is out of scope for now since it doesn’t have any support from Cloudformation. But maybe in the future? We have no real way of interacting with it as of now.

**Comment by SomayaB** [comment]
I will close this issue for now and we can reopen it once it has Cloudformation support.

**Comment by codeslubber** [comment]
Sad....

**Comment by 0xdevalias** [comment]
> and we can reopen it once it has Cloudformation support

@SomayaB So what's the state of that in 2022/almost 2023?

**Comment by MrArnoldPalmer** [comment]
As far as I can tell there is no information regarding CloudFormation support for aws chime resources. However, there is a construct library available built using custom resources to work that.

[Construct Hub](https://constructs.dev/packages/cdk-amazon-chime-resources/v/0.1.191?lang=typescript)
[Github](https://github.com/cdklabs/cdk-amazon-chime-resources)
