### ISSUE TITLE
Vpc import subnet grouping

### ISSUE THREAD

**Issue by IndikaUdagedara** [aws/aws-cdk#927]
https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-ec2.html#@aws-cdk/aws-ec2.VpcNetworkRef

It is not clear how to specify subnet groups in `VpcNetworkRefProps` - it accepts `privateSubnetNames` which is a 

> List of names for the private subnets. Must be undefined or have a name for every private subnet group.

 However, `privateSubnetIds` is a 

> List of private subnet IDs. Must be undefined or match the availability zones in length and order

How do you specify the grouping of subnetIds there? Do you have an example?

**Comment by indikaudagedara** [comment]
hmm.. it seems to be done like this

```
  public import(parent: cdk.Construct): VpcSubnetRef[] {
    return range(this.subnetIds.length).map(i => {
      const k = Math.floor(i / this.availabilityZones.length);
      return VpcSubnetRef.import(parent, subnetId(this.names[k], i), {
        availabilityZone: this.pickAZ(i),
        subnetId: this.subnetIds[i]
      });
    });
  }
```

i.e. 
subnetids = [grp1-subnet1, grp1-subnet2, grp2-subnet1, grp2-subnet2]
subnetnames = [grp1, grp2]

Please correct if I'm wrong. Mentioning this in docs or an example would be nice. I'll do a PR if I get a chance.

**Comment by rix0rrr** [comment]
You got it, one subnet for every AZ is considered a group.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any activity on it in a while. Feel free to reopen.
