### ISSUE TITLE
[cdk-pipelines]  Manual Approval should configure the external link URL to a reasonable default

### ISSUE THREAD

**Issue by roskelleycj** [aws/aws-cdk#9272]
When the [AddStageOptions](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.AddStageOptions.html) uses manualApproval=true it would be ideal to place a useful link that is related to what is being approved.

### Use Case

See #9101 for an example of constructing a Stage with the manualApproval set to true.  When it has been enabled there are several possibilities that could be presented to the person approving the next set of actions.  Here are just a few:
* The set of 'Change Set' links that were created as part of the 'Prepare' actions in the Stage.
* The 'pipeline execution' link that needs to be approved.
* The 'Source change' link that causes the pipeline to get to this point.

Since the pipeline execution link is already included and the Source Link can be derived easily, it might make sense to allow the link to be associated with the ChangeSet link that was created as part of the 'Prepare' action.  Ideally all of the links would be presented.  However, it seems to be a deficiency in the codepipeline API to only allow one link for manual approvals.

### Proposed Solution

When the manual approval is added allow an association to be made between the stack in the stage that is being approved.  And if there is only one stack, automatically associate the the Prepare actions link.

Another possibility might be to automate the comment too.  In that the git change comment is known and could be included to.

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Worse, as far as I know, the link must be static (that is, independent of the current execution), whereas all the links you are proposing depend on the change currently running through the pipeline.

Maybe I'm wrong, and I can use pipeline variables to make useful links. Would appreciate some tips and pointers here!

**Comment by luisantonioa** [comment]
You can use codepipeline variables:  
https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-variables.html#actions-variables-examples-approvals
This does require plumbing a namespace value into the source action.

The example above works for a CodeCommit Repository but I'm not sure if a github source action would work.

A workaround to this could be enabling a variable namespace in the Build Synth Action as within the CodeBuild Project you can make use of env/exported-variables in the buildspec to export values out of codebuild and then they can be used in downstream actions like the first example.

CodeBuild exported variables: 
https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.env.exported-variables

CodePipeline variable docs:
https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html#reference-variables-rules.

I tried to have a quick play at adding this to a cdk pipeline but right now its not simple to access the action behind the synth project to set the variable namespace:  
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.ActionProperties.html#variablesnamespace.

Ideally there is PR to this package that maybe gives the source/synth actions a default namespace name so customers are unblocked from doing this themselves.

**Comment by PrettySolution** [comment]
Hi, is there any progress on ExternalEntityLink
