### ISSUE TITLE
[SQS][VPC] Cannot create VPC InterfaceEndpoint for SQS in aws-cn

### ISSUE THREAD

**Issue by imgaray** [aws/aws-cdk#9277]
### The Question
When adding an SQS interface endpoint with CDK (v1.32.2), the service name that gets output in the Cloudformation json is in the format of `com.amazonaws.${AWS::Region}.sqs`. This fails  to deploy to the `aws-cn` partition due to SQS using the service name of `cn.com.amazonaws.cn-northwest-1.sqs`. 

### Environment

  - **CDK CLI Version:**  1.32.2
  - **Module Version:**  1.32.2
  - **Node.js Version:** 12.18.2
  - **OS:** all
  - **Language:** TypeScript

### Other information
Example code:

```
this.vpc.addInterfaceEndpoint('sqsGateway', {
            service: InterfaceVpcEndpointAwsService.SQS,
            subnets: {
                subnetType: SubnetType.PRIVATE
            }
        });

```

Generated JSON:

```
"ServiceName": {
          "Fn::Join": [
            "",
            [
              "com.amazonaws.",
              {
                "Ref": "AWS::Region"
              },
              ".sqs"
            ]
          ]
        },
```

**Comment by flemjame-at-amazon** [comment]
This is fixed in https://github.com/aws/aws-cdk/issues/8372
If you can't update to v1.51, then you can work around it by creating an InterfaceVpcEndpointService and specifying the name as "cn.com.amazonaws.cn-northwest-1.sqs"
