### ISSUE TITLE
[assertions] haveResource without generating the logical Id hashes 

### ISSUE THREAD

**Issue by Azwraith42** [aws/aws-cdk#9278]
I feel it would be helpful for unit testing if there was a version of 'haveResource' similar to 'haveResourceLike' that allows you to assert against the logical Id of a resource without the unique hash.

### Use Case

Many resources require the logicalId or ARN of other resources. For example, I have an SNS topic I want to use a lambda to send an email with. If I want to test that I am passing the SNS Topic Arn correctly as an environment variable, asserting that my stack has a lambda function resource with an environment variable of the Arn fails because the reference to the arn will be `"${Token[TOKEN.56]}"`. What you can do is say the environment variable has a value of "Ref: <the logical Id>", but the stack has the unique hash with it while my `topic.topicName` does not.

### Proposed Solution

I would propose an assertion like `haveResourceSimple`. Given a construct like

```typescript
export interface EmailLambdaProps {
    topic?: ITopic,
    email: string
}
export class EmailLambda {
    public readonly topic: ITopic;
    public readonly email: string;
    public readonly lambda: l.Function;

    constructor(scope: cdk.Construct, id: string, props: EmailLambdaProps) {

        this.email = props.email;
        this.topic = props.topic || new Topic(scope, 'EmailLambdaTopic');

        this.lambda = new l.Function(scope, 'LambdaFunction', {
            runtime: l.Runtime.NODEJS_12_X,
            handler: 'index.handler',
            code: l.Code.fromAsset("lib/lambdas"),
            environment: {
                TOPIC_ARN: this.topic.topicArn
            }
        });

        this.topic.addSubscription(new sub.EmailSubscription(this.email))
        this.topic.grantPublish(this.lambda)
    }
}
```

I want to be able to assert that my environment variable is passed correctly with a test like
```typescript
    test('Function has topicArn as environment variable', () => {
        const stack = new cdk.Stack();
        const email = "someEmail";
        const uniqueId = 'SomeId';
        const topic = new Topic(stack, uniqueId);

        new EmailLambda(stack, 'testEmailLambda', {
            email,
            topic
        });

        expect(stack).to(haveResourceSimple("AWS::Lambda::Function", {
            Environment: {
                Variables: {
                    TOPIC_ARN: {
                        Ref: uniqueId
                    }
                }
            }
        }));
    });
```
If done with `haveResource` this would fail because it would try to compare `"SomeId6C362A7D"` to `"SomeId"`. 

### Other

Currently the only way I have found to get close to something I would use in production I found on a [stackOverflow post here](https://stackoverflow.com/questions/61803090/how-to-get-logical-id-of-resource-with-cdk) suggesting `Ref: stack.getLogicalId(topic.node.defaultChild as CfnTopic)`, but I would prefer to not use seemingly internal object references and be able to simply describe what I am testing.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hi @Azwraith42 -

How about doing this instead as -

```ts
TOPIC_ARN: stack.resolve(topic.topicArn);
```

Does that address your use case?
