### ISSUE TITLE
L2s: return a concrete physical name/ARN instead of token when possible

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#928]
For things like cross-region/account references (#49), it might be needed to use "well-known" physical names for resources when they are referenced across stacks.

Today, L2 properties that represent attributes are always resolved to the L1 attribute. For example, `bucket.bucketName` will always resolve to `{ "Fn::GetAtt": [ "ID", "Name" ] }`. However, if users explicitly specified a bucket name when they defined the bucket (`new Bucket(this, 'Mybucket', { bucketName: 'foo' })`), then why not just return `"foo"` for `bucket.bucketName`?

Then, consumers can use something like `unresolved(bucket.bucketName)` to determine if this is a concrete valuer or not when they read the value.

**Comment by skinny85** [comment]
I believe the current reason for always using `{ "Fn::GetAtt": [ "MyResource", "Name" ] }` instead of just `'foo'` is that the former establishes an implicit dependency ordering in CloudFormation. This way, we're certain resources in the Stack will get created in the correct order.

**Comment by eladb** [comment]
Duplicate with #4093
