### ISSUE TITLE
[@aws-cdk/aws-s3-deployment] Error trying to download aws s3 deployment version 1.49.0

### ISSUE THREAD

**Issue by malinoa** [aws/aws-cdk#9282]
Trying to download aws s3 deployment version 1.49.0 I am getting a error 

### Reproduction Steps

 npm i @aws-cdk/aws-s3-deployment@1.49.0

### Error Log
```console
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '@aws-cdk/aws-s3-deployment@1.49.0'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session c8b5ba88df9979ce
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://pkgs.dev.azure.com/evtcea/evt-cdk/_packaging/evt-cdk/npm/registry/@aws-cdk%2faws-s3-deployment 3605ms
8 silly fetchPackageMetaData error for @aws-cdk/aws-s3-deployment@1.49.0 No matching version found for @aws-cdk/aws-s3-deployment@1.49.0.
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 4559ms
11 verbose type version
12 verbose stack @aws-cdk/aws-s3-deployment: No matching version found for @aws-cdk/aws-s3-deployment@1.49.0.
12 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:122:13)
12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:14
12 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
12 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
12 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
12 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
12 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
12 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
12 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
12 verbose stack     at processImmediate (internal/timers.js:456:21)
13 verbose cwd C:\aws\cdk-devops-nexus
14 verbose Windows_NT 10.0.18362
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@aws-cdk/aws-s3-deployment@1.49.0"
16 verbose node v12.16.2
17 verbose npm  v6.14.4
18 error code ETARGET
19 error notarget No matching version found for @aws-cdk/aws-s3-deployment@1.49.0.
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @malinoa - Are you sure this wasn't a sporadic issue or something with your network configuration? Im able to successfully download and you can also see the version is available on npm: https://www.npmjs.com/package/@aws-cdk/aws-s3-deployment/v/1.49.0.

**Comment by malinoa** [comment]
Hi @iliapolo   thanks for reply... I do not have any problem with my network configuration since I am able to download another aws libraries... I tried in my personal laptop and home network,  tried at  office and with my  hots post... and teh result is the same 
![image](https://user-images.githubusercontent.com/68884674/89236059-8d0a0200-d5bd-11ea-9b1c-06ec27f38928.png)

**Comment by iliapolo** [comment]
@malinoa Are you able to download a different version of `@aws-cdk/aws-s3-deployment`?. 

Might also help if you run `npm` with verbose: `npm i --loglevel verbose @aws-cdk/aws-s3-deployment@1.49.0`.

**Comment by malinoa** [comment]
@iliapolo here the output
![image](https://user-images.githubusercontent.com/68884674/89334122-0bb97a80-d664-11ea-9b24-60f834d89d8a.png)

**Comment by malinoa** [comment]
@iliapolo   Regarding your question:  Are you able to download a different version of @aws-cdk/aws-s3-deployment?.
I am able to downlod any version less than 1.49.0

**Comment by iliapolo** [comment]
@malinoa I see that your NPM if configured to access a custom azure registry: `https://pkgs.dev.azure.com/....`

Could this registry be lagging somehow? Or maybe its blocking the package for some reason? I suspect this is the issue. If you can, configure NPM to use the default registry (`https://registry.npmjs.org/`) and see if reproduces.

**Comment by malinoa** [comment]
it was worked as expected... do you have any idea why this library version is blocked and others libraries I am able to download    I mean using the same configuration used for  NPM to access a custom azure registry: https://pkgs.dev.azure.com/.... 
I am able to download :

npm i @aws-cdk/assert@1.49.0
npm i @aws-cdk/aws-ec2@1.49.0
npm i @aws-cdk/aws-iam@1.49.0
npm i @aws-cdk/aws-s3@1.49.0
npm i @aws-cdk/core@1.49.0
npm i aws-cdk@1.49.0
npm i @aws-cdk/aws-elasticloadbalancingv2@1.49.0
npm i @aws-cdk/aws-autoscaling@1.49.0
npm i @aws-cdk/aws-logs@1.49.0
npm i @aws-cdk/aws-codepipeline@1.49.0
npm i @aws-cdk/aws-elasticloadbalancing@1.49.0


Except :  
**npm i @aws-cdk/aws-s3-deployment@1.49.0**

Appreciate your time!!!

**Comment by iliapolo** [comment]
Im not sure why the registry would be blocking these libraries. We haven't added anything to this library in version 1.49.0 as you can see [here](https://github.com/aws/aws-cdk/releases/tag/v1.49.0).

You'd need to have a look at the registry logs or possibly contact azure support :\

**Comment by malinoa** [comment]
Thanks fro your support
