### ISSUE TITLE
[@aws-cdk/aws-codedeploy] Add support for Triggers property in ServerDeploymentGroup

### ISSUE THREAD

**Issue by JosipTrbuscic** [aws/aws-cdk#9287]
Currently [ServerDeploymentGroup](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codedeploy.ServerDeploymentGroup.html) construct does not provide prop for adding triggers which are available in [CfnDeploymentGroup](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codedeploy.CfnDeploymentGroup.html). Can we add support for this in construct?

### Use Case

Trigger prop would allow adding triggers in construct.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Hey @JosipTrbuscic thank you for your contribution! Are you still intending to make the changes requested to your PR to get it merged?

**Comment by CaptChakri** [comment]
Reopening the issue, as `ServerDeploymentGroup` still doesn't support `triggersConfiguration` in the cdk construct.
