### ISSUE TITLE
[cli] How to validate the output of the stack before deploying?

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#9288]
## :question: General Issue
I'm not sure if this a bug or lack of a feature, or simply I'm missing something. Is it possible to validate what is about to deploy before actually deploying the stack?  
For example I had a stack which creates two Roles with S3 policy. I made a mistake and used just the bucket name (instead of the ARN) as the resource and got the following error during deployment:
> Resource my-bucket must be in ARN format or "*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument;

Seems to be simple validation (whether built-in or using external tools like cfn-lint).

**Comment by shivlaks** [comment]
@akefirad can you share the code that you were using? we do validate some resources and properties and perhaps this is one that's missing. it should be relatively straightforward to add in so we can fail during `synth` ahead of any deployments.

**Comment by akefirad** [comment]
I don't have the code to share. But it basically was a stack with a role with a policy to read from a bucket and the resource in the policy was just the name of the bucket instead of bucket ARN. Something like this:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["s3:GetObject"],
      "Effect": "Allow",
      "Resource": "foo-bucket", // this is wrong
      "Principal": {
        "AWS": ["arn:aws:iam::123456789012:user/foo"]
      }
    }
  ]
}
```
Do you still need a sample code?

**Comment by shivlaks** [comment]
@akefirad Were you using a `Cfn*` class or a higher level construct?

yes please, the sample code would identify the construct where we would want to consider adding validation into.

**Comment by akefirad** [comment]
```typescript
# cdk init
# and then use the below stack

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new iam.Role(this, 'FooRole', {
      assumedBy: new iam.AccountPrincipal(account_id), // FIXME: this also fails if it's not the current account 
      inlinePolicies: {
        buggyS3Policy: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              actions: ['s3:GetObject'],
              resources: ['my-bucket/my-key'] // FIXME: this is gonna fail because it's not a valid ARN
            })]
        })
      },
    })
  }
}
```

**Comment by rix0rrr** [comment]
cfn-lint is realistically the only tool which is going to catch things like this. We do our best but we can't catch everything.
