### ISSUE TITLE
[aws-stepfunctions-tasks] Unable to use the Wait for task Token: Task Token is missing in payload (pass Context.taskToken somewhere in payload)

### ISSUE THREAD

**Issue by mariobittencourt** [aws/aws-cdk#9292]
### The Question

How can I specify a task that uses the wait for task token using CDK.

The README does not contain an example using the RunLambdaTask (https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-stepfunctions-tasks#lambda) so I took the existing one and adapted like below 
```
const reserveHotel = new sfn.Task(this, 'doX', {
      task: new tasks.RunLambdaTask(doXLambda, {
        integrationPattern: sfn.ServiceIntegrationPattern.WAIT_FOR_TASK_TOKEN,
        payload: sfn.TaskInput.fromObject({
          taskToken: "$$.Task.Token",
          input: "$"
        })
      }),
      resultPath: '$.Result'
    }).addCatch(otherTask, {
      resultPath: "$.Error"
    });
```

When trying to use cdk synth it complains "Task Token is missing in payload (pass Context.taskToken somewhere in payload)".
I've tried variations using the `sfn.Context.taskToken` but same result.

I guess it would be beneficial to update the ReadME to indicate the correct way of doing so.

### Environment

  - **CDK CLI Version:** 1.54.0 (build c01b9b9)
  - **Module Version:** Not sure
  - **Node.js Version:** 12.18.3
  - **OS:** Ubuntu 20
  - **Language (Version):** Typescript

**Comment by michaelwiles** [comment]
It's worth taking a look at the existing tests... 

and it looks like there is a [test that exercises this](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke-function.ts)

According to the test your payload should be:

```
 payload: sfn.TaskInput.fromObject({
      token: sfn.JsonPath.taskToken,
    }),
```

**Comment by shivlaks** [comment]
@mariobittencourt - I'd also start by taking a look at the test as suggested by @michaelwiles 

Note that RunLambdaTask is marked as `deprecated` and I'd suggest moving over to `LambdaInvoke`, especially if you're sticking to the examples in the README as they've all been ported over

**Comment by mariobittencourt** [comment]
> @mariobittencourt - I'd also start by taking a look at the test as suggested by @michaelwiles
> 
> Note that RunLambdaTask is marked as `deprecated` and I'd suggest moving over to `LambdaInvoke`, especially if you're sticking to the examples in the README as they've all been ported over

Hi @shivlaks thank you for the answer but I think it is the other way around. At least from the code I see

```
/**
 * A Step Functions Task to invoke a Lambda function.
 *
 * The Lambda function Arn is defined as Resource in the state machine definition.
 *
 * OUTPUT: the output of this task is the return value of the Lambda Function.
 *
 * @deprecated Use `RunLambdaTask`
 */
export declare class InvokeFunction implements sfn.IStepFunctionsTask {
```

**Comment by mariobittencourt** [comment]
> It's worth taking a look at the existing tests...
> 
> and it looks like there is a [test that exercises this](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke-function.ts)
> 
> According to the test your payload should be:
> 
> ```
>  payload: sfn.TaskInput.fromObject({
>       token: sfn.JsonPath.taskToken,
>     }),
> ```

Hi @michaelwiles thank you. I am looking at the tests. Interesting enough now the problem now is on the compilation phase
`error TS2339: Property 'JsonPath' does not exist on type 'typeof import("/my-path/node_modules/@aws-cdk/aws-stepfunctions/lib/index")'`

I am using `import * as sfn from '@aws-cdk/aws-stepfunctions';`

**Comment by shivlaks** [comment]
@mariobittencourt what version are your modules?

> > @mariobittencourt - I'd also start by taking a look at the test as suggested by @michaelwiles
> > Note that RunLambdaTask is marked as `deprecated` and I'd suggest moving over to `LambdaInvoke`, especially if you're sticking to the examples in the README as they've all been ported over
> 
> Hi @shivlaks thank you for the answer but I think it is the other way around. At least from the code I see
> 
> ```
> /**
>  * A Step Functions Task to invoke a Lambda function.
>  *
>  * The Lambda function Arn is defined as Resource in the state machine definition.
>  *
>  * OUTPUT: the output of this task is the return value of the Lambda Function.
>  *
>  * @deprecated Use `RunLambdaTask`
>  */
> export declare class InvokeFunction implements sfn.IStepFunctionsTask {
> ```

`InvokeFunction` is the predecessor to `RunLambdaTask`. `RunLambdaTask` is the predecessor to `LambdaInvoke`

I implemented `RunLambdaTask` and deprecated it when I introduced `LambdaInvoke` - here's the [reference documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.RunLambdaTask.html) and the [code](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts#L6-L10).


All of the code samples in the `README` and module overview should be using LambdaInvoke.

**Comment by mariobittencourt** [comment]
Package.json 
```
"devDependencies": {
    "@aws-cdk/assert": "1.36.0",
    "@types/jest": "^24.0.22",
    "@types/node": "10.17.5",
    "aws-cdk": "1.36.0",
    "jest": "^24.9.0",
    "ts-jest": "^24.1.0",
    "ts-node": "^8.10.2",
    "typescript": "~3.7.2"
  },
  "dependencies": {
    "@aws-cdk/aws-apigateway": "1.36.0",
    "@aws-cdk/aws-dynamodb": "1.36.0",
    "@aws-cdk/aws-lambda": "1.36.0",
    "@aws-cdk/aws-stepfunctions": "1.36.0",
    "@aws-cdk/aws-stepfunctions-tasks": "1.36.0",
    "@aws-cdk/core": "1.36.0",
    "source-map-support": "^0.5.19"
  }
```

cdk version: 1.55.0 (build 48ccf09)

**Comment by shivlaks** [comment]
@mariobittencourt 

`JsonPath` was introduced in `1.48.0`. Prior to that you would use `sfn.Context.taskToken` and not `sfn.JsonPath.taskToken`. Give that a try and let me know how it goes!

Also, `LambdaInvoke was introduced in `1.41.0` so it's not an option for you until you upgrade to a more recent version.

**Comment by mariobittencourt** [comment]
Thank you. I updated and now it is recognized.

Now I just have to figure out how to pass the input in the payload alongside the token.  the equivalent of  
```
{
  "token.$": "$$.Task.Token",    // this is fine sfn.JsonPath takes care
  "input.$": "$"
}
```

**Comment by mariobittencourt** [comment]
```
payload: sfn.TaskInput.fromObject({
          token: sfn.JsonPath.taskToken,
          input: sfn.JsonPath.entirePayload
        })
```

Did the trick. I hope it is the right way.

**Comment by shivlaks** [comment]
@mariobittencourt - you got it, that's what I would expect it to look like, and glad to see you got it going!!! 

Are we good to close this issue or did you have any other outstanding questions?

**Comment by mariobittencourt** [comment]
all good Sir. Thank you for your support.
I will try to propose a PR with minor suggestions to the documentation. At least for me the entirePayload was more or less lucky and others may stumble the same question.

**Comment by shivlaks** [comment]
@mariobittencourt great! 

I should also mention the default should be the entire payload if you're using `LambdaInvoke`.
you shouldn't need to explicitly specify it unless you're selecting part of the state input.
