### ISSUE TITLE
[synthetics] support runConfig properties

### ISSUE THREAD

**Issue by kaizencc** [aws/aws-cdk#9300]
### Issue

AWS Synthetics Canary has an optional `runConfig` [property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-runconfig.html) that is currently not supported by the Canary L2. This property exposes `timeoutInSeconds` and `memoryInMb`. 

The difficulty is that `timeoutInSeconds` is required if `runConfig` is set, so one cannot **only** specify `memoryInMb`. 

This does not seem like it should be a hard requirement (i.e. one should be able to set `memoryInMb` without `timeout`).

The requirements for `timeoutInSeconds` are that it is inside the range 3 - 840 seconds* and not greater than the amount specified in the `schedule` expression. 

&nbsp;

\* yes, this is different than specified in the docs but I tried to set it to be 900 seconds and received the error "Invalid request provided: Run timeout cannot be less than 3 seconds or greater than 840 seconds"

### Use Case

The use case for this property is unclear so this issue serves as a platform for discussion on whether it is needed and how to implement.

While the proposed solution is possible, this seems like extra work if the `runConfig` property is largely ignored anyway. And if `timeoutInSeconds` becomes optional, then we no longer need to find a default for the property.

### Proposed Solution

Add separate optional properties `timeout: cdk.Duration` and `memorySize: cdk.Size` to `CanaryProps`.

`timeout` should default to the minimum of 840 seconds and the amount in `expression`. This would require parsing through the expression string to extract the number/unit and convert to seconds.

`memorySize` is optional in `runConfig`, so no need to default and it is up to the user to specify a valid amount of memory.

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by ArendAMZN** [comment]
+1, our team would like to use this for environment variables

Also we want our canaries to run every minute, this is supported in cfncanary, but not in synthetics.canary

We added the cfncanary work around, but it's making it hard to extend our cdk from there. For example, adding alarms is much easier using synthetics.canary as opposed to cfncanary

**Comment by laksandy** [comment]
+1, our team would like to use this for environment variables
