### ISSUE TITLE
[elasticloadbalancing] Clarify expected value of sslCertificateId property of LoadBalancerListener is an ARN

### ISSUE THREAD

**Issue by dillon-odonovan** [aws/aws-cdk#9303]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancing.LoadBalancerListener.html#sslcertificateid

I was attempting to replicate some existing AWS resources in a CDK app and one of the resources was a Classic Load Balancer which had an HTTPS listener and was using an ACM certificate. The documentation describes the `sslCertificateId` property of `LoadBalancerListener` as the "ID of the SSL Certificate", and the data type of the field is a `string`, so I supplied the ACM identifier. When I tried `cdk deploy`, I eventually got an HTTP 400 error "Server Certificate not found for the key". I verified that I had no typos and was left a little confused as to why the `sslCertificateId` was not found, so I went to the CLI documentation looking for additional information on the API call being used and any restrictions on the input. I landed on the AWS CLI documentation for [set-load-balancer-listener-ssl-certificate](https://docs.aws.amazon.com/cli/latest/reference/elb/set-load-balancer-listener-ssl-certificate.html), where the definition of `--ssl-certificate-id` states that this is the ARN of the SSL Certificate. 

I would like the CDK documentation updated to reflect this, and explicitly state that `sslCertificateId` refers to the ARN of the certificate and not just the identifier, as simply referring to it as an ID or identifier is a bit ambiguous for those not already aware that the expected value is an ARN.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Fair. Even better probably is to rename to `sslCertificateArn`.

**Comment by OksanaH** [comment]
Hello, I would like to work on this issue, and I have a question: do I need to submit 2 different PRs - one for just fixing the documentation and another one for actually changing the property name? Thanks
