### ISSUE TITLE
[@aws-cdk/pipelines] Maximum policy size of 10240 bytes exceeded for role

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#9316]
### The Question
After adding around 5 stacks to a single Pipeline Application (Stage) the pipeline references 15 assets and new reused PipelineAssetRole policy grows to be too large, blocking the pipeline and making it unusable.

Just tried out the latest fix (#9243) with v1.55.0 But now I am seeing this error when deploying.

```
Maximum policy size of 10240 bytes exceeded for role PipelineStack-PipelineAssetsRole9B011X83-1UOLXJQTUXXXX
```

### Environment

  - **CDK CLI Version:** 1.55.0 (build 48ccf09)
  - **Module Version:** 1.55.0
  - **Node.js Version:** v14.5.0
  - **OS:** OSX Catalina
  - **Language (Version):** TypeScript (3.9.7)

### Other information

Related: 
https://github.com/aws/aws-cdk/issues/9225

**Comment by njlynch** [comment]
The individual statements for a single asset within the `PipelineAssetsRoleDefaultPolicy` comes in at ~2400 bytes; this means the current approach only scales to about 4-5 assets before we will hit this policy size limit.
