### ISSUE TITLE
[s3-deployment] Validate leading slash in cloudfront invalidation paths.

### ISSUE THREAD

**Issue by Gaelan** [aws/aws-cdk#9317]
Before deploying, validate that each element of `distributionPaths` starts with a slash.

### Use Case

The following code results in a CloudFormation failure:

```js
new BucketDeployment(this, "DeployPublic", {
  sources: [Source.asset(`${app}/public`)],
  destinationBucket: assetsBucket,
  destinationKeyPrefix: "",
  distribution: dist,
  distributionPaths: ["images/*"],
})
```

The issue is that `distributionPaths` should have a leading slash, i.e. `/images/*`. Cloudfront errors are slow and frustrating, so should be avoided where possible.

### Proposed Solution

Make sure the paths have a leading slash before attempting to deploy.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@Gaelan Thanks for this. Any chance you can also attach the specific error that happens? Or a link to a documentation page that explains this behavior?

**Comment by Gaelan** [comment]
Sure. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#invalidation-specifying-objects-paths:

> In the CloudFront console, you can omit the leading slash in the path, like this: images/image2.jpg. When you use the CloudFront API directly, invalidation paths must begin with a leading slash.

**Comment by iliapolo** [comment]
@Gaelan Cool. Thanks!

**Comment by peterwoodworth** [comment]
Hey @Gaelan, thanks again for submitting this issue! I see you said you might be able to implement this, any chance you still want to implement this yourself? I'd be happy to take a look at the pr you would submit for this
