### ISSUE TITLE
[aws-cdk-java] TaskEnvironmentVariable is missing valuePath property 

### ISSUE THREAD

**Issue by clementy28** [aws/aws-cdk#9318]
### Reproduction Steps

Class: software.amazon.awscdk.services.stepfunctions.tasks.TaskEnvironmentVariable

It is missing the valuePath property, to generate a "Value.$" key.

    /**
     * Value of the environment variable.
     * <p>
     * Exactly one of <code>value</code> and <code>valuePath</code> must be specified.
     */
    @software.amazon.jsii.Stability(software.amazon.jsii.Stability.Level.Stable)
    @org.jetbrains.annotations.NotNull java.lang.String getValue();

### Environment

  - **CLI Version      :** 
  - **Framework Version:**  1.5793
  - **Node.js Version:** 
  - **OS               :** 
  - **Language (Version):**  Java 11

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
discussed this with @clementy28 offline. This is actually already supported.
Here's an example in our [test](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/test/ecs/run-tasks.test.ts#L70) and the [expectation](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/test/ecs/run-tasks.test.ts#L102)
