### ISSUE TITLE
[lambda-nodejs] doc issue - Too Many Requests Docker Hub rate limit existed

### ISSUE THREAD

**Issue by ookangzheng** [aws/aws-cdk#9321]
While building lambda-nodejs I encounter this issue serveral time today while using codebuild. 

### Error Log

![image](https://user-images.githubusercontent.com/6301735/88772016-af151600-d1b2-11ea-9046-4bea9fa92537.png)

### Environment

  - **CLI Version : 1.54.0**
  - **Framework Version: 1.54.0**
  - **Node.js Version: v14.5.0** 
  - **Language (Version): Typescript 3.9.6** 

--- 

This is :bug: Bug Report

**Comment by j0k3r** [comment]
FWIW we got the same issue in AWS CodeBuild when using a custom image from Docker Hub. Using dedicated credentials to authenticate the request solved the issue for us.

As of now, without authenticating, it seems to be fixed too.
Maybe AWS (globally) hit the rate limit on Docker Hub 🤷‍♂️

**Comment by ookangzheng** [comment]
Our workaround will be using `buildspec.yml` login to a docker hub account to bypass rate limit.

**Comment by eladb** [comment]
@jogold let's add a documentation snippet to the bundling README with some guidance?

**Comment by jogold** [comment]
This looks like a temporary issue in CodeBuild not related to the `aws-lambda-nodejs` module? Can you confirm this @ookangzheng?

**Comment by ookangzheng** [comment]
What do you mean  "temporay issue" in CodeBuild? 
I agree, it maybe not related to `aws-lambda-nodejs` module, I hope maybe some how add a WARNING that let other users know it may need to login to docker hub everytime during CodeBuild.

**Comment by jogold** [comment]
I'm never logged in to Docker hub in CodeBuild and I don't have the issue. Anything specific about your setup? Are you pulling other images? With the Docker caching mechanism the image used by `aws-lambda-nodejs` should not be pulled more than once per CI run (and can be [cached across runs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html#caching-local-console))

**Comment by ookangzheng** [comment]
Currently we have this in our Codebuild
1. A docker image from docker hub: `docker:dind`
2. Will pull down Lambda typescript files in Codebuild container
3. Do `cdk deploy` will compile with `aws-lambda-nodejs` parcel v2 on Codebuild container.
4. No cache.

**Comment by j0k3r** [comment]
Have you tried https://aws.amazon.com/fr/blogs/devops/how-to-use-docker-images-from-a-private-registry-in-aws-codebuild-for-your-build-environment/ ?

**Comment by ookangzheng** [comment]
Nope

**Comment by nbaillie** [comment]
i have seen this issue today. with "@aws-cdk/aws-lambda-nodejs": "1.74.0",

stderr: Sending build context to Docker daemon   2.56kB
--
341 |  
342 | Step 1/9 : ARG IMAGE=amazon/aws-sam-cli-build-image-nodejs12.x
343 | Step 2/9 : FROM $IMAGE
344 | toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
345 | Subprocess exited with error 1
346 | Error: Subprocess exited with error 1

**Comment by jogold** [comment]
> im gessing it is affeced by this perhaps: [Docker rate-limits](https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=pull%20limits%20hub%20home%20page&utm_budget=)

Yes that's it... see also https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/ and the **Coming soon** part at the end.

**Comment by ookangzheng** [comment]
We migrate from Docker hub to Amazon ECR though because of parcel build going to fetch from Docker Hub, therefore we will log in to Docker Hub at Codebuild. 

`buildspec.yml` example
```yaml
env:
  variables:
  secrets-manager:
    DOCKER_HUB_USERNAME: docker-hub-credential:username
    DOCKER_HUB_PASSWORD: docker-hub-credential:password

phases:
  install:
    commands:
      - docker login --username ${DOCKER_HUB_USERNAME} --password ${DOCKER_HUB_PASSWORD}
      - npm install -g --unsafe-perm=true esbuild ## Recommend change from Parcel to esbuild 

```

**Comment by jogold** [comment]
This should be closed as the docker image is now fetched from the ECR Public Gallery.

**Comment by eladb** [comment]
Thanks
