### ISSUE TITLE
[aws-eks] All eks.ServiceAccount constructs Are Added to Cluster Stack

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#9325]
Let's say we have three stacks:  

* EKS Cluster Stack
```typescript
export class EksStack extends cdk.Stack {
  public readonly cluster: eks.Cluster;
  //  all the stuff needed to build an EKS cluster goes here;
  this.cluster = new eks.Cluster(this, 'EksCluster', clusterProps);
}
```
* K8S Namespaces Stack
```typescript
export interface K8SResourcesProps extends cdk.StackProps {
  readonly cluster: eks.Cluster;
}

export class K8SResourcesStack extends cdk.Stack {
  public readonly cluster: eks.Cluster;
  constructor(scope: cdk.Construct, id: string, props: K8SResourcesProps) {
    super(scope, id, props);

    new eks.KubernetesResource(this, 'MyNamespace', {
      cluster: props.cluster,
      manifest: loadManifestFile('k8s/my-namespace.yaml'),
    });
}
```
* Service Accounts Stack
```typescript
export interface K8SServiceAccountsProps extends cdk.StackProps {
  readonly cluster: eks.Cluster;
}

export class K8SServiceAccountsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: K8SServiceAccountsProps) {
    super(scope, id, props);

    const account = new eks.ServiceAccount(this.cluster, accountName, {
      cluster: props.cluster,
      name: accountName,
      namespace: accountNamespace,
    });
   // add some policies to the account;
}
```
Now the problem is, in the generated templates, service account resources are part of the Cluster stack (i.e. `K8SServiceAccountsStack` template is empty). I'm surprised by this, because for the namespaces stack, this is not the case, meaning, resources defined in the namespaces stacks are indeed part of the namespaces stack.

### Reproduction Steps
1. Create a stack containing a simple EKS cluster.
2. Create another stack containing service account resources for the cluster created above.
3. Generated the templates. (The second stack is empty.)

### Environment

  - **CLI Version      :** aws-cli/2.0.24 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev28
  - **Framework Version:** 1.54.0 (build c01b9b9)
  - **Node.js Version:** v14.5.0
  - **OS               :** Mac OS X 10.15.6
  - **Language (Version):** typescript ~3.7.2

### Other

I think this is important, since this way we cannot share a cluster stack we other stack and make sure about the ownership of the resources. 

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @akefirad 

Notice that when you create the `ServiceAccount`, you are passing the **cluster** as the scope, instead of the stack:

```typescript
const account = new eks.ServiceAccount(this.cluster, accountName, { // you should pass 'this', not 'this.cluster'
      cluster: props.cluster,
      name: accountName,
      namespace: accountNamespace,
    });
```

If should be:

```typescript
const account = new eks.ServiceAccount(this, accountName, {
      cluster: props.cluster,
      name: accountName,
      namespace: accountNamespace,
    });
```

Closing this, feel free to reopen if you still experience some problems.

Thanks

**Comment by akefirad** [comment]
@iliapolo For some reason I can't produce the original issue I reported (I don't have the original code). When I'm trying to do what you suggest, I get the following error:
> Error: 'EksClusterStack' depends on 'AccountsStack' (EksClusterStack -> AccountsStack/MyAccount/Role/Resource.Arn). Adding this dependency (AccountsStack -> EksClusterStack/Cluster/Resource/Resource/Default.OpenIdConnectIssuer) would create a cyclic reference.

The code is as follow:
```typescript
export class EksClusterStack extends cdk.Stack {
  public readonly cluster: eks.Cluster;

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const cluster = this.cluster = new eks.Cluster(this, 'Cluster', {
      version: KubernetesVersion.V1_17
    })
  }
}
```
and
```typescript
export interface StackProps extends cdk.StackProps {
  readonly cluster: eks.Cluster;
}

export class AccountsStack extends cdk.Stack {
  public readonly cluster: eks.Cluster;

  constructor(scope: cdk.Construct, id: string, props: StackProps) {
    super(scope, id, props);

    new eks.ServiceAccount(this, 'MyAccount', {
      cluster: props.cluster,
    })
  }
}
```
and
```typescript
#!/usr/bin/env node
import { EksClusterStack } from '../lib/test-cdk-stack';
import { AccountsStack } from '../lib/test-other-stack';

const app = new cdk.App();
const cluster = new EksClusterStack(app, 'EksClusterStack');
const accounts = new AccountsStack(app, 'AccountsStack', {
    cluster: cluster.cluster
})
```
What am I doing wrong? 😕

**Comment by iliapolo** [comment]
@akefirad Now you are not doing anything wrong :)

Unfortunately you stumbled upon this bug: https://github.com/aws/aws-cdk/issues/8884

As a workaround, define the `ServiceAccount` in the same stack as the cluster, we are actively working on a fix.

**Comment by akefirad** [comment]
Ah I see, ok, ok.
