### ISSUE TITLE
[aws-lambda-nodejs] enable lambda-nodejs to be a target of Event Bridge Rule

### ISSUE THREAD

**Issue by dave-graham** [aws/aws-cdk#9330]
I want to create a node lambda that is invoked from Event bridge. I'm using the following code:

```
const handler = new lambda.NodejsFunction(this, 'MyFunction', {
 ...
});

const rule = new Rule(this, "newRule", {
      description: "description",
      eventPattern: {
        source: ["one.two.three"],
        detailType: ["detail"],
      },
    });

rule.addTarget(handler);
```

And I'm seeing the following:

Argument of type 'NodejsFunction' is not assignable to parameter of type 'IRuleTarget'.
  Property 'bind' is missing in type 'NodejsFunction' but required in type 'IRuleTarget'

This works for standard lambda in cdk.

Anything you can do to help is really appreciated.

This is a :rocket: Feature Request

**Comment by eladb** [comment]
You need to use the `@aws-cdk/aws-events-targets.LambdaFunction` integration class:

```ts
rule.addTarget(new targets.LambdaFunction(handler));
```

**Comment by Lumene98** [comment]
> ```ts
> LambdaFunction
> ```

`Nodejsfunction` is not compatible to `LambdaFunction`
