### ISSUE TITLE
[elasticloadbalancingv2] NetworkTargeGroup should inherit protocol from listener 

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#9331]
If you create a network target group by using the `addTargets` method, the target group uses `TCP` as protocol instead of inheriting the protocol of the listener itself.

### Reproduction Steps

Create new NetworkListener with TCP_UDP as protocol and call addTargets.

### Error Log

You will see a protocol mismatch when deploying the app.

### Environment

  - **CLI Version      :** 1.55.0
  - **Framework Version:** 1.55.0
  - **Node.js Version:** v14
  - **OS               :** macOS
  - **Language (Version):** Python

### Other

[x] I can create a PR if you think this is valid.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
That sounds perfectly sensible.

**Comment by hoegertn** [comment]
Ok, I will open a PR. But I still think it is a bug because the resulting template is not deployable.
