### ISSUE TITLE
[IAM] AccountPrincipal appears to be functionally the same as AccountRootPrincipal

### ISSUE THREAD

**Issue by jsmartin** [aws/aws-cdk#9334]
AccountPrincipal appears to be functionally the same as AccountRootPrincipal

### Reproduction Steps

When generating an IAM Policy Statement, add an account principal:

`principals = [iam.AccountPrincipal('123456789123')]`

### Error Log

No errors.  The resulting Principal statement of the policy looks like:

```
      "Principal": {
        "AWS": "arn:aws:iam::123456789123:root"
      },

```

My expectation is that the it would look like:

```
      "Principal": {
        "AWS": "123456789123"
      },

```

### Environment

  - **CLI Version:** 1.55.0 (build 48ccf09)
  - **Framework Version:**
  - **Node.js Version:** v14.4.0
  - **OS:** OSX 10.15.16
  - **Language (Version):** Python 3.8.2

--- 

This is :bug: Bug Report

**Comment by jsmartin** [comment]
I was using this as a reference:  https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html.

I was seeing this behavior with S3 Bucket Policies, so to verify it I attempted adding a principal through the web console:

```
      "Principal": {
        "AWS": "123456789123"
      },
```

It saved properly, but when I reloaded the page it had become:

```
      "Principal": {
        "AWS": "arn:aws:iam::123456789123:root"
      },
```

Maybe this is just an S3 specific behavior?

**Comment by rix0rrr** [comment]
Those two phrasings mean exactly the same. Some services convert between them on "save", some don't, but rest assured the behavior is the same.

The classes are not exactly the same. `AccountRootPrincipal` means the *current* account, while `AccountPrincipal` allows you to supply an account.
