### ISSUE TITLE
[core] Add aws-rfdk to version reporting metadata

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#9336]
The AWS RFDK is a soon-to-be released library for use with the CDK. We have discussed leveraging the CDK's version reporting mechanism with @ccfife and received his blessing to do so.

### Use Case

Tracking usage of a new library for use with the CDK.

### Proposed Solution

I'll add a package whitelist to `core/private/runtime-info.ts`. I'll have a PR posted asap.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Fixed by #9337
