### ISSUE TITLE
[aws-ec2] AWS IP Ranges Lookup for use in Network ACLs and Security Groups

### ISSUE THREAD

**Issue by civilizeddev** [aws/aws-cdk#9347]
> "Amazon Web Services (AWS) publishes its current IP address ranges in JSON format."

https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html

### Use Case

Sometimes you want to know the range of IP addresses for AWS services.

1. Once you have `data: IpRanges` as below,

    ```ts
    import * as fs from 'fs'
    import * as path from 'path'
    import * as ec2 from '@aws-cdk/aws-ec2'
    
    export interface IpRanges {
      syncToken: string
      createDate: string
      prefixes: {
        ip_prefix: string
        region: string
        service: string
        network_border_group: string
      }[]
      ipv6_prefixes: {
        ipv6_prefix: string
        region: string
        service: string
        network_border_group: string
      }[]
    }
    
    const file = path.resolve(__dirname, '../ip-ranges.json')
    const json = fs.readFileSync(file).toString()
    const data = JSON.parse(json) as IpRanges
    ```

1. you can achieve this:

    ```ts
    data.prefixes
      .filter((_) => _.region === this.region)
      .filter((_) => _.service === 'S3') // Allow S3 Only
      .map((_) => _.ip_prefix)
      .map((cidr, index) => {
        return this.networkAcl.addEntry(`entry-ipv4-${index}`, {
          cidr: ec2.AclCidr.ipv4(cidr),
          direction: ec2.TrafficDirection.EGRESS,
          traffic: ec2.AclTraffic.tcpPort(443), // Allow HTTPS only
          ruleNumber: 1000 + index,
        })
      })
    ```

    ![image](https://user-images.githubusercontent.com/15084045/88867854-9b68be80-d249-11ea-8e4d-0e3fb92dfd5a.png)

1. And so...

    ```ts
    const securityGroup: ec2.SecurityGroup = ...

    data.prefixes
      .filter((_) => _.region === this.region)
      .map((_) => _.ip_prefix)
      .map((cidr) => {
        // Allow ingress traffic from AWS services
        return securityGroup.addIngressRule(ec2.Peer.ipv4(cidr), ec2.Port.allTraffic())
      })
    ```

### Proposed Solution

1. Download [ip-ranges.json](https://ip-ranges.amazonaws.com/ip-ranges.json) file

    > Just like you download `000_CloudFormationResourceSpecification.json` in `@aws-cdk/cfnspec`

    > **Q. Where is the good place for this file?**

1. Provide `interface IpRanges` for type-safe use.

    ```ts
    export interface IpRanges {
      syncToken: string
      createDate: string
      prefixes: {
        ip_prefix: string
        region: string
        service: string
        network_border_group: string
      }[]
      ipv6_prefixes: {
        ipv6_prefix: string
        region: string
        service: string
        network_border_group: string
      }[]
    }
    ```

    > **Q. Where is the good place for this file?** `@aws-cdk/core` or `@aws-cdk/aws-ec2`?

### Other

- **Roadmap**
  - [x] `ip-ranges.json` in the path
  - [x] Provide `interface IpRanges`
  - [ ] shell scripts for update
  - [ ] Extra helpers: enum, const...

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I think this makes a perfect use case for a 3rd party construct or CDK-related library.

If you build and publish it and it turns out that a lot of people derive a lot of value from it (to the point that 50+% of CDK applications use this library), we can talk about upstreaming it into core at a later point.
