### ISSUE TITLE
[aws-lambda-nodejs] running cdk in a container breaks bundling since docker is not present

### ISSUE THREAD

**Issue by obiwabrakenobi** [aws/aws-cdk#9348]
### The Question

We are running cdk in a jenkins pipeline which runs cdk in a docker container. Since bundling runs its own docker container it fails to start the bundling image. How can I manage that? I know that I can start containers from a running container (https://itnext.io/docker-in-docker-521958d34efd) like this. But how to pass all this to the bundling process?

### Environment

  - **CDK CLI Version:** 1.55.0
  - **Module Version:** 1.55.0
  - **Node.js Version:** v12.18.3
  - **OS:** Ubuntu Server 20.x
  - **Language (Version):** TypeScript (3.9.6)

**Comment by eladb** [comment]
I believe you simply need to setup your build environment so it can run docker (regardless of the CDK). The bundling process simply invokes `docker` from PATH. 

You can also set the environment variable `CDK_DOCKER` to point to an alternative executable (like a script) if you wish to customize something in this process.

**Comment by obiwabrakenobi** [comment]
yes that is already done. It starts a container which runs cdk. Then inside this container cdk wants to start another container which cannot find the docker bin since it is inside the container...

**Comment by obiwabrakenobi** [comment]
well after a few tries I don't get it running. Well the container starts but it brings several errors. It has something todo with the volumes

`
🚨 Build failed.

Error: Entry /asset-input/src/** does not exist
`

But from my perspective starting docker from docker is not a good practice. I'm not able to use any bundling container from inside a jenkins build which is running in a container too. Can anyone support on this?

**Comment by obiwabrakenobi** [comment]
@eladb do you mind to reopen the issue? I think that issue might affect everyone who is using docker to run a cdk build using a bundling image

**Comment by obiwabrakenobi** [comment]
nice! I'll give it a try!
