### ISSUE TITLE
[aws-autoscaling]Stack name is shown for EC2 instances instead of Name tag

### ISSUE THREAD

**Issue by mohdarshad** [aws/aws-cdk#9350]
I am trying to spin out EC2 instances through AutoscallingGroup. Using AWS CDK java language.
I am setting the name tag and PropagateAtLaunch: 'true'. But still EC2 instances name are shown as stack name and not the name tag value.

**Comment by NetaNir** [comment]
Can  you share a code sample?

**Comment by mohdarshad** [comment]
Can be solved by using priority property. Closing the issue.
