### ISSUE TITLE
[pipelines] Asset stage can't support more than 50 assets.

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#9353]
When attempting to deploy a pipeline with more than 50 assets, the deploy fails due to the Asset stage having more than 50 actions.

### Reproduction Steps

Deploy a pipeline with > 50 assets.

```ts
    for (let i = 0; i < 32; i++) {
      const websiteBucket = new s3.Bucket(this, `WebsiteBucket${i}`, {
        websiteIndexDocument: 'index.html',
      });

      new s3deploy.BucketDeployment(this, `DeployWebsite${i}`, {
        sources: [s3deploy.Source.asset('./test-file-asset', { assetHash: `file-asset-${i}` })],
        destinationBucket: websiteBucket,
      });

      new ecr_assets.DockerImageAsset(this, `DockerAsset${i}`, {
        directory: './test-docker-asset',
        extraHash: `docker-asset-${i}`,
      });
    }
```

### Error Log

On deploy, the following error is hit:

`Pipeline stage 'Assets' has too many actions. There can only be up to 50 actions in a pipeline stage (Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidStageDeclarationException; Request ID: xxx)`

### Other

The approach will likely be to dynamically create new asset publishing stages to the pipeline when > 50 assets are created. This will require API support in CodePipelines, as currently stages can't be inserted, only added to the end of the pipeline.

--- 

This is :bug: Bug Report

**Comment by nonken** [comment]
I am running into this as well in a serverless setup since I use one asset per Lambda to keep function size minimal. 

Right now my workaround is to have a few lambdas handle several routes but I’d rather keep a 1:1 mapping.

**Comment by MousaZeidBaker** [comment]
This also limits CDK apps to have maximum 25 stacks since two actions (one prepare & one deploy) are created in the deploy stage for each stack. Our app have already reached this limit. One possible workaround to at least increase the limit to 50 stacks is to divide the prepare & deploy actions into different pipeline stages.

**Comment by seawatts** [comment]
@rix0rrr Is there a plan of how this will potentially be implemented yet? I'm coming pretty close to this limit, 48 assets, so if there is anyway I can help push this through that would be great!

**Comment by JFox** [comment]
@njlynch The same issue exists when a single stage has more than 50 actions as well, either by having more than 25 stacks (1 prepare action + 1 deploy action) or less stacks + manual approvals. Is there a plan to fix that limit as well?
