### ISSUE TITLE
[@aws-cdk/pipelines] Allow multiple build / install commands for SimpleSynthAction

### ISSUE THREAD

**Issue by timbaer** [aws/aws-cdk#9357]
I think the buildspec generation in the SimpleSynthAction can be improved. For cases where you need run additional build-commands (e.g. build lambda-sources before synth), it would be good to have a way to pass multiple install and build commands to the _SimpleSynthAction_. A good way would be to provide a string-array for parameter _SimpleSynthAction.buildCommand_ and _SimpleSynthAction.installCommand_.

Currently, I'm helping myself by concatenating all install/build commands as follows:

```
SimpleSynthAction.standardNpmSynth({
                sourceArtifact,
                cloudAssemblyArtifact,
                installCommand: 'npm ci --prefix ../lambda/create' +
                    '&& npm ci --prefix ../lambda/update' +
                    '&& npm ci',
                buildCommand: 'npm run build --prefix ../lambda/create' +
                    '&& npm run build --prefix ../lambda/update' +
                    '&& npm run build'
            }
```

### Use Case

As a cdk-pipeline user, I want to pass a list of build-commands / actions to the build action of a pipeline to run them one after another or in parallel.

### Proposed Solution

1. change parameter-type of _buildCommand_ and _installCommand_ from string to _Array<string>_

* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by asterikx** [comment]
Similar to #9021
