### ISSUE TITLE
[aws-eks] How do I deploy a docker image for a node group?

### ISSUE THREAD

**Issue by deathquin** [aws/aws-cdk#9362]
### The Question
How do I deploy a docker image for a node group?
I made a nodegroup using eks. But I looked it up because I wanted to distribute the docker image, but I don't know.
No way to distribute the image to the node group.
I wish you could share the information.
Thank you

### Environment

  - **CDK CLI Version:** 1.55.0
  - **Module Version:** 1.55.0
  - **Node.js Version:** 12.1
  - **OS:** 
  - **Language (Version):** 

### Other information

     const cluster = new eks.Cluster(this, 'cluster', {
            vpc,
            version: eks.KubernetesVersion.V1_17,
            mastersRole: eksRole,
            clusterName: 'eks-demo',
            defaultCapacity: 0,
            defaultCapacityType: eks.DefaultCapacityType.EC2,
            defaultCapacityInstance: new ec2.InstanceType("m5.large"),
            kubectlEnabled: true,
            role: eksRole,
        });

      new eks.Nodegroup(this, "nodegroup", {
            cluster,
            nodegroupName: "nodegroups",
            instanceType: new ec2.InstanceType('m5.large'),
            desiredSize: 2,
            minSize: 2,
            maxSize: 5,
            forceUpdate: true,
            diskSize: 30,
            subnets: {
                subnetType: ec2.SubnetType.PUBLIC
            },
            remoteAccess: {
                sshKeyName: 'dk_armiq',
                sourceSecurityGroups: [publicSG]
            },
            labels: {
                "nodegroups": "nodegroups",

            }
        });
      const sa = cluster.addServiceAccount('MyServiceAccount', {});

        cluster.addResource('mypod', {
            apiVersion: 'v1',
            kind: 'Pod',
            metadata: { name: 'mypod' },
            spec: {
                serviceAccountName: sa.serviceAccountName.split("/")[0],
                containers: [
                    {
                        name: 'main',
                        image: "aws-eks-example-another:latest",
                        ports: [{ containerPort: 5000 }],
                    }
                ]
            }
        });

**Comment by iliapolo** [comment]
@deathquin 

> How do I deploy a docker image for a node group?

What do you mean by that? Just deploy a container onto the cluster and specify an image? 

The code you provided should work.

What exactly is the problem you are experiencing?
