### ISSUE TITLE
[aws-apigateway]: Changing role used in api gateway resource is not triggering api gateway deployment 

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#9363]
### The Question
Hi,
I have a cdk stack with multiple resources.
One of the resources is API Gateway, which is private one and it has one resource which is invoking aws service i.e. Step function.
For this i have to provide a role which has policy of full access of step function.

Problem : **API Gateway  deployment is not getting triggered when new role is attached to api gateway resource** 

Description:
 When i supply role created in this stack to api gateway resource it is updating perfectly but it is not triggering api gateway deployment. I checked the stage deployment as well there is no recent history for this deployment.
This causes a false situation in which the role of resource looks like it changed in the AWS console, but actually it still not applying.  Deploying the api gateway manually in the AWS console solved it.

### Environment

  - **CDK CLI Version:**  1.47.0
  - **Module Version:** 1.54.0
  - **Node.js Version:** 12.18.0
  - **OS:**  Windows 10
  - **Language (Version):** TypeScript (3.9.5)

**Comment by devendra-kumar1** [comment]
@nija-at any update on this issue ?

**Comment by SomayaB** [comment]
@devendra-kumar1 Sorry for the late reply. Could you provide a code sample?

**Comment by devendra-kumar1** [comment]
Hi @SomayaB ,
  Actually my query is like this.
I create an api gateway with a resource which will call an AWS resource i.e. step function. In order to start step function I have to provide an execution role. So first time i gave role **XYZ**. But at later point of time i came to know this is wrong role. So i change role ARN in my code to **ABC** from **XYZ**. Then i tried to deploy to cdk code. After successfully deployment i checked using AWS console, change role **ABC** is correctly reflected in api resource. But when i go to stages and checked deployment history nothing has been changed. and it creates a false situation where changes has been reflected but not deployed.

**Comment by SomayaB** [comment]
Hi @devendra-kumar1, thanks for giving us more details. Is it possible to share an actual code sample, that would make it easier for us to assess the issue and try to reproduce it.

**Comment by devendra-kumar1** [comment]
@SomayaB : Will update you with sample code snippet in few days
