### ISSUE TITLE
[RDS] Implement grant functions for Cluster and Instance

### ISSUE THREAD

**Issue by BryanPan342** [aws/aws-cdk#9378]
Grant functions for easy policy creation.

### Use Case

Any AWS service/construct that wants to operate on RDS.

### Proposed Solution

```ts
const role = new iam.Role(...);
const cluster = new rds.DatabaseCluster(...);
cluster.grantRead(role);
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
revisit this pr #9258 and change policy generation for rds cluster to a grant

**Comment by njlynch** [comment]
The proposed `grantRead()` methods and the RDS Data API associated are specific to RDS Aurora Serverless clusters, which is currently pending support (#929). I would propose this is either delivered as part of #929 (making this redundant) or handled after the initial delivery of Serverless support.

For what it's worth, I think the naive initial implementation is this:
```ts
  /**
   * Permits an IAM principal all rds-data operations.
   * Note that the RDS Data API does not support specifying a resource ARN in the policy statement,
   * so the statement will grant read operations on all RDS Data APIs ('*').
   *
   * See https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonrdsdataapi.html
   */
  public grantRead(grantee: iam.IGrantable): iam.Grant {
    return iam.Grant.addToPrincipal({
      grantee,
      actions: [
        'rds-data:BatchExecuteStatement',
        'rds-data:BeginTransaction',
        'rds-data:CommitTransaction',
        'rds-data:ExecuteStatement',
        'rds-data:RollbackTransaction',
      ],
      resourceArns: ['*'],
      scope: this,
    });
  }
```

However, it's worth noting that there is also a managed policy -- `AmazonRDSDataFullAccess ` -- which grants permissions in the `dbqms` namespace, as well as secretsmanager access for the RDS credentials. See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/query-editor.html#query-editor.access for this policy inlined in the docs. The SecretsManager aspect is the most interesting there, as the design of the serverless support will dictate if & how that secret is available to the `grantRead` method.

Tagging @shivlaks , who's working on Serverless support, for comment.
