### ISSUE TITLE
[aws-rds] L2 construct for Aurora Serverless

### ISSUE THREAD

**Issue by asterikx** [aws/aws-cdk#9381]
Add an L2 construct for Aurora Serverless.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
@asterikx thanks for opening the issue, but we already have one for this matter: #929

Please add your +1 there!

**Comment by asterikx** [comment]
@skinny85 Sorry for the dup. I already gave a +1 a while ago, but I just couldn't find it again 😂

**Comment by skinny85** [comment]
No worries, it's all good 😃
