### ISSUE TITLE
[aws-eks] Use NodeGroup as Loadblanacer Tagert 

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#9388]
It would be nice to be able to use `NodeGroup` resources as loadbalancer targets in the listeners. 

### Use Case
We have an EKS cluster + a Loadbalancer (not an ingress, but as an AWS resource maintained by the same stack). We create an AutoScalingGroup and use it as the target for the loadbalancer. The AutoScalingGroup is added to the cluster as well. (The architecture is similar to [this](https://quip-amazon.com/blob/bGA9AAmviCK/11tDfN7IqiC8qv7bZS50qw?a=Uf6IToPAN5W87b0DphRwhQxMafnFU1WYA0ya6pLXR0Ua)).
Among the above, creating the AutoScalingGroup should not be needed, since having a NodeGroup does the job. Having this feature makes the stack a lot cleaner.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ranjanashish** [comment]
For the time being, is there any workaround for this? Say, if we can get a handle to the underlying AutoScalingGroup, and then, add that as a target (I did give this a shot but reached nowhere 🙈).

P.S. Thank you for this project. It's a joy to use CDK.

**Comment by akefirad** [comment]
Bump.
