### ISSUE TITLE
[contributing.md] awslint link broken

### ISSUE THREAD

**Issue by ReidWeb** [aws/aws-cdk#9394]
[`CONTRIBUTING.MD` guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).

The contributing guide talks about `awslint`, but the [awslint README link](https://github.com/aws/aws-cdk/blob/master/tools/awslint/README.md) to it is a broken link, unsure as to where it should go.

---

This is a 📕 documentation issue

**Comment by Chriscbr** [comment]
Good catch, it looks like this link wasn't updated when the awslint package was published as an external module in https://github.com/aws/aws-cdk/pull/8558 - the correct file you're looking for is [here](https://github.com/aws/aws-cdk/blob/master/packages/awslint/README.md). 🙂
