### ISSUE TITLE
[rds]  rds proxy only works with certain version, check at compile time

### ISSUE THREAD

**Issue by jonny-rimek** [aws/aws-cdk#9396]
The RDS Proxy only supports certain versions of Postgres and Mysql and their Aurora version.

`The MySQL engine family includes RDS MySQL 5.6 and 5.7, and Aurora MySQL versions 1 and 2.`

`The RDS PostgreSQL engine family includes version 10.10 and higher minor versions and version 11.5 and higher minor versions. `

Those versions should be checked in CDK before pushing it to cloudformation and get an error while creating/updating the stack.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by civilizeddev** [comment]
> [Limitations for RDS Proxy](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html#rds-proxy.limitations)
