### ISSUE TITLE
[init-template-ts] Enable tsconfig's `forceConsistentCasingInFileNames` option

### ISSUE THREAD

**Issue by sisisin** [aws/aws-cdk#9399]
TypeScript can detect inconsistently-cased references by `forceConsistentCasingInFileNames` option.
This helps less mistake development using case insensitive filesystem(e.g. macOS,Windows).

### Proposed Solution

https://github.com/aws/aws-cdk/pull/9387

### Other

* [ ] :wave: I may be able to implement this feature request
  * I can't pass `yarn integ-init` on master branch ( https://github.com/aws/aws-cdk/pull/9387#issuecomment-667551110 )
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@sisisin what's the issue you ran into when trying to run `yarn integ-init` on GitPod?

**Comment by sisisin** [comment]
@shivlaks thank you for your reply
I tried following steps

- open GitPod from [CONTRIBUTING.md#Gitpod](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#gitpod)
- cd to repository root and run `yarn build`
- failed on `check-prerequisites.sh`  with following error

```bash
Checking if docker is running... Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

- I found skip options and run `yarn build --skip-prereqs --skip-test` ,then passed build.
- run `yarn pack` and passed, but didn't create `dist` directory.
- run `./pack.sh` directly, failed on `pack.sh` with following error.

```bash
[INFO] aggregatepom 1.0.0 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:12 min
[INFO] Finished at: 2020-08-08T12:34:30Z
[INFO] ------------------------------------------------------------------------
[ERROR] GC overhead limit exceeded -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError


    at ChildProcess.child.once (/workspace/aws-cdk/node_modules/jsii-pacmak/lib/util.js:57:31)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

I gave up to run `yarn integ-init` and create this issue...
