### ISSUE TITLE
[aws-appsync] mapping template AWS Cognito Id as partition key

### ISSUE THREAD

**Issue by owenashurst** [aws/aws-cdk#9401]
### The Question
When creating a GraphQL data resolver, I'm not sure how to add '$ctx.identity.sub' as the partition key.

### Environment

  - **CDK CLI Version:** 1.56.0
  - **Module Version:** @aws-cdk/aws-appsync - 1.56.0
  - **Node.js Version:** 12.16.1
  - **OS:** All
  - **Language (Version):** TypeScript (3.8.3)

### Other information
Let's say I have the following resolver;

```
customerDataResolver.createResolver({
            typeName: 'Customer',
            fieldName: 'id',
            requestMappingTemplate: MappingTemplate.dynamoDbPutItem(PrimaryKey.partition('id').auto(), Values.projecting('Customer')),
            responseMappingTemplate: MappingTemplate.dynamoDbResultItem()
});
```

The resolver here is going to automatically generate an id for me for the partition key, however I would like to pass in the cognito identity sub property (which is the cognito user id) instead.

If I was to use the console and use JSON, I know I'd do something like;

```
"key" : {
        "id": $ctx.identity.sub
 },
```

This was given to me from a support agent through AWS technical support.

Does anyone have any idea how one could implement this?

Thanks,
Owen

**Comment by BryanPan342** [comment]
@owenashurst I dont believe AppSync has that functionality available in our MappinTemplates class.

What I would recommend is to use the `MappingTemplate.fromString` static function to accomplish your use case.

```ts
const api = appsync.GraphQLApi( // definition);
api.createResolver ({
  typeName: 'Customer',
  fieldName: 'id',
  requestMappingTemplate: appsync.MappingTemplate.fromString(`{
    "version": "2017-02-28",
    "operation": "id",
    "key": {
        "id": $ctx.identity.sub
     },
  }`),
  responseMappingTemplate: MappingTemplate.dynamoDbResultItem(),
});
```

**Comment by hmngwy** [comment]
@BryanPan342 is this by design or is this something that will be added in the future?
