### ISSUE TITLE
[@aws-cdk/pipelines] Error during CDK synth: 'Stage ... must have at least one action'

### ISSUE THREAD

**Issue by 404-** [aws/aws-cdk#9402]
Build tool: SBT 1.3.10
CDK version: 1.55.0

Goal: CI/CD CodeCommit Pipeline for an extremely simple Lambda Function with `java11` runtime (source in S3).

Based on my understanding of the (lack of) info in the [blog post] and [official docs], `CdkPipeline`'s `synthAction` for non-toy languages like TypeScript has to be `CodeBuildAction`. Which is fine, since I have a working vanilla CodeCommit Pipeline (from `@aws-cdk/aws-codepipeline`). However, what's entirely unclear is what I'm supposed to do in order to properly add an app stage to the new `CdkPipeline`. Simply calling `addApplicationStage` results in the following error during `cdk synth`: `Stage 'AppStage' must have at least one action`

```
...
at App.synth (C:\some_path\jsii-kernel-UzXcZQ\node_modules\@aws-cdk\core\lib\stage.js:72:41)
...
[error]         at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:119)
[error]         at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:91)
[error]         at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:183)
[error]         at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:120)
[error]         at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:106)
[error]         at software.amazon.awscdk.core.Stage.synth(Stage.java:95)
...
```

Do I need to manually add [DeployCdkStackAction] to the instance of `CdkStage` returned from `CdkPipeline#addApplicationStage`? If so, how do I configure it to point at the Lambda Function's ZIPped sources in S3? Currently, in the vanilla CodeCommit `Pipeline` I have a stage with an instance of `CloudFormationCreateUpdateStackAction` where I configure the `Code` with `parameterOverrides(code.assign(synthesizedApp.getS3Location))`. How is this supposed to work in the `CdkPipeline`?

[blog post]: https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/
[official docs]: https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html
[DeployCdkStackAction]: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.DeployCdkStackAction.html

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Hi 404. 

First off, can I please ask that you don't insult other programming languages (or implicitly, the communities of people associated with them). We'd like our community to be welcoming to people of all creeds and preferences, and an off-hand derogatory remark like "toy language" has no place in that.

Second, I understand you're probably frustrated by the lack of examples currently available for CDK Pipelines. Honestly, between languages the only thing that should really be different is the Synth step. You need a CodeBuild project that compiles your Java program, installs the CDK CLI and then runs `cdk synth`, thereby producing a `cdk.out` directory. Then that `cdk.out` directory needs to be output into the CodePipeline Artifact that is passed as `cloudAssemblyArtifact` to the pipeline.

If `addApplicationStage()` is failing with this error, that probably means the `Stage` object you gave it does not contain any `Stack` objects. I will add a check and a more descriptive error message for that case.

You do not need to instantiate `DeployCdkStackAction` directly -- it will be done for you in `addApplicationStage()`.

CDK Pipelines is currently targeted to work with Lambda Assets that are built using `lambda.Code.fromAsset('../lambda')`. If your source is different (I'm guessing a separate CodeBuild project?) it might need some more doing. `DeployCdkStackAction` currently does not support parameters, so what you're trying to do might not be feasible at the moment.

**Comment by rix0rrr** [comment]
I think the actionable items have been extracted into separate issues. Closing this.
