### ISSUE TITLE
ELBv2+ECS: having to specify an extraneous TargetGroup port is endlessly confusing

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9404]
When creating a load balancer, listener and then assigning targets you need to specify the listener port/protocol multiple times. An example is below to better illustrate this. According to the docs this is intentional? As you can see at the below docs, either `port` or `protocol` must be specified, not on the parent listener but in the `addTargets` call as well

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.AddApplicationTargetsProps.html

### Reproduction Steps

From the ECS documentation:

```typescript
import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2';

const service = new ecs.FargateService(this, 'Service', { /* ... */ });

const lb = new elbv2.ApplicationLoadBalancer(this, 'LB', { vpc, internetFacing: true });
const listener = lb.addListener('Listener', { port: 80 });
const targetGroup1 = listener.addTargets('ECS1', {
  port: 80,
  targets: [service]
});
const targetGroup2 = listener.addTargets('ECS2', {
  port: 80,
  targets: [service.loadBalancerTarget({
    containerName: 'MyContainer',
    containerPort: 8080
  })]
});
```

As you can see, port 80 is defined on the listener, and then it is required yet again when calling `.addTargets` on that same listener. This should be inherited from the listener, at least by default as what you would expect when adding a target is that it uses a valid port.

### Error Log

```

/codebuild/output/src989833227/src/cdk/node_modules/.pnpm/@aws-cdk/core@1.55.0/node_modules/@aws-cdk/core/lib/private/synthesis.ts:118
    throw new Error(`Validation failed with the following errors:\n  ${errorList}`);
          ^
Error: Validation failed with the following errors:
  [LabConsoleStack/LabConsoleAdminLB/defaultAdminListener/labConsoleAdminTargetGroup] At least one of 'port' or 'protocol' is required for a non-Lambda TargetGroup
    at validateTree (/codebuild/output/src989833227/src/cdk/node_modules/.pnpm/@aws-cdk/core@1.55.0/node_modules/@aws-cdk/core/lib/private/synthesis.ts:118:11)
    at Object.synthesize (/codebuild/output/src989833227/src/cdk/node_modules/.pnpm/@aws-cdk/core@1.55.0/node_modules/@aws-cdk/core/lib/private/synthesis.ts:21:5)
    at App.synth (/codebuild/output/src989833227/src/cdk/node_modules/.pnpm/@aws-cdk/core@1.55.0/node_modules/@aws-cdk/core/lib/stage.ts:168:23)
    at process.<anonymous> (/codebuild/output/src989833227/src/cdk/node_modules/.pnpm/@aws-cdk/core@1.55.0/node_modules/@aws-cdk/core/lib/app.ts:112:45)
    at Object.onceWrapper (events.js:422:26)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:482:12)
    at process.emit (/codebuild/output/src989833227/src/cdk/node_modules/.pnpm/source-map-support@0.5.19/node_modules/source-map-support/source-map-support.js:495:21)
    at process.topLevelDomainCallback (domain.js:137:15)
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/codebuild/output/src989833227/src/cdk/node_modules/.pnpm/aws-cdk@1.55.0/node_modules/aws-cdk/lib/api/cxapp/exec.ts:118:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
·ERROR· Command failed with exit code 1.
```

### Environment

  - **CLI Version:** 1.56.0 (build c1c174d)
  - **Framework Version:** 1.56.0 (build c1c174d)
  - **Node.js Version:** v12.13.1
  - **OS:** MacOS 10.15
  - **Language (Version):** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
They're not the same port. One is the port that the listener listens on, the other is the port that the instances listen on.

It's confusing in an ECS context because ECS services register themselves into a load balancer on startup with a dynamic port number, so even though you're required to pass a port when initializing the target group, that port number is ignored.

I guess we need to do something about this because I've seen this question a number of times already.

**Comment by justin8** [comment]
What about the example for `targetGroup2` above? It has 3 ports:

```
const listener = lb.addListener('Listener', { port: 80 });
...
const targetGroup2 = listener.addTargets('ECS2', {
  port: 80,
  targets: [service.loadBalancerTarget({
    containerName: 'MyContainer',
    containerPort: 8080
  })]
});
```

Where there is a listener port, a target port *and* a container port. When in reality this would be the "port" on the container that will be mapped to a random port on the host, and the listener's port on the ALB itself. Yet here we have a third port still.

**Comment by MMOSimca** [comment]
I also spent a decent amount of time confused by this recently.

I had it set to the same value as the containerPort at first, which does not work and results in weird errors.

**Comment by bearrito** [comment]
Two years on, problem remains. I spent a good hour, running around in a loop. 
Doesn't help that the docstrings/docs in V2 are out of date.

To confirm for people getting here from search:

If we want to have the ALB listen on say, 443, terminating SSL, but have the container listen on say 8081, then what port/protocl values in what constructs need to be set to what values?
