### ISSUE TITLE
[aws-cloudfront] Where does Australia locate in Cloudfront PriceClass?

### ISSUE THREAD

**Issue by ivawzh** [aws/aws-cdk#9405]
## Which `PriceClass` should I choose for Australia?

According to tsdoc

```ts
/**
 * The price class that corresponds with the maximum price that you want to pay for CloudFront service.
 * If you specify PriceClass_All, CloudFront responds to requests for your objects from all CloudFront edge locations.
 * If you specify a price class other than PriceClass_All, CloudFront serves your objects from the CloudFront edge location
 * that has the lowest latency among the edge locations in your price class.
 *
 * @default PriceClass.PRICE_CLASS_ALL
 */
readonly priceClass?: PriceClass;
```

and 

```ts
/** USA, Canada, Europe, & Israel */
PRICE_CLASS_100 = "PriceClass_100",
/** PRICE_CLASS_100 + South Africa, Kenya, Middle East, Japan, Singapore, South Korea, Taiwan, Hong Kong, & Philippines */
PRICE_CLASS_200 = "PriceClass_200",
```

Australia Sydney doesn't sit either in `PRICE_CLASS_100` nor `PRICE_CLASS_200`. 

And `PRICE_CLASS_ALL` means using every region than picking the region I specifically care which is Sydney.

I am assuming this is a mistake and Syndey actually sits in `PRICE_CLASS_200`?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 1.56.0
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):** TypeScript (3.8.3)

**Comment by iliapolo** [comment]
Hi @ivawzh - According to the table [here](https://aws.amazon.com/cloudfront/pricing/): 

![Screen Shot 2020-08-03 at 1 26 44 PM](https://user-images.githubusercontent.com/1428812/89173566-266cf000-d58d-11ea-8b44-c256c2f284f7.png)

Australia only exist in `PRICE_CLASS_ALL`. 

So the documentation is actually correct.  

I'm resolving the issue for now, let us know if you still feel something in unclear.
