### ISSUE TITLE
[@aws-cdk/aws-lambda-python] Support caching of built assets

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9406]
Currently when using the PythonFunction class you end up downloading all the files in `requirements.txt` every single time. We should be caching this to greatly improve build and dev experience in terms of deployment speed as well as iteration cycles.

### Use Case

* Not caching built artifacts that will often never change results in a terrible experience

### Proposed Solution

* I'm not sure what is handled for the cdk staging directory internally, but leaving the previously built assets before running the current `pip install` command would result in it not re-installing the existing matching libraries
* By moving off the installed libraries to a Lambda Layer we can update user-created code without re-uploading every single dependency each time, further improving deployment speeds.

### Other

This would probably apply to the NodeJS functions as well, looking at the code they seem to behave the same way here, but I haven't confirmed.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Related to #8882

**Comment by adamelmore** [comment]
@jogold let me know if I can be helpful here.
