### ISSUE TITLE
[cli] CDK bootstrap should allow an existing bucket to be used

### ISSUE THREAD

**Issue by ssg-cnc** [aws/aws-cdk#9408]
### The Question

How can I use an existing S3 bucket with CDK bootstrap?   The AWS environment provided by my company doesn't grant permissions to individuals to create S3 buckets. I work for a health care company that rightly fears an accidental exposure of PHI data, and so an S3 bucket can only be created using a Service Catalog product designed to create S3 buckets with encryption and no public access.  

### Environment

  - **CDK CLI Version:** 1.53
  - **Module Version:** 1.53
  - **Node.js Version:** 12.18
  - **OS:** macOS Mojave 10.14.6
  - **Language:** Javascript

### Other information

I've tried specifying a bucket with bootstrap option --bootstrap-bucket-name, but it returns an error message "already exists in stack" error message.  I now know that it is only used to name the bucket that bootstrap will create, but it would be great if I could use something like --bootstrap-existing-bucket so that I can specify an existing bucket.

**Comment by rix0rrr** [comment]
We're not going to offer options for this. Your best bet is to bootstrap yourself using the bootstrapping template that's in the CDK CLI (we don't make it easy yet to get at that, but you can fish it out of the source repository until we do) and deploy it by importing an existing S3 bucket.

**Comment by ssg-cnc** [comment]
I will say that I am a little disappointment.  However, I will take a look at "bootstrapping template" to see if that offers a good solution.  Thank you for your time on this.

**Comment by dgimmler** [comment]
Haven't tried this myself, but joseph-behrens provided another workaround using cloudformation stacks: https://github.com/aws/aws-cdk/issues/3684#issuecomment-586518441

**Comment by ssg-cnc** [comment]
I figured out how to do this using the following bootstrap-template.yaml:

Description: The CDK Toolkit Stack. It was created by `cdk bootstrap` and manages resources necessary for managing your Cloud Applications with AWS CDK.
Conditions:
  UsePublicAccessBlockConfiguration:
    Fn::Equals:
      - "true"
      - "true"
Parameters:
  FileAssetsBucketName:
    Description: The name of the S3 bucket used for file assets
    Default: /cdk/bootstrap/BucketName
    Type: AWS::SSM::Parameter::Value<String>
  FileAssetsBucketDomainName:
    Description: The name of the S3 bucket Regional Domain name used for file assets
    Default: /cdk/bootstrap/BucketDomainName
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  CdkBootstrapVersion:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub: /cdk-bootstrap/version
      Value: 4

Outputs:
  BucketName:
    Description: The name of the S3 bucket owned by the CDK toolkit stack
    Value:
      Ref: FileAssetsBucketName
  BucketDomainName:
    Description: The domain name of the S3 bucket owned by the CDK toolkit stack
    Value:
      Ref: FileAssetsBucketDomainName

The two parameters come from AWS Parameter Store and contain the name of the bucket and Regional domain name.  You can either manually add the two parameters by hand or create another CDK to deploy the two parameters.  Set these two values to point to an existing S3 bucket, and then execute the following command line:

> aws cloudformation create-stack --stack-name CDKToolkit --region us-east-1 --template-body file://bootstrap-template.yaml

Then, make sure to pass in the toolkit stack name, CDKToolkit, into every CDK deploy command (example):

cdk deploy --toolkit-stack-same CDKToolkit -a "node bin/app.js"
