### ISSUE TITLE
bundling - multiple docker image builds

### ISSUE THREAD

**Issue by jarikujansuu** [aws/aws-cdk#9424]
When use same Lambda for multiple places CDK builds same docker image for each case. 

### Use Case

We have 2 Custom Resources that are used in multiple places. So when doing synth for some stack there are 26 or so docker image builds happening for those Lambdas. We have devs, staging and production so for each place it is used image is built 3 times (not all services have all environments so not 3 * 2 * n)

When I tried to cache created Code objects that are generated only with input of path and runtime I get errors about cross stack referencing.

### Proposed Solution

Build docker image only once per runtime & path combination. Also wouldn't mind if synth for one stack wouldn't build everything for all stacks.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
@eladb - sending your way since this looks related to the new ability to bundle assets. 
cc @jogold

**Comment by jogold** [comment]
We need to cache during `synth` based on the inputs

**Comment by maoosi** [comment]
I do have an app with multiple stacks and I am facing a similar issue when bundling Lambda functions with the NodejsFunction class.

Even though the functions are only used in one of the stacks, the assets bundling is still happening multiple times during a single deploy (number of NodejsFunction X number of stacks). I do have 11 stacks and 3 functions, so this is quite impacting.

**Comment by eladb** [comment]
@jogold yes we can probably avoid multiple builds if the exact same input is used. Wondering though why isn't docker doing that for us?

**Comment by jogold** [comment]
> Wondering though why isn't docker doing that for us?

Because we are `run`ning multiple times not `build`ing multiple times.

**Comment by jogold** [comment]
Requires #9576
