### ISSUE TITLE
[RDS] Set "engine" props with a specific version - Now in rds.IEngine & rds.IClusterEngine type

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#9427]
## The Question
Since 1.52.0 CDK version, for example in :
- rds.ParameterGroup
- rds.OptionGroup
- rds.DatabaseCluster
- rds.DatabaseInstance

The property engineVersion in `I*Engine` changed from a string to EngineVersion.
But now, how to define a specific version  for each ?

In my case, I'm creating Parameter & Option Groups before DB (Cluster & Instance) and set them after in DB constructs.
I don't want to create these groups after DB (and in that case I have to create multiple groups, no ?).

Can't set the version, the **(property) rds.ParameterGroupProps.engine: rds.IEngine** for example.

Any advice will be apreciated :)

### Environment

  - **CDK CLI Version: 1.56.0** 

### Other information

```ts
    const RdsParameterGroupMySQL57 = new rds.ParameterGroup(this, 'RdsParameterGroupMySQL57', {
      engine: rds.DatabaseClusterEngine.AURORA_MYSQL,   // How to set a specific version now before creating my DB ?
      description: 'Parameter Group for aurora-mysql5.7',
      parameters: {
      ...
      }
    });

[...]

    const RdsOptionGroupOracleSe2 = new rds.OptionGroup(this, 'RdsOptionGroupOracleSe2', {
      configurations: [
      engine: rds.DatabaseInstanceEngine.ORACLE_SE2,   // How to set a specific version now before creating my DB ?
      description: 'Option Group for oracle-se2-12.2'
    });

[...]

    const DatabaseClusterFinance = new rds.DatabaseCluster(this, 'DatabaseClusterFinance', {
      clusterIdentifier: RdsClusterFinanceName,
      engine: rds.DatabaseClusterEngine.AURORA_MYSQL,   // How to set a specific version
      ...
      parameterGroup: RdsParameterGroupMySQL57
    });
```

**Comment by skinny85** [comment]
Hey @Cloudrage ,

the way to do that is to use the static factory methods in the `DatabaseClusterEngine` / `DatabaseInstanceEngine` classes, like this:

```ts
    const myEngine = rds.DatabaseClusterEngine.auroraMysql({
      version: rds.AuroraMysqlEngineVersion.VER_2_08_1,
    });
    const RdsParameterGroupMySQL57 = new rds.ParameterGroup(this, 'RdsParameterGroupMySQL57', {
      engine: myEngine,
      description: 'Parameter Group for aurora-mysql5.7',
      parameters: {
        ...
      },
    });
    const DatabaseClusterFinance = new rds.DatabaseCluster(this, 'DatabaseClusterFinance', {
      clusterIdentifier: RdsClusterFinanceName,
      engine: myEngine,
      ...
      parameterGroup: RdsParameterGroupMySQL57
    });
```

And for Instance:

```ts
    const RdsOptionGroupOracleSe2 = new rds.OptionGroup(this, 'RdsOptionGroupOracleSe2', {
      configurations: [
      engine: rds.DatabaseInstanceEngine.oracleSe2({
        version: OracleEngineVersion.VER_19,
      description: 'Option Group for oracle-se2-12.2'
    });
```

This is shown in [our documentation](https://github.com/aws/aws-cdk/blob/b1b9d23f442b674df97c1aadb4f84cc0251bb826/packages/@aws-cdk/aws-rds/README.md#starting-a-clustered-database).

Thanks,
Adam

**Comment by Cloudrage** [comment]
Hi @skinny85 ,

Thanks for your reply.
Sorry about that !
I staid on the _AURORA_MYSQL_ API element "deprecated" :/

I don't have seen the new _rds.DatabaseClusterEngine.**auroraMysql**_ method ^^

In that case I've been able to update the code.
But ! @ll my Clusters Aurora have been replaced... Even if the version & configuration was the same : 
```
[~] AWS::RDS::DBCluster DatabaseClusterNomade DatabaseClusterNomadeFBBA5597 replace
 └─ [+] EngineVersion (requires replacement)
     └─ 5.7.12
```
I was already in 5.7.12...

**Comment by skinny85** [comment]
Have you seen the deprecation message? 🙂

If you're not using a specific major version for your Cluster, keep using the `DatabaseClusterEngine. AURORA_MYSQL` field. It's deprecated, because we feel it's a bad practice, but if you already have an existing Cluster with it, feel free to continue using it.

**Comment by Cloudrage** [comment]
Yep but the pb was not here, but the change **from a string to EngineVersion** of **engine** prop :) 
No choice about that, breaking changes ^^

Anyway, many thanks for your help !

**Comment by skinny85** [comment]
No problem, got it's all working now 🙂
