### ISSUE TITLE
[aws-codepipeline-actions] S3 Source Action's autogenerated role is not exposed

### ISSUE THREAD

**Issue by jonathanmorley** [aws/aws-cdk#9429]
sourceAction.actionProperties.role

### Reproduction Steps

```ts
const sourceAction = new S3SourceAction({
      actionName: 'Source',
      bucket: new Bucket(this, 'Bucket', {...}),
      bucketKey: Bar,
      output: new codepipeline.Artifact(),
      /*role: new Role(this, 'SourceRole', {
        assumedBy: new ServicePrincipal('codepipeline.amazonaws.com')
      })*/
    });

console.log(sourceAction.actionProperties.role);
```

### What did you expect to happen?

I expected a Role to be logged to the console

I would like to grant a permission to the source action's role (to decrypt with a KMS key)

### What actually happened?

`undefined` is logged to the console (unless a role is provided, see comment in repro steps).
Note: the commented section does not successfully deploy, but does successfully synth.

### Environment

  - **CLI Version      :** 1.56
  - **Framework Version:** 1.56
  - **Node.js Version:** 
  - **OS               :** macos
  - **Language (Version):**  typescript 3.7.2

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @jonathanmorley ,

thanks for opening the issue. Yes, the default automatically-generated Role is not exposed on the Action (mainly because the same Action could be added to multiple CodePipelines, each of which would have its own auto-generated Role).

Try this instead:

```ts
    const role = new Role(this, 'SourceRole', {
      assumedBy: new iam.AccountRootPrincipal(),
    });
    const sourceAction = new S3SourceAction({
      actionName: 'Source',
      bucket: new Bucket(this, 'Bucket', {...}),
      bucketKey: Bar,
      output: new codepipeline.Artifact(),
      role: role,
    });
```

And modify `role` however you please from there.

Let me know if this helps!

Thanks,
Adam
