### ISSUE TITLE
[aws-cloudfront] Add ability to set aliases on cloudfront.Distribution

### ISSUE THREAD

**Issue by corymhall** [aws/aws-cdk#9430]
The new Distribution construct should allow you to add aliases. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-aliases. 

### Use Case

Aliases are required if you want to use custom domain names (i.e. example.com) instead of the default cloudfront URL. 
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html

### Proposed Solution

This could be handled similar to the CloudFrontWebDistribution construct which requires a ViewerCertificate construct property. https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.ViewerCertificate.html

### Other

Currently I am using an escape hatch as a workaround.

```ts
const cfnDistro = distribution.node.tryFindChild('CFDistribution') as cloudfront.CfnDistribution;
cfnDistro.addPropertyOverride('DistributionConfig.Aliases', ['example.com']);
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by lanwen** [comment]
`distribution.node.tryFindChild('CFDistribution') as cloudfront.CfnDistribution;` doesn't work in 1.59 anymore - `Cannot read property 'addPropertyOverride' of undefined`

but now defaultChild works fine `const cfnDistro = distribution.node.defaultChild as cloudfront.CfnDistribution;`

**Comment by njlynch** [comment]
This was handled as part of #9699 .

**Comment by iDVB** [comment]
@njlynch Can you give a bit more detail how exactly how this has been handled as part of that issue? I read the issue and still not very clear what we are supposed to do to add an alias?

**Comment by njlynch** [comment]
@iDVB - See the example in [the docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront-readme.html):

```
new cloudfront.Distribution(this, 'myDist', {
  defaultBehavior: { origin: new origins.S3Origin(myBucket) },
  domainNames: ['www.example.com'],
  certificate: myCertificate,
});
```

The `domainNames` property is what functions as the alias.

**Comment by proxy-hatch** [comment]
I'm not sure why its not working for me. 
```typescript
const distribution = new Distribution(this, 'StaticContentDistribution', {
            defaultBehavior: {
                origin: new S3Origin(staticContentBucket, {
                    originAccessIdentity: originAccessIdentity,
                }),
                allowedMethods: AllowedMethods.ALLOW_GET_HEAD_OPTIONS
            },
            logBucket: cloudFrontLogBucket,
            enableIpv6: true,
            ...stage !== STAGE.ALPHA && {
                domainNames: [ `static.${hostedZone!.zoneName}` ],
                certificate: props.cloudFrontCertificate!,
            }
        });
```

Examining the Route53 Hosted Zone, I don't see any static subdomain alias records created (or any records for this subdomain). Is there restriction on the certificate matching the domain? My certificate is issued on `*.HOSTED_ZONE_DOMAIN`
