### ISSUE TITLE
[core] CfnMapping creates wrong mappings

### ISSUE THREAD

**Issue by beomseoklee** [aws/aws-cdk#9432]
[CfnMapping](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnMapping.html) creates wrong CFN mappings. It should not add ```Mappings``` twice.

Please let me know if any other information is needed or I did something wrong.

### Reproduction Steps

```javascript
import * as cdk from '@aws-cdk/core';

export class CDKStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    new cdk.CfnMapping(this, 'Mappings', {
      mapping: {
        Map: {
          This: {
            One: 'Yes'
          }
        }
      }
    });
  }
}
```

With that code, when I ```cdk synth --asset-metadata false --path-metadata false --version-reporting false --json true```, it created wrong mappings.

### What did you expect to happen?

```json
{
  "Mappings": {
    "Map": {
      "This": {
        "One": "Yes"
      }
    }
  }
}
```

### What actually happened?

```json
{
  "Mappings": {
    "Mappings": {
      "Map": {
        "This": {
          "One": "Yes"
        }
      }
    }
  }
}
```
### Environment

  - **CLI Version      :** 1.54.0
  - **Framework Version:** 1.54.0
  - **Node.js Version:** 12.13.1
  - **OS               :** OSX Mojave
  - **Language (Version):** TypeScript (3.9.6) 

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Each `CfnMapping` (singular) object represents a single entry in your template's `Mappings` section (plural). This way, you can define multiple mappings by simply creating multiple instances of `CfnMapping`.

The `id` of the `CfnMapping` construct will be used as the ID of the mapping. 

```ts
import * as cdk from '@aws-cdk/core';

export class CDKStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new cdk.CfnMapping(this, 'Map1', {
      mapping: {
        This: {
          One: 'Yes'
        }
      }
    });

    new cdk.CfnMapping(this, 'Map'2, {
      mapping: {
        Hello: 'world'
      }
    });
  }
}
```

Will yield:

```json
{
  "Mappings": {
    "Map1": {
      "This": {
        "One": "Yes"
      }
    },
    "Map2": {
      "Hello": "World"
    }
  }
}
```

I've created a PR to update the docs to make it a bit clearer: https://github.com/aws/aws-cdk/pull/9451
