### ISSUE TITLE
[ecs-patterns] ApplicationLoadBalancedEc2Service missing option to control ingress of security group

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#9433]
The `ApplicationLoadBalancedEc2Service` is missing the ability to lock-down the ingress of the ALB listener that it creates. The listener is created, by default, to be fully open to ingress from all IP addresses. There is a design but in that it does not expose any option that allows the user to lock-down this security group to allow no-ingress except the ingress that is explicitly allowed.

Note: This was found during a security audit and has security implications. It is a high-priority fix.

### Reproduction Steps

Create a `ApplicationLoadBalancedEc2Service` 

### What did you expect to happen?

The expectation was that it would be possible to control ingress to the ALB created by `ApplicationLoadBalancedEc2Service` via the security group of the listener.

### What actually happened?

The security group of the listener is wide-open by default; it may as well not even have a security group.

### Environment

  - **CLI Version      :** 1.52.0
  - **Framework Version:** 1.52.0
  - **Node.js Version:** Any
  - **OS               :** Any
  - **Language (Version):** all

### Other

I have a PR ready to fix this, and will be submitting shortly.

--- 

This is :bug: Bug Report

**Comment by flemjame-at-amazon** [comment]
Also fixes #8342
