### ISSUE TITLE
[lambda] lambda.Runtime.GO_1_X.bundlingDockerImage doesn't exist

### ISSUE THREAD

**Issue by corymhall** [aws/aws-cdk#9435]
The Golang bundlingDockerImage was recently updated to use a new docker image. It looks like there are no images in the  dockerhub repository though.

amazon/aws-sam-cli-build-image-go1.x:latest

https://hub.docker.com/r/amazon/aws-sam-cli-build-image-go1.x

### Reproduction Steps

Try and create a Golang lambda using bundling.

```ts
new lambda.Function(this, 'Function', {
  code: lambda.Code.fromAsset('path', {
    bundling: {
      image: lambda.Runtime.GO_1_X.bundlingDockerImage,
      command: [
        'bash', '-c', [
          `cd /asset-input`,
          `go build -o main`,
          `cp /asset-input/main /asset-output/`
        ].join(' && ')
      ],
      user: 'root',
    }
  }),
  runtime: lambda.Runtime.GO_1_X,
  handler: 'main',
};
```

Then when trying to deploy
```bash
Unable to find image 'amazon/aws-sam-cli-build-image-go1.x:latest' locally
docker: Error response from daemon: manifest for amazon/aws-sam-cli-build-image-go1.x:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

### What did you expect to happen?

Should be able to find the image.

### Environment

  - **CLI Version      :**1.56.0
  - **Framework Version:**
  - **Node.js Version:**  12.16.1
  - **OS               :** Ubuntu 18.04.3 LTS
  - **Language (Version):**  TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
It looks like there are no images in Dockerhub tagged 'latest' for Go and Dotnetcore.

@iph - do you happen to know about this? Is is just a delay?

**Comment by aripalo** [comment]
Oh nice, just found this feature myself. Can't wait for #9465 to land 😅 👍

**Comment by joekendal** [comment]
It is better to use ECR so that you don't get random rate limits by DockerHub. We had this recently where we couldn't deploy anything. The solution is to just reference the ECR public mirror like so:
```ts
new lambda.Function(this, 'Function', {
  code: lambda.Code.fromAsset('path', {
    bundling: {
      image: cdk.DockerImage.from_registry("public.ecr.aws/sam/build-go1.x:latest"),
      command: [
        'bash', '-c', [
          `cd /asset-input`,
          `go build -o main`,
          `cp /asset-input/main /asset-output/`
        ].join(' && ')
      ],
      user: 'root',
    }
  }),
  runtime: lambda.Runtime.GO_1_X,
  handler: 'main',
};
```

**Comment by SamuelCabralCruz** [comment]
@joekendal I recently faced rate limiting issue in my CI job and tried out your approach but then realized that `lambda.Runtime.GO_1_X.bundlingImage` actually point on aws public ecr by default. at the moment, the best solution I found was to use a [github action](https://github.com/satackey/action-docker-layer-caching) for caching docker level images.
