### ISSUE TITLE
[cdk-pipelines] fails to deploy

### ISSUE THREAD

**Issue by mainframenzo** [aws/aws-cdk#9436]
I have followed [this blog post](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/) and created an updated version of that code [here](https://github.com/mainframenzo/cdk-test) to work with CDK version 1.56.0. I've bootstrapped and can get simple stacks to deploy with the CDK (I haven't included those in the linked repo). My issues seem to be with CdkPipeline itself:
1. I can not get the pipeline stack to deploy after running `npm run build && cdk deploy CdkpipelinesDemoPipelineStack` because the stack fails during creation: `CdkpipelinesDemoPipelineStack | ROLLBACK_IN_PROGRESS | The following resource(s) failed to create: [Pipeline9850B417]. . Rollback requested by user.`
1. There is no insight available to me for debugging what is happening other than CloudFormation events, which are not proving useful, since the reason seems to be: `2020-08-04 12:07:02 UTC-0700 | Pipeline9850B417 | CREATE_FAILED | Internal Failure`. There are no other failures listed during attempted creation, so CdkPipeline seems to be the primary reason.

Am I doing something wrong? I would also like to request better information be relayed to the customer. Thanks!

**Comment by rix0rrr** [comment]
See the [@aws-cdk/pipelines documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#troubleshooting)
