### ISSUE TITLE
[aws-codedeploy] (design): Allowing custom Lambda deployment configurations

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#9437]
### The problem
I want to create a deployment configuration that doesn't fit into the static configs that codedeploy has today, and the [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codedeploy.LambdaDeploymentConfig.html) say that we need a custom resource to create such configs programmatically. I think there's an opportunity to reduce load on developers who need a custom config by creating the custom resource for them, exposing an interface which is easier to use.

### Proposed solution
To reference a deployment config today we only need to reference the following:
```ts
const config = LambdaDeploymentConfig.LINEAR_10_PERCENT_EVERY_3_MINUTES;
```

I propose two static methods to create such deployment configs:

```ts
LambdaDeploymentConfig.Linear(_scope: Construct, _id: string, props: LinearLambdaDeploymentConfigProps): ILambdaDeploymentConfig
LambdaDeploymentConfig.Canary(_scope: Construct, _id: string, props: CanaryLambdaDeploymentConfigProps): ILambdaDeploymentConfig
```

### Example usages
```ts
const canaryConfig = LambdaDeploymentConfig.Canary(stack, 'MyCanary', {
  name: 'Canary25Percent45Minutes',
  percentage: 25,
  interval: 45
});
```

```ts
const linearconfig = LambdaDeploymentConfig.Linear(stack, 'MyLinear', {
  name: 'Linear5Percent10Minutes',
  percentage: 5,
  interval: 10
});
```

Behind the scenes, the implementation would be an AwsCustomResource to make the API calls necessary -- examples can be found [here](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations-create.html).

**Comment by skinny85** [comment]
Hey @flemjame-at-amazon ,

thanks for opening the issue. But don't you think requiring a Lambda (for the custom resource) just to deploy your main Lambda is a little much?

I wonder if it's better to put pressure on CloudFormation to close this gap.

Thanks,
Adam

**Comment by flemjame-at-amazon** [comment]
@skinny85 

> Hey @flemjame-at-amazon ,
> But don't you think requiring a Lambda (for the custom resource) just to deploy your main Lambda is a little much?

I don't personally mind it, because it can be an abstraction to the CDK user. This is a prime use case for custom resources -- CFN is behind, and the CLI is able to solve the problem.

> I wonder if it's better to put pressure on CloudFormation to close this gap.

Absolutely they should support this, but my experience is that can take a long time. If this used a custom resource, it would still be functional even if CFN added official support.

We could design this functionality with the expectation that it may be deprecated in favor of something better in the future -- something like:
```ts
const canaryConfig = LambdaDeploymentConfig.CustomCanary(stack, 'MyCanary', {
  name: 'Canary25Percent45Minutes',
  percentage: 25,
  interval: 45
});
```

If CFN updates, we could release a new method and deprecate CustomCanary:
```ts
const canaryConfig = LambdaDeploymentConfig.Canary(stack, 'MyCanary', {
  name: 'Canary25Percent45Minutes',
  percentage: 25,
  interval: 45
});
```

**Comment by flemjame-at-amazon** [comment]
Additionally this would only need to be run once for an account, then the new deployment config would be cached.

**Comment by flemjame-at-amazon** [comment]
This is something I was planning on implementing myself -- I just need a design consultation.

**Comment by skinny85** [comment]
If you want to work on it, I think the best design in a new class that implements the `ILambdaDeploymentConfig` interface - `CustomLambdaDeploymentConfig` (probably with a `type` property whose type is en enum with 2 values, `LINEAR` and `CANARY`). In the implementation, it will create the Custom Resource needed for this to function.

**Comment by flemjame-at-amazon** [comment]
Blocked on https://github.com/aws/aws-cdk/pull/10012 for implementation, the resource deletion doesn't work if a CDK application has multiple custom resources.
