### ISSUE TITLE
[aws-lambda-event-sources] S3EventSource in NESTED stack causes "Cannot use tokens in construct ID"

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#9440]
Suppose you have a stack where you define a bucket.

That stack also has a NestedStack where that bucket is used for an S3 Event Source.

Then you will get this:

```/Users/sblackstone/code/xxxxxxx/stacks/node_modules/@aws-cdk/core/lib/construct-compat.js:34
            throw new Error(`Cannot use tokens in construct ID: ${id}`);            
```

I believe this is because the S3EventSource tries to use properties of the bucket in its id.

n.b. (I emphasized nested stack as there is a similar issue when shared between stacks that causes a circular depdency, this is a slightly different issue)

**Comment by nija-at** [comment]
Can you provide a code example?
