### ISSUE TITLE
[aws-appsync] add cloudWatchLogsRoleArn to GraphQLApiProps

### ISSUE THREAD

**Issue by octopi-jr** [aws/aws-cdk#9441]
In GraphQLApiProps, add the ability to set the `cloudWatchLogsRoleArn`

### Use Case

We need the ability to specify an existing role. 

### Proposed Solution

Currently, we need to use CfnGraphQLApiProps so we can use our specific role.

Possible solution is to update graphqlapi.ts. Instead of creating a Role in here, allow the developer to set it using a new `cloudWatchLogsRoleArn` property.

Existing code:
`
    let apiLogsRole;

    if (props.logConfig) {

      apiLogsRole = new Role(this, 'ApiLogsRole', {

        assumedBy: new ServicePrincipal('appsync'),

      });

      apiLogsRole.addManagedPolicy(

        ManagedPolicy.fromAwsManagedPolicyName(

          'service-role/AWSAppSyncPushToCloudWatchLogs',

        ),

      );

    }
`

**Comment by BryanPan342** [comment]
This looks like a good first issue to tackle for first time contributors!

- [ ] Expose role in `props.logConfig`
- [ ] in constructor add an if statement for `props.logConfig?.cloudwatchArn`
- [ ] in creation of `CfnGraphQLApi`, put the service arn here
- [ ] add unit tests to make sure that config happens as desired
