### ISSUE TITLE
[s3-assets] some fields in AssetOptions are deprecated, but is that intended?

### ISSUE THREAD

**Issue by acomagu** [aws/aws-cdk#9447]
The `exclude` and `follow` fields in [AssetOptions](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.AssetOptions.html) interface were marked deprecated, because of #7708. But the pull doesn't seem to have the intension to deprecate them. If not, they should be fixed.  

---

This is a 📕 documentation issue

**Comment by iliapolo** [comment]
@acomagu These properties are deprecated in favor of using the `core` library:

https://github.com/aws/aws-cdk/blob/938f326c14029687159e1b553d621d1418bf3d64/packages/%40aws-cdk/core/lib/fs/options.ts#L33-L49

This is intended, as `CopyOptions` from the `assets` module (which `AssetOptions` in `s3-assets` extend from) will be removed in future **major** versions.

**Comment by danielsharvey** [comment]
Should this be re-opened? The deprecation notice remains confusing...

**Comment by eladb** [comment]
I believe @skinny85 spent some time on this, right?

**Comment by mjwbenton** [comment]
Is there a plan for migrating other packages (e.g. aws-s3-deployment) that use aws-s3-assets right now to core? I don't think I can find an issue related to it.

Isn't it possible to make that step without it being a breaking change, and therefore side step the issue with the confusing deprecation notices?

**Comment by skinny85** [comment]
Here's the summary of the situation, and how we will change it:

1. Currently, the `AssetOptions` interface from the `@aws-cdk/aws-s3-assets` module extends the deprecated `CopyOptions` interface from the deprecated module `@aws-cdk/assets`.
2. We will add a new, non-deprecated interface `FileCopyOptions` to `@aws-cdk/core`. The above mentioned `AssetOptions` interface will now extend both `CopyOptions` and `FileCopyOptions`. This is done in PR #13356.
3. In V2, we will automatically strip all deprecated features from our code. Which means the old `CopyOptions` will be removed, and only the new `FileCopyOptions` will remain, thus getting rid of the confusing deprecations.

Hope this clears this up!

Thanks,
Adam

**Comment by mjwbenton** [comment]
Gotcha, thanks for the explanation.
