### ISSUE TITLE
Versioning Strategy

### ISSUE THREAD

**Issue by ColeMurray** [aws/aws-cdk#9448]
### The Question
Hello CDK Team,

I've looked through the repository and haven't seen any documentation around versioning of releases. It seems the releases are not following a semantic versioning pattern, as indicated by the ⚠ BREAKING CHANGES seen in the change log.

Can we update the documentation to better explain the versioning plan? After having a project broken due to upgrading a minor version, it's not clear what the versioning strategy is.

**Comment by Jerry-AWS** [comment]
In short, APIs that are under active development are marked experimental and can have breaking changes. APIs designated stable adhere to semantic versioning and won't have breaking changes. APIs are developed in public with community involvement so there are bound to be false starts, refactoring, etc., so we must reserve the right to break APIs that aren't fully baked.

More info can be found at [Versioning](https://docs.aws.amazon.com/cdk/latest/guide/reference.html#versioning) in the Developer Guide or in much more detail in the [Construct Library Lifecycle](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) RFC.

If you had trouble finding this information, we might want to add some links from this repo's README.

**Comment by Jerry-AWS** [comment]
https://github.com/aws/aws-cdk/pull/9691 adds this to the README

**Comment by ColeMurray** [comment]
Thanks for the speedy update 👍
