### ISSUE TITLE
[aws-cloudfront] Support for Cloudfront Origin Groups 

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9449]
There is now CloudFormation support for Origin Groups in CloudFront. It's technically possible to create an origin group config using the low level `Cfn` objects, but it is a pretty poor experience. What we need is first class support for origin groups to gloss over the CloudFormation implementation.

### Use Case

To use automatic failover of multiple origins with CloudFront

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Hi @justin8 - We actually just added support for this

For the stable API have a look at: https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudfront#origin-fallback

We are also in the process of providing a better API, which is currently still experimental, but you can have a look here: https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudfront-origins#failover-origins-origin-groups

So I believe this feature request can be resolved, can you confirm?

**Comment by justin8** [comment]
Ahh nice.

I see it's in the repo but not up on the docs site yet, which would be how I was able to miss it :)

Yes this can be closed. Thanks!
