### ISSUE TITLE
[@aws-cdk/pipelines] Source (branch) mapping to account/stage

### ISSUE THREAD

**Issue by abbottdev** [aws/aws-cdk#9461]
### The Question

Is it possible, using the new CDKPipeline (preview) library `@aws-cdk/pipelines` to have a specify a different source action for each stage/account? This could be a usage failing, but my scenario looks like this:

We are using GitFlow- so we have `develop`, `release` and `master` branches. Each one of these branches should deploys to a different AWS account. Let's assume that `develop` is a `develop` account, `release` is a `release` account and `master` is a `master` account.

In this scenario, if I use a GitHub action for my source, I don't appear to have a way to filter the GitHub action's branch to which stage (account) this should deploy to? 

Our pipeline process is essentially the same in each of these branches - albeit with a few bits turned on or off at each stage (I know that the Context lookup isn't yet available, but we should be able to map those settings appropriately when it is).

We have a `build`, `deploy` and `test` action in our pipeline, and that pipeline is currently created 3 times (3 pipeline stacks deployed separately) for each `branch` we want to map to an AWS Account... so it feels like this should be something I use `CdkPipelines` for. 

Any recommended usage patterns, questions, or documentation would be helpful if I'm going about this the wrong way - equally I thought as this is in Preview and this (may) be a valuable feature I should raise it.

### Environment

  - **CDK CLI Version:** 1.56.0
  - **Module Version:** 1.56.0
  - **Node.js Version:** 12.4.0
  - **OS:**  Ubuntu (WSL)
  - **Language (Version):** TypeScript (3.9.7)

### Other information

If this is within the scope of `CdkPipelines`, An example of what I might expect this to look like:

```
    const devStage = pipeline.addApplicationStage(new MyApplication(this, 'Dev', {
      env: {
        account: '123456789012',
        region: 'eu-west-1',
      },
      // sourceAction is a new paramter we can pass to the applicationStage? 
      sourceAction: new GitHubSourceAction({ 
         repo: "somerepo",
         actionName: "source",
         oauthToken: new SecretValue(""),
         owner: "someowner",
         branch: "develop",
         output: devArtifact
       });
    }));
```

**Comment by BrianFarnhill** [comment]
I work to a similar model, and implemented a unique pipeline per branch - so after I do a pull request from dev to master, the master pipeline triggers and releases to prod, while the dev pipeline just hangs off the dev branch and deploys to its account. I'm not sure there is a model here where a single pipeline could do this, but would be keen to see what others think on this.

**Comment by AlanChauchet** [comment]
Hi @BrianFarnhill Did you implemented that using `@aws-cdk/pipelines` ? I would be interested to see what it looks like because I am currently trying to do the same

**Comment by BrianFarnhill** [comment]
@AlanChauchet Yep, the codes on an private repo but here is the class that sets up the two pipelines:

```
const sourceArtifact = new codepipeline.Artifact();
const cloudAssemblyArtifact = new codepipeline.Artifact();

const synthParams = {
    buildCommand: 'npm run build --prefix ../../ && npm run test --prefix ../../',
    installCommand: 'npm run bootstrap --prefix ../../',
    subdirectory: 'packages/infrastructure',
}

function CreatePipeline(stack: cdk.Stack, sourceRepo: codecommit.IRepository, branchName: string) {

    const pipeline = new pipelines.CdkPipeline(stack, `${branchName}Pipeline`, {
        cloudAssemblyArtifact,
        sourceAction: new actions.CodeCommitSourceAction({
            actionName: 'CodeCommit',
            output: sourceArtifact,
            repository: sourceRepo,
            branch: branchName
        }),
        synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
            ...synthParams, sourceArtifact, cloudAssemblyArtifact
        })
    })

    const stageName = (branchName === 'master' ? 'prod' : 'dev')
    const accountId = (branchName === 'master' ? 'ACCOUNTID-PROD' : 'ACCOUNTID-DEV')

    pipeline.addApplicationStage(new CloudshotStage(stack, stageName, {
        env: { account: accountId, region: 'ap-southeast-2' }
    }))

    return pipeline
}

export class CloudshotPipeline extends cdk.Stack {

    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props)
        
        const sourceRepo = codecommit.Repository.fromRepositoryName(this, "SourceRepo", 'MyRepoName')

        CreatePipeline(this, sourceRepo, 'dev')
        CreatePipeline(this, sourceRepo, 'master')
    }

}
```

Tweak the approach to putting in your branch names or account IDs to suit however you want to do that, but that's the basic premise to how it works.

**Comment by rix0rrr** [comment]
You should think of a pipeline as a rule of the form:

## If X changes, then do Y

You can extend this a little, for example you can say:

```
If (X1 OR X2 OR X3) changes, then do Y
```
and

```
If X changes, then do Y1 AND Y2 AND Y3
```

However, you are looking to say:

```
If X1 changes, then do Y1
If X2 changes, then do Y2
If X3 changes, then do Y3
```

A single pipeline is just not able to express that logic, so you will have to resort to multiple pipelines. Fortunately, since this is code you should be able to make 3 similar pipelines easily enough with a `for` loop.

**Comment by davidxiao** [comment]
it's closed, but feel it doesn't make sense
when use feature/xxxx temp branches , then we need to set up a separate pipeline? 
and then how to remove them after build?

**Comment by OperationalFallacy** [comment]
"It’s important to note that trunk-based is, by far, the best strategy for taking full advantage of a DevOps approach; this is the branching strategy that AWS recommends to its customers"
https://aws.amazon.com/blogs/devops/multi-branch-codepipeline-strategy-with-event-driven-architecture/

Codepipline is such a pita for dealing with branches...

**Comment by MarcoAlessandroRiggio** [comment]
> A single pipeline is just not able to express that logic, so you will have to resort to multiple pipelines. Fortunately, since this is code you should be able to make 3 similar pipelines easily enough with a `for` loop.

Hi @rix0rrr, we've tried to create two CdkPipeline in a `for` loop like you suggested but in _UpdatePipeline Stage_ one of the two pipelines always fails with the following error:
`Call failed: describeChangeSet({"StackName":"<pipeline-stack-id>","ChangeSetName":"<change-set-name>"}) => ChangeSet [<change-set-name>] does not exist`


```typescript
 ["development", "production"].forEach(environment => {
            process.env.NODE_ENV = environment;
            delete require.cache[require.resolve("config")];
            const config = require('config');

            new CdkPipeline(this, `${environment}-cloud-pipeline`, {
                pipelineName: `${environment}-cloud-pipeline`,
                cloudAssemblyArtifact,
                sourceAction: new codepipeline_actions.CodeCommitSourceAction({
                    actionName: 'CodeCommit_Source',
                    repository: Repository.fromRepositoryName(this, `${environment}-repository`, config.repositoryName),
                    output: sourceArtifact,
                    branch: config.branch
                }),
                synthAction: SimpleSynthAction.standardNpmSynth({
                    sourceArtifact,
                    cloudAssemblyArtifact,
                    buildCommand: 'npm run build'
                })
            }).addApplicationStage(new CdkInfrastructureStage(this, environment, environment, {
                env: {account: config.account, region: config.region}
            }));
        });
```

How should it work?
Do you have any suggestions?

Thanks 
Best Regards
