### ISSUE TITLE
[aws-efs] Lifecycle policy for AFTER_7_DAYS is not being applied properly 

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#9474]
When creating or updating EFS resource with `LifecyclePolicy` param set to `AFTER_7_DAYS` this property gets omitted from the underlying CloudFormation template.

### Reproduction Steps

Assume having an EFS resource created with `LifecyclePolicy` param set to `AFTER_14_DAYS`:
```ts
const fileSystem = new efs.FileSystem(this, "EFS", { 
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      lifecyclePolicy: efs.LifecyclePolicy.AFTER_14_DAYS,
      vpc,
});
```
Corresponding CFN template contains `AFTER_14_DAYS`:
```bash
npm run build; cdk synth | grep -r -n1 "AFTER_"; cdk diff

> demo@0.1.0 build /Users/robertd/code/demo
> tsc

(standard input)-327-      LifecyclePolicies:
(standard input):328:        - TransitionToIA: AFTER_14_DAYS
(standard input)-329-    UpdateReplacePolicy: Delete
Stack EFSDemoTest
There were no differences
```

If you try to change `LifecyclePolicy` param to `AFTER_7_DAYS`:

```ts
const fileSystem = new efs.FileSystem(this, "EFS", { 
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      lifecyclePolicy: efs.LifecyclePolicy.AFTER_7_DAYS,
      vpc,
});
```
Outputting CFN template will completely ignore `AFTER_7_DAYS` change, and just remove `AFTER_14_DAYS` one:
```bash
npm run build; cdk synth | grep -r -n1 "AFTER_"; cdk diff

> demo@0.1.0 build /Users/robertd/code/demo
> tsc

Stack EFSDemoTest
Resources
[~] AWS::EFS::FileSystem EFS EFSBAA8953A
 └─ [-] LifecyclePolicies
     └─ [{"TransitionToIA":"AFTER_14_DAYS"}]

```

### What did you expect to happen?

Value of `AFTER_7_DAYS` of `LifecyclePolicy` property to be applied properly on EFS resource.

### What actually happened?

`LifecyclePolicy` policy is blank... only when making `AFTER_7_DAYS` selection.

### Possible Cause

`LifecyclePolicy` implementation (here: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-efs/lib/efs-file-system.ts#L250) in the constructor is using index based enum implementation, which is probably causing ternary condition check to short-circuit as `AFTER_7_DAYS`'s index is 0.

### Environment

  - **CLI Version      :** aws-cli/2.0.37 Python/3.8.5 Darwin/18.7.0 source/x86_64
  - **Framework Version:** 1.56.0
  - **Node.js Version:** v14.7.0
  - **OS               :** 10.14.6
  - **Language (Version):**  TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It's because `LifecyclePolicy` is a number-based enum, `AFTER_7_DAYS` gets the value 0, and then the ternary here doesn't pick it up:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-efs/lib/efs-file-system.ts#L250

**Comment by robertd** [comment]
Ahh exactly my thoughts in “Possible Cause” section of the initial bug report above. 👍
