### ISSUE TITLE
[aws-ec2] Python:  Cannot retrieve value from context provider vpc-provider

### ISSUE THREAD

**Issue by yohei1126** [aws/aws-cdk#9477]
Importing an existing VPC did not work.

### Reproduction Steps

* specify `env` as discussed here. https://github.com/aws/aws-cdk/issues/3082

```
MyStack(
    app,
    "airflow",
    env=core.Environment(account="98765432", region="ap-southeast-1")
)
```

* use from_lookup.
```
from aws_cdk import aws_ec2
class MyStack(core.Stack):
    def __init__(self, app: core.App, id: str, **kwargs) -> None:
        super().__init__(app, id, **kwargs)
        vpc = aws_ec2.Vpc.from_lookup(self, "vpc", vpc_id="vpc-xxx")
```

### What did you expect to happen?

* the existing VPC is imported to the CloudFormation stack

### What actually happened?

> jsii.errors.JSIIError: Cannot retrieve value from context provider vpc-provider since account/region are not specified at the stack level. Either configure "env" with explicit account and region when you define your stack, or use the environment variables "CDK_DEFAULT_ACCOUNT" and "CDK_DEFAULT_REGION" to inherit environment information from the CLI (not recommended for production stacks)

### Environment

  - **CLI Version      : 1.56.0 (build c1c174d)**
  - **Framework Version: 1.54.0**
  - **Node.js Version: v12.18.3**
  - **OS               : Windows 10**
  - **Language (Version): Python 3.7.3**

### Other

* also asked the same question on stackoverflow https://stackoverflow.com/questions/63262298/aws-python-cdk-cannot-retrieve-value-from-context-provider-vpc-provider

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Please create a simple GitHub repository that reproduces this issue, because I cannot reproduce it.

**Comment by yohei1126** [comment]
Looks like small example does not reproduce the issue.

**Comment by rix0rrr** [comment]
Then there is something different between the small example and the application in which you are observing this issue.

It's up to you to find what the difference is, we cannot do that for you.
