### ISSUE TITLE
[route53] Support for geolocation routing 

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9478]
Currently the only way to generate a geolocation record appears to be by utilizing the `Cfn` resources. It would be great to have higher level constructs for defining these

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jumic** [comment]
@njlynch I would suggest the following API to implement property [`GeoLocation`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-geolocation-1.html
). Do you have any comments or optimizations? Thanks.

Create a new class `GeoLocation` with methods that can be used to initialize the properties. The values (country codes, etc. ) can be passed as strings. Class [`GeoRestriction`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudfront/lib/geo-restriction.ts) in CloudFront module is built in the same way.

Class `GeoLocation` can be used as shown here:
```ts
GeoLocation.continent('EU');
GeoLocation.country('DE');
GeoLocation.subdivision('WA');  // default state US (only available for US)
GeoLocation.subdivision('WA', 'US');  // state can be specified if different states are supported later
```

In `RecordSet` this new property can be assigned:
```ts
new route53.ARecord(this, 'ARecord', {
  zone: myZone,
  target: route53.RecordTarget.fromIpAddresses('1.2.3.4', '5.6.7.8'),
  geoLocation: route53.GeoLocation.country('DE'),
});
```

Structure of class `GeoLocation` (validations, comments will be added):
```ts
export class GeoLocation {
  
  public static continent(continentCode: string) {
    return new GeoLocation(continentCode, undefined, undefined);
  }
  
  public static country(countryCode: string) {
    return new GeoLocation(undefined, countryCode, undefined);
  }

  public static subdivision(subdivisionCode: string, countryCode: string = 'US') {
    return new GeoLocation(undefined, countryCode, subdivisionCode);
  }

  private constructor(readonly continentCode: string | undefined, 
    readonly countryCode: string | undefined, readonly subdivisionCode: string | undefined) {}
}
```

**Comment by jumic** [comment]
@njlynch I'm not sure if this issue is still on your todo list. Probably other topics like CDK 2.0 were more important when I replied to issue.

If you have time to provide feedback on my API design, I could submit a pull request that implements the functionality. Thanks.

**Comment by njlynch** [comment]
@jumic - Yes, sorry, I think this fell off my plate either due to holidays or v2. :). The API as designed looks good to me!

**Comment by desoss** [comment]
are there any news regarding this?
