### ISSUE TITLE
[ECR] imageScanOnPush - add ability to rename the Lambda function name and add custom description

### ISSUE THREAD

**Issue by zulhfreelancer** [aws/aws-cdk#9480]
When creating a repository in ECR with [`imageScanOnPush`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecr.Repository.html#imagescanonpush) sets to `true`, the CloudFormation stack creates a Lambda function with a long and messy name and without a description.

I opened a case in AWS Support (case 7225519181) and the AWS staff asked me to raise an issue here because the feature is not available in CDK. Here is the reply to the case:

```
Hi Zulh,

This is Sihle from AWS Premium Support.

I understand that you would still like to know if it's still possible to set that function's description using CDK TypeScript code.

I have checked the documentation[1] again and the repo[2] for ECR in CDK Typescript and it appears there is no way for updating the function's description in 

I realize the importance of being able to rename the function and setting the description using the CDK TypeScript code, may I recommend that you open an issue[3] so that the team responsible for CDK TypeScript developing consider this feature.

If you have any other questions on this issue, fee free to get back to me with the questions on this case and I will be happy to assist you.

References:
[1] https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecr.Repository.html 
[2] https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-ecr 
[3] https://github.com/aws/aws-cdk/issues 

We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.

Best regards,
Sihle M.
Amazon Web Services
```

### Use Case

As the number of Lambda functions grow, it's hard to differentiate which Lambda function for which stack. By having ability to rename the Lambda function name and add custom description using CDK, it can help us scan and find Lambda function that we need easily when looking at the AWS web console. Plus, we can add some more information inside the description area.

### Proposed Solution

```
this.ecrRepo = new ecr.Repository(this, "myRepo", {
    imageScanOnPush: true,
    imageScanOnPushFunctionName: "myFunction",
    imageScanOnPushFunctionDesc: "myFunction description...",
});
```

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hey @zulhfreelancer,

We are reviewing old feature-requests to determine if they are still valid. From what I can tell of the ECR image-scanning [documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html), it seems that any activity of the image scan is an integrated component. I am not seeing the value to exposing explicit components of the lambda created to do so.

Could you clarify why you need to be able to rename said function (as opposed to just locating it in the stack definition when you want to check on it)?

😸 😷

**Comment by NGL321** [comment]
Also, as a note, this change would require Cloudformation to change their structure rather than the CDK. As you can see here, we do not create the lambda ourselves in the L2, that task is delegated to Cloudformation:

https://github.com/aws/aws-cdk/blob/a75d52fb82ad9a4f526f82aa58ff8ee74d35a3cd/packages/%40aws-cdk/aws-ecr/lib/repository.ts#L454-L463

**Comment by zulhfreelancer** [comment]
As mentioned in the PR description:

> As the number of Lambda functions grow, it's hard to differentiate which Lambda function for which stack. By having ability to rename the Lambda function name and add custom description using CDK, it can help us scan and find Lambda function that we need easily when looking at the AWS web console. Plus, we can add some more information inside the description area.

The keyword here is to ease the team when visually looking at Lambda functions index page. The function name that get generated by CDK/Cloudformation is full of random characters and not readable. It's hard to tell which function is for which project and what it actually does. That's why I opened this issue — a proposal to allow us to set a custom name and description for this imageScanOnPush Lambda function.

Btw, I'm no longer using CDK at work. So, I can't really help verify anything e.g. the fixes that will arrive later. Apologies.

**Comment by peterwoodworth** [comment]
If anyone runs into this issue in the future - I recommend reaching out to the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) and creating an issue there if one doesn't exist. As mentioned above, CDK isn't in control of creating this lambda function, so we cannot customize it. This feature is dependent on Cfn / ECR
