### ISSUE TITLE
[codebuild] Using custom build image with codebuild PipelineProject produces JSII resolution error

### ISSUE THREAD

**Issue by paveljos** [aws/aws-cdk#9486]
Using a custom buildimage hosted in ECR causes JSII resolution errors. 

### Reproduction Steps

Using Python, comparing these image definitions:
```
codebuild_custom_image = codebuild.LinuxBuildImage.from_ecr_repository(
     ecr.Repository.from_repository_name(
           self,
           'codebuild_ecr_repository',
            repository_name='cdk'
     ),
     'latest')
standard_image = codebuild.LinuxBuildImage.STANDARD_2_0
```
If I set this portion of code to "codebuild_custom_image", I receive an error:
```
cdk_build = codebuild.PipelineProject(self, "CdkBuild",
   build_spec = codebuild.BuildSpec.from_object(dict(
      version="0.2",
      phases=dict(
         install=dict(commands=[]),
         build=dict(commands=[]),
         post_build=dict(commands=[])),
         artifacts={
             "base-directory": "output","files": []},
         environment=dict(buildImage=build_image))))
```
If I set it to standard_image, it compiles as expected.
### What did you expect to happen?
I should be able to specify a custom ECR container for use as the build environment in CodeBuild.

### What actually happened?

`jsii.errors.JavaScriptError: 
  Error: Resolution error: Resolution error: Resolution error: Resolution error: Trying to resolve() a Construct at /environment/buildImage/repository/node/_actualNode.
`
(followed by a long and nasty stack trace)
### Environment

  - **CLI Version:** 1.56
  - **Framework Version:** 1.56
  - **Node.js Version:** 14.7.0
  - **OS:** Mac
  - **Language (Version):** Python 3.8

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @paveljos ,

thanks for opening the issue. The problem in your code is that you're passing `environment` in `BuildSpec.from_object()`, instead of to `PipelineProject`:

```python
        cdk_build = codebuild.PipelineProject(self, "CdkBuild",
            build_spec = codebuild.BuildSpec.from_object(dict(
                version="0.2",
                phases=dict(
                    install=dict(commands=[]),
                    build=dict(commands=[]),
                    post_build=dict(commands=[])),
                artifacts={
                    "base-directory": "output","files": [],
                },
                environment=dict(buildImage=build_image)))) # <---- nope!
```

In fact, when synthesizing with `build_image` = `standard_image`, the resulting CloudFormation is `Image: aws/codebuild/standard:1.0`, which is not what you set `standard_image` to (which was 2.0).

You want this instead:

```python
        cdk_build = codebuild.PipelineProject(self, "CdkBuild",
            build_spec = codebuild.BuildSpec.from_object(dict(
                version="0.2",
                phases=dict(
                    install=dict(commands=[]),
                    build=dict(commands=[]),
                    post_build=dict(commands=[])),
                artifacts={
                    "base-directory": "output","files": [],
                },
            )),
            environment=codebuild.BuildEnvironment(
                build_image=build_image,
            )
        )
```

Thanks,
Adam

**Comment by paveljos** [comment]
Thanks for the response!

While your adjustment does allow the code to compile successfully, it doesn't correctly set the codebuild environment. Making the change you suggested produced a valid synth, but the diff showed no changes. I then deleted my stacks and redeployed with this correction, and the resulting codebuild environment is still set to "aws/codebuild/standard:1.0".

**Comment by paveljos** [comment]
FYI - problem definitely in my code, the below is what I used to get it to work:
```
        codebuild_custom_image = codebuild.LinuxBuildImage.from_ecr_repository(
            ecr.Repository.from_repository_name(
                self,
                'codebuild_ecr_repository',
                repository_name=ecr_repository
            ),
            ecr_tag)

        cb_env = codebuild.BuildEnvironment(
            build_image = codebuild_custom_image,
            privileged  = True
        )

        cdk_build = codebuild.PipelineProject(self, "CdkBuild",
                        role        = codebuild_build_role,
                        description = "CDK Build with CodeBuild",
                        environment = cb_env,
```
I think my only lingering question/problem/feedback is why the example you gave (setting the environment to a build image) synthesizes correctly, having worked it out with the proper resources I would have expected that to fail with a type error/mismatch.

**Comment by paveljos** [comment]
Thank you so much for the guidance - this works! I do believe there may be room for improvement in that I can pass a LinuxBuildImage resource to the environment and it synthesizes without error but does not perform any change. That should give an error and fail. It might prevent people from making the dumb mistake that I did.  :-)

**Comment by skinny85** [comment]
Yes. That's because the `from_object` method on `BuildSpec` takes in an untyped Dictionary as its input, and the reason for that is we don't want to block our customers from using new CodeBuild buildspec features as they are released.

We have an issue for a type-safe Buildspec: #2039, but we haven't gotten around to it yet (contributions are welcome!).

I'm glad you got unblocked. I'm resolving this one, let me know if you need anything else for this issue from our side.
