### ISSUE TITLE
[aws-ec2] InterfaceEndpoint: use construct ID as name tag by default

### ISSUE THREAD

**Issue by cl-ewhite** [aws/aws-cdk#9487]
### The Question
I assume that given:
```
    vpc.addInterfaceEndpoint('EC2',{
      service: ec2.InterfaceVpcEndpointAwsService.EC2,
      securityGroups: [ defaultSecurityGroup ],
    });
```
The `ID:String` should end up being the name of the Endpoint.  The endpoints are created with no names.
Is this a bug or by design?

### Environment

  - **CDK CLI Version:** 1.56.0
  - **Module Version:** 1.56.0
  - **Node.js Version:** v14.7.0
  - **OS:** OSX Mojave
  - **Language (Version):** TypeScript

**Comment by rix0rrr** [comment]
That's an interesting question. I guess it's an oversight, but now having been made aware of it I have a hard time deciding whether it's the right behavior or not. I guess there's something to be said either way :).

In any case, I don't see issue with defaulting to the given identifier as the name for the endpoint (as long as they don't have to be unique).

I think in most of EC2s resources, names are determined by `Tag`s, so it's probably a matter of adding the right tag.

**Comment by flemjame-at-amazon** [comment]
This is blocked on CFN support for tagging VpcEndpoints -- see #8463 

@cl-ewhite how would you feel if the name for an InterfaceVpcEndpointAwsService was the name of the actual service itself? For example, "ec2" for InterfaceVpcEndpointAwsService.EC2 ?

**Comment by cl-ewhite** [comment]
@flemjame-at-amazon Using the name of the actual service would suit my use case fine, in fact it is exactly what I was going to do.   
#8463 explains why I was having so much trouble setting the Name tag manually.
