### ISSUE TITLE
[autoscaling] Option for recreating Auto Scale Groups when AMI ID changes

### ISSUE THREAD

**Issue by ajbdev** [aws/aws-cdk#9497]
When a stack's AMI ID changes, respawn the instances with the fresh AMI. Perhaps this could be a configuration option during creation of the ASG. 

I apologize if this feature is out of the scope of the intentions of AWS CDK, but I thought I'd at least document the use case I'm attempting to execute. 

### Use Case

Our infrastructure uses the concept of [golden images](https://hodgkins.io/building-a-golden-image-pipeline) to deploy code changes to our application. This means AMI ID's change with every code deployment.

Currently we have to run a script to manually pump up/down the desired capacity after a `cdk deploy` is ran in order to recycle instances into the group with the fresh AMI. 

### Proposed Solution

I don't know the exact implementation details, but I think ideally the way this would occur is by:

- Creating a new AutoScaleGroup with fresh instances
- Detaching the old AutoScaleGroup from all target groups
- Attach new AG to target groups

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
What is the `machineImage` you are using?  You can use `AmazonLinuxImage` which will update to the latest version on every deployment:

```ts
new autoscaling.AutoScalingGroup(stack, 'MyFleet', {
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.M4, ec2.InstanceSize.MICRO),
  machineImage: new ec2.AmazonLinuxImage(),
  vpc,
});
```
Is this what you are looking for?

**Comment by ajbdev** [comment]
This just updates the AutoScaleGroup's LaunchConfiguration, right?

You still need to cycle the instances for the new AMI to be serving requests behind a load balancer after you `cdk deploy`.

**Comment by NetaNir** [comment]
`AutoScalingGroup` includes an `updateType` property, which sets the asg [UpdatePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html), by default it's set to `None`, but can be set to `ROLLING_UPDATE` which will replace the instances in the AutoScalingGroup.
If you are using the `AmazonLinuxImage`, you need to make sure that the AMI value is not cached in cdk.context.json file 
 see [docs](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-autoscaling#machine-images-amis), to allow the AMI update

**Comment by ajbdev** [comment]
This looks like exactly what I'm looking for. Thanks a lot for pointing me in this direction!
