### ISSUE TITLE
[IAM] trailing space at the end of an ARN causes cryptic error

### ISSUE THREAD

**Issue by kwkr** [aws/aws-cdk#9510]
When there is a trailing space at the end of an ARN that is used by some newly created resources, it causes the deployment to fail with a cryptic error.

### Reproduction Steps
Put this in your stack and invoke `addToRolePolicy` of some other resource.
```
const statement = new PolicyStatement();
    statement.addResources(
      "arn:aws:ssm:*:*:parameter/test/deployment/token "
    );
    statement.addActions("ssm:GetParameter"); 
someResource.addToRolePolicy(statement)
```

then when trying to `cdk deploy` a table containing list of changes for new resources will be displayed. If the ARN (that is probably meant to be in this table) contains whitespace at the end, the command fails.

### What did you expect to happen?

I expect to get some more precise warning.

### What actually happened?

I got following output:
```
IAM Statement Changes
Table data must not contain control characters.
```
and the command exited.

Which is not precise about what is causing the problem.

### Environment

  - **CLI Version      :** 1.41.0 (build 9e071d2)
  - **Framework Version:**  1.41.0
  - **Node.js Version:** v12.14.1
  - **OS               :** macOS Catalina 10.15.6
  - **Language (Version):** TypeScript (3.8.3

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Hey Somaya, this is not a CLI issue.

If anything it's an IAM issue, and it's also one I would feel comfortable saying "no" to.

**Comment by NGL321** [comment]
Hey @kwkr,

Thank you for reporting this, but I am going to close the issue for now as we don't see a problem with the behavior.

This is actually a very explicit error. ARN formatting is not evaluated in synth time, so it could only fail during deploy, and it tells you exactly what is wrong. ["Control character"](https://en.wikipedia.org/wiki/Control_character) is a pretty common phrase (and spaces are typically not allowed in resource naming anyway). If you would like more information on how to format your ARNs, please see [here](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html).

Please let us know if you have anything else!

😸 😷

**Comment by jonnekaunisto** [comment]
Would it be possible to print the violating string though? It can be pretty hard to find
