### ISSUE TITLE
[@aws-cdk/aws-ec2] BastionHostLinux selects wrong availability zone

### ISSUE THREAD

**Issue by mackensen** [aws/aws-cdk#9519]
We have a multi-account setup where a VPC and subnets are defined in a single primary account and shared with other accounts through Resource Access Manager. We have a single networking library where the VPC and subnets are imported; that library is then included in our various projects. The VPC and subnets are imported using the availability zones as the primary account knows them; the actual availability zones differ in the other accounts.

Most constructs (Fargate, EFS, Autoscaling) handle this fine; given the desired subnets, they resolve the correct availability zone based on the AZs available to the downstream account. BastionHostLinux appears to use the AZ defined on the subnet as imported, so you get this:

```
Value (us-east-1d) for parameter availabilityZone is invalid. Subnet 'subnet-xxxxxx' is in the availability zone us-east-1b
```

`us-east-1d` is defined in the import; `us-east-1b` is the correct AZ for that subnet in the deploy account.

### Reproduction Steps

Networking library:

``` typescript
        this.devVpc = ec2.Vpc.fromVpcAttributes(this, "DevVPC", {
            vpcId: "vpc-xxxxxx",
            availabilityZones: ['us-east-1a', 'us-east-1d'],
        });

        this.devWebZoneDSubnet = ec2.Subnet.fromSubnetAttributes(this, "DevWebDSubnet", {
            subnetId: "subnet-xxxxxx",
            availabilityZone: 'us-east-1d',
        });
        this["devWebZoneDSubnet"] = this.devWebZoneDSubnet;
        this.devWebZoneASubnet = ec2.Subnet.fromSubnetAttributes(this, "DevWebASubnet", {
            subnetId: "subnet-xxxxxx",
            availabilityZone: 'us-east-1a',
        });
        this["devWebZoneASubnet"] = this.devWebZoneASubnet;

```

Bastion host code:

``` typescript
    this.bastionHost = new ec2.BastionHostLinux(scope, opts.identifier + 'BastionHost', {
      vpc: this.devVpc,
      securityGroup: xxx,
      subnetSelection: {
        onePerAz: true,
        subnets: [
          this["devWebZoneASubnet"],
          this["devWebZoneDSubnet"]
        ],
      },
    });
```

### What did you expect to happen?

Create a BastionHostLinux in one of the two supplied subnets.

### What actually happened?

Deploy error (see above) because CDK attempted to use the wrong availability zone.

### Environment

  - **CLI Version      :** 1.51.0
  - **Framework Version:** 1.51.0
  - **Node.js Version:** v12.14.1
  - **OS               :** macOS Mojave 10.14.6 
  - **Language (Version):** TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Am I understanding the situation correctly when I summarize it as follows:

You are doing the following:

```ts
        this.devWebZoneDSubnet = ec2.Subnet.fromSubnetAttributes(this, "DevWebDSubnet", {
            subnetId: "subnet-123456",
            availabilityZone: 'us-east-1d',
        });
```

Even though `subnet-123456` actually lives in `us-east-1b`.

Then, when you go to use `devWebZoneDSubnet`in a `BastionHostLinux`, you get an error because the Instance says that `subnet-12356` does not live in `us-east-1d`.

Let me know if my understanding is incorrect, but if is correct:

Not quite sure whether there's anything we can do about this, but I'm a little confused why you would expect to put wrong information in and have the underlying system divine the right information instead. The fact that it works for some constructs and not others is not a great argument for why it should work in general. Seems like you've just gotten lucky up until this point.

**Comment by mackensen** [comment]
@rix0rrr your summary is accurate, but I would clarify that the information is correct for the original account, just not the downstream account.

**Comment by rix0rrr** [comment]
Unfortunately AZ mappings are not consistent between accounts.
