### ISSUE TITLE
[codebuild] FileSystemLocation doesn't accept valid DNS name

### ISSUE THREAD

**Issue by paveljos** [aws/aws-cdk#9520]
codebuild.FileSystemLocation doesn't accept DNS names with a '-' in them, as per any AWS DNS name that includes the region.

### Reproduction Steps

```
        fs = codebuild.FileSystemLocation.efs(
            identifier  = 'parallel-cdk-efs',
            location    = 'fs-XXXXXXXX.efs.us-east-1.amazonaws.com:/', 
            mount_point = "/cdk_deploy"
        )
```
* Note: Ideally, I'd love for the DNS name to be a property of the EFS filesystem itself (it's not listed here: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_efs.html)

I believe this is the correct format for my location string based upon the example here: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codebuild.README.html#project-file-system-location-efs and a manually created CodeBuild project with an EFS mount that displays the location as `fs-XXXXXXXX.efs.us-east-1.amazonaws.com:/`

### What did you expect to happen?

CodeBuild should define the FileSystem appropriately. 

### What actually happened?

Received error:
`Invalid input: identifier must contain only alphanumeric characters and underscores and be less than 128 characters in length. `

### Environment

  - **CLI Version      : 1.56
  - **Framework Version: 1.56
  - **Node.js Version: v14.7.0
  - **OS               : MacOS
  - **Language (Version): Python 3.8

### Other

Other checks have interfered with my ongoing troubleshooting of this: for instance, if I remove the "-" from the name, I get `Invalid AWS Region: useast1`. Trying to formulate it in other ways get me the error `Invalid Input: File System Location is invalid, should be in the form 'FileSystemDNS':'FileSystemDirectory'`. 

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @paveljos ,

thanks for opening the issue. Is the error you're getting at `cdk deploy` time? If not, when does it happen?

Thanks,
Adam

**Comment by paveljos** [comment]
Yes, during deploy time. It synthesizes fine.

**Comment by paveljos** [comment]
```8:47:43 AM | CREATE_FAILED        | AWS::CodeBuild::Project     | CdkBuild455F642E
Invalid input: identifier must contain only alphanumeric characters and underscores and be less than 128 characters in length. (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; Request ID: bcffa0a2-b093-4aef-82ae-4118d
2f5dfcb; Proxy: null)

	new Project (/private/var/folders/r9/d3g9b6nx2c11r9zqfylmhfjd15mdx5/T/jsii-kernel-CZtSJ4/node_modules/@aws-cdk/aws-codebuild/lib/project.js:282:26)
	\_ new PipelineProject (/private/var/folders/r9/d3g9b6nx2c11r9zqfylmhfjd15mdx5/T/jsii-kernel-CZtSJ4/node_modules/@aws-cdk/aws-codebuild/lib/pipeline-project.js:12:9)
	\_ /Users/paveljos/code/parallel_cdk/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7922:49
	\_ Kernel._wrapSandboxCode (/Users/paveljos/code/parallel_cdk/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8395:20)
	\_ Kernel._create (/Users/paveljos/code/parallel_cdk/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7922:26)
	\_ Kernel.create (/Users/paveljos/code/parallel_cdk/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7666:21)
	\_ KernelHost.processRequest (/Users/paveljos/code/parallel_cdk/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7446:28)
	\_ KernelHost.run (/Users/paveljos/code/parallel_cdk/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7384:14)
	\_ Immediate._onImmediate (/Users/paveljos/code/parallel_cdk/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7387:37)
	\_ processImmediate (internal/timers.js:458:21)


 ❌  parallel-cdk-pipeline failed: Error: The stack named parallel-cdk-pipeline failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:292:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:266:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:268:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:188:9)
The stack named parallel-cdk-pipeline failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE```

**Comment by paveljos** [comment]
Leaving this as a monument to my foolishness. It clearer says "identifier", but I had been troubleshooting the "location". Fixed my identifier to match the specifications (alphanumeric and underscores) and everything is fine. It would be nice to catch this error at synth time, but it was my own fault.
