### ISSUE TITLE
[aws-cloudfront] Add Geolocation Headers 

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#9523]
_On behalf of: alxgla@_

I would like to request the [new Cloudfront Geolocation headers](https://aws.amazon.com/about-aws/whats-new/2020/07/cloudfront-geolocation-headers/) be added to the CDK

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
I believe that to add these headers we may need to wait for Cloudformation to implement them first. @iliapolo would you agree?

**Comment by iliapolo** [comment]
@NGL321 As I understand, the way to use these headers is through an [Origin Request Policy](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/controlling-origin-requests.html#origin-request-understand-origin-request-policy-info). This is not yet supported by CDK, even though it is by [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-originrequestpolicyid). 

Looks like we have a gap here, making @njlynch aware as well.

**Comment by iliapolo** [comment]
Now that i look at it again, it looks like CloudFormation does support passing a policy id, but doesn't support actually creating them. This might a tricky one.

**Comment by njlynch** [comment]
Origin Request Policy support was closed out in #9647 for `Distribution`, and pending #10830 for `CloudFrontWebDistribution`. Closing this out in favor of those two issues.
