### ISSUE TITLE
[core] Possibility of deploying a wrong template when cdk deploy command is running in parallel

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#9545]
When deploying stacks by running multiple `cdk deploy` commands at once, there is a possibility of an unintentional template deployed.

### Reproduction Steps

Given the `bin/cdk.ts` below:

```ts
const queue11Name = app.node.tryGetContext("queue11Name");
const queue12Name = app.node.tryGetContext("queue12Name");
const queue2Name = app.node.tryGetContext("queue2Name");

new SampleStack(app, 'stack1-1', {
    stackName: 'stack1-1',
    queueName: queue11Name,
});
new SampleStack(app, 'stack1-2', {
    stackName: 'stack1-2',
    queueName: queue12Name,
});
new SampleStack(app, 'stack2', {
    stackName: 'stack2',
    queueName: queue2Name,
});

interface SampleStackProps extends cdk.StackProps {
    queueName?: string
}

class SampleStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props: SampleStackProps) {
    super(scope, id, props);

    const queue = new sqs.Queue(this, 'queue', {
        queueName: props.queueName ?? 'default',
    });
  }
}
```

And type cdk deploy commands in the following order:
1. Run `npm run cdk deploy stack1* -- -c queue11Name queue11 -c queue12Name queue12`
2. When the deployment of stack1-1 has started, then run `npm run cdk deploy stack2 -- -c queue2Name queue2`

### What did you expect to happen?

The name of queue in `stack1-2` set as `queue12`, as specified by the `queueName12` context variable.

### What actually happened?
The name of queue in `stack1-2` set as `default`.

Also, retrying `npm run cdk deploy stack1* -- -c queue11Name queue11 -c queue12Name queue12` does not work.
The name of the queue remains `default` even though you retry deploying the stack with the same options.

### Why this can happen?

`cdk deploy` command deploys stacks in the following steps:
1. json templates for all the available stacks (as `cdk ls` with the same option outputs) are synthesized and placed in `cdk.out` directory. Also the synthesize result jsons are [cached in ram](https://github.com/aws/aws-cdk/blob/v1.57.0/packages/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.ts#L120-L125) at this time.
2. loop for the stacks selected by the argument of deploy command (equal to or more than one)
    1. stack is deployed by [deploy-stack function](https://github.com/aws/aws-cdk/blob/v1.57.0/packages/aws-cdk/lib/api/deploy-stack.ts#L166)
        1. [calculate hash](https://github.com/aws/aws-cdk/blob/v1.57.0/packages/aws-cdk/lib/api/deploy-stack.ts#L326-L331) for the template YAML string **from the template cached in the step1**
           * the hash is used as the S3 object key when uploading the template file as an asset
        2. upload the file asset to S3. If the file with the same S3 object key is found on the staging bucket, [it doesn't re-upload the template](https://github.com/aws/aws-cdk/blob/v1.57.0/packages/cdk-assets/lib/private/handlers/files.ts#L40-L43) (because if it has the same hash, file content should also be the same.) Note that when uploading the file, **it reads the file content from the storage (not the string cached in the ram)**
        3. create a CFn change set from the S3 object and apply it.

The problem can happen because the template the hash caluculated from and the template actually uploaded to S3 can be different.

So the events happens in the following order:
1. Run `npm run cdk deploy stack1* -- -c queue11Name queue11 -c queue12Name queue12`
2. Json templates for stack1-1, stack1-2, stack2 are synthesized and placed in `cdk.out` directory.
   * queue11Name=queue11, queue12Name=queue12, queue2Name=undefined
3. the deployment of stack1-1 starts
4. Run `npm run cdk deploy stack2 -- -c queue2Name queue2`
5. Json templates for stack1-1, stack1-2, stack2 are synthesized and placed in `cdk.out` directory.
   * queue11Name=undefined, queue12Name=undefined, queue2Name=queue2
6. the deployment of stack2 starts, and the deployment of stack1-1 completes
7. the deployment of stack1-2 starts. As the template file for stack1-2 is modified at step 5, the actually deployed template becomes one synthesized at step5. This is why the name of queue in `stack1-2` set as `default`.

### Environment

  - **CLI Version      :** 1.57.0
  - **Framework Version:** 1.57.0
  - **Node.js Version:**  v13.11.0
  - **OS               :** macOS
  - **Language (Version):**  TypeScript

### Other
There are several possible ways to fix the problem:
1. add hash (as s3 object keys) to the file name of the json templates in `cdk.out` dir to ensure that each `deploy` command has no side effect on other `deploy` commands.
2. Upload the template json to staging bucket reading from ram (not file) 
3. Always upload the template file to staging bucket even though there is the file with the same S3 object key. (By this, we can retry to deploy the correct template)

It may be an edge case but running deploy command in parallel is a popular workaround to deploy mulitple stacks at once.
This behaviour makes the workaround nearly unusable for us so we hope it fixed.

--- 

This is :bug: Bug Report

**Comment by tneely** [comment]
My team has been able to workaround this issue by deploying each stack with a separate output directory (e.g. `cdk deploy stack1 --output ~/tmp/out1` and `cdk deploy stack2 --output ~/tmp/out2`).

**Comment by rix0rrr** [comment]
Yes, pretty sure this happens because the 2nd synth will overwrite the templates in `cdk.out`. 

You've found the correct way to address this.
