### ISSUE TITLE
[certificatemanager] The certificate provided must be owned by the account creating the domain.

### ISSUE THREAD

**Issue by apoorvmote** [aws/aws-cdk#9548]
## Bug description
I am adding domain to my HTTP API gateway 

```typescript
    const certificate = Certificate.fromCertificateArn(this, 'ssl_cert', certArn)

    const domain = new DomainName(this, 'domain', {
      domainName: website_domain,
      certificate
    })
```
I get the following error
`The certificate provided must be owned by the account creating the domain. (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException;`

I have manually verified certification arn at least 10 times. It's correct arn and I only have access to single aws account. 

Same exact code did worked 5 days ago with 1.56.0 not working for 1.57.0

This time I am trying to deploy lambda with http api and last time I deployed frontend to s3 and cloudfront using same exact code. 

### Environment

  - **CLI Version      : 1.57.0**
  - **Framework Version: 1.57.0**
  - **Node.js Version: 12.18.3** 
  - **OS               : Ubuntu 18.04**
  - **Language (Version): Typescript 3.7.2** 

### Other

--- 

This is :bug: Bug Report

**Comment by apoorvmote** [comment]
Sorry I think the real issue is with **`HTTP api`**

I tried adding certificate manually from **aws console**.

If I select endpoint to be regional then I can only select certificate from that region but my certificate is at different region (us-east-1).

If I select endpoint to be Edge-optimized (supports only REST APIs) then I can select certificate from different region. However I don't want to use REST API.

**Comment by mainframenzo** [comment]
@njlynch I am running into this same issue when the CdkPipeline tries to deploy a stage using both 1.56 and 1.57 release: `The certificate provided must be owned by the account creating the domain.` I am using a Rest API optimized for the edge, which aligns with the "fix" above, so I'm at a loss; I also tried grepping the error in the AWS docs with no luck. Does it have something to do with ACM certificate permissions for CdkPipeline (which I'm using)?  I have tried using a newly created cert (shown below) and also an already-validated certificate with an ARN reference.

```
   const proxyLambda = new lambda.Function(this, 'LambdaAPIProxy', {
      code: lambda.Code.fromAsset(path.resolve(__dirname, '../../web_src/api')),
      handler: 'handler.index',
      runtime: lambda.Runtime.NODEJS_12_X
    });
    
    const api = new apigateway.LambdaRestApi(this, 'APIGateway', {
      description: 'API',
      handler: proxyLambda
    });

   const hostedZone = route53.HostedZone.fromLookup(this, 'Zone', {
      domainName: 'domain.com'
    });

    const certificate = new certificateManager.DnsValidatedCertificate(this, 'DomainWildcardCertificate', {
      domainName: '*.domain.com',
      hostedZone: hostedZone,
      region: 'us-east-1'
    });

   //this is where the failure happens!
    const apiDomainName = api.addDomainName('CustomAPIDomainName', {
      domainName: 'api.domain.com',
      certificate: certificate,
      endpointType: apigateway.EndpointType.EDGE
    });

```

**Comment by kay-is** [comment]
Had the same issue. Solved it by creating a cert in every region I deploy to.

/cc #9608
