### ISSUE TITLE
Deployment parameters

### ISSUE THREAD

**Issue by IndikaUdagedara** [aws/aws-cdk#955]
My use case is to pass certain parameters only during the stack creation and then use the previous value on stack updates (or when that parameter is not specified). This is useful as not all parameters will change per deployment, and also to pass secret parameters that can't be put in the `cdk.json` file.

With Cloudformation, this can be achieved with the `UsePreviousValue` parameter option. 

The approach we follow with CFN is
- A team member who has access to secrets will deploy the stack passing all parameters
- When stack is deployed with CD pipeline it passes `UsePreviousValue` to secret parameters.

It's not clear how to achieve a similar workflow with cdk.

**Comment by rix0rrr** [comment]
Implementation note: take care to never display parameters for which `noEcho` is set.

**Comment by shivlaks** [comment]
`previous-parameters` was added as a [supported flag](https://github.com/aws/aws-cdk/commit/44310c93af939f8aaf9ca4245c944b5c93f61ab7) which will use previous values for existing parameters.

All parameters must be specified on every deployment if this is disabled.

Resolving this issue. Feel free to re-open if it still does not cover your use case.
