### ISSUE TITLE
[cdk-pipelines] DeployCdkStackAction needs support for parameters in some way

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#9560]
From https://github.com/aws/aws-cdk/issues/9402 (among others):

Some people want to deploy Lambdas etc. not from CDK assets but parameters.

# Design notes

* In principle we have a full list of parameters so we can have DeployCdkStackAction VALIDATE that all parameters have a value and there are no extraneous parameters! Isn't that cool!

---

This is a :rocket: Feature Request

**Comment by timbaer** [comment]
Is this feature meant to allow a workflow like explained here: https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html ? Meaning that one can pass a list of cf-parameters to be passed as `parameterOverrides` parameter?

**Comment by Mr-istov** [comment]
Hey @rix0rrr any updates on this issue?
I just stumbled on this problem where I want to deploy a lambda from the parameters and was researching how can it be done with a CDK pipeline and found this issue.

**Comment by stekern** [comment]
Any plans to look into this any further? As far as I can tell the required functionality (passing CloudFormation parameters to a CloudFormation deploy action) exists in CodePipeline as far as I can tell, so what's missing is leveraging/exposing this functionality in CDK Pipelines.

**Comment by stekern** [comment]
In the meantime here's a hacky way using an Aspect to add CloudFormation parameter overrides to a CDK Pipeline:
```typescript
// Apply the aspect to the CDK Pipelines construct after it has been built
function addParameterOverrides(scope: constructs.IConstruct) {
  const stack = cdk.Stack.of(scope)
  cdk.Aspects.of(scope).add({
    visit(construct: constructs.IConstruct) {
      if (
        construct instanceof pipelines.CodePipeline &&
        construct.pipeline.node
      ) {
        const pipeline = construct.pipeline.node
          .defaultChild as codepipeline.CfnPipeline
        ;(
          stack.resolve(
            pipeline.stages,
          ) as codepipeline.CfnPipeline.StageDeclarationProperty[]
        ).forEach((stage, stageIndex) => {
          ;(
            stack.resolve(
              stage.actions,
            ) as codepipeline.CfnPipeline.ActionDeclarationProperty[]
          ).forEach((action, actionIndex) => {
            const actionTypeId = stack.resolve(
              action.actionTypeId,
            ) as codepipeline.CfnPipeline.ActionTypeIdProperty
            const configuration = action.configuration as Record<
              string,
              unknown
            >
            if (
              actionTypeId.category === "Deploy" &&
              actionTypeId.owner === "AWS" &&
              actionTypeId.provider === "CloudFormation" &&
              actionTypeId.version === "1" &&
              configuration &&
              (configuration.ActionMode === "CHANGE_SET_REPLACE" ||
                configuration.ActionMode === "CREATE_UPDATE")
            ) {
              pipeline.addPropertyOverride(
                `Stages.${stageIndex}.Actions.${actionIndex}.Configuration.ParameterOverrides`,
                JSON.stringify({
                  ParameterNameStaticValue: "value",
                  ParameterNameDynamicValue:
                    "#{codepipeline.PipelineExecutionId}",
                }),
              )
            }
          })
        })
      }
    },
  })
}

```
