### ISSUE TITLE
[core] Do not emit duplicate messages (warnings/errors/...)

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#9565]
When synthesizing the [EKS integration test] I am getting the following output:

[EKS integration test]: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/test/integ.eks-cluster.ts

```
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/KubectlProviderSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/Nodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/Nodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/Nodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/Nodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/Nodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/BottlerocketNodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/BottlerocketNodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/BottlerocketNodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/BottlerocketNodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/BottlerocketNodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/spot/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/spot/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/spot/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/spot/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/spot/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/InferenceInstances/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/InferenceInstances/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/InferenceInstances/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/InferenceInstances/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/InferenceInstances/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
```

### Reproduction Steps

In the CDK repo:

```shell
$ cd packages/@aws-cdk/aws-eks
$ cdk synth -a test/integ.eks-cluster.ts
```

### What did you expect to happen?

Don't display the same warning twice:

```
[Warning at /aws-cdk-eks-cluster-test/Cluster/ControlPlaneSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/KubectlProviderSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/Nodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/BottlerocketNodes/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/spot/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /aws-cdk-eks-cluster-test/Cluster/InferenceInstances/InstanceSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
```

### Environment

  - **CLI Version      :** 1.57.0
  - **Framework Version:** 1.57.0
  - **Node.js Version:**  14.5.0
  - **OS               :** Mac OSX
  - **Language (Version):**  all

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The same annotation should probably just not be emitted twice.

**Comment by rix0rrr** [comment]
Also that warning should probably not be emitted at all.

**Comment by eladb** [comment]
> The same annotation should probably just not be emitted twice.

That's probably a good idea - we can do that based on scope path and message text.

**Comment by NetaNir** [comment]
The reason I added the warning was due to multiple issues reported by users when trying to add an egress rule to allow all IPv6 traffic, and the rule being ignored since by default allowAllOutBound is set to true. 
The default condition today creates a weird situation in which not all traffic is allowed by default (only IPv4) and in order to add all IPv6 one needs to set "allowAllOutBound" to false and then add two rules which allows all traffic, to IPv4 and IPv6.

**Comment by joerx** [comment]
Assuming I'm creating an SG for an ECS service, like this:

```typescript
    const serviceSg = new ec2.SecurityGroup(this, "MySg", {
      vpc: props.vpc,
    });

    const service = new ecs.FargateService(this, "Service", {
      securityGroups: [serviceSg],
    });
```

Then allow ingress from, let's say a database:

```typescript
db.connections.allowFrom(serviceSg, ec2.Port.tcp(1234));
```

At this point I'll get the warning, in a (to my knowledge) perfectly valid setup. Trying to "fix" it by setting `allowAllOutbound=false` will break the ECS service since it now can't pull docker images anymore.

IMHO a warning shouldn't be shown here. It can be irritating and in this case destructive.

**Comment by NetaNir** [comment]
Yeah, the `allowFrom` is trying to add an ingress rule to the connection and an egress rule to security group. Since the security group already allows all outbound traffic the warning will be added. I agree that in this case it is not helpful. We will remove the warning once we add Ipv6 to the `allowAllOutBound` implementation.

**Comment by itajaja** [comment]
so is it safe if in EKS' `addAutoScalingGroupCapacity` i set `allowAllOutbound` to false? seems like the default security group does allow outbounds.

**Comment by heiba** [comment]
@NetaNir Please see the picture below. This is an ugly amount of needless warnings that are emitted every time I build a project In CDK all related to the exact same ALB security group, albeit from different ALB listeners.

Please apply a fix to not emit this warning, or at least only emit it once.

This issue has been raised since 10th August 2020, i.e. 10 months ago.

Appreciate your kind action.

![image](https://user-images.githubusercontent.com/4654411/114322667-2369cc80-9b2a-11eb-9e2d-ab8bc686cef4.png)

**Comment by ThomasSteinbach** [comment]
@NetaNir _"We will remove the warning once we add Ipv6 to the allowAllOutBound implementation."_

Is there an issue we can track the status from? We have commented out `--strict` in our CDK deployment with a "TODO - WORKAROUND issue..." comment above. It would be nice having a reference to the progress of the solution, as we regularly try to solve all workarounds.

**Comment by heiba** [comment]
@NetaNir any news on this please ?

**Comment by heiba** [comment]
@NetaNir any news on this please ?

**Comment by automartin5000** [comment]
> Assuming I'm creating an SG for an ECS service, like this:
> 
> ```ts
>     const serviceSg = new ec2.SecurityGroup(this, "MySg", {
>       vpc: props.vpc,
>     });
> 
>     const service = new ecs.FargateService(this, "Service", {
>       securityGroups: [serviceSg],
>     });
> ```
> 
> Then allow ingress from, let's say a database:
> 
> ```ts
> db.connections.allowFrom(serviceSg, ec2.Port.tcp(1234));
> ```
> 
> At this point I'll get the warning, in a (to my knowledge) perfectly valid setup. Trying to "fix" it by setting `allowAllOutbound=false` will break the ECS service since it now can't pull docker images anymore.
> 
> IMHO a warning shouldn't be shown here. It can be irritating and in this case counterproductive.

@rix0rrr @eladb @NetaNir Could we get a comment on fixing this? As previously mentioned, this is a bug when using the CDK _as designed_.

**Comment by CodeExplorer07** [comment]
Any update or fix on this? Observing multiple warnings. 

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/65492599/166411351-a453c923-4cad-48c1-8ead-68818e6ddd0d.png">

**Comment by rtrap-rsi** [comment]
Still no updates on this?

**Comment by bora-7** [comment]
working on a permanent fix

**Comment by metametadata** [comment]
@NetaNir @Styerp @TheRealAmazonKendra

The fix will try to deduplicate the messages. But another important question was not addressed. Users expect no warnings at all as was explained in, say, https://github.com/aws/aws-cdk/issues/9565#issuecomment-695339705. Is issue a ticket to track that problem?

**Comment by Styerp** [comment]
In my opinion, using of this issue to track unwanted messages from the ec2 module subverts the original bug report: duplicate messages in the core module. 

In the interest of not losing the "bad warnings" report, I opened https://github.com/aws/aws-cdk/issues/24109
