### ISSUE TITLE
[aws-ecs-patterns] Attach sg port to ApplicationLoadBalancedFargateService

### ISSUE THREAD

**Issue by kyler-hyuna** [aws/aws-cdk#9572]
### The Question

Hey, I'm trying to create a fargate/ecs setup using ecs patterns `ApplicationLoadBalancedFargateService`. This is a great construct, in that it creates all the necessary target groups and security groups. My application's public port is 8822, but the port for the health check is 8821.

I've been able to change the health check by:
```ts
new ecs_patterns.ApplicationLoadBalancedFargateService()
  .targetGroup.configureHealthCheck({
    port: '8821',
    path: '/monitor',
  });
```

And adding a port mapping for the container via:
```ts
new ecs_patterns.ApplicationLoadBalancedFargateService()
  .taskDefinition.defaultContainer?.addPortMappings({
      containerPort: 8821,
   });
```

The last part I'm unable to figure out is how to allow traffic via the security group between the tasks and the lb. There's no option for `listenerPort` to be an array to allow multiple ports. The generated security group only allows 8822.

### Summary:
How do I add additional ports to the generated security group from `ecs_patterns.ApplicationLoadBalancedFargateService` so both port 8822 (traffic), and 8821(monitor) can be reached from the lb.

### Environment

  - **CDK CLI Version:** 1.57.0
  - **Module Version:** 1.57.0
  - **Node.js Version:** v12.18.1
  - **OS:** OSX Catalina
  - **Language (Version):** TypeScript (3.7.2)

**Comment by neilkuan** [comment]
Hi, any update about this issue?!
In my use case, if my application's  health check port is `9000`,  and api port is `8080`.
I need to define 4 line code to complete my case.

step 1. define api port mapping for health check port.
```bash
apiContainer.addPortMappings(...[{ containerPort: 9000 }]);
```

step 2. settings health check port for target group.
```bash
apifargetsvc.targetGroup.configureHealthCheck({
      path: '/healthchek',
      interval: Duration.seconds(180),
      port: '9000',
    });
```

step 3. Create Ingress Rule at service security group for HealthCheck .
```bash
apifargetsvc.loadBalancer.connections.securityGroups[0].addEgressRule(apifargetsvc.service.connections.securityGroups[0], ec2.Port.tcp(9000));  
 apifargetsvc.service.connections.securityGroups[0].addIngressRule(apifargetsvc.loadBalancer.connections.securityGroups[0], ec2.Port.tcp(9000));```
