### ISSUE TITLE
[aws-ec2] vpc: Support secondary CIDR ranges

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#9573]
It should be possible to specify additional CIDR ranges when creating a VPC using the `ec2.Vpc` construct. Right now, one has to do something like this to add secondary ranges:

```ts
    const cidr = new ec2.CfnVPCCidrBlock(this, "AdditionalCidr", {
      vpcId: vpc.vpcId,
      cidrBlock: "100.64.0.0/16"
    });

    const localZoneSubnet = new ec2.PrivateSubnet(this, "LocalZoneSubnet", {
      availabilityZone: localZoneName,
      vpcId: vpc.vpcId,
      cidrBlock: "100.64.0.0/16"
    });

    localZoneSubnet.addDefaultNatRoute(
      natGatewayProvider.configuredGateways[0].gatewayId
    );

    localZoneSubnet.node.addDependency(cidr);
```

### Use Case

Customers who use multiple CIDR ranges for their VPCs will take advantage of this. For example, EKS customers frequently create non-routable subnets in the 100.64.0.0/10 range to dedicate to their pod-to-pod traffic.

### Proposed Solution

Add an `additionalCidrs` property that takes a list of types. The type should contain the CIDR block and hints about AZ placement and routing for each block.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Good callout. It's another +1 on the signal that we never should have provided the current `Vpc` to begin with, because every other day someone comes in to ask for juuuust one more flag for juuuust one more customization.

Going to close this in favor of https://github.com/aws/aws-cdk/issues/5927
