### ISSUE TITLE
[api-gateway]  docs suggests solution that breaks a number of things.

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#9574]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#breaking-up-methods-and-resources-across-stacks

Not sure to report this as a bug or documentation issue, but the solution presented here breaks a number of things.  For example, if you have defaultCorsFlightOptions, they won't be carried over since the api's are looked up in each stack by ID.

The solution I finely settled on was to manually call addCorsPreflight(...opts..) on each resource and push the method into the array so the stage waits for all of the OPTIONS methods to be created as well before building the deployment.   You can't even pass the cors options into the resource's constructor as a prop since that method will be added silently and you won't have access to it to make the deployment dependent on the method.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
We're tracking this here - https://github.com/aws/aws-cdk/issues/8899
