### ISSUE TITLE
Nuget Package Icons barely visible in Visual Studio dark mode

### ISSUE THREAD

**Issue by ppittle** [aws/aws-cdk#9577]
## :question: General Issue

NuGet package icons are not visible in Visual Studio dark mode. Consider changing the icon colors or using a set color background:

![image](https://user-images.githubusercontent.com/1190907/89839592-f68c9200-db22-11ea-8bc0-9ad52a7de51f.png)

### The Question

Change the nuget icons.

### Environment
 -  **IDE:** Visual Studio 2019  
  - **OS:** Windows 10 
  - **Language (Version):** .net

**Comment by RomainMuller** [comment]
Heh, I guess the transparent background works well on the NuGet gallery but not so much in dark mode IDEs. I think we should be able to use a white background instead, and that'll very much fix that...

**Comment by RomainMuller** [comment]
IIRC, the logo is fetched from URL, and corresponds to [logo/default-256-dark.png](https://github.com/aws/aws-cdk/blob/master/logo/default-256-dark.png)
