### ISSUE TITLE
[cloudfront-origins] All origin access identities have identical names

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9580]
Currently when you use the new cloudfront-origins package to create S3 origins, it generates an OAI with the exact same name each time. If you have multiple origins/distributions you end up with a list of identities all labeled `Allows CloudFront to reach the bucket`. In the console when you inspect the distribution it resolves the comment/name field for this, so you can't tell what distribution is using what without enumerating them using the API.

I'd suggest propagating the origin's logical name in to the comment field to make it clearer which OAI is in use for which bucket/origin.

### Environment

  - **CLI Version      :** 1.57
  - **Framework Version:** 1.57
  - **Node.js Version:** 1.12
  - **OS               :** MacOS
  - **Language (Version):** all

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report! I've posted a PR for the fix.
