### ISSUE TITLE
[aws-s3-deployment] Support for copying an entire remote S3 directory

### ISSUE THREAD

**Issue by sridevi1302** [aws/aws-cdk#9592]
## :question: General Issue

I have a use case to copy the contents of an entire folder in a S3 bucket into another S3 bucket. However, aws-s3-deployment construct only supports destinationBucket + zipObjectKey combination and not destinationBucket+s3PathKey combination. How to achieve this instead of manually calling the construct for every zipObjectKey. 

### The Question
1. Can I specify destinationBucket+s3PathKey combination for a S3 bucket in aws-s3-deployment construct.
2. Is it possible to copy files other than zip files using aws-s3-deployment construct? 

### Environment

  - **CDK CLI Version:** 1.32.2
  - **Node.js Version:** v10.21.0
  - **OS:**  macOS Mojave 
  - **Language (Version):** Java (8)

**Comment by iliapolo** [comment]
Hi @sridevi1302 

> How to achieve this instead of manually calling the construct for every zipObjectKey.

Just to my understanding, does your folder in the S3 bucket contain multiple zip files, and you'd like to copy all of them into another bucket?

Currently, the `BucketDeployment` construct supports full directory copy only from local directories, not remote ones.
I suggest you edit this issue to reflect a feature request for copying remote directories.

**Comment by sridevi1302** [comment]
Yes, as mentioned. I would like to have support for copying S3 remote directories using BucketDeployment

**Comment by jzybert** [comment]
+1 to this issue as it's affecting my team right now. We're using the `BucketDeployment` construct to copy an entire S3 bucket from one account to another upon deployment, but right now the construct is limited to just a single zip file rather than an entire remote directory

**Comment by mccauleyp** [comment]
+1

**Comment by ievgen-boink** [comment]
+1
