### ISSUE TITLE
[aws-apigatewayv2]  resources generated by HttpApi.defaultDomainMapping option should be compatible with previous versions of CDK

### ISSUE THREAD

**Issue by eldargab** [aws/aws-cdk#9602]
### Reproduction Steps

Define HttpApi with cdk version `1.51.0` as follows

```ts
new apigateway2.HttpApi(this, 'Api', {
    defaultDomainMapping:  {
        domainName: domain,
        mappingKey:  ''
    }
})
```

then upgrade to the latest version of CDK and remove `mappingKey` option to map to the `/`.

### What did you expect to happen?

Nothing

### What actually happened?

Deploy fails with  `ApiMapping key already exists for this domain name`.

Seems like this happens, because new ApiMapping is generated with backwards incompatible and ugly name of the form `<DomainName>undefined`.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
@eldargab - this seems to be a miss on our part. This PR - https://github.com/aws/aws-cdk/pull/9141/ - has changed some defaults but was unfortunately not called out as a breaking change. You may have to either manually override the `mappingKey` option for compatibility.

Apologies for that.

**Comment by eldargab** [comment]
As a workaround one should migrate the old definition

```typescript
let res = new apigateway2.HttpApi(this, 'Api', {
    defaultDomainMapping:  {
        domainName: domain,
        mappingKey:  ''
    }
})

res.node.addDependency(domain)
```

to the following 

```typescript
let res = new apigateway2.HttpApi(this, 'Api')

let stage = res.defaultStage!

new apigateway2.HttpApiMapping(stage, domain.toString(), {
    api: res,
    domainName: domain,
    stage
})

res.node.addDependency(domain)
```

This is exactly what CDK is currently doing except for the `HttpApiMapping` name. CDK uses `${domain}undefined`, while snippet above just `domain.toString()`.

Given that 

1. change in question was introduced relatively recently
2. new `HttpApiMapping` names are ugly (with weird undefined at the end)

I'd say this should be treated as an issue and fixed.

**Comment by nija-at** [comment]
@eldargab - help me understand the problem a bit better here.

I've written the same CDK app and am comparing the CloudFormation templates generated between versions `1.51.0` and `1.62.0`.

The CDK app for `1.51.0` looks like -

```ts
new HttpApi(stack, 'api', {
  defaultDomainMapping: {
    domainName,
    mappingKey: '',
  }
});
```

and for CDK `1.62.0`, it looks like - 

```ts
new HttpApi(stack, 'api', {
  defaultDomainMapping: {
    domainName,
  }
});
```

The only difference being the absence of the `mappingKey`. Between these two versions of the app, the only 'effective' difference in the CloudFormation templates produced is that the [`ApiMappingKey` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-apimapping.html#cfn-apigatewayv2-apimapping-apimappingkey) is `''` in the former and absent in the latter.

Besides the weirdly named logical ids that have `undefined` in their name, what specific problem are you facing. 
Are you looking to specify `''` (empty string) as a mapping key?

**Comment by chasemaier** [comment]
Using CDK 1.86.0  and I'm still seeing the generated names with `undefined` embedded. Even though it is likely harmless (given it seems to just be the names), it is concerning to see `undefined` and should probably be handled more gracefully when generating names.
