### ISSUE TITLE
[@aws-cdk/assert] Assertions library for Python

### ISSUE THREAD

**Issue by srethira** [aws/aws-cdk#9614]
[@aws-cdk/assert](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/assert) is only available in Typescript and Javascript. Would like this feature to be supported in Python for Unit and Integration testing.

**Comment by Juberstine** [comment]
+1

**Comment by Zirkonium88** [comment]
+1

**Comment by wuqunfei** [comment]
+1

**Comment by aserour** [comment]
+1

**Comment by domtes** [comment]
While trying to build my an assertion library in Python I've found out that the `aws-cdk.cloudformation-diff` packages is not exported to other languages.

Making it available would be useful to build a consistent assertion library in python and other languages.
The language-specific assertion libraries could then be built mimicking the same design of the embedded Typescript one.

**Comment by nideveloper** [comment]
As more and more languages are supported by CDK, a consistent infra testing experience is 100% needed. I thought there already was an issue or an RFC for a multi lang assert library from 2018/19 but I can't find it now. It may be this on the rfc https://github.com/aws/aws-cdk-rfcs/issues/4

**Comment by nija-at** [comment]
Thanks @nideveloper and others. We've heard this feedback from customers and intend to make this available for all our supported languages.

The work involved is non-trivial, so it may be a bit of time before we can get to this.

**Comment by michaelbrewer** [comment]
yep, otherwise Typescript is the only runtime that is fully supported

**Comment by nija-at** [comment]
This work is complete. Please use the new module '@aws-cdk/assertions' that is available in all languages.
