### ISSUE TITLE
[core] know from within the script which action is executed

### ISSUE THREAD

**Issue by robert-hanuschke** [aws/aws-cdk#9619]
I would like to know inside my CDK script which action is being executed on it - be it synth, deploy, destroy etc.

#### Reusable stacks

Defining reusable stacks and resources requires to provide differences as context variables. E.g. using a service name in a resource name is possible when having it defined as (in my case Python):

`name=f"{self.node.try_get_context('service')}-example-resource"`

Then I can successfully deploy different instances by specifying the variable on the command line as context:

`cdk deploy my-reusable-stack --context service="my-service-A"`

However, now I also need to specify the context variable even for every synth to not get an error. From within the script, for that case I'd like to check if this is a synth action and set the service variable to a dummy value.

#### Context sensitive actions

For example, I'd like to execute additional actions if my "stage" context variable is "prod", but only if the action is "deploy" or "destroy", e.g. update an asset inventory that does not include non-prod resources or any other action dependent on a combination of those contexts.

### Proposed Solution

Something like a "get_cdk_action" function, to be used like this for the use cases mentioned above:

```
if self.node.get_cdk_action() == "synth":
    active_service = "Dummy"
```

```
if self.node.get_cdk_action() == "deploy" and self.node.try_get_context('stage') == "prod":
    update_inventory()
```

### Other

I realize those could be achieved by wrapper scripts but I really don't see why I should do that and have to take care of handling exit codes and outputs of the external cdk command if I can do basically everything in app.py already - just limited by not knowing the full execution context.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Related to #9540

**Comment by eladb** [comment]
It's not considered a healthy practice to change the behavior of a CDK app based on the CLI operation. CDK apps are expected to simply synthesize the output. The the resulting "cloud assembly" can later be interacted with using the CLI or in CI/CD systems.

If you wish to pass context to your CDK app based on some external state, although not recommended, you can either use simply environment variables or `--context`. Either way, I don't think this is something we will likely support.

#9540 is related and we may introduce some information about the operation context just as an optimization.
