### ISSUE TITLE
[aws-cloudfront] Support setting forwarded header values in distributions

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9621]
I expected to be able to set a list of header values to forward on my cloudfront distribution. This is possible with a WebDistribution, but not with the newer Distribution construct. The header values are hardcoded currently instead of being accessible via a prop.

### Use Case

To use things such as CORS

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
This is now supported via the new [Cache Policies](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudfront#customizing-cache-keys-and-ttls-with-cache-policies) construct. This was merged as part of #10656 and will go out with the next release.

```ts
const myCachePolicy = new cloudfront.CachePolicy(this, 'myCachePolicy', {
  headerBehavior: cloudfront.CacheHeaderBehavior.allowList('X-MyCustomHeader'),
});
new cloudfront.Distribution(this, 'myDistCustomPolicy', {
  defaultBehavior: {
    origin: bucketOrigin,
    cachePolicy: myCachePolicy,
  },
});
```
