### ISSUE TITLE
[pipelines/codepipeline] improve existing Action interface

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#9624]
Need to address the following:

* More flexible ordering among Actions (autoderive ordering via artifacts and other relative "before/after" constraints)
* Change ordering among Stages (necessary to insert stages later)
* Make it easier to create new Actions (current interface is rather cumbersome, around `actionProperties()/bind()/bound()`).

More abstract things to think about:

* Compound actions?
* Should actions and stages not have been constructs?
* It should be easy to add a CodeBuild project to a pipeline "in one go", while allowing max. customization

---

This is a :rocket: Feature Request

**Comment by pcolazurdo** [comment]
Facing an issue related with this when trying to add permissions to the Action Role. As the Role is not exposed directly I'm finding very hard to use the existing interfaces to modify this.

**Comment by skinny85** [comment]
Why do you need to add permissions to that Role @pcolazurdo ?

**Comment by pcolazurdo** [comment]
In my case, I need to use a [Full Clone](https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-codecommit-gitclone.html) to use AWS Copilot CLI - The permission setup for this are documented [here](https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-codecommit-gitclone.html#tutorials-codecommit-gitclone-rolepolicy) and [here](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeCommit.html#action-reference-CodeCommit-config)

**Comment by skinny85** [comment]
I feel like that's more of a matter of the `CodeCommitSourceAction` not having support for that option.

But thanks!

**Comment by pcolazurdo** [comment]
I've also created a FR for the ```CodeCommitSourceAction``` but that will only solve the CodeCommit permissions, it should not change the CodeBuild construct.

Additionally, in my use case, I also had to add a policy to let the CodeBuild Role to assume a Role created by AWS Copilot to let CodeBuild call a stack change (this is due to how Copilot works but I can see this happening with other tools/frameworks)

**Comment by rix0rrr** [comment]
This change is unlikely to be necessary anymore as we've changed strategies for https://github.com/aws/aws-cdk/issues/10872
