### ISSUE TITLE
[core] Make use of methods using ${TOKEN concept and avoid `Don't know how to convert object to JSON`

### ISSUE THREAD

**Issue by nmyster** [aws/aws-cdk#9646]
### The Question

*How do I make use of methods which use the ${TOKEN concept and avoid the `Don't know how to convert object to JSON:' Errors I keep receiving for what feels like simple interactions*

#### Detail 

When it comes to creating constructs and making use of various other construct features, it seems that my App Synth breaks very quickly when a Construct method returns a `${TOKEN..`. value.

I found several examples where my code will break because the value of a property has rendered to a `${TOKEN...` which my Stack trace then complains that `Don't know how to convert object to JSON:`

My use case is that I want to package up a few resources which originate from a Construct (Instance/Role/Sg) where that construct makes use of things like lookups - so I can attach an existing Sg to the Instance, or get an existing Role or set the VPC of the SG/Instance based on a common name used in the lookup.

A further example is when trying to create and use CfnParameter within a construct - Due to the limitations of being able to pass secure values to certain resources that make use of the SSM Resolver functionality, I am getting around this by using a CfnParameter with NoEcho and then providing that secure value on deploy.

Using this Constuct within my new construct results in the same `Don't know how to convert object to JSON:`

The docs explain what ${TOKEN is used for which is fine but it's not clear where I can or can't use it and the limitations above (hoping to be told this is user error) make the scope of constructs somewhat limited where I want to use lookups/other functionality that returns a `${TOKEN...`

**Comment by Jerry-AWS** [comment]
I'd like to beef up the CDK Developer Guide tokens material if there's beefing to be done.

**Comment by eladb** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
