### ISSUE TITLE
[cloudfront] Origin request policies

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#9647]
The CloudFormation v16.2.0 spec ~~(pending #9452)~~ introduced origin request policies for behaviors. Origin request policies supersede the existing properties (and new ones) for values that are added to requests to the origin.

See:
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/controlling-origin-requests.html
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html

This feature request is to add support for both origin request policies in general, and the managed origin request policies as well.

*Notes:*
* This is for support for the new `Distribution` construct; the older `CloudFrontWebDistribution` is out of scope.

---

This is a :rocket: Feature Request

**Comment by mmeylan** [comment]
@njlynch Is there a plan to support this for `CloudFrontWebDistribution` ? Or, as you suggest, is `Distribution` the preferred over `CloudFrontWebDistribution` ?

**Comment by njlynch** [comment]
@mmeylan - see https://github.com/aws/aws-cdk/issues/10830 for the tracking issue. Please :+1: (or submit a PR!) :D

**Comment by mmeylan** [comment]
Thanks @njlynch ! 

Do you have any idea if this origin request policy control is new or if Cloudfront is currently becoming stricter about it ? We didn't have CORS issue with a live deployment so far using `Use legacy cache settings`, and this morning, we had CORS issue for some of our urls, but not all.
