### ISSUE TITLE
[amplify] missing enableBranchAutoDeletion option

### ISSUE THREAD

**Issue by martinbiard** [aws/aws-cdk#9650]
The `amplify.App` class is missing the `enableBranchAutoDeletion` option.

### Use Case

We would like to start using the experimental `amplify.App` but currently have to use `amplify.CfnApp` for the ability to activate the `enableBranchAutoDeletion` option.

### Other

- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-amplify.CfnApp.html
- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-amplify.App.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
@martinbiard you can use the "escape hatch" in the meantime:

```ts
const app = new amplify.App(this, 'App', { ... });
const cfnApp = app.node.defaultChild as amplify.CfnApp;
cfnApp.addPropertyOverride('EnableBranchAutoDeletion', true);
```
