### ISSUE TITLE
[@aws-cdk/core] Issue Creating Stack in Unit Tests after 1.58.0 Update

### ISSUE THREAD

**Issue by dennymorrison** [aws/aws-cdk#9659]
With the 1.58.0 update all of my tests fail with the following error:
`unexpected: all stacks must be part of a Stage or an App`

All of these tests pass under 1.57.0, and reading the release notes for 1.58.0 it seems like the code below should still work.

### Reproduction Steps
```
const stack = new Stack();
new Bucket(stack, 'bucket');
expectCDK(stack).to(haveResource('AWS::S3::Bucket'));
```

### What actually happened?
The test fails with the following error:
`unexpected: all stacks must be part of a Stage or an App`

I thought what the heck, make an app and pass that into the stack as its scope, but even with that I still got the same error.

### Environment

  - **CLI Version: 1.58.0**
  - **Framework Version:1.58.0**
  - **Node.js Version:** 12.18.2
  - **OS** : macOS 10.15.6
  - **Language (Version):** Typescript

--- 

This is :bug: Bug Report

**Comment by srinika** [comment]
I am having the same issue with 1.58.0 update.

**Comment by vipul0092** [comment]
Having the same issue as well with 1.58.0

**Comment by beatleboy501** [comment]
+1

**Comment by eladb** [comment]
I suspect this might be a result of multiple versions of CDK modules in your `node_modules`. Can you please verify your `package.json` uses the same version for all CDK modules, nuke your `node_modules` and re-run `npm install` (or `yarn install`)?

**Comment by eladb** [comment]
Please comment if the proposed solution did not work.

**Comment by caveman-dick** [comment]
Clearing out the `node_modules` folder wasn't enough for me, I had to nuke the `package-lock.json` too. Seems to be every CDK upgrade I'm having to do this. It's getting a bit boring now! 😞

**Comment by mospina** [comment]
I an having the same issue with 1.68.0

**Comment by msimperi** [comment]
I was having the same issue with 1.69.0, I tried to clean node_modules folder etc. but it didn't help. Now 1.70.0 upgrade fixed the issue.

**Comment by Sergio-PB** [comment]
Having the same problem even with 1.70.0
