### ISSUE TITLE
AWS CDK stack names.

### ISSUE THREAD

**Issue by laimonassutkus** [aws/aws-cdk#9662]
AWS CDK usually modifies logical ids of the resources to avoid name clashes. This is applicable for stacks too. Except for the main stack. How can I achieve normal unmodified logical ids of stacks as the parent (root) stack?

### Reproduction Steps

- Create a stack.
- Inside that stack create other stack.

### What did you expect to happen?

Stacks logical ids:
PvMi-Core-Main
PvMi-ContactCenter-ContactCenterStack

### What actually happened?

Stacks logical ids:
PvMi-Core-Main
PvMiCoreMainPvMiContactCenterContactCenterStack321A5E85

### Environment

  - **CLI Version      :** aws-cli/1.18.49 Python/3.6.0 Windows/10 botocore/1.15.49
  - **Framework Version:** 1.45.0 (build 0cfab15)
  - **Node.js Version:** v12.16.2
  - **OS               :** Windows
  - **Language (Version):** Python 3.8

--- 

This is :bug: Bug Report

**Comment by laimonassutkus** [comment]
How one would avoid this logical ids generation nonsense?

**Comment by hoegertn** [comment]
You can override the logical id of constructs. But I do not think this qualifies as a bug as it is the intended behavior to generate logical ids for all resources.

**Comment by laimonassutkus** [comment]
Can you please share some specifics about "You can override the logical id of constructs."?

Thank you.

**Comment by hoegertn** [comment]
The Cfn* objects have a method `overrideLogicalId` that can be used. You have to get the underlying Cfn* object using the `res.node` syntax if you use L2 or L3 constructs. 

Beware: The node field will be renamed soon

**Comment by laimonassutkus** [comment]
And how about "not" cfn resources?

I am talking specifically about "from aws_cdk.core import Stack"

**Comment by hoegertn** [comment]
For the stack it should be possible to set the stackName property on the object properties.

**Comment by laimonassutkus** [comment]
FYI. Setting stack name does not affect logical id.

**Comment by hoegertn** [comment]
Can you provide a minimal example repo? I can then try to dig deeper and see how you can achieve the desired result.

**Comment by laimonassutkus** [comment]
**app.py**:

`from aws_cdk import core

app = core.App()

stack1 = core.Stack(app, 'Stack1', stack_name='Stack1')
stack2 = core.Stack(stack1, 'Stack2', stack_name='Stack2')

app.synth()`

**cdk list** results in:
Stack1
Stack1Stack2DCD8AFBC

**Comment by laimonassutkus** [comment]
By the way, to get (lets say print) these modified stack ids you first need to syth the cdk app and then iterate through CF artefacts:
```
assembly: CloudAssembly = app.synth()
stacks: List[CloudFormationStackArtifact] = assembly.stacks

for stack in assembly.stacks:
    print(stack.id)
```

**Comment by eladb** [comment]
@laimonassutkus `cdk list` prints the list of stack artifact IDs, not stack names. That's why you are seeing these results. The stack names as deployed by `cdk deploy` will be the ones you want.
