### ISSUE TITLE
[applicationautoscaling] Typo in doc string

### ISSUE THREAD

**Issue by saiprasanna94** [aws/aws-cdk#9678]
https://github.com/aws/aws-cdk/blob/09e994a204697930987ee9fa420ccbe1b20fb97b/packages/%40aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts#L227

CPU should be replaced with memory here
I guess this code was copied from above and the dev forgot to change the keyword.

My first github issue!

**Comment by NetaNir** [comment]
So how about a first GitHub PR? :)
