### ISSUE TITLE
[aws-chatbot] L2 support for SlackChannelConfiguration

### ISSUE THREAD

**Issue by luckily** [aws/aws-cdk#9679]
Currently there's only L1 resources in `CfnSlackChannelConfiguration` of aws-chatbot.
Let's create L2 construct support.

### Use Case And Proposed Solution
It's just like we create slack channel configuration via AWS web console.
There is pseudocode as below:
```ts
const slackChannel = new chatbot.SlackChannelConfiguration(this, 'MySlackChannel', {
  slackChannelConfigurationName: 'test-channel',
  slackWorkspaceId: 'YOUR_WORKSPACE_ID',
  slackChannelId: 'YOUR_CHANNEL_ID', 
});

slackChannel.addLambdaInvokeCommandPermissions();
slackChannel.addNotificationPermissions();
slackChannel.addSupportCommandPermissions();
slackChannel.addReadOnlyCommandPermissions();

slackChannel.addToPrincipalPolicy(new iam.PolicyStatement({
  effect: iam.Effect.ALLOW,
  actions: [
    's3:GetObject',
  ],
  resources: ['arn:aws:s3:::abc/xyz/123.txt'],
}));

```

### Other
Associate with #5020 

cc @skinny85 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by humanzz** [comment]
Hey @luckily, it's great that you're looking into this because between @Stacy-D and myself, we too were keen to get an L2 construct very similar to what you proposed above in https://github.com/aws/aws-cdk/issues/8636#issuecomment-673452381.

Just to avoid duplication of efforts, I wanted to connect to know if you're planning to progress this soon with a contribution? Our initial plan was to try to do that sometime over next week but if you're going to be doing that we'd happily step back and await for your contribution :)

**Comment by luckily** [comment]
Hi @humanzz, I'm so happy that you have similar problem.

I have some plans to resolve this [issue](https://github.com/aws/aws-cdk/issues/5020) and this is [my proposed](https://github.com/aws/aws-cdk/issues/5020#issuecomment-668723373).

These include:
1. L2 construct for CfnSlackChannelConfiguration of chatbot package.
2. L2 construct for CfnNotificationRule of codestarnotification package.
3. `addNotification({...})` method of codebuild and codepipeline depend on above implements.

See also: #9680 #9682

**Comment by humanzz** [comment]
@luckily Thanks for acting super quickly on this... we can't wait till this gets merged/released :)

**Comment by skinny85** [comment]
@humanzz if you want to add your review to #9702 (is it similar to your own solution?).

**Comment by humanzz** [comment]
It’s quite similar but I’ll defer to @Stacy-D as she was the one actually working on it.
