### ISSUE TITLE
[cli/pipelines] Describe bootstrapping protocol

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#9681]
Describe bootstrapping, what it does, what it needs, and specifically:

# How to customize

We need this in order to close all the "I need such and such bootstrap customization" issues.

There are very many of those, including multiple "enable encryption"/"disable encryption"/"import existing bucket" ones. They will all be resolved.

---

This is a 📕 documentation issue

**Comment by Jerry-AWS** [comment]
This is now in the Developer Guide.

https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html
