### ISSUE TITLE
[core] expose the value of --profile inside the CDK

### ISSUE THREAD

**Issue by mark-ashton** [aws/aws-cdk#9683]
If I execute a cdk command like this:
`cdk synth myStack --profile myProfile`
... then I have access to the Account value from within the cdk using `System.Environment.GetEnvironmentVariable("CDK_DEFAULT_ACCOUNT")`

It would be really useful to have access to the profile that was used to run a CDK command, or 'default' if none was provided.

### Use Case

Maybe what I am doing is a bit off the beaten path, but I am trying to use the SDK from within my CDK to check for existence of a parameter store entry: if the parameter store entry does not exist then I want to create it with a long random value, if it does exist then I want my synth'd template to just use that existing value.
This parameter store value is associated with a single service I am deploying with the CDK so it makes sense (to me) to keep that definition close to the service, rather than have to deploy it as a different stack.

At the moment I am struggling to find a way to give `AmazonSimpleSystemsManagementClient` a suitable set of credentials (those specified by the `--profile myProfile` CLI args to the CDK) because I can't find a way to retrieve the profile that was used.
If I was just using default profile then I think it would just work, but I'm not.

### Proposed Solution

`stack.Profile` ?

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Accessing network resources from within a CDK app is not recommended. It can cause different "synth" runs to result in a different output, which is against best practices for build tools (which "synth" is).

The CLI profile name is very environment-specific. Relying it in a CDK app can be tricky (e.g. `test` can mean different things in different environments).

Given it's potential for abuse, we prefer to not add explicit support for this feature.

If your use case requires this and you have no other choice, you could always use an environment variable to specify the profile (`AWS_PROFILE`) and then read it in your CDK app through `process.env.AWS_PROFILE`. There is no need for explicit CLI support.

**Comment by mark-ashton** [comment]
Thanks for feedback @eladb. Using `--context` or `--parameters` you can already produce CDK code that results in different outputs, but I take your point. In the end I used `--context` to achieve what I wanted without having use the SDK client.

**Comment by marc-guenther** [comment]
I don't understand. I need to use the SDK due to #6176.

When I specify a `AWS_PROFILE` env variable, everything is fine, as both CDK and SDK support that variable. But when I use `--profile`, SDK doesn't know anything about it, and happily talks to the wrong account, which results in errors.

I could tell my users to never use `--profile`, but I would prefer that it works as expected.
