### ISSUE TITLE
[core] Support importing existing orphaned resources to CloudFormation stacks

### ISSUE THREAD

**Issue by kennu** [aws/aws-cdk#9686]
CloudFormation has support for [importing existing resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-existing-stack.html) into a stack. You can use the [ResourcesToImport parameter to createChangeSet](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#createChangeSet-property) to do it.

Could AWS CDK support importing existing resources? The current implementation that calls [createChangeSet](https://github.com/aws/aws-cdk/blob/72ec59b2108fabea4b52f32dbb0184b12d591aff/packages/aws-cdk/lib/api/deploy-stack.ts#L223) does not seem to pass the ResourcesToImport parameter in any situation.

I tried to search for existing issues about this. They are hard to find because many issues talk about importing exported values or importing a reference to a resource in another stack. But here I mean importing orphaned cloud resources.

### Use Case

Typical use cases are:
* Moving resources from one CloudFormation stack to another
* Splitting CloudFormation stacks when they become too big
* Adopting an orphaned resource because a stack was broken and had to be deleted
* Adopting a resource that was created manually before CloudFormation supported the resource type

These use cases are important when the orphaned resource contains data, e.g. a DynamoDB table or a S3 bucket that cannot be deleted.

### Proposed Solution

I am not sure about all the details that are related using to ResourcesToImport. It probably requires a lot of testing with different AWS [resource types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html) to make it work.

In a perfect world AWS CDK would automatically import named resources when it notices that the resource already exists outside the stack. It would ask the user for confirmation if there are any issues, like having to tune the resource policy/permissions/properties to make the import work.

---

This is a :rocket: Feature Request

**Comment by Jerry-AWS** [comment]
There are ways to use existing resources in CDK apps. See the [Resources](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_importing) topic in the Developer Guide. Does that help?

**Comment by kennu** [comment]
@Jerry-AWS No. Like I said in the issue description, I'm not talking about referring to external resources. I'm talking about importing orphaned resources back into a CloudFormation stack so that CloudFormation actually takes ownership of the resource. CloudFormation supports this, so I think AWS CDK could support it too.

**Comment by NetaNir** [comment]
We are tracking this in the RFC repo, see https://github.com/aws/aws-cdk-rfcs/issues/52. Closing this in favor of the RFC issues.

**Comment by hugomallet** [comment]
Is there any workaround to reattach an orphaned s3 to cdk stack ?
As fromBucketArn doest not allow to modify an existing s3 bucket, i am facing a deadlock ...

**Comment by jaecktec** [comment]
@hugomallet when you create a new stack you can import resources. 
For that 'synth' your stack and when creating you chose 'with existing resources' 

however you maybe need to add some additional parameters like 'retention' to the resources. (the cloud-formation import is so nice to prompt you why it failed)
