### ISSUE TITLE
[api-gateway] Access log must include at least `AccessLogFormat.contextRequestId()`when tokenized format is passed

### ISSUE THREAD

**Issue by vad3x** [aws/aws-cdk#9687]
I'm trying to use `Stage` construct with format by SSM key (so my format is similar to `'${Token[TOKEN.65]}'`).

```
    this.stage = new apigateway.Stage(this, 'Stage', {
      ...
      accessLogFormat: apigateway.AccessLogFormat.custom(props.apiGatewayAcessLogFormatSsmKey),
      accessLogDestination: new apigateway.LogGroupLogDestination(this.apiGatewayLogGroup),
      ...
    });
```

### What did you expect to happen?

No error.

### What actually happened?

Error: "Access log must include at least `AccessLogFormat.contextRequestId()`"

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/stage.ts#L213

### Environment

  - **CLI Version      : 1.57**
  - **Framework Version:1.57**
  - **Node.js Version: v12.14.0** 
  - **OS               : macOS 10.15.4**
  - **Language (Version): TypeScript (3.9.7)** 

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
@vad3x -

As called out in the error message, the string value passed to `AccessLogFormat.custom()` must contain the context request id.

Update your string to include this.

```ts
accessLogFormat: apigateway.AccessLogFormat.custom(`${AccessLogFormat.contextRequestId()} ${props.apiGatewayAcessLogFormatSsmKey}`),
```

**Comment by vad3x** [comment]
@nija-at Thank you for the workaround.

I guess your proposal will omit the error, but this will change the expected log format provided by the external output (SSM in my case).

**Comment by nija-at** [comment]
This is a requirement enforced by API Gateway - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-stage-accesslogsetting.html#cfn-apigateway-stage-accesslogsetting-format

**Comment by vad3x** [comment]
Correct, but I'm not sure why you do the check on CDK sync level, I assume CF will fail the resource creating in case when `$context.requestId` is not on the format.
But my format is not a string, it's a reference:

Expected CDK output:
```
...
          "Format": {
            "Fn::ImportValue": "stack-name:ExportsOutputRefSsmParameter......"
          }
...
```

This is working CF output because `apiGatewayAcessLogFormatSsmKey` output value already contains `$context.requestId`.

**Comment by nija-at** [comment]
Ah ok, I see what the problem is. We need to exclude the validation if the string is a token.

**Comment by vad3x** [comment]
Looks like that :)
