### ISSUE TITLE
[aws-cognito] documentation should change emailTransmission to emailSettings

### ISSUE THREAD

**Issue by gregorypierce** [aws/aws-cdk#9693]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html#emails

The documentation discusses a feature for emailTransmission:

  emailTransmission: {
    from: 'noreply@myawesomeapp.com',
    replyTo: 'support@myawesomeapp.com',
  },

But this feature does not actually exist in the UserPool. There is a feature/property "emailSettings" that has the same signature and it is possible that this is the intended feature:

  emailSettings: {
    from: 'noreply@myawesomeapp.com',
    replyTo: 'support@myawesomeapp.com',
  },

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Correct. This is a mis-type in the documentation
