### ISSUE TITLE
Release notes for v1.58.0 reflect a reverted change.

### ISSUE THREAD

**Issue by guidola** [aws/aws-cdk#9700]
---

This is a 📕 documentation issue

## The issue

#9637 reverted the introduction of Construct.construct while the release notes for v1.58.0 still hold the change as being introduced by the release.

Might be interesting to remove the following line: 

> * core: deprecate "Construct.node" in favor of "Construct.construct" (#9557) (aa4c5b7), closes /github.com/aws/aws-cdk-rfcs/blob/master/text/0192-remove-constructs-compat.md#10

from the release notes for that tag as performing the recommended code change would not be successful.

**Comment by eladb** [comment]
Thanks, done.
