### ISSUE TITLE
applyAspect visits same node twice in Version 1.58

### ISSUE THREAD

**Issue by lanefelker** [aws/aws-cdk#9706]
When upgrading to version 1.58 we started to get an error where apply aspect visited the same node twice causing the second operation to fail

### Reproduction Steps

An apply aspect on an api as follows:
```
const optionsIntegration = lambdaIntegration(api, lambda)
api.node.applyAspect({
    visit: (node: cdk.IConstruct): void => {
      // Add OPTIONS to all resources
      if (node instanceof apiGateway.Resource) {
        node.addMethod('OPTIONS', optionsIntegration)
      }
    }
})
```

and an apigateway with one resource. For example:
```
const resource = api.root.addResource('resource')
resource.addMethod('GET', new apigateway.MockIntegration())
```
### What did you expect to happen?
apply aspect only visits each node once

### What actually happened?
An error occurred  "Error: There is already a Construct with name 'OPTIONS' in Resource [resource]"

### Environment

  - **CLI Version: ** 1.58.0
  - **Framework Version:**  1.58.0
  - **Node.js Version:** v11.10.1
  - **OS:** Mac OS X Catalina
  - **Language (Version):** 3.9.2

### Other

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
I wasn't able to reproduce this issue... here is the code I tried on v1.58 which synthesized and deployed without warnings:

```
import * as apigateway from '@aws-cdk/aws-apigateway';
import * as lambda from '@aws-cdk/aws-lambda'
import * as cdk from '@aws-cdk/core';

export class CdkTestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const func = new lambda.Function(this, 'MyFunction', {
      runtime: lambda.Runtime.NODEJS_12_X,
      code: new lambda.InlineCode('exports.handler = function() { console.log("Hello!") }'),
      handler: 'index.handler',
    });

    const api = new apigateway.RestApi(this, 'MyApi');
    const resource = api.root.addResource('resource');
    resource.addMethod('GET', new apigateway.MockIntegration());

    const optionsIntegration = new apigateway.LambdaIntegration(func);
    api.node.applyAspect({
      visit: (node: cdk.IConstruct): void => {
        if (node instanceof apigateway.Resource) {
          node.addMethod('OPTIONS', optionsIntegration)
        }
      }
    });
  }
}
```

Maybe the behavior has something to do with interaction with other constructs/aspects in your stack? There was a change to aspects introduced in #9558, so it's possible there's a regression, but it's hard for me to pinpoint.

**Comment by eladb** [comment]
@NetaNir can you take a look?

**Comment by NetaNir** [comment]
Which version did you upgrade from? It's hard to tell what could be the problem without seeing how is `api` created. 
Can you try and log the node path from the visit method:

```ts
api.node.applyAspect({
    visit: (node: cdk.IConstruct): void => {
      // Add OPTIONS to all resources
      if (node instanceof apiGateway.Resource) {
       console.log(node.node.path);
        node.addMethod('OPTIONS', optionsIntegration)
      }
    }
})
```

Might give some clue as to what is hapnning
