### ISSUE TITLE
[aws-cognito] Add support for Amazon Pinpoint

### ISSUE THREAD

**Issue by gregorypierce** [aws/aws-cdk#9731]
Amazon pinpoint is a messaging service provided by Amazon that allows a managed way to send SMS, Voice, Email, PushNotifications, etc. Ideally when setting up a cognito stream we would be able to point it at the SNS and SES channels that are already behind Pinpoint as those channels handle messaging and templating.

### Use Case

This feature is necessary to avoid duplicating message delivery channels as the channels created using plain SES and SNS are not visible to Pinpoint. In addition, this would allow one to avoid creating unnecessary roles for this functionality.

### Proposed Solution

When configuring Cognito, one should be able to specify a Pinpoint Application and have Cognito retrieve the CfnEmailChannel and CfnSMSChannel from the Pinpoint Application in order to setup the SES and the SNS delivery mechanisms specifically. This will provide better integration between the messaging platform and the user management platform inside of CDK.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
This feature is supported in CloudFormation on the [`UserPoolClient` resource type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-analyticsconfiguration).
