### ISSUE TITLE
[aws-ec2] Vpc.fromLookup() does not identify publicSubnet properly

### ISSUE THREAD

**Issue by davxiao** [aws/aws-cdk#9735]
According to [AWS doc](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#vpc-subnet-basics), 

> If a subnet's traffic is routed to an internet gateway, the subnet is known as a public subnet.

But apparently ec2.Vpc.fromLookup() checks whether a public subnet (associated with a route table that has default routes to IGW) has 'Auto-assign public IPv4 address' enabled, if that is not enabled, the subnet is deemed as private. 

I think it is a bug because it contradicts the definition of public subnet given by aws doc above.

### Environment

  - **CLI Version      : Latest CDK CLI

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It does both: https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/context-providers/vpcs.ts#L69
