### ISSUE TITLE
[core] Do not ignore Egress rules when 'allowAllOutbound' is set to true

### ISSUE THREAD

**Issue by manospasj** [aws/aws-cdk#9740]
I have a multi-stack app that creates an Application Load Balancer in Stack A and some ECS Fargate tasks in Stack B. The Fargate tasks are also registered as targets in the Load Balancer in Stack B. The Load Balancer Security Group was initially created with 'allowAllOutbound' set to true.

Yesterday I updated aws-cdk to version 1.58.0 and I started getting a `Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup` warning.

Since the app is already deployed, if I set the 'allowAllOutbound' to false, CloudFormation will remove the 'allowAllOutbound' egress rule from the Load Balancer Security Group during Stack A deployment and will then add the individual egress rules for each Fargate task during Stack B deployment. That means that the Load Balancer will stop routing requests to Fargate during deployment of the new infrastructure, which is not acceptable.

### Proposed Solution

I see 3 options:

- Do not display this warning at all. It is generally acceptable to allow all outbound connections in Security Groups.
- Display the warning, but create the individual Fargate egress rules along with the 'allowAllOutbound' rule. This will allow me to disable the 'allowAllOutbound' without any issues.
- Allow people to hide specific warnings using a config file.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by manospasj** [comment]
This is related to https://github.com/aws/aws-cdk/issues/9565

**Comment by NetaNir** [comment]
You can set `allowAllOutbound` to false and set the egress rules using `addEgressRule`.
The current implementation of `allowAllOutbound ` does not allow IPv6 traffic, so it's not all traffic :/, which is why the warning was added. The right way to fix this is to change the implementation of `allowAllOutbound `, since this will be a breaking change we will need to do it behind a feature flag.

**Comment by heiba** [comment]
Hello @NetaNir, any news on this please ?

**Comment by heiba** [comment]
@NetaNir any news on this please ?

**Comment by bestickley** [comment]
Has anyone been able to successfully ack this warning?
When I run `cdk ack @aws-cdk/aws-ec2:ipv4IgnoreEgressRule` the warning still shows. My full warning is:

> [Warning at /lh-stickb/chatbot/ChatFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]

**Comment by modosc** [comment]
it resolves to `

> Has anyone been able to successfully ack this warning? When I run `cdk ack @aws-cdk/aws-ec2:ipv4IgnoreEgressRule` the warning still shows. My full warning is:
> 
> > [Warning at /lh-stickb/chatbot/ChatFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]

fyi i filed https://github.com/aws/aws-cdk/issues/33804 since it's not just this warning that has this issue.
