### ISSUE TITLE
[python] Enum values are equal to their member names

### ISSUE THREAD

**Issue by jessecollier** [aws/aws-cdk#9742]
I noticed all the Enum classes that are converted to python do not have their correct values associated to them.

You can see in the python docs associated with any Enum, for example [ScalingProcesses](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/ScalingProcess.html).

### Reproduction Steps

```
>>> import aws_cdk.aws_autoscaling as autoscaling
>>> autoscaling.ScalingProcess.AZ_REBALANCE.value
'AZ_REBALANCE'
```

### What did you expect to happen?

```
>>> import aws_cdk.aws_autoscaling as autoscaling
>>> aws_cdk.aws_autoscaling.ScalingProcess.AZ_REBALANCE.value
'AZRebalance'
```

### What actually happened?

```
>>> import aws_cdk.aws_autoscaling as autoscaling
>>> autoscaling.ScalingProcess.AZ_REBALANCE.value
'AZ_REBALANCE'
```

### Environment

  - **CLI Version      :** 1.59.0
  - **Framework Version:**
  - **Node.js Version:** v12.18.2
  - **OS               :**
  - **Language (Version):** Python 3.7.8

### Other

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
It looks like the Python docs are consistent with the behavior shown, as there is no mention of AZRebalance. I think what you're looking for is currently a limitation of JSII, the library which processes and packages `aws-cdk` from TypeScript into other-language libraries (see [here](https://github.com/aws/jsii/blob/fa60b7f3d4268cd426d519bab9c738507c1ae503/docs/specifications/2-type-system.md#enum)). What's the use case that you need the base string value for?

**Comment by jessecollier** [comment]
I wasn’t sure which repo was the appropriate place to open the ticket.

I’ve written my own autoscaling construct that uses launch templates and
wanted to leverage the existing Enums.

I can easily write my own Enum, but wanted to report it since I hadn’t seen
any other issues mentioning it.

-- 
-Jesse Collier

**Comment by RomainMuller** [comment]
The `jsii` type model does not currently represent enums as string- or int-valued; they are just a set of opaque constants. Some languages do not support enum constant valuation in the same way that JavaScript does, so this is a somewhat tricky feature to add in the future, too.

I am curious what is the use-case you're pursuing where not having the string value of the enum constant is problematic. Can you elaborate on this?

**Comment by jessecollier** [comment]
hey @RomainMuller -- I totally get it.

In the case of `aws_cdk.autoscaling.ScalingProcess` Enum, it provides a list of acceptable values I can use. For example when suspending processes during an autoscaling launchtemplate change in a cloudformation update. Since cloudformation requires the value like `AZRebalance`, I cannot use the member name `AZ_REBALANCE`. Effectively making this Enum useless in python.

All that said, is it worth making it work in python? Maybe not. In my particular case I wanted to mimic the typescript coding styles and examples, while leveraging an existing Enum classes.

**Comment by RomainMuller** [comment]
Thanks for the precisions!

I've re-filed this as a feature request; as this is all working "as designed". I reckon what you are trying to do can be seen as a reasonable pattern, it it probably would be sweet if we could enable that.

**Comment by adrianmace** [comment]
I just came across this issue while trying to work out how to extract the Enum's actual value using Python.

Is this possible at all? I'm trying to validate some user input to make sure it matches one of [RetentionDays](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs.RetentionDays.html#members).
