### ISSUE TITLE
[custom-resources] How to upload a file to an s3 bucket with a custom resource

### ISSUE THREAD

**Issue by jonathan-kosgei** [aws/aws-cdk#9748]
### The Question
I need to upload a zip file to an s3 bucket after its creation. I'm aware of the s3_deployment package but it doesn't fit my usecase because I need the file to be uploaded only once, on stack creation. The s3_deployment package would upload the zip on every update.

I have the following custom resource defined however I'm not sure how to pass the body of the file to the custom resource. I've tried opening the file in binary mode but that returns an error.

### Environment

  - **CDK CLI Version:** 1.58.0 (build 09e12a6)
  - **Module Version:** aws-cdk.custom-resources==1.58.0
  - **Node.js Version:**  v12.16.1
  - **OS:** Ubuntu
  - **Language (Version):** Python (3.8)

### Other information

```
app_data_bootstrap = AwsCustomResource(self, "BootstrapData",
    on_create={
        "service": "S3",
        "action": "putObject",
        "parameters": {
            "Body": open('app_data.zip', 'rb'),
            "Bucket": f"my-app-data",
            "Key": "app_data.zip",
        },
        "physical_resource_id": PhysicalResourceId.of("BootstrapDataBucket")
    },
    policy=AwsCustomResourcePolicy.from_sdk_calls(resources=AwsCustomResourcePolicy.ANY_RESOURCE)
)
```

**Comment by rix0rrr** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.

**Comment by jonathan-kosgei** [comment]
Here's the SO question I posted before opening an issue here - https://stackoverflow.com/questions/63427486/how-to-upload-a-file-to-an-s3-bucket-with-a-custom-resource-in-aws-cdk.

I also went through the S3File construct example in the [docs](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-file.ts). There you pass the file contents as a string and don't show how to handle a zip file.
