### ISSUE TITLE
[aws-route53-targets] Documentation about zones is incorrect, property not specified

### ISSUE THREAD

**Issue by gregorypierce** [aws/aws-cdk#9752]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-route53-targets-readme.html

The documentation suggests that the value of the zone should be specified when it is in fact a property that should have a value:

new route53.ARecord(this, 'AliasRecord', {
  zone,
  recordName, // www
  target: route53.RecordTarget.fromAlias(new alias.BucketWebsiteTarget(bucket)),
});

This should be:

new route53.ARecord(this, 'AliasRecord', {
  zone: myHostedZone,
  recordName: myRecordName, //www
  target: route53.RecordTarget.fromAlias(new alias.BucketWebsiteTarget(bucket)),
});

This is the case for all the code examples on this page.
---

This is a 📕 documentation issue

**Comment by Jerry-AWS** [comment]
This is a shortcut for writing JavaScript object literals when you have a key and a value that have the same name. When you have this:

```
new route53.ARecord(this, 'AliasRecord', {
zone,
recordName, // www
target: route53.RecordTarget.fromAlias(new alias.BucketWebsiteTarget(bucket)),
});
```

It is equivalent to:

```
new route53.ARecord(this, 'AliasRecord', {
zone: zone,
recordName: recordName, // www
target: route53.RecordTarget.fromAlias(new alias.BucketWebsiteTarget(bucket)),
});
```

For more information, see this 2013 blogpost: https://ariya.io/2013/02/es6-and-object-literal-property-value-shorthand

This feature was formally added to JavaScript in the ECMAScript 6 standard (2015). It is used throughout the examples, not just on this page, so it could be a large effort in removing it. Is there value in *not* using it?

**Comment by gregorypierce** [comment]
Understand what that is saying, not sure it's immediately obvious since it is a shortcut and unless you're routinely writing Javascript this looks like the value of zone belongs there. Just leave it as is. Folks will find this issue if they search for it.

**Comment by mattvb91** [comment]
@Jerry-AWS  @gregorypierce  sorry about the ping but I couldn't find anything else relating to this but what is the import for `alias` in the context of `new alias.BucketWebsiteTarget()`

What is the instantiation of `alias`?

**Comment by bcteam2020** [comment]
route53 package = ('@aws-cdk/aws-route53')
alias  package = (@aws-cdk/aws-route53-targets)
