### ISSUE TITLE
[aws-ssm] how parse ssm parameter to ecs fargate container?

### ISSUE THREAD

**Issue by cmoreno82** [aws/aws-cdk#9765]
**Environment**

    CDK CLI Version: 1.59.0 (build 09e12a6)
    Modules Version: 1.59.0 
    Node.js Version: v10.15.2
    OS: Ubuntu
    Language (Version): Python (3.7.5)
    CDK with Python

Hallo,
I try to get some parameter from AWS System Manager for ECS Fargate Containers, but I get some problems.
My code is:

```py
secret_value = ssm.StringParameter.from_secure_string_parameter_attributes(
                self,
                "/spark/ssh_pub",
                parameter_name="/spark/ssh_pub",
                version=1
            )

container_sp = fargate_task_definition_sp.add_container(
                "pod-spark-master",
                image=ecs.ContainerImage.from_registry(
                    "xxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com/spark-master:ready-for-test-deployment"),
                health_check=health_check_sp,
                logging=log_config_sp,
                secrets={
                    "SPARK_PUB": ecs.Secret.from_ssm_parameter(secret_value)
                    }
            )
```

and the result ist:
`jsii.errors.JSIIError: There is already a Construct with name '--spark--ssh_pub' in Stack [sandbox]`

has someone one idea?

**Comment by nramirezuy** [comment]
@cmoreno82 if you change you id it should work just fine.

```python
secret_value = ssm.StringParameter.from_secure_string_parameter_attributes(
                self,
                "some-random-id",
                parameter_name="/spark/ssh_pub",
                version=1
            )
```

But you will hit another wall I'm currently hitting.

`Non-secure ssm prefix was used for secure parameter <parameter-name>`
