### ISSUE TITLE
[pipelines] Infinite-loop in self-mutating pipeline

### ISSUE THREAD

**Issue by fongie** [aws/aws-cdk#9766]
The pipeline's 'UpdatePipeline' stage fails and the pipeline restarts, which it is expected to do once when infrastructure is updated. However, when it restarts, it updates itself again. This loops infinitely, and the pipeline never reaches the "Assets" stage.

### Reproduction Steps

I deployed a new pipeline using cdk deploy. I have added one stage to it which deploys two stacks.

There is an old issue which perfectly describes my problem in #9080, which was supposed to have been fixed in v1.54.0 (in #9183) but not in this case it seems.

I am using cdk cli version 1.58.0 and my cdk code uses 1.56.0 in package.json. 

If it matters, I have a custom build as my synth action.

### What did you expect to happen?

I expected the pipeline to reach the asset stage and deploy my stacks after restarting.

### What actually happened?

The pipeline kept updating itself and restarting before the 'asset' stage.

### Environment

  - **CLI Version      :** 1.58.0
  - **Framework Version:** 1.56.0
  - **Node.js Version:**  14.3.0 locally
  - **OS               :** mac
  - **Language (Version):**  Typescript

### Other

I have followed the blog post here https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/ before and got it to work, so I am unsure what is the difference now. I will investigate a bit further tomorrow. Is there anything I could be doing that is causing the infrastructure to think it has to update every time?

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Have a look at the Stack Events in the CloudFormation console and see what is updated every time. That should at least give you a hint to what's causing this.

**Comment by fongie** [comment]
I think I have located where the issue is, but not exactly why yet.

The SelfMutate codebuild logs say everytime that the template has changed, so I looked at the template diff after each run. It seems like a path inside the build artifact from the synth build is changing in the template everytime the synth build is run. In all places where this path is located in the template: `Artifact_Build_BuildAndSynth::../../../../../../../../tmp/cdk.outhDG4a2/...` it is changed to `Artifact_Build_BuildAndSynth::../../../../../../../../tmp/cdk.outBXOIUt/...`, notice the difference in characters after `cdk.out`. 

Here's a full line example, where the buildspec for the codebuild project of one of the stacks' file assets project has a diff in the path at the first array item under the build/commands key:

```json
"BuildSpec": "{\n  \"version\": \"0.2\",\n  \"phases\": {\n    \"install\": {\n      \"commands\": \"npm install -g cdk-assets\"\n    },\n    \"build\": {\n      \"commands\": [\n        \"cdk-assets --path \\\"../../../../../../../../tmp/cdk.outhDG4a2/[my-stack-name]A6BA2591.assets.json\\\" --verbose publish \\\"[my-account-details]\\\"\"\n      ]\n    }\n  }\n}",
```
vs
```json
"BuildSpec": "{\n  \"version\": \"0.2\",\n  \"phases\": {\n    \"install\": {\n      \"commands\": \"npm install -g cdk-assets\"\n    },\n    \"build\": {\n      \"commands\": [\n        \"cdk-assets --path \\\"../../../../../../../../tmp/cdk.outBXOIUt/[my-stack-name].assets.json\\\" --verbose publish \\\"[my-account-details]\\\"\"\n      ]\n    }\n  }\n}",
```

this is repeated in all places where the cdk.out+random characters path is used.

I also tried to use `cdk synth` twice locally in my project and diff the templates generated, and it turns out that this also creates diffs in exactly the same way, leading me to believe there is something in my code or my synth build project which is triggering this. Or, I could be completely off and this path is supposed to change everytime and the selfmutate build takes that into account.

I will search some more and look into what cdk actually is doing here (and maybe find out that this is intended)

The cloudformation events show that the File Asset code builds are updated and that the pipeline itself is updated, which is in line with what differs in the templates

**Comment by fongie** [comment]
I have spent a while now without much luck. The pipeline is updated as described above because the cloud assembly path changes on every `cdk synth` command, but I don't know why it is doing that.

I actually have a working implementation of the pipeline with the stacks I want to deploy, but it is very specific to this deployment and what I am trying to do is to generalize the pipeline so we can re-use it in other deployments. 

The differences I can see between the more literal implementation which works (stack A), and the generic one which doesnt (stack B) are:
- When I run synth on stack A, it outputs one single template. 
When I synth stack B, the output tells me to supply a stack id to display a template, and it lists three stacks: the pipeline stack, and the two stacks that I have added to my pipeline stage. There are templates for all three in cdk.out directory.
- For stack A, the App, Pipeline, and Stage classes are in the local directory, while the stacks to be deployed are imported from outside. 
For stack B, only the App is in the local directory, and the Pipeline and Stage classes are in a (local) npm package instead. The stacks to be deployed are passed to the Stage as types and instantiated inside the Stage class - see below.

My best guess was that something was going wrong with `scope` and `this` since the `cdk synth` output gave several stacks instead of just one in the non-working stack. However, I have debugged the instantiated objects and they all have `scope`s that seem logical to me.

Maybe I am trying to do something pretty hacky here which wont work, but this is the idea. `StackTypeA`and `StackTypeB` are the actual stack classes that I want to deploy with the pipeline:

__app.ts__
```ts
const app = new App()
const stackprops = {...}
const stackTypes = [ StackTypeA, StackTypeB ]
const pipe = new MyPipeline(app, 'id', stackTypes, stackProps)
app.synth()
```

__mypipeline.ts__
```ts
export class MyPipeline extends Stack {
  constructor(..., stackTypes, stackProps) {
    
    // create build project, source, artifacts, etc. - identical to the working stack

    const pipeline = new CdkPipeline(this, ... id and props) // also identical to working stack

    pipeline.addApplicationStage(
      new PipelineStage(this, id, stackTypes) // identical except for passing the stackTypes
    )
  }
}
```

__pipelinestage.ts__
```ts
export class PipelineStage extends Stage {
  constructor(..., stackTypes) {
    
    stackTypes.forEach( 
       (stack) => new stack(this, ... id and props)
    )
    // in working stack, instead of the foreach we just do new StackTypeA(this, ...) and new StackTypeB(this, ...)
  }
}
```

and that's it

The most suspicious part to me was of course the `stackTypes.forEach()` but if I replace it with a simple normal stack defined in the same file then `synth` still outputs more than one template. Also, when debugging and logging the stacks generated here (by putting them in a list instead and logging afterwards), they look good to me.

I have tried messing around with replacing `this` with `scope` or even with `pipeline` in different places here but without success.

At this point I am at a loss. When digging around the cdk code I found the method which sets the temp output dir to cdk.out + random characters but I dont know why this is done on every synth in my generalized pipeline but not in the more specific one.

I would appreciate either some help or to know if what I am trying to do is impossible and/or not useful =)

**Comment by rix0rrr** [comment]
This is very odd. The only reason that I can think of for this happening is that this condition here is taking the wrong branch (should have taken the 'true' branch, but is taking the 'false' one):

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/private/synthesis.ts#L30-L32

I can't really figure out why though. Are all your CDK libraries the same version? You mentioned that the stacks are coming from an NPM package, could that have something to do with it?

> if I replace it with a simple normal stack defined in the same file then `synth` still outputs more than one template

That shouldn't be happening. The fact that the stacks are created under a `Stage` should lead them to be created in a "nested cloud assembly", which ought to be invisible to the CLI (that's a missing feature, but this is the way it should be for now). The fact that the CLI sees them means that something is wrong there. The construct tree might not look like you think it does, or the `Stage` class is not actually the right `Stage` class.

Try looking at the construct tree using the VSCode AWS extension (should have an "AWS CDK Explorer" pane which interprets cdk.out).

On another note:


> I would appreciate either some help or to know if what I am trying to do is impossible and/or not useful =)

It should not be impossible, although you are deviating from intended use somewhat.

* We recommend sharing `Construct`s, not `Stack`s. If you put your reusable code in a `Construct`, downstream users have the same or more freedom.
* I don't really see the point of the dynamic stage. You're encoding a list of stacks somewhere -- might as well be the `Stage` construct itself (instead of the location that instantiates the Stage).

**Comment by fongie** [comment]
Hi!
Sorry for taking so long, I had to do some other non-CDK related stuff at work

I ended up refactoring our code to use constructs and intantiate the stacks inside the stage, as suggested by rix0rrr, instead of problem-solving this usecase any more. I realized there was really nothing much gained by trying to do it the previous way. 

I think I will close this issue since it doesn't seem like anyone else is experiencing this problem, maybe I was simply doing something wrong somewhere. The pipelines I have now are working great =)

Thanks

**Comment by gvnavin** [comment]
I faced some what similar issue. Pasting my observation, it might help others.

The issue with this code which I added in code build step to create a unit test report.

```
 Map<String, String> reportGroupProps = Map.of(
                "files", "**/*.xml",
                "base-directory", "lambda/build/test-results/test/",
                "file-format", "JUNITXML"
        );
        Map<String, ?> reports = Map.of(reportGroup.getReportGroupArn(), reportGroupProps);
        Map<String, ?> reportsMap = Map.of("reports", reports);
```

It looks like cdk does Map.toString() somewhere in the code. Map.of() changes the order of keys while doing toString(), which result in cdk diff. This diff creates the pipeline to update, hence it is looping.

I tested with the below code, the hashmap and treemap is consitently giving the same order, which map.of changes the order.

```
        Map<String, String> mp = Map.of("k1", "v1", "k2", "V2");
        System.out.println("mp = " + mp);

        Map<String, String> hp = new HashMap<>();
        hp.put("k1", "v1");
        hp.put("k2", "v2");
        System.out.println("hp = " + hp);

        Map<String, String> smp = new TreeMap<>();
        smp.put("k1", "v1");
        smp.put("k2", "v2");
        System.out.println("smp = " + smp);
```
