### ISSUE TITLE
Feature request: Check npm cdk module versions are in-sync

### ISSUE THREAD

**Issue by 0xdabbad00** [aws/aws-cdk#9770]
Sometimes I get weird errors from the CDK, such as most recently:
```
unable to determine cloud assembly output directory. Assets must be defined indirectly within a "Stage" or an "App" scope
```

The cause of this was my npm modules being out of sync, meaning I had `"@aws-cdk/core": "1.42.1"` in my `packages.json`, but other modules were newer, such as `"@aws-cdk/aws-s3-deployment": "^1.56.0"`.  This was due to me having installed the CDK at some point in the past, and then trying to use the other libraries by just running `npm i @aws-cdk/aws-s3-deployment` and not specifying a version.

### Use Case

Ensuring the module versions are in-sync would dramatically improve debug time for weird issues that result from this problem.

### Proposed Solution

During `cdk synth` or `cdk deploy`, somehow check that all the CDK related npm modules that have been imported are the same version.

---

This is a :rocket: Feature Request

**Comment by Jerry-AWS** [comment]
See also https://github.com/aws/aws-cdk/issues/9071

**Comment by 0xdabbad00** [comment]
Thanks @Jerry-AWS, I hadn't seen that. This ticket can probably be closed if that one goes through.  It sounds like in the other though you are wanting people to run another command, whereas I would want a sanity check built right in, because for the casual or new CDK user, these error messages are misleading and if someone knew to run `cdk doctor`, they would probably know about the root cause issue in the first place.

**Comment by Jerry-AWS** [comment]
You might also look at [monocdk](https://www.npmjs.com/package/monocdk-experiment)

**Comment by SomayaB** [comment]
@0xdabbad00 I added your comment to issue #9071 so that it can all be tracked in one issue. Closing this issue.
