### ISSUE TITLE
[custom-resources] Support function name in AwsCustomResource construct

### ISSUE THREAD

**Issue by kinbald** [aws/aws-cdk#9771]
Hello, 

As we have hands on the role of the Signleton Lambda created by the AwsCustomResource construct, could it possible to add the functionName ?

### Use Case

In the environment of my entreprise, we require naming convention over resources like lambdas, roles, etc.
We can't use the AwsCustomResource at the moment because we don't have hands on the functionName created by the resource.

### Proposed Solution

Add an optional parameter which allow to set the functionName when needed.

```
const awsCustom1 = new AwsCustomResource(this, 'API1', {
 functionName: 'lambda-env-call',
  onCreate: {
    service: '...',
    action: '...',
    physicalResourceId: PhysicalResourceId.of('...')
  },
  policy: AwsCustomResourcePolicy.fromSdkCalls({resources: AwsCustomResourcePolicy.ANY_RESOURCE})
});
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I think this is a bad idea and your environment should learn not to care about resource names. You should probably be tagging instead.

Unlikely we will implement this, but PRs are welcome.

**Comment by fdelhoste** [comment]
@rix0rrr Agreed, tags are far better for managing resources. However, I'd argue other constructs already allow this. Plus there are cases where names are used by AWS customers, for ex, by operation teams outside the boundary of the CDK developer like @kinbald who needs to comply.
