### ISSUE TITLE
[@aws-cdk/aws-lambda-event-sources] Add Lambda as event source in SQS producing Error

### ISSUE THREAD

**Issue by niciqy** [aws/aws-cdk#9782]
I am trying out with the example found in CDK site. Essentially, it trying to add a lambda as event source to SQS

```javascript
import * as sqs from '@aws-cdk/aws-sqs';
import { SqsEventSource } from '@aws-cdk/aws-lambda-event-sources';
import { Duration } from '@aws-cdk/core';

const queue = new sqs.Queue(this, 'MyQueue', {
  visibilityTimeout: Duration.seconds(30)      // default,
  receiveMessageWaitTime: Duration.seconds(20) // default
});

lambda.addEventSource(new SqsEventSource(queue, {
  batchSize: 10 // default
});
```

I am getting this error:
`Argument of type 'SqsEventSource' is not assignable to parameter of type 'IEventSource'.
  Types of property 'bind' are incompatible.`

### Environment

  - **CLI Version      1.57.0:**
  - **Framework Version:**
  - **Node.js Version:** v10.16.3
  - **OS               :** OSX 10.14.3
  - **Language (Version):** TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by niciqy** [comment]
How are we tracking with this issue? Is this a me issue are other people having the same problem?

**Comment by nija-at** [comment]
This is likely because the version of `aws-lambda-event-sources` is not the same as `aws-lambda`. Can you check the version of these packages (either in `yarn.lock` or package-lock.json`) and ensure they are exactly same?

**Comment by niciqy** [comment]
You are spot on! Thank you for your prompt reply
