### ISSUE TITLE
[pipelines] Expose the artifact bucket prop of CodePipeline pipeline

### ISSUE THREAD

**Issue by tomas-mazak** [aws/aws-cdk#9794]
Expose the artifact bucket prop of CodePipeline pipeline via CdkPipeline props as an optional property.

### Use Case

CodePipeline pipeline construct has an optional `artifactBucket` property. If not defined, a new bucket is created with encryption enabled and bucket policy created. This will fail to deploy in accounts where setting encryption and/or bucket policies is prohibited by service control policies. This can easily be worked around by creating the bucket explicitly without encryption/bucket policy and passing it to the pipeline constructor.

However, with CdkPipeline, this property is not exposed, so the workaround does not work.

### Proposed Solution

To resolve the problem, I would suggest simply exposing `artifactBucket` property in `CdkPipelineProps` and passing it to the codepipeline pipeline.

Another, option, adding even more flexibility, would be to allow passing the codepipeline pipeline as an optional property. If defined, the one provided in properties would be used in `CdkPipeline` constructor, instead of instantiating a new one.

Even more flexible perhaps would be to move the codepipeline pipeline creation from the `CdkPipeline` constructor to a separate method, what would allow extending `CdkPipeline` in a subclass and overriding the pipeline creation method.

I am willing to implement this feature if it's welcome.

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I think accepting an existing `pipeline` as an argument is the most in line with what we usually do.

**Comment by tomas-mazak** [comment]
@rix0rrr thanks, I've implemented your suggestion as PR #9962 , will you be able to have a look?

**Comment by tomas-mazak** [comment]
Resolved in #10148
