### ISSUE TITLE
[aws-codebuild] Provide the ability to explicitly set BuildEnvironment type 

### ISSUE THREAD

**Issue by jimistry123** [aws/aws-cdk#9817]
When building artifacts using ARM architecture, it would be nice to be able to specify the type of the build environment when CodeBuild is not able to directly infer the architecture from the build image. Especially this is the case when using a custom image instead of a default image.

### Use Case

I am using a custom Docker image that is built from base ARM image `LinuxBuildImage.AMAZON_LINUX_2_ARM`. And when I create a CodeBuild project using this custom image, it configures the `Environment.Type` property to `LINUX_CONTAINER` instead of `ARM_CONTAINER`.

### Proposed Solution

To workaround this issue, I have to use an escape hatch to modify CloudFormation resource behind `CodeBuildProject` like this:

```java
CfnProject cfnProject = (CfnProject) createBuildProject().getNode().getDefaultChild();
if (cfnProject != null) {
  cfnProject.addPropertyOverride("Environment.Type", "ARM_CONTAINER");
}
```

So it would be nice if there was a `type` method in [BuildEnvironment.Builder](https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/codebuild/BuildEnvironment.html) class that allows setting the type to `LINUX_CONTAINER` or `ARM_CONTAINER`.

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @jimistry123 ,

thanks for opening the issue. We had a similar problem recently when CodeBuild introduced a second type of Windows build images. We solved it by adding a new enum that allows you to choose between the two versions - see https://github.com/aws/aws-cdk/pull/9526 for details.

Would you consider opening a similar PR for ARM images?

Thanks,
Adam
