### ISSUE TITLE
[aws-elasticache]  no encryption for cluster

### ISSUE THREAD

**Issue by ogger** [aws/aws-cdk#9820]
I would like to create an encrypted elasticache redis cluster with the following Options:

* encryption at rest
* encryption in transit
* redis auth

### Use Case
We are using elasticache redis for caching data, an we would like to encrypt the cluster. Encryption is part of our security strategy and a must. With CDK this is not possible, the options are missing.  I have checked with AWS console, it is possible, also with boto3 (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elasticache.html#ElastiCache.Client.create_cache_cluster).

### Proposed Solution

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Hi @ogger - Looking at the docs you sent, I don't see support for encryption. And indeed, it looks like the service API also doesn't have this option: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html.

However, encryption properties are available when creating a `ReplicationGroup`, which is a generalization of a single cluster, so would that work for you? Here are the docs for it:

CDK Docs: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticache.CfnReplicationGroup.html

**Comment by irby** [comment]
I'm surprised no encryption at rest option is available from the APIs. Seems to be like a big miss.

**Comment by Lumnut** [comment]
Like @iliapolo points out above it looks like a workaround is to use a CfnReplicationGroup instead

```
		const redisCluster = new redis.CfnReplicationGroup(this, 'redisCluster', {
			engine: 'redis',
			autoMinorVersionUpgrade: true,
			replicationGroupDescription: 'Redis Cache used in the backend',
			cacheSubnetGroupName: redisSubnetGroup.ref,
			securityGroupIds: [redisSecurityGroup.securityGroupId],

			transitEncryptionEnabled: true,
			atRestEncryptionEnabled: true,
			authToken: 'authToken',

			// As minimal of a cache cluster as possible
			cacheNodeType: 'cache.t4g.micro',
			clusterMode: 'Disabled',
			numCacheClusters: 1,
			automaticFailoverEnabled: false,
		})

```


This generates a cluster with 1 node, with encryption at rest, transit encryption and auth token
