### ISSUE TITLE
[aws-events-targets] Support tagging when starting a Fargate task from CloudWatch Events

### ISSUE THREAD

**Issue by zulhfreelancer** [aws/aws-cdk#9823]
I saw [this issue on aws/containers-roadmap](https://github.com/aws/containers-roadmap/issues/89) and it's exactly the problem I'm facing now. I'm using [EcsTask](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events-targets.EcsTask.html) and [EcsTaskProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events-targets.EcsTaskProps.html) to schedule Fargate tasks using CloudWatch Events rule. Since the scheduled task will run without ECS service, I can't use [propagateTags](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html#propagatetags) or [propagateTaskTagsFrom](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html#propagatetasktagsfrom-span-class-api-icon-api-icon-deprecated-title-this-api-element-is-deprecated-its-use-is-not-recommended-span) props.

### Use Case

Mainly for billing. By having specific tags, I can use them in AWS Cost Explorer to see the cost breakdown for my scheduled tasks vs normal tasks (i.e. web containers).

### Proposed Solution

Something like this would be great:

```typescript
import events = require("@aws-cdk/aws-events");
import event_targets = require("@aws-cdk/aws-events-targets");

const rule = new events.Rule(this, "theRule", {
    enabled: true,
    // code omitted for brevity
});

rule.addTarget(
    new event_targets.EcsTask({
        // code omitted for brevity
        taskTags: [
            {
                key: "project",
                value: "my-cdk-project"
            },
            {
                key: "team",
                value: "team-a"
            }
        ]
    })
);
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by baxang** [comment]
Adding support for `propagateTags` would be great too!

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_EcsParameters.html#eventbridge-Type-EcsParameters-PropagateTags

**Comment by faabsen** [comment]
Any updates on this? Is there a known workaround to propagate the tags to an `EcsRunTask` started by a statemachine / event rule / schedule?

**Comment by fabiog27** [comment]
I'm also interested in updates to this issue. It seems from https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/394 that it should be supported by CloudFormation now, but I can't see any options in cdk. I'm trying to add tags to a [ScheduledFargateTask](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.ScheduledFargateTask.html).

**Comment by faabsen** [comment]
> I'm also interested in updates to this issue. It seems from [aws-cloudformation/cloudformation-coverage-roadmap#394](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/394) that it should be supported by CloudFormation now, but I can't see any options in cdk. I'm trying to add tags to a [ScheduledFargateTask](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.ScheduledFargateTask.html).

I solved it via https://github.com/aws/aws-cdk/issues/14553#issuecomment-865223460, maybe this is an option for you too
