### ISSUE TITLE
[aws-cloudfront] cloudfront.Distribution ignores webAclId

### ISSUE THREAD

**Issue by lanwen** [aws/aws-cdk#9824]
`DistributionProps.webAclId` has no effect when used with `cloudfront.Distribution` and I cant actually find any usage in js files, only in types

### Reproduction Steps

```js
new cloudfront.Distribution(
      this,
      "StaticDistribution",
      {
        defaultBehavior: {
          origin: new origins.S3Origin(bucket),
        },
        webAclId: wafAclArn,
      }
    );
```

### What did you expect to happen?

`DistributionConfig.WebACLId` would be in the generated template

### What actually happened?

Nothing

### Environment

  - **CLI Version     :**  1.59
  - **Framework Version:**  1.59

### Other

right now workarounded with

```js
    const cfnDistro = distribution.node
      .defaultChild as cloudfront.CfnDistribution;
    cfnDistro.addPropertyOverride("DistributionConfig.WebACLId", wafAclArn);
```

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Whoops. This got missed in #9635.
