### ISSUE TITLE
[aws-cloudfront] cloudfront won't forward request to custom domain HTTP API. 

### ISSUE THREAD

**Issue by apoorvmote** [aws/aws-cdk#9837]
### The Question

I am serving static website with S3/Cloudfront at `/` and I have set custom domain HTTP API at `/api/*` as per [CDK documentation on apigatewayv2](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html#custom-domain) but cloudfront won't forward request to HTTP API. Cloudfront will serve 404 not found to any `/api/*` path. 

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by njlynch** [comment]
Hi @apoorvmote ,

Can you share some more details about your setup? How exactly are you defining the `Distribution` or `CloudFrontWebDistribution`, and how is this linked to your API gateway? Sharing some code snippets would go a long way to understanding what's happening here. Without more information, it's quite hard to comment on why the setup isn't working.

**Comment by apoorvmote** [comment]
My `CloudFrontWebDistribution` is as follows
```typescript
const distribution = new CloudFrontWebDistribution(this, 'CloudfrontWebDistribution', {
      httpVersion: HttpVersion.HTTP2,
      priceClass: PriceClass.PRICE_CLASS_ALL,
      viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      originConfigs: [
        {
          s3OriginSource: {
            s3BucketSource: bucket,
            originAccessIdentity
          },
          behaviors: [{
              isDefaultBehavior: true,
              defaultTtl: Duration.hours(1)
            }]
        }, 
        {
          customOriginSource: {
            domainName: website_domain
          },
          behaviors: [{
            pathPattern: '/api/*',
            isDefaultBehavior: false,
            allowedMethods: CloudFrontAllowedMethods.ALL,
            defaultTtl: Duration.seconds(0),
            minTtl: Duration.seconds(0),
            maxTtl: Duration.seconds(0),
            forwardedValues: {
              queryString: true,
              cookies: {
                forward: 'all'
              }
            }
          }]
        }
      ],
      errorConfigurations: [
        {
          errorCode: 404,
          responseCode: 404,
          responsePagePath: '/404.html'
        }
      ],
      viewerCertificate: ViewerCertificate.fromAcmCertificate(certificate, {
        aliases: [website_domain],
        securityPolicy: SecurityPolicyProtocol.TLS_V1_2_2018
      })
    })
```
My HTTP API custom domain is as follows
```typescript
    const certificate = Certificate.fromCertificateArn(this, 'ssl_cert', certArn)
    
    const domain = new DomainName(this, 'domain', {
      domainName: website_domain,
      certificate
    }) 

    const api = new HttpApi(this, 'endpoint', {
      defaultDomainMapping: {
        domainName: domain,
        mappingKey: 'api'
      },
      corsPreflight: {
        allowCredentials: true,
        allowHeaders: ['Content-Type'],
        allowMethods: [HttpMethod.GET, HttpMethod.POST, HttpMethod.OPTIONS, HttpMethod.HEAD],
        allowOrigins: [
          "https://cdn.ampproject.org",
          "https://www.bing-amp.com"
        ]
      },
      apiName: 'myAPI'
    })
```

Everything is successfully deployed. And I am getting 404 not found when I try to reach my API.

**Comment by njlynch** [comment]
I think you're running afoul of the same issue mentioned in #3486, where the `defaultRootObject` is set to `index.html` if not provided. An unfortunate "helpful" default that isn't always helpful. See https://github.com/aws/aws-cdk/issues/3486#issuecomment-578528190 for someone else who hit this same scenario.

Try explicitly setting `defaultRootObject` to an empty string and see if that helps:

```ts
const distribution = new CloudFrontWebDistribution(this, 'CloudfrontWebDistribution', {
      httpVersion: HttpVersion.HTTP2,
      priceClass: PriceClass.PRICE_CLASS_ALL,
      defaultRootObject: '',
      ... // etc.
});
```

**Comment by apoorvmote** [comment]
I want to set `Set-Cookie: promo_shown=1; SameSite=Strict` as per [same site documentation](https://web.dev/samesite-cookies-explained/).
But I am forced to use `api.mywebsite.com` for HTTP API custom domain that requires CORS from `mywebsite.com`
I want to set `mywebsite.com/api/*` for HTTP API custom domain so its first party request that doesn't require CORS.
For that also I had to manually Add `A Record` to route 53 from HTTP API custom domain. Its not currently possible through CDK.

**Comment by njlynch** [comment]
So your CloudFront config is then pointing to `website_domain` which is `'getrichwithabudget.com'`, and then you have an A Record for `'getrichwithabudget.com'` pointing to the CloudFront distribution? If so, you've effectively set up a circular loop of redirects; your website points to the distribution, which goes to your website to get the content, which points to the distribution...

If you have an A Record for `'api.getrichwithabudget.com'` which points to the API gateway endpoint, why aren't you using that as the domain name for the origin?

**Comment by apoorvmote** [comment]
> So your CloudFront config is then pointing to `website_domain` which is `'getrichwithabudget.com'`, and then you have an A Record for `'getrichwithabudget.com'` pointing to the CloudFront distribution? If so, you've effectively set up a circular loop of redirects; your website points to the distribution, which goes to your website to get the content, which points to the distribution...

I removed the `A record` from Route 53 now I only have domain in Cloudfront distribution. And my website is down. You can try visiting [getrichwithabudget.com](https://getrichwithabudget.com). I just followed some online tutorial to setup my CI CD pipeline for static website. And looks like they added `A record` for a reason. And I cannot remove domain connected to cloudfront because I don't want to lose SSL/HTTPS connection.

> If you have an A Record for `'api.getrichwithabudget.com'` which points to the API gateway endpoint, why aren't you using that as the domain name for the origin?

Because as I mentioned earlier

> I want to set Set-Cookie: promo_shown=1; SameSite=Strict as per [same site documentation.](https://web.dev/samesite-cookies-explained/)

Subdomain api is not 1st party cookie but 3rd party cookie.

Other than same site I want to setup **server side rendering** for specific paths. For example comments for each blog post will be on different page(similar to aws blog). Each comment page will be server sider rendered. I need to **forward request from cloudfront to api based on path url for server side rendering of pages**.

**Comment by njlynch** [comment]
The ultimate answer is that in order for a CloudFront distribution to forward your API requests to API gateway, you need to either use the API gateway endpoint as the origin or have a custom domain for the API gateway and point the distribution to that. In either scenario, the domain name you use as the origin cannot be the exact same domain name you want to use for the distribution.

There are a multitude of ways you could architect this, and I'm afraid I can't dictate which will work for your specific setup. We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.

**Comment by apoorvmote** [comment]
@njlynch 
I have created issue on Stackoverflow under the aws-cdk tag many days ago. Please see 
https://stackoverflow.com/questions/63504502/how-to-forward-cloudfront-to-http-api-with-custom-domain

**Comment by nonken** [comment]
@njlynch I am seeing that there doesn't seem to be a domain property which you can use as the HttpOrigin attribute in the CloudFront origin property. Should I file a new issue for this or am I missing something? The below example fails with:

```
The parameter origin name cannot contain a colon. 
```

Here a shortened reproduction:

```
const api = new HttpApi(this, 'api', {
  defaultIntegration,
});

const productionDistribution = new Distribution(this, 'distribution', {
  defaultBehavior: { 
    origin: new HttpOrigin(api.url)
  }
});
```

I see the url is built like this `https://${Token[TOKEN.374]}.execute-api.${Token[AWS.Region.4]}.${Token[AWS.URLSuffix.1]}/` so removing `https://` should do the trick.

**Comment by ffxsam** [comment]
This is still an issue. What's the proper way to set up an HTTP origin in CDK? @rix0rrr @njlynch

**Comment by ffxsam** [comment]
Solved! For anyone else looking for the solution:

```js
new cloudfront.Distribution(this, 'Dist', {
  defaultBehavior: {
    origin: new origins.HttpOrigin(
      core.Fn.select(1, core.Fn.split('://', httpApi.url))
    ),
  },
});
```
