### ISSUE TITLE
[custom-resources] AwsCustomResource onDelete fails with multiple Custom Resources because the associated IAM policy is missing

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#9840]
When using an `AwsCustomResource` that has an `AwsSdkCall` specified for `onDelete`, the IAM policy associated with the custom resource is removed *before* the onDelete is executed. This causes the onDelete sdk call to fail with a "not authorized to perform action" error, like below:

`Failed to delete resource. User: arn:aws:sts::123456789012:assumed-role/AWS679f53fac002430cb0da5b7982bd2287ServiceRo-WTH8L2RRAM8O/AWS679f53fac002430cb0da5b7982bd22872D164C4C-JACGZKNLR8JK is not authorized to perform: codedeploy:DeleteDeploymentConfig on resource: arn:aws:codedeploy:us-west-2:123456789012:deploymentconfig:MyDeploymentConfigName`

### Reproduction Steps
```java
AwsCustomResource deploymentConfig = new AwsCustomResource(scope, deploymentConfigName, AwsCustomResourceProps.builder()
                .onCreate(AwsSdkCall.builder()
                        .service("CodeDeploy")
                        .action("createDeploymentConfig")
                        .parameters(new HashMap<String, Object>() {{
                            put("deploymentConfigName", deploymentConfigName);
                            put("computePlatform", "Lambda");
                            put("trafficRoutingConfig", routingConfig);
                        }})
                        .physicalResourceId(PhysicalResourceId.of(deploymentConfigName))
                        .build())
                .policy(AwsCustomResourcePolicy.fromStatements(Arrays.asList(
                        new PolicyStatement(PolicyStatementProps.builder()
                                .actions(Arrays.asList("codedeploy:*"))
                                .resources(Arrays.asList("*"))
                                .effect(Effect.ALLOW)
                                .build())
                )))
                .onDelete(AwsSdkCall.builder()
                        .service("CodeDeploy")
                        .action("deleteDeploymentConfig")
                        .parameters(new HashMap<String, Object>(){{
                            put("deploymentConfigName", deploymentConfigName);
                        }})
                        .build())
                .build());
```

The error occurs when this resource is created, then deleted in a subsequent deployment.

### What did you expect to happen?

I expected the onDelete SDK call to succeed.

### What actually happened?

The onDelete SDK call occurred with a "not authorized to perform action" error.

### Environment

  - **CLI Version      :** 1.51
  - **Framework Version:**
  - **OS               :** OSX 
  - **Language (Version):** Java 8

### Other

IAM policy after resource is created:

`          "Statement": [
            {
              "Action": "ec2:DescribeSecurityGroups",
              "Effect": "Allow",
              "Resource": "*"
            },
            {
              "Action": "codedeploy:*",
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
`

IAM policy when resource is deleted:

`    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "ec2:DescribeSecurityGroups",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
`

When resource is deleted, this is the CFN update order. You can see that the IAM policy is updated first, then the custom resource is deleted. Because the policy update removes permissions to delete the resource, the resource deletion fails.

Timestamp | Logical ID | Status | Status Reason | Type
------------ | ------------- | ------------- | ------------- | -------------
2020-08-19 12:52:11 UTC-0400 | AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E |UPDATE_IN_PROGRESS | | AWS::IAM::Policy
2020-08-19 12:52:27 UTC-0400 | AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E |UPDATE_COMPLETE | | AWS::IAM::Policy
2020-08-19 12:56:11 UTC-0400 | CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_IN_PROGRESS | | AWS::CloudFormation::CustomResource
2020-08-19 12:57:12 UTC-0400 | CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_FAILED | Failed to delete resource. User: arn:aws:sts::123456789012:assumed-role/alpha-AWS679f53fac002430cb0da5b7982bd2287ServiceRo-WTH8L2RRAM8O/alpha-AWS679f53fac002430cb0da5b7982bd22872D164C4C-JACGZKNLR8JK is not authorized to perform: codedeploy:DeleteDeploymentConfig on resource: arn:aws:codedeploy:us-west-2:123456789012:deploymentconfig:CustomDeploymentLambdaLinear5Percent2Minutes | AWS::CloudFormation::CustomResource
2020-08-19 12:56:11 UTC-0400 | CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_IN_PROGRESS | | AWS::CloudFormation::CustomResource
2020-08-19 12:57:12 UTC-0400 | CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_FAILED | Failed to delete resource. User: arn:aws:sts::123456789012:assumed-role/alpha-AWS679f53fac002430cb0da5b7982bd2287ServiceRo-WTH8L2RRAM8O/alpha-AWS679f53fac002430cb0da5b7982bd22872D164C4C-JACGZKNLR8JK is not authorized to perform: codedeploy:DeleteDeploymentConfig on resource: arn:aws:codedeploy:us-west-2:123456789012:deploymentconfig:CustomDeploymentLambdaLinear5Percent2Minutes | AWS::CloudFormation::CustomResource
2020-08-19 13:00:14 UTC-0400 | CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_IN_PROGRESS | | AWS::CloudFormation::CustomResource
2020-08-19 13:00:16 UTC-0400 | CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_FAILED | Failed to delete resource. User: arn:aws:sts::123456789012:assumed-role/alpha-AWS679f53fac002430cb0da5b7982bd2287ServiceRo-WTH8L2RRAM8O/alpha-AWS679f53fac002430cb0da5b7982bd22872D164C4C-JACGZKNLR8JK is not authorized to perform: codedeploy:DeleteDeploymentConfig on resource: arn:aws:codedeploy:us-west-2:123456789012:deploymentconfig:CustomDeploymentLambdaLinear5Percent2Minutes | AWS::CloudFormation::CustomResource
2020-08-19 13:03:18 UTC-0400| CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_IN_PROGRESS | | AWS::CloudFormation::CustomResource
2020-08-19 13:03:20 UTC-0400 | CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95 |DELETE_FAILED | Failed to delete resource. User: arn:aws:sts::123456789012:assumed-role/alpha-AWS679f53fac002430cb0da5b7982bd2287ServiceRo-WTH8L2RRAM8O/alpha-AWS679f53fac002430cb0da5b7982bd22872D164C4C-JACGZKNLR8JK is not authorized to perform: codedeploy:DeleteDeploymentConfig on resource: arn:aws:codedeploy:us-west-2:123456789012:deploymentconfig:CustomDeploymentLambdaLinear5Percent2Minutes | AWS::CloudFormation::CustomResource

--- 

This is :bug: Bug Report

**Comment by flemjame-at-amazon** [comment]
I was able to workaround the bug by creating a dummy custom resource which contains the same permissions. This way, when the IAM policy is updated, the permissions are technically still there so the resource can be deleted.

**Comment by flemjame-at-amazon** [comment]
Thinking on this more, I wonder if the problem is because AwsCustomResource uses a singleton function to do all AwsSdkCalls.

**Comment by rix0rrr** [comment]
Can you help me out by double-checking something for me in your template? As far as I can think of, the dependency/reference graph inside CloudFormation should look like this:

```
   ┌─────────────────┐  ExecutionRo  ┌───────────────────┐   Provider:  ┌───────────────────┐
   │                 │    le: Ref    │                   │    GetAtt    │                   │
   │    IAM::Role    │◀──────────────│ Lambda::Function  │◀─────────────│ Custom::Resource  │
   │                 │               │                   │              │                   │
   └─────────────────┘               └───────────────────┘              └───────────────────┘
            ▲                                  │                                             
            │                                  │                                             
            │    ┌─────────────────┐           │ DependsOn                                   
PolicyName: │    │                 │           │                                             
    Ref     └────│   IAM::Policy   │◀──────────┘                                             
                 │                 │                                                         
                 └─────────────────┘                                                         
```

Feels like the only proper OnDelete order would delete the CustomResource here before Deletion the Function or the Policy.

Might be that the DependsOn between the Function and the Policy is missing, which means there's a race condition which just happens to (apparently) never trigger OnCreate, but DOES trigger OnDelete.

What does your template look like?

**Comment by flemjame-at-amazon** [comment]
> Can you help me out by double-checking something for me in your template? As far as I can think of, the dependency/reference graph inside CloudFormation should look like this:
> 
> ```
>    ┌─────────────────┐  ExecutionRo  ┌───────────────────┐   Provider:  ┌───────────────────┐
>    │                 │    le: Ref    │                   │    GetAtt    │                   │
>    │    IAM::Role    │◀──────────────│ Lambda::Function  │◀─────────────│ Custom::Resource  │
>    │                 │               │                   │              │                   │
>    └─────────────────┘               └───────────────────┘              └───────────────────┘
>             ▲                                  │                                             
>             │                                  │                                             
>             │    ┌─────────────────┐           │ DependsOn                                   
> Roles:      │    │                 │           │                                             
>     Ref     └────│   IAM::Policy   │◀──────────┘                                             
>                  │                 │                                                         
>                  └─────────────────┘                                                         
> ```
> 
> Feels like the only proper OnDelete order would delete the CustomResource here before Deletion the Function or the Policy.
> 
> Might be that the DependsOn between the Function and the Policy is missing, which means there's a race condition which just happens to (apparently) never trigger OnCreate, but DOES trigger OnDelete.
> 
> What does your template look like?

This is the template with the custom resource.

Custom resource:
```
    "CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig986A9D95": {
      "Type": "Custom::AWS",
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "AWS679f53fac002430cb0da5b7982bd22872D164C4C",
            "Arn"
          ]
        },
        "Create": {
          "action": "createDeploymentConfig",
          "service": "CodeDeploy",
          "parameters": {
            "computePlatform": "Lambda",
            "deploymentConfigName": "CustomDeploymentLambdaLinear5Percent2Minutes",
            "trafficRoutingConfig": {
              "timeBasedLinear": {
                "linearPercentage": "5",
                "linearInterval": "2"
              },
              "type": "TimeBasedLinear"
            }
          },
          "physicalResourceId": {
            "id": "CustomDeploymentLambdaLinear5Percent2Minutes"
          }
        },
        "Delete": {
          "action": "deleteDeploymentConfig",
          "service": "CodeDeploy",
          "parameters": {
            "deploymentConfigName": "CustomDeploymentLambdaLinear5Percent2Minutes"
          }
        }
      },
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "alpha/CustomDeploymentLambdaLinear5Percent2MinutesDeploymentConfig/Resource/Default"
      }
    }
```

Function:
```
    "AWS679f53fac002430cb0da5b7982bd22872D164C4C": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "deploymentbucket-06336367b01914a34be8b607f126c5de94ea0c80",
          "S3Key": {
            "Fn::Join": [
              "",
              [
                {
                  "Ref": "PackagingS3KeyPrefix"
                },
                "/",
                {
                  "Ref": "PackagingAggregateId"
                },
                "_transform/cdk.out/asset.f883e12689f8357ff04376b1abab555e2b18f9992e78242d504a2c4d74bb50cc.zip"
              ]
            ]
          }
        },
        "Handler": "index.handler",
        "Role": {
          "Fn::GetAtt": [
            "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x",
        "Timeout": 120
      },
      "DependsOn": [
        "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E",
        "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2"
      ],
      "Metadata": {
        "aws:cdk:path": "alpha/AWS679f53fac002430cb0da5b7982bd2287/Resource",
        "aws:asset:path": "asset.f883e12689f8357ff04376b1abab555e2b18f9992e78242d504a2c4d74bb50cc",
        "aws:asset:property": "Code"
      }
    }
```

Policy:
```
    "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": "ec2:DescribeSecurityGroups",
              "Effect": "Allow",
              "Resource": "*"
            },
            {
              "Action": "codedeploy:CreateDeploymentConfig",
              "Effect": "Allow",
              "Resource": "*"
            },
            {
              "Action": "codedeploy:DeleteDeploymentConfig",
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E",
        "Roles": [
          {
            "Ref": "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2"
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "alpha/AWS679f53fac002430cb0da5b7982bd2287/ServiceRole/DefaultPolicy/Resource"
      }
    }
```
Role:
```
    "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
              ]
            ]
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "alpha/AWS679f53fac002430cb0da5b7982bd2287/ServiceRole/Resource"
      }
    }
```

**Comment by flemjame-at-amazon** [comment]
> Can you help me out by double-checking something for me in your template? As far as I can think of, the dependency/reference graph inside CloudFormation should look like this:
> 
> ```
>    ┌─────────────────┐  ExecutionRo  ┌───────────────────┐   Provider:  ┌───────────────────┐
>    │                 │    le: Ref    │                   │    GetAtt    │                   │
>    │    IAM::Role    │◀──────────────│ Lambda::Function  │◀─────────────│ Custom::Resource  │
>    │                 │               │                   │              │                   │
>    └─────────────────┘               └───────────────────┘              └───────────────────┘
>             ▲                                  │                                             
>             │                                  │                                             
>             │    ┌─────────────────┐           │ DependsOn                                   
> Roles:      │    │                 │           │                                             
>     Ref     └────│   IAM::Policy   │◀──────────┘                                             
>                  │                 │                                                         
>                  └─────────────────┘                                                         
> ```
> 
> Feels like the only proper OnDelete order would delete the CustomResource here before Deletion the Function or the Policy.
> 

I'm not deleting the function or the policy -- I have two custom resources, and because the function is a singleton, deleting the second custom resource won't cause the function or policy to be deleted. As such, the policy goes through an Update, not a Delete.

I have no doubt that if I had just the one custom resource, the deletion would be handled correctly.

**Comment by rix0rrr** [comment]
AH! Good detail, of course you are correct.

In that case, I wonder if adding a dependency from the Custom Resource to the Policy would be sufficient, or whether we need a Policy per Custom Resource.

**Comment by flemjame-at-amazon** [comment]
> AH! Good detail, of course you are correct.
> 
> In that case, I wonder if adding a dependency from the Custom Resource to the Policy would be sufficient

In this situation, wouldn't the policy update before or after the resource was deleted?

> or whether we need a Policy per Custom Resource

Would this push the problem onto the Lambda function? Where the function would update first (removing the policy), then the custom resource would be deleted?

**Comment by flemjame-at-amazon** [comment]
I did a quick simulated test where I had a resource (in my case a VPC) which had a `DependsOn` on a Policy. I created them in one CFN update, then in the second update I deleted the VPC and modified the policy. In this case, the update came before the delete again. It seems that the policy update would happen before the resource was deleted, so adding the dependency wouldn't be enough.

**Comment by flemjame-at-amazon** [comment]
I tested the second option, where there is a policy for each custom resource and the resource depends on the policy. In this case, both were deleted, with the resource being deleted first.
