### ISSUE TITLE
[aws-stepfunctions] State ___ already has a next state

### ISSUE THREAD

**Issue by sudopla** [aws/aws-cdk#9843]
In the example below I would like to replace the `Pass` state in the condition with `UploadMessage`. But the problem is that CDK returns the following error - _State 'Upload Message' already has a next state_

If I go to the console and edit the JSON file manually, it works.

```
const definition = sfn.Chain
        .start(new sfn.Choice(this, 'Job Type ?')
            .when(sfn.Condition.stringEquals('$.jobtype', 'job_type_1'), new sfn.Pass(this, 'Pass'))
            .otherwise(runLambda1.next(runLambda2))
            .afterwards())
        .next(UploadMessage)
        .next(runFargateTask)

```

Do you know if there's a way to remove this `Pass` state and send this condition directly to the `UploadMessage` state in CDK?

**Comment by sudopla** [comment]
I figured this out. 

```
const definition = sfn.Chain
        .start(new sfn.Choice(this, 'Job Type ?')
            .when(sfn.Condition.stringEquals('$.jobtype', 'job_type_1'), UploadMessage.next(runFargateTask)
            .otherwise(runLambda1.next(runLambda2).next(UploadMessage))
```

**Comment by madeesha** [comment]
Thanks for posting the resolution.
