### ISSUE TITLE
[aws-stepfunctions] Python result_path not making it into sfn definition. 

### ISSUE THREAD

**Issue by michaelconnor00** [aws/aws-cdk#9844]
When creating a stepfunction where you don't want the output of a task merged (added) to the stepfunction JSON context, you add `"ResultPath": null`. In the Python class for `aws_stepfunctions_tasks.BatchSubmitJob`, for example, there is a kwargs for `result_path: Optional[str] = None`. By default, the Python `result_path=None` should output JSON as `"ResultPath": null`. However, I have not been able to get the Python code to output with that parameter when it is None, it is ignored. 

### Reproduction Steps

```python
image_process_task = aws_stepfunctions_tasks.BatchSubmitJob(
    self,
    'image-process-batch',
    job_name='image-process-batch-job',
    job_definition=batch_image_job,
    job_queue=cpu_queue,
    result_path=None,
)
print(json.dumps(image_process_task.to_state_json(), indent=2))
```

This outputs the following json:
```json
{
  "End": true,
  "Type": "Task",
  "Resource": "arn:${Token[AWS::Partition.3]}:states:::batch:submitJob.sync",
  "Parameters": {
    "JobDefinition": "${Token[...]}",
    "JobName": "image-process-batch-job",
    "JobQueue": "${Token[...]}"
  }
}
```
The attribute `"ResultPath": null` is missing. Same thing happens with `aws_stepfunctions.Map`, and maybe more classes.

### What did you expect to happen?

I expect there to be an appropriate Python value for `result_path`, that will output the JSON equivalent `"ResultPath": null`.

### What actually happened?

Seems in Python when `result_path=None`, it takes it as don't include it. But the Amazon states language says the default value for `ResultPath` is `"$"` which is not what I want.  

### Environment

  - **CLI Version      :** 1.59.0
  - **Framework Version:** 1.59.0
  - **Node.js Version:** v12.18.3 
  - **OS               :** Linux pop-os 5.4.0-7634-generic (20.04)
  - **Language (Version):** Python 3.7.7 

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
hey @michaelconnor00 , have you tried using the [`DISCARD`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions/JsonPath.html#aws_cdk.aws_stepfunctions.JsonPath.DISCARD) attribute? 

rather than `result_path=None`, you should be able to supply `JsonPath.DISCARD` 
I'm going to mark this as `guidance` for now. let me know how it goes! 

we can update the README/classify it as a bug if there's still an issue with it.

**Comment by michaelconnor00** [comment]
@shivlaks Thank you! That did what I needed. I also see it in the docs now: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions/Task.html. Cheers.
