### ISSUE TITLE
[appsync]: Data Source breaking change

### ISSUE THREAD

**Issue by asnaseer-resilient** [aws/aws-cdk#9854]
I just tried the latest CDK v1.60.0 and changed these lines of code in my existing deployment from this:
```
    const lambdaApiResolverDataSource = graphQlApi.addLambdaDataSource(
      'LambdaApiResolverDataSource',
      `Resolves GraphQL requests for ${product}`,
      lambdaApiResolverFunction
    );
```
to this:
```
    const lambdaApiResolverDataSource = graphQlApi.addLambdaDataSource('LambdaApiResolverDataSource', lambdaApiResolverFunction, {
      description: `Resolves GraphQL requests for ${product}`
    });
```
When the deployment ran, it failed with this:
```
AppSyncConstructGraphQLLambdaApiResolverDataSourceBAD1E2A7
CREATE_FAILED
Data source with name LambdaApiResolverDataSource already exists (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 45ade8da-9b90-432e-9620-0de300aaf18a; Proxy: null)
```
This is for an existing AppSync deployment. This code was working in the previous release I had (v1.59.0).

### Reproduction Steps

As described above.

### What did you expect to happen?

The deployment should have succeeded.

### What actually happened?

The deployment failed with:
```
AppSyncConstructGraphQLLambdaApiResolverDataSourceBAD1E2A7
CREATE_FAILED
Data source with name LambdaApiResolverDataSource already exists (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 45ade8da-9b90-432e-9620-0de300aaf18a; Proxy: null)
```

### Environment

  - **CLI Version      : v1.60.0**
  - **Framework Version:**
  - **Node.js Version: v12.4.0**
  - **OS               : Deployment ran on CircleCI**
  - **Language (Version): Typescript 3.9.7**

### Other

--- 

This is :bug: Bug Report

**Comment by asnaseer-resilient** [comment]
I had to delete my AppSync deployment on AWS and then re-deploy it for it to work again.

**Comment by andrestone** [comment]
Probably [this](https://github.com/aws/aws-cdk/pull/9254) changed the construct tree which is what generates the correspondent logical ID in the synthesized template, making CloudFormation think you were creating a new data source.

I'm not sure there's something to be fixed here. Maybe make sure such things appear in the "Breaking Changes"?

**Comment by asnaseer-resilient** [comment]
Thanks for tracking it down - and I agree it should definitely have appeared in the "Breaking Changes".

We have 3 APIs that have been deployed to live and a web app that uses them. This breakage meant that I had to delete the 3 APIs and then re-deploy them which caused their corresponding GraphQL endpoints to change. I then had to update my web app with the new endpoints and re-deploy that.

I realise this is an evolving library and really appreciate all the work everyone has put into this. Many people now use this in production and therefore it would be really appreciated if any changes could be made such that they do not imply a deployment of resources - I know this is hard but just something to think about.

**Comment by BryanPan342** [comment]
@andrestone thanks for the initiative in looking into this

@asnaseer-resilient thanks for the feedback! I apologize, I should have written a better commit description highlighting the potential effects. The AppSync module a couple of months ago used to be a monolithic single file with virtually no unit tests. Currently, I have been trying to clean up the library and make sure it functions similarly to the rest of the CDK.

I definitely keep this in mind as I make changes in the future!

**Comment by asnaseer-resilient** [comment]
@BryanPan342 Thanks - and don't get me wrong - I really appreciate the amazing work all of you are putting into this library. It is by far the best deployment framework I have ever worked with (and I have been coding for more than 30 years).

**Comment by asnaseer-resilient** [comment]
BTW: I assume you guys are using semantic versioning which states:

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.

It will therefore help even more if you always change the MAJOR version when making a breaking change.
