### ISSUE TITLE
[cli] Cache mfa credentials 

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#9855]
It's great to see that the CDK CLI now supports MFA since #6510 was merged! However, the MFA credentials are not cached, which means that for every deploy/synth/diff it requires you to enter your MFA credentials again.

### Use Case
As a user I would like to not have to enter my MFA credentials for every CLI command.

### Proposed Solution
Cache the credentials in some way for some amount of time so that users don't have to enter their MFA credentials every time they call a CLI command.

---

This is a :rocket: Feature Request

**Comment by johanli-axis** [comment]
Any news on this? Since the update it also disabled the possibility to use the third party solution aws-mfa which would cache the MFA credentials, getting more and more frustrating having to input the MFA code every command. 😢

**Comment by TheRealAmazonKendra** [comment]
Closing this in favor of linked duplicate issue.
