### ISSUE TITLE
[core] Synthesizing all stacks when explicitly deploying one causing undesireable side-effects

### ISSUE THREAD

**Issue by robert-hanuschke** [aws/aws-cdk#9857]
When defining cross-account projects in CDK, we put values to reference in a different account into cdk.json, e.g. the ARN of a resource to be created (as CloudFormation Outputs don't work cross account).
When synthesizing a stack that relies on that value being present, we fail the operation if self.node.try_get_context("<key>") is not successful to warn the user that they might have forgotten to put the value there or trying to deploy the stacks in the wrong order.

This obviously means we have to deploy the stacks in order, beginning with the ones that create the resources to be referenced.

When we deploy that single stack others rely on by **specifically** naming it in "cdk deploy <**stack name**>" though, cdk synthesizes **all** of them and fails the synth for a different stack we know cannot succeed due to the resource we need to put the arn into cdk.json is not even existing.

### Reproduction Steps

1. Create a stack that requires a value from cdk.json using node.try_get_context and failing synthesizing if not present (if not self.node.try_get_context("key"): raise...)
2. Create a different stack
3. Deploy the stack from step 2 by specifically naming it in the cdk deploy command

### What did you expect to happen?

The stack created in step 2 and specifically named for deployment gets synthesized and deployed

### What actually happened?

The command fails as CDK tries to synthesize the stack from step 1 even though no action on it was requested at all

### Environment

  - **CLI Version      :** aws-cli/2.0.28 Python/3.7.7 Windows/10 botocore/2.0.0dev32
  - **Framework Version:** 1.59.0 (build 1d082f4)
  - **Node.js Version:** v12.18.2
  - **OS               :** Windows 10
  - **Language (Version):** Python 3.8.3

### Other

Currently, we have to use the ugly workaround of adding context variables to our deploy commands which are checked in app.py and skip synthesizing of totally unrelated stacks.

I would expect the CDK to only synthesize the stack requested for deployment if specifically naming it which would tidy up our code and not require us to awkwardly work with skipping context variables any more.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Seems that the failure is under your own control. Instead of raising an exception, you can choose to add an error annotation. This will prevent deployment without failing the synthesis.

**Comment by robert-hanuschke** [comment]
We certainly _can_ do that, but it increases chance of user error as just a logged notification is easily overlooked and it adds coding burden to AWS's customers. In general, it is confusing to get error messages of stacks that have specifically not been requested to do anything with.

It's just not user friendly.

Not tackling this is an easy way out on the CDK side without apparent benefits. Do the stacks all need to be synthed for a single one to be deployed?

**Comment by ryanwilliams83** [comment]
The virtual method OnSynthesize() seems to be getting executed in all stacks when I run `cdk synth <SpecificStackName>`.

**Comment by Aeolun** [comment]
Why is this closed? It seems strange that CDK works this way. If you already know what stack to synthesize, why try to do it for all the others?

On a technical level I know you can't actually do this because of the way the stack is just instantiating a bunch of Typescript classes, but it has to be one of the most counterintuitive parts of the whole thing.
