### ISSUE TITLE
[lambda] unable to use my host OS $HOME/.m2 for bundling, a $PWD/?/.m2 directory gets created in the host OS

### ISSUE THREAD

**Issue by lestephane** [aws/aws-cdk#9858]
I'm trying to re-use the `${HOME}/.m2` directory on my host system to avoid having to re-download all maven artifacts from scratch when there's a perfectly good copy of those artifacts already present on my system.

What is currently happening is that a directory called `?/.m2` gets created in the working directory where the `cdk` command is run, which is confusing, to say the least.

I was able in a previous version of the CDK to setup a volume that I would pass to the `lambda.Code.fromAsset`'s `bundling` parameter: 

```typescript
const m2Volume = {
    containerPath: '/.m2',
    hostPath: `${process.env['HOME']}/.m2`
}
...
const otherDepsLayer = new lambda.LayerVersion(this, 'OtherDeps', {
    compatibleRuntimes: [props.runtime],
    code: lambda.Code.fromAsset(props.basePath, {
        bundling: {
            image: props.runtime.bundlingDockerImage,
            volumes: [m2Volume],
            command: ['bash', '-c', otherDepsCommand],
        },
    }),
});
```

I would then make sure all maven commands use the `-Duser.home=/` JVM argument.

And amazingly, it would work.

Now it no longer does, and I have absolutely no workaround.

There is a `?/.m2` directory getting created everytime I run a maven command that needs to save something to `${HOME}/.m2` (or what it thinks `${HOME}/.m2` is) in the container.

Has anyone been able to bundle using maven successfully without this `$PWD/?/.m2 ` getting created?

**Comment by lestephane** [comment]
Hmm it turns out I forgot to add `-Duser.home=/`in a maven command I had added just today, hence the dismay. So my workaround is still working.

So this issue may be about filling a documentation gap for maven users of CDK. People should be told how to make use of their $HOME/.m2 for bundling. My issue description provides a blueprint for how this can be achieved, but it feels pretty hacky. You be the judge.

**Comment by nisabek** [comment]
There's definitely something fishy going on with the permissions between the docker and the host or simply within the docker image provided. In my case I didn't neceserraly want to use the local cache, but this failed:

```
            code: lambda.AssetCode.fromAsset(codePath,  {
                bundling: {
                    command: ["npm", "run", "dist"],
                    image: lambda.Runtime.NODEJS_12_X.bundlingDockerImage
                }
            }),
```

with 
```
npm ERR! correctMkdir failed to make directory /.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/.npm"
```

So I used the solution mentioned here with sharing my host ~.m2~ .npm

so, this works:

```
   const handler = new lambda.Function(this, `Function`, {
            environment: {},
            code: lambda.AssetCode.fromAsset(codePath,  {
                bundling: {
                    command: ["npm", "run", "dist"],
                    image: lambda.Runtime.NODEJS_12_X.bundlingDockerImage,
                    volumes: [{
                        containerPath: '/.npm',
                        hostPath: `${process.env['HOME']}/.npm`
                    }]
                }
            }),
            handler: 'app.handler',
            runtime: lambda.Runtime.NODEJS_12_X,
            timeout: core.Duration.minutes(1)
        });
```

**Comment by eladb** [comment]
@jogold should we add this to out docs?
