### ISSUE TITLE
[assets] layer and function assets bundled through lambda.Code.fromAsset bundling option keep getting re-uploaded and new versions published despite nothing having changed

### ISSUE THREAD

**Issue by lestephane** [aws/aws-cdk#9861]
I have a lambda function that uses two lambda layers to optimize for my use case (slow upload speed where I live).

It contains 3 assets:

- layer asset for 'other' jars (the third party dependencies that get changed the least often)

```typescript
const otherDepsLayer = new lambda.LayerVersion(this, 'OtherJars', {
    compatibleRuntimes: [props.runtime],
    code: lambda.Code.fromAsset(props.basePath, {
        bundling: {
            image: props.runtime.bundlingDockerImage,
            volumes: [m2Volume],
            command: ['bash', '-c', otherDepsCommand],
        },
    }),
});
```

- layer asset for 'our' jars (the other modules in a maven reactor project that may have a higher rate of change)

```typescript
const ourDepsLayer = new lambda.LayerVersion(this, 'OurJars', {
    compatibleRuntimes: [props.runtime],
    code: lambda.Code.fromAsset(props.basePath, {
        bundling: {
            image: props.runtime.bundlingDockerImage,
            volumes: [m2Volume],
            command: ['bash', '-c', ourDepsCommand],
        },
    }),
});
```

- lambda function classes asset (the module with the highest rate of change when I develop it)

```typescript
this.lambdaFunction = new lambda.Function(this, "Function", {
    ...props,
    layers: [otherDepsLayer, ourDepsLayer],
    code: lambda.Code.fromAsset(props.basePath, {
        bundling: {
            image: props.runtime.bundlingDockerImage,
            volumes: [m2Volume],
            command: ['bash', '-c', commandToBundleClasses],
        },
    }),
})
```

When I run `cdk deploy` twice in a row (within modifying anything in between), I expect:

- the 'other' jars asset not be uploaded, no new layer version to be created
- the 'our' jars asset not be uploaded, no new layer version to be created
- the lambda function classes assets not to be uploaded, no new lambda function to be created
- no new asset.* directory to be created in cdk.out
 
What happens

- the 'other' jars asset is uploaded again (it says `start: Publishing` then `success: Published`)
- a new 'other' jars layer version is created  
- the 'our' jars asset is uploaded again (it says `start: Publishing` then `success: Published`)
- a new 'our' jars layer version is created  
- the lambda function classes assets is uploaded again (it says `start: Publishing` then `success: Published`)
- a new lambda function version is created

I was going to spend time making sure 'our' jars are created in a reproducible manner to ensure the checksums
are always the same. But that will be for nought if there is no intelligence in the CDK for asset content deduplication.

This is already how SAM CLI works, so I'd expect CDK to have the same behaviour.

**Comment by misterjoshua** [comment]
If you change `assetHashType` to `BUNDLE`, do you have the same problem?

**Comment by lestephane** [comment]
Sorry for the delay. Adding `AssetHashType.Bundle` helps. But it feels counter intuitive to have to specify this when someone is using `bundling` right next to it. Shouldn't the very presence of the `bundling` property swich the AssetHashType to `Bundle` by default?

```typescript
code: lambda.Code.fromAsset(props.basePath, {
    assetHashType: AssetHashType.BUNDLE,                // <<<<<<<<<< this...
    bundling: {                                         // <<<<<<<<<< ..could be derived from this 
        image: props.runtime.bundlingDockerImage,
        volumes: [m2Volume],
        command: ['bash', '-c', otherDepsCommand],
    },
}),
```

**Comment by eladb** [comment]
@jogold can you take a look?

**Comment by jogold** [comment]
> But it feels counter intuitive to have to specify this when someone is using `bundling` right next to it. Shouldn't the very presence of the `bundling` property swich the AssetHashType to `Bundle` by default?

I understand but the default for `bundling` is `AssetHashType.SOURCE`. Usually the bundling operation is not "pure", especially when dependencies are installed so its best to rely on the hash of the source for stability.

**Comment by eladb** [comment]
Should we rename `AssetHashType.BUNDLE` to `SOURCE`?

**Comment by eladb** [comment]
`OUTPUT`

**Comment by lestephane** [comment]
I guess I don't understand the difference between SOURCE and BUNDLE yet (or I kinda do, but I think the way it's explained is insufficient and / or misleadging).

The API documentation for AssetHashType should really explain what's going on, and why one would want to use one vs the other. The optimal answer will vary based on the runtime for example, so that even choosing a default for the user is fraught for risks. 

Documentation:
```typescript
/**
 * The type of asset hash
 */
export declare enum AssetHashType {
    /**
     * Based on the content of the source path
     */
    SOURCE = "source",
    /**
     * Based on the content of the bundled path
     */
    BUNDLE = "bundle",
```
