### ISSUE TITLE
[aws-ec2] Interface endpoints are incorrect in China

### ISSUE THREAD

**Issue by efernandes-dev-ops** [aws/aws-cdk#9864]
We are trying to create a VPC endpoint to ECR in china region (cn-north-1). 

The service that comes back when running the code below is "com.amazonaws.cn-north-1.ecr.dkr". However upon looking at aws console when manually adding a vpc ecr endpoint the service name is "cn.com.amazonaws.cn-north-1.ecr.dkr".

As a result of the incorrect service name cloudformation throws an error stating it can't find the service/it does not exist.

### Reproduction Steps

`ecr_endpoint = self.vpc.add_interface_endpoint("%s-ECREndpoint" % namespace, service= ec2.InterfaceVpcEndpointAwsService.ECR_DOCKER)`

### What did you expect to happen?

The right service name to be returned "cn.com.amazonaws.cn-north-1.ecr.dkr"

### What actually happened?

The wrong service name came back "com.amazonaws.cn-north-1.ecr.dkr". As a result cloudformation cannot create the vpc endpoint

### Environment

  - **CLI Version      :** 1.54.0 (build c01b9b9)
  - **Framework Version:**
  - **Node.js Version:**   v12.18.3
  - **OS               :** mac
  - **Language (Version):**  Python (3.7.3)

### Other

--- 

This is :bug: Bug Report

**Comment by efernandes-dev-ops** [comment]
The full error returned back from AWS 

"The Vpc Endpoint Service 'com.amazonaws.cn-north-1.ecr.dkr' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidServiceName; Request ID: b84640b9-adb4-43ed-b7bd-dca784cf249b; Proxy: null)"

**Comment by rix0rrr** [comment]
Do you know if this is true only for this specific service, or is it true for all interface endpoints in the Chinese partition?

**Comment by efernandes-dev-ops** [comment]
Not too sure, will need to check

**Comment by mikeler216** [comment]
The Vpc Endpoint Service 'com.amazonaws.cn-northwest-1.sqs' does not exist I think this is for every service
@rix0rrr

**Comment by visunali** [comment]
when can we fix this issue? this is blocking us creating vpc endpoint via CDK

**Comment by ZeBidule** [comment]
Hi, I have the same issue with the terraform data `aws_vpc_endpoint_service` in china :
### Code
```
provider "aws" {
  region  = "cn-north-1"
  profile = "china"
}

data "aws_vpc_endpoint_service" "sqs" {
  service = "sqs"
}

output "sqs_endpoint_service" {
  value = data.aws_vpc_endpoint_service.sqs
}
```
### Output
```
> terraform apply                                                          
data.aws_vpc_endpoint_service.sqs: Refreshing state...

Error: error reading VPC Endpoint Service (com.amazonaws.cn-north-1.sqs): InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.cn-north-1.sqs' does not exist
        status code: 400, request id: 5fb025e4-5aa5-4ba1-975e-055c98d66830
 ```
### Expected result
`cn.com.amazonaws.cn-north-1.sts`

**Comment by njlynch** [comment]
Contributions are absolutely welcome, @readybuilderone ! See https://github.com/aws/aws-cdk/pull/14721 for a previous attempt, including some comments on that approach.

**Comment by readybuilderone** [comment]
Thanks @njlynch , since there are two regions with different endpoints prefix in China(cn-north-1, cn-northwest-2), and the services in cn-north-1 and cn-northwest-2 are not exactly the same, so the previous attempt in #14721 will not fix this issue.
Shall we discuss my draft idea here or move to #14721 ?

**Comment by readybuilderone** [comment]
Thanks @njlynch , I studied the previous attempt in  [#14721](https://github.com/aws/aws-cdk/pull/14721) , and found:
1. In cn-north-1 and cn-northwest-1, the vpc endpoint prefix is both region and service related, so exception rules should be defined.
2. It's hard to maintain the exception rules manually, instead we should keep the rules up to date automatically.

And I found we could get the vpc endpoint prefix via [AWS API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpoints.html ), and we could use the javascript [AWS-SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeVpcEndpoints-property) to fetch the vpc endpoints. However the AWS-SDK supports only asynchronous call, and the asynchronous call could not be done in the constructor. So I am not sure what's the best pattern to handle it, do you think the [readiness pattern](https://pdconsec.net/blogs/devnull/asynchronous-constructor-design-pattern) is a good idea?  @njlynch @NetaNir @pahud

**Comment by njlynch** [comment]
> It's hard to maintain the exception rules manually, instead we should keep the rules up to date automatically.

While this would be ideal, we don't currently have the infrastructure in place to make routing AWS API calls and commit that result. The alternative -- as you note -- is making live AWS calls as part of CDK synthesis/object construction itself, which isn't a great idea.

> It's hard to maintain the exception rules manually, instead we should keep the rules up to date automatically.

While it's not ideal, I think curating the list manually is acceptable. This values won't ever change (only be added to), and the rate of change should be relatively small in the grand scheme.
