### ISSUE TITLE
[aws-iam] FederatedPrincipal JSON dump does not include conditions

### ISSUE THREAD

**Issue by allistera** [aws/aws-cdk#9868]
When running to_json() method against a FederatedPrincipal class the dump does not include conditions.

### Reproduction Steps

```
        print(FederatedPrincipal(federated="arn:aws:iam::1213231232213:saml-provider/FooBar", conditions=[{
            "StringEquals": {
                "SAML:aud": "https://signin.aws.amazon.com/saml"
            }
        }]).to_json())
```

### What did you expect to happen?

Returns:

```
{'Federated': ['arn:aws:iam::1213231232213:saml-provider/FooBar'], 'Conditions': [{"StringEquals": {"SAML:aud": "https://signin.aws.amazon.com/saml"}}]}
```

### What actually happened?

Returns:

```
{'Federated': ['arn:aws:iam::1213231232213:saml-provider/FooBar']}
```

### Environment

  - **CLI Version   1.36.1 (build 4df7dac)   :**
  - **Node.js Version:** v14.4.0
  - **OS               : OSX**
  - **Language (Version):** Python 3.8.0

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Why are you printing the `to_json()`? Is your template also incorrect when using the principal in a `PolicyStatement`?

**Comment by allistera** [comment]
Printing was just for debugging purposes. 

The use case would be to create an Escape hatch to 'hack' the resulting JSON into a trust policy for an IAM role - as CompositePrincipal does not support principals with conditionals.
