### ISSUE TITLE
[aws-eks] - CDK support for Custom AMI Support for EKS Managed Nodes feature

### ISSUE THREAD

**Issue by haofeif** [aws/aws-cdk#9873]
Amazon Elastic Kubernetes Service (EKS) now supports EC2 Launch Templates and custom AMIs for managed node groups. When combined, these new features provide flexible configuration and customization options for Amazon EC2 instances which are managed as Kubernetes nodes by EKS. This enables you to leverage the simplicity of managed node provisioning and lifecycle management features while adhering to any level of customization, compliance, or security requirements.

https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/

### Use Case

Customers who needs Custom AMI to clear the blocker to adopt the EKS Managed Node Group solution, is now available to use the new feature provided from the EKS Managed Node Group.
However, the CDK currently yet to support the feature.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
I am working on the unmanaged NG support today, will cut a PR for this first and then continue the managed NG.

https://twitter.com/pahudnet/status/1296447254363025410

**Comment by pahud** [comment]
I am the original contributor of the managed nodegroup. I'll try extend it with the custom AMI support with a new PR.

**Comment by haofeif** [comment]
@pahud @SomayaB  Hi, i saw that the change not released in the cdk 1.61. Is this expected to be released in the next cdk version 1.62 ?

**Comment by pahud** [comment]
Hi @haofeif

We are still pending this PR for approval. https://github.com/aws/aws-cdk/pull/9881

**Comment by boazsilverman** [comment]
Reading these comments, it seems to me that there currently is a possibility to use CDK for creating nodes with custom AMI. Can someone please explain how to do this?
Thanks

**Comment by iliapolo** [comment]
@boazsilverman https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks#launch-template-support

**Comment by boazsilverman** [comment]
Hi Eli, thank you very much for the response. I am writing my code in
Python, and when I try to translate the code you referenced to python it
doesn't seem to work.
Any chance you have that same code in Python that I can use as a reference?

Thanks a lot,
Boaz

**Comment by boazsilverman** [comment]
Hey, when trying to apply exactly the same logic, just in Python, here is
the result I got:
[image: image.png]

My code is attached:
ssh_connection = aws_eks.NodegroupRemoteAccess(
            ssh_key_name="cdk-pair-ohio",
            source_security_groups=[cluster.cluster_security_group]
        )
        user_data = aws_ec2.UserData.custom(
'/aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/image_id')
        user_data.add_commands("set -o xtrace", f"/etc/eks/bootstrap.sh {
cluster.cluster_name}")

        ltd = aws_ec2.CfnLaunchTemplate.LaunchTemplateDataProperty(
            image_id="ami-0ebe2603fe80091fd",
            instance_type="t3.small",
            user_data=core.Fn.base64(user_data.render()),
        )

        lt = aws_ec2.CfnLaunchTemplate(scope=self, id="LaunchTemplate",
                                       launch_template_data=ltd
                                       )
        lts = aws_eks.LaunchTemplateSpec(id=lt.ref)
        group = aws_eks.Nodegroup(
            scope=self,
            id=f'{id}-nodegroup',
            cluster=cluster,
            nodegroup_name=f'{id}-nodegroup',
            remote_access=ssh_connection,
            launch_template_spec=lts,
            min_size=2,
            max_size=100,
        )

Any chance you understand the problem, and can explain to me how to solve
it?

Thanks,
Boaz

**Comment by iliapolo** [comment]
@boazsilverman 

> Hey, when trying to apply exactly the same logic, just in Python, here is
the result I got:
[image: image.png]

Looks like the image didn't upload. 

If you feel you are encountering a bug, please open a separate issue with the reproduction and the error message. 
In the meantime I can offer this: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_eks/README.html#launch-template-support

**Comment by alainms25** [comment]
Hi, I need to define userdata for nodegroups with cdk. It is possible to perform that action without having to work with a custom ami.
