### ISSUE TITLE
[core] Override default mounts for bundling containers

### ISSUE THREAD

**Issue by NicoVIII** [aws/aws-cdk#9885]
I need a way to overwrite the mounting paths of the bundling containers which handle stuff like `npm install` on lambdas before packing and uploading.
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#bundling-asset-code

It would be nice, if there would be an option to provide alternative paths for the mounted host paths.

### Use Case

We use VScode for developing in CDK and want to use Devcontainers. With that we can use a preconfigured docker image as dev environment and a new developer doesn't have to set up CLI and CDK etc. to start working.

It is possible to launch another docker image from inside the devcontainer.
https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker

This works, but the used mount paths are wrong. The CDK provides the paths from inside the devcontainer, but this docker-from-docker strategy requires host paths.

### Proposed Solution

Extend the BundlingOptions in core (bundling.ts) with a function property, which allows editing which paths are used as default mounts paths for the bundling containers in asset-staging.ts (atm line 168-179).

```
    // Always mount input and output dir
    const volumes = [
      {
        hostPath: this.sourcePath,
        containerPath: AssetStaging.BUNDLING_INPUT_DIR,
      },
      {
        hostPath: bundleDir,
        containerPath: AssetStaging.BUNDLING_OUTPUT_DIR,
      },
      ...options.volumes ?? [],
    ];
```

### Other

(I hope, I explained everything in enough detail, this is my first issue for such a big project as the AWS CDK)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Is there a way to inspect the current mount options when running inside a Docker container and doing this mapping back to host paths automatically?

**Comment by NicoVIII** [comment]
I'm not sure.
This article suggests to add an environment variable and fill it with the VScode own variable ${localWorkspaceFolder}.
https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker#using-bind-mounts-when-working-with-docker-inside-the-container

devcontainer.json
```
"remoteEnv": { "LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}" }
```

This is, what I would use, but I don't think that this is good enough for complete automation. I'm not that experienced in docker though, so maybe there is a more elegant way I don't know about.

**Comment by rix0rrr** [comment]
I'm not opposed to `LOCAL_WORKSPACE_FOLDER`. But we would need to know which container path corresponds to the host's `LOCAL_WORKSPACE_FOLDER`. Is that standardized?

On another note, why don't you mount the directories at the same name in both host and container? This is what I generally do and it removes the need for the mapping.

This is what I put in my `docker run`:

```
    -v $HOME:$HOME -w $PWD
```

Which makes it so I can use any directory under `~`, and I generally don't need other directories anyway.

**Comment by NicoVIII** [comment]
As far as I know the default mount for the devcontainer uses "/workspaces/<projectname>". This is changeable in the config.
But for this VScode has another variable `${containerWorkspaceFolder}`, which one could use to define an envvar.

We are (sadly) working on Windows and the container is a unix one. I'm not sure, if this works but I will try to adjust devcontainer configs to match this behaviour.
