### ISSUE TITLE
[codepipeline] Issues with default created roles for actions

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#9894]
### Reproduction Steps

I have set a role to a pipeline with multiple actions : 
```
    const Codepipeline = new codepipeline.Pipeline(this, 'Codepipeline', {
      role: IamRoleCodepipeline,
      stages: [
        {
          stageName: 'DEV',
          actions: [
            new codepipeline_actions.ManualApprovalAction({
              actionName: 'Deploy-Validation',
              notificationTopic: SnsTopicCodepipeline,
              runOrder: 1
            }),
```

In that case, CDK create additional roles for each actions (useless because permissions are in the "main" role defined at the beginning).
Ok, it's interesting to give the selected permissions for each actions, a best practice.

But in that case I have an error at this CodePipeline stage when executing it : 
`The provided role cannot be assumed: 'Access denied when attempting to assume the role 'arn:aws:iam::123456789:role/pipeline-ecs-CodepipelineDEVD-1P2J04U72KI7H''
`

And indeed, in Trusted entities of the "default role" created on our behalf, I have the Account ID where CodePipeline is deployed; and no access for Codepipeline Service !

So, to prevent that, I have to set the prop `role: IamRoleCodepipeline,` for each actions to get it works.

### What did you expect to happen?

If we set/create and attach a role to CodePipeline, no need te create "default" roles on our behalf.
That role must have the priority (it's the case when using/creating via CloudFormation).

Maybe add a prop (boolean) to create a default role on each actions needed if wanted ?

### What actually happened?

Actually, I have plenty of role created by default for each actions, useless in my case.
I just want to set 1 role for Codepipeline and set some other when, for example, I need to set a Role created on another account to STS on it.

### Environment

  - **CLI Version      :*CDK 1.60.0*
  - **Framework Version:*6.14.8*
  - **Node.js Version:*v12.15.0* 
  - **OS               :*Linux*
  - **Language (Version):*TypeScript * 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @Cloudrage ,

thanks for opening the issue. I think this is the same as #5941 - do you agree?

Thanks,
Adam

**Comment by Cloudrage** [comment]
I think so, explained differently ^^

**Comment by vandreykiv** [comment]
Any updates on this issue? In our case we have around 150 pipelines right now and they created like 1500 IAM roles (around 10 per pipeline) that is quite big amount. Maybe we have some workaround to reduce this number?

**Comment by skinny85** [comment]
@vandreykiv the simplest solution to reducing that number would be to create a Role yourself, and pass it when creating the different Actions (or, pass the Pipeline's Role itself).

I'm resolving this one in favor of #5941, please comment if you disagree!

**Comment by vandreykiv** [comment]
I tried to add pipeline role but it still not work. We still have roles for each action in the pipeline. As I understand it's not possible to set a role for the action itself at this moment?  


```
        new codepipeline.Pipeline(this, 'Pipeline', {
            pipelineName: this.config.servicename.pipelineName,
            role: deployerRole,
            artifactBucket: artifact_s3,
            stages: [
                {
                    stageName: 'Source',
                    actions: [
                        sourceAction
                    ]
                },
                {
                    stageName: 'DockerBuild',
                    actions: [
                        new codepipeline_actions.CodeBuildAction({
                            actionName: 'Build',
                            project: build,
                            input: sourceOutput,
                        })
                    ]
                },
                {
                    stageName: 'DevApproval',
                    actions: [
                        new codepipeline_actions.ManualApprovalAction({
                            actionName: 'ApproveDeploy',
                            notifyEmails: this.config.notificationEmails
                        })
                    ]
                },
                ...
            ]
        });
```

**Comment by vandreykiv** [comment]
Looks like I was able to archive this adding role to each action and pipeline itself.

role:
```
        const deployerRole = new iam.Role(this, 'deployerRole', {
            assumedBy: new iam.CompositePrincipal(
                new iam.ServicePrincipal('codebuild.amazonaws.com'),
                new iam.ServicePrincipal('codepipeline.amazonaws.com')
            )
        });
```
source action:
```
        const sourceAction = new codepipeline_actions.CodeCommitSourceAction({
            actionName: 'CodeCommit_Source',
            branch: this.config.servicename.branch || 'master',
            repository: repo,
            trigger: codepipeline_actions.CodeCommitTrigger.POLL,
            output: sourceOutput,
            role: deployerRole
        });
```
pipeline itself:
```
new codepipeline.Pipeline(this, 'Pipeline', {
            pipelineName: this.config.mapProxy.pipelineName,
            role: deployerRole,
            artifactBucket: artifact_s3,
            stages: [
                {
                    stageName: 'Source',
                    actions: [
                        sourceAction
                    ]
                },
                {
                    stageName: 'DockerBuild',
                    actions: [
                        new codepipeline_actions.CodeBuildAction({
                            actionName: 'Build',
                            project: build,
                            input: sourceOutput,
                            role: deployerRole
                        })
                    ]
                },
                {
                    stageName: 'DevApproval',
                    actions: [
                        new codepipeline_actions.ManualApprovalAction({
                            actionName: 'ApproveDeploy',
                            notifyEmails: this.config.notificationEmails,
                            role: deployerRole
                        })
                    ]
                },
                ...
                {
                    stageName: 'QAApproval',
                    actions: [
                        new codepipeline_actions.ManualApprovalAction({
                            actionName: 'ApproveDeploy',
                            notifyEmails: this.config.notificationEmails,
                            role: deployerRole
                        })
                    ]
                },
               ...
                {
                    stageName: 'ProdApproval',
                    actions: [
                        new codepipeline_actions.ManualApprovalAction({
                            actionName: 'ApproveDeploy',
                            notifyEmails: this.config.notificationEmails,
                            role: deployerRole
                        })
                    ]
                },
               ...
            ]
        });
```

**Comment by skinny85** [comment]
You absolutely can, example:

```ts
        new codepipeline.Pipeline(this, 'Pipeline', {
            pipelineName: this.config.servicename.pipelineName,
            role: deployerRole,
            artifactBucket: artifact_s3,
            stages: [
                 // omitted for clarity...
                {
                    stageName: 'DevApproval',
                    actions: [
                        new codepipeline_actions.ManualApprovalAction({
                            actionName: 'ApproveDeploy',
                            notifyEmails: this.config.notificationEmails,
                            role: myRole, // <--------- !!!!
                        })
                    ]
                },
                // ...
            ]
        });
```

**Comment by skinny85** [comment]
> Looks like I was able to archive this adding role to each action and pipeline itself.

You can also leave CDK to create the Pipeline Role, and then take it out and pass it to each Action. That will save you fiddling with the service principals (which are not correct right now BTW, you don't need the CodeBuild principal there).

**Comment by vandreykiv** [comment]
In our case, we use this role in different steps and some of them require codebuild permissions to assume this role. I think for us it may better work to have a predefined role with permissions we need and pass it to all actions rather than have a custom role plus a pipeline role. At least it will bring us to 1 role per pipeline rather than 2 roles per pipeline. 

Anyway thanks for your help.

**Comment by skinny85** [comment]
Just to clarify: if you're using that Role just as the Role for a CodeBuild Project Action, you do _not_ need to trust the CodeBuild principal in that Role.

Only the Project's Role needs to do that.
