### ISSUE TITLE
[elbv2] Java class HealthCheck defined in multiple places

### ISSUE THREAD

**Issue by cartwrightian** [aws/aws-cdk#9895]
Cut&Paste from intelij:
Reference to `HealthCheck` is ambiguous, both `software.amazon.awscdk.services.elasticloadbalancingv2.HealthCheck` and `software.amazon.awscdk.services.autoscaling.HealthCheck` match

Unfortunately several examples in the java docs import both these namespaces.

For example code on this page: https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/elasticloadbalancingv2/package-summary.html

It is left an exercise for the user to try and work out which one to use.

### Use Case

Needed so don't have to try and work out which one is meant to be used based on signature of consuming methods.

### Proposed Solution

Remove one, or change name as appropriate.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the report. 

Naming conflicts across modules is unfortunately just a way of life; other `HealthCheck` modules do exist (and likely others may be created in the future). The alternative is fully qualifying them in the class name, making our packages redundant (e.g., `AwsCdkServicesElasticLoadBalancingV2HealthCheck`).


That being said, we absolutely want our docs as helpful as possible. I've opened up #9933 to qualify the `AutoScalingGroup` import so the naming conflict doesn't appear in the documentation.
