### ISSUE TITLE
[aws-events] Allow grantPutEvents on IEventBus

### ISSUE THREAD

**Issue by alextriaca** [aws/aws-cdk#9896]
While the EventBus object allows you to call `grantPutEvents` on it the `IEventBus` object returned when importing an EventBus by its ARN does not have this option.  

Please can this option be added so that the imported EventBus can also grant access. Similar examples that have already been patched:
* https://github.com/aws/aws-cdk/issues/7473
* https://github.com/aws/aws-cdk/issues/8618
* https://github.com/aws/aws-cdk/pull/6635

### Reproduction Steps

```python
event_bus = EventBus.from_event_bus_arn(
    self, "name", event_bus_arn="bus_arn"
)
event_bus.grant_put_events(my_function)
```

### Environment

  - **CLI Version      : aws-cli/1.17.11**
  - **Framework Version: 1.60.0**
  - **Node.js Version: v12.14.1** 
  - **OS               : macOS**
  - **Language (Version): all** 

--- 

This is :bug: Bug Report

**Comment by michaelwiles** [comment]
When using event bridge it is not possible to filter the event bus by arn. The arn that you use can only be a wild card.

Thus it is not necessary to have the grantPutEvents on the event bus. It is a static method on EventBus.

`        EventBus.grant_put_events(task_role)`

The above code grants the task role permission to put events on Event bus. The identity of the event bus is not relevant as the event bus context does not support that level of granularity.

**Comment by alextriaca** [comment]
The best kind of fix is no fix at all :) Thanks @michaelwiles for the pointer. Have swapped over the logic and it works great.
