### ISSUE TITLE
[aws-lambda] CurrentVersion not available for imported Lambda@Edge function

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#9901]
### The Question
I'm only able to get `.currentVersion` on the new lambda function, but not on the imported one. 

![image](https://user-images.githubusercontent.com/31543/90936242-0da06f00-e3c2-11ea-966b-43a0ca5be258.png)

Is it possible to get `.currentVersion` property of the imported Lambda@Edge function?

### Environment

  - **CDK CLI Version:** 1.60.0
  - **Node.js Version:** v14.8.0
  - **OS:** OSX Mojave
  - **Language (Version):** TypeScript (3.8.3)

**Comment by nija-at** [comment]
The `currentVersion` API as described in [its documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#currentversion) is about creating a new version for the lambda function each time the function's configuration changes. 
Since the CDK cannot know when an imported function's configuration changes, this cannot be implemented for imported functions.

What is your use case?

**Comment by robertd** [comment]
@nija-at I'm trying to import an existing L@E function. As you know, Lambda@Edge functions can only be created in `us-east-1`; the default region we use is `us-west-2`. This function (it's current version) is used as a parameter for the CloudFront distribution construct.

```ts
const lambdaEdge = lambda.Function.fromFunctionArn(this, "test", "arn:aws:lambda:us-east-1:1234567890:function:test-cloudfront:1");

const distro = new cloudfront.Distribution(this, "cf-distro", {
  defaultBehavior: {
    origin: new origins.S3Origin(testBucket),
    viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
    edgeLambdas: [
       {
         functionVersion: lambdaEdge.currentVersion, // <== This doesn't exist on the imported lambda function
         eventType: cloudfront.LambdaEdgeEventType.VIEWER_REQUEST
       },
    ]
  },
  certificate: acmCertificate,
  defaultRootObject: "index.html",
  priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
});
```

**Comment by jogold** [comment]
@robertd like I proposed in #9892 with **`fromVersionArn()`**:

```ts
const functionVersion = lambda.Version.fromVersionArn(this, 'Version', 'arn:aws:lambda:us-east-1:1234567890:function:test-cloudfront:1');

const distro = new cloudfront.Distribution(this, "cf-distro", {
  defaultBehavior: {
    origin: new origins.S3Origin(testBucket),
    viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
    edgeLambdas: [
       {
         functionVersion, // <== the imported version is used here
         eventType: cloudfront.LambdaEdgeEventType.VIEWER_REQUEST
       },
    ]
  },
  certificate: acmCertificate,
  defaultRootObject: "index.html",
  priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
});
```

**Comment by robertd** [comment]
@jogold Ah... I totally missed the `lambda.Version.fromVersionArn` and read it as `lambda.Layer.fromLayerArn`. Thank you so much.

I will update readme.md in both `aws-lambda` and `aws-cloudfront` to cover these use cases. Thanks again!
