### ISSUE TITLE
[docs] App construct does not show "construction properties", first section is "member properties" and is easy to misinterpret

### ISSUE THREAD

**Issue by mikestopcontinues** [aws/aws-cdk#9909]
I'm trying to set my account and region at the App level so that all my stacks inherit from it as in the [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.App.html). However, when I log the instantiated App, account and region are undefined. In the [source](https://github.com/aws/aws-cdk/blob/v1.60.0/packages/@aws-cdk/core/lib/app.ts#L77), it seems that the props are unsupported.

At minimum, the docs are out of date. However... 

I'm pulling account and region from the CDK env vars (CDK_DEFAULT_ACCOUNT, CDK_DEFAULT_REGION). So even if App no longer supports setting them, my stacks should be picking them up anyway. Yet I get the following error:

`Error: Cannot retrieve value from context provider hosted-zone since account/region are not specified at the stack level. Either configure "env" with explicit account and region when you define your stack, or use the environment variables "CDK_DEFAULT_ACCOUNT" and "CDK_DEFAULT_REGION" to inherit environment information from the CLI (not recommended for production stacks)`

I'm going back to configuring on the Stack-level, but I figured this still warrants looking into.

### Reproduction Steps

```js
import {App, Stack} from '@aws-cdk/core';

const account = process.env.CDK_DEFAULT_ACCOUNT;
const region = process.env.CDK_DEFAULT_REGION;

const app = new App({account, region});
const stack = new Stack(app, 'Stack', {});

console.log({account, region}); // { account: '215531866295', region: 'us-east-1' }
```

### Environment

  - **CLI Version      :** 1.60.0
  - **Framework Version:** 1.60.0
  - **Node.js Version:** 14.8.0
  - **OS               :** OSX
  - **Language (Version):** JS

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
The docs you have attached shows inherited members, they are the one marked with a blue diamond. I agree it's not clear enough, especially when using Javascript. Im going to mark this as a doc issue so we can see how we can make it better.

To have multiple stacks created with the same environment extend [`Stage`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stage.html), which represents a lifecycle "Stage" of your application ("prod", "dev"). The CDK Pipeline [docs](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/pipelines#at-a-glance) explains the concept in details.

**Comment by mikestopcontinues** [comment]
@NetaNir Thanks. On the topic of Stages, I'd like to be able to rapidly deploy my stacks individually during development, but deploy them all within a Stage during CI/CD. I tried a number of different methods with no success. How can I make this happen?

**Comment by Jerry-AWS** [comment]
I think we need some content in the Developer Guide around Stages. It currently doesn't have any.

**Comment by rix0rrr** [comment]
Neta was right and I'm wrong. I fell into the same trap as the original poster, mistaking the set of "member properties" for a set of "construction properties".

Normally a construct renders the construction properties as the first table but not for `App` since it's the only construct that doesn't follow the standard construct signature of `(scope, id, props)`.

This is a docs problem: `App` should show the table of construction properties, and the fact that both sets of properties are called "properties" doesn't help AT ALL
