### ISSUE TITLE
[cli] New bootstrap produces roles without appropriate policies

### ISSUE THREAD

**Issue by mikestopcontinues** [aws/aws-cdk#9912]
After running the new-style `cdk bootstrap`, I can't deploy anything. I get variations on the following error:

`❌  [StackName] failed: AccessDenied: User: arn:aws:sts::[ACCOUNT]:assumed-role/cdk-[HASH]-deploy-role-[ACCOUNT]-[REGION]/aws-cdk-msc is not authorized to perform: cloudformation:UpdateTerminationProtection on resource: arn:aws:cloudformation:[REGION]:[ACCOUNT]:stack/[StackName]/[GUID]`

After scouting around, I tried deleting the `CDKToolkit` stack and bootstrapping with `--cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess`, but the errors during deploy were the same. 

Since `--cloudformation-execution-policies` is undocumented, I also tried with `--role-arn`, but I couldn't successfully bootstrap, getting the following error:

`❌  Environment aws://[ACCOUNT]/[REGION] failed bootstrapping: AccessDenied: Cross-account pass role is not allowed`

What's going on here?

### Environment

  - **CLI Version      :** 1.60.0
  - **Framework Version:** 1.60.0
  - **Node.js Version:** 14.8.0
  - **OS               :** OSX
  - **Language (Version):** JS

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@mikestopcontinues we should certainly better document `--cloudformation-execution-policies` - can you verify that the bootstrap stack contains that role with the Administrator permissions updated? Note that you don't need to delete the CdkToolkit stack and can just run bootstrap again with `--cloudformation-execution-policies` to update the stack.

Did you run the new bootstrap? i.e. was the context key `@aws-cdk/core:newStyleStackSynthesis` set?
Alternatively, If that key was not set you can provide it through the `--context` flag

```
cdk bootstrap --context @aws-cdk/core:newStyleStackSynthesis=1 --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://123456789012/<region i.e. us-east-1>
```

A minimal repro of the issue would help dig into this. I'm curious about the errors you see after bootstrapping.

**Comment by mikestopcontinues** [comment]
Turns out, I can't replicate the issue. The first time, bootstrapped new-style both as a change to the old CDKToolkit stack, as well as from scratch. I received the confirmation of new-stack status. However, after new-style bootstrapping again, the stack did have the admin role, and I was able to deploy a new stack from scratch.

Thanks for your help. :)
