### ISSUE TITLE
Allow passing of tokens as a qualifier for a DefaultStackSynthesizer (with possible solution)

### ISSUE THREAD

**Issue by maclema** [aws/aws-cdk#9916]
Without a long-winded description to why, CDK pipelines should allow passing a token, i.e. cdk.Fn.ref("Qualifier"), to the DefaultStackSynthesizer.

This currently cannot be accomplished because roleFromPlaceholderArn in deploy-cdk-stack-action.ts assigns the incoming ARN as the construct id, which may contain a token from users passing one to the qualifier prop.

When changed to the following, one can then pass ref's as the qualifier:
const id = arn.replace(/\$/g, '_')

Source Line: https://github.com/aws/aws-cdk/blob/25a9cc7fabbe3b70add48edfd01421f74429b97f/packages/%40aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts#L274

Workaround for anyone interested:
Add a "postinstall" script in package.json with "node patch-pipelines.js" where patch-pipelines.js is:

```
const fs = require("fs")
const file = "node_modules/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.js"
var src = fs.readFileSync(file) + ""
src = src.split("const id = arn").join("const id = arn.replace(/\\$/g, '_')")
fs.writeFileSync(file, src)
console.log("Patched CDK Pipelines")
```

**Comment by rix0rrr** [comment]
Honestly this is not something we're every likely to do, as it does not align with how we expect CDK to be used.

> Without a long-winded description to why

I can't assess the need and we're unlikely to invest effort into changes we don't see the point of.
