### ISSUE TITLE
[aws-eks]  use ec2.IVpc for the Pinger

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#9924]
The Pinger is using `ec2.Vpc` as the type of `prop.vpc`. I guess `ec2.IVpc` would be enough. In this case we can use the `Pinger` construct with any existing Vpc. And this helps for PR development.

https://github.com/aws/aws-cdk/blob/25a9cc7fabbe3b70add48edfd01421f74429b97f/packages/%40aws-cdk/aws-eks/test/pinger/pinger.ts#L9

### Use Case

Use the `Pinger` with any existing Vpc.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
Hi @iliapolo  

What do you think?

Shall we create a seperate little PR for this or just add this support in https://github.com/aws/aws-cdk/pull/9881 ?

**Comment by iliapolo** [comment]
@pahud It can be part of #9881 no problem 👍
