### ISSUE TITLE
[aws-appsync] Adding AuthorizationConfig within construction HttpDataSource of the appsync module.

### ISSUE THREAD

**Issue by haruharuharuby** [aws/aws-cdk#9934]
Adding AuthorizationConfig within construction HttpDataSource of the appsync module.

### Use Case

Integrating AWS StepFunctions to the appsync as HTTP Datasource.
Current(24, August 2021) AWS CDK can not configure the authorizationConfig during creating data source.
Currently, That can do only from the AWS-CLI. (create-data-source command) 
https://docs.aws.amazon.com/cli/latest/reference/appsync/create-data-source.html

Related AWS Blogs.
https://aws.amazon.com/blogs/mobile/invoke-aws-services-directly-from-aws-appsync/

### Proposed Solution

I'd like to call the addHttpDataSource method with authorizationConfig object.

```javascript
    api.addHttpDataSource('ds', endpoint, {
      name: 'custom',
      description: 'custom description',
      authorizationConfig: {
        authorizationType: 'AWS_IAM',
        awsIamConfig: {
          signingRegion: 'us-east-1',
          signingServiceName: 'states'
        }
      }
    });
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
@haruharuharuby Feel free to take a stab at this! Please tag it with `in-progress` once you start working on it and dont be afraid to reach out here if you need help 🙂

**Comment by haruharuharuby** [comment]
@BryanPan342 I started implementation for this issue. How can I tag the in-progress?

**Comment by BryanPan342** [comment]
@haruharuharuby wooo no worries i added the label!

**Comment by haruharuharuby** [comment]
@BryanPan342 I added PR for this issue.  I need to fix some CI checks. 
I will fix it later.

https://github.com/aws/aws-cdk/pull/9971

**Comment by haruharuharuby** [comment]
@BryanPan342 is it necessary to add unit test httpConfig that is in CfnTemplate.
It looks like no CfnTest in the UnitTest. I only found the HttpConfig test in integration test.

**Comment by BryanPan342** [comment]
@haruharuharuby for the unit tests, go to https://github.com/aws/aws-cdk/blob/3c116f3b5854726bef610e425fc35f2d2b50a179/packages/%40aws-cdk/aws-appsync/test/appsync-http.test.ts#L1-L20 for some examples!

**Comment by BryanPan342** [comment]
nvm it looks like you did it already
