### ISSUE TITLE
CDK accepts Role.fromRoleArn for an ARN that does not exist.  

### ISSUE THREAD

**Issue by marcioemiranda** [aws/aws-cdk#9941]
I would expect that 
```ts
const role = Role.fromRoleArn(scope, id, unexistent_role_arn, {
            mutable: false,
        });
```
passing an ARN that does not exist would trigger an exception or return a null value but it doesn't.
 
I have a situation where a new Role was always being created in the stack. However, if the Role already existed, deploy would throw an error at CF execution time (not in synth). So, I need a way to create a role only if the ARN does not exist.

Sample code of the Role being created:
```ts
new Role(scope, id, {
                 assumedBy: new AccountPrincipal(account),
                 externalId: my_ext_id,
                 maxSessionDuration: Duration.minutes(duration_min),
                 roleName: roleName,
                 managedPolicies: [ManagedPolicy.fromAwsManagedPolicyName("AdministratorAccess")]
             }); 
```
To reproduce the error:
- Deploy the stack to region A. It runs fine and the role is created.
- Deploy the stack to region B. Stack fails because Role already exists.

So I've tried to execute `Role.fromRoleArn(scope, id, role_arn, props)` first, expecting for it to throw an error if the ARN did not exist, but it just returns a Role object similar to the object that would be returned if the ARN actually existed.

**Comment by mdipirro** [comment]
I noticed the same behavior today. Is this the way it is meant to be?

**Comment by micah-jaffe** [comment]
+1, I am having the same issue.

**Comment by peterwoodworth** [comment]
Apologies for the late response time @marcioemiranda!

There is no way to create a `new role(...{roleName: roleName})` only if the role does not exist. Physical resources cannot have the same [Physical names](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_physical_names) in the same account and region, so `new role(...{roleName: roleName})` will always fail if there is already a resource that exists with the same name. The best solution here is to not specify the physical name `roleName` and let the CDK automatically create a name that is guaranteed to not exist!

One of the benefits to using the CDK is that it automatically handles lots of annoying roles and permissions stuff, so using `fromRoleArn()` is recommended against for most use cases. If you want to use this method to reference an existing role, you'll need to have already created the role.

There is no way here to have both, you'll have to use one or the other. Again, I recommend letting the CDK create its own physical names here, and in general. It can save headaches like this!

**Comment by peterwoodworth** [comment]
Closing this, ping me if there are any questions and I can reopen if necessary
