### ISSUE TITLE
[aws-s3] AccelerateConfiguration property not available on Bucket

### ISSUE THREAD

**Issue by rraraujo** [aws/aws-cdk#9947]
The S3 option "" is not available in the Bucket interface.
This does not allow us to create a Bucket with this configuration.

### Reproduction Steps

This is the interface where this property should be available:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L953

It should have the option available here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-accesscontrol

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@rraraujo Thanks for reporting this. Marking as a feature request. In the meantime, you can use [Escape Hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to configure the underlying CFN resource as you like.

Thanks

**Comment by dveldhoen** [comment]
Please look into this again. It will be really helpful. Thanks!
