### ISSUE TITLE
SubnetConfiguration should allow disabling MapPublicIpOnLaunch for public subnets.

### ISSUE THREAD

**Issue by maclema** [aws/aws-cdk#9948]
The following line should check an optional property on SubnetConfiguration to allow disabling MapPublicIpOnLaunch for public subnets.

https://github.com/aws/aws-cdk/blob/b1d0ac0564a86ab325e06b18670657ee9c953e3e/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1346

**Comment by NetaNir** [comment]
Hi!

We are tracking `Vpc` improvement in: https://github.com/aws/aws-cdk/issues/5927

duplicate https://github.com/aws/aws-cdk/issues/5927
