### ISSUE TITLE
Pipeline should allow enabling S3 access logging on the artifacts bucket.

### ISSUE THREAD

**Issue by maclema** [aws/aws-cdk#9950]
The Pipeline construct should provide an optional property allowing one to specify S3 access logging settings for the artifacts bucket.

https://github.com/aws/aws-cdk/blob/d6278b37ce787c587e1079a3f2844566291d7c27/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts#L234

**Comment by NetaNir** [comment]
You can supply a bucket and customize it to fit your use case. By accepting a `Bucket` on the L2 properties interface we allow users to customize their bucket, and they are not blocked by a specific implementation.
Feel free to reopen the issue if I missed your use case.
