### ISSUE TITLE
CdkPipeline should allow passing artifactsBucket for the underlying Pipeline

### ISSUE THREAD

**Issue by maclema** [aws/aws-cdk#9951]
In follow up to https://github.com/aws/aws-cdk/issues/9950. - I do see that codepipeline.Pipeline let's you specify a bucket. This should also be added to  pipelines.CdkPipeline.

**Comment by tomas-mazak** [comment]
@maclema hi, I've raised an issue #9794 for this and also raised a PR to resolve it: #9962 , you might want to upvote that one instead :)

**Comment by NGL321** [comment]
@tomas-mazak good catch!

Closing as duplicate.

😸 😷
