### ISSUE TITLE
[aws-events-targets] Support CloudWatch Logs as a target

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#9953]
Although it's not well-documented yet, CloudWatch Logs is a [supported target](https://docs.aws.amazon.com/eventbridge/latest/userguide/eventbridge-tutorial-cloudwatch-logs.html) for event rules. The ARN is the log group ARN.

### Use Case

This is useful for, among other things, recording ECS task state changes that are otherwise difficult to observe.

### Proposed Solution

Here's an example. Note, the log group name must start with `/aws/events/` because EventBridge relies on an unpublished CloudWatch Logs resource policy in order to work properly.

Caller: 

```ts
    const logGroup = new logs.LogGroup(this, 'EcsEventLog', {
      // must start with /aws/events/
      logGroupName: `/aws/events/ecs-${cluster.clusterName}` 
    });

    new cdk.CfnOutput(this, 'LogGroupName', {
      value: logGroup.logGroupName
    });

    const clusterEvents = new events.Rule(this, 'EcsEvents', {
      eventPattern: {
        source: ['aws.ecs'],
        detail: {
          clusterArn: [cluster.clusterArn]
        }
      },
      targets: [new CloudWatchLogsTarget(this, 'LogsTarget', logGroup)]
    });
```

Implementation:

```ts
export class CloudWatchLogsTarget extends cdk.Construct {
    private logGroup: logs.ILogGroup;

    constructor(scope: cdk.Construct, id: string, logGroup: logs.ILogGroup) {
        super(scope, id);
        this.logGroup = logGroup;
    }

    public bind(rule: events.IRule, id?: string): events.RuleTargetConfig {
        return {
            id: '',
            // we can't use logGroup.logArn because it has `:*` on the end, and it's a token
            // so we can't just remove the suffix with string replacement operations
            arn: `arn:aws:logs:${this.logGroup.stack.region}:${this.logGroup.stack.account}:log-group:${this.logGroup.logGroupName}`,
        }
    }
}
```

Ideally, we'd go one step further and implement event handler declarations on ECS Cluster objects, but that's a story for another day.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by demus** [comment]
Thanks for making this issue! I was looking to do this today as well.

Here's a slight modification of the code sample in this issue that I have working by implementing IRuleTarget:

```
// Source: https://github.com/aws/aws-cdk/issues/9953
import * as events from "@aws-cdk/aws-events";
import * as logs from "@aws-cdk/aws-logs";

export class CloudWatchLogsTarget implements events.IRuleTarget {
  private logGroup: logs.ILogGroup;

  constructor(logGroup: logs.ILogGroup) {
    this.logGroup = logGroup;
  }

  public bind(_rule: events.IRule, _id?: string): events.RuleTargetConfig {
    return {
      id: "",
      // we can't use logGroup.logArn because it has `:*` on the end, and it's a token
      // so we can't just remove the suffix with string replacement operations
      arn: `arn:aws:logs:${this.logGroup.stack.region}:${this.logGroup.stack.account}:log-group:${this.logGroup.logGroupName}`,
    };
  }
}
```

**Comment by otterley** [comment]
Looks good @demus. One runtime check I might add is to verify that the log group name starts with `/aws/events/` and raise a runtime error if not.

**Comment by jfenderico** [comment]
@demus have you been able to make it work with custom events, sent from a lambda for example, or does it only work with aws events?

**Comment by otterley** [comment]
@jfenderico I have not tried! But if you do, please let us know. :)

**Comment by demus** [comment]
> @demus have you been able to make it work with custom events, sent from a lambda for example, or does it only work with aws events?



> @jfenderico I have not tried! But if you do, please let us know. :)

Same here, I have not tried either

**Comment by jfenderico** [comment]
I could send events from a lambda and it worked well. I had to add some permissions to the target. I found this workaround in another post:

```ts
  // Source: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/351#issuecomment-664493982
  public bind(rule: IRule, id: string): RuleTargetConfig {
      // Ugly hack to grant a permission for allowing EventBridge to store logs in CloudWatch
      const policyName = `${rule.ruleName}-CloudWatchPolicy`
      new AwsCustomResource(this.stack, "CloudwatchLogResourcePolicy", {
          resourceType: "Custom::CloudwatchLogResourcePolicy",
          onUpdate: {
              service: "CloudWatchLogs",
              action: "putResourcePolicy",
              parameters: {
                  policyName,
                  policyDocument: JSON.stringify({
                      Version: "2012-10-17",
                      Statement: [
                          {
                              Sid: policyName,
                              Effect: "Allow",
                              Principal: {
                                  Service: ["events.amazonaws.com"]
                              },
                              Action: ["logs:CreateLogStream", "logs:PutLogEvents"],
                              Resource: this.logGroup.logGroupArn
                          }
                      ]
                  })
              },
              physicalResourceId: PhysicalResourceId.of(policyName),
          },
          onDelete: {
              service: "CloudWatchLogs",
              action: "deleteResourcePolicy",
              parameters: {
                  policyName
              }
          },
          policy: AwsCustomResourcePolicy.fromStatements([
              new PolicyStatement({
                  actions: ["logs:PutResourcePolicy", "logs:DeleteResourcePolicy"],
                  resources: ["*"]
              })
          ])
      });

      return {
          id: '',
          arn: this.logGroup.logGroupArn,
          targetResource: this.logGroup
      }
  }
```

**Comment by otterley** [comment]
@jfenderico The resource policy should not be needed as long as the target Log Group prefix is `/aws/events/`. This policy already exists by default in AWS accounts.

**Comment by leantorres73** [comment]
This is related to this issue in cloudformation coverage roadmap:

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/351

**Comment by aripalo** [comment]
I guess this is due to that CloudFormation issue, but just today found this out since I had created CloudWatch Log Group as EventBridge Rule target manually in the console, but could not replicate it with CDK.

Just my two cents, it'd be a really useful feature to have!

**Comment by BenChaimberg** [comment]
> @jfenderico The resource policy should not be needed as long as the target Log Group prefix is `/aws/events/`. This policy already exists by default in AWS accounts.

I don't believe that this is correct. When creating an event rule with a log group target in the console, this resource policy is created automatically. However, the policy does not exist for brand-new accounts and would not be created if the only event rules with log group targets are created via CDK (or the API, for that matter). See: https://docs.aws.amazon.com/eventbridge/latest/userguide/resource-based-policies-eventbridge.html#cloudwatchlogs-permissions

(cc: @DaWyz since you are working on this feature)

**Comment by DaWyz** [comment]
> > @jfenderico The resource policy should not be needed as long as the target Log Group prefix is `/aws/events/`. This policy already exists by default in AWS accounts.
> 
> I don't believe that this is correct. When creating an event rule with a log group target in the console, this resource policy is created automatically. However, the policy does not exist for brand-new accounts and would not be created if the only event rules with log group targets are created via CDK (or the API, for that matter). See: https://docs.aws.amazon.com/eventbridge/latest/userguide/resource-based-policies-eventbridge.html#cloudwatchlogs-permissions
> 
> (cc: @DaWyz since you are working on this feature)

I didn't know that. Thanks for the update @BenChaimberg , I will try and update the PR accordingly !
