### ISSUE TITLE
[Documentation] API references in backticks in methods docs aren't translated

### ISSUE THREAD

**Issue by abaki007** [aws/aws-cdk#9964]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/Role.html
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/Group.html
https://pypi.org/project/aws-cdk.aws-iam/1.59.0/

The python documentation (links above) refer to the use of addManagedPolicy & fromAwsManagedPolicyName methods in the following syntax:
`iam_group_object.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName(policyName))`
`iam_role_object.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName(policyName))`

This is incorrect as the following methods should be referenced as:
- `addManagedPolicy` = `add_managed_policy`
- `fromAwsManagedPolicyName` = `from_aws_managed_policy_name`

Therefore:
`iam_role_object.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName(policyName))`
should be:
`iam_role_object.add_managed_policy(iam.ManagedPolicy.from_aws_managed_policy_name(policyName))`

Please can you update documentation to reflect the correct method names *OR* document how to translate method names between languages:
so if Typescript method is written in lower camel case `addManagedPolicy`
python will use snake case so please convert method name to `add_method_policy`

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
>  _OR_ document how to translate method names between languages:

https://docs.aws.amazon.com/cdk/latest/guide/multiple_languages.html
