### ISSUE TITLE
Error with latest Parcel prerelease

### ISSUE THREAD

**Issue by sh4m1l65** [aws/aws-cdk#9974]
https://github.com/aws/aws-cdk/blob/276c322780a9a8c9c6e569509a90ba0a7bec0879/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundlers.ts#L131

`--no-autoinstall` seems to be not a valid option in latest Parcel prerelease:
```
 ~/Projects/golang-redirector-infra/ [master*] npx cdk synthesize   
Bundling asset GolangRedirectorInfraStack/cloudfront-distribution/cloudfront-dist/edge-function/Code/Stage...
error: unknown option `--no-autoinstall'
Failed to bundle asset GolangRedirectorInfraStack/cloudfront-distribution/cloudfront-dist/edge-function/Code/Stage: Error: bash exited with status 1
Subprocess exited with error 1
```

(it fails the same way in CodeBuild as part of a CDK pipeline)

package.json:
```
{
...
  "devDependencies": {
    "parcel": "^2.0.0-nightly.380",
     ...
  }
}
```

**Comment by sh4m1l65** [comment]
This may be a bug in Parcel, IDK. Latest prerelease Parcel docs still show the option in the "general options" CLI section.

**Comment by jogold** [comment]
@sh4m1l65 this looks like a bug the nightly release of Parcel. It is recommended for now to to pin to `2.0.0-beta.1`

```json
{
...
  "devDependencies": {
    "parcel": "2.0.0-beta.1",
     ...
  }
}
```

**Comment by sh4m1l65** [comment]
That worked, tyvm.
