### ISSUE TITLE
aws_ec2.InterfaceVpcEndpointAwsService.APIGATEWAY

### ISSUE THREAD

**Issue by michael-perfects** [aws/aws-cdk#9981]
### What did you expect to happen?
cn.com.amazonaws.cn-northwest-1.execute-api This should of returned cn.com.amazonaws.cn-northwest-1.execute-api in china region

### What actually happened?
com.amazonaws.cn-northwest-1.execute-api returned this in China AWS region

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Duplicate of https://github.com/aws/aws-cdk/issues/9864
