### ISSUE TITLE
[events] Property 'addTarget' does not exist on type 'IRule'.

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#9983]
## :question: General Issue

When trying to import an **events.Rule** I can't use "addTarget" Method : 
```
// Lambda
    var LambdaArn = cdk.Fn.importValue('LambdaArn');
    const Lambda = lambda.Function.fromFunctionArn(this, 'Lambda', LambdaArn);

// Events Rule
    var LambdaRuleArn = cdk.Fn.importValue('LambdaRuleArn');
    const LambdaRule = events.Rule.fromEventRuleArn(this, 'LambdaRule', LambdaRuleArn); 

// Add Target
    LambdaRule.addTarget(new eventsTargets.LambdaFunction(Lambda));
```

For **addTarget** > `Property 'addTarget' does not exist on type 'IRule'.`
No pb when creating the events.Rule directly in the Stack.

### The Question

What's wrong ?

### Environment

  - **CDK CLI Version:** 1.60.0 
  - **Module Version:** 6.14.8 
  - **Node.js Version:** v12.15.0 
  - **OS:** Linux 
  - **Language (Version):** TypeScript

**Comment by leantorres73** [comment]
I'm facing this same issue, and it would be great to follow some event design patters and be able to define the targets in other projects, not just in the place where the rule is created. You can create a rule and don't know how many services want to subscribe to it, and then attach and dettach targets dynamically from other places

**Comment by rix0rrr** [comment]
As far as I know it is not possible to add Targets to a Rule that already exists. At least not using CloudFormation.

If I am mistaken, please open a new issue to point me to the documentation where it say otherwise.

It may be possible to be done using a Custom Resource. I would encourage you to vend a 3rd party construct library that has this capability. If it's not natively supported, we're unlikely to be taking this into CDK core.

**Comment by Cloudrage** [comment]
@rix0rrr , it's possible to do it directly in the same stack, but not when imported from another one; for example, this case is wotking :
```
    const LambdaRule = new events.Rule(this, 'LambdaRule', {
      ruleName: 'Lambda',
      schedule: events.Schedule.cron({minute: '*/10', hour: '*', month: '*', weekDay: '*'}),
      enabled: true
        });
    LambdaRule.addTarget(new eventsTargets.LambdaFunction(Lambda, {event: events.RuleTargetInput.fromObject({
        'Key': Value
    })
    }));
```

But not the imported use case identified in the initial Comment of this issue.
