### ISSUE TITLE
cdk cli always exits with code 1 when doing a diff

### ISSUE THREAD

**Issue by PacoVK** [aws/aws-cdk#9985]
CDK cli always exits with code 1 even if the result is the expected (getting a list of possible changes). 
This behaviour makes it hard to integrate with CI tools like GitLabCi. 
Exit code 1 should be expected if eg. AWS permission error for the command execution occured but not if there are outstanding changes.

### Reproduction Steps

do a ```cdk diff``` in any project using aws-cdk

### What did you expect to happen?

Get a list of possible changes and exit code 0 if no error during the command occured

### What actually happened?

```cdk diff``` always exits with code 1, which makes it hard to use in tools like gitlabci pipelines

### Environment

  - **CLI Version      :** 1.60.0 (build 8e3f53a)
  - **Node.js Version:** v14.7.0
  - **OS               :** MacOS Catalina 10.15.6
  - **Language (Version):** all
--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@PacoVK can you run your command with `-v` flag. Is the context `"aws-cdk:enableDiffNoFail": "true",` set in `cdk.json`, `~/.cdk.json` or passed via the `-c` context flag?

**Comment by PacoVK** [comment]
@shivlaks yes it even exits with code 1 when `"aws-cdk:enableDiffNoFail": "true"` is set either in `cdk.json` or passed via `-c` 

see below the output of the cmd with ```-v``` flag:
`CDK toolkit version: 1.60.0 (build 8e3f53a)
Command line arguments: {
_: [ 'diff' ],
profile: 'XXXXXXX',
v: 1,
verbose: 1,
'ignore-errors': false,
ignoreErrors: false,
json: false,
j: false,
ec2creds: undefined,
i: undefined,
'version-reporting': undefined,
versionReporting: undefined,
'path-metadata': true,
pathMetadata: true,
'asset-metadata': true,
assetMetadata: true,
'role-arn': undefined,
r: undefined,
roleArn: undefined,
staging: true,
'no-color': false,
noColor: false,
fail: false,
'context-lines': 3,
contextLines: 3,
strict: false,
'$0': 'node_modules/.bin/cdk'
}
cdk.json: {
"app": "npx ts-node -O '{\"module\":\"commonjs\"}' ./infrastructure/index.ts",
"requireApproval": "never",
"aws-cdk:enableDiffNoFail": "true",
"context": {
"projectName": "SampleProject",
"hostedZoneName": "masked.for.example.me",
"subdomain": "test"
}
}
cdk.context.json: {
"hosted-zone:account=111111111111:domainName=test.masked.for.example.me:region=eu-central-2": {
"Id": "/hostedzone/XXXXXXXXXXXX",
"Name": "test.masked.for.example.me."
},
"hosted-zone:account=111111111111:domainName=test.masked.for.example.me:region=eu-central-2": {
"Id": "/hostedzone/XXXXXXXXXXXX",
"Name": "test.masked.for.example.me."
}
}
merged settings: {
versionReporting: true,
pathMetadata: true,
output: 'cdk.out',
app: `npx ts-node -O '{"module":"commonjs"}' ./infrastructure/index.ts`,
requireApproval: 'never',
'aws-cdk:enableDiffNoFail': 'true',
context: {
projectName: 'SampleProject',
hostedZoneName: 'masked.for.example.me',
subdomain: 'test'
},
tags: [],
assetMetadata: true,
profile: 'XXXXXXXX',
toolkitBucket: {},
staging: true
}
Determining whether we're on an EC2 instance.
Does not look like EC2 instance.
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to eu-central-2
Resolving default credentials
Looking up default account ID from STS
Default account ID: 111111111111
Setting "CDK_DEFAULT_ACCOUNT" environment variable to 111111111111
context: {
'hosted-zone:account=111111111111:domainName=test.masked.for.example.me:region=eu-central-2': {
Id: '/hostedzone/XXXXXXXXXXXX',
Name: 'test.masked.for.example.me.'
},
'hosted-zone:account=111111111111:domainName=test.masked.for.example.me:region=eu-central-2': {
Id: '/hostedzone/XXXXXXXXXXXX',
Name: 'test.masked.for.example.me.'
},
projectName: 'SampleProject',
hostedZoneName: 'masked.for.example.me',
subdomain: 'test',
'aws:cdk:enable-path-metadata': true,
'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
CDK_DEFAULT_REGION: 'eu-central-2',
CDK_DEFAULT_ACCOUNT: '111111111111',
CDK_CONTEXT_JSON: '{"hosted-zone:account=111111111111:domainName=test.masked.for.example.me:region=eu-central-2":{"Id":"/hostedzone/XXXXXXXXXXXXX","Name":"masked.for.example.me."},"hosted-zone:account=111111111111:domainName=test.masked.for.example.me:region=eu-central-2":{"Id":"/hostedzone/XXXXXXXXXXXXX","Name":"masked.for.example.me."},"projectName":"SampleProject","hostedZoneName":"masked.for.example.me","subdomain":"test","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
CDK_OUTDIR: 'cdk.out',
CDK_CLI_ASM_VERSION: '5.0.0',
CDK_CLI_VERSION: '1.60.0'
}
`

**Comment by shivlaks** [comment]
@PacoVK - I'll need to repro this behaviour but it should exit with `0` if the `aws-cdk:enableDiffNoFail` key is set. Does this fail with any CDK app?

**Comment by jonny-rimek** [comment]
@PacoVK did you set it inside the context object like this:

`
"context": {
	"aws-cdk:enableDiffNoFail": "true"
  }
´

This did the trick for me. the --fail false flag gets ignored and the supposed default

**Comment by PacoVK** [comment]
@shivlaks @jonny-rimek i set the property inside the context, passed it via CLI and added it to the cdk.json however still exits with 1. I tried it on other projects eg. the official examples and indeed it behaved as expected and exits with code 0.

**Comment by blimmer** [comment]
I also tried the context and `--fail false` and it always exits with code 1 for me.
