### ISSUE TITLE
[cognito] Import existing user pool domain

### ISSUE THREAD

**Issue by jarikujansuu** [aws/aws-cdk#9988]
There doesn't seem to be way to import existing Cognito user pool domain, so when `AuthenticateCognitoActionProps` needs `IUserPoolDomain` it must have been created in CDK (and in that CDK app)

`IUserPool` and  `IUserPoolClient` can be imported. 

Code seems to just copy arns, ids and name from resources so requiring instances of IResource is unnecessary.

### Use Case

Need to add listener authentication action for Cognito not created in this CDK project.

### Proposed Solution

Change `AuthenticateCognitoActionProps`so that user pool, client and domain are interfaces that can be passed manually (not extending IResource). 

**Or** Add static method `UserPoolDomain.fromDomainName(domainName: string): IUserPoolDomain` so importing user pool domain would be possible.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
It seems like adding the import for `IUserPoolDomain` makes the most sense here.
