### ISSUE TITLE
[s3-deployment] BucketDeployment not reading role from Role.fromRoleArn

### ISSUE THREAD

**Issue by mukeshchauhan** [aws/aws-cdk#9989]
### Issue
Instantiating `BucketDeployment` with provided `Role.fromRoleArn` have no affect, approval for updating the policy is presented with the same permissions that are in the existing role. Due to corporate IAM limitations, we cannot approve the IAM changes on fly and have to use existing roles.

### Environment

  - **CDK CLI Version:** 1.60.0 
  - **Module Version:** 1.60.0
  - **Node.js Version:** v12.18.2 
  - **OS:** osx 10.15.6
  - **Language:** Typescript 

### Code Snippet
```ts
        let destinationBucket = Bucket.fromBucketName(this, 'myexistingbucket', 'test-dev-us-east-1');
        let irole = Role.fromRoleArn(this, 'exising_role', 'arn:aws:iam::12345:role/MyRole');
        let dep = new BucketDeployment(this, 'MyFiles', {
            sources: [Source.asset(path.join(__dirname, '../../dist/test'))],
            destinationBucket: destinationBucket,
            role: irole,
            serverSideEncryption: ServerSideEncryption.AWS_KMS,
            serverSideEncryptionAwsKmsKeyId: 'arn:aws:kms:us-east-1:12345:key/123-123-1233'
        });
```

**Comment by iliapolo** [comment]
@mukeshchauhan 

> Instantiating BucketDeployment with provided Role.fromRoleArn have no affect

What do you mean have no affect? The way it should work is by adding an `AWS::IAM::Policy` resource that grants your role the necessary permissions to download from the staging bucket and upload to the destination bucket.

 Is that policy not being created? Are you getting errors during deployment?

**Comment by mukeshchauhan** [comment]
Because of corporate policies, creating roles at runtime is not allowed (which cdk is doing ) All roles are reviewed and approved before they can be used. For now we found a work around mentioned here. https://github.com/aws/aws-cdk/issues/3684

**Comment by otaviomacedo** [comment]
@mukeshchauhan, just to clarify a couple of things first: when you provide a role to `BucketDeployment`, the CDK will respect that and assign that role to the Lambda function. And, as @iliapolo pointed out, it will create a policy with the right permissions (`s3:GetObject*`, `s3:GetBucket*`, etc) and attach that policy to the function's role, regardless of where that role came from. 

Now, to your problem: I get it. It would make more sense if, when presented with a custom role, it didn't attach any policy to it. As part of its contract, `BucketDeployment` should assume that the role has all the right permissions already. But if we change that now, it will remove some permissions that users are (implicitly or explicitly) relying on.

**Comment by Georift** [comment]
@otaviomacedo we noticed this today at work. I also feel like providing a custom role should prevent a new one being made. I've been thinking but I can't think of a use case where adding extra permissions would make sense for a S3 Deployment. Given we're not in control of the code, what more permission could it need than the S3 access it's already making?

FWIW we worked around it with some disgusting patching of the bucket passed in to make `grantReadWrite` have no effect:
```typescript
Bucket.fromBucketArn(this, "nulledReadWrite", filesBucket.bucketArn).grantReadWrite = (() => {
	console.trace('nulled out grantReadWrite() will have no effect');
}) as any;
```

**Comment by otaviomacedo** [comment]
Ok, what I said above is not entirely correct. I wasn't aware that there is a boolean property, `mutable` that you can pass to `Role.fromRoleArn()`. If you set that property to `false`, the role will be left untouched and no additional policy or role will be created. I believe this solves the problem.

Feel free to reopen if you have additional questions.

**Comment by Georift** [comment]
Perfect thank you!

**Comment by spencer-robertson** [comment]
I want my Role to only be able to Put or Overwrite a specific file during deployment. However I am struggling to get the right minimum roles and getting an error that the python script to copy the zip file to the destination is failing. Would you be able to let me know what are the minimum roles I would need? I think this has something to do with not setting roles for the temporary assets folder that gets created?

My current setup is:
`const deployFileRole = new Role(this, "DeployFileRole", {
    assumedBy: new ServicePrincipal("lambda.amazonaws.com"),
});

deployFileRole.attachInlinePolicy(
    new Policy(this, "DeployFilesAccess", {
	statements: [
	    new PolicyStatement({
		effect: Effect.ALLOW,
		actions: [
			"s3:List*",
					"s3:PutObject*",
					"s3:GetObject*",
					"s3:GetBucket*",
				],
				resources: [`${filesBucket.bucketArn}/public/download.html`], // This is my goal here
			}),
			new PolicyStatement({
				effect: Effect.ALLOW,
				actions: [
					"s3:List*",
					"s3:PutObject*",
					"s3:GetObject*",
					"s3:GetBucket*",
				], 
				resources: [
					`${filesBucket.bucketArn}/public`,
					`${filesBucket.bucketArn}/public/*`,
				],
			}),
		],
	}),
);

new BucketDeployment(this, "deployDownloadFile", {
	sources: [
		Source.asset("./DeployFilesFolder", { exclude: ["*", "!download.html"] }),
	],
	destinationBucket: filesBucket,
	destinationKeyPrefix: "public",
	prune: false,
	role: deployFileRole.withoutPolicyUpdates(), // Does the same as setting mutable to false I believe
});


`

**Comment by spencer-robertson** [comment]
`test`

**Comment by BillyWitrock** [comment]
I also found, that if you are passing in a role, you can use the `withoutPolicyUpdates()` function to get a copy of the role that ignores any grants it is given, and pass that in instead.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#withoutwbrpolicywbrupdatesoptions
