### ISSUE TITLE
[cdk-pipelines] Dynamic branch pipeline support for CDK Pipelines

### ISSUE THREAD

**Issue by srethira** [aws/aws-cdk#9990]
Is it possible to enhance CDK Pipelines to support dynamic branch pipeline, similar to [this](https://aws.amazon.com/quickstart/architecture/serverless-cicd-for-enterprise/)? 

- Create a feature branch pipeline automatically when a new branch is created
- Delete a feature branch pipeline stack and application stack once PR is merged and the branch is deleted

**Comment by rix0rrr** [comment]
Interesting idea. Seems like a good use for a 3rd party construct library. Unlikely to be something we'll implement in core soon.

**Comment by srethira** [comment]
Any thoughts on the design how would I approach/implement this using 3rd party construct library ?
