### ISSUE TITLE
[RDS] Create a new cluster in an existing cluster subnet group

### ISSUE THREAD

**Issue by Sully8891** [aws/aws-cdk#9991]
I want to be able to create a new RDS cluster into an existing subnet group. Exactly the same as this [issue](https://github.com/aws/aws-cdk/issues/9241) but for RDS.

### Use Case

If a company doesn't allow it's DBAs to create subnets(as many do) then creating a new cluster into an existing subnet should be an option.

### Proposed Solution

When trying to implement the workaround mentioned in [Issue 9241](https://github.com/aws/aws-cdk/issues/9241) using escape hatches, it seems like we need to pass the parameter group physical id in the rds.CfnDBClusterProps when creating the rds.CfnDBCluster.  Which don't seem to exist until the actual deployment. Do we need to do this in two separate deployment steps with two stacks?

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hello @Sully8891 ,

thanks for opening the issue. The problem of referencing things that are only known at deploy time is to use CloudFormation attributes. In your case, it looks similar to:

```ts
const paramterGroup = new rds.CfnClusterParameterGroup(this, 'ParamGroup', {
  // ....
});
new rds. CfnDBCluster(this, 'Cluster', {
  // ...
  dbClusterParameterGroupName: parmeterGroup.ref,
});
```

Hope this helps!

Thanks,
Adam

**Comment by Sully8891** [comment]
Thanks for the help @skinny85! That's very helpful!

Getting this feature added natively would still be much appreciated.

**Comment by skinny85** [comment]
It already is 🙂 https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html#starting-a-clustered-database

**Comment by njlynch** [comment]
@skinny85  - Just to clarify, I don't believe we support this yet; this is the equivalent of https://github.com/aws/aws-cdk/issues/9241 for RDS. We need to create an L2 for AWS::RDS::DBSubnetGroup and then provide an option for customers to use that with either a [cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-dbsubnetgroupname) or [instance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbsubnetgroupname).

**Comment by skinny85** [comment]
Ah, got it. Thanks @njlynch ; I misunderstood what the original ask was.

Cool, let's add it to the GA milestone then!
