### ISSUE TITLE
[aws-lambda] Add ability to assign DatabaseProxy to lambda

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#9993]
Add ability to assign DatabaseProxy to lambda, currently there does not seem to be a way to do this through CloudFormation or the CDK, only through the AWS Console.

### Use Case

I currently have over 50 lambdas that are deployed with the cdk and I want to add a database proxy to all of them. As my lambda count continue to grow I will need to add the proxy manually to each one as they are created. This leaves the possibility to miss one while creating new lambdas.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Can you explain what you mean by assigning database proxy to lambda? 

Is this a new feature that's available in Lambda, or do you simply mean creating an RDS database proxy and configuring your lambda functions to point to the proxy endpoint?

**Comment by seawatts** [comment]
@nija-at I might be miss understanding how the DatabaseProxy feature works. However, when I am in the AWS console there is a section where I can assign a DatabaseProxy to the lambda. I'm not sure what it is doing under the hood, other than allowing the Role permissions to connect to the proxy. But if it is doing something else other than just updating the Role, it would be nice to be able to perform the same action that you can do through the AWS Console within the CDK

**Comment by nija-at** [comment]
I believe all of these features already exist in the CDK. Once a database proxy is created using the [RDS construct library](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseProxy.html) in the same VPC as the lambda function, the function should be able to connect to the proxy.

If you find any gaps, please report back with a more specific issue.

**Comment by seawatts** [comment]
@nija-at Do you have an example of how to do this? I am not seeing it show up in the lambda function in the screenshot I provided above. 

Also is there a way to give the lambda permissions or do I need to manually attach a policy to the role?
e.x.
```
 function.role.addToPrincipalPolicy(
      new PolicyStatement({
        actions: ['rds-db:connect'],
        effect: Effect.ALLOW,
        resources: [`arn:aws:rds-db:us-east-1:41705XXXXXXX:dbuser:prx-071838XXXXXXXXX/*`],
      }),
    );
```

**Comment by nija-at** [comment]
It seems for the moment, you have to do something like what you have. I believe we're missing a `grantConnect()` API on the proxy. This should provide an API such as along the lines of `proxy.grantConnect(function)`.

I've opened an issue here on your behalf - https://github.com/aws/aws-cdk/issues/10133
