### ISSUE TITLE
[cloudfront] Distribution construct does not add edgelambda.amazonaws.com service principal to associated Lambda function roles

### ISSUE THREAD

**Issue by iliana** [aws/aws-cdk#9998]
#5180 reported an issue where the edgelambda.amazonaws.com service principal was not present on automatically-generated IAM roles for Lambda functions associated with a `CloudFrontWebDistribution` construct. #5191 fixed this.

The newer `Distribution` construct lacks this behavior, and I hit the same error as reported in #5180. I had to work around by manually generating a role and adding the appropriate two service principals.

### Environment

  - **CLI Version      :** 1.60.0 (build 8e3f53a)
  - **Framework Version:** 1.60.0
  - **Node.js Version:**  v12.16.3
  - **OS               :** Linux
  - **Language (Version):**  TypeScript (4.0.2)

--- 

This is :bug: Bug Report

**Comment by sh4m1l65** [comment]
I ran into the same issue, but couldn't even successfully workaround: https://stackoverflow.com/questions/63610300/how-to-create-a-valid-role-for-edge-lambda
